//! Invariant declaration emission — closes the silent-drop gap on
//! `invariant <name>(<scope>) @<mode> { <predicate> }` declarations
//! flagged in the 2026-04-26 spec audit (`docs/spec/dsl.md` §2.6
//! callout).
//!
//! # What this emits
//!
//! For each [`InvariantIR`] in the [`Compilation`], this synthesises
//! a Rust function `pub fn check_<name>(...) -> Vec<Violation>` that
//! evaluates the resolved predicate against host-side readback of the
//! materialized-view storage referenced by the predicate. Per-fixture
//! runtime crates (`predator_prey_runtime`, …) call these via a
//! convenience `pub fn check_invariants(&mut self) -> Vec<Violation>`
//! after each tick; a non-empty return is a deterministic, replayable
//! violation report.
//!
//! # Supported predicate shape (initial scope)
//!
//! The emitter today supports the **per-agent scalar-view-bounded**
//! shape:
//!
//! ```text
//! invariant <name>(<binder>: Agent) @<mode> {
//!     <view_name>(<binder>) <op> <literal_f32>
//! }
//! ```
//!
//! where `<view_name>` is a `@materialized` view returning `f32` and
//! `<op>` ∈ `{<, <=, >, >=, ==, !=}`. The check iterates the view's
//! readback slice once and returns one [`Violation`] per slot whose
//! value violates the comparator. The `predator_prey_min.sim`
//! `bounded_kill_count` invariant is the canonical fit.
//!
//! Predicates that don't match this shape (multi-arg scope, nested
//! field access, quantifiers, view returning vec3, …) are skipped
//! with a `// SKIP: <reason>` comment — they don't compile to a
//! check, so the gap is visible in the emitted file rather than
//! silently dropped at the compiler entry point. Future plans can
//! extend the supported shape table.
//!
//! # Why a separate function (not `emit_cg_program`)
//!
//! Invariants don't correspond to CG ops, kernels, or the schedule —
//! they're host-side checks over view-storage readback. They live
//! outside [`crate::cg::CgProgram`] (which carries only kernel-bound
//! IR), so the emit pass takes the [`Compilation`] directly. The
//! companion entry point [`emit_cg_program_with_invariants`] wraps
//! [`super::program::emit_cg_program`] and injects the synthesized
//! `invariants.rs` into the artifact map for callers (per-fixture
//! `build.rs`) that want one-stop emission.

use std::fmt::Write as _;

use dsl_ast::ast::{BinOp, InvariantMode};
use dsl_ast::ir::{Compilation, IrExpr, IrType, InvariantIR, ViewKind};

use super::program::{emit_cg_program, EmittedArtifacts, ProgramEmitError};
use crate::cg::program::CgProgram;
use crate::cg::schedule::synthesis::ComputeSchedule;

/// Synthesise the per-fixture `invariants.rs` source. Returns `None`
/// when the compilation declares no invariants (so callers can skip
/// the artifact entirely instead of writing an empty file).
pub fn synthesize_invariants(comp: &Compilation) -> Option<String> {
    if comp.invariants.is_empty() {
        return None;
    }

    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Source: each `invariant <name>(<scope>) @<mode> { <predicate> }`\n");
    out.push_str("// declaration in the fixture's .sim file. Regenerate by editing\n");
    out.push_str("// the .sim file and rebuilding.\n\n");
    out.push_str("/// Single invariant violation. `tick` is filled by the runtime caller\n");
    out.push_str("/// (the compiler doesn't know the runtime tick counter); `agent` is\n");
    out.push_str("/// the slot index whose value violated the predicate.\n");
    out.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    out.push_str("pub struct Violation {\n");
    out.push_str("    pub invariant: &'static str,\n");
    out.push_str("    pub agent:     u32,\n");
    out.push_str("    pub value:     f32,\n");
    out.push_str("    pub bound:     f32,\n");
    out.push_str("    pub mode:      Mode,\n");
    out.push_str("}\n\n");
    out.push_str("/// Mirror of `dsl_ast::ast::InvariantMode`. Decides how the runtime\n");
    out.push_str("/// surfaces a violation: `DebugOnly` is suppressible in release, the\n");
    out.push_str("/// other two are always live.\n");
    out.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq)]\n");
    out.push_str("pub enum Mode {\n");
    out.push_str("    Static,\n");
    out.push_str("    Runtime,\n");
    out.push_str("    DebugOnly,\n");
    out.push_str("}\n\n");

    for inv in &comp.invariants {
        emit_invariant_check(comp, inv, &mut out);
        out.push('\n');
    }

    Some(out)
}

/// Wrap [`emit_cg_program`] so callers (per-fixture `build.rs`) get the
/// `invariants.rs` artifact alongside the kernel + cross-cutting set
/// without duplicating the emit-and-merge boilerplate. Existing
/// callers of [`emit_cg_program`] are untouched; they get the same
/// artifact set (no `invariants.rs`, since invariants live outside
/// [`CgProgram`]).
pub fn emit_cg_program_with_invariants(
    schedule: &ComputeSchedule,
    prog: &CgProgram,
    comp: &Compilation,
) -> Result<EmittedArtifacts, ProgramEmitError> {
    let mut artifacts = emit_cg_program(schedule, prog)?;
    if let Some(src) = synthesize_invariants(comp) {
        artifacts.rust_files.insert("invariants.rs".to_string(), src);
    }
    Ok(artifacts)
}

// ---------------------------------------------------------------------------
// Per-invariant emit
// ---------------------------------------------------------------------------

fn emit_invariant_check(comp: &Compilation, inv: &InvariantIR, out: &mut String) {
    let mode_str = match inv.mode {
        InvariantMode::Static => "Mode::Static",
        InvariantMode::Runtime => "Mode::Runtime",
        InvariantMode::DebugOnly => "Mode::DebugOnly",
    };

    match classify(comp, inv) {
        InvariantShape::ScalarViewBounded { view_name, op, bound } => {
            let _ = writeln!(
                out,
                "/// Invariant `{name}` (mode = {mode:?}) — \
                 derived from a per-agent scalar view comparison: \
                 `{view}(agent) {op} {bound:?}`.",
                name = inv.name,
                mode = inv.mode,
                view = view_name,
                op = op.symbol(),
                bound = bound,
            );
            let _ = writeln!(
                out,
                "pub fn check_{name}(view_storage: &[f32]) -> Vec<Violation> {{",
                name = inv.name,
            );
            let _ = writeln!(out, "    let mut out = Vec::new();");
            let _ = writeln!(out, "    for (slot, &value) in view_storage.iter().enumerate() {{");
            let _ = writeln!(
                out,
                "        let bound: f32 = {bound:?};",
                bound = bound,
            );
            let _ = writeln!(
                out,
                "        let violated = !({lhs} {sym} bound);",
                lhs = "value",
                sym = op.symbol(),
            );
            let _ = writeln!(out, "        if violated {{");
            let _ = writeln!(out, "            out.push(Violation {{");
            let _ = writeln!(out, "                invariant: \"{name}\",", name = inv.name);
            let _ = writeln!(out, "                agent:     slot as u32,");
            let _ = writeln!(out, "                value,");
            let _ = writeln!(out, "                bound,");
            let _ = writeln!(out, "                mode:      {mode_str},");
            let _ = writeln!(out, "            }});");
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "    out");
            let _ = writeln!(out, "}}");
        }
        InvariantShape::Skipped(reason) => {
            let _ = writeln!(
                out,
                "// SKIP `{name}`: predicate shape not yet supported by emit — {reason}.",
                name = inv.name,
                reason = reason,
            );
            let _ = writeln!(
                out,
                "// (Parses + resolves cleanly; no host-side check generated. Extend \
                 `cg::emit::invariants::classify` to lift this skip.)",
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Predicate-shape classifier
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq)]
enum CmpOp {
    Lt,
    Le,
    Gt,
    Ge,
    Eq,
    Ne,
}

impl CmpOp {
    fn from_binop(b: BinOp) -> Option<Self> {
        match b {
            BinOp::Lt => Some(Self::Lt),
            BinOp::LtEq => Some(Self::Le),
            BinOp::Gt => Some(Self::Gt),
            BinOp::GtEq => Some(Self::Ge),
            BinOp::Eq => Some(Self::Eq),
            BinOp::NotEq => Some(Self::Ne),
            _ => None,
        }
    }

    fn symbol(self) -> &'static str {
        match self {
            Self::Lt => "<",
            Self::Le => "<=",
            Self::Gt => ">",
            Self::Ge => ">=",
            Self::Eq => "==",
            Self::Ne => "!=",
        }
    }
}

enum InvariantShape<'a> {
    /// `<view>(<binder>) <op> <literal>` over a single Agent-scoped
    /// binder, where the view is `@materialized` and returns `f32`.
    ScalarViewBounded {
        view_name: &'a str,
        op: CmpOp,
        bound: f32,
    },
    /// Reason the predicate doesn't fit the supported shape. Surfaced
    /// in the emitted file as a `// SKIP` comment so authors see the
    /// gap.
    Skipped(&'static str),
}

fn classify<'a>(comp: &'a Compilation, inv: &InvariantIR) -> InvariantShape<'a> {
    // Today the only supported scope is a single Agent-typed binder.
    // (Spec example: `invariant bounded_kill_count(a: Agent) @debug_only`.)
    if inv.scope.len() != 1 {
        return InvariantShape::Skipped(
            "only single-binder per-Agent scopes are supported today",
        );
    }
    let binder_local = inv.scope[0].local;

    let (op, lhs, rhs) = match &inv.predicate.kind {
        IrExpr::Binary(b, l, r) => match CmpOp::from_binop(*b) {
            Some(op) => (op, l.as_ref(), r.as_ref()),
            None => {
                return InvariantShape::Skipped(
                    "top-level operator must be a comparator (<, <=, >, >=, ==, !=)",
                );
            }
        },
        _ => {
            return InvariantShape::Skipped(
                "predicate must be a single comparator at top level",
            );
        }
    };

    // RHS must be a numeric literal (the bound).
    let bound = match &rhs.kind {
        IrExpr::LitFloat(f) => *f as f32,
        IrExpr::LitInt(i) => *i as f32,
        _ => {
            return InvariantShape::Skipped(
                "RHS of the comparator must be a numeric literal",
            );
        }
    };

    // LHS must be `<view>(<binder>)` where view is `@materialized`
    // returning `f32` and the call's only arg is the scope binder.
    let (view_ref, args) = match &lhs.kind {
        IrExpr::ViewCall(view_ref, args) => (*view_ref, args),
        _ => {
            return InvariantShape::Skipped(
                "LHS must be a ViewCall (e.g. `kill_count(a)`)",
            );
        }
    };
    let view_idx = view_ref.0 as usize;
    let view = match comp.views.get(view_idx) {
        Some(v) => v,
        None => return InvariantShape::Skipped("view ref out of range (resolver bug?)"),
    };
    if !matches!(view.kind, ViewKind::Materialized(_)) {
        return InvariantShape::Skipped(
            "view must be `@materialized` (lazy views aren't host-readback today)",
        );
    }
    if !matches!(view.return_ty, IrType::F32) {
        return InvariantShape::Skipped("view return type must be f32");
    }
    if args.len() != 1 {
        return InvariantShape::Skipped("view call must have exactly one argument");
    }
    let arg = &args[0].value;
    let local_ref = match &arg.kind {
        IrExpr::Local(local_ref, _) => *local_ref,
        _ => {
            return InvariantShape::Skipped(
                "view-call argument must be the scope binder (no expressions yet)",
            );
        }
    };
    if local_ref != binder_local {
        return InvariantShape::Skipped(
            "view-call argument must be the invariant's scope binder",
        );
    }

    InvariantShape::ScalarViewBounded {
        view_name: view.name.as_str(),
        op,
        bound,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use dsl_ast::resolve::resolve;

    fn compile(src: &str) -> Compilation {
        let p = crate::parse(src).expect("parse");
        resolve(p).expect("resolve")
    }

    #[test]
    fn empty_compilation_emits_nothing() {
        let comp = Compilation::default();
        assert!(synthesize_invariants(&comp).is_none());
    }

    #[test]
    fn scalar_view_bounded_emits_check_fn() {
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
@materialized(on_event = [Tick])
view kill_count(by: Agent) -> f32 {
    initial: 0.0,
    on Tick { } { self += 1.0 }
}
invariant bounded_kc(a: Agent) @debug_only {
    kill_count(a) < 1000.0
}
"#;
        let comp = compile(src);
        let out = synthesize_invariants(&comp).expect("non-empty");
        assert!(
            out.contains("pub fn check_bounded_kc(view_storage: &[f32]) -> Vec<Violation>"),
            "expected per-invariant check fn:\n{out}"
        );
        assert!(
            out.contains("Mode::DebugOnly"),
            "expected DebugOnly mode literal:\n{out}"
        );
    }

    #[test]
    fn unsupported_shape_emits_skip_comment() {
        // Predicate without a top-level comparator → SKIP.
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
invariant always_true() @runtime {
    true
}
"#;
        let comp = compile(src);
        let out = synthesize_invariants(&comp).expect("non-empty");
        assert!(
            out.contains("// SKIP `always_true`"),
            "expected SKIP comment for unsupported shape:\n{out}"
        );
    }
}
