//! Metric declaration emission — closes the silent-drop gap on
//! `metric { metric <name> = <expr> [...] }` declarations flagged in
//! the 2026-04-26 spec audit (`docs/spec/dsl.md` §2.6 callout) and
//! tracked in the 2026-05-03 verb/probe/metric plan
//! (`docs/superpowers/plans/2026-05-03-verb-probe-metric-emit.md`,
//! Slice C).
//!
//! # What this emits
//!
//! For each [`MetricIR`] in the [`Compilation`], this synthesises a
//! Rust struct field on the per-fixture `MetricsSink` plus a
//! `record_<name>(&mut self, value: f32)` setter the runtime calls
//! each tick with the freshly-evaluated metric value. A companion
//! `record_tick(&mut self, world_tick: u64)` driver fires the metrics
//! whose value source is `world.tick` automatically — those metrics
//! the runtime doesn't have to know about by name. Metrics whose
//! source is a constant or world.tick are auto-driven; others emit
//! per-name setters the runtime invokes manually with whatever scalar
//! it computes.
//!
//! # Supported value shape (initial scope)
//!
//! The emitter today supports the **wrapped-scalar shape**:
//!
//! ```text
//! metric <name> = <kind>(<inner>) [...]
//! ```
//!
//! where `<kind>` is one of `gauge` / `counter` / `histogram` (parsed
//! as `UnresolvedCall`, since these are part of the metric grammar
//! per spec §7.3 not stdlib functions; `MetricKind` lift is
//! deliberately NOT performed here — see plan's open questions §C
//! "emit-side recognition is simpler"), and `<inner>` is one of:
//!
//! - A numeric literal (`f32` / `i64`).
//! - The `world.tick` namespace field (resolves as
//!   `NamespaceField { ns: World, field: "tick", ty: U64 }`).
//!
//! Both literal and `world.tick` sources let the emitter generate a
//! self-driving `record_tick` that fires every metric automatically.
//! Authoring shapes the emitter doesn't yet recognise (aggregates
//! like `count(e in events.this_tick where ...)`, view calls,
//! quantifiers, conditioned_on / alert_when bodies) get a
//! per-metric `record_<name>` setter the runtime fills in, plus a
//! `// SKIP <reason>` comment so authors see the gap at build time
//! instead of runtime.
//!
//! # Why a separate function (not `emit_cg_program`)
//!
//! Metrics, like invariants, don't correspond to CG ops, kernels, or
//! the schedule — they're host-side telemetry over runtime state.
//! They live outside [`crate::cg::CgProgram`] (which carries only
//! kernel-bound IR), so the emit pass takes the [`Compilation`]
//! directly. The companion entry point
//! [`emit_cg_program_with_invariants_and_metrics`] wraps
//! [`super::invariants::emit_cg_program_with_invariants`] and injects
//! the synthesized `metrics.rs` into the artifact map alongside the
//! `invariants.rs` artifact.

use std::fmt::Write as _;

use dsl_ast::ir::{Compilation, IrExpr, MetricIR, NamespaceId};

use super::invariants::emit_cg_program_with_invariants;
use super::program::{EmittedArtifacts, ProgramEmitError};
use crate::cg::program::CgProgram;
use crate::cg::schedule::synthesis::ComputeSchedule;

/// Synthesise the per-fixture `metrics.rs` source. Returns `None` when
/// the compilation declares no metrics (so callers can skip the
/// artifact entirely instead of writing an empty file).
pub fn synthesize_metrics(comp: &Compilation) -> Option<String> {
    if comp.metrics.is_empty() {
        return None;
    }

    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Source: each `metric <name> = <expr> [window N] [emit_every N]\n");
    out.push_str("//          [conditioned_on EXPR] [alert when EXPR]` declaration in\n");
    out.push_str("// the fixture's .sim file. Regenerate by editing the .sim file and\n");
    out.push_str("// rebuilding.\n\n");

    out.push_str("/// Monotonic counter — accumulates a sum + sample count across\n");
    out.push_str("/// every recorded value. The sum is f64 to keep precision over\n");
    out.push_str("/// long runs; per-sample values stay f32 to match the metric IR's\n");
    out.push_str("/// scalar value type. `count` is the number of recorded samples\n");
    out.push_str("/// (not the cumulative event count fed into a `count(...)` body).\n");
    out.push_str("#[derive(Clone, Debug, Default)]\n");
    out.push_str("pub struct Counter {\n");
    out.push_str("    pub count: u64,\n");
    out.push_str("    pub total: f64,\n");
    out.push_str("}\n");
    out.push_str("impl Counter {\n");
    out.push_str("    pub fn record(&mut self, value: f32) {\n");
    out.push_str("        self.count += 1;\n");
    out.push_str("        self.total += value as f64;\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("/// Last-write-wins gauge — tracks the most recent recorded value\n");
    out.push_str("/// plus the total number of samples for sanity-checking. `last` is\n");
    out.push_str("/// `None` until the first `record()` call.\n");
    out.push_str("#[derive(Clone, Debug, Default)]\n");
    out.push_str("pub struct Gauge {\n");
    out.push_str("    pub last: Option<f32>,\n");
    out.push_str("    pub count: u64,\n");
    out.push_str("}\n");
    out.push_str("impl Gauge {\n");
    out.push_str("    pub fn record(&mut self, value: f32) {\n");
    out.push_str("        self.last = Some(value);\n");
    out.push_str("        self.count += 1;\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("/// Per-sample histogram — records every value into a `Vec`. The\n");
    out.push_str("/// runtime can compute bucketed views (max_bin etc.) off the raw\n");
    out.push_str("/// samples; this emit pass keeps the storage shape simple so the\n");
    out.push_str("/// per-tick record path is allocation-free after the initial Vec\n");
    out.push_str("/// capacity is sized.\n");
    out.push_str("#[derive(Clone, Debug, Default)]\n");
    out.push_str("pub struct Histogram {\n");
    out.push_str("    pub samples: Vec<f32>,\n");
    out.push_str("}\n");
    out.push_str("impl Histogram {\n");
    out.push_str("    pub fn record(&mut self, value: f32) {\n");
    out.push_str("        self.samples.push(value);\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // MetricsSink struct — one field per metric, of the type matching
    // the metric's wrapper kind (or `Gauge` as the default for bare
    // scalars / unsupported shapes). Every field is `pub` so tests
    // and runtime introspection can read the accumulated values
    // directly without a per-field accessor proliferation.
    out.push_str("/// Per-fixture metrics sink. One field per `metric` declaration\n");
    out.push_str("/// in the source `.sim` file. Construct via `Default::default()`\n");
    out.push_str("/// and feed values via `record_tick(world_tick)` for the auto-\n");
    out.push_str("/// driven metrics, or per-metric `record_<name>(value)` setters\n");
    out.push_str("/// for the ones whose value the runtime computes itself.\n");
    out.push_str("#[derive(Clone, Debug, Default)]\n");
    out.push_str("pub struct MetricsSink {\n");
    for m in &comp.metrics {
        let kind_name = match classify(m).kind {
            MetricKind::Counter => "Counter",
            MetricKind::Gauge | MetricKind::Unknown => "Gauge",
            MetricKind::Histogram => "Histogram",
        };
        let _ = writeln!(out, "    pub {name}: {ty},", name = m.name, ty = kind_name);
    }
    out.push_str("}\n\n");

    out.push_str("impl MetricsSink {\n");

    // record_tick — auto-drives the metrics whose value source the
    // emitter recognises (Constant / WorldTick). Metrics whose
    // source falls into the Skipped / Computed bucket get a
    // per-metric setter and are NOT touched here; the runtime drives
    // them.
    out.push_str("    /// Auto-drive every metric whose value source the compiler\n");
    out.push_str("    /// recognises. Call this from the per-fixture runtime once per\n");
    out.push_str("    /// tick; the runtime is also responsible for the per-metric\n");
    out.push_str("    /// `record_<name>(value)` setters for metrics whose source is\n");
    out.push_str("    /// computed host-side (those carry a `// SKIP` annotation in\n");
    out.push_str("    /// the per-metric setter docs).\n");
    out.push_str("    pub fn record_tick(&mut self, world_tick: u64) {\n");
    let mut auto_driven_any = false;
    for m in &comp.metrics {
        let cls = classify(m);
        let driver_value = match (&cls.source, &cls.kind) {
            (MetricSource::Constant(v), _) => Some(format!("{v:?}_f32")),
            (MetricSource::WorldTick, _) => Some("world_tick as f32".to_string()),
            _ => None,
        };
        if let (Some(value_expr), kind) = (driver_value, cls.kind) {
            // Honor `emit_every`: only record on ticks where
            // `world_tick % emit_every == 0`. The default is every
            // tick (`emit_every = 1`) when the modifier is absent.
            let emit_every = m.emit_every.unwrap_or(1).max(1);
            if matches!(kind, MetricKind::Counter | MetricKind::Gauge | MetricKind::Histogram | MetricKind::Unknown) {
                auto_driven_any = true;
                if emit_every == 1 {
                    let _ = writeln!(
                        out,
                        "        self.{name}.record({value});",
                        name = m.name,
                        value = value_expr,
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "        if world_tick % {modulus} == 0 {{ self.{name}.record({value}); }}",
                        name = m.name,
                        modulus = emit_every,
                        value = value_expr,
                    );
                }
            }
        }
    }
    if !auto_driven_any {
        out.push_str("        // No auto-driven metrics in this fixture; every metric's\n");
        out.push_str("        // value source is computed host-side and recorded via the\n");
        out.push_str("        // per-metric `record_<name>` setters below.\n");
        out.push_str("        let _ = world_tick;\n");
    }
    out.push_str("    }\n\n");

    // Per-metric setters. Auto-driven metrics still get a setter so
    // hand-written tests + alternative drivers can override the
    // auto-tick behaviour; computed metrics REQUIRE the setter
    // because record_tick won't touch them.
    for m in &comp.metrics {
        emit_metric_setter(m, &mut out);
        out.push('\n');
    }

    out.push_str("}\n");

    Some(out)
}

/// Wrap [`emit_cg_program_with_invariants`] so callers (per-fixture
/// `build.rs`) get the `metrics.rs` artifact alongside the
/// `invariants.rs` + kernel + cross-cutting set without duplicating
/// the emit-and-merge boilerplate. Existing callers of
/// [`emit_cg_program_with_invariants`] are untouched; they get the
/// same artifact set (no `metrics.rs`, since metrics live outside the
/// schedule + invariants inject independently).
pub fn emit_cg_program_with_invariants_and_metrics(
    schedule: &ComputeSchedule,
    prog: &CgProgram,
    comp: &Compilation,
) -> Result<EmittedArtifacts, ProgramEmitError> {
    let mut artifacts = emit_cg_program_with_invariants(schedule, prog, comp)?;
    if let Some(src) = synthesize_metrics(comp) {
        artifacts.rust_files.insert("metrics.rs".to_string(), src);
    }
    Ok(artifacts)
}

// ---------------------------------------------------------------------------
// Per-metric emit
// ---------------------------------------------------------------------------

fn emit_metric_setter(m: &MetricIR, out: &mut String) {
    let cls = classify(m);
    let kind_str = match cls.kind {
        MetricKind::Counter => "counter",
        MetricKind::Gauge => "gauge",
        MetricKind::Histogram => "histogram",
        MetricKind::Unknown => "gauge (default for unwrapped value)",
    };
    let _ = writeln!(
        out,
        "    /// Setter for metric `{name}` ({kind_str}). The runtime\n\
         \x20   /// calls this each tick with the freshly-evaluated value;\n\
         \x20   /// `record_tick` may also drive it automatically when the\n\
         \x20   /// metric's source is recognised by the emitter.",
        name = m.name,
        kind_str = kind_str,
    );
    if let MetricSource::Skipped(reason) = &cls.source {
        let _ = writeln!(
            out,
            "    // SKIP `{name}`: value-source shape not yet recognised — {reason}.\n\
             \x20   // (Parses + resolves cleanly; auto-drive disabled. The runtime\n\
             \x20   //  must call `record_{name}(value)` itself with whatever scalar\n\
             \x20   //  it computes for this metric.)",
            name = m.name,
            reason = reason,
        );
    }
    let _ = writeln!(
        out,
        "    pub fn record_{name}(&mut self, value: f32) {{",
        name = m.name,
    );
    let _ = writeln!(out, "        self.{name}.record(value);", name = m.name);
    let _ = writeln!(out, "    }}");
}

// ---------------------------------------------------------------------------
// Value-shape classifier
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum MetricKind {
    Counter,
    Gauge,
    Histogram,
    /// Bare scalar (no `gauge(...)` / `counter(...)` / `histogram(...)`
    /// wrapper). Defaults to `Gauge` semantics in the sink.
    Unknown,
}

#[derive(Clone, Debug)]
enum MetricSource {
    /// Compile-time constant `f32` — `record_tick` drives the metric
    /// with this value every tick.
    Constant(f32),
    /// `world.tick` — `record_tick` drives the metric with the runtime
    /// tick counter.
    WorldTick,
    /// Recognised wrapper but the inner expression isn't a
    /// constant or `world.tick`. The emitter still creates a per-metric
    /// setter the runtime fills in, but `record_tick` doesn't drive it
    /// automatically.
    #[allow(dead_code)]
    Computed,
    /// The wrapper itself doesn't fit a recognised shape. Surfaces in
    /// the emitted file as a `// SKIP` comment so authors see the gap.
    Skipped(&'static str),
}

#[derive(Clone, Debug)]
struct MetricClass {
    kind: MetricKind,
    source: MetricSource,
}

fn classify(m: &MetricIR) -> MetricClass {
    // Strip the optional gauge/counter/histogram wrapper. Per spec
    // §7.3 these are part of the metric grammar (not stdlib calls)
    // but parse as UnresolvedCall today — the `MetricKind` lift to a
    // real enum on the IR is a deliberate follow-up. Until then,
    // emit-side recognition is simpler than a parse-time change.
    let (kind, inner_expr) = match &m.value.kind {
        IrExpr::UnresolvedCall(name, args) if args.len() == 1 => {
            let kind = match name.as_str() {
                "gauge" => Some(MetricKind::Gauge),
                "counter" => Some(MetricKind::Counter),
                "histogram" => Some(MetricKind::Histogram),
                _ => None,
            };
            match kind {
                Some(k) => (k, &args[0].value),
                None => {
                    return MetricClass {
                        kind: MetricKind::Unknown,
                        source: MetricSource::Skipped(
                            "wrapper-form value must be `gauge` / `counter` / `histogram`",
                        ),
                    };
                }
            }
        }
        IrExpr::UnresolvedCall(_, _) => {
            return MetricClass {
                kind: MetricKind::Unknown,
                source: MetricSource::Skipped(
                    "wrapper-form must take exactly one argument",
                ),
            };
        }
        // Bare scalar: unwrapped value, default to Gauge semantics.
        _ => (MetricKind::Unknown, &m.value),
    };

    let source = match &inner_expr.kind {
        IrExpr::LitFloat(f) => MetricSource::Constant(*f as f32),
        IrExpr::LitInt(i) => MetricSource::Constant(*i as f32),
        IrExpr::NamespaceField { ns, field, .. }
            if *ns == NamespaceId::World && field == "tick" =>
        {
            MetricSource::WorldTick
        }
        IrExpr::NamespaceField { .. } => MetricSource::Skipped(
            "value source must be a literal or `world.tick` (other namespace fields not yet wired)",
        ),
        IrExpr::ViewCall(_, _) => MetricSource::Skipped(
            "view-call value source not yet wired (needs an aggregation strategy across slots)",
        ),
        IrExpr::BuiltinCall(_, _) => MetricSource::Skipped(
            "builtin-call (count / mean / sum) value source not yet wired",
        ),
        IrExpr::Quantifier { .. } | IrExpr::Fold { .. } => MetricSource::Skipped(
            "quantifier / fold value source not yet wired",
        ),
        _ => MetricSource::Skipped(
            "value source must be a literal, `world.tick`, or one of the recognised aggregate forms",
        ),
    };

    MetricClass { kind, source }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use dsl_ast::resolve::resolve;

    fn compile(src: &str) -> Compilation {
        let p = crate::parse(src).expect("parse");
        resolve(p).expect("resolve")
    }

    #[test]
    fn empty_compilation_emits_nothing() {
        let comp = Compilation::default();
        assert!(synthesize_metrics(&comp).is_none());
    }

    #[test]
    fn gauge_world_tick_emits_auto_driver() {
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
metric {
  metric tick_gauge = gauge(world.tick) emit_every 1
}
"#;
        let comp = compile(src);
        let out = synthesize_metrics(&comp).expect("non-empty");
        assert!(
            out.contains("pub tick_gauge: Gauge,"),
            "expected MetricsSink field for gauge:\n{out}"
        );
        assert!(
            out.contains("self.tick_gauge.record(world_tick as f32);"),
            "expected auto-drive line for world.tick gauge:\n{out}"
        );
        assert!(
            out.contains("pub fn record_tick"),
            "expected record_tick driver fn:\n{out}"
        );
    }

    #[test]
    fn counter_constant_emits_constant_driver() {
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
metric {
  metric ticks_seen = counter(1.0) emit_every 1
}
"#;
        let comp = compile(src);
        let out = synthesize_metrics(&comp).expect("non-empty");
        assert!(
            out.contains("pub ticks_seen: Counter,"),
            "expected MetricsSink field for counter:\n{out}"
        );
        assert!(
            out.contains("self.ticks_seen.record(1.0_f32);"),
            "expected auto-drive line with constant 1.0:\n{out}"
        );
    }

    #[test]
    fn histogram_emit_every_gates_record() {
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
metric {
  metric tick_hist = histogram(world.tick) emit_every 10
}
"#;
        let comp = compile(src);
        let out = synthesize_metrics(&comp).expect("non-empty");
        assert!(
            out.contains("pub tick_hist: Histogram,"),
            "expected Histogram-typed field:\n{out}"
        );
        assert!(
            out.contains("if world_tick % 10 == 0 {"),
            "expected emit_every gating in record_tick:\n{out}"
        );
    }

    #[test]
    fn unsupported_value_shape_emits_skip_comment() {
        // Wrapper with two args (recognised wrapper name but wrong
        // arity) — must produce a SKIP plus a setter.
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
metric {
  metric two_arg_gauge = gauge(world.tick, 1.0)
}
"#;
        let comp = compile(src);
        let out = synthesize_metrics(&comp).expect("non-empty");
        assert!(
            out.contains("// SKIP `two_arg_gauge`"),
            "expected SKIP comment for wrong-arity wrapper:\n{out}"
        );
        assert!(
            out.contains("pub fn record_two_arg_gauge"),
            "even SKIPped metrics must expose a manual setter:\n{out}"
        );
    }

    #[test]
    fn unsupported_inner_expr_emits_skip_comment() {
        // Recognised wrapper around a binary expression — wrapper
        // shape is fine but the inner expr's source isn't auto-driveable
        // (not a literal, not world.tick). Expect SKIP + setter.
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
metric {
  metric tick_plus_one = gauge(world.tick + 1)
}
"#;
        let comp = compile(src);
        let out = synthesize_metrics(&comp).expect("non-empty");
        assert!(
            out.contains("// SKIP `tick_plus_one`"),
            "expected SKIP comment for non-source-expr inner:\n{out}"
        );
        assert!(
            out.contains("pub fn record_tick_plus_one"),
            "even SKIPped metrics must expose a manual setter:\n{out}"
        );
        // The auto-drive path must NOT fire for this metric — the
        // emitted record_tick driver would otherwise reference the
        // metric's `record(world_tick as f32)` setter (or a constant
        // form). The per-metric setter `record_tick_plus_one` calls
        // `self.tick_plus_one.record(value)` (note `value`, not
        // `world_tick as f32`); the auto-drive call would carry a
        // different argument. Asserting the auto-drive call shape is
        // absent proves auto-drive correctly skipped this metric.
        assert!(
            !out.contains("self.tick_plus_one.record(world_tick as f32)"),
            "auto-drive must skip non-recognised inner exprs:\n{out}"
        );
    }

    #[test]
    fn missing_emit_every_defaults_to_every_tick() {
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
metric {
  metric always = gauge(world.tick)
}
"#;
        let comp = compile(src);
        let out = synthesize_metrics(&comp).expect("non-empty");
        // No `if world_tick % N == 0` gate; just the bare record line.
        assert!(
            out.contains("self.always.record(world_tick as f32);"),
            "expected unconditional record line for missing emit_every:\n{out}"
        );
        assert!(
            !out.contains("if world_tick %"),
            "must not emit a gate when emit_every is absent:\n{out}"
        );
    }
}
