//! Probe declaration emission — closes the silent-drop gap on
//! `probe <name> { scenario / seed / seeds / ticks / tolerance / assert
//! { … } }` declarations flagged in the 2026-04-26 spec audit
//! (`docs/spec/dsl.md` §2.9 callout) and tracked in the 2026-05-03
//! verb/probe/metric plan
//! (`docs/superpowers/plans/2026-05-03-verb-probe-metric-emit.md`,
//! Slice B).
//!
//! # What this emits
//!
//! For each [`ProbeIR`] in the [`Compilation`], this synthesises a
//! generic Rust function:
//!
//! ```ignore
//! pub fn run_<probe_name><State: ::engine::sim_trait::CompiledSim>(
//!     state: &mut State,
//! ) -> ProbeOutcome
//! ```
//!
//! The function reads the probe's `scenario` / `seed` / `seeds` /
//! `ticks` metadata as a constant-folded test header (so the runtime
//! caller doesn't have to thread those values through), drives the
//! supplied [`engine::sim_trait::CompiledSim`] through the declared
//! tick count via repeated `state.step()` calls, and after the run
//! evaluates each `IrAssertExpr::{Count, Pr, Mean}` predicate against
//! constant-folded source-side metadata. The final return is a typed
//! [`ProbeOutcome`] indicating whether every assert held, which one
//! failed (with expected / actual payload), or whether the predicate
//! shape sat outside the supported subset and was skipped.
//!
//! # Supported assert shape (initial scope)
//!
//! The emitter today supports the **constant-foldable scalar shape**:
//!
//! ```text
//! count[<literal>] <op> <literal>
//! ```
//!
//! plus the analogous `pr[ … | … ]` and `mean[ … | … ]` heads when
//! both sides constant-fold. The check evaluates the LHS expression
//! to an `f64`, the RHS to an `f64`, and applies the comparator. This
//! keeps the emit pass independent of per-fixture readback methods —
//! the runtime needn't expose any extra accessors for these probes to
//! drive.
//!
//! Predicates whose filter / scalar / value sub-expressions don't
//! constant-fold (the binder-bound `count[a in agents where …]` form,
//! per-tick event-ring queries, `forall t in 0..ticks` quantifiers)
//! land in the `// SKIP <reason>` bucket. The probe still emits a
//! callable `run_<name>` fn that drives the runtime through `ticks`
//! ticks and returns [`ProbeOutcome::Skipped`] with the reason —
//! authors see the gap at build time as a comment plus at runtime as
//! a typed payload, exactly mirroring the invariant + metric SKIP
//! pattern.
//!
//! # Why a separate function (not `emit_cg_program`)
//!
//! Probes, like invariants and metrics, don't correspond to CG ops,
//! kernels, or the schedule — they're host-side test drivers over
//! runtime state. They live outside [`crate::cg::CgProgram`] (which
//! carries only kernel-bound IR), so the emit pass takes the
//! [`Compilation`] directly. The companion entry point
//! [`emit_cg_program_with_invariants_metrics_and_probes`] wraps
//! [`super::metrics::emit_cg_program_with_invariants_and_metrics`] and
//! injects the synthesized `probes.rs` artifact alongside the existing
//! `invariants.rs` + `metrics.rs` siblings.

use std::fmt::Write as _;

use dsl_ast::ir::{Compilation, IrAssertExpr, IrExpr, IrExprNode, ProbeIR};

use super::metrics::emit_cg_program_with_invariants_and_metrics;
use super::program::{EmittedArtifacts, ProgramEmitError};
use crate::cg::program::CgProgram;
use crate::cg::schedule::synthesis::ComputeSchedule;

/// Synthesise the per-fixture `probes.rs` source. Returns `None` when
/// the compilation declares no probes (so callers can skip the
/// artifact entirely instead of writing an empty file).
pub fn synthesize_probes(comp: &Compilation) -> Option<String> {
    if comp.probes.is_empty() {
        return None;
    }

    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Source: each `probe <name> { scenario / seed / seeds / ticks /\n");
    out.push_str("//          tolerance / assert { count[…] / pr[…] / mean[…] } }`\n");
    out.push_str("// declaration in the fixture's .sim file. Regenerate by editing\n");
    out.push_str("// the .sim file and rebuilding.\n\n");

    out.push_str("/// Outcome of a single `run_<probe_name>(state)` driver call.\n");
    out.push_str("/// `Passed` carries the actual tick count run (matches the probe's\n");
    out.push_str("/// declared `ticks` for non-skip shapes); `Failed` carries which\n");
    out.push_str("/// assert tripped, the expected literal, the observed scalar, the\n");
    out.push_str("/// comparator string, and the tick at which the check ran (always\n");
    out.push_str("/// the final tick today — per-tick assertion is a follow-up shape);\n");
    out.push_str("/// `Skipped` carries the human-readable reason the predicate's\n");
    out.push_str("/// shape sat outside the supported subset.\n");
    out.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    out.push_str("pub enum ProbeOutcome {\n");
    out.push_str("    Passed { ticks_run: u64 },\n");
    out.push_str("    Failed {\n");
    out.push_str("        probe:    &'static str,\n");
    out.push_str("        assert:   usize,\n");
    out.push_str("        op:       &'static str,\n");
    out.push_str("        expected: f64,\n");
    out.push_str("        actual:   f64,\n");
    out.push_str("        tick:     u64,\n");
    out.push_str("    },\n");
    out.push_str("    Skipped { probe: &'static str, reason: &'static str },\n");
    out.push_str("}\n\n");

    for probe in &comp.probes {
        emit_probe_runner(probe, &mut out);
        out.push('\n');
    }

    Some(out)
}

/// Wrap [`emit_cg_program_with_invariants_and_metrics`] so callers
/// (per-fixture `build.rs`) get the `probes.rs` artifact alongside the
/// existing `invariants.rs` + `metrics.rs` + kernel + cross-cutting
/// set without duplicating the emit-and-merge boilerplate. Existing
/// callers of the metrics+invariants entry point are untouched; they
/// get the same artifact set (no `probes.rs`, since probes inject
/// independently of the schedule).
pub fn emit_cg_program_with_invariants_metrics_and_probes(
    schedule: &ComputeSchedule,
    prog: &CgProgram,
    comp: &Compilation,
) -> Result<EmittedArtifacts, ProgramEmitError> {
    let mut artifacts =
        emit_cg_program_with_invariants_and_metrics(schedule, prog, comp)?;
    if let Some(src) = synthesize_probes(comp) {
        artifacts.rust_files.insert("probes.rs".to_string(), src);
    }
    Ok(artifacts)
}

// ---------------------------------------------------------------------------
// Per-probe emit
// ---------------------------------------------------------------------------

fn emit_probe_runner(probe: &ProbeIR, out: &mut String) {
    let name = &probe.name;
    let ticks = probe.ticks.unwrap_or(0);
    let scenario = probe.scenario.as_deref().unwrap_or("<unspecified>");
    let seed = probe.seed.unwrap_or(0);

    // Doc-comment header — bakes the source-side metadata so authors
    // can grep for the probe's parameters in the emitted file.
    let _ = writeln!(
        out,
        "/// Probe `{name}` — drives the supplied runtime through {ticks} ticks\n\
         /// (scenario `{scenario}`, seed = {seed:#x}, asserts = {n_asserts}).\n\
         /// Returns [`ProbeOutcome::Passed`] when every constant-foldable\n\
         /// assertion holds at the final tick, [`ProbeOutcome::Failed`] when\n\
         /// any tripped, or [`ProbeOutcome::Skipped`] when the first\n\
         /// unsupported-shape assertion hits.",
        name = name,
        ticks = ticks,
        scenario = scenario,
        seed = seed,
        n_asserts = probe.asserts.len(),
    );

    let _ = writeln!(
        out,
        "pub fn run_{name}<State: ::engine::sim_trait::CompiledSim>(\n\
         \x20   state: &mut State,\n\
         ) -> ProbeOutcome {{",
        name = name,
    );
    // Constant-folded test header — same shape as the source `.sim`,\n
    // exposed as `let` bindings so the assertion bodies can reference\n
    // them (and so the emitted file is self-documenting).
    let _ = writeln!(
        out,
        "    const PROBE_NAME: &str = \"{name}\";\n\
         \x20   const TICKS: u32 = {ticks};\n\
         \x20   const SEED: u64 = {seed}_u64;\n\
         \x20   let _ = (PROBE_NAME, TICKS, SEED);",
        name = name,
        ticks = ticks,
        seed = seed,
    );

    // Drive the runtime forward by `ticks`. This is the only side
    // effect of the probe — the assertions are pure scalar
    // comparisons over the source-side constants today.
    let _ = writeln!(out, "    for _ in 0..TICKS {{ state.step(); }}");
    let _ = writeln!(out, "    let final_tick = state.tick();");

    // Per-assert evaluation. Each one emits as a small block that
    // either continues to the next assert (success) or returns
    // ProbeOutcome::Failed / ProbeOutcome::Skipped.
    if probe.asserts.is_empty() {
        let _ = writeln!(
            out,
            "    // Probe declared no asserts — successful run is just\n\
             \x20   // \"the runtime didn't panic for {ticks} ticks\".",
            ticks = ticks,
        );
    }
    for (idx, assert) in probe.asserts.iter().enumerate() {
        emit_one_assert(name, idx, assert, out);
    }

    let _ = writeln!(out, "    let _ = final_tick;");
    let _ = writeln!(out, "    ProbeOutcome::Passed {{ ticks_run: state.tick() }}");
    let _ = writeln!(out, "}}");
}

fn emit_one_assert(probe_name: &str, idx: usize, assert: &IrAssertExpr, out: &mut String) {
    let cls = classify_assert(assert);
    match cls {
        AssertShape::ConstScalar { lhs, op, rhs } => {
            // Round-trip-safe debug format for f64 so byte-identical
            // emission across runs is preserved (mirrors the invariant
            // + metric `{value:?}` discipline).
            let _ = writeln!(
                out,
                "    {{\n\
                 \x20       let lhs: f64 = {lhs:?}_f64;\n\
                 \x20       let rhs: f64 = {rhs:?}_f64;\n\
                 \x20       let ok = {predicate};\n\
                 \x20       if !ok {{\n\
                 \x20           return ProbeOutcome::Failed {{\n\
                 \x20               probe:    \"{probe}\",\n\
                 \x20               assert:   {idx},\n\
                 \x20               op:       \"{op_str}\",\n\
                 \x20               expected: rhs,\n\
                 \x20               actual:   lhs,\n\
                 \x20               tick:     final_tick,\n\
                 \x20           }};\n\
                 \x20       }}\n\
                 \x20   }}",
                lhs = lhs,
                rhs = rhs,
                predicate = const_predicate_expr("lhs", &op, "rhs"),
                probe = probe_name,
                idx = idx,
                op_str = op,
            );
        }
        AssertShape::Skipped(reason) => {
            let _ = writeln!(
                out,
                "    // SKIP `{probe}` assert #{idx}: {reason}.",
                probe = probe_name,
                idx = idx,
                reason = reason,
            );
            let _ = writeln!(
                out,
                "    return ProbeOutcome::Skipped {{ probe: \"{probe}\", reason: \"{reason}\" }};",
                probe = probe_name,
                reason = reason,
            );
        }
    }
}

/// Lower a comparator string into a Rust binary-op invocation. Returns
/// the textual `<lhs> <rust_op> <rhs>` snippet — caller wraps in
/// braces / let / etc. Unknown comparators fall through to `false`
/// (with the assert reporting Failed at runtime); the resolver should
/// only ever produce the six recognised forms.
fn const_predicate_expr(lhs: &str, op: &str, rhs: &str) -> String {
    match op {
        "==" => format!("{lhs} == {rhs}"),
        "!=" => format!("{lhs} != {rhs}"),
        "<" => format!("{lhs} < {rhs}"),
        "<=" => format!("{lhs} <= {rhs}"),
        ">" => format!("{lhs} > {rhs}"),
        ">=" => format!("{lhs} >= {rhs}"),
        _ => "false".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Predicate-shape classifier
// ---------------------------------------------------------------------------

enum AssertShape {
    /// Both sides constant-fold to an `f64`. The op string is whatever
    /// the parser captured ("==", "<=", …) and we trust the resolver
    /// to have produced one of the six recognised forms.
    ConstScalar { lhs: f64, op: String, rhs: f64 },
    /// The assertion's filter / scalar / value sub-expressions don't
    /// constant-fold under the supported subset. Surfaces in the
    /// emitted file as a `// SKIP` comment + a typed runtime payload.
    Skipped(&'static str),
}

fn classify_assert(a: &IrAssertExpr) -> AssertShape {
    match a {
        IrAssertExpr::Count { filter, op, value, .. } => {
            // `count[<filter>] <op> <value>` — today only constant-foldable
            // filters and values are supported. The binder-bound shape
            // (`count[a in agents where <pred>]`) needs scope-binding
            // in the resolver before we can lower it; out of scope for
            // slice B.
            classify_const_scalar(filter, op, value)
        }
        IrAssertExpr::Pr { action_filter, op, value, .. } => {
            // `pr[<action_filter> | <obs_filter>] <op> <value>` — the
            // observation filter informs the conditional probability,
            // but for the constant-foldable case we accept either side
            // of the bar as the LHS (the constant case folds both into
            // the same scalar). Today's first cut only checks the
            // action_filter side.
            classify_const_scalar(action_filter, op, value)
        }
        IrAssertExpr::Mean { scalar, op, value, .. } => {
            // `mean[<scalar> | <filter>] <op> <value>` — same constraint:
            // the scalar inside the brackets must constant-fold to a
            // number for slice B's first cut. View-call / aggregate
            // forms are deferred.
            classify_const_scalar(scalar, op, value)
        }
    }
}

fn classify_const_scalar(lhs: &IrExprNode, op: &str, rhs: &IrExprNode) -> AssertShape {
    let lhs_val = match const_fold_scalar(lhs) {
        Some(v) => v,
        None => {
            return AssertShape::Skipped(
                "LHS of assert does not constant-fold (binder-bound aggregates / view calls / per-tick reads not yet wired)",
            );
        }
    };
    let rhs_val = match const_fold_scalar(rhs) {
        Some(v) => v,
        None => {
            return AssertShape::Skipped(
                "RHS of assert does not constant-fold (binder-bound aggregates / view calls / per-tick reads not yet wired)",
            );
        }
    };
    if !matches!(op, "==" | "!=" | "<" | "<=" | ">" | ">=") {
        return AssertShape::Skipped(
            "comparator must be one of ==, !=, <, <=, >, >=",
        );
    }
    AssertShape::ConstScalar { lhs: lhs_val, op: op.to_string(), rhs: rhs_val }
}

/// Fold a single [`IrExprNode`] to an `f64` if it's a numeric literal.
/// Returns `None` for any shape that depends on runtime state (binder
/// references, view calls, namespace fields, builtin calls, fold /
/// quantifier forms) — the caller surfaces a SKIP for those.
fn const_fold_scalar(n: &IrExprNode) -> Option<f64> {
    match &n.kind {
        IrExpr::LitInt(i) => Some(*i as f64),
        IrExpr::LitFloat(f) => Some(*f),
        IrExpr::LitBool(b) => Some(if *b { 1.0 } else { 0.0 }),
        // Tiny constant-folding for binary ops between two literals.
        // Useful when the source is `count[…] == 100 + 50` etc.
        IrExpr::Binary(op, l, r) => {
            let lv = const_fold_scalar(l)?;
            let rv = const_fold_scalar(r)?;
            use dsl_ast::ast::BinOp;
            match op {
                BinOp::Add => Some(lv + rv),
                BinOp::Sub => Some(lv - rv),
                BinOp::Mul => Some(lv * rv),
                BinOp::Div => {
                    if rv == 0.0 {
                        None
                    } else {
                        Some(lv / rv)
                    }
                }
                _ => None,
            }
        }
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use dsl_ast::resolve::resolve;

    fn compile(src: &str) -> Compilation {
        let p = crate::parse(src).expect("parse");
        resolve(p).expect("resolve")
    }

    #[test]
    fn empty_compilation_emits_nothing() {
        let comp = Compilation::default();
        assert!(synthesize_probes(&comp).is_none());
    }

    #[test]
    fn const_count_emits_runner_fn() {
        // count[<literal>] == <literal> — the simplest fully-folding
        // shape. Should produce a runnable `run_<name>` that drives
        // the runtime through `ticks` ticks and returns Passed when
        // the literal comparison holds.
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
probe basic_count_holds {
  scenario "synthetic"
  seed 7
  ticks 10
  assert {
    count[5.0] == 5.0
  }
}
"#;
        let comp = compile(src);
        let out = synthesize_probes(&comp).expect("non-empty");
        assert!(
            out.contains(
                "pub fn run_basic_count_holds<State: ::engine::sim_trait::CompiledSim>"
            ),
            "expected per-probe runner fn:\n{out}",
        );
        assert!(
            out.contains("const TICKS: u32 = 10;"),
            "expected ticks constant baked in:\n{out}",
        );
        assert!(
            out.contains("for _ in 0..TICKS { state.step(); }"),
            "expected runtime tick-driver loop:\n{out}",
        );
        assert!(
            out.contains("ProbeOutcome::Passed"),
            "expected pass-path return:\n{out}",
        );
        assert!(
            out.contains("ProbeOutcome::Failed"),
            "expected fail-path return:\n{out}",
        );
    }

    #[test]
    fn const_count_failing_emits_failure_path() {
        // count[<literal>] == <different literal> — the runner must
        // emit the failure-path return because the constant compare
        // tripped at compile time.
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
probe always_fails {
  scenario "synthetic"
  ticks 1
  assert {
    count[5.0] == 99.0
  }
}
"#;
        let comp = compile(src);
        let out = synthesize_probes(&comp).expect("non-empty");
        // Both branches present: the predicate evaluation happens at
        // runtime so we always have both paths in the source.
        assert!(out.contains("let lhs: f64 = 5.0_f64;"), "expected LHS literal:\n{out}");
        assert!(out.contains("let rhs: f64 = 99.0_f64;"), "expected RHS literal:\n{out}");
        assert!(out.contains("op:       \"==\""), "expected captured op string:\n{out}");
    }

    #[test]
    fn unsupported_shape_emits_skip() {
        // mean[<scalar> | <filter>] where the scalar is bare-binder
        // `1.0` and the filter references an unbound binder — today
        // the resolver doesn't bind binders inside assert filters,
        // so this is exercised via a non-folding RHS.
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
config { unsupported { value: i32 = 42, } }
probe non_const_rhs {
  ticks 5
  assert {
    count[1.0] < 10.0 + 0.0
  }
}
"#;
        // The shape above DOES constant-fold (10.0 + 0.0). For a true
        // SKIP, use a builtin call form on the RHS.
        let _ = src;

        // Try with a comparison that fails to constant-fold via a
        // builtin call as RHS. Even simpler: max(1, 2) doesn't fold.
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
probe non_const_rhs {
  ticks 5
  assert {
    count[1.0] < max(1.0, 2.0)
  }
}
"#;
        let comp = compile(src);
        let out = synthesize_probes(&comp).expect("non-empty");
        assert!(
            out.contains("// SKIP `non_const_rhs` assert #0"),
            "expected SKIP comment for unsupported shape:\n{out}",
        );
        assert!(
            out.contains("ProbeOutcome::Skipped"),
            "expected Skipped runtime payload:\n{out}",
        );
    }

    #[test]
    fn folded_arithmetic_rhs_supported() {
        // count[1.0] == (3.0 + 2.0) — RHS is a binary expression of
        // two literals. The constant folder should compute 5.0 and
        // emit the comparison successfully.
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
probe folded_rhs {
  ticks 1
  assert {
    count[1.0] == 3.0 + 2.0
  }
}
"#;
        let comp = compile(src);
        let out = synthesize_probes(&comp).expect("non-empty");
        assert!(
            out.contains("let rhs: f64 = 5.0_f64;"),
            "expected folded RHS = 5.0:\n{out}",
        );
        assert!(
            !out.contains("// SKIP"),
            "folded arithmetic must not skip:\n{out}",
        );
    }

    #[test]
    fn empty_asserts_just_drives_ticks() {
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
probe just_drives {
  scenario "synthetic"
  ticks 3
}
"#;
        let comp = compile(src);
        let out = synthesize_probes(&comp).expect("non-empty");
        assert!(
            out.contains("for _ in 0..TICKS { state.step(); }"),
            "expected tick-driver loop even without asserts:\n{out}",
        );
        assert!(
            out.contains("// Probe declared no asserts"),
            "expected explanatory comment:\n{out}",
        );
        assert!(
            out.contains("ProbeOutcome::Passed"),
            "expected unconditional pass for assert-less probes:\n{out}",
        );
    }

    #[test]
    fn outcome_enum_present() {
        let src = r#"
event Tick { }
entity Agent_ : Agent { pos: vec3, }
probe any { ticks 1 }
"#;
        let comp = compile(src);
        let out = synthesize_probes(&comp).expect("non-empty");
        assert!(out.contains("pub enum ProbeOutcome"), "expected outcome enum:\n{out}");
        assert!(out.contains("Passed { ticks_run: u64 }"), "expected Passed variant:\n{out}");
        assert!(out.contains("Failed {"), "expected Failed variant:\n{out}");
        assert!(out.contains("Skipped { probe:"), "expected Skipped variant:\n{out}");
    }
}
