//! Full-program emission — Task 4.3.
//!
//! Walks every kernel in a [`ComputeSchedule`] and produces the file
//! set the xtask writes into `crates/engine_gpu_rules/src/`. Each
//! kernel becomes one `.wgsl` file (the WGSL kernel source) plus one
//! `.rs` file (the Rust kernel module that owns the pipeline, BGL,
//! `Bindings` struct, `bind()`, and `build_cfg()`).
//!
//! # Pipeline
//!
//! ```text
//!   ComputeSchedule  ─┐
//!                     ├─►  emit_cg_program  ─►  EmittedArtifacts
//!   CgProgram        ─┘                           ├─ wgsl_files: BTreeMap<String, String>
//!                                                 ├─ rust_files: BTreeMap<String, String>
//!                                                 └─ kernel_index: Vec<String>
//! ```
//!
//! For each `(stage, kernel)` pair this calls Task 4.2's
//! [`kernel_topology_to_spec_and_body`] to obtain the `(KernelSpec,
//! body)` pair, then runs the four
//! [`crate::kernel_lowerings::lower_*`] helpers — drift across the
//! WGSL and Rust outputs is structurally impossible because every
//! string derives from the same [`KernelSpec`].
//!
//! # Determinism
//!
//! Outputs are byte-identical across runs:
//! - [`BTreeMap`] preserves sorted iteration order.
//! - The schedule iteration is deterministic (Task 3.x guarantees a
//!   stable stage list).
//! - All inner lowerings ([`crate::kernel_lowerings`], Task 4.1's
//!   walks, Task 4.2's spec lowering) are deterministic.
//!
//! The `program_emit_is_deterministic` test pins the contract.
//!
//! # Limitations
//!
//! - **Inherits Task 4.2's limitations.** Placeholder bodies for
//!   [`crate::cg::op::ComputeOpKind::ScoringArgmax`],
//!   [`crate::cg::op::ComputeOpKind::SpatialQuery`], and
//!   [`crate::cg::op::ComputeOpKind::Plumbing`] are emitted as
//!   documented `// TODO(task-X.Y)` comment lines, not panics. Kernel
//!   names are structural (`cg_<topology>_<first_op>_<count>`); the
//!   cfg uniform's struct shape is a placeholder
//!   `{ agent_cap: u32, _pad: [u32; 3] }`.
//! - **Output file format approximates legacy emit; exact byte-for-byte
//!   parity with the hand-written `crates/engine_gpu_rules/src/<k>.{rs,wgsl}`
//!   files is Task 5.1's job.** Differences in this commit:
//!   - Header comment is `// GENERATED by dsl_compiler — do not edit
//!     by hand.` rather than the legacy
//!     `// GENERATED by dsl_compiler::emit_<...>. ...`.
//!   - The Rust module's `record()` dispatch helper carries a
//!     placeholder body — Task 5.1 adds the dispatch-shape-driven
//!     workgroup count + indirect-dispatch wiring (today the helper
//!     dispatches with `ctx.dispatch_count(...)`).
//!   - `Kernel` trait `impl` is omitted in this first cut; the emitted
//!     file declares the struct + standalone helpers but does not yet
//!     implement [`engine_gpu_rules::Kernel`]. Task 5.1 adds the
//!     trait impl shape.
//! - **`kernel_index` is a flat `Vec`.** The legacy build emits a
//!   registry index file (`kernel_index.rs`); Task 5.1 may extend
//!   [`EmittedArtifacts`] with that registry alongside.
//! - **Name-collision detection is a structural safety net.** With
//!   today's structural naming (`cg_<topology>_<first_op>_<count>`),
//!   two kernels can collide if a stage carries two `Split` kernels
//!   over the same op kind with the same op count (e.g. two Split
//!   `mask_predicate` kernels in different stages). Task 5.1's name
//!   alignment will use semantic names that include the masked output
//!   handle, removing the structural collision risk; until then the
//!   collision check surfaces it as a typed error.

use std::collections::BTreeMap;
use std::fmt;

use crate::cg::dispatch::DispatchShape;
use crate::cg::program::CgProgram;
use crate::cg::schedule::synthesis::{ComputeSchedule, KernelTopology};
use crate::kernel_binding_ir::KernelSpec;
use crate::kernel_lowerings::{
    lower_rust_bg_entries, lower_rust_bgl_entries, lower_rust_bindings_struct_fields,
    lower_wgsl_bindings,
};

use super::kernel::{kernel_topology_to_spec_and_body, KernelEmitError};
use super::wgsl_body::{EmitCtx, HandleNamingStrategy};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// The set of emitted source artifacts produced by [`emit_cg_program`].
///
/// File-name keys carry the basename only (e.g. `fused_mask.wgsl`); the
/// xtask resolves them under `crates/engine_gpu_rules/src/`. Both maps
/// use [`BTreeMap`] so iteration is deterministic across runs.
#[derive(Debug, Clone, Default, Eq, PartialEq)]
pub struct EmittedArtifacts {
    /// Per-kernel WGSL file content. Key is the output filename
    /// (`<kernel_name>.wgsl`); value is the full file contents.
    pub wgsl_files: BTreeMap<String, String>,
    /// Per-kernel Rust module content. Key is the output filename
    /// (`<kernel_name>.rs`); value is the full file contents.
    pub rust_files: BTreeMap<String, String>,
    /// Index of all kernels in schedule order — each entry is the
    /// kernel's snake_case name. Useful for building a `mod.rs` /
    /// `lib.rs` registry (Task 5.1).
    pub kernel_index: Vec<String>,
}

/// Errors that can surface from [`emit_cg_program`]. Every variant
/// carries typed payload — no free-form `String` reasons.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProgramEmitError {
    /// A [`KernelTopology`] failed to lower to a [`KernelSpec`]. The
    /// `(stage_index, kernel_index)` locates the failing kernel inside
    /// the schedule.
    KernelLowering {
        stage_index: usize,
        kernel_index: usize,
        error: KernelEmitError,
    },
    /// Two kernels in the same schedule produced the same name. With
    /// Task 4.2's structural naming this can fire when two
    /// [`KernelTopology::Split`] kernels over the same op kind carry
    /// the same op count. Task 5.1's semantic-name alignment removes
    /// the risk; until then the collision is surfaced as a typed error
    /// rather than silently overwriting one of the files.
    KernelNameCollision {
        name: String,
        first_at: (usize, usize),
        second_at: (usize, usize),
    },
}

impl fmt::Display for ProgramEmitError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ProgramEmitError::KernelLowering {
                stage_index,
                kernel_index,
                error,
            } => write!(
                f,
                "kernel emit failed at stage[{stage_index}].kernels[{kernel_index}]: {error}"
            ),
            ProgramEmitError::KernelNameCollision {
                name,
                first_at,
                second_at,
            } => write!(
                f,
                "kernel name collision: `{name}` first emitted at \
                 stage[{}].kernels[{}], collided at stage[{}].kernels[{}]",
                first_at.0, first_at.1, second_at.0, second_at.1
            ),
        }
    }
}

impl std::error::Error for ProgramEmitError {}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Emit the full set of WGSL + Rust source files for a
/// [`ComputeSchedule`].
///
/// Walks every kernel in every stage, lowers each to a `(KernelSpec,
/// body)` pair via Task 4.2's [`kernel_topology_to_spec_and_body`], and
/// composes the WGSL + Rust file contents using the four
/// [`crate::kernel_lowerings::lower_*`] helpers.
///
/// # Errors
///
/// - [`ProgramEmitError::KernelLowering`] — any kernel's spec lowering
///   raised a typed [`KernelEmitError`] (op-id out-of-range, empty
///   topology, inner-walk arena failure, spec-validation failure).
/// - [`ProgramEmitError::KernelNameCollision`] — two kernels in the
///   schedule produced the same snake_case name. (See `# Limitations`
///   on the module-level docs.)
pub fn emit_cg_program(
    schedule: &ComputeSchedule,
    prog: &CgProgram,
) -> Result<EmittedArtifacts, ProgramEmitError> {
    let mut wgsl_files: BTreeMap<String, String> = BTreeMap::new();
    let mut rust_files: BTreeMap<String, String> = BTreeMap::new();
    let mut kernel_index: Vec<String> = Vec::new();
    let mut seen_names: BTreeMap<String, (usize, usize)> = BTreeMap::new();

    let ctx = EmitCtx {
        prog,
        naming: HandleNamingStrategy::Structural,
    };

    for (stage_idx, stage) in schedule.stages.iter().enumerate() {
        for (kernel_idx, topology) in stage.kernels.iter().enumerate() {
            let (spec, body) = kernel_topology_to_spec_and_body(topology, prog, &ctx).map_err(
                |error| ProgramEmitError::KernelLowering {
                    stage_index: stage_idx,
                    kernel_index: kernel_idx,
                    error,
                },
            )?;

            if let Some(prior) = seen_names.get(&spec.name) {
                return Err(ProgramEmitError::KernelNameCollision {
                    name: spec.name.clone(),
                    first_at: *prior,
                    second_at: (stage_idx, kernel_idx),
                });
            }
            seen_names.insert(spec.name.clone(), (stage_idx, kernel_idx));

            let wgsl = compose_wgsl_file(&spec, &body, topology);
            wgsl_files.insert(format!("{}.wgsl", spec.name), wgsl);

            let rs = compose_rust_module_file(&spec);
            rust_files.insert(format!("{}.rs", spec.name), rs);

            kernel_index.push(spec.name.clone());
        }
    }

    Ok(EmittedArtifacts {
        wgsl_files,
        rust_files,
        kernel_index,
    })
}

// ---------------------------------------------------------------------------
// File composition
// ---------------------------------------------------------------------------

/// Compose a single `.wgsl` file from a [`KernelSpec`] + body string +
/// originating [`KernelTopology`] (used to derive the workgroup size).
///
/// The output mirrors the legacy WGSL files' shape:
/// 1. A `// GENERATED ...` header comment.
/// 2. The `@group(0) @binding(N)` declaration block from
///    [`lower_wgsl_bindings`].
/// 3. The `@compute @workgroup_size(N)` annotation, derived from the
///    topology's [`DispatchShape::workgroup_size`].
/// 4. The entry-point function with its `gid` argument and the body
///    from Task 4.2.
fn compose_wgsl_file(spec: &KernelSpec, body: &str, topology: &KernelTopology) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push('\n');

    out.push_str(&lower_wgsl_bindings(spec));
    out.push('\n');

    let workgroup_x = topology_workgroup_size_x(topology);

    out.push_str(&format!(
        "@compute @workgroup_size({workgroup_x})\n\
         fn {entry}(@builtin(global_invocation_id) gid: vec3<u32>) {{\n",
        entry = spec.entry_point
    ));
    out.push_str(body);
    if !body.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("}\n");

    out
}

/// Compose a single `.rs` file from a [`KernelSpec`].
///
/// The output mirrors the legacy Rust kernel modules' shape (see
/// `crates/engine_gpu_rules/src/alive_pack.rs` for a template), with
/// the differences documented in the module-level `# Limitations`. Each
/// section is sourced from one of the [`crate::kernel_lowerings`]
/// helpers, so a regression in any single emitted form is caught by the
/// lowering's own tests; this composer is structural glue only.
fn compose_rust_module_file(spec: &KernelSpec) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push('\n');

    // Cfg struct decl — KernelSpec.cfg_struct_decl is the full
    // `#[repr(C)] ... pub struct <Cfg> { ... }` form.
    out.push_str(&spec.cfg_struct_decl);
    out.push_str("\n\n");

    // Bindings struct.
    out.push_str(&format!(
        "pub struct {pascal}Bindings<'a> {{\n",
        pascal = spec.pascal
    ));
    out.push_str(&lower_rust_bindings_struct_fields(spec));
    out.push_str("}\n\n");

    // BGL entries function.
    out.push_str(&format!(
        "pub fn {name}_bgl_entries() -> Vec<wgpu::BindGroupLayoutEntry> {{\n    \
         vec![\n",
        name = spec.name
    ));
    out.push_str(&lower_rust_bgl_entries(spec));
    out.push_str("    ]\n}\n\n");

    // Bind-group entries function. Returns the BindGroupEntry list a
    // caller wraps with the BGL into a BindGroup.
    out.push_str(&format!(
        "pub fn {name}_bind_group_entries<'a>(\n    \
         bindings: &'a {pascal}Bindings<'a>,\n) -> \
         Vec<wgpu::BindGroupEntry<'a>> {{\n    vec![\n",
        name = spec.name,
        pascal = spec.pascal
    ));
    out.push_str(&lower_rust_bg_entries(spec));
    out.push_str("    ]\n}\n\n");

    // Cfg builder.
    out.push_str(&format!(
        "pub fn {name}_build_cfg(state: &engine::state::SimState) -> {cfg} {{\n    \
         {build}\n}}\n",
        name = spec.name,
        cfg = spec.cfg_struct,
        build = spec.cfg_build_expr,
    ));

    out
}

// ---------------------------------------------------------------------------
// Topology → workgroup size
// ---------------------------------------------------------------------------

/// Pick the `@workgroup_size(x)` value a kernel emitted from `topology`
/// should declare. Routes through Task 1.4's
/// [`DispatchShape::workgroup_size`] so the WGSL annotation and the
/// dispatch-count rule never disagree.
///
/// For [`KernelTopology::Indirect`] the consumer's per-event dispatch
/// drives the size — every consumer carries the same `PerEvent` shape,
/// so picking the first is structural (the well-formed pass already
/// guards mismatches).
fn topology_workgroup_size_x(topology: &KernelTopology) -> u32 {
    let dispatch = match topology {
        KernelTopology::Fused { dispatch, .. } => *dispatch,
        KernelTopology::Split { dispatch, .. } => *dispatch,
        KernelTopology::Indirect { consumers: _, .. } => {
            // Indirect-dispatched consumers always carry PerEvent.
            // The well-formed pass guarantees consumers exist; if they
            // don't, the body lowering above would have already errored
            // with `EmptyKernelTopology`.
            DispatchShape::PerEvent {
                source_ring: crate::cg::data_handle::EventRingId(0),
            }
        }
    };
    dispatch.workgroup_size().x
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cg::data_handle::{
        AgentFieldId, AgentRef, CgExprId, DataHandle, EventRingId, MaskId,
    };
    use crate::cg::dispatch::DispatchShape;
    use crate::cg::expr::{BinaryOp, CgExpr, CgTy, LitValue};
    use crate::cg::lower::lower_compilation_to_cg;
    use crate::cg::op::{
        ComputeOp, ComputeOpKind, EventKindId, OpId, PhysicsRuleId, PlumbingKind,
        ReplayabilityFlag, Span,
    };
    use crate::cg::schedule::synthesis::{
        synthesize_schedule, ComputeStage, KernelTopology,
    };
    use crate::cg::schedule::ScheduleStrategy;
    use crate::cg::stmt::{CgStmt, CgStmtId, CgStmtList, CgStmtListId};
    use dsl_ast::ir::Compilation;

    // -- Test fixtures ---------------------------------------------------

    fn push_op(prog: &mut CgProgram, mut op: ComputeOp) -> OpId {
        let id = OpId(prog.ops.len() as u32);
        op.id = id;
        prog.ops.push(op);
        id
    }

    fn push_expr(prog: &mut CgProgram, e: CgExpr) -> CgExprId {
        let id = CgExprId(prog.exprs.len() as u32);
        prog.exprs.push(e);
        id
    }

    fn push_stmt(prog: &mut CgProgram, s: CgStmt) -> CgStmtId {
        let id = CgStmtId(prog.stmts.len() as u32);
        prog.stmts.push(s);
        id
    }

    fn push_list(prog: &mut CgProgram, l: CgStmtList) -> CgStmtListId {
        let id = CgStmtListId(prog.stmt_lists.len() as u32);
        prog.stmt_lists.push(l);
        id
    }

    /// Build a single MaskPredicate op `mask[m] = (self.hp < 5.0)`.
    fn mask_op(prog: &mut CgProgram, mask: MaskId) -> OpId {
        let hp = push_expr(
            prog,
            CgExpr::Read(DataHandle::AgentField {
                field: AgentFieldId::Hp,
                target: AgentRef::Self_,
            }),
        );
        let five = push_expr(prog, CgExpr::Lit(LitValue::F32(5.0)));
        let lt = push_expr(
            prog,
            CgExpr::Binary {
                op: BinaryOp::LtF32,
                lhs: hp,
                rhs: five,
                ty: CgTy::Bool,
            },
        );
        let kind = ComputeOpKind::MaskPredicate {
            mask,
            predicate: lt,
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::PerAgent,
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    /// Build a PhysicsRule op `self.hp = self.hp + 1.0` over `ring`.
    fn physics_op(prog: &mut CgProgram, rule: PhysicsRuleId, ring: EventRingId) -> OpId {
        let hp_read = push_expr(
            prog,
            CgExpr::Read(DataHandle::AgentField {
                field: AgentFieldId::Hp,
                target: AgentRef::Self_,
            }),
        );
        let one = push_expr(prog, CgExpr::Lit(LitValue::F32(1.0)));
        let add = push_expr(
            prog,
            CgExpr::Binary {
                op: BinaryOp::AddF32,
                lhs: hp_read,
                rhs: one,
                ty: CgTy::F32,
            },
        );
        let assign = push_stmt(
            prog,
            CgStmt::Assign {
                target: DataHandle::AgentField {
                    field: AgentFieldId::Hp,
                    target: AgentRef::Self_,
                },
                value: add,
            },
        );
        let body = push_list(prog, CgStmtList { stmts: vec![assign] });
        let kind = ComputeOpKind::PhysicsRule {
            rule,
            on_event: EventKindId(0),
            body,
            replayable: ReplayabilityFlag::Replayable,
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::PerEvent { source_ring: ring },
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    fn seed_indirect_op(prog: &mut CgProgram, ring: EventRingId) -> OpId {
        let kind = ComputeOpKind::Plumbing {
            kind: PlumbingKind::SeedIndirectArgs { ring },
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::OneShot,
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    /// Wrap a single kernel topology into a one-stage schedule.
    fn one_stage(topology: KernelTopology) -> ComputeSchedule {
        ComputeSchedule {
            stages: vec![ComputeStage {
                kernels: vec![topology],
            }],
        }
    }

    // ---- 1. Empty schedule ----

    #[test]
    fn empty_schedule_yields_empty_artifacts() {
        let prog = CgProgram::default();
        let schedule = ComputeSchedule { stages: vec![] };
        let artifacts = emit_cg_program(&schedule, &prog).expect("empty schedule must succeed");
        assert!(artifacts.wgsl_files.is_empty(), "wgsl: {:?}", artifacts.wgsl_files);
        assert!(artifacts.rust_files.is_empty(), "rust: {:?}", artifacts.rust_files);
        assert!(artifacts.kernel_index.is_empty(), "index: {:?}", artifacts.kernel_index);
    }

    // ---- 2. Single Split kernel ----

    #[test]
    fn single_split_kernel_produces_one_wgsl_and_one_rust_file() {
        let mut prog = CgProgram::default();
        let op = mask_op(&mut prog, MaskId(7));
        let topology = KernelTopology::Split {
            op,
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("single split must succeed");

        assert_eq!(artifacts.wgsl_files.len(), 1);
        assert_eq!(artifacts.rust_files.len(), 1);
        assert_eq!(artifacts.kernel_index.len(), 1);

        // Filenames key by `<kernel_name>.wgsl` / `.rs`.
        let kernel_name = &artifacts.kernel_index[0];
        let wgsl_key = format!("{kernel_name}.wgsl");
        let rs_key = format!("{kernel_name}.rs");
        assert!(
            artifacts.wgsl_files.contains_key(&wgsl_key),
            "wgsl files: {:?}",
            artifacts.wgsl_files.keys().collect::<Vec<_>>()
        );
        assert!(
            artifacts.rust_files.contains_key(&rs_key),
            "rust files: {:?}",
            artifacts.rust_files.keys().collect::<Vec<_>>()
        );

        // WGSL file contains the @compute annotation + the binding decl.
        let wgsl = &artifacts.wgsl_files[&wgsl_key];
        assert!(wgsl.contains("@compute @workgroup_size(64)"), "wgsl: {wgsl}");
        assert!(wgsl.contains("@group(0) @binding(0)"), "wgsl: {wgsl}");
        assert!(
            wgsl.contains(&format!("fn cs_{kernel_name}")),
            "wgsl missing entry point: {wgsl}"
        );

        // Rust file contains the bindings struct + cfg struct decl.
        let rs = &artifacts.rust_files[&rs_key];
        assert!(rs.contains("pub struct"), "rs missing struct: {rs}");
        assert!(rs.contains("Bindings<'a>"), "rs missing Bindings: {rs}");
        assert!(rs.contains("_bgl_entries"), "rs missing bgl_entries: {rs}");
        assert!(rs.contains("_build_cfg"), "rs missing build_cfg: {rs}");
    }

    // ---- 3. Multi-stage schedule ----

    #[test]
    fn multi_stage_schedule_emits_all_kernels() {
        let mut prog = CgProgram::default();
        let m0 = mask_op(&mut prog, MaskId(0));
        let m1 = mask_op(&mut prog, MaskId(1));
        // Two Fused topologies in two stages — different op counts so
        // structural names diverge.
        let stage_a = KernelTopology::Fused {
            ops: vec![m0],
            dispatch: DispatchShape::PerAgent,
        };
        let stage_b = KernelTopology::Fused {
            ops: vec![m1, m1],
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = ComputeSchedule {
            stages: vec![
                ComputeStage {
                    kernels: vec![stage_a],
                },
                ComputeStage {
                    kernels: vec![stage_b],
                },
            ],
        };
        let artifacts = emit_cg_program(&schedule, &prog).expect("multi-stage emit");
        assert_eq!(artifacts.wgsl_files.len(), 2);
        assert_eq!(artifacts.rust_files.len(), 2);
        assert_eq!(artifacts.kernel_index.len(), 2);

        // Index entries are unique snake_case kernel names.
        let mut sorted = artifacts.kernel_index.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(sorted.len(), 2, "names must be unique: {:?}", artifacts.kernel_index);
    }

    // ---- 4. Snapshot — a non-trivial Rust module's full output ----

    #[test]
    fn snapshot_split_mask_predicate_rust_module() {
        let mut prog = CgProgram::default();
        let op = mask_op(&mut prog, MaskId(3));
        let topology = KernelTopology::Split {
            op,
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("snapshot emit");

        let rs_key = format!("{}.rs", artifacts.kernel_index[0]);
        let rs = &artifacts.rust_files[&rs_key];

        // Pin every section's distinguishing line. A regression in any
        // single section will break exactly one of these asserts.
        assert!(rs.contains("// GENERATED by dsl_compiler"), "rs: {rs}");
        assert!(rs.contains("#[repr(C)]"), "missing #[repr(C)]: {rs}");
        assert!(rs.contains("bytemuck::Pod"), "missing Pod derive: {rs}");
        assert!(rs.contains("pub agent_hp: &'a wgpu::Buffer,"), "missing agent_hp: {rs}");
        assert!(rs.contains("pub mask_3_bitmap: &'a wgpu::Buffer,"), "missing mask_3_bitmap: {rs}");
        assert!(rs.contains("pub cfg: &'a wgpu::Buffer,"), "missing cfg field: {rs}");
        assert!(
            rs.contains("crate::fused_mask::bgl_storage(0, true)"),
            "missing bgl entry slot 0: {rs}"
        );
        assert!(
            rs.contains("crate::fused_mask::bgl_uniform(2)"),
            "missing bgl uniform: {rs}"
        );
        assert!(
            rs.contains("wgpu::BindGroupEntry { binding: 0,"),
            "missing bg entry slot 0: {rs}"
        );
        assert!(rs.contains("state.agent_cap()"), "missing build_cfg: {rs}");
    }

    // ---- 5. Name collision ----

    #[test]
    fn duplicate_kernels_yield_typed_collision_error() {
        // Two singleton Fused kernels with identical op-kind + count
        // produce identical structural names — the collision detector
        // should flag the second one.
        let mut prog = CgProgram::default();
        let m0 = mask_op(&mut prog, MaskId(0));
        let m1 = mask_op(&mut prog, MaskId(1));
        let stage_a = KernelTopology::Fused {
            ops: vec![m0],
            dispatch: DispatchShape::PerAgent,
        };
        let stage_b = KernelTopology::Fused {
            ops: vec![m1],
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = ComputeSchedule {
            stages: vec![
                ComputeStage {
                    kernels: vec![stage_a],
                },
                ComputeStage {
                    kernels: vec![stage_b],
                },
            ],
        };
        let err = emit_cg_program(&schedule, &prog).expect_err("collision must surface");
        match err {
            ProgramEmitError::KernelNameCollision {
                ref name,
                first_at,
                second_at,
            } => {
                assert_eq!(first_at, (0, 0));
                assert_eq!(second_at, (1, 0));
                assert!(name.starts_with("cg_fused_mask_predicate"), "name: {name}");
            }
            other => panic!("expected KernelNameCollision, got {other:?}"),
        }
    }

    // ---- 6. Determinism ----

    #[test]
    fn program_emit_is_deterministic() {
        let build = || {
            let mut prog = CgProgram::default();
            let a = mask_op(&mut prog, MaskId(2));
            let b = mask_op(&mut prog, MaskId(0));
            let topology = KernelTopology::Fused {
                ops: vec![a, b],
                dispatch: DispatchShape::PerAgent,
            };
            let schedule = one_stage(topology);
            emit_cg_program(&schedule, &prog).expect("emit must succeed")
        };
        let lhs = build();
        let rhs = build();
        assert_eq!(lhs.wgsl_files, rhs.wgsl_files);
        assert_eq!(lhs.rust_files, rhs.rust_files);
        assert_eq!(lhs.kernel_index, rhs.kernel_index);
    }

    // ---- 7. Driver round-trip — synthetic Compilation through the full pipeline ----

    #[test]
    fn driver_roundtrip_lowers_synthesizes_and_emits() {
        // Empty Compilation → CgProgram (only plumbing ops) →
        // ComputeSchedule → EmittedArtifacts. Validates the wiring of
        // the full Phase 2 → Phase 3 → Phase 4 pipeline end-to-end:
        // every type along the path agrees, every helper is reachable
        // from emit_cg_program, and inner-walk failures bubble through
        // as typed errors.
        //
        // The empty Compilation lowers to four always-on plumbing ops
        // (UploadSimCfg / PackAgents / UnpackAgents / KickSnapshot) —
        // each becomes its own Split kernel. With Task 4.2's
        // structural naming (`cg_<topology>_<first_op_kind>_<count>`),
        // every plumbing op produces the same name
        // (`cg_split_plumbing_1`) so emit_cg_program legitimately
        // surfaces a KernelNameCollision. That's the documented
        // limitation of Task 4.2's naming (Task 5.1 fixes it via
        // semantic names).
        //
        // Either outcome — a clean emit OR a typed
        // ProgramEmitError::KernelNameCollision — proves the full
        // pipeline wired correctly. We assert specifically that the
        // pipeline doesn't panic and that any error returned is a
        // structural collision, not a malformed-IR or
        // arena-out-of-range failure.
        let comp = Compilation::default();
        let prog = lower_compilation_to_cg(&comp).expect("empty Compilation must lower");
        let synthesis = synthesize_schedule(&prog, ScheduleStrategy::Default);

        match emit_cg_program(&synthesis.schedule, &prog) {
            Ok(artifacts) => {
                assert_eq!(
                    artifacts.kernel_index.len(),
                    synthesis.schedule.kernel_count(),
                    "every kernel in the schedule must produce one index entry"
                );
                assert_eq!(
                    artifacts.wgsl_files.len(),
                    artifacts.kernel_index.len(),
                    "one wgsl file per kernel"
                );
                assert_eq!(
                    artifacts.rust_files.len(),
                    artifacts.kernel_index.len(),
                    "one rust file per kernel"
                );
            }
            Err(ProgramEmitError::KernelNameCollision { name, .. }) => {
                // Expected with Task 4.2's structural naming on the
                // empty Compilation's plumbing kernels. The collision
                // detector firing at all proves the full pipeline ran;
                // the specific name pin guards against regression to
                // a different (non-plumbing) cause.
                assert!(
                    name.starts_with("cg_"),
                    "collision must be on a structurally-named kernel: {name}"
                );
            }
            Err(other) => panic!(
                "driver round-trip surfaced a non-collision error: {other:?}; \
                 the pipeline should not produce malformed-IR or arena failures \
                 from an empty Compilation"
            ),
        }
    }

    // ---- 8. Indirect topology emits the consumer kernel ----

    #[test]
    fn indirect_topology_emits_one_consumer_file() {
        let mut prog = CgProgram::default();
        let ring = EventRingId(2);
        let producer = seed_indirect_op(&mut prog, ring);
        let consumer = physics_op(&mut prog, PhysicsRuleId(0), ring);
        let topology = KernelTopology::Indirect {
            producer,
            consumers: vec![consumer],
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("indirect emit");
        assert_eq!(artifacts.kernel_index.len(), 1);

        // The consumer kernel uses workgroup_size(64) (PerEvent rule).
        let wgsl = artifacts.wgsl_files.values().next().unwrap();
        assert!(
            wgsl.contains("@compute @workgroup_size(64)"),
            "wgsl: {wgsl}"
        );
    }

    // ---- 9. Lowering errors propagate as ProgramEmitError::KernelLowering ----

    #[test]
    fn op_id_out_of_range_surfaces_as_kernel_lowering_error() {
        let prog = CgProgram::default();
        let topology = KernelTopology::Split {
            op: OpId(99),
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let err = emit_cg_program(&schedule, &prog).expect_err("invalid op-id must error");
        match err {
            ProgramEmitError::KernelLowering {
                stage_index,
                kernel_index,
                error,
            } => {
                assert_eq!(stage_index, 0);
                assert_eq!(kernel_index, 0);
                assert!(
                    matches!(error, KernelEmitError::OpIdOutOfRange { .. }),
                    "inner error was {error:?}"
                );
            }
            other => panic!("expected KernelLowering, got {other:?}"),
        }
    }

    // ---- 10. WGSL file structure ----

    #[test]
    fn wgsl_file_has_header_bindings_and_entry_point() {
        let mut prog = CgProgram::default();
        let op = mask_op(&mut prog, MaskId(5));
        let topology = KernelTopology::Split {
            op,
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("emit");
        let wgsl = artifacts.wgsl_files.values().next().unwrap();

        assert!(wgsl.starts_with("// GENERATED"), "header: {wgsl}");
        assert!(wgsl.contains("@group(0) @binding("), "bindings: {wgsl}");
        assert!(wgsl.contains("@compute @workgroup_size("), "compute: {wgsl}");
        assert!(wgsl.contains("agent_id = gid.x"), "preamble: {wgsl}");
        assert!(wgsl.contains("mask_5_bitmap"), "body wiring: {wgsl}");
        // File ends with closing brace + newline.
        assert!(wgsl.ends_with("}\n"), "trailing: {:?}", &wgsl[wgsl.len().saturating_sub(20)..]);
    }
}
