//! Full-program emission — Task 4.3.
//!
//! Walks every kernel in a [`ComputeSchedule`] and produces the file
//! set the xtask writes into `crates/engine_gpu_rules/src/`. Each
//! kernel becomes one `.wgsl` file (the WGSL kernel source) plus one
//! `.rs` file (the Rust kernel module that owns the pipeline, BGL,
//! `Bindings` struct, `bind()`, and `build_cfg()`).
//!
//! # Pipeline
//!
//! ```text
//!   ComputeSchedule  ─┐
//!                     ├─►  emit_cg_program  ─►  EmittedArtifacts
//!   CgProgram        ─┘                           ├─ wgsl_files: BTreeMap<String, String>
//!                                                 ├─ rust_files: BTreeMap<String, String>
//!                                                 └─ kernel_index: Vec<String>
//! ```
//!
//! For each `(stage, kernel)` pair this calls Task 4.2's
//! [`kernel_topology_to_spec_and_body`] to obtain the `(KernelSpec,
//! body)` pair, then runs the four
//! [`crate::kernel_lowerings::lower_*`] helpers — drift across the
//! WGSL and Rust outputs is structurally impossible because every
//! string derives from the same [`KernelSpec`].
//!
//! # Determinism
//!
//! Outputs are byte-identical across runs:
//! - [`BTreeMap`] preserves sorted iteration order.
//! - The schedule iteration is deterministic (Task 3.x guarantees a
//!   stable stage list).
//! - All inner lowerings ([`crate::kernel_lowerings`], Task 4.1's
//!   walks, Task 4.2's spec lowering) are deterministic.
//!
//! The `program_emit_is_deterministic` test pins the contract.
//!
//! # Limitations
//!
//! - **Inherits Task 4.2's body limitations.** Placeholder bodies for
//!   [`crate::cg::op::ComputeOpKind::ScoringArgmax`],
//!   [`crate::cg::op::ComputeOpKind::SpatialQuery`], and
//!   [`crate::cg::op::ComputeOpKind::Plumbing`] are emitted as
//!   documented `// TODO(task-X.Y)` comment lines, not panics. The cfg
//!   uniform's struct shape is a placeholder
//!   `{ agent_cap: u32, _pad: [u32; 3] }`.
//! - **Kernel names are semantic** (`fused_mask`, `scoring`,
//!   `fold_<view>`, `physics_<rule>`, `spatial_<query>`,
//!   `alive_pack` / `seed_indirect_<ring>` / …). See
//!   [`super::kernel::semantic_kernel_name`] for the full mapping.
//! - **`Kernel` trait `impl`, `lib.rs`, and `bgl_storage` /
//!   `bgl_uniform` helpers are emitted as of Task 5.2.** The
//!   `lib.rs` content is keyed under `"lib.rs"` in
//!   [`EmittedArtifacts::rust_files`] (xtask writes it as
//!   `<src>/lib.rs`). The trait `impl` body uses
//!   `pass.dispatch_workgroups(...)` derived from the topology's
//!   [`DispatchShape::workgroup_size`]; indirect-dispatch wiring (real
//!   `dispatch_workgroups_indirect`) is a Task 5.4+ concern — today the
//!   record body emits the agent-cap-bounded direct dispatch the
//!   legacy emitters use as their stub.
//! - **Output file format approximates legacy emit; exact byte-for-byte
//!   parity with the hand-written `crates/engine_gpu_rules/src/<k>.{rs,wgsl}`
//!   files is later cross-cutting work (Task 5.4+).** Differences in
//!   this commit:
//!   - Header comment is `// GENERATED by dsl_compiler — do not edit
//!     by hand.` rather than the legacy
//!     `// GENERATED by dsl_compiler::emit_<...>. ...`.
//!   - The `Kernel::new` body uses `include_str!("<name>.wgsl")` for
//!     the WGSL source — works when xtask writes both files into the
//!     same directory.
//! - **`kernel_index` is a flat `Vec`.** The synthesized `lib.rs`
//!   walks it to produce the `mod <name>;` + `pub use` lines.
//! - **Name-collision detection is a defensive safety net.** Distinct
//!   ops with distinct semantic identities (mask name, view name,
//!   rule name) produce distinct kernel names. The collision check
//!   only fires on a real ambiguity — e.g. two ops referencing the
//!   same mask id — and surfaces as a typed error rather than
//!   silently overwriting.

use std::collections::BTreeMap;
use std::fmt;

use std::fmt::Write as _;

use crate::cg::dispatch::DispatchShape;
use crate::cg::program::CgProgram;
use crate::cg::schedule::synthesis::{ComputeSchedule, KernelTopology};
use crate::kernel_binding_ir::{snake_to_pascal, AccessMode, BgSource, KernelSpec};
use crate::kernel_lowerings::{
    lower_rust_bg_entries, lower_rust_bindings_struct_fields, lower_wgsl_bindings,
};

use super::kernel::{kernel_topology_to_spec_and_body, KernelEmitError};
use super::wgsl_body::{EmitCtx, HandleNamingStrategy};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// The set of emitted source artifacts produced by [`emit_cg_program`].
///
/// File-name keys carry the basename only (e.g. `fused_mask.wgsl`); the
/// xtask resolves them under `crates/engine_gpu_rules/src/`. Both maps
/// use [`BTreeMap`] so iteration is deterministic across runs.
#[derive(Debug, Clone, Default, Eq, PartialEq)]
pub struct EmittedArtifacts {
    /// Per-kernel WGSL file content. Key is the output filename
    /// (`<kernel_name>.wgsl`); value is the full file contents.
    pub wgsl_files: BTreeMap<String, String>,
    /// Per-kernel Rust module content. Key is the output filename
    /// (`<kernel_name>.rs`); value is the full file contents.
    pub rust_files: BTreeMap<String, String>,
    /// Index of all kernels in schedule order — each entry is the
    /// kernel's snake_case name. Useful for building a `mod.rs` /
    /// `lib.rs` registry (Task 5.1).
    pub kernel_index: Vec<String>,
}

/// Errors that can surface from [`emit_cg_program`]. Every variant
/// carries typed payload — no free-form `String` reasons.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProgramEmitError {
    /// A [`KernelTopology`] failed to lower to a [`KernelSpec`]. The
    /// `(stage_index, kernel_index)` locates the failing kernel inside
    /// the schedule.
    KernelLowering {
        stage_index: usize,
        kernel_index: usize,
        error: KernelEmitError,
    },
    /// Two kernels in the same schedule produced the same name. With
    /// Task 5.2's semantic naming distinct ops with distinct semantic
    /// identities (mask name, view name, rule name, etc.) produce
    /// distinct kernel names; this branch only fires on a real
    /// ambiguity — e.g. two ops referencing the same mask id, or two
    /// fused kernels whose first op produces the same name. The
    /// collision is surfaced as a typed error rather than silently
    /// overwriting one of the files.
    KernelNameCollision {
        name: String,
        first_at: (usize, usize),
        second_at: (usize, usize),
    },
}

impl fmt::Display for ProgramEmitError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ProgramEmitError::KernelLowering {
                stage_index,
                kernel_index,
                error,
            } => write!(
                f,
                "kernel emit failed at stage[{stage_index}].kernels[{kernel_index}]: {error}"
            ),
            ProgramEmitError::KernelNameCollision {
                name,
                first_at,
                second_at,
            } => write!(
                f,
                "kernel name collision: `{name}` first emitted at \
                 stage[{}].kernels[{}], collided at stage[{}].kernels[{}]",
                first_at.0, first_at.1, second_at.0, second_at.1
            ),
        }
    }
}

impl std::error::Error for ProgramEmitError {}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Emit the full set of WGSL + Rust source files for a
/// [`ComputeSchedule`].
///
/// Walks every kernel in every stage, lowers each to a `(KernelSpec,
/// body)` pair via Task 4.2's [`kernel_topology_to_spec_and_body`], and
/// composes the WGSL + Rust file contents using the four
/// [`crate::kernel_lowerings::lower_*`] helpers.
///
/// # Errors
///
/// - [`ProgramEmitError::KernelLowering`] — any kernel's spec lowering
///   raised a typed [`KernelEmitError`] (op-id out-of-range, empty
///   topology, inner-walk arena failure, spec-validation failure).
/// - [`ProgramEmitError::KernelNameCollision`] — two kernels in the
///   schedule produced the same snake_case name. (See `# Limitations`
///   on the module-level docs.)
pub fn emit_cg_program(
    schedule: &ComputeSchedule,
    prog: &CgProgram,
) -> Result<EmittedArtifacts, ProgramEmitError> {
    let mut wgsl_files: BTreeMap<String, String> = BTreeMap::new();
    let mut rust_files: BTreeMap<String, String> = BTreeMap::new();
    let mut kernel_index: Vec<String> = Vec::new();
    let mut seen_names: BTreeMap<String, (usize, usize)> = BTreeMap::new();

    let ctx = EmitCtx {
        prog,
        naming: HandleNamingStrategy::Structural,
    };

    for (stage_idx, stage) in schedule.stages.iter().enumerate() {
        for (kernel_idx, topology) in stage.kernels.iter().enumerate() {
            let (spec, body) = kernel_topology_to_spec_and_body(topology, prog, &ctx).map_err(
                |error| ProgramEmitError::KernelLowering {
                    stage_index: stage_idx,
                    kernel_index: kernel_idx,
                    error,
                },
            )?;

            if let Some(prior) = seen_names.get(&spec.name) {
                return Err(ProgramEmitError::KernelNameCollision {
                    name: spec.name.clone(),
                    first_at: *prior,
                    second_at: (stage_idx, kernel_idx),
                });
            }
            seen_names.insert(spec.name.clone(), (stage_idx, kernel_idx));

            let wgsl = compose_wgsl_file(&spec, &body, topology);
            wgsl_files.insert(format!("{}.wgsl", spec.name), wgsl);

            let rs = compose_rust_module_file(&spec, topology);
            rust_files.insert(format!("{}.rs", spec.name), rs);

            kernel_index.push(spec.name.clone());
        }
    }

    // Synthesize lib.rs (kernel registry + Kernel trait + bgl_storage /
    // bgl_uniform helpers). Stored under the `"lib.rs"` key (matching
    // the per-kernel `<name>.rs` keys) so the xtask side-channel writes
    // it as `<src>/lib.rs` verbatim.
    rust_files.insert("lib.rs".to_string(), synthesize_lib_rs(&kernel_index));

    Ok(EmittedArtifacts {
        wgsl_files,
        rust_files,
        kernel_index,
    })
}

// ---------------------------------------------------------------------------
// File composition
// ---------------------------------------------------------------------------

/// Compose a single `.wgsl` file from a [`KernelSpec`] + body string +
/// originating [`KernelTopology`] (used to derive the workgroup size).
///
/// The output mirrors the legacy WGSL files' shape:
/// 1. A `// GENERATED ...` header comment.
/// 2. The `@group(0) @binding(N)` declaration block from
///    [`lower_wgsl_bindings`].
/// 3. The `@compute @workgroup_size(N)` annotation, derived from the
///    topology's [`DispatchShape::workgroup_size`].
/// 4. The entry-point function with its `gid` argument and the body
///    from Task 4.2.
fn compose_wgsl_file(spec: &KernelSpec, body: &str, topology: &KernelTopology) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push('\n');

    out.push_str(&lower_wgsl_bindings(spec));
    out.push('\n');

    let workgroup_x = topology_workgroup_size_x(topology);

    out.push_str(&format!(
        "@compute @workgroup_size({workgroup_x})\n\
         fn {entry}(@builtin(global_invocation_id) gid: vec3<u32>) {{\n",
        entry = spec.entry_point
    ));
    out.push_str(body);
    if !body.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("}\n");

    out
}

/// Compose a single `.rs` file from a [`KernelSpec`] + originating
/// [`KernelTopology`] (used to derive the dispatch-workgroup expression
/// inside the [`crate::Kernel::record`] body).
///
/// The output mirrors the legacy Rust kernel modules' shape (see
/// `crates/engine_gpu_rules/src/alive_pack.rs` for a template), with
/// the differences documented in the module-level `# Limitations`. Each
/// section is sourced from one of the [`crate::kernel_lowerings`]
/// helpers, so a regression in any single emitted form is caught by the
/// lowering's own tests; this composer is structural glue only.
///
/// The synthesized module is `crate::Kernel`-implementing: the
/// `<Pascal>Kernel` struct, `<Pascal>Bindings<'a>`, the cfg struct, an
/// `impl crate::Kernel for <Pascal>Kernel { … }` block (real bodies,
/// no panics), and the standalone helper fns (`<name>_bgl_entries`,
/// `<name>_bind_group_entries`, `<name>_build_cfg`) the legacy callers
/// expect.
///
/// # Limitations
/// - The `record()` body uses
///   `pass.dispatch_workgroups((agent_cap + N - 1) / N, 1, 1)` for
///   per-agent / per-event / per-pair / per-word kernels, and
///   `(1, 1, 1)` for one-shot. Indirect dispatch
///   (`dispatch_workgroups_indirect`) is a Task 5.4+ concern — the
///   legacy emitters today use the same agent-cap-bounded direct
///   dispatch as a placeholder for per-event kernels.
/// - The `bind()` body is built from the spec's [`BgSource`] tags via
///   [`render_bg_source_expr`]; ViewHandle / AliasOf are routed
///   through `unwrap_or(primary)` patterns that mirror the legacy fold
///   kernels' pattern. None of today's CG kernels emit those variants
///   (Task 5.4+ wires fold-view tuple destructuring); the helpers stay
///   in place defensively so the composer never panics.
fn compose_rust_module_file(spec: &KernelSpec, topology: &KernelTopology) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push('\n');

    out.push_str("use crate::binding_sources::BindingSources;\n\n");

    // Per-kernel struct (carries the pipeline + BGL).
    out.push_str(&format!(
        "pub struct {pascal}Kernel {{\n    \
         pipeline: wgpu::ComputePipeline,\n    \
         bgl: wgpu::BindGroupLayout,\n}}\n\n",
        pascal = spec.pascal
    ));

    // Bindings struct.
    out.push_str(&format!(
        "pub struct {pascal}Bindings<'a> {{\n",
        pascal = spec.pascal
    ));
    out.push_str(&lower_rust_bindings_struct_fields(spec));
    out.push_str("}\n\n");

    // Cfg struct decl — KernelSpec.cfg_struct_decl is the full
    // `#[repr(C)] ... pub struct <Cfg> { ... }` form.
    out.push_str(&spec.cfg_struct_decl);
    out.push_str("\n\n");

    // WGSL source — the `.wgsl` file is co-located in the output
    // directory; `include_str!` resolves it at compile time when the
    // emitted crate is built.
    out.push_str(&format!(
        "const SHADER_SRC: &str = include_str!(\"{name}.wgsl\");\n\n",
        name = spec.name
    ));

    // Kernel trait impl.
    out.push_str(&compose_kernel_trait_impl(spec, topology));
    out.push('\n');

    // BGL entries function.
    out.push_str(&format!(
        "pub fn {name}_bgl_entries() -> Vec<wgpu::BindGroupLayoutEntry> {{\n    \
         vec![\n",
        name = spec.name
    ));
    out.push_str(&render_cg_bgl_entries(spec));
    out.push_str("    ]\n}\n\n");

    // Bind-group entries function. Returns the BindGroupEntry list a
    // caller wraps with the BGL into a BindGroup.
    out.push_str(&format!(
        "pub fn {name}_bind_group_entries<'a>(\n    \
         bindings: &'a {pascal}Bindings<'a>,\n) -> \
         Vec<wgpu::BindGroupEntry<'a>> {{\n    vec![\n",
        name = spec.name,
        pascal = spec.pascal
    ));
    out.push_str(&lower_rust_bg_entries(spec));
    out.push_str("    ]\n}\n\n");

    // Cfg builder (free fn variant — kept for backwards compat with any
    // caller that hasn't switched to `<Pascal>Kernel::build_cfg`).
    out.push_str(&format!(
        "pub fn {name}_build_cfg(state: &engine::state::SimState) -> {cfg} {{\n    \
         {build}\n}}\n",
        name = spec.name,
        cfg = spec.cfg_struct,
        build = spec.cfg_build_expr,
    ));

    out
}

/// Compose the `impl crate::Kernel for <Pascal>Kernel { … }` block.
fn compose_kernel_trait_impl(spec: &KernelSpec, topology: &KernelTopology) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "impl crate::Kernel for {pascal}Kernel {{\n    \
         type Bindings<'a> = {pascal}Bindings<'a>;\n    \
         type Cfg = {cfg};\n\n",
        pascal = spec.pascal,
        cfg = spec.cfg_struct
    ));

    // new()
    out.push_str("    fn new(device: &wgpu::Device) -> Self {\n");
    out.push_str(&format!(
        "        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::wgsl\"),\n            \
             source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),\n        \
             }});\n",
        name = spec.name
    ));
    out.push_str(&format!(
        "        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::bgl\"),\n            \
             entries: &[\n",
        name = spec.name
    ));
    out.push_str(&render_cg_bgl_entries(spec));
    out.push_str("            ],\n        });\n");
    out.push_str(&format!(
        "        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::pl\"),\n            \
             bind_group_layouts: &[&bgl],\n            \
             push_constant_ranges: &[],\n        \
             }});\n",
        name = spec.name
    ));
    out.push_str(&format!(
        "        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::pipeline\"),\n            \
             layout: Some(&pl),\n            \
             module: &shader,\n            \
             entry_point: Some(\"{entry}\"),\n            \
             compilation_options: Default::default(),\n            \
             cache: None,\n        \
             }});\n        \
             Self {{ pipeline, bgl }}\n    }}\n\n",
        name = spec.name,
        entry = spec.entry_point
    ));

    // build_cfg()
    out.push_str(&format!(
        "    fn build_cfg(&self, state: &engine::state::SimState) -> {cfg} {{\n        \
         let _ = state;\n        \
         {build}\n    }}\n\n",
        cfg = spec.cfg_struct,
        build = spec.cfg_build_expr
    ));

    // bind()
    out.push_str(&format!(
        "    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> {pascal}Bindings<'a> {{\n        \
         let _ = sources;\n        \
         {pascal}Bindings {{\n",
        pascal = spec.pascal
    ));
    out.push_str(&compose_bind_body(spec));
    out.push_str("        }\n    }\n\n");

    // record()
    out.push_str(&format!(
        "    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &{pascal}Bindings<'_>, agent_cap: u32) {{\n",
        pascal = spec.pascal
    ));
    out.push_str(&format!(
        "        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::bg\"),\n            \
             layout: &self.bgl,\n            \
             entries: &[\n",
        name = spec.name
    ));
    out.push_str(&lower_rust_bg_entries(spec));
    out.push_str("            ],\n        });\n");
    out.push_str(&format!(
        "        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::pass\"),\n            \
             timestamp_writes: None,\n        \
             }});\n",
        name = spec.name
    ));
    out.push_str("        pass.set_pipeline(&self.pipeline);\n");
    out.push_str("        pass.set_bind_group(0, &bg, &[]);\n");
    out.push_str(&compose_dispatch_call(topology));
    out.push_str("    }\n");

    out.push_str("}\n");
    out
}

/// Render the BGL entries for a CG-emitted kernel, routing through the
/// CG-side helpers `crate::bgl_storage` / `crate::bgl_uniform` defined
/// in the synthesized `lib.rs`. Distinct from
/// [`crate::kernel_lowerings::lower_rust_bgl_entries`] which routes
/// through the legacy `crate::fused_mask::bgl_*` path; the legacy
/// path requires the legacy `fused_mask.rs` to define the helpers,
/// which a CG-only output never carries.
fn render_cg_bgl_entries(spec: &KernelSpec) -> String {
    let mut out = String::new();
    for b in &spec.bindings {
        let descriptor = match b.access {
            AccessMode::ReadStorage => format!("crate::bgl_storage({}, true)", b.slot),
            AccessMode::ReadWriteStorage | AccessMode::AtomicStorage => {
                format!("crate::bgl_storage({}, false)", b.slot)
            }
            AccessMode::Uniform => format!("crate::bgl_uniform({})", b.slot),
        };
        writeln!(out, "                {}, // {}", descriptor, b.name)
            .expect("write to String never fails");
    }
    out
}

/// Render the `bindings: <field>: <expr>,` rows for the `bind()`
/// initializer body.
fn compose_bind_body(spec: &KernelSpec) -> String {
    let mut out = String::new();
    for b in &spec.bindings {
        // AliasOf bindings don't have their own struct field; the alias
        // is handled in `lower_rust_bg_entries` at BindGroupEntry time.
        if matches!(b.bg_source, BgSource::AliasOf(_)) {
            continue;
        }
        let value = render_bg_source_expr(&b.bg_source, &b.name);
        out.push_str(&format!("            {field}: {value},\n", field = b.name, value = value));
    }
    out
}

/// Render a [`BgSource`] as the Rust expression that yields the
/// `&'a wgpu::Buffer` used by the `bind()` initializer.
///
/// `field` is the binding's name — used to surface a self-referential
/// fallback for ViewHandle (the generic CG path; today no kernel emits
/// it, so the helper stays defensive).
fn render_bg_source_expr(src: &BgSource, field: &str) -> String {
    match src {
        BgSource::Resident(f) => format!("sources.resident.{f}"),
        BgSource::Transient(f) => format!("sources.transient.{f}"),
        BgSource::External(f) => format!("sources.external.{f}"),
        BgSource::Pool(f) => format!("sources.pool.{f}"),
        BgSource::Cfg => "cfg".to_string(),
        BgSource::ViewHandle { accessor, tuple_idx } => {
            // Defensive: until Task 5.4 wires fold-view tuple
            // destructuring at the kernel-module emit layer, the
            // generic path renders a `<accessor>().<idx>`-style
            // expression. The legacy fold kernels destructure into
            // (primary, anchor, ids) locals; today no CG kernel emits
            // ViewHandle — this arm exists so the composer never falls
            // through to a panic if a future spec does.
            format!(
                "sources.resident.{accessor}().{idx} /* {field} */",
                accessor = accessor,
                idx = tuple_idx
            )
        }
        BgSource::AliasOf(target) => {
            // Defensive — AliasOf bindings are filtered out before this
            // helper is called. If a caller skipped the filter, render
            // a self-evidently routable expression rather than panic.
            format!("/* alias of {target} */ sources.external.sim_cfg")
        }
    }
}

/// Pick the `pass.dispatch_workgroups(...)` line for a kernel based on
/// its topology's [`DispatchShape`].
fn compose_dispatch_call(topology: &KernelTopology) -> String {
    let dispatch = match topology {
        KernelTopology::Fused { dispatch, .. } => *dispatch,
        KernelTopology::Split { dispatch, .. } => *dispatch,
        KernelTopology::Indirect { .. } => DispatchShape::PerEvent {
            source_ring: crate::cg::data_handle::EventRingId(0),
        },
    };
    let wg_x = dispatch.workgroup_size().x;
    match dispatch {
        DispatchShape::OneShot => "        pass.dispatch_workgroups(1, 1, 1);\n".to_string(),
        DispatchShape::PerWord => format!(
            "        let num_words = (agent_cap + 31u32) / 32u32;\n        \
             pass.dispatch_workgroups((num_words + {wg_x_minus_one}u32) / {wg_x}u32, 1, 1);\n",
            wg_x = wg_x,
            wg_x_minus_one = wg_x - 1
        ),
        DispatchShape::PerAgent
        | DispatchShape::PerEvent { .. }
        | DispatchShape::PerPair { .. } => format!(
            "        pass.dispatch_workgroups((agent_cap + {wg_x_minus_one}u32) / {wg_x}u32, 1, 1);\n",
            wg_x = wg_x,
            wg_x_minus_one = wg_x - 1
        ),
    }
}

// ---------------------------------------------------------------------------
// lib.rs synthesis
// ---------------------------------------------------------------------------

/// Build the synthesized `lib.rs` content for the CG-emitted crate.
///
/// `kernel_index` is the schedule-order list of snake_case kernel names
/// (one per emitted module). The output declares each module, re-exports
/// the `<Pascal>Kernel` struct, defines the [`crate::Kernel`] trait,
/// the `KernelKind` registry enum, the `BufferRef` enum, and the
/// `bgl_storage` / `bgl_uniform` helper fns every per-kernel module
/// invokes as `crate::bgl_storage(...)` / `crate::bgl_uniform(...)`.
///
/// The CG-emitted kernel modules use [`render_cg_bgl_entries`] (NOT
/// the legacy `lower_rust_bgl_entries` which routes via
/// `crate::fused_mask::bgl_*`) so the helper paths align with the
/// top-level helpers synthesized here.
///
/// # Limitations
/// - **`mod binding_sources;` is declared but `binding_sources.rs` is
///   not emitted today.** The CG pipeline emits per-kernel modules
///   only; `binding_sources.rs` is hand-authored in the legacy crate
///   and a Task 5.4+ concern for the CG side. A consumer overlaying
///   the CG output on the legacy crate inherits the legacy
///   `binding_sources.rs`; a fresh CG-only crate would need a stub.
/// - **`schedule`, `resident_context`, `pingpong_context`, `pool`,
///   `transient_handles`, `external_buffers` modules are NOT
///   declared.** The legacy `lib.rs` emits them; the CG pipeline does
///   not yet, but every emitted kernel imports `BindingSources` from
///   `binding_sources` (which transitively pulls in the rest). Task
///   5.4+ extends.
/// - **`KernelKind` variants are PascalCase derived from
///   [`snake_to_pascal`].** Two distinct snake names that pascalize to
///   the same identifier (e.g. `foo_bar` and `foo__bar`) would collide
///   here; today the [`super::kernel::semantic_kernel_name`] mapping
///   keeps every name's snake form unique, so pascal collisions are
///   structurally impossible. The synthesized helper has no defensive
///   collision check — adding one is cheap if a future renaming
///   policy makes the invariant fragile.
pub fn synthesize_lib_rs(kernel_index: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push('\n');
    out.push_str("#![allow(clippy::all)]\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push('\n');

    // Per-kernel module declarations + re-exports.
    for name in kernel_index {
        out.push_str(&format!("pub mod {name};\n"));
    }
    out.push('\n');
    for name in kernel_index {
        let pascal = snake_to_pascal(name);
        out.push_str(&format!("pub use {name}::{pascal}Kernel;\n"));
    }
    out.push('\n');

    // binding_sources is required by every emitted kernel; declare it
    // so the path resolution in `use crate::binding_sources::…` works.
    out.push_str("pub mod binding_sources;\n");
    out.push('\n');

    // KernelKind enum.
    out.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]\n");
    out.push_str("pub enum KernelKind {\n");
    for name in kernel_index {
        out.push_str(&format!("    {},\n", snake_to_pascal(name)));
    }
    out.push_str("}\n\n");

    // BufferRef enum (matches legacy lib.rs).
    out.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]\n");
    out.push_str("pub enum BufferRef {\n");
    out.push_str("    /// Resident path indirect-args buffer.\n");
    out.push_str("    ResidentIndirectArgs,\n");
    out.push_str("    /// Cascade-physics event ring tail buffer (gates further iterations when zero).\n");
    out.push_str("    CascadeRingTail,\n");
    out.push_str("}\n\n");

    // Kernel trait.
    out.push_str("pub trait Kernel {\n");
    out.push_str("    type Bindings<'a> where Self: 'a;\n");
    out.push_str("    type Cfg: bytemuck::Pod + bytemuck::Zeroable + Copy;\n\n");
    out.push_str("    fn new(device: &wgpu::Device) -> Self where Self: Sized;\n");
    out.push_str("    fn build_cfg(&self, state: &engine::state::SimState) -> Self::Cfg;\n");
    out.push_str("    fn bind<'a>(&'a self, sources: &'a binding_sources::BindingSources<'a>, cfg: &'a wgpu::Buffer) -> Self::Bindings<'a>;\n");
    out.push_str("    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &Self::Bindings<'_>, agent_cap: u32);\n");
    out.push_str("}\n\n");

    // Shared BGL helpers — pub(crate) so every emitted module can use
    // them via `crate::bgl_storage` / `crate::bgl_uniform`. The legacy
    // emitters route through `crate::fused_mask::bgl_storage`; the
    // [`crate::kernel_lowerings::lower_rust_bgl_entries`] call still
    // emits `crate::fused_mask::bgl_storage(...)` for source compat,
    // and `pub mod fused_mask` re-exports them via the per-module file.
    out.push_str("pub(crate) fn bgl_storage(b: u32, read_only: bool) -> wgpu::BindGroupLayoutEntry {\n");
    out.push_str("    wgpu::BindGroupLayoutEntry {\n");
    out.push_str("        binding: b,\n");
    out.push_str("        visibility: wgpu::ShaderStages::COMPUTE,\n");
    out.push_str("        ty: wgpu::BindingType::Buffer {\n");
    out.push_str("            ty: wgpu::BufferBindingType::Storage { read_only },\n");
    out.push_str("            has_dynamic_offset: false,\n");
    out.push_str("            min_binding_size: None,\n");
    out.push_str("        },\n");
    out.push_str("        count: None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub(crate) fn bgl_uniform(b: u32) -> wgpu::BindGroupLayoutEntry {\n");
    out.push_str("    wgpu::BindGroupLayoutEntry {\n");
    out.push_str("        binding: b,\n");
    out.push_str("        visibility: wgpu::ShaderStages::COMPUTE,\n");
    out.push_str("        ty: wgpu::BindingType::Buffer {\n");
    out.push_str("            ty: wgpu::BufferBindingType::Uniform,\n");
    out.push_str("            has_dynamic_offset: false,\n");
    out.push_str("            min_binding_size: None,\n");
    out.push_str("        },\n");
    out.push_str("        count: None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// Topology → workgroup size
// ---------------------------------------------------------------------------

/// Pick the `@workgroup_size(x)` value a kernel emitted from `topology`
/// should declare. Routes through Task 1.4's
/// [`DispatchShape::workgroup_size`] so the WGSL annotation and the
/// dispatch-count rule never disagree.
///
/// For [`KernelTopology::Indirect`] the consumer's per-event dispatch
/// drives the size — every consumer carries the same `PerEvent` shape,
/// so picking the first is structural (the well-formed pass already
/// guards mismatches).
fn topology_workgroup_size_x(topology: &KernelTopology) -> u32 {
    let dispatch = match topology {
        KernelTopology::Fused { dispatch, .. } => *dispatch,
        KernelTopology::Split { dispatch, .. } => *dispatch,
        KernelTopology::Indirect { consumers: _, .. } => {
            // Indirect-dispatched consumers always carry PerEvent.
            // The well-formed pass guarantees consumers exist; if they
            // don't, the body lowering above would have already errored
            // with `EmptyKernelTopology`.
            DispatchShape::PerEvent {
                source_ring: crate::cg::data_handle::EventRingId(0),
            }
        }
    };
    dispatch.workgroup_size().x
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cg::data_handle::{
        AgentFieldId, AgentRef, CgExprId, DataHandle, EventRingId, MaskId,
    };
    use crate::cg::dispatch::DispatchShape;
    use crate::cg::expr::{BinaryOp, CgExpr, CgTy, LitValue};
    use crate::cg::lower::lower_compilation_to_cg;
    use crate::cg::op::{
        ComputeOp, ComputeOpKind, EventKindId, OpId, PhysicsRuleId, PlumbingKind,
        ReplayabilityFlag, Span,
    };
    use crate::cg::schedule::synthesis::{
        synthesize_schedule, ComputeStage, KernelTopology,
    };
    use crate::cg::schedule::ScheduleStrategy;
    use crate::cg::stmt::{CgStmt, CgStmtId, CgStmtList, CgStmtListId};
    use dsl_ast::ir::Compilation;

    // -- Test fixtures ---------------------------------------------------

    fn push_op(prog: &mut CgProgram, mut op: ComputeOp) -> OpId {
        let id = OpId(prog.ops.len() as u32);
        op.id = id;
        prog.ops.push(op);
        id
    }

    fn push_expr(prog: &mut CgProgram, e: CgExpr) -> CgExprId {
        let id = CgExprId(prog.exprs.len() as u32);
        prog.exprs.push(e);
        id
    }

    fn push_stmt(prog: &mut CgProgram, s: CgStmt) -> CgStmtId {
        let id = CgStmtId(prog.stmts.len() as u32);
        prog.stmts.push(s);
        id
    }

    fn push_list(prog: &mut CgProgram, l: CgStmtList) -> CgStmtListId {
        let id = CgStmtListId(prog.stmt_lists.len() as u32);
        prog.stmt_lists.push(l);
        id
    }

    /// Build a single MaskPredicate op `mask[m] = (self.hp < 5.0)`.
    fn mask_op(prog: &mut CgProgram, mask: MaskId) -> OpId {
        let hp = push_expr(
            prog,
            CgExpr::Read(DataHandle::AgentField {
                field: AgentFieldId::Hp,
                target: AgentRef::Self_,
            }),
        );
        let five = push_expr(prog, CgExpr::Lit(LitValue::F32(5.0)));
        let lt = push_expr(
            prog,
            CgExpr::Binary {
                op: BinaryOp::LtF32,
                lhs: hp,
                rhs: five,
                ty: CgTy::Bool,
            },
        );
        let kind = ComputeOpKind::MaskPredicate {
            mask,
            predicate: lt,
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::PerAgent,
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    /// Build a PhysicsRule op `self.hp = self.hp + 1.0` over `ring`.
    fn physics_op(prog: &mut CgProgram, rule: PhysicsRuleId, ring: EventRingId) -> OpId {
        let hp_read = push_expr(
            prog,
            CgExpr::Read(DataHandle::AgentField {
                field: AgentFieldId::Hp,
                target: AgentRef::Self_,
            }),
        );
        let one = push_expr(prog, CgExpr::Lit(LitValue::F32(1.0)));
        let add = push_expr(
            prog,
            CgExpr::Binary {
                op: BinaryOp::AddF32,
                lhs: hp_read,
                rhs: one,
                ty: CgTy::F32,
            },
        );
        let assign = push_stmt(
            prog,
            CgStmt::Assign {
                target: DataHandle::AgentField {
                    field: AgentFieldId::Hp,
                    target: AgentRef::Self_,
                },
                value: add,
            },
        );
        let body = push_list(prog, CgStmtList { stmts: vec![assign] });
        let kind = ComputeOpKind::PhysicsRule {
            rule,
            on_event: EventKindId(0),
            body,
            replayable: ReplayabilityFlag::Replayable,
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::PerEvent { source_ring: ring },
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    fn seed_indirect_op(prog: &mut CgProgram, ring: EventRingId) -> OpId {
        let kind = ComputeOpKind::Plumbing {
            kind: PlumbingKind::SeedIndirectArgs { ring },
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::OneShot,
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    /// Wrap a single kernel topology into a one-stage schedule.
    fn one_stage(topology: KernelTopology) -> ComputeSchedule {
        ComputeSchedule {
            stages: vec![ComputeStage {
                kernels: vec![topology],
            }],
        }
    }

    // ---- 1. Empty schedule ----

    #[test]
    fn empty_schedule_yields_only_lib_rs_artifact() {
        // An empty schedule still synthesizes `lib.rs` (the kernel
        // registry + Kernel trait + bgl helpers) so the side-channel
        // output is always a self-contained Rust crate. No per-kernel
        // wgsl/rust files are produced.
        let prog = CgProgram::default();
        let schedule = ComputeSchedule { stages: vec![] };
        let artifacts = emit_cg_program(&schedule, &prog).expect("empty schedule must succeed");
        assert!(artifacts.wgsl_files.is_empty(), "wgsl: {:?}", artifacts.wgsl_files);
        // `lib.rs` is the only Rust file emitted for an empty schedule.
        assert_eq!(
            artifacts.rust_files.keys().collect::<Vec<_>>(),
            vec![&"lib.rs".to_string()],
            "rust: {:?}",
            artifacts.rust_files.keys().collect::<Vec<_>>()
        );
        assert!(artifacts.kernel_index.is_empty(), "index: {:?}", artifacts.kernel_index);
        // The synthesized lib content carries the trait + helpers even
        // when no kernels are emitted.
        let lib = &artifacts.rust_files["lib.rs"];
        assert!(lib.contains("pub trait Kernel"), "lib: {lib}");
        assert!(lib.contains("pub(crate) fn bgl_storage"), "lib: {lib}");
        assert!(lib.contains("pub(crate) fn bgl_uniform"), "lib: {lib}");
    }

    // ---- 2. Single Split kernel ----

    #[test]
    fn single_split_kernel_produces_one_wgsl_and_one_rust_file() {
        let mut prog = CgProgram::default();
        let op = mask_op(&mut prog, MaskId(7));
        let topology = KernelTopology::Split {
            op,
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("single split must succeed");

        assert_eq!(artifacts.wgsl_files.len(), 1);
        // One per-kernel file plus the synthesized `lib.rs`.
        assert_eq!(artifacts.rust_files.len(), 2);
        assert!(artifacts.rust_files.contains_key("lib.rs"));
        assert_eq!(artifacts.kernel_index.len(), 1);

        // Filenames key by `<kernel_name>.wgsl` / `.rs`.
        let kernel_name = &artifacts.kernel_index[0];
        let wgsl_key = format!("{kernel_name}.wgsl");
        let rs_key = format!("{kernel_name}.rs");
        assert!(
            artifacts.wgsl_files.contains_key(&wgsl_key),
            "wgsl files: {:?}",
            artifacts.wgsl_files.keys().collect::<Vec<_>>()
        );
        assert!(
            artifacts.rust_files.contains_key(&rs_key),
            "rust files: {:?}",
            artifacts.rust_files.keys().collect::<Vec<_>>()
        );

        // WGSL file contains the @compute annotation + the binding decl.
        let wgsl = &artifacts.wgsl_files[&wgsl_key];
        assert!(wgsl.contains("@compute @workgroup_size(64)"), "wgsl: {wgsl}");
        assert!(wgsl.contains("@group(0) @binding(0)"), "wgsl: {wgsl}");
        assert!(
            wgsl.contains(&format!("fn cs_{kernel_name}")),
            "wgsl missing entry point: {wgsl}"
        );

        // Rust file contains the bindings struct + cfg struct decl.
        let rs = &artifacts.rust_files[&rs_key];
        assert!(rs.contains("pub struct"), "rs missing struct: {rs}");
        assert!(rs.contains("Bindings<'a>"), "rs missing Bindings: {rs}");
        assert!(rs.contains("_bgl_entries"), "rs missing bgl_entries: {rs}");
        assert!(rs.contains("_build_cfg"), "rs missing build_cfg: {rs}");
    }

    // ---- 3. Multi-stage schedule ----

    #[test]
    fn multi_stage_schedule_emits_all_kernels() {
        let mut prog = CgProgram::default();
        let m0 = mask_op(&mut prog, MaskId(0));
        let m1 = mask_op(&mut prog, MaskId(1));
        // Two Fused topologies in two stages over distinct mask ids —
        // semantic names (`fused_mask_0` / `fused_mask_1`) diverge.
        let stage_a = KernelTopology::Fused {
            ops: vec![m0],
            dispatch: DispatchShape::PerAgent,
        };
        let stage_b = KernelTopology::Fused {
            ops: vec![m1, m1],
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = ComputeSchedule {
            stages: vec![
                ComputeStage {
                    kernels: vec![stage_a],
                },
                ComputeStage {
                    kernels: vec![stage_b],
                },
            ],
        };
        let artifacts = emit_cg_program(&schedule, &prog).expect("multi-stage emit");
        assert_eq!(artifacts.wgsl_files.len(), 2);
        // Two per-kernel files + the synthesized `lib.rs`.
        assert_eq!(artifacts.rust_files.len(), 3);
        assert!(artifacts.rust_files.contains_key("lib.rs"));
        assert_eq!(artifacts.kernel_index.len(), 2);

        // Index entries are unique snake_case kernel names.
        let mut sorted = artifacts.kernel_index.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(sorted.len(), 2, "names must be unique: {:?}", artifacts.kernel_index);
    }

    // ---- 4. Snapshot — a non-trivial Rust module's full output ----

    #[test]
    fn snapshot_split_mask_predicate_rust_module() {
        let mut prog = CgProgram::default();
        let op = mask_op(&mut prog, MaskId(3));
        let topology = KernelTopology::Split {
            op,
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("snapshot emit");

        let rs_key = format!("{}.rs", artifacts.kernel_index[0]);
        let rs = &artifacts.rust_files[&rs_key];

        // Pin every section's distinguishing line. A regression in any
        // single section will break exactly one of these asserts.
        assert!(rs.contains("// GENERATED by dsl_compiler"), "rs: {rs}");
        assert!(rs.contains("#[repr(C)]"), "missing #[repr(C)]: {rs}");
        assert!(rs.contains("bytemuck::Pod"), "missing Pod derive: {rs}");
        assert!(rs.contains("pub agent_hp: &'a wgpu::Buffer,"), "missing agent_hp: {rs}");
        assert!(rs.contains("pub mask_3_bitmap: &'a wgpu::Buffer,"), "missing mask_3_bitmap: {rs}");
        assert!(rs.contains("pub cfg: &'a wgpu::Buffer,"), "missing cfg field: {rs}");
        // CG-emitted modules route through top-level `crate::bgl_storage`
        // / `crate::bgl_uniform` (defined in the synthesized `lib.rs`),
        // distinct from the legacy `crate::fused_mask::bgl_*` path.
        assert!(
            rs.contains("crate::bgl_storage(0, true)"),
            "missing bgl entry slot 0: {rs}"
        );
        assert!(
            rs.contains("crate::bgl_uniform(2)"),
            "missing bgl uniform: {rs}"
        );
        assert!(
            rs.contains("wgpu::BindGroupEntry { binding: 0,"),
            "missing bg entry slot 0: {rs}"
        );
        assert!(rs.contains("state.agent_cap()"), "missing build_cfg: {rs}");
        // The Kernel trait impl carries real bodies — no panics.
        assert!(rs.contains("impl crate::Kernel for"), "missing trait impl: {rs}");
        assert!(
            !rs.contains("unimplemented!"),
            "trait impl must not contain unimplemented!(): {rs}"
        );
        assert!(!rs.contains("todo!()"), "trait impl must not contain todo!(): {rs}");
        assert!(rs.contains("fn new("), "missing Kernel::new: {rs}");
        assert!(rs.contains("fn build_cfg("), "missing Kernel::build_cfg: {rs}");
        assert!(rs.contains("fn bind<"), "missing Kernel::bind: {rs}");
        assert!(rs.contains("fn record("), "missing Kernel::record: {rs}");
        assert!(
            rs.contains("dispatch_workgroups("),
            "record body should dispatch: {rs}"
        );
    }

    // ---- 5. Name collision ----

    #[test]
    fn duplicate_kernels_yield_typed_collision_error() {
        // Two singleton kernels over the SAME mask id produce identical
        // semantic names (`mask_<n>`) — the collision detector should
        // flag the second one. With semantic naming over distinct mask
        // ids the names diverge cleanly; the collision branch only
        // fires on a real ambiguity, but the defensive check must still
        // surface it as a typed error rather than silently overwriting.
        let mut prog = CgProgram::default();
        let m_first = mask_op(&mut prog, MaskId(7));
        let m_second = mask_op(&mut prog, MaskId(7));
        let stage_a = KernelTopology::Split {
            op: m_first,
            dispatch: DispatchShape::PerAgent,
        };
        let stage_b = KernelTopology::Split {
            op: m_second,
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = ComputeSchedule {
            stages: vec![
                ComputeStage {
                    kernels: vec![stage_a],
                },
                ComputeStage {
                    kernels: vec![stage_b],
                },
            ],
        };
        let err = emit_cg_program(&schedule, &prog).expect_err("collision must surface");
        match err {
            ProgramEmitError::KernelNameCollision {
                ref name,
                first_at,
                second_at,
            } => {
                assert_eq!(first_at, (0, 0));
                assert_eq!(second_at, (1, 0));
                assert_eq!(name, "mask_7", "name: {name}");
            }
            other => panic!("expected KernelNameCollision, got {other:?}"),
        }
    }

    // ---- 6. Determinism ----

    #[test]
    fn program_emit_is_deterministic() {
        let build = || {
            let mut prog = CgProgram::default();
            let a = mask_op(&mut prog, MaskId(2));
            let b = mask_op(&mut prog, MaskId(0));
            let topology = KernelTopology::Fused {
                ops: vec![a, b],
                dispatch: DispatchShape::PerAgent,
            };
            let schedule = one_stage(topology);
            emit_cg_program(&schedule, &prog).expect("emit must succeed")
        };
        let lhs = build();
        let rhs = build();
        assert_eq!(lhs.wgsl_files, rhs.wgsl_files);
        assert_eq!(lhs.rust_files, rhs.rust_files);
        assert_eq!(lhs.kernel_index, rhs.kernel_index);
    }

    // ---- 7. Driver round-trip — synthetic Compilation through the full pipeline ----

    #[test]
    fn driver_roundtrip_lowers_synthesizes_and_emits() {
        // Empty Compilation → CgProgram (only plumbing ops) →
        // ComputeSchedule → EmittedArtifacts. Validates the wiring of
        // the full Phase 2 → Phase 3 → Phase 4 → Task-5.2 lib synth
        // pipeline end-to-end: every type along the path agrees, every
        // helper is reachable from emit_cg_program, inner-walk failures
        // bubble through as typed errors, and the synthesized `lib.rs`
        // is present alongside the per-kernel files.
        //
        // The empty Compilation lowers to a handful of always-on
        // plumbing ops (UploadSimCfg / PackAgents / UnpackAgents /
        // KickSnapshot) — each becomes its own Split kernel. With Task
        // 5.2's semantic naming, each plumbing kind maps to a distinct
        // kernel name (`upload_sim_cfg`, `pack_agents`, …), so the emit
        // succeeds without collision.
        let comp = Compilation::default();
        let prog = lower_compilation_to_cg(&comp).expect("empty Compilation must lower");
        let synthesis = synthesize_schedule(&prog, ScheduleStrategy::Default);

        let artifacts = emit_cg_program(&synthesis.schedule, &prog)
            .expect("driver round-trip emit must succeed with semantic naming");
        assert_eq!(
            artifacts.kernel_index.len(),
            synthesis.schedule.kernel_count(),
            "every kernel in the schedule must produce one index entry"
        );
        assert_eq!(
            artifacts.wgsl_files.len(),
            artifacts.kernel_index.len(),
            "one wgsl file per kernel"
        );
        // Per-kernel rust files + the synthesized `lib.rs`.
        assert_eq!(
            artifacts.rust_files.len(),
            artifacts.kernel_index.len() + 1,
            "one rust file per kernel + lib.rs"
        );
        assert!(artifacts.rust_files.contains_key("lib.rs"), "lib.rs missing");
    }

    // ---- 8. Indirect topology emits the consumer kernel ----

    #[test]
    fn indirect_topology_emits_one_consumer_file() {
        let mut prog = CgProgram::default();
        let ring = EventRingId(2);
        let producer = seed_indirect_op(&mut prog, ring);
        let consumer = physics_op(&mut prog, PhysicsRuleId(0), ring);
        let topology = KernelTopology::Indirect {
            producer,
            consumers: vec![consumer],
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("indirect emit");
        assert_eq!(artifacts.kernel_index.len(), 1);

        // The consumer kernel uses workgroup_size(64) (PerEvent rule).
        let wgsl = artifacts.wgsl_files.values().next().unwrap();
        assert!(
            wgsl.contains("@compute @workgroup_size(64)"),
            "wgsl: {wgsl}"
        );
    }

    // ---- 9. Lowering errors propagate as ProgramEmitError::KernelLowering ----

    #[test]
    fn op_id_out_of_range_surfaces_as_kernel_lowering_error() {
        let prog = CgProgram::default();
        let topology = KernelTopology::Split {
            op: OpId(99),
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let err = emit_cg_program(&schedule, &prog).expect_err("invalid op-id must error");
        match err {
            ProgramEmitError::KernelLowering {
                stage_index,
                kernel_index,
                error,
            } => {
                assert_eq!(stage_index, 0);
                assert_eq!(kernel_index, 0);
                assert!(
                    matches!(error, KernelEmitError::OpIdOutOfRange { .. }),
                    "inner error was {error:?}"
                );
            }
            other => panic!("expected KernelLowering, got {other:?}"),
        }
    }

    // ---- 10. WGSL file structure ----

    #[test]
    fn wgsl_file_has_header_bindings_and_entry_point() {
        let mut prog = CgProgram::default();
        let op = mask_op(&mut prog, MaskId(5));
        let topology = KernelTopology::Split {
            op,
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("emit");
        let wgsl = artifacts.wgsl_files.values().next().unwrap();

        assert!(wgsl.starts_with("// GENERATED"), "header: {wgsl}");
        assert!(wgsl.contains("@group(0) @binding("), "bindings: {wgsl}");
        assert!(wgsl.contains("@compute @workgroup_size("), "compute: {wgsl}");
        assert!(wgsl.contains("agent_id = gid.x"), "preamble: {wgsl}");
        assert!(wgsl.contains("mask_5_bitmap"), "body wiring: {wgsl}");
        // File ends with closing brace + newline.
        assert!(wgsl.ends_with("}\n"), "trailing: {:?}", &wgsl[wgsl.len().saturating_sub(20)..]);
    }

    // ---- 11. lib.rs synthesis (Task 5.2) ----

    #[test]
    fn synthesize_lib_rs_for_empty_kernel_index() {
        let lib = synthesize_lib_rs(&[]);
        // No `pub mod`s when no kernels — but the trait + helpers + the
        // `binding_sources` shim still appear.
        assert!(lib.contains("pub trait Kernel"), "trait missing: {lib}");
        assert!(
            lib.contains("pub(crate) fn bgl_storage(b: u32, read_only: bool)"),
            "bgl_storage missing: {lib}"
        );
        assert!(
            lib.contains("pub(crate) fn bgl_uniform(b: u32)"),
            "bgl_uniform missing: {lib}"
        );
        assert!(
            lib.contains("pub mod binding_sources;"),
            "binding_sources mod missing: {lib}"
        );
        assert!(
            lib.contains("pub enum KernelKind {"),
            "KernelKind enum missing: {lib}"
        );
        assert!(
            lib.contains("pub enum BufferRef"),
            "BufferRef enum missing: {lib}"
        );
        assert!(
            lib.contains("ResidentIndirectArgs"),
            "BufferRef::ResidentIndirectArgs missing: {lib}"
        );
        // Header line for diff readability.
        assert!(
            lib.starts_with("// GENERATED by dsl_compiler"),
            "header missing: {lib}"
        );
    }

    #[test]
    fn synthesize_lib_rs_emits_module_decl_and_pub_use_per_kernel() {
        let names = vec![
            "fused_mask".to_string(),
            "scoring".to_string(),
            "fold_threat_level".to_string(),
        ];
        let lib = synthesize_lib_rs(&names);
        // Module declarations.
        assert!(lib.contains("pub mod fused_mask;"), "{lib}");
        assert!(lib.contains("pub mod scoring;"), "{lib}");
        assert!(lib.contains("pub mod fold_threat_level;"), "{lib}");
        // Per-kernel re-exports of `<Pascal>Kernel`.
        assert!(lib.contains("pub use fused_mask::FusedMaskKernel;"), "{lib}");
        assert!(lib.contains("pub use scoring::ScoringKernel;"), "{lib}");
        assert!(
            lib.contains("pub use fold_threat_level::FoldThreatLevelKernel;"),
            "{lib}"
        );
        // KernelKind variants in PascalCase.
        assert!(lib.contains("    FusedMask,"), "{lib}");
        assert!(lib.contains("    Scoring,"), "{lib}");
        assert!(lib.contains("    FoldThreatLevel,"), "{lib}");
    }

    #[test]
    fn synthesize_lib_rs_is_deterministic() {
        let names = vec!["a".to_string(), "b".to_string(), "c".to_string()];
        assert_eq!(synthesize_lib_rs(&names), synthesize_lib_rs(&names));
    }

    // ---- 12. Kernel trait impl emission (Task 5.2) ----

    #[test]
    fn kernel_trait_impl_emitted_with_real_bodies() {
        let mut prog = CgProgram::default();
        let op = mask_op(&mut prog, MaskId(0));
        prog.interner.masks.insert(0, "low_health".to_string());
        let topology = KernelTopology::Split {
            op,
            dispatch: DispatchShape::PerAgent,
        };
        let schedule = one_stage(topology);
        let artifacts = emit_cg_program(&schedule, &prog).expect("emit");
        let rs = artifacts
            .rust_files
            .get("mask_low_health.rs")
            .expect("kernel rust file");

        // Trait impl signature.
        assert!(rs.contains("impl crate::Kernel for MaskLowHealthKernel"), "{rs}");
        assert!(rs.contains("type Bindings<'a> = MaskLowHealthBindings<'a>;"), "{rs}");
        assert!(rs.contains("type Cfg = MaskLowHealthCfg;"), "{rs}");

        // Each method emitted with a real body.
        assert!(rs.contains("fn new(device: &wgpu::Device) -> Self"), "{rs}");
        assert!(rs.contains("device.create_shader_module"), "{rs}");
        assert!(rs.contains("device.create_compute_pipeline"), "{rs}");
        assert!(rs.contains("entry_point: Some(\"cs_mask_low_health\")"), "{rs}");

        assert!(
            rs.contains("fn build_cfg(&self, state: &engine::state::SimState) -> MaskLowHealthCfg"),
            "{rs}"
        );

        assert!(
            rs.contains("fn bind<'a>(&'a self, sources: &'a BindingSources<'a>"),
            "{rs}"
        );
        assert!(rs.contains("MaskLowHealthBindings {"), "{rs}");

        assert!(
            rs.contains("fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder"),
            "{rs}"
        );
        assert!(rs.contains("encoder.begin_compute_pass"), "{rs}");
        assert!(rs.contains("pass.set_pipeline(&self.pipeline);"), "{rs}");
        assert!(rs.contains("pass.dispatch_workgroups("), "{rs}");

        // No panicking placeholders.
        assert!(!rs.contains("unimplemented!"), "{rs}");
        assert!(!rs.contains("todo!()"), "{rs}");
        assert!(!rs.contains("panic!("), "{rs}");
    }

    #[test]
    fn kernel_trait_impl_dispatch_call_matches_topology() {
        // PerAgent → ((agent_cap + 63) / 64, 1, 1).
        // OneShot → (1, 1, 1).
        // PerWord → num_words / wg_x.
        let mut prog = CgProgram::default();
        let op = mask_op(&mut prog, MaskId(0));
        let schedule = one_stage(KernelTopology::Split {
            op,
            dispatch: DispatchShape::PerAgent,
        });
        let artifacts = emit_cg_program(&schedule, &prog).expect("emit");
        let rs = artifacts.rust_files.values().find(|s| s.contains("impl crate::Kernel")).unwrap();
        assert!(
            rs.contains("dispatch_workgroups((agent_cap + 63u32) / 64u32, 1, 1)"),
            "PerAgent dispatch line missing: {rs}"
        );

        // OneShot via a kick_snapshot plumbing op.
        let mut prog2 = CgProgram::default();
        let op2 = ComputeOp::new(
            OpId(0),
            ComputeOpKind::Plumbing {
                kind: PlumbingKind::KickSnapshot,
            },
            DispatchShape::OneShot,
            Span::dummy(),
            &prog2,
            &prog2,
            &prog2,
        );
        let id2 = push_op(&mut prog2, op2);
        let schedule2 = one_stage(KernelTopology::Split {
            op: id2,
            dispatch: DispatchShape::OneShot,
        });
        let artifacts2 = emit_cg_program(&schedule2, &prog2).expect("emit");
        let rs2 = artifacts2
            .rust_files
            .values()
            .find(|s| s.contains("impl crate::Kernel"))
            .unwrap();
        assert!(
            rs2.contains("dispatch_workgroups(1, 1, 1)"),
            "OneShot dispatch line missing: {rs2}"
        );
    }

    #[test]
    fn no_collision_on_synthesized_plumbing_kernels() {
        // Driver-roundtrip in the wild: Compilation::default() lowers
        // to a set of plumbing ops. With semantic naming each plumbing
        // kind gets its own kernel name — no collision should fire.
        let comp = Compilation::default();
        let prog = lower_compilation_to_cg(&comp).expect("lower");
        let synthesis = synthesize_schedule(&prog, ScheduleStrategy::Default);
        let artifacts = emit_cg_program(&synthesis.schedule, &prog)
            .expect("semantic naming should resolve plumbing-collision");
        // Sanity: every kernel name is unique.
        let mut seen = std::collections::BTreeSet::new();
        for name in &artifacts.kernel_index {
            assert!(seen.insert(name.clone()), "duplicate name in index: {name}");
        }
    }
}
