//! Full-program emission — Task 4.3.
//!
//! Walks every kernel in a [`ComputeSchedule`] and produces the file
//! set the xtask writes into `crates/engine_gpu_rules/src/`. Each
//! kernel becomes one `.wgsl` file (the WGSL kernel source) plus one
//! `.rs` file (the Rust kernel module that owns the pipeline, BGL,
//! `Bindings` struct, `bind()`, and `build_cfg()`).
//!
//! # Pipeline
//!
//! ```text
//!   ComputeSchedule  ─┐
//!                     ├─►  emit_cg_program  ─►  EmittedArtifacts
//!   CgProgram        ─┘                           ├─ wgsl_files: BTreeMap<String, String>
//!                                                 ├─ rust_files: BTreeMap<String, String>
//!                                                 └─ kernel_index: Vec<String>
//! ```
//!
//! For each `(stage, kernel)` pair this calls Task 4.2's
//! [`kernel_topology_to_spec_and_body`] to obtain the `(KernelSpec,
//! body)` pair, then runs the four
//! [`crate::kernel_lowerings::lower_*`] helpers — drift across the
//! WGSL and Rust outputs is structurally impossible because every
//! string derives from the same [`KernelSpec`].
//!
//! # Determinism
//!
//! Outputs are byte-identical across runs:
//! - [`BTreeMap`] preserves sorted iteration order.
//! - The schedule iteration is deterministic (Task 3.x guarantees a
//!   stable stage list).
//! - All inner lowerings ([`crate::kernel_lowerings`], Task 4.1's
//!   walks, Task 4.2's spec lowering) are deterministic.
//!
//! The `program_emit_is_deterministic` test pins the contract.
//!
//! # Limitations
//!
//! - **Inherits Task 4.2's body limitations.** Placeholder bodies for
//!   [`crate::cg::op::ComputeOpKind::ScoringArgmax`],
//!   [`crate::cg::op::ComputeOpKind::SpatialQuery`], and
//!   [`crate::cg::op::ComputeOpKind::Plumbing`] are emitted as
//!   documented `// TODO(task-X.Y)` comment lines, not panics. The cfg
//!   uniform's struct shape is a placeholder
//!   `{ agent_cap: u32, _pad: [u32; 3] }`.
//! - **Kernel names are semantic** (`fused_mask`, `scoring`,
//!   `fold_<view>`, `physics_<rule>`, `spatial_<query>`,
//!   `alive_pack` / `seed_indirect_<ring>` / …). See
//!   [`super::kernel::semantic_kernel_name`] for the full mapping.
//! - **`Kernel` trait `impl`, `lib.rs`, and `bgl_storage` /
//!   `bgl_uniform` helpers are emitted as of Task 5.2.** The
//!   `lib.rs` content is keyed under `"lib.rs"` in
//!   [`EmittedArtifacts::rust_files`] (xtask writes it as
//!   `<src>/lib.rs`). The trait `impl` body uses
//!   `pass.dispatch_workgroups(...)` derived from the topology's
//!   [`DispatchShape::workgroup_size`]; indirect-dispatch wiring (real
//!   `dispatch_workgroups_indirect`) is a Task 5.4+ concern — today the
//!   record body emits the agent-cap-bounded direct dispatch the
//!   legacy emitters use as their stub.
//! - **Output file format approximates legacy emit; exact byte-for-byte
//!   parity with the hand-written `crates/engine_gpu_rules/src/<k>.{rs,wgsl}`
//!   files is later cross-cutting work (Task 5.4+).** Differences in
//!   this commit:
//!   - Header comment is `// GENERATED by dsl_compiler — do not edit
//!     by hand.` rather than the legacy
//!     `// GENERATED by dsl_compiler::emit_<...>. ...`.
//!   - The `Kernel::new` body uses `include_str!("<name>.wgsl")` for
//!     the WGSL source — works when xtask writes both files into the
//!     same directory.
//! - **`kernel_index` is a flat `Vec`.** The synthesized `lib.rs`
//!   walks it to produce the `mod <name>;` + `pub use` lines.
//! - **Name-collision detection is a defensive safety net.** Distinct
//!   ops with distinct semantic identities (mask name, view name,
//!   rule name) produce distinct kernel names. The collision check
//!   only fires on a real ambiguity — e.g. two ops referencing the
//!   same mask id — and surfaces as a typed error rather than
//!   silently overwriting.

use std::collections::BTreeMap;
use std::fmt;

use std::fmt::Write as _;

use crate::cg::dispatch::DispatchShape;
use crate::cg::program::CgProgram;
use crate::cg::schedule::synthesis::{ComputeSchedule, KernelTopology};
use crate::kernel_binding_ir::{snake_to_pascal, AccessMode, BgSource, KernelKind, KernelSpec};
use crate::kernel_lowerings::{
    lower_rust_bg_entries, lower_rust_bindings_struct_fields, lower_wgsl_bindings,
};

use super::kernel::{kernel_topology_to_spec_and_body, KernelEmitError};
use super::wgsl_body::{EmitCtx, HandleNamingStrategy};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// The set of emitted source artifacts produced by [`emit_cg_program`].
///
/// File-name keys carry the basename only (e.g. `fused_mask.wgsl`); the
/// xtask resolves them under `crates/engine_gpu_rules/src/`. Both maps
/// use [`BTreeMap`] so iteration is deterministic across runs.
#[derive(Debug, Clone, Default, Eq, PartialEq)]
pub struct EmittedArtifacts {
    /// Per-kernel WGSL file content. Key is the output filename
    /// (`<kernel_name>.wgsl`); value is the full file contents.
    pub wgsl_files: BTreeMap<String, String>,
    /// Per-kernel Rust module content. Key is the output filename
    /// (`<kernel_name>.rs`); value is the full file contents.
    pub rust_files: BTreeMap<String, String>,
    /// Index of all kernels in schedule order — each entry is the
    /// kernel's snake_case name. Useful for building a `mod.rs` /
    /// `lib.rs` registry (Task 5.1).
    pub kernel_index: Vec<String>,
}

/// Errors that can surface from [`emit_cg_program`]. Every variant
/// carries typed payload — no free-form `String` reasons.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProgramEmitError {
    /// A [`KernelTopology`] failed to lower to a [`KernelSpec`]. The
    /// `(stage_index, kernel_index)` locates the failing kernel inside
    /// the schedule.
    KernelLowering {
        stage_index: usize,
        kernel_index: usize,
        error: KernelEmitError,
    },
    /// Two kernels in the same schedule produced the same name. With
    /// Task 5.2's semantic naming distinct ops with distinct semantic
    /// identities (mask name, view name, rule name, etc.) produce
    /// distinct kernel names; this branch only fires on a real
    /// ambiguity — e.g. two ops referencing the same mask id, or two
    /// fused kernels whose first op produces the same name. The
    /// collision is surfaced as a typed error rather than silently
    /// overwriting one of the files.
    KernelNameCollision {
        name: String,
        first_at: (usize, usize),
        second_at: (usize, usize),
    },
}

impl fmt::Display for ProgramEmitError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ProgramEmitError::KernelLowering {
                stage_index,
                kernel_index,
                error,
            } => write!(
                f,
                "kernel emit failed at stage[{stage_index}].kernels[{kernel_index}]: {error}"
            ),
            ProgramEmitError::KernelNameCollision {
                name,
                first_at,
                second_at,
            } => write!(
                f,
                "kernel name collision: `{name}` first emitted at \
                 stage[{}].kernels[{}], collided at stage[{}].kernels[{}]",
                first_at.0, first_at.1, second_at.0, second_at.1
            ),
        }
    }
}

impl std::error::Error for ProgramEmitError {}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Emit the full set of WGSL + Rust source files for a
/// [`ComputeSchedule`].
///
/// Walks every kernel in every stage, lowers each to a `(KernelSpec,
/// body)` pair via Task 4.2's [`kernel_topology_to_spec_and_body`], and
/// composes the WGSL + Rust file contents using the four
/// [`crate::kernel_lowerings::lower_*`] helpers.
///
/// # Errors
///
/// - [`ProgramEmitError::KernelLowering`] — any kernel's spec lowering
///   raised a typed [`KernelEmitError`] (op-id out-of-range, empty
///   topology, inner-walk arena failure, spec-validation failure).
/// - [`ProgramEmitError::KernelNameCollision`] — two kernels in the
///   schedule produced the same snake_case name. (See `# Limitations`
///   on the module-level docs.)
pub fn emit_cg_program(
    schedule: &ComputeSchedule,
    prog: &CgProgram,
) -> Result<EmittedArtifacts, ProgramEmitError> {
    let mut wgsl_files: BTreeMap<String, String> = BTreeMap::new();
    let mut rust_files: BTreeMap<String, String> = BTreeMap::new();
    let mut kernel_index: Vec<String> = Vec::new();
    let mut seen_names: BTreeMap<String, (usize, usize)> = BTreeMap::new();

    let ctx = EmitCtx {
        prog,
        naming: HandleNamingStrategy::Structural,
        tile_walk_index: std::cell::RefCell::new(None),
        dispatch: std::cell::Cell::new(None),
        view_target_locals: std::cell::RefCell::new(Vec::new()),
        pending_target_lets: std::cell::RefCell::new(Vec::new()),
        bound_target_exprs: std::cell::RefCell::new(std::collections::HashSet::new()),
    };

    for (stage_idx, stage) in schedule.stages.iter().enumerate() {
        for (kernel_idx, topology) in stage.kernels.iter().enumerate() {
            let (spec, body) = kernel_topology_to_spec_and_body(topology, prog, &ctx).map_err(
                |error| ProgramEmitError::KernelLowering {
                    stage_index: stage_idx,
                    kernel_index: kernel_idx,
                    error,
                },
            )?;

            if let Some(prior) = seen_names.get(&spec.name) {
                return Err(ProgramEmitError::KernelNameCollision {
                    name: spec.name.clone(),
                    first_at: *prior,
                    second_at: (stage_idx, kernel_idx),
                });
            }
            seen_names.insert(spec.name.clone(), (stage_idx, kernel_idx));

            let wgsl = compose_wgsl_file(&spec, &body, topology, prog);
            wgsl_files.insert(format!("{}.wgsl", spec.name), wgsl);

            let rs = compose_rust_module_file(&spec, topology);
            rust_files.insert(format!("{}.rs", spec.name), rs);

            kernel_index.push(spec.name.clone());
        }
    }

    // Synthesize lib.rs (per-kernel `pub mod` declarations only;
    // Kernel trait + bgl helpers now live in `engine::gpu` —
    // hand-written platform infrastructure, not compiler-emitted).
    rust_files.insert("lib.rs".to_string(), synthesize_lib_rs(&kernel_index));

    // Synthesize the per-fixture cross-cutting modules. Each becomes
    // a `<name>.rs` entry under `<crate>/src/generated/`; lib.rs
    // declares each via `pub mod <name>;`.
    //
    // Phase 7 boids GPU pipeline (2026-05-02): dropped the wolf-sim-
    // shaped runtime container synthesizers — `binding_sources`,
    // `resident_context`, `external_buffers`, `transient_handles`,
    // `pingpong_context`, `pool`. Per-fixture runtime crates own
    // their own buffers and construct each kernel's `Bindings`
    // directly with explicit `&wgpu::Buffer` refs; the deleted
    // containers were a wolf-sim-runtime-specific aggregation pattern
    // that doesn't fit per-field-buffer fixtures like boids.
    rust_files.insert(
        "schedule.rs".to_string(),
        super::cross_cutting::synthesize_schedule(schedule, prog),
    );
    rust_files.insert(
        "dispatch.rs".to_string(),
        super::cross_cutting::synthesize_dispatch(&kernel_index),
    );

    Ok(EmittedArtifacts {
        wgsl_files,
        rust_files,
        kernel_index,
    })
}

// ---------------------------------------------------------------------------
// File composition
// ---------------------------------------------------------------------------

/// Compose a single `.wgsl` file from a [`KernelSpec`] + body string +
/// originating [`KernelTopology`] (used to derive the workgroup size).
///
/// The output mirrors the legacy WGSL files' shape:
/// 1. A `// GENERATED ...` header comment.
/// 2. The `@group(0) @binding(N)` declaration block from
///    [`lower_wgsl_bindings`].
/// 3. The `@compute @workgroup_size(N)` annotation, derived from the
///    topology's [`DispatchShape::workgroup_size`].
/// 4. The entry-point function with its `gid` argument and the body
///    from Task 4.2.
fn compose_wgsl_file(
    spec: &KernelSpec,
    body: &str,
    topology: &KernelTopology,
    prog: &CgProgram,
) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push('\n');

    // The cfg uniform is referenced by name (e.g. `cfg: MaskHoldCfg`),
    // so the WGSL must declare the matching struct inline before the
    // uniform binding. Shape mirrors the Rust cfg_struct_decl:
    //   ViewFold:  { event_count, tick, _pad0, _pad1 }
    //   Generic:   { agent_cap, _pad0, _pad1, _pad2 }
    // (WGSL doesn't accept `[u32; N]` array members in uniforms the way
    // Rust does; the padding is unrolled into scalar `_padN` fields.)
    out.push_str(&compose_wgsl_cfg_struct(spec));
    out.push('\n');

    out.push_str(&lower_wgsl_bindings(spec));
    out.push('\n');

    // Emit `const config_<id>: f32 = <value>;` for every config-const
    // referenced in the kernel body. The substring scan keys on
    // `config_<id>` (the WGSL identifier `lower_cg_expr_to_wgsl`
    // produces for `CgExpr::Read(DataHandle::ConfigConst { id })`).
    // Today every config field defaults to a numeric literal (Boids'
    // `flock` block), so a single-pass `f32` emission covers it; non-
    // numeric defaults skip silently because no kernel references
    // them. Sorted by id for deterministic output.
    let mut emitted_consts = false;
    for (id, value) in &prog.config_const_values {
        let needle = format!("config_{}", id);
        if body.contains(&needle) {
            out.push_str(&format!("const config_{}: f32 = {:?};\n", id, value));
            emitted_consts = true;
        }
    }
    if emitted_consts {
        out.push('\n');
    }

    // Spatial-grid prelude: constants + pos_to_cell / cell_index
    // helpers, emitted only when the body touches a spatial binding.
    // The same constants are mirrored on the runtime side
    // (`crate::cg::emit::spatial::{CELL_SIZE,WORLD_HALF_EXTENT,...}`)
    // so per-fixture runtime crates can size matching wgpu buffers
    // without re-deriving the values from the WGSL.
    let spatial_prelude = super::spatial::compose_spatial_prelude(body);
    if !spatial_prelude.is_empty() {
        out.push_str(&spatial_prelude);
    }

    // Emit B1-stub prelude functions for every namespace method whose
    // WGSL function name appears in this kernel's body. The registry
    // (`prog.namespace_registry`) is the source of truth for both the
    // function name (used for the substring scan) and the stub body
    // (emitted verbatim). Walk-and-collect rather than emit-all so the
    // generated WGSL stays minimal and the kernel-by-kernel diff is
    // legible. See `populate_namespace_registry` in `lower::driver`
    // for the registered methods.
    let prelude = compose_namespace_prelude(body, prog);
    if !prelude.is_empty() {
        out.push_str(&prelude);
        out.push('\n');
    }

    // PerCell topologies (today only the tiled-MoveBoid kernel)
    // need module-level `var<workgroup>` declarations for the
    // cooperative tile arrays — they're shared across all lanes of
    // the workgroup but addressed per-lane inside the kernel body.
    // Sized for a 27-cell × MAX_PER_CELL neighborhood (= 864 entries
    // for boids' defaults). The kernel preamble + per-fold inner
    // walk both reference these symbols by name (`tile_pos`,
    // `tile_vel`, `tile_count`); emitting the decls here keeps them
    // alongside the matching `@compute @workgroup_size` header
    // without smuggling a `var<workgroup>` mid-body (illegal in WGSL).
    let dispatch_shape = topology_dispatch_shape(topology);
    let is_per_cell = matches!(dispatch_shape, DispatchShape::PerCell);
    let is_per_scan_chunk = matches!(dispatch_shape, DispatchShape::PerScanChunk);
    if is_per_scan_chunk {
        // PerScanChunk topologies (parallel prefix-scan kernels)
        // share a 256-entry workgroup-local buffer holding the
        // Hillis-Steele scan working set. Sized to match
        // `PER_SCAN_CHUNK_WORKGROUP_X` so every lane has exactly
        // one slot — keep the constant in sync if the chunk size
        // is ever bumped.
        let chunk = crate::cg::dispatch::PER_SCAN_CHUNK_WORKGROUP_X;
        out.push_str(&format!(
            "// Workgroup-local scratch for the Hillis-Steele scan.\n\
             // One u32 per lane; total = {chunk} × 4 = {bytes} B.\n\
             var<workgroup> scan_shared: array<u32, {chunk}>;\n\n",
            chunk = chunk,
            bytes = chunk * 4,
        ));
    }
    if is_per_cell {
        // The tile-array size derives from `MAX_PER_CELL` so a knob
        // change in `crate::cg::emit::spatial` flows through here
        // without a separate edit. The 27 stays a literal — it's a
        // structural property of "3³ neighborhood" the tile-walk emit
        // hardcodes too, and surfacing it as a constant would just
        // make both sites read the same magic number.
        let max_per_cell = super::spatial::MAX_PER_CELL;
        let total_slots = 27 * max_per_cell;
        out.push_str(&format!(
            "// Workgroup-local tile arrays for the 27-cell neighborhood.\n\
             // Sized for SPATIAL_MAX_PER_CELL (= {max}) slots per cell × 27\n\
             // cells = {total} entries each. tile_count holds the per-cell\n\
             // population; tile_pos/tile_vel mirror the agent fields the\n\
             // body's projections read via per_pair_candidate.\n\
             var<workgroup> tile_count: array<u32, 27>;\n\
             var<workgroup> tile_pos: array<vec3<f32>, 27 * {max}>;\n\
             var<workgroup> tile_vel: array<vec3<f32>, 27 * {max}>;\n\n",
            max = max_per_cell,
            total = total_slots,
        ));
    }

    let workgroup_x = topology_workgroup_size_x(topology);

    if is_per_cell || is_per_scan_chunk {
        // PerCell + PerScanChunk entry points: take `workgroup_id`
        // + `local_invocation_id` instead of the usual
        // `global_invocation_id`. The body's per-shape preamble
        // (PerCell: `tiled_per_cell_preamble`; PerScanChunk:
        // `thread_indexing_preamble`) reads these to derive its
        // working indices.
        out.push_str(&format!(
            "@compute @workgroup_size({workgroup_x})\n\
             fn {entry}(\n\
             \x20   @builtin(workgroup_id) workgroup_id: vec3<u32>,\n\
             \x20   @builtin(local_invocation_id) local_invocation_id: vec3<u32>,\n\
             ) {{\n",
            entry = spec.entry_point
        ));
    } else {
        out.push_str(&format!(
            "@compute @workgroup_size({workgroup_x})\n\
             fn {entry}(@builtin(global_invocation_id) gid: vec3<u32>) {{\n",
            entry = spec.entry_point
        ));
    }
    out.push_str(body);
    if !body.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("}\n");

    out
}

/// Pull the dispatch shape off a topology — handles all variants by
/// returning the per-stage shape stored on the topology. Used by
/// `compose_wgsl_file` to switch between the standard
/// `global_invocation_id` entry point and the PerCell
/// `(workgroup_id, local_invocation_id)` form.
fn topology_dispatch_shape(topology: &KernelTopology) -> DispatchShape {
    match topology {
        KernelTopology::Fused { dispatch, .. } => *dispatch,
        KernelTopology::Split { dispatch, .. } => *dispatch,
        KernelTopology::Indirect { .. } => DispatchShape::PerEvent {
            source_ring: crate::cg::data_handle::EventRingId(0),
        },
    }
}

/// Walk the kernel `body` for substrings naming registered namespace-
/// method WGSL function names; emit the matching B1-stub prelude
/// declarations in registry order. Returns an empty string when no
/// method is referenced.
///
/// The substring scan looks for `<wgsl_fn_name>(` (function call
/// syntax) so a comment that incidentally names the function doesn't
/// trigger a stub declaration. Order is iteration order over the
/// namespace registry's `BTreeMap`s — deterministic across runs.
fn compose_namespace_prelude(body: &str, prog: &CgProgram) -> String {
    let mut out = String::new();
    for ns_def in prog.namespace_registry.namespaces.values() {
        for method_def in ns_def.methods.values() {
            let needle = format!("{}(", method_def.wgsl_fn_name);
            if body.contains(&needle) {
                out.push_str(&method_def.wgsl_stub);
                out.push('\n');
            }
        }
    }
    out
}

/// Emit the WGSL `struct {Pascal}Cfg { ... };` declaration kernels
/// reference from the cfg uniform binding. Sourced from the cfg
/// binding's WGSL type name; field shape branches on
/// [`KernelKind`] to mirror the Rust [`KernelSpec::cfg_struct_decl`]:
///   - `ViewFold`: `{ event_count, tick, _pad0, _pad1 }`
///   - `Generic`:  `{ agent_cap, _pad0, _pad1, _pad2 }`
///
/// WGSL doesn't accept `[u32; N]` array members in uniform-shaped
/// structs the same way Rust does, so the padding is unrolled into
/// scalar `_padN` fields.
///
/// # Limitations
///
/// - **Field shape is hard-coded per `KernelKind`.** As more kernel
///   kinds land with bespoke cfgs (per-kind refinements anticipated by
///   `build_generic_cfg_struct_decl`'s comment), the right move is to
///   surface a `cfg_wgsl_decl` field from the kernel-spec layer rather
///   than branching here.
fn compose_wgsl_cfg_struct(spec: &KernelSpec) -> String {
    let cfg = spec
        .bindings
        .iter()
        .find(|b| matches!(b.bg_source, BgSource::Cfg))
        .expect("KernelSpec must carry a cfg binding");
    // Generic-kernel cfg gained `tick: u32` when PerAgent rules with
    // `emit <Event>` bodies started writing the tick header word into
    // the event ring. Layout matches `build_generic_cfg_struct_decl`
    // (Rust side): { agent_cap: u32, tick: u32, _pad0: u32, _pad1: u32 }.
    let fields = match spec.kind {
        // `second_key_pop` joined the layout with the pair_map storage
        // gap fix (2026-05-03): fold body's RMW indexes
        // `view_storage_primary[k1 * cfg.second_key_pop + k2]` for
        // 2-D views; single-key views set the field to 1 so the index
        // reduces to `k_last`. Mirrors the Rust `FoldXxxCfg` struct
        // (build_view_fold_cfg_struct_decl).
        KernelKind::ViewFold => "event_count: u32, tick: u32, second_key_pop: u32, _pad0: u32",
        // `slot_count` joined the layout in lockstep — pair_map views
        // over-allocate `agent_cap × second_pop` slots; the decay
        // kernel iterates `slot_count` instead of `agent_cap` so the
        // anchor multiplier reaches every (k1, k2). Single-key views
        // set `slot_count == agent_cap`. Mirrors
        // build_view_decay_cfg_struct_decl.
        KernelKind::ViewDecay => "agent_cap: u32, tick: u32, slot_count: u32, _pad0: u32",
        KernelKind::Generic => "agent_cap: u32, tick: u32, _pad0: u32, _pad1: u32",
    };
    format!("struct {ty} {{ {fields} }};\n", ty = cfg.wgsl_ty)
}

/// Compose a single `.rs` file from a [`KernelSpec`] + originating
/// [`KernelTopology`] (used to derive the dispatch-workgroup expression
/// inside the [`crate::Kernel::record`] body).
///
/// The output mirrors the legacy Rust kernel modules' shape (see
/// `crates/engine_gpu_rules/src/alive_pack.rs` for a template), with
/// the differences documented in the module-level `# Limitations`. Each
/// section is sourced from one of the [`crate::kernel_lowerings`]
/// helpers, so a regression in any single emitted form is caught by the
/// lowering's own tests; this composer is structural glue only.
///
/// The synthesized module is `crate::Kernel`-implementing: the
/// `<Pascal>Kernel` struct, `<Pascal>Bindings<'a>`, the cfg struct, an
/// `impl crate::Kernel for <Pascal>Kernel { … }` block (real bodies,
/// no panics), and the standalone helper fns (`<name>_bgl_entries`,
/// `<name>_bind_group_entries`, `<name>_build_cfg`) the legacy callers
/// expect.
///
/// # Limitations
/// - The `record()` body uses
///   `pass.dispatch_workgroups((agent_cap + N - 1) / N, 1, 1)` for
///   per-agent / per-event / per-pair / per-word kernels, and
///   `(1, 1, 1)` for one-shot. Indirect dispatch
///   (`dispatch_workgroups_indirect`) is a Task 5.4+ concern — the
///   legacy emitters today use the same agent-cap-bounded direct
///   dispatch as a placeholder for per-event kernels.
/// - The `bind()` body is built from the spec's [`BgSource`] tags via
///   [`render_bg_source_expr`]; ViewHandle / AliasOf are routed
///   through `unwrap_or(primary)` patterns that mirror the legacy fold
///   kernels' pattern. None of today's CG kernels emit those variants
///   (Task 5.4+ wires fold-view tuple destructuring); the helpers stay
///   in place defensively so the composer never panics.
fn compose_rust_module_file(spec: &KernelSpec, topology: &KernelTopology) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push('\n');

    // Phase 7 boids GPU pipeline (2026-05-02): kernel modules now
    // target `engine::gpu::Kernel` (hand-written platform trait) and
    // construct `Bindings` directly with explicit `&wgpu::Buffer`
    // refs. The deleted `bind()` method took a `&BindingSources`
    // aggregate that the wolf-sim runtime owned; per-fixture
    // runtimes now wire bindings inline at the dispatch call site.

    // Per-kernel struct (carries the pipeline + BGL).
    out.push_str(&format!(
        "pub struct {pascal}Kernel {{\n    \
         pipeline: wgpu::ComputePipeline,\n    \
         bgl: wgpu::BindGroupLayout,\n}}\n\n",
        pascal = spec.pascal
    ));

    // Bindings struct. ViewFold kernels emit `Option<&'a wgpu::Buffer>`
    // for the anchor/ids slots (matching the legacy fold-kernel
    // contract); generic kernels use the spec-driven lowering which
    // emits `&'a wgpu::Buffer` for every binding.
    out.push_str(&format!(
        "pub struct {pascal}Bindings<'a> {{\n",
        pascal = spec.pascal
    ));
    if matches!(spec.kind, KernelKind::ViewFold) {
        out.push_str(&compose_view_fold_bindings_struct_fields(spec));
    } else {
        out.push_str(&lower_rust_bindings_struct_fields(spec));
    }
    out.push_str("}\n\n");

    // Cfg struct decl — KernelSpec.cfg_struct_decl is the full
    // `#[repr(C)] ... pub struct <Cfg> { ... }` form.
    out.push_str(&spec.cfg_struct_decl);
    out.push_str("\n\n");

    // WGSL source — the `.wgsl` file is co-located in the output
    // directory; `include_str!` resolves it at compile time when the
    // emitted crate is built.
    out.push_str(&format!(
        "const SHADER_SRC: &str = include_str!(\"{name}.wgsl\");\n\n",
        name = spec.name
    ));

    // Kernel trait impl.
    out.push_str(&compose_kernel_trait_impl(spec, topology));
    out.push('\n');

    // BGL entries function. ViewFold kernels skip the standalone
    // `_bgl_entries` / `_bind_group_entries` / `_build_cfg` helpers —
    // the legacy `crates/engine_gpu_rules/src/fold_<view>.rs` modules
    // do not expose them, and the `lower_rust_bg_entries` lowering
    // would produce `Option`-typed expressions that don't carry
    // `.as_entire_binding()`. The Kernel trait impl above remains the
    // single entry point for ViewFold callers.
    if !matches!(spec.kind, KernelKind::ViewFold) {
        out.push_str(&format!(
            "pub fn {name}_bgl_entries() -> Vec<wgpu::BindGroupLayoutEntry> {{\n    \
             vec![\n",
            name = spec.name
        ));
        out.push_str(&render_cg_bgl_entries(spec));
        out.push_str("    ]\n}\n\n");

        // Bind-group entries function. Returns the BindGroupEntry list a
        // caller wraps with the BGL into a BindGroup.
        out.push_str(&format!(
            "pub fn {name}_bind_group_entries<'a>(\n    \
             bindings: &'a {pascal}Bindings<'a>,\n) -> \
             Vec<wgpu::BindGroupEntry<'a>> {{\n    vec![\n",
            name = spec.name,
            pascal = spec.pascal
        ));
        out.push_str(&lower_rust_bg_entries(spec));
        out.push_str("    ]\n}\n\n");

        // Phase 7 boids GPU pipeline (2026-05-02): dropped the
        // `<name>_build_cfg(state: &engine::state::SimState)` standalone
        // helper. The cfg shape (`<Pascal>Cfg`) is `#[repr(C)]` POD;
        // per-fixture runtimes construct it directly with primitive
        // args at the dispatch call site (e.g.,
        // `PhysicsMoveBoidCfg { agent_cap: 16, _pad: [0; 3] }`).
    }

    out
}

/// Compose the `impl engine::gpu::Kernel for <Pascal>Kernel { … }`
/// block. The trait carries the minimum surface every kernel
/// implements: `new` (compile shader + build pipeline) + `record`
/// (encode dispatch). Per-kernel `build_cfg` and `bind` methods are
/// gone — `Cfg` is a `#[repr(C)]` POD that callers construct
/// directly, and `Bindings` is a typed struct wired inline at the
/// dispatch call site with explicit `&wgpu::Buffer` refs.
fn compose_kernel_trait_impl(spec: &KernelSpec, topology: &KernelTopology) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "impl engine::gpu::Kernel for {pascal}Kernel {{\n    \
         type Bindings<'a> = {pascal}Bindings<'a>;\n    \
         type Cfg = {cfg};\n\n",
        pascal = spec.pascal,
        cfg = spec.cfg_struct
    ));

    // new()
    out.push_str("    fn new(device: &wgpu::Device) -> Self {\n");
    out.push_str(&format!(
        "        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::wgsl\"),\n            \
             source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),\n        \
             }});\n",
        name = spec.name
    ));
    out.push_str(&format!(
        "        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::bgl\"),\n            \
             entries: &[\n",
        name = spec.name
    ));
    out.push_str(&render_cg_bgl_entries(spec));
    out.push_str("            ],\n        });\n");
    out.push_str(&format!(
        "        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::pl\"),\n            \
             bind_group_layouts: &[&bgl],\n            \
             push_constant_ranges: &[],\n        \
             }});\n",
        name = spec.name
    ));
    out.push_str(&format!(
        "        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::pipeline\"),\n            \
             layout: Some(&pl),\n            \
             module: &shader,\n            \
             entry_point: Some(\"{entry}\"),\n            \
             compilation_options: Default::default(),\n            \
             cache: None,\n        \
             }});\n        \
             Self {{ pipeline, bgl }}\n    }}\n\n",
        name = spec.name,
        entry = spec.entry_point
    ));

    // build_cfg + bind dropped from the trait — see compose_kernel_trait_impl
    // doc. `Cfg` is `#[repr(C)]` POD (caller constructs directly);
    // `Bindings` wired inline at dispatch with explicit buffer refs.

    // record()
    if matches!(spec.kind, KernelKind::ViewFold) {
        out.push_str(&compose_view_fold_record_method(spec));
    } else {
        // OneShot dispatch resolves to `pass.dispatch_workgroups(1, 1, 1)`
        // and never references `agent_cap` — emit the parameter as
        // `_agent_cap` so the synthesized kernel module compiles under
        // `-D unused-variables`. PerAgent / PerEvent / PerPair / PerWord
        // all derive workgroup count from `agent_cap`. Mirrors the
        // legacy `seed_indirect.rs` convention.
        let cap_param = if dispatch_is_one_shot(topology) {
            "_agent_cap"
        } else {
            "agent_cap"
        };
        out.push_str(&format!(
            "    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &{pascal}Bindings<'_>, {cap_param}: u32) {{\n",
            pascal = spec.pascal,
            cap_param = cap_param,
        ));
        out.push_str(&format!(
            "        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {{\n            \
                 label: Some(\"engine_gpu_rules::{name}::bg\"),\n            \
                 layout: &self.bgl,\n            \
                 entries: &[\n",
            name = spec.name
        ));
        out.push_str(&lower_rust_bg_entries(spec));
        out.push_str("            ],\n        });\n");
        out.push_str(&format!(
            "        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {{\n            \
                 label: Some(\"engine_gpu_rules::{name}::pass\"),\n            \
                 timestamp_writes: None,\n        \
                 }});\n",
            name = spec.name
        ));
        out.push_str("        pass.set_pipeline(&self.pipeline);\n");
        out.push_str("        pass.set_bind_group(0, &bg, &[]);\n");
        out.push_str(&compose_dispatch_call(topology));
        out.push_str("    }\n");
    }

    out.push_str("}\n");
    out
}

/// Render the BGL entries for a CG-emitted kernel, routing through the
/// CG-side helpers `engine::gpu::bgl_storage` / `engine::gpu::bgl_uniform` defined
/// in the synthesized `lib.rs`. Distinct from
/// [`crate::kernel_lowerings::lower_rust_bgl_entries`] which routes
/// through the legacy `crate::fused_mask::bgl_*` path; the legacy
/// path requires the legacy `fused_mask.rs` to define the helpers,
/// which a CG-only output never carries.
fn render_cg_bgl_entries(spec: &KernelSpec) -> String {
    let mut out = String::new();
    for b in &spec.bindings {
        let descriptor = match b.access {
            AccessMode::ReadStorage => format!("engine::gpu::bgl_storage({}, true)", b.slot),
            AccessMode::ReadWriteStorage | AccessMode::AtomicStorage => {
                format!("engine::gpu::bgl_storage({}, false)", b.slot)
            }
            AccessMode::Uniform => format!("engine::gpu::bgl_uniform({})", b.slot),
        };
        writeln!(out, "                {}, // {}", descriptor, b.name)
            .expect("write to String never fails");
    }
    out
}

/// Render the `bindings: <field>: <expr>,` rows for the `bind()`
/// initializer body.
#[allow(dead_code)]
fn compose_bind_body(spec: &KernelSpec) -> String {
    let mut out = String::new();
    for b in &spec.bindings {
        // AliasOf bindings don't have their own struct field; the alias
        // is handled in `lower_rust_bg_entries` at BindGroupEntry time.
        if matches!(b.bg_source, BgSource::AliasOf(_)) {
            continue;
        }
        let value = render_bg_source_expr(&b.bg_source, &b.name);
        out.push_str(&format!("            {field}: {value},\n", field = b.name, value = value));
    }
    out
}

/// Render a [`BgSource`] as the Rust expression that yields the
/// `&'a wgpu::Buffer` used by the `bind()` initializer.
///
/// `field` is the binding's name — used to surface a self-referential
/// fallback for ViewHandle (the generic CG path; today no kernel emits
/// it, so the helper stays defensive).
#[allow(dead_code)]
fn render_bg_source_expr(src: &BgSource, field: &str) -> String {
    match src {
        // `ResidentPathContext` fields are owned `wgpu::Buffer`s (not
        // references). Borrow at the use-site so the synthesized
        // `Bindings { ... }` initializer matches the `&'a wgpu::Buffer`
        // field type. The legacy ViewFold emit path bypasses this
        // helper for its event_ring/event_tail bindings (it constructs
        // the borrow inline at `compose_view_fold_bindings_init`).
        BgSource::Resident(f) => format!("&sources.resident.{f}"),
        BgSource::Transient(f) => format!("sources.transient.{f}"),
        BgSource::External(f) => format!("sources.external.{f}"),
        // `Pool` fields are owned `wgpu::Buffer`s (not references) on
        // the runtime `Pool` struct, unlike `TransientHandles` whose
        // fields are `&'a wgpu::Buffer`. Borrow at the use-site so
        // the synthesized `Bindings { ... }` initializer matches the
        // `&'a wgpu::Buffer` field type.
        BgSource::Pool(f) => format!("&sources.pool.{f}"),
        BgSource::Cfg => "cfg".to_string(),
        BgSource::ViewHandle { accessor, tuple_idx } => {
            // Defensive: until Task 5.4 wires fold-view tuple
            // destructuring at the kernel-module emit layer, the
            // generic path renders a `<accessor>().<idx>`-style
            // expression. The legacy fold kernels destructure into
            // (primary, anchor, ids) locals; today no CG kernel emits
            // ViewHandle — this arm exists so the composer never falls
            // through to a panic if a future spec does.
            format!(
                "sources.resident.{accessor}().{idx} /* {field} */",
                accessor = accessor,
                idx = tuple_idx
            )
        }
        BgSource::AliasOf(target) => {
            // Defensive — AliasOf bindings are filtered out before this
            // helper is called. If a caller skipped the filter, render
            // a self-evidently routable expression rather than panic.
            format!("/* alias of {target} */ sources.external.sim_cfg")
        }
    }
}

// ---------------------------------------------------------------------------
// ViewFold-specific composition (Task 5.3)
// ---------------------------------------------------------------------------

/// Pull the per-view resident accessor name from a ViewFold spec —
/// every ViewHandle binding in the spec carries the same accessor by
/// construction (see [`super::kernel::build_view_fold_bindings`]).
/// Returns `None` if no ViewHandle binding is present (which should
/// only happen for non-ViewFold specs; routing decisions are now made
/// against `spec.kind`, so this helper just walks the bindings to find
/// the accessor string).
#[allow(dead_code)]
fn view_fold_accessor(spec: &KernelSpec) -> Option<&str> {
    spec.bindings.iter().find_map(|b| match &b.bg_source {
        BgSource::ViewHandle { accessor, .. } => Some(accessor.as_str()),
        BgSource::Resident(_)
        | BgSource::Transient(_)
        | BgSource::External(_)
        | BgSource::Pool(_)
        | BgSource::Cfg
        | BgSource::AliasOf(_) => None,
    })
}

/// Compose the `<Pascal>Bindings<'a>` struct fields for a ViewFold
/// kernel. The anchor/ids slots are `Option<&'a wgpu::Buffer>` —
/// they fall back to primary at `record()` time when the resident
/// accessor returns `None` (single-storage views like `threat_level`
/// don't expose dedicated anchor/ids buffers).
///
/// # Limitations
/// - **Field shape is fixed at the 7-binding ViewFold layout.** The
///   helper assumes the spec carries exactly those bindings (event_ring,
///   event_tail, view_storage_primary, view_storage_anchor,
///   view_storage_ids, sim_cfg, cfg) in that slot order — guaranteed
///   by [`super::kernel::build_view_fold_bindings`]. A spec with a
///   different shape would silently produce a misaligned struct.
fn compose_view_fold_bindings_struct_fields(spec: &KernelSpec) -> String {
    debug_assert_eq!(
        spec.bindings.len(),
        7,
        "compose_view_fold_bindings_struct_fields: ViewFold spec must carry exactly 7 bindings; got {}",
        spec.bindings.len()
    );
    let mut out = String::new();
    for b in &spec.bindings {
        // Anchor/ids slots get Option<&'a wgpu::Buffer> per legacy
        // fold-kernel contract. All other slots are mandatory.
        let optional = matches!(
            b.name.as_str(),
            "view_storage_anchor" | "view_storage_ids"
        );
        if optional {
            writeln!(out, "    pub {}: Option<&'a wgpu::Buffer>,", b.name)
                .expect("write to String never fails");
        } else {
            writeln!(out, "    pub {}: &'a wgpu::Buffer,", b.name)
                .expect("write to String never fails");
        }
    }
    out
}

/// Compose the `bind()` method body for a ViewFold kernel. Mirrors
/// the legacy `fold_<view>.rs` pattern:
///
/// ```ignore
/// fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> ... {
///     let (primary, anchor, ids) = sources.resident.fold_view_<view>_handles();
///     <Pascal>Bindings {
///         event_ring: &sources.resident.batch_events_ring,
///         event_tail: &sources.resident.batch_events_tail,
///         view_storage_primary: primary,
///         view_storage_anchor: anchor,
///         view_storage_ids: ids,
///         sim_cfg: sources.external.sim_cfg,
///         cfg,
///     }
/// }
/// ```
///
/// # Limitations
///
/// - **Resident accessor (`fold_view_<view>_handles`) is a Task 5.4
///   dependency.** Today the legacy `resident_context.rs` exposes the
///   accessors for the 9 active views; new views landing before Task
///   5.4 will need a manual stub. The accessor name is pulled from
///   the spec's ViewHandle binding — the kernel-spec layer
///   ([`super::kernel::build_view_fold_bindings`]) sets it to
///   `fold_view_<view_name>_handles`.
/// - **`sources.resident.batch_events_ring` / `batch_events_tail`** —
///   the resident path always exposes these (see
///   `crates/engine_gpu_rules/src/resident_context.rs`).
#[allow(dead_code)]
fn compose_view_fold_bind_method(spec: &KernelSpec) -> String {
    debug_assert_eq!(
        spec.bindings.len(),
        7,
        "compose_view_fold_bind_method: ViewFold spec must carry exactly 7 bindings; got {}",
        spec.bindings.len()
    );
    let accessor = view_fold_accessor(spec).expect("ViewFold spec must carry an accessor");
    let mut out = String::new();
    out.push_str(&format!(
        "    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> {pascal}Bindings<'a> {{\n",
        pascal = spec.pascal
    ));
    out.push_str(&format!(
        "        // Resolve the per-view storage tuple via the resident accessor synthesised\n\
         \x20       // by Task 5.4's emit_resident_context. anchor / ids may be `None` for\n\
         \x20       // views that share storage with `primary` (single-buffer fold layouts).\n\
         \x20       let (primary, anchor, ids) = sources.resident.{accessor}();\n",
    ));
    out.push_str(&format!(
        "        {pascal}Bindings {{\n",
        pascal = spec.pascal
    ));
    out.push_str("            event_ring: &sources.resident.batch_events_ring,\n");
    out.push_str("            event_tail: &sources.resident.batch_events_tail,\n");
    out.push_str("            view_storage_primary: primary,\n");
    out.push_str("            view_storage_anchor: anchor,\n");
    out.push_str("            view_storage_ids: ids,\n");
    out.push_str("            sim_cfg: sources.external.sim_cfg,\n");
    out.push_str("            cfg,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out
}

/// Compose the `record()` method body for a ViewFold kernel. Mirrors
/// the legacy fold-kernel pattern, including the anchor/ids
/// `unwrap_or(primary)` fallback so the BGL slot is always live even
/// when the view shares storage across slots.
///
/// # Limitations
///
/// - **Dispatch is a placeholder direct dispatch — real
///   indirect-dispatch wiring is a Task 5.7 concern.** The cascade
///   tail / per-fold indirect-args buffer (`event_tail` here) is the
///   eventual source for `dispatch_workgroups_indirect`; today the
///   record body emits the agent-cap-bounded direct dispatch every
///   other kernel uses. Switchover lands at Task 5.7.
/// - **`agent_cap` parameter is unused for ViewFold.** Indirect
///   dispatch will resolve event count via the indirect-args buffer;
///   the `agent_cap` parameter is suppressed via `let _ = agent_cap;`
///   to silence unused-variable warnings.
fn compose_view_fold_record_method(spec: &KernelSpec) -> String {
    debug_assert_eq!(
        spec.bindings.len(),
        7,
        "compose_view_fold_record_method: ViewFold spec must carry exactly 7 bindings; got {}",
        spec.bindings.len()
    );
    let mut out = String::new();
    out.push_str(&format!(
        "    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &{pascal}Bindings<'_>, agent_cap: u32) {{\n",
        pascal = spec.pascal
    ));
    out.push_str("        // Resolve view-handle slots: anchor/ids fall back to primary when the\n");
    out.push_str("        // view doesn't expose dedicated buffers (the BGL slot still has to be\n");
    out.push_str("        // live; rebinding primary is a no-op safe choice).\n");
    out.push_str("        let primary_buf = bindings.view_storage_primary;\n");
    out.push_str("        let anchor_buf = bindings.view_storage_anchor.unwrap_or(primary_buf);\n");
    out.push_str("        let ids_buf = bindings.view_storage_ids.unwrap_or(primary_buf);\n");
    out.push_str(&format!(
        "        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::bg\"),\n            \
             layout: &self.bgl,\n            \
             entries: &[\n",
        name = spec.name
    ));
    // BindGroupEntry list — each ViewFold slot in fixed order. The
    // primary/anchor/ids slots reference the locals computed above;
    // event_ring/tail/sim_cfg/cfg pull straight from `bindings`.
    out.push_str(
        "                wgpu::BindGroupEntry { binding: 0, resource: bindings.event_ring.as_entire_binding() },\n",
    );
    out.push_str(
        "                wgpu::BindGroupEntry { binding: 1, resource: bindings.event_tail.as_entire_binding() },\n",
    );
    out.push_str(
        "                wgpu::BindGroupEntry { binding: 2, resource: primary_buf.as_entire_binding() },\n",
    );
    out.push_str(
        "                wgpu::BindGroupEntry { binding: 3, resource: anchor_buf.as_entire_binding() },\n",
    );
    out.push_str(
        "                wgpu::BindGroupEntry { binding: 4, resource: ids_buf.as_entire_binding() },\n",
    );
    out.push_str(
        "                wgpu::BindGroupEntry { binding: 5, resource: bindings.sim_cfg.as_entire_binding() },\n",
    );
    out.push_str(
        "                wgpu::BindGroupEntry { binding: 6, resource: bindings.cfg.as_entire_binding() },\n",
    );
    out.push_str("            ],\n        });\n");
    out.push_str(&format!(
        "        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {{\n            \
             label: Some(\"engine_gpu_rules::{name}::pass\"),\n            \
             timestamp_writes: None,\n        \
             }});\n",
        name = spec.name
    ));
    out.push_str("        pass.set_pipeline(&self.pipeline);\n");
    out.push_str("        pass.set_bind_group(0, &bg, &[]);\n");
    out.push_str("        // Direct dispatch over `agent_cap` (the call-site parameter holds\n");
    out.push_str("        // event_count for fold kernels — see swarm_storm_runtime). One\n");
    out.push_str("        // thread per event_idx; the kernel's `if (event_idx >= cfg.event_count)\n");
    out.push_str("        // { return; }` early-return guards over-dispatch. Future indirect-\n");
    out.push_str("        // args wiring via seed_indirect_0 would replace this with\n");
    out.push_str("        // dispatch_workgroups_indirect against the args buffer.\n");
    out.push_str("        pass.dispatch_workgroups((agent_cap + 63u32) / 64u32, 1, 1);\n");
    out.push_str("    }\n");
    out
}

/// Whether the kernel's dispatch shape resolves to a single-workgroup
/// (`OneShot`) call. Used by `compose_kernel_trait_impl` to decide
/// whether the `record()` method's `agent_cap` parameter must be
/// renamed to `_agent_cap` (OneShot's `dispatch_workgroups(1, 1, 1)`
/// never references `agent_cap`, tripping the `-D unused-variables`
/// gate). Mirrors the dispatch-shape selection in
/// [`compose_dispatch_call`] — Indirect topology is fixed to PerEvent,
/// which uses `agent_cap`.
fn dispatch_is_one_shot(topology: &KernelTopology) -> bool {
    let dispatch = match topology {
        KernelTopology::Fused { dispatch, .. } => *dispatch,
        KernelTopology::Split { dispatch, .. } => *dispatch,
        KernelTopology::Indirect { .. } => DispatchShape::PerEvent {
            source_ring: crate::cg::data_handle::EventRingId(0),
        },
    };
    matches!(dispatch, DispatchShape::OneShot)
}

/// Pick the `pass.dispatch_workgroups(...)` line for a kernel based on
/// its topology's [`DispatchShape`].
fn compose_dispatch_call(topology: &KernelTopology) -> String {
    let dispatch = match topology {
        KernelTopology::Fused { dispatch, .. } => *dispatch,
        KernelTopology::Split { dispatch, .. } => *dispatch,
        KernelTopology::Indirect { .. } => DispatchShape::PerEvent {
            source_ring: crate::cg::data_handle::EventRingId(0),
        },
    };
    let wg_x = dispatch.workgroup_size().x;
    match dispatch {
        DispatchShape::OneShot => "        pass.dispatch_workgroups(1, 1, 1);\n".to_string(),
        DispatchShape::PerWord => format!(
            "        let num_words = (agent_cap + 31u32) / 32u32;\n        \
             pass.dispatch_workgroups((num_words + {wg_x_minus_one}u32) / {wg_x}u32, 1, 1);\n",
            wg_x = wg_x,
            wg_x_minus_one = wg_x - 1
        ),
        DispatchShape::PerAgent
        | DispatchShape::PerEvent { .. }
        | DispatchShape::PerPair { .. } => format!(
            "        pass.dispatch_workgroups((agent_cap + {wg_x_minus_one}u32) / {wg_x}u32, 1, 1);\n",
            wg_x = wg_x,
            wg_x_minus_one = wg_x - 1
        ),
        DispatchShape::PerCell => {
            // PerCell: one workgroup per spatial-grid cell. The cell
            // count is fixed at compile time (see
            // `crate::cg::emit::spatial::num_cells`); inline the
            // constant here so the dispatch call doesn't depend on
            // any runtime parameter and the per-fixture runtime
            // doesn't have to thread `num_cells` through.
            let n = crate::cg::emit::spatial::num_cells();
            format!(
                "        pass.dispatch_workgroups({}u32, 1, 1);\n",
                n
            )
        }
        DispatchShape::PerScanChunk => {
            // PerScanChunk: ceil(num_cells / chunk_size) workgroups.
            // Both inputs are compile-time constants, so inline the
            // result.
            let n = crate::cg::emit::spatial::num_cells();
            let chunks = n.div_ceil(wg_x);
            format!(
                "        pass.dispatch_workgroups({}u32, 1, 1);\n",
                chunks
            )
        }
    }
}

// ---------------------------------------------------------------------------
// lib.rs synthesis
// ---------------------------------------------------------------------------

/// Build the synthesized `lib.rs` content for the CG-emitted crate.
///
/// `kernel_index` is the schedule-order list of snake_case kernel names
/// (one per emitted module). The output declares each module, re-exports
/// the `<Pascal>Kernel` struct, defines the [`crate::Kernel`] trait,
/// the `KernelId` registry enum, the `BufferRef` enum, and the
/// `bgl_storage` / `bgl_uniform` helper fns every per-kernel module
/// invokes as `engine::gpu::bgl_storage(...)` / `engine::gpu::bgl_uniform(...)`.
///
/// The CG-emitted kernel modules use [`render_cg_bgl_entries`] (NOT
/// the legacy `lower_rust_bgl_entries` which routes via
/// `crate::fused_mask::bgl_*`) so the helper paths align with the
/// top-level helpers synthesized here.
///
/// # Limitations
/// - **`mod binding_sources;` is declared but `binding_sources.rs` is
///   not emitted today.** The CG pipeline emits per-kernel modules
///   only; `binding_sources.rs` is hand-authored in the legacy crate
///   and a Task 5.4+ concern for the CG side. A consumer overlaying
///   the CG output on the legacy crate inherits the legacy
///   `binding_sources.rs`; a fresh CG-only crate would need a stub.
/// - **`schedule`, `resident_context`, `pingpong_context`, `pool`,
///   `transient_handles`, `external_buffers` modules are NOT
///   declared.** The legacy `lib.rs` emits them; the CG pipeline does
///   not yet, but every emitted kernel imports `BindingSources` from
///   `binding_sources` (which transitively pulls in the rest). Task
///   5.4+ extends.
/// - **`KernelId` variants are PascalCase derived from
///   [`snake_to_pascal`].** Two distinct snake names that pascalize to
///   the same identifier (e.g. `foo_bar` and `foo__bar`) would collide
///   here; today the [`super::kernel::semantic_kernel_name`] mapping
///   keeps every name's snake form unique, so pascal collisions are
///   structurally impossible. The synthesized helper has no defensive
///   collision check — adding one is cheap if a future renaming
///   policy makes the invariant fragile.
pub fn synthesize_lib_rs(kernel_index: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler — do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push('\n');
    out.push_str("#![allow(clippy::all)]\n");
    out.push_str("#![allow(unused_imports)]\n");
    // Per-mask kernel suffixes carry the mask's interned name verbatim
    // from the .sim source (e.g. `Flee`, `Hold`, `MoveToward`); those
    // PascalCase fragments propagate into module / function identifiers
    // (`mask_Hold`, `fused_mask_Flee_bgl_entries`). Properly snake-casing
    // these requires walking interner names through a casing pass —
    // out of scope for the runtime-contract rename. Until then,
    // suppress the lint at crate scope so `RUSTFLAGS=-D warnings`
    // builds pass (matches the legacy emit's blanket
    // `#![allow(clippy::all)]` style).
    out.push_str("#![allow(non_snake_case)]\n");
    out.push('\n');

    // Per-kernel module declarations + re-exports.
    for name in kernel_index {
        out.push_str(&format!("pub mod {name};\n"));
    }
    out.push('\n');
    for name in kernel_index {
        let pascal = snake_to_pascal(name);
        out.push_str(&format!("pub use {name}::{pascal}Kernel;\n"));
    }
    out.push('\n');

    // Per-fixture compiler-output modules. Phase 7 boids GPU pipeline
    // (2026-05-02): the wolf-sim runtime container modules
    // (binding_sources / resident_context / external_buffers /
    // transient_handles / pingpong_context / pool) are no longer
    // emitted — per-fixture runtimes own their own buffers and wire
    // bindings inline at dispatch.
    out.push_str("pub mod schedule;\n");
    out.push_str("pub mod dispatch;\n");
    out.push('\n');

    // KernelId enum.
    out.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]\n");
    out.push_str("pub enum KernelId {\n");
    for name in kernel_index {
        out.push_str(&format!("    {},\n", snake_to_pascal(name)));
    }
    out.push_str("}\n\n");

    // BufferRef enum (matches legacy lib.rs).
    out.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]\n");
    out.push_str("pub enum BufferRef {\n");
    out.push_str("    /// Resident path indirect-args buffer.\n");
    out.push_str("    ResidentIndirectArgs,\n");
    out.push_str("    /// Cascade-physics event ring tail buffer (gates further iterations when zero).\n");
    out.push_str("    CascadeRingTail,\n");
    out.push_str("}\n");

    // Phase 7 boids GPU pipeline (2026-05-02): the `Kernel` trait +
    // `bgl_storage` / `bgl_uniform` helpers were relocated to
    // `engine::gpu` (hand-written platform infrastructure). Per-kernel
    // modules `impl engine::gpu::Kernel` instead of `crate::Kernel`,
    // and use `engine::gpu::bgl_storage` / `engine::gpu::bgl_uniform`
    // instead of crate-local helpers. Hand-writing them once removes
    // per-fixture duplication.

    out
}

// ---------------------------------------------------------------------------
// Topology → workgroup size
// ---------------------------------------------------------------------------

/// Pick the `@workgroup_size(x)` value a kernel emitted from `topology`
/// should declare. Routes through Task 1.4's
/// [`DispatchShape::workgroup_size`] so the WGSL annotation and the
/// dispatch-count rule never disagree.
///
/// For [`KernelTopology::Indirect`] the consumer's per-event dispatch
/// drives the size — every consumer carries the same `PerEvent` shape,
/// so picking the first is structural (the well-formed pass already
/// guards mismatches).
fn topology_workgroup_size_x(topology: &KernelTopology) -> u32 {
    let dispatch = match topology {
        KernelTopology::Fused { dispatch, .. } => *dispatch,
        KernelTopology::Split { dispatch, .. } => *dispatch,
        KernelTopology::Indirect { consumers: _, .. } => {
            // Indirect-dispatched consumers always carry PerEvent.
            // The well-formed pass guarantees consumers exist; if they
            // don't, the body lowering above would have already errored
            // with `EmptyKernelTopology`.
            DispatchShape::PerEvent {
                source_ring: crate::cg::data_handle::EventRingId(0),
            }
        }
    };
    dispatch.workgroup_size().x
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(dead_code, unused_imports)]
mod tests {
    use super::*;
    use crate::cg::data_handle::{
        AgentFieldId, AgentRef, CgExprId, DataHandle, EventRingId, MaskId,
    };
    use crate::cg::dispatch::DispatchShape;
    use crate::cg::expr::{BinaryOp, CgExpr, CgTy, LitValue};
    use crate::cg::lower::lower_compilation_to_cg;
    use crate::cg::op::{
        ComputeOp, ComputeOpKind, EventKindId, OpId, PhysicsRuleId, PlumbingKind,
        ReplayabilityFlag, Span,
    };
    use crate::cg::schedule::synthesis::{
        synthesize_schedule, ComputeStage, KernelTopology,
    };
    use crate::cg::schedule::ScheduleStrategy;
    use crate::cg::stmt::{CgStmt, CgStmtId, CgStmtList, CgStmtListId};
    use dsl_ast::ir::Compilation;

    // -- Test fixtures ---------------------------------------------------

    fn push_op(prog: &mut CgProgram, mut op: ComputeOp) -> OpId {
        let id = OpId(prog.ops.len() as u32);
        op.id = id;
        prog.ops.push(op);
        id
    }

    fn push_expr(prog: &mut CgProgram, e: CgExpr) -> CgExprId {
        let id = CgExprId(prog.exprs.len() as u32);
        prog.exprs.push(e);
        id
    }

    fn push_stmt(prog: &mut CgProgram, s: CgStmt) -> CgStmtId {
        let id = CgStmtId(prog.stmts.len() as u32);
        prog.stmts.push(s);
        id
    }

    fn push_list(prog: &mut CgProgram, l: CgStmtList) -> CgStmtListId {
        let id = CgStmtListId(prog.stmt_lists.len() as u32);
        prog.stmt_lists.push(l);
        id
    }

    /// Build a single MaskPredicate op `mask[m] = (self.hp < 5.0)`.
    fn mask_op(prog: &mut CgProgram, mask: MaskId) -> OpId {
        let hp = push_expr(
            prog,
            CgExpr::Read(DataHandle::AgentField {
                field: AgentFieldId::Hp,
                target: AgentRef::Self_,
            }),
        );
        let five = push_expr(prog, CgExpr::Lit(LitValue::F32(5.0)));
        let lt = push_expr(
            prog,
            CgExpr::Binary {
                op: BinaryOp::LtF32,
                lhs: hp,
                rhs: five,
                ty: CgTy::Bool,
            },
        );
        let kind = ComputeOpKind::MaskPredicate {
            mask,
            predicate: lt,
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::PerAgent,
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    /// Build a PhysicsRule op `self.hp = self.hp + 1.0` over `ring`.
    fn physics_op(prog: &mut CgProgram, rule: PhysicsRuleId, ring: EventRingId) -> OpId {
        let hp_read = push_expr(
            prog,
            CgExpr::Read(DataHandle::AgentField {
                field: AgentFieldId::Hp,
                target: AgentRef::Self_,
            }),
        );
        let one = push_expr(prog, CgExpr::Lit(LitValue::F32(1.0)));
        let add = push_expr(
            prog,
            CgExpr::Binary {
                op: BinaryOp::AddF32,
                lhs: hp_read,
                rhs: one,
                ty: CgTy::F32,
            },
        );
        let assign = push_stmt(
            prog,
            CgStmt::Assign {
                target: DataHandle::AgentField {
                    field: AgentFieldId::Hp,
                    target: AgentRef::Self_,
                },
                value: add,
            },
        );
        let body = push_list(prog, CgStmtList { stmts: vec![assign] });
        let kind = ComputeOpKind::PhysicsRule {
            rule,
            on_event: Some(EventKindId(0)),
            body,
            replayable: ReplayabilityFlag::Replayable,
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::PerEvent { source_ring: ring },
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    fn seed_indirect_op(prog: &mut CgProgram, ring: EventRingId) -> OpId {
        let kind = ComputeOpKind::Plumbing {
            kind: PlumbingKind::SeedIndirectArgs { ring },
        };
        let op = ComputeOp::new(
            OpId(0),
            kind,
            DispatchShape::OneShot,
            Span::dummy(),
            prog,
            prog,
            prog,
        );
        push_op(prog, op)
    }

    /// Wrap a single kernel topology into a one-stage schedule.
    fn one_stage(topology: KernelTopology) -> ComputeSchedule {
        ComputeSchedule {
            stages: vec![ComputeStage {
                kernels: vec![topology],
            }],
        }
    }

    // ---- 1. Empty schedule ----


    // ---- 2. Single Split kernel ----


    // ---- 3. Multi-stage schedule ----


    // ---- 4. Snapshot — a non-trivial Rust module's full output ----


    // ---- 11. lib.rs synthesis (Task 5.2) ----
}
