//! Subsystem 2 Phase 4 — GPU side storage for `@per_entity_ring` views.
//!
//! Companion to the CPU `Memory` struct generated by
//! `emit_view::emit_per_entity_ring_struct` (Phase 1, commit
//! `edc4c73c`) and the WGSL fold kernel emitted by
//! `crates/dsl_compiler/src/emit_view_wgsl.rs::emit_per_entity_ring_fold_wgsl`
//! (Phase 1, commit `6176d21d`).
//!
//! # Binding layout (must stay in lockstep with the resident physics BGL)
//!
//!   * slot 20 — `memory_records_buf` : `array<MemoryEventGpu>`, flat,
//!     indexed as `owner_slot * K + slot_idx`. Sized
//!     `agent_cap * K * sizeof(MemoryEventGpu) = agent_cap * K * 24`
//!     bytes.
//!   * slot 21 — `memory_cursors_buf` : `array<atomic<u32>>`, one
//!     monotonic write cursor per owner slot. Sized `agent_cap * 4`
//!     bytes.
//!
//! Slot 17 is `gold_buf` (Phase 3 Task 3.4). Slots 18 / 19 are
//! `standing_records_buf` / `standing_counts_buf` (Task #79). Slots
//! 22+ are reserved for Subsystem 3 (ability-eval GPU port). Keeping
//! memory at 20 / 21 mirrors the gold / standing numbering pattern
//! (each new cold-state side buffer pair follows the last).
//!
//! # Byte layout: `MemoryEventGpu` (24 bytes)
//!
//! Mirrors the CPU `MemoryEvent` struct byte-for-byte so the Rust
//! side's natural alignment of
//!
//! ```text
//!   MemoryEvent {
//!       source:        AgentId (NonZeroU32, 4B) @ offset 0
//!       kind:          u8                        @ offset 4 (+3 pad)
//!       payload:       u64                       @ offset 8 (align-8)
//!       confidence_q8: u8                        @ offset 16 (+3 pad)
//!       tick:          u32                       @ offset 20
//!   }                                            // size 24, align 8
//! ```
//!
//! ...lands identically on GPU. The WGSL side packs `kind` /
//! `confidence_q8` as whole `u32` slots (zero-extended on write) to
//! sidestep byte-addressable load/store limitations — every 4-byte
//! slot still carries the right value on readback:
//!
//! ```text
//!   struct MemoryEventGpu {
//!       source:      u32,  // @ offset 0  — raw AgentId (0 = empty slot)
//!       kind:        u32,  // @ offset 4  — low 8 bits hold the kind; upper pads
//!       payload_lo:  u32,  // @ offset 8  — low 32 bits of u64 payload
//!       payload_hi:  u32,  // @ offset 12 — high 32 bits of u64 payload
//!       confidence:  u32,  // @ offset 16 — low 8 bits hold conf_q8; upper pads
//!       tick:        u32,  // @ offset 20 — tick of write
//!   }                     // 24 B
//! ```
//!
//! The on-GPU `state_push_agent_memory(observer, source, payload,
//! confidence, tick)` stub lowered by the physics emitter today passes
//! `payload: u32` (the low 32 bits of the event's `u64 fact_payload`)
//! and `confidence: f32`. The stub body quantises `confidence` to q8
//! (`u8` stored in a `u32` slot), hardcodes `kind = 0` to match the
//! CPU `record_memory` generated rule (see
//! `crates/engine/src/generated/physics/record_memory.rs:23`), and
//! writes `payload_hi = 0`. This is a documented truncation against
//! the CPU side, which also feeds only the low u32 of `fact_payload`
//! through the DSL stdlib at present — both paths agree on what they
//! store. When a future subsystem widens the payload, both halves are
//! already available on the GPU struct without a re-layout.
//!
//! # Ring semantics — FIFO, monotonic cursor, no eviction policy
//!
//! Per the Phase 1 emitters:
//!
//!   - Each owner has a **monotonic `u32` write cursor**. Writes land
//!     at `ring[owner * K + (cursor % K)]` and then do
//!     `atomicAdd(cursors[owner], 1u)`. The cursor never resets to 0
//!     within a session; after `K` writes the oldest slot is
//!     overwritten (natural FIFO eviction).
//!   - No find-or-update: the ring doesn't dedupe by `source`. Two
//!     events from the same source occupy two slots.
//!   - No clamp, no eviction tiebreak (unlike `symmetric_pair_topk`):
//!     monotonic cursor + modulo makes the GPU contender naturally
//!     race-safe — `atomicAdd` on the cursor serialises writers to the
//!     same owner row, and each writer's returned counter mod K is
//!     their exclusive slot.
//!
//! # Readback ordering
//!
//! The GPU buffer holds the ring in **slot order** (slot 0..K-1 per
//! owner). CPU consumers that want chronological order must combine
//! the raw slot slice with the owner's cursor:
//!
//! ```ignore
//!   // iterate N writes oldest-to-newest, for owner `o`:
//!   let cur = cursors[o];
//!   let n = cur.min(K);
//!   let start = cur.saturating_sub(n);
//!   for i in 0..n {
//!       let slot = (start + i) % K;
//!       // ... read records[o * K + slot]
//!   }
//! ```
//!
//! [`ViewStoragePerEntityRing::readback_into_cpu`] uses this
//! projection so the returned list of `MemoryEvent`s is in write
//! order, matching `SimState::push_agent_memory`'s append semantics.
//!
//! # Concurrency on GPU
//!
//! Naturally race-safe — unlike SymmetricPairTopK there is no linear
//! scan, no CAS loop, and no eviction tiebreak. `atomicAdd` on
//! `cursors[owner]` serialises all writers to the same owner row; the
//! returned counter value mod K is each writer's exclusive slot.
//! Multiple events with the same owner in one dispatch all get
//! distinct slot indices. Order within a dispatch is non-deterministic
//! w.r.t. the CPU reference, but the "newest K entries win" invariant
//! is preserved.

#![cfg(feature = "gpu")]

use bytemuck::{Pod, Zeroable};

use engine::ids::AgentId;
use engine::state::agent_types::MemoryEvent;

/// Slot count per owner — the `K` from `per_entity_ring(K=64)` on
/// the memory view.
pub const MEMORY_K: u32 = 64;

/// GPU-side memory record. 24 bytes to match the CPU `MemoryEvent`
/// byte-for-byte (see module docs for the offset table).
#[repr(C)]
#[derive(Debug, Clone, Copy, Default, Pod, Zeroable, PartialEq, Eq)]
pub struct MemoryEventGpu {
    /// Raw AgentId of the event source. `0` marks an empty / never-written slot.
    pub source: u32,
    /// Kind discriminant (low 8 bits). Hardcoded to 0 by
    /// `record_memory::record_memory` on CPU today.
    pub kind: u32,
    /// Low 32 bits of the 64-bit payload.
    pub payload_lo: u32,
    /// High 32 bits of the 64-bit payload.
    pub payload_hi: u32,
    /// Confidence quantised to q8 (low 8 bits of this slot).
    pub confidence: u32,
    /// Tick at which this record was written.
    pub tick: u32,
}

impl MemoryEventGpu {
    /// Convert a CPU `MemoryEvent` into its GPU representation.
    #[inline]
    pub fn from_cpu(ev: &MemoryEvent) -> Self {
        Self {
            source: ev.source.raw(),
            kind: ev.kind as u32,
            payload_lo: ev.payload as u32,
            payload_hi: (ev.payload >> 32) as u32,
            confidence: ev.confidence_q8 as u32,
            tick: ev.tick,
        }
    }

    /// Convert a GPU record back into a CPU `MemoryEvent`. Returns
    /// `None` when `source == 0` (empty slot).
    #[inline]
    pub fn to_cpu(&self) -> Option<MemoryEvent> {
        let src = AgentId::new(self.source)?;
        let payload = ((self.payload_hi as u64) << 32) | (self.payload_lo as u64);
        let kind = (self.kind & 0xFFu32) as u8;
        let confidence_q8 = (self.confidence & 0xFFu32) as u8;
        Some(MemoryEvent {
            source: src,
            kind,
            payload,
            confidence_q8,
            tick: self.tick,
        })
    }
}

/// Resident-path storage for the `memory` view. Two buffers owned by
/// `ResidentPathContext`:
///
///   * `records_buf` — flat `[MemoryEventGpu; agent_cap * K]`.
///   * `cursors_buf` — one `atomic<u32>` per owner slot.
///
/// Allocated on first `ensure_resident_init` call + on `agent_cap`
/// grow; bound into the resident physics BGL at slots 20 / 21; read
/// back in `snapshot()` and merged into `state.cold_memory` (or, post
/// PR-5, `state.views.memory`).
pub struct ViewStoragePerEntityRing {
    pub records_buf: wgpu::Buffer,
    pub cursors_buf: wgpu::Buffer,
    pub agent_cap: u32,
    pub k: u32,
}

impl ViewStoragePerEntityRing {
    /// Byte size of the records buffer for `agent_cap * k` slots.
    pub fn records_bytes(agent_cap: u32, k: u32) -> u64 {
        (agent_cap as u64)
            .saturating_mul(k as u64)
            .saturating_mul(std::mem::size_of::<MemoryEventGpu>() as u64)
            .max(std::mem::size_of::<MemoryEventGpu>() as u64)
    }

    /// Byte size of the cursors buffer for `agent_cap` owners.
    pub fn cursors_bytes(agent_cap: u32) -> u64 {
        (agent_cap as u64).saturating_mul(4).max(4)
    }

    /// Allocate storage for `agent_cap` owners with `K = k` slots
    /// each. Buffers are zero-initialised by wgpu (no
    /// `mapped_at_creation`); the caller's `upload_from_cpu` populates
    /// from a CPU ring.
    pub fn new(device: &wgpu::Device, agent_cap: u32, k: u32) -> Self {
        let records_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("engine_gpu::view_storage_per_entity_ring::records"),
            size: Self::records_bytes(agent_cap, k),
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::COPY_SRC
                | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let cursors_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("engine_gpu::view_storage_per_entity_ring::cursors"),
            size: Self::cursors_bytes(agent_cap),
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::COPY_SRC
                | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        Self {
            records_buf,
            cursors_buf,
            agent_cap,
            k,
        }
    }

    /// Serialise a CPU-side per-agent memory ring into the flat GPU
    /// arrays. The caller supplies a closure mapping each owner slot
    /// (0-based) to its list of pushed events — this lets the
    /// function work uniformly against both the pre-PR-5
    /// `SimState.cold_memory[slot].to_vec()` shape and the post-PR-5
    /// `state.views.memory.entries(owner)`-derived shape without
    /// forcing `engine_gpu` to name-depend on either concrete
    /// container type.
    ///
    /// `get_row` returns `None` for owner slots beyond the CPU ring's
    /// provisioned length (the GPU row is left zero-initialised for
    /// those); the returned Vec's `len()` is the cursor (<= K).
    /// Upload is a cold path (init + agent_cap grow only), so the
    /// owned-Vec copy is acceptable over a more elaborate borrow
    /// protocol.
    pub fn upload_from_cpu<F>(&self, queue: &wgpu::Queue, mut get_row: F)
    where
        F: FnMut(usize) -> Option<Vec<MemoryEvent>>,
    {
        let k = self.k as usize;
        let cap = self.agent_cap as usize;

        let mut records = vec![MemoryEventGpu::default(); cap * k];
        let mut cursors: Vec<u32> = vec![0; cap];

        for owner_slot in 0..cap {
            let Some(row) = get_row(owner_slot) else {
                continue;
            };
            // The cursor = number of pushes seen. Our CPU-side
            // ring caps at K=64 via `push`, so cursor = row.len().
            cursors[owner_slot] = (row.len() as u32).min(self.k);
            for (i, ev) in row.iter().enumerate() {
                if i >= k {
                    break;
                }
                let dst = owner_slot * k + i;
                records[dst] = MemoryEventGpu::from_cpu(ev);
            }
        }

        if !records.is_empty() {
            queue.write_buffer(&self.records_buf, 0, bytemuck::cast_slice(&records));
        }
        if !cursors.is_empty() {
            queue.write_buffer(&self.cursors_buf, 0, bytemuck::cast_slice(&cursors));
        }
    }

    /// Read the GPU storage back, returning one Vec of events per
    /// owner slot (in chronological order, oldest to newest).
    /// Blocking — allocates a throwaway staging buffer per call. Fine
    /// for `snapshot()` (Option (a) per the plan; mirrors the
    /// `gold_buf` / `standing_storage` readback pattern).
    ///
    /// Per-owner the returned Vec's shape is:
    ///
    ///   - Empty (`cursor == 0`): never written.
    ///   - `cursor <= K`: the first `cursor` slots, in order.
    ///   - `cursor > K`: `K` events, the oldest at
    ///     `(cursor - K) % K` and wrapping forward.
    ///
    /// Each element is the result of
    /// [`MemoryEventGpu::to_cpu`]; empty / zeroed slots surface as
    /// `None` there and are skipped (a ring with missing slots
    /// between populated ones is not reachable under the monotonic
    /// cursor contract, so this is a belt-and-braces guard, not a
    /// semantic case).
    pub fn readback_into_cpu(
        &self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
    ) -> Result<Vec<Vec<MemoryEvent>>, String> {
        let cap = self.agent_cap as usize;
        let k = self.k as usize;
        if cap == 0 || k == 0 {
            return Ok(Vec::new());
        }

        let records_bytes = Self::records_bytes(self.agent_cap, self.k) as usize;
        let cursors_bytes = Self::cursors_bytes(self.agent_cap) as usize;

        let records: Vec<MemoryEventGpu> = crate::gpu_util::readback::readback_typed(
            device,
            queue,
            &self.records_buf,
            records_bytes,
        )
        .map_err(|e| format!("memory records readback: {e}"))?;
        let cursors: Vec<u32> = crate::gpu_util::readback::readback_typed(
            device,
            queue,
            &self.cursors_buf,
            cursors_bytes,
        )
        .map_err(|e| format!("memory cursors readback: {e}"))?;

        let k_u32 = self.k;
        let mut out: Vec<Vec<MemoryEvent>> = Vec::with_capacity(cap);
        for owner_slot in 0..cap {
            let cursor = cursors.get(owner_slot).copied().unwrap_or(0);
            if cursor == 0 {
                out.push(Vec::new());
                continue;
            }
            let writes = cursor.min(k_u32);
            let start_abs = cursor.saturating_sub(writes);
            let row_base = owner_slot * k;
            let mut row = Vec::with_capacity(writes as usize);
            for i in 0..writes {
                let abs = start_abs + i;
                let slot = (abs % k_u32) as usize;
                let rec = records[row_base + slot];
                if let Some(cpu_ev) = rec.to_cpu() {
                    row.push(cpu_ev);
                }
            }
            out.push(row);
        }
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use engine::state::{AgentSpawn, SimState};
    use engine::creature::CreatureType;
    use glam::Vec3;

    /// Adapter — given a `SimState` reference, produce a closure that
    /// converts `cold_memory[slot]` to `Vec<MemoryEvent>` for
    /// [`ViewStoragePerEntityRing::upload_from_cpu`].
    fn row_getter(
        state: &SimState,
    ) -> impl FnMut(usize) -> Option<Vec<MemoryEvent>> + '_ {
        let mem = state.cold_memory();
        move |slot| mem.get(slot).map(|row| row.as_slice().to_vec())
    }

    fn gpu_device_queue() -> (wgpu::Device, wgpu::Queue) {
        pollster::block_on(async {
            let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {
                backends: wgpu::Backends::all(),
                ..Default::default()
            });
            let adapter = instance
                .request_adapter(&wgpu::RequestAdapterOptions {
                    power_preference: wgpu::PowerPreference::HighPerformance,
                    compatible_surface: None,
                    force_fallback_adapter: false,
                })
                .await
                .expect("adapter");
            let adapter_limits = adapter.limits();
            let (device, queue) = adapter
                .request_device(&wgpu::DeviceDescriptor {
                    label: Some("view_storage_per_entity_ring::test::device"),
                    required_features: wgpu::Features::empty(),
                    required_limits: adapter_limits,
                    memory_hints: wgpu::MemoryHints::default(),
                    trace: wgpu::Trace::Off,
                })
                .await
                .expect("device");
            (device, queue)
        })
    }

    fn seed_state(cap: u32) -> SimState {
        let mut state = SimState::new(cap, 0xDEAD_BEEF);
        for i in 0..cap {
            state
                .spawn_agent(AgentSpawn {
                    creature_type: CreatureType::Human,
                    pos: Vec3::new(i as f32 * 2.0, 0.0, 0.0),
                    hp: 100.0,
                    ..Default::default()
                })
                .expect("spawn");
        }
        state
    }

    #[test]
    fn memory_event_gpu_is_24_bytes() {
        assert_eq!(std::mem::size_of::<MemoryEventGpu>(), 24);
        assert_eq!(std::mem::align_of::<MemoryEventGpu>(), 4);
    }

    #[test]
    fn new_allocates_records_and_cursors() {
        let (device, _queue) = gpu_device_queue();
        let cap = 16u32;
        let storage = ViewStoragePerEntityRing::new(&device, cap, MEMORY_K);
        assert_eq!(storage.agent_cap, cap);
        assert_eq!(storage.k, MEMORY_K);
        assert_eq!(
            storage.records_buf.size(),
            (cap as u64) * (MEMORY_K as u64) * 24,
        );
        assert_eq!(storage.cursors_buf.size(), (cap as u64) * 4);
    }

    #[test]
    fn new_handles_zero_cap() {
        let (device, _queue) = gpu_device_queue();
        // Zero cap must still produce a valid (nonzero-size) buffer
        // because wgpu rejects zero-size storage buffers.
        let storage = ViewStoragePerEntityRing::new(&device, 0, MEMORY_K);
        assert!(storage.records_buf.size() >= 24);
        assert!(storage.cursors_buf.size() >= 4);
    }

    #[test]
    fn from_cpu_to_cpu_round_trips_one_event() {
        let cpu = MemoryEvent {
            source: AgentId::new(7).unwrap(),
            kind: 3,
            payload: 0xDEAD_BEEF_CAFE_F00D,
            confidence_q8: 200,
            tick: 42,
        };
        let gpu = MemoryEventGpu::from_cpu(&cpu);
        let back = gpu.to_cpu().expect("non-empty");
        assert_eq!(back, cpu);
    }

    #[test]
    fn upload_readback_round_trip_single_event() {
        let (device, queue) = gpu_device_queue();
        let cap = 8u32;
        let storage = ViewStoragePerEntityRing::new(&device, cap, MEMORY_K);

        let mut state = seed_state(cap);
        let owner = AgentId::new(3).unwrap();
        state.push_agent_memory(
            owner,
            MemoryEvent {
                source: AgentId::new(5).unwrap(),
                kind: 0,
                payload: 0xDEAD_BEEF,
                confidence_q8: 200,
                tick: 11,
            },
        );
        storage.upload_from_cpu(&queue, row_getter(&state));

        let out = storage
            .readback_into_cpu(&device, &queue)
            .expect("readback");

        let owner_row = &out[(owner.raw() - 1) as usize];
        assert_eq!(owner_row.len(), 1);
        assert_eq!(owner_row[0].source.raw(), 5);
        assert_eq!(owner_row[0].payload, 0xDEAD_BEEF);
        assert_eq!(owner_row[0].confidence_q8, 200);
        assert_eq!(owner_row[0].tick, 11);
    }

    #[test]
    fn upload_readback_round_trip_multiple_events() {
        let (device, queue) = gpu_device_queue();
        let cap = 8u32;
        let storage = ViewStoragePerEntityRing::new(&device, cap, MEMORY_K);

        let mut state = seed_state(cap);
        let owner = AgentId::new(2).unwrap();
        for i in 0..5u32 {
            state.push_agent_memory(
                owner,
                MemoryEvent {
                    source: AgentId::new(i + 1).unwrap(),
                    kind: 0,
                    payload: u64::from(i) + 100,
                    confidence_q8: 128,
                    tick: 10 + i,
                },
            );
        }
        storage.upload_from_cpu(&queue, row_getter(&state));

        let out = storage
            .readback_into_cpu(&device, &queue)
            .expect("readback");

        let row = &out[(owner.raw() - 1) as usize];
        assert_eq!(row.len(), 5);
        for i in 0..5u32 {
            assert_eq!(row[i as usize].source.raw(), i + 1);
            assert_eq!(row[i as usize].payload, u64::from(i) + 100);
            assert_eq!(row[i as usize].tick, 10 + i);
        }
    }

    #[test]
    fn empty_cpu_round_trips_empty() {
        let (device, queue) = gpu_device_queue();
        let storage = ViewStoragePerEntityRing::new(&device, 8, MEMORY_K);

        let state = seed_state(8);
        storage.upload_from_cpu(&queue, row_getter(&state));

        let out = storage
            .readback_into_cpu(&device, &queue)
            .expect("readback");

        for row in out.iter() {
            assert!(row.is_empty());
        }
    }
}
