//! Pin: `@cascade(max_iter=N)`-scheduled kernels get a runtime
//! `DispatchOp::FixedPoint { kernel: KernelId::X, .. }` arm in the
//! synthesized step() body, with the dispatch wrapped in
//! `for _iter in 0..N { ... }` (Gap forest_fire#F follow-up).
//!
//! ## Slice scope
//!
//! Commit `9c5c7d8c` added the `@cascade` annotation surface — the
//! lower pass populates `CgProgram::cascade_max_iter` and the schedule
//! synthesizer emits the per-rule `max_iter` into
//! `DispatchOp::FixedPoint` entries. Until this follow-up, the
//! synthesized step() body matched only `Kernel(...)` /
//! `Indirect { ... }` arms, falling through to a catch-all `_ => {}`
//! that silently no-op'd cascade-annotated kernels at runtime.
//!
//! This test pins the catch-up: the build_helper detects `FixedPoint`
//! entries in the emitted `schedule.rs` and emits a per-kernel arm
//! that wraps the same dispatch body the `Kernel(...)` arm would have
//! used in a `for _iter in 0..N u32 { ... }` loop. MVP semantics:
//! unconditional loop, no early-break on no-change. Re-running an
//! idempotent fixed-point kernel past its convergence tick is safe.
//!
//! ## Strategy
//!
//! Construct a synthetic `KernelSpec` (mirrors a physics-rule kernel
//! that lowers via direct `Bindings { ... }` construction, NOT
//! `from_context_with_extras`) and a hand-crafted `schedule.rs` file
//! containing the `DispatchOp::FixedPoint` entry, then drive
//! `synthesize_runtime_core_a2` directly and assert the generated
//! source contains the FixedPoint arm shape + the for-loop wrapping.
//! Synthetic spec keeps the test independent of the full DSL→CG→emit
//! stack; the lower / schedule / emit pipeline is exercised by
//! `tests/cascade_annotation_lower.rs`.

use dsl_compiler::build_helper::synthesize_runtime_core_a2;
use dsl_compiler::cg::emit::EmittedArtifacts;
use dsl_compiler::kernel_binding_ir::{
    AccessMode, BgSource, KernelBinding, KernelKind, KernelSpec,
};

/// A minimal physics-shape kernel: one fixture-owned binding plus the
/// mandatory `cfg` Cfg-source slot. The direct-Bindings emit path
/// (no `from_context_with_extras`) is the production path for
/// physics-rule kernels.
fn physics_shape_kernel_spec(name: &str, pascal: &str) -> KernelSpec {
    KernelSpec {
        name: name.into(),
        pascal: pascal.into(),
        entry_point: format!("cs_{name}"),
        cfg_struct: format!("{pascal}Cfg"),
        cfg_build_expr: format!("{pascal}Cfg::default()"),
        cfg_struct_decl: format!(
            "#[repr(C)]\n#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]\n\
             pub struct {pascal}Cfg {{ pub agent_cap: u32, pub tick: u32, pub _pad: [u32; 2] }}\n",
        ),
        bindings: vec![
            KernelBinding {
                slot: 0,
                name: "agent_hp".into(),
                access: AccessMode::ReadStorage,
                wgsl_ty: "array<f32>".into(),
                bg_source: BgSource::External("agent_hp".into()),
            },
            KernelBinding {
                slot: 1,
                name: "cfg".into(),
                access: AccessMode::Uniform,
                wgsl_ty: format!("{pascal}Cfg"),
                bg_source: BgSource::Cfg,
            },
        ],
        kind: KernelKind::Generic,
        y_dim_override: None,
        runtime_cfg_fields: Vec::new(),
    }
}

/// Construct an `EmittedArtifacts` with one kernel `spec` and a
/// hand-crafted `schedule.rs` containing a `DispatchOp::FixedPoint`
/// entry for that kernel. Mirrors the shape `synthesize_schedule`
/// emits for a `@cascade(max_iter=N)`-annotated physics rule.
fn artifacts_with_fixed_point(spec: KernelSpec, max_iter: u32) -> EmittedArtifacts {
    // The format matches `cg::emit::cross_cutting::synthesize_schedule`
    // exactly — that's what the build_helper parses out of the
    // schedule.rs file to discover FixedPoint kernels.
    let schedule_rs = format!(
        "// GENERATED by dsl_compiler — do not edit by hand.\n\
         use crate::{{KernelId, BufferRef}};\n\
         \n\
         #[derive(Copy, Clone, Debug)]\n\
         pub enum DispatchOp {{\n\
             Kernel(KernelId),\n\
             FixedPoint {{ kernel: KernelId, max_iter: u32 }},\n\
             Indirect {{ kernel: KernelId, args_buf: BufferRef }},\n\
             GatedBy {{ kernel: KernelId, gate: BufferRef }},\n\
         }}\n\
         \n\
         pub const SCHEDULE: &[DispatchOp] = &[\n\
         \x20   DispatchOp::FixedPoint {{ kernel: KernelId::{pascal}, max_iter: {max_iter} }},\n\
         ];\n",
        pascal = spec.pascal,
    );
    let mut rust_files = std::collections::BTreeMap::new();
    rust_files.insert("schedule.rs".to_string(), schedule_rs);
    // Empty per-kernel rust_files entry → build_helper takes the
    // direct-Bindings emit path (no `from_context_with_extras`).
    rust_files.insert(format!("{}.rs", spec.name), String::new());
    EmittedArtifacts {
        kernel_index: vec![spec.name.clone()],
        kernel_specs: vec![spec],
        rust_files,
        ..Default::default()
    }
}

fn synthesize(artifacts: &EmittedArtifacts) -> String {
    synthesize_runtime_core_a2(
        "cascade_fp_dispatch_test",
        artifacts,
        &[],
        &[],
        &std::collections::BTreeMap::new(),
        &[],
        &[],
        None,
        &[],
        false,
        false, // binds_navgrid
        &[],
        &[],
        0,
        0,
        false,
        None,
        "{\"bindings\":[]}",
        "{\"arena_radius\":0.0,\"camera\":\"Observer\",\"agents\":[],\"vfx\":[]}",
        "{\"hud\":[],\"screens\":[]}",
        dsl_compiler::cg::lower::DebugDepth::Off,
    )
}

#[test]
fn fixed_point_kernel_arm_uses_fixedpoint_dispatch_op_pattern() {
    let artifacts =
        artifacts_with_fixed_point(physics_shape_kernel_spec("physics_tickle", "PhysicsTickle"), 8);
    let core = synthesize(&artifacts);

    // The arm pattern must match `DispatchOp::FixedPoint { kernel:
    // KernelId::PhysicsTickle, .. }` (not the legacy `Kernel(...)`
    // shape). The `..` rest pattern absorbs `max_iter` so the runtime
    // doesn't need to read it back — the loop count is baked into the
    // for-loop literal at codegen time.
    assert!(
        core.contains("schedule::DispatchOp::FixedPoint { kernel: KernelId::PhysicsTickle, .. }"),
        "missing FixedPoint arm pattern for cascade-annotated kernel.\n\
         --- generated runtime_core.rs ---\n{core}",
    );
}

#[test]
fn fixed_point_kernel_dispatch_body_wrapped_in_for_loop() {
    let artifacts =
        artifacts_with_fixed_point(physics_shape_kernel_spec("physics_tickle", "PhysicsTickle"), 8);
    let core = synthesize(&artifacts);

    // The for-loop literal: `for _iter in 0..8u32 { ... }`. The
    // count is baked from the authored `@cascade(max_iter=N)` value
    // parsed out of the synthesized schedule.rs.
    assert!(
        core.contains("for _iter in 0..8u32 {"),
        "missing fixed-point for-loop wrapping the dispatch body.\n\
         --- generated runtime_core.rs ---\n{core}",
    );

    // The dispatch helper call must appear lexically AFTER the
    // `for _iter` open and BEFORE the matching close. Find the arm
    // and grep within it.
    let arm_start = core
        .find("schedule::DispatchOp::FixedPoint { kernel: KernelId::PhysicsTickle, .. }")
        .expect("arm pattern present");
    // The arm body is everything from the arm_start to the next
    // top-level `_ => {}` catch-all — but a coarser bound is fine:
    // just check the dispatch call follows the for-loop open within
    // the next ~2 KiB of source.
    let window = &core[arm_start..core.len().min(arm_start + 4096)];
    let for_open = window
        .find("for _iter in 0..8u32 {")
        .expect("for-loop open inside arm");
    let dispatch_call = window
        .find("dispatch::dispatch_physics_tickle(")
        .expect("dispatch helper call inside arm");
    assert!(
        dispatch_call > for_open,
        "dispatch call must follow the for-loop open inside the arm.\n\
         --- generated runtime_core.rs ---\n{core}",
    );
}

#[test]
fn fixed_point_kernel_loop_count_threads_authored_max_iter() {
    // Distinct from the default `8` so we can tell "the authored value
    // took effect" from "the default happened to coincide".
    let artifacts =
        artifacts_with_fixed_point(physics_shape_kernel_spec("physics_tickle", "PhysicsTickle"), 12);
    let core = synthesize(&artifacts);

    assert!(
        core.contains("for _iter in 0..12u32 {"),
        "authored max_iter=12 must round-trip into the for-loop literal.\n\
         --- generated runtime_core.rs ---\n{core}",
    );
    // Sanity: the legacy `8` ceiling must NOT slip through.
    assert!(
        !core.contains("for _iter in 0..8u32 {"),
        "legacy max_iter=8 must not appear when the authored value is 12.\n\
         --- generated runtime_core.rs ---\n{core}",
    );
}

#[test]
fn non_fixed_point_kernel_still_uses_kernel_arm() {
    // Non-regression: a kernel scheduled as `DispatchOp::Kernel(...)`
    // (no `@cascade` annotation) keeps emitting the plain `Kernel(X)`
    // arm shape, with no for-loop wrapping. Build the artifacts by
    // hand with a `Kernel`-shape schedule entry.
    let spec = physics_shape_kernel_spec("plain_kernel", "PlainKernel");
    let schedule_rs = format!(
        "// GENERATED\n\
         use crate::{{KernelId, BufferRef}};\n\
         pub enum DispatchOp {{ Kernel(KernelId), FixedPoint {{ kernel: KernelId, max_iter: u32 }}, Indirect {{ kernel: KernelId, args_buf: BufferRef }}, GatedBy {{ kernel: KernelId, gate: BufferRef }} }}\n\
         pub const SCHEDULE: &[DispatchOp] = &[\n\
         \x20   DispatchOp::Kernel(KernelId::{pascal}),\n\
         ];\n",
        pascal = spec.pascal,
    );
    let mut rust_files = std::collections::BTreeMap::new();
    rust_files.insert("schedule.rs".to_string(), schedule_rs);
    rust_files.insert(format!("{}.rs", spec.name), String::new());
    let artifacts = EmittedArtifacts {
        kernel_index: vec![spec.name.clone()],
        kernel_specs: vec![spec],
        rust_files,
        ..Default::default()
    };
    let core = synthesize(&artifacts);

    assert!(
        core.contains("schedule::DispatchOp::Kernel(KernelId::PlainKernel)"),
        "non-annotated kernel must emit the plain `Kernel(X)` arm.\n\
         --- generated runtime_core.rs ---\n{core}",
    );
    // No for-loop wrapping — the dispatch call appears directly in
    // the arm body.
    assert!(
        !core.contains("for _iter in 0.."),
        "non-FixedPoint kernel must not produce a `for _iter in 0..` loop.\n\
         --- generated runtime_core.rs ---\n{core}",
    );
    // No FixedPoint arm pattern either.
    assert!(
        !core.contains("schedule::DispatchOp::FixedPoint { kernel: KernelId::PlainKernel"),
        "non-annotated kernel must not produce a FixedPoint arm.\n\
         --- generated runtime_core.rs ---\n{core}",
    );
}
