use dsl_compiler::emit_megakernel::{emit_megakernel_rs, emit_megakernel_wgsl};
use dsl_compiler::emit_schedule::{ScheduleEntry, DispatchOpKind};

#[test]
fn megakernel_rs_has_kernel_impl() {
    let entries = vec![
        ScheduleEntry { kernel: "FusedMask".into(), kind: DispatchOpKind::Kernel },
        ScheduleEntry { kernel: "Scoring".into(),   kind: DispatchOpKind::Kernel },
    ];
    let src = emit_megakernel_rs(&entries);
    assert!(src.starts_with("// GENERATED by dsl_compiler"));
    assert!(src.contains("pub struct MegaKernel"));
    assert!(src.contains("include_str!(\"megakernel.wgsl\")"));
}

#[test]
fn megakernel_wgsl_inlines_each_kernel() {
    let entries = vec![
        ScheduleEntry { kernel: "FusedMask".into(), kind: DispatchOpKind::Kernel },
        ScheduleEntry { kernel: "Scoring".into(),   kind: DispatchOpKind::Kernel },
    ];
    let wgsl = emit_megakernel_wgsl(&entries);
    assert!(wgsl.starts_with("// GENERATED by dsl_compiler"));
    assert!(wgsl.contains("// section: FusedMask"));
    assert!(wgsl.contains("// section: Scoring"));
}

#[test]
fn fixed_point_emits_while_loop() {
    let entries = vec![
        ScheduleEntry { kernel: "Physics".into(), kind: DispatchOpKind::FixedPoint { max_iter: 8 } },
    ];
    let wgsl = emit_megakernel_wgsl(&entries);
    assert!(wgsl.contains("while ("), "expected while loop, got: {wgsl}");
    assert!(wgsl.contains("8u"), "expected max_iter=8 bound");
}
