use dsl_compiler::emit_scoring_kernel::{emit_scoring_rs, emit_scoring_unpack_rs};

#[test]
fn scoring_rs_has_kernel_impl_and_view_bindings() {
    let src = emit_scoring_rs(&[]); // no views — minimal core layout
    assert!(src.starts_with("// GENERATED by dsl_compiler"));
    assert!(src.contains("pub struct ScoringKernel"));
    assert!(src.contains("impl crate::Kernel for ScoringKernel"));
    assert!(src.contains("include_str!(\"scoring.wgsl\")"));
    // 5 core bindings unconditional: agent_data, mask_bitmaps, scoring_table, scoring_out, cfg
    assert!(src.contains("// agent_data"));
    assert!(src.contains("// scoring_table"));
    assert!(src.contains("// scoring_out"));
}

#[test]
fn scoring_unpack_rs_has_impl() {
    let src = emit_scoring_unpack_rs();
    assert!(src.contains("pub struct ScoringUnpackKernel"));
    assert!(src.contains("impl crate::Kernel for ScoringUnpackKernel"));
}
