//! Smoke tests for the view-fold Rust emitter. The emitter now takes
//! a `&ViewIR`; these tests build a synthetic minimal view and walk
//! the assertion against the emitted source string. Each view kind
//! lowers to a distinct binding spec — exercising the IR refactor.

use dsl_compiler::ast::Span;
use dsl_compiler::emit_view_fold_kernel::emit_view_fold_rs;
use dsl_compiler::ir::{IrExpr, IrExprNode, IrType, StorageHint, ViewBodyIR, ViewIR, ViewKind};

fn dummy_view(name: &str, kind: ViewKind) -> ViewIR {
    let zero_lit = IrExprNode {
        kind: IrExpr::LitInt(0),
        span: Span::dummy(),
    };
    ViewIR {
        name: name.into(),
        kind,
        params: vec![],
        return_ty: IrType::I32,
        decay: None,
        body: ViewBodyIR::Fold {
            initial: zero_lit,
            handlers: vec![],
            clamp: None,
        },
        annotations: vec![],
        span: Span::dummy(),
    }
}

#[test]
fn fold_engaged_with_rs_has_kernel_impl() {
    let v = dummy_view(
        "engaged_with",
        ViewKind::Materialized(StorageHint::PairMap),
    );
    let src = emit_view_fold_rs(&v);
    assert!(src.starts_with("// GENERATED by dsl_compiler"));
    assert!(src.contains("pub struct FoldEngagedWithKernel"));
    assert!(src.contains("impl crate::Kernel for FoldEngagedWithKernel"));
    assert!(src.contains("include_str!(\"fold_engaged_with.wgsl\")"));
    assert!(src.contains("entry_point: Some(\"cs_fold_engaged_with\")"));
}

#[test]
fn fold_threat_level_rs_uses_view_specific_name() {
    let v = dummy_view(
        "threat_level",
        ViewKind::Materialized(StorageHint::PairMap),
    );
    let src = emit_view_fold_rs(&v);
    assert!(src.contains("pub struct FoldThreatLevelKernel"));
    assert!(src.contains("entry_point: Some(\"cs_fold_threat_level\")"));
}
