use dsl_compiler::emit_view_fold_kernel::emit_view_fold_rs;

#[test]
fn fold_engaged_with_rs_has_kernel_impl() {
    let src = emit_view_fold_rs("engaged_with");
    assert!(src.starts_with("// GENERATED by dsl_compiler"));
    assert!(src.contains("pub struct FoldEngagedWithKernel"));
    assert!(src.contains("impl crate::Kernel for FoldEngagedWithKernel"));
    assert!(src.contains("include_str!(\"fold_engaged_with.wgsl\")"));
    assert!(src.contains("entry_point: Some(\"cs_fold_engaged_with\")"));
}

#[test]
fn fold_threat_level_rs_uses_view_specific_name() {
    let src = emit_view_fold_rs("threat_level");
    assert!(src.contains("pub struct FoldThreatLevelKernel"));
    assert!(src.contains("entry_point: Some(\"cs_fold_threat_level\")"));
}
