use dsl_compiler::emit_kernel_index::emit_lib_rs;

#[test]
fn lib_rs_contains_kernel_trait_and_module_list() {
    let modules = vec![
        "fused_mask".to_string(),
        "scoring".to_string(),
        "pick_ability".to_string(),
    ];
    let src = emit_lib_rs(&modules);
    // Header
    assert!(src.starts_with("// GENERATED by dsl_compiler"), "missing header: {src}");
    // Module list
    assert!(src.contains("pub mod fused_mask;"));
    assert!(src.contains("pub mod scoring;"));
    assert!(src.contains("pub mod pick_ability;"));
    // Static prelude pieces
    assert!(src.contains("pub trait Kernel"));
    assert!(src.contains("pub enum KernelId"));
    assert!(src.contains("pub enum BufferRef"));
    // Shared-infrastructure module declarations are static, even on empty input
    assert!(src.contains("pub mod schedule;"));
    assert!(src.contains("pub mod resident_context;"));
    assert!(src.contains("pub mod pingpong_context;"));
    assert!(src.contains("pub mod pool;"));
    assert!(src.contains("pub mod transient_handles;"));
    assert!(src.contains("pub mod external_buffers;"));
    assert!(src.contains("pub mod binding_sources;"));
    // Trait signature: bind() takes &BindingSources, not &ResidentPathContext.
    assert!(src.contains("sources: &'a binding_sources::BindingSources"));
    assert!(src.contains("device: &wgpu::Device"));
}

#[test]
fn lib_rs_is_byte_stable_for_same_modules() {
    let modules = vec!["fused_mask".to_string(), "scoring".to_string()];
    let a = emit_lib_rs(&modules);
    let b = emit_lib_rs(&modules);
    assert_eq!(a, b);
}
