use dsl_compiler::emit_movement_kernel::emit_movement_rs;

#[test]
fn movement_rs_has_kernel_impl() {
    let src = emit_movement_rs();
    assert!(src.starts_with("// GENERATED by dsl_compiler"));
    assert!(src.contains("pub struct MovementKernel"));
    assert!(src.contains("impl crate::Kernel for MovementKernel"));
    assert!(src.contains("include_str!(\"movement.wgsl\")"));
    assert!(src.contains("entry_point: Some(\"cs_movement\")"));
}
