// GENERATED by dsl_compiler from assets/sim/entities.sim.
// Was emitted from .sim source by xtask `compile-dsl` (retired Phase 7, 2026-05-02); now hand-maintained.
// Do not edit by hand.

// Entity `Human` — an Agent-root creature. The `CreatureType::Human`
// variant, per-variant `Capabilities::for_creature(...)` arm, and
// hostility-matrix contribution live in this directory's `mod.rs`.

// This file is intentionally near-empty — see `mod.rs`.
#[allow(dead_code)]
pub(super) const __ENTITY_HUMAN: &str = "Human";
