// GENERATED by dsl_compiler from assets/sim/masks.sim.
use engine::ids::AgentId;
use engine::mask::TargetMask;
use engine::state::SimState;

#[allow(unused_variables)]
pub fn mask_attack(state: &SimState, self_id: AgentId, target: AgentId) -> bool {
    if !(true) {
        return false;
    }
    true
}

pub fn mask_attack_candidates(state: &SimState, self_id: AgentId, out: &mut TargetMask) {
    let self_pos = state.agent_pos(self_id).unwrap_or(glam::Vec3::ZERO);
    for target in state.agents_alive() {
        if target == self_id {
            continue;
        }
        let target_pos = state.agent_pos(target).unwrap_or(glam::Vec3::ZERO);
        if !(state.agent_alive(target)) {
            continue;
        }
        if !(crate::views::is_hostile(state, self_id, target)) {
            continue;
        }
        if !(self_pos.distance(target_pos) < 2.0) {
            continue;
        }
        out.push(self_id, engine::mask::MicroKind::Attack, target);
    }
}
