// GENERATED by dsl_compiler from assets/sim/masks.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use engine::ids::AgentId;
use engine::state::SimState;

/// Predicate: can `self_id` issue this mask's action head against the given target?
/// Lowered from `mask Cast` in `assets/sim/masks.sim`.
pub fn mask_cast(state: &SimState, self_id: AgentId, ability: engine::ability::AbilityId) -> bool {
    if !(state.agent_alive(self_id)) {
        return false;
    }
    if !(!(crate::views::is_stunned(state, self_id))) {
        return false;
    }
    if !(state.ability_registry.get(ability).is_some()) {
        return false;
    }
    if !(state.can_cast_ability(self_id, (ability).slot() as u8, state.tick as u32)) {
        return false;
    }
    if !((state.agent_engaged_with(self_id)).is_none()) {
        return false;
    }
    true
}
