// GENERATED by dsl_compiler from assets/sim/masks.sim.
use engine::ids::AgentId;
use engine::state::SimState;

pub fn mask_eat(state: &SimState, self_id: AgentId) -> bool {
    if !(state.agent_alive(self_id)) {
        return false;
    }
    true
}
