// GENERATED by dsl_compiler. Do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

pub mod attack;
pub mod cast;
pub mod drink;
pub mod eat;
pub mod flee;
pub mod hold;
pub mod move_toward;
pub mod rest;

pub use attack::mask_attack;
pub use attack::mask_attack_candidates;
pub use cast::mask_cast;
pub use drink::mask_drink;
pub use eat::mask_eat;
pub use flee::mask_flee;
pub use hold::mask_hold;
pub use move_toward::mask_move_toward;
pub use move_toward::mask_move_toward_candidates;
pub use rest::mask_rest;

pub fn register() {}
