// GENERATED by dsl_compiler from assets/sim/views.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use engine_data::events::Event;
use engine::ids::AgentId;

/// @materialized view `standing` — `storage = symmetric_pair_topk(K=8)`.
#[derive(Debug, Clone, Copy, Default)]
pub struct StandingEdge {
    pub other: u32,
    pub value: i32,
    pub anchor_tick: u32,
}

#[derive(Debug, Default)]
pub struct Standing {
    slots: Vec<[StandingEdge; 8]>,
}

impl Standing {
    pub const K: usize = 8;

    pub fn new() -> Self {
        Self::default()
    }

    pub fn len(&self) -> usize {
        self.slots.len()
    }
    pub fn is_empty(&self) -> bool {
        self.slots.is_empty()
    }

    fn canonical_pair(a: AgentId, b: AgentId) -> (AgentId, AgentId) {
        if a.raw() <= b.raw() {
            (a, b)
        } else {
            (b, a)
        }
    }

    pub fn get(&self, a: AgentId, b: AgentId) -> i32 {
        let (owner, other) = Self::canonical_pair(a, b);
        if owner.raw() == 0 || other.raw() == 0 {
            return 0;
        }
        let owner_slot = (owner.raw() - 1) as usize;
        let other_id = other.raw();
        let Some(row) = self.slots.get(owner_slot) else {
            return 0;
        };
        for s in row.iter() {
            if s.other == other_id {
                return s.value;
            }
        }
        0
    }

    fn row_mut(&mut self, owner_slot: usize) -> &mut [StandingEdge; 8] {
        if owner_slot >= self.slots.len() {
            self.slots
                .resize(owner_slot + 1, [StandingEdge::default(); 8]);
        }
        &mut self.slots[owner_slot]
    }

    pub fn adjust(&mut self, a: AgentId, b: AgentId, delta: i32, tick: u32) -> i32 {
        let (owner, other) = Self::canonical_pair(a, b);
        if owner.raw() == 0 || other.raw() == 0 {
            return 0;
        }
        let owner_slot = (owner.raw() - 1) as usize;
        let other_id = other.raw();
        let row = self.row_mut(owner_slot);
        for i in 0..8 {
            if row[i].other == other_id {
                let updated = row[i].value + delta;
                let updated = updated.clamp(-1000, 1000);
                row[i].value = updated;
                row[i].anchor_tick = tick;
                return updated;
            }
        }
        for i in 0..8 {
            if row[i].other == 0 {
                let v = delta.clamp(-1000, 1000);
                row[i] = StandingEdge {
                    other: other_id,
                    value: v,
                    anchor_tick: tick,
                };
                return v;
            }
        }
        let mut min_i: usize = 0;
        let mut min_mag: i32 = row[0].value.abs();
        for i in 1..8 {
            let m = row[i].value.abs();
            if m < min_mag {
                min_mag = m;
                min_i = i;
            }
        }
        if delta.abs() > min_mag {
            let v = delta.clamp(-1000, 1000);
            row[min_i] = StandingEdge {
                other: other_id,
                value: v,
                anchor_tick: tick,
            };
            return v;
        }
        0
    }

    pub fn fold_event(&mut self, event: &Event, tick: u32) {
        match event {
            Event::EffectStandingDelta { a, b, delta, .. } => {
                let delta: i32 = *delta as i32;
                self.adjust(*a, *b, delta, tick);
            }
            _ => {}
        }
    }
}
