// GENERATED by dsl_compiler from assets/sim/views.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use engine_data::events::Event;
use engine::ids::AgentId;

/// @materialized view `threat_level` — `storage = per_entity_topk(K=8)`.
/// @decay(rate = 0.98, per = tick)
#[derive(Debug, Clone, Copy, Default)]
pub struct TopkSlot {
    pub id: u32,
    pub value: f32,
    pub anchor_tick: u32,
}

#[derive(Debug, Default)]
pub struct ThreatLevel {
    slots: Vec<[TopkSlot; 8]>,
}

impl ThreatLevel {
    pub const K: usize = 8;
    pub const RATE: f32 = 0.98_f32;

    pub fn new() -> Self {
        Self::default()
    }

    pub fn len(&self) -> usize {
        self.slots.len()
    }
    pub fn is_empty(&self) -> bool {
        self.slots.is_empty()
    }

    pub fn get(&self, a: AgentId, b: AgentId, tick: u32) -> f32 {
        let obs_slot = (a.raw() - 1) as usize;
        let atk_id = b.raw();
        let Some(row) = self.slots.get(obs_slot) else {
            return 0.0;
        };
        for s in row.iter() {
            if s.id == atk_id {
                let dt = tick.saturating_sub(s.anchor_tick);
                let decayed = s.value * Self::RATE.powi(dt as i32);
                return decayed.clamp(0.0, 1000.0);
            }
        }
        0.0
    }

    pub fn sum_for_first(&self, a: AgentId, tick: u32) -> f32 {
        let obs_slot = (a.raw() - 1) as usize;
        let Some(row) = self.slots.get(obs_slot) else {
            return 0.0;
        };
        let mut total: f32 = 0.0;
        for s in row.iter() {
            if s.id == 0 {
                continue;
            }
            let dt = tick.saturating_sub(s.anchor_tick);
            let decayed = s.value * Self::RATE.powi(dt as i32);
            total += decayed.clamp(0.0, 1000.0);
        }
        total
    }

    fn row_mut(&mut self, obs_slot: usize) -> &mut [TopkSlot; 8] {
        if obs_slot >= self.slots.len() {
            self.slots.resize(obs_slot + 1, [TopkSlot::default(); 8]);
        }
        &mut self.slots[obs_slot]
    }

    fn fold_one(&mut self, observer: u32, attacker: u32, delta: f32, tick: u32) {
        if observer == 0 || attacker == 0 {
            return;
        }
        let obs_slot = (observer - 1) as usize;
        let row = self.row_mut(obs_slot);
        for i in 0..8 {
            if row[i].id == attacker {
                let dt = tick.saturating_sub(row[i].anchor_tick);
                let current = row[i].value * Self::RATE.powi(dt as i32);
                let updated = current + delta;
                let updated = updated.clamp(0.0, 1000.0);
                row[i].value = updated;
                row[i].anchor_tick = tick;
                return;
            }
        }
        for i in 0..8 {
            if row[i].id == 0 {
                let v = delta.clamp(0.0, 1000.0);
                row[i] = TopkSlot {
                    id: attacker,
                    value: v,
                    anchor_tick: tick,
                };
                return;
            }
        }
        let mut min_i: usize = 0;
        let mut min_v: f32 = {
            let dt = tick.saturating_sub(row[0].anchor_tick);
            row[0].value * Self::RATE.powi(dt as i32)
        };
        for i in 1..8 {
            let dt = tick.saturating_sub(row[i].anchor_tick);
            let v = row[i].value * Self::RATE.powi(dt as i32);
            if v < min_v {
                min_v = v;
                min_i = i;
            }
        }
        if delta > min_v {
            let v = delta.clamp(0.0, 1000.0);
            row[min_i] = TopkSlot {
                id: attacker,
                value: v,
                anchor_tick: tick,
            };
        }
    }

    pub fn fold_event(&mut self, event: &Event, tick: u32) {
        match event {
            Event::AgentAttacked { target, actor, .. } => {
                self.fold_one(target.raw(), actor.raw(), 1.0, tick);
            }
            Event::EffectDamageApplied { target, actor, .. } => {
                self.fold_one(target.raw(), actor.raw(), 1.0, tick);
            }
            _ => {}
        }
    }
}
