// GENERATED by dsl_compiler from assets/sim/scoring.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

// Per-block placeholder — the aggregate table in
// `mod.rs` owns every entry. Keeping this file around
// mirrors the other kinds' emission layout (physics,
// mask, entity) so the xtask's file-bookkeeping logic
// doesn't need a scoring-specific branch.

// Entries contributed by this block:
// - [0] head=`Hold` base=0.1 modifiers=0
// - [1] head=`MoveToward` base=0.3 modifiers=0
// - [2] head=`Flee` base=0.0 modifiers=2
// - [3] head=`Attack` base=0.0 modifiers=3
// - [4] head=`Cast` base=0.0 modifiers=0
// - [5] head=`UseItem` base=0.0 modifiers=0
// - [6] head=`Harvest` base=0.0 modifiers=0
// - [7] head=`Eat` base=0.0 modifiers=1
// - [8] head=`Drink` base=0.0 modifiers=0
// - [9] head=`Rest` base=0.0 modifiers=0
// - [10] head=`PlaceTile` base=0.0 modifiers=0
// - [11] head=`PlaceVoxel` base=0.0 modifiers=0
// - [12] head=`HarvestVoxel` base=0.0 modifiers=0
// - [13] head=`Converse` base=0.0 modifiers=0
// - [14] head=`ShareStory` base=0.0 modifiers=0
// - [15] head=`Communicate` base=0.0 modifiers=0
// - [16] head=`Ask` base=0.0 modifiers=0
// - [17] head=`Remember` base=0.0 modifiers=0
