// GENERATED by dsl_compiler from assets/sim/enums.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum GroupBehavior {
    OneVsOne = 0,
    NoFriendlyFire = 1,
    SharedPursuit = 2,
    EqualSpoils = 3,
}
