// GENERATED by dsl_compiler. Do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

pub mod combustion_reason;
pub mod group_behavior;

pub use combustion_reason::CombustionReason;
pub use group_behavior::GroupBehavior;
