//! Campaign state for headless simulation.
//!
//! All types are `Clone + Debug` for MCTS tree search (cheap state cloning,
//! deterministic stepping). The game world advances via fixed 100ms ticks.

use serde::{Deserialize, Serialize};

use super::config::CampaignConfig;

/// Fixed tick duration in milliseconds, matching the combat sim.
pub const CAMPAIGN_TICK_MS: u32 = 100;

// ---------------------------------------------------------------------------
// Top-level state
// ---------------------------------------------------------------------------

/// Complete campaign state as a plain, Clone-able struct.
///
/// Designed for MCTS: cheap to clone, deterministic to step.
/// No Bevy ECS — all state is explicit fields.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CampaignState {
    // --- Time ---
    /// Monotonic tick counter (increments by 1 each step).
    pub tick: u64,
    /// Total elapsed game time in milliseconds (`tick * CAMPAIGN_TICK_MS`).
    pub elapsed_ms: u64,

    // --- Guild ---
    pub guild: GuildState,

    // --- World ---
    pub overworld: OverworldState,
    pub factions: Vec<FactionState>,
    pub diplomacy: DiplomacyMatrix,

    // --- Units ---
    pub adventurers: Vec<Adventurer>,
    pub parties: Vec<Party>,

    // --- Quests ---
    /// Available requests on the guild board (not yet accepted).
    pub request_board: Vec<QuestRequest>,
    /// Accepted, in-progress quests.
    pub active_quests: Vec<ActiveQuest>,
    /// Completed quest history (bounded ring buffer in practice).
    pub completed_quests: Vec<CompletedQuest>,

    // --- Battles ---
    pub active_battles: Vec<BattleState>,

    // --- Progression ---
    /// Unlocked abilities/buffs. Effect-property vectors, NOT identity-indexed.
    pub unlocks: Vec<UnlockInstance>,
    pub progression_history: Vec<ProgressionEvent>,

    // --- Choices ---
    /// Pending choice events requiring player decision.
    /// If deadline passes, the `default_option` is auto-selected.
    pub pending_choices: Vec<ChoiceEvent>,

    // --- Hook state ---
    /// Tracks which quest hooks have fired and when.
    #[serde(default)]
    pub hook_state: super::quest_hooks::HookState,

    // --- Bonds ---
    /// Adventurer bond matrix. Key = (min_id, max_id), value = bond strength 0-100.
    #[serde(default)]
    pub adventurer_bonds: std::collections::HashMap<(u32, u32), f32>,

    // --- Narrative ---
    pub event_log: Vec<CampaignEvent>,
    pub npc_relationships: Vec<NpcRelationship>,

    // --- RNG ---
    /// LCG state for deterministic randomness. Isolated from combat sim RNG.
    pub rng: u64,

    // --- ID counters ---
    pub next_quest_id: u32,
    pub next_party_id: u32,
    pub next_battle_id: u32,
    pub next_unlock_id: u32,
    pub next_event_id: u32,

    // --- Combat mode ---
    pub combat_mode: CombatMode,

    // --- Progression queue ---
    /// Content generated by the LLM, cached until the next rest event.
    /// Items are added immediately when triggers fire, presented at rest.
    #[serde(default)]
    pub pending_progression: Vec<PendingProgression>,
    /// Whether the guild is currently resting (no quests dispatched, recovery active).
    #[serde(default)]
    pub resting: bool,
    /// Ticks since last rest (drives fatigue and rest prompts).
    #[serde(default)]
    pub ticks_since_rest: u64,

    // --- Campaign phase ---
    /// Current phase of the campaign.
    pub phase: CampaignPhase,

    /// Available starting packages. Loaded from data files.
    /// Emptied after the player chooses one.
    pub available_starting_choices: Vec<StartingChoice>,

    // --- Player character ---
    /// The player's created character. Built up during character creation.
    #[serde(default)]
    pub player_character: Option<PlayerCharacter>,

    /// Queue of backstory events to present during character creation.
    #[serde(default)]
    pub creation_event_queue: Vec<super::backstory::BackstoryEvent>,

    // --- Buildings ---
    /// Guild building upgrade tiers (0–3 each). Provides passive bonuses.
    #[serde(default)]
    pub guild_buildings: super::systems::buildings::GuildBuildings,

    // --- Configuration ---
    /// All tunable balance parameters. Systems read from this.
    pub config: CampaignConfig,

    // --- LLM content generation ---
    /// Optional LLM config for generating abilities/classes via Ollama.
    /// When None, falls back to template generators.
    #[serde(skip)]
    pub llm_config: Option<super::llm::LlmConfig>,
    /// Shared content store for LLM request/response logging and dedup.
    /// Arc so it survives Clone (BFS branches share the same store).
    #[serde(skip)]
    pub llm_store: Option<std::sync::Arc<super::llm::ContentStore>>,
    /// Optional VAE model for content generation (replaces LLM + templates).
    /// Arc so cloned states share the same weights.
    #[serde(skip)]
    pub vae_model: Option<std::sync::Arc<super::vae_inference::ContentVaeWeights>>,

    // --- Rival guild ---
    /// AI-controlled competing guild. Activates at tick 2000.
    #[serde(default)]
    pub rival_guild: RivalGuildState,

    // --- New systems state ---
    #[serde(default)]
    pub trade_routes: Vec<TradeRoute>,
    #[serde(default)]
    pub caravans: Vec<Caravan>,
    #[serde(default)]
    pub next_caravan_id: u32,
    #[serde(default)]
    pub next_route_id: u32,
    #[serde(default)]
    pub retired_adventurers: Vec<RetiredAdventurer>,
    #[serde(default)]
    pub mentor_assignments: Vec<MentorAssignment>,
    #[serde(default)]
    pub civil_wars: Vec<CivilWarState>,
    #[serde(default)]
    pub rumors: Vec<Rumor>,
    #[serde(default)]
    pub war_exhaustion: Vec<WarExhaustion>,
    #[serde(default)]
    pub spies: Vec<Spy>,
    #[serde(default)]
    pub next_spy_id: u32,
    #[serde(default)]
    pub available_mercenaries: Vec<MercenaryCompany>,
    #[serde(default)]
    pub hired_mercenaries: Vec<MercenaryCompany>,
    #[serde(default)]
    pub black_market: BlackMarketState,
    #[serde(default)]
    pub resource_nodes: Vec<ResourceNode>,
    #[serde(default)]
    pub gathering_boosts: std::collections::HashMap<usize, u64>,
    #[serde(default)]
    pub migrations: Vec<MigrationWave>,
    #[serde(default)]
    pub next_migration_id: u32,
    #[serde(default)]
    pub active_festivals: Vec<Festival>,
    #[serde(default)]
    pub rivalries: Vec<Rivalry>,
    #[serde(default)]
    pub chronicle: Vec<ChronicleEntry>,
    #[serde(default)]
    pub nemeses: Vec<Nemesis>,
    #[serde(default)]
    pub faction_favors: Vec<FactionFavor>,
    #[serde(default)]
    pub favor_requests: Vec<FavorRequest>,
    #[serde(default)]
    pub site_preparations: Vec<SitePreparation>,
    #[serde(default)]
    pub next_site_id: u32,
    #[serde(default)]
    pub council_votes: Vec<CouncilVote>,
    #[serde(default)]
    pub next_vote_id: u32,
    #[serde(default)]
    pub diseases: Vec<Disease>,
    #[serde(default)]
    pub next_disease_id: u32,
    #[serde(default)]
    pub prisoners: Vec<Prisoner>,
    #[serde(default)]
    pub next_prisoner_id: u32,
    #[serde(default)]
    pub captured_adventurers: Vec<u32>,
    #[serde(default)]
    pub propaganda_campaigns: Vec<PropagandaCampaign>,
    #[serde(default)]
    pub monster_populations: Vec<MonsterPopulation>,
    #[serde(default)]
    pub visions: Vec<Vision>,
    #[serde(default)]
    pub next_vision_id: u32,
    #[serde(default)]
    pub loans: Vec<Loan>,
    #[serde(default)]
    pub credit_rating: f32,
    #[serde(default)]
    pub victory_condition: VictoryCondition,
    #[serde(default)]
    pub victory_progress: VictoryProgress,
    #[serde(default)]
    pub named_npcs: Vec<NamedNpc>,
    #[serde(default)]
    pub artifacts: Vec<Artifact>,
    #[serde(default)]
    pub next_artifact_id: u32,
    #[serde(default)]
    pub difficulty_scaling: DifficultyState,
    #[serde(default)]
    pub regional_cultures: Vec<RegionalCulture>,
    #[serde(default)]
    pub dungeons: Vec<Dungeon>,
    /// Crafting resource stockpile.
    #[serde(default)]
    pub resources: std::collections::HashMap<ResourceType, f32>,

    // --- Extended system trackers ---
    /// Aggregate counters for the ~30 campaign subsystems.
    /// Updated by step logic; consumed by tokens, clustering, and value estimation.
    #[serde(default)]
    pub system_trackers: SystemTrackers,
}

// ---------------------------------------------------------------------------
// Extended system trackers
// ---------------------------------------------------------------------------

/// Aggregate counters for campaign subsystems that feed the token/clustering/value
/// pipeline. Each field is a cheap scalar maintained by the step logic. Defaults
/// to zero so old serialized states remain compatible.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct SystemTrackers {
    // --- Espionage ---
    /// Number of active spies embedded in factions.
    pub spy_count: u32,
    /// Total intel points gathered across the campaign.
    pub total_intel_gathered: f32,
    /// Average cover level of active spies (0-100).
    pub mean_spy_cover: f32,

    // --- Mercenaries ---
    /// Currently hired mercenaries across all active quests/battles.
    pub mercenaries_hired: u32,
    /// Total aggregate mercenary combat strength.
    pub total_mercenary_strength: f32,
    /// Average loyalty of hired mercenaries (0-100).
    pub mean_mercenary_loyalty: f32,

    // --- Black market ---
    /// Heat level from illicit activity (0-100). High heat attracts enforcement.
    pub black_market_heat: f32,
    /// Total profit from black market deals.
    pub black_market_profit: f32,
    /// Number of currently active black market deals.
    pub active_deals: u32,

    // --- Prisoners ---
    /// Captured enemy combatants held by the guild.
    pub prisoner_count: u32,
    /// Captured adventurers (our side) held by enemies.
    pub captured_adventurer_count: u32,

    // --- Loans ---
    /// Total outstanding debt from loans.
    pub total_debt: f32,
    /// Credit rating (0-100). Higher = better loan terms.
    pub credit_rating: f32,

    // --- Rumors ---
    /// Number of active unverified rumors.
    pub active_rumor_count: u32,
    /// Number of rumors that have been investigated.
    pub investigated_rumor_count: u32,

    // --- Civil wars ---
    /// Number of active civil wars between factions.
    pub active_civil_war_count: u32,
    /// Whether the guild is involved in any civil war.
    pub guild_civil_war_involvement: bool,

    // --- Diplomacy agreements ---
    /// Number of active trade agreements.
    pub trade_agreement_count: u32,
    /// Number of active non-aggression pacts.
    pub non_aggression_pact_count: u32,
    /// Number of active mutual defense treaties.
    pub mutual_defense_count: u32,
    /// Gold per tick from active trade agreements.
    pub active_trade_income: f32,

    // --- Rival guild extended ---
    /// Reputation gap (rival - player). Positive = behind.
    pub rival_reputation_gap: f32,
    /// Power gap (rival - player). Positive = behind.
    pub rival_power_gap: f32,
    /// Rate at which rival competes for the same quests (0-1).
    pub rival_quest_competition_rate: f32,

    // --- Caravans ---
    /// Number of active trade caravan routes.
    pub active_caravan_routes: u32,
    /// Total income from caravan trade.
    pub caravan_trade_income: f32,
    /// Number of caravans raided this campaign.
    pub caravans_raided: u32,

    // --- Retirement ---
    /// Number of adventurers who have retired.
    pub retired_count: u32,
    /// Sum of legacy bonuses from retired adventurers.
    pub total_legacy_bonuses: f32,

    // --- Monster ecology ---
    /// Total monster population across all regions.
    pub total_monster_population: f32,
    /// Highest aggression level among monster groups.
    pub highest_monster_aggression: f32,

    // --- Festivals ---
    /// Number of currently active festivals.
    pub active_festival_count: u32,
    /// Total festivals attended this campaign.
    pub festivals_attended: u32,

    // --- Backstory ---
    /// Fraction of adventurers that have backstory content (0-1).
    pub has_backstory_ratio: f32,
    /// Number of rival faction connections from backstories.
    pub rival_faction_connections: u32,

    // --- Mentorship ---
    /// Number of active mentor-mentee pairings.
    pub active_mentorship_count: u32,

    // --- Rivalries ---
    /// Number of active adventurer rivalries.
    pub active_rivalry_count: u32,
    /// Average intensity of active rivalries (0-100).
    pub mean_rivalry_intensity: f32,

    // --- War exhaustion ---
    /// Maximum war exhaustion level across all factions at war with us.
    pub max_war_exhaustion: f32,

    // --- Chronicle ---
    /// Total chronicle entries written.
    pub chronicle_entry_count: u32,
    /// Number of recent tragedy events in the chronicle.
    pub recent_tragedy_count: u32,

    // --- Deeds ---
    /// Total heroic deeds earned by adventurers.
    pub total_deeds_earned: u32,

    // --- Population ---
    /// Total regional population in guild-controlled territory.
    pub total_population: f32,
    /// Average civilian morale across controlled regions.
    pub mean_population_morale: f32,
    /// Total tax income from controlled populations.
    pub total_tax_income: f32,

    // --- Site preparation ---
    /// Total preparation level across quest sites.
    pub total_site_preparation: f32,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CombatMode {
    /// Predict outcomes via small MLP (microseconds). Used during MCTS.
    Oracle,
    /// Run full deterministic combat sim (milliseconds). Used for evaluation.
    FullSim,
    /// Run tactical sim bridge with generated abilities (~0.1ms).
    TacticalSim,
}

// ---------------------------------------------------------------------------
// Guild
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GuildState {
    pub gold: f32,
    /// Aggregate supply pool at the guild base.
    pub supplies: f32,
    /// 0–100. Affects request quality and pricing.
    pub reputation: f32,
    pub base: BaseState,
    /// How many quests can run simultaneously.
    pub active_quest_capacity: usize,
    /// Bitmask of known unlock categories.
    pub unlock_bitmask: u64,
    /// Inventory of unequipped gear.
    pub inventory: Vec<InventoryItem>,

    // --- Economy system ---
    /// Current spending priority allocation.
    #[serde(default)]
    pub spend_priority: super::actions::SpendPriority,
    /// Dynamic market price multipliers.
    #[serde(default)]
    pub market_prices: MarketPrices,
    /// Accumulated trade income from controlled regions.
    #[serde(default)]
    pub total_trade_income: f32,
    /// Investment levels across spending categories.
    #[serde(default)]
    pub investment: InvestmentState,
    /// Rolling purchase history for market inflation.
    #[serde(default)]
    pub purchase_history: PurchaseHistory,
    /// Current guild reputation tier.
    #[serde(default)]
    pub guild_tier: GuildTier,
    /// Crafting resource stockpile.
    #[serde(default)]
    pub resources: std::collections::HashMap<ResourceType, f32>,
}

/// Dynamic market price multipliers. Prices inflate with demand.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MarketPrices {
    /// Multiplier for supply costs.
    pub supply_multiplier: f32,
    /// Multiplier for recruitment costs.
    pub recruitment_multiplier: f32,
    /// Multiplier for training costs.
    pub training_multiplier: f32,
    /// Multiplier for mercenary costs.
    pub mercenary_multiplier: f32,
}

impl Default for MarketPrices {
    fn default() -> Self {
        Self {
            supply_multiplier: 1.0,
            recruitment_multiplier: 1.0,
            training_multiplier: 1.0,
            mercenary_multiplier: 1.0,
        }
    }
}

/// Investment levels for the four spending categories.
/// Each level provides diminishing returns to its domain.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct InvestmentState {
    pub defense_level: f32,
    pub recruitment_level: f32,
    pub infrastructure_level: f32,
    pub intelligence_level: f32,
}

/// Rolling purchase counts that decay over time, driving market inflation.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct PurchaseHistory {
    pub supply_purchases: f32,
    pub recruitment_purchases: f32,
    pub training_purchases: f32,
    pub mercenary_purchases: f32,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BaseState {
    pub base_type: BaseType,
    /// Overworld coordinates (x, y).
    pub position: (f32, f32),
    pub upgrade_slots: Vec<UpgradeSlot>,
    pub defensive_strength: f32,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BaseType {
    Camp,
    Fixed,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct UpgradeSlot {
    pub slot_type: UpgradeSlotType,
    pub installed: Option<String>,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum UpgradeSlotType {
    Defense,
    Storage,
    Training,
    Information,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct InventoryItem {
    pub id: u32,
    pub name: String,
    pub slot: EquipmentSlot,
    pub quality: f32,
    pub stat_bonuses: StatBonuses,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct StatBonuses {
    pub hp_bonus: f32,
    pub attack_bonus: f32,
    pub defense_bonus: f32,
    pub speed_bonus: f32,
}

// ---------------------------------------------------------------------------
// Adventurer
// ---------------------------------------------------------------------------

/// An adventurer in the guild. Maps from existing `HeroCompanion`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Adventurer {
    pub id: u32,
    pub name: String,
    /// Archetype from hero_templates (e.g. "knight", "ranger", "mage").
    pub archetype: String,
    pub level: u32,
    pub xp: u32,

    // --- Combat stats summary ---
    pub stats: AdventurerStats,
    pub equipment: Equipment,
    pub traits: Vec<String>,

    // --- Condition ---
    pub status: AdventurerStatus,
    /// 0–100.
    pub loyalty: f32,
    /// 0–100.
    pub stress: f32,
    /// 0–100.
    pub fatigue: f32,
    /// 0–100. ≥90 = incapacitated.
    pub injury: f32,
    /// 0–100.
    pub resolve: f32,
    /// 0–100.
    pub morale: f32,

    // --- Assignment ---
    /// Which party this adventurer belongs to, if any.
    pub party_id: Option<u32>,
    /// NPC relationship score to the guild (−100 to 100).
    pub guild_relationship: f32,

    // --- Leadership ---
    /// Leadership role providing passive buffs to the guild/faction.
    /// Unlocked through progression. Buff is active while adventurer is
    /// alive and not on a quest.
    #[serde(default)]
    pub leadership_role: Option<LeadershipRole>,
    /// Whether this is the player character.
    #[serde(default)]
    pub is_player_character: bool,
    /// Which faction this adventurer belongs to (None = guild).
    #[serde(default)]
    pub faction_id: Option<usize>,
    /// If traveling to join a faction (Sleeping King mechanic).
    #[serde(default)]
    pub rallying_to: Option<RallyTarget>,
    /// Unit tier progression status.
    #[serde(default)]
    pub tier_status: super::unit_tiers::UnitTierStatus,

    /// History tags accumulated from gameplay. Used to bias ability generation
    /// so abilities reflect the adventurer's actual journey.
    /// e.g., {"solo": 10, "blight_prevention": 3, "region_defense": 5}
    #[serde(default)]
    pub history_tags: std::collections::HashMap<String, u32>,

    // --- New system fields ---
    /// Generated backstory — birthplace, motivation, flaw, personal quest hook.
    #[serde(default)]
    pub backstory: Option<super::systems::backstory::Backstory>,
    /// Legendary deeds earned through achievements.
    #[serde(default)]
    pub deeds: Vec<LegendaryDeed>,
    /// Hobbies developed during idle downtime.
    #[serde(default)]
    pub hobbies: Vec<HobbyProgress>,
    /// Health status with respect to diseases.
    #[serde(default)]
    pub disease_status: DiseaseStatus,
}

/// A leadership role that provides passive buffs while the adventurer is active.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LeadershipRole {
    pub title: String,
    pub buff: LeadershipBuff,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum LeadershipBuff {
    /// Adds flat military strength to the faction.
    MilitaryStrength(f32),
    /// Multiplier on faction attack power.
    AttackMultiplier(f32),
    /// Reduces control loss from enemy attacks.
    DefenseBonus(f32),
    /// Passive gold income per tick.
    GoldIncome(f32),
    /// Faster adventurer recovery.
    RecoveryRate(f32),
    /// Improved quest reward scaling.
    RewardMultiplier(f32),
    /// Better recruitment chances.
    RecruitBonus(f32),
    /// Improved faction relationship drift.
    DiplomacyBonus(f32),
    /// Reduces adventurer stress accumulation.
    MoraleAura(f32),
}

/// An adventurer traveling to rally to a faction (for crisis mechanics).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RallyTarget {
    /// Faction they're traveling to join.
    pub faction_id: usize,
    /// Position they're heading to.
    pub destination: (f32, f32),
    /// Travel speed (tiles/sec).
    pub speed: f32,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct AdventurerStats {
    pub max_hp: f32,
    pub attack: f32,
    pub defense: f32,
    pub speed: f32,
    pub ability_power: f32,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Equipment {
    pub weapon: Option<u32>,
    pub offhand: Option<u32>,
    pub chest: Option<u32>,
    pub boots: Option<u32>,
    pub accessory: Option<u32>,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AdventurerStatus {
    Idle,
    /// In the candidate pool for a quest, not yet dispatched.
    Assigned,
    /// En route to quest location.
    Traveling,
    /// At quest location, executing.
    OnMission,
    /// In active battle.
    Fighting,
    /// Recovering from injury, unavailable.
    Injured,
    Dead,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EquipmentSlot {
    Weapon,
    Offhand,
    Chest,
    Boots,
    Accessory,
}

// ---------------------------------------------------------------------------
// Party
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Party {
    pub id: u32,
    /// Adventurer IDs in this party.
    pub member_ids: Vec<u32>,
    /// Continuous overworld position (x, y).
    pub position: (f32, f32),
    /// Where the party is heading. `None` = stationary.
    pub destination: Option<(f32, f32)>,
    /// Tiles per second.
    pub speed: f32,
    pub status: PartyStatus,
    /// 0–100.
    pub supply_level: f32,
    /// Aggregate party morale (mean of members).
    pub morale: f32,
    /// Which quest this party is assigned to.
    pub quest_id: Option<u32>,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PartyStatus {
    Idle,
    Traveling,
    OnMission,
    Fighting,
    /// Heading back to guild base.
    Returning,
}

// ---------------------------------------------------------------------------
// Quests
// ---------------------------------------------------------------------------

/// A request on the guild board (not yet accepted).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct QuestRequest {
    pub id: u32,
    pub source_faction_id: Option<usize>,
    pub source_area_id: Option<usize>,
    pub quest_type: QuestType,
    /// Estimated difficulty (0–100).
    pub threat_level: f32,
    pub reward: QuestReward,
    /// Distance from guild base in tiles.
    pub distance: f32,
    /// Location where the quest takes place.
    pub target_position: (f32, f32),
    /// Expires at this elapsed_ms if not accepted.
    pub deadline_ms: u64,
    pub description: String,
    /// When it appeared on the board.
    pub arrived_at_ms: u64,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum QuestType {
    Combat,
    Exploration,
    Diplomatic,
    Escort,
    Rescue,
    Gather,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct QuestReward {
    pub gold: f32,
    pub reputation: f32,
    pub relation_faction_id: Option<usize>,
    pub relation_change: f32,
    pub supply_reward: f32,
    /// Whether this quest has a chance of dropping equipment.
    pub potential_loot: bool,
}

/// An accepted, in-progress quest.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ActiveQuest {
    pub id: u32,
    /// Original request data (preserved for reward application).
    pub request: QuestRequest,
    pub status: ActiveQuestStatus,
    /// Adventurer IDs the player assigned to the candidate pool.
    pub assigned_pool: Vec<u32>,
    /// Party formed by the NPC system after dispatch.
    pub dispatched_party_id: Option<u32>,
    /// Milliseconds since the quest was accepted.
    pub elapsed_ms: u64,
    /// Events that happened during the quest.
    pub events: Vec<QuestEvent>,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ActiveQuestStatus {
    /// Pool assigned, not yet dispatched.
    Preparing,
    /// Party formed, traveling to quest location.
    Dispatched,
    /// At location, executing quest objectives.
    InProgress,
    /// Battle triggered.
    InCombat,
    /// Completed, party heading back.
    Returning,
    /// Going sideways — support actions available.
    NeedsSupport,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct QuestEvent {
    pub tick: u64,
    pub description: String,
}

/// A quest that has been completed (history record).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CompletedQuest {
    pub id: u32,
    pub quest_type: QuestType,
    pub result: QuestResult,
    pub reward_applied: QuestReward,
    pub completed_at_ms: u64,
    pub party_id: u32,
    pub casualties: u32,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum QuestResult {
    Victory,
    Defeat,
    Abandoned,
}

// ---------------------------------------------------------------------------
// Battles
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BattleState {
    pub id: u32,
    /// Which quest triggered this battle.
    pub quest_id: u32,
    /// Our party.
    pub party_id: u32,
    pub location: (f32, f32),

    // --- Summarized combat state ---
    /// Aggregate HP remaining for our party (0–1).
    pub party_health_ratio: f32,
    /// Aggregate HP remaining for enemies (0–1).
    pub enemy_health_ratio: f32,
    /// Enemy composition strength estimate.
    pub enemy_strength: f32,
    pub elapsed_ticks: u64,
    /// Combat oracle prediction (−1 = certain defeat, +1 = certain victory).
    pub predicted_outcome: f32,
    pub status: BattleStatus,

    // --- Support state ---
    pub runner_sent: bool,
    pub mercenary_hired: bool,
    pub rescue_called: bool,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BattleStatus {
    Active,
    Victory,
    Defeat,
    Retreat,
}

// ---------------------------------------------------------------------------
// Seasons
// ---------------------------------------------------------------------------

/// The four seasons of the campaign world, cycling every 5000 ticks.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Season {
    Spring,
    Summer,
    Autumn,
    Winter,
}

impl Default for Season {
    fn default() -> Self {
        Season::Spring
    }
}

impl Season {
    /// Return the next season in the cycle.
    pub fn next(self) -> Season {
        match self {
            Season::Spring => Season::Summer,
            Season::Summer => Season::Autumn,
            Season::Autumn => Season::Winter,
            Season::Winter => Season::Spring,
        }
    }
}

// ---------------------------------------------------------------------------
// Overworld
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OverworldState {
    pub regions: Vec<Region>,
    /// Named locations: settlements, dungeons, ruins, outposts.
    pub locations: Vec<Location>,
    /// Global threat level (0–100).
    pub global_threat_level: f32,
    /// Overall campaign progress toward endgame (0–1).
    pub campaign_progress: f32,
    /// Endgame calamity, if one has been selected.
    pub endgame_calamity: Option<CalamityType>,
    /// Active endgame crises. Multiple can run simultaneously.
    #[serde(default)]
    pub active_crises: Vec<ActiveCrisis>,
    /// Current season of the world.
    #[serde(default)]
    pub season: Season,
    /// Tick counter within the current season (resets each transition).
    #[serde(default)]
    pub season_tick: u64,
    /// Active weather hazards.
    #[serde(default)]
    pub active_weather: Vec<WeatherEvent>,
    /// Next weather event ID.
    #[serde(default)]
    pub next_weather_id: u32,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Region {
    pub id: usize,
    pub name: String,
    pub owner_faction_id: usize,
    pub neighbors: Vec<usize>,
    /// 0–100.
    pub unrest: f32,
    /// 0–100.
    pub control: f32,
    /// Regional threat level (0–100).
    pub threat_level: f32,
    /// Fog-of-war visibility (0.0 = unknown, 1.0 = fully scouted).
    /// Decays over time as information goes stale.
    #[serde(default = "default_region_visibility")]
    pub visibility: f32,
    /// Civilian population (100-1000 typical range).
    #[serde(default = "default_population")]
    pub population: u32,
    /// Civilian morale (0-100). Affects growth, unrest, events.
    #[serde(default = "default_civilian_morale")]
    pub civilian_morale: f32,
    /// Tax rate (0.0-1.0). Controls income vs morale trade-off.
    #[serde(default = "default_tax_rate")]
    pub tax_rate: f32,
    /// Population growth rate modifier.
    #[serde(default)]
    pub growth_rate: f32,
}

fn default_region_visibility() -> f32 {
    0.3
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Location {
    pub id: usize,
    pub name: String,
    pub position: (f32, f32),
    pub location_type: LocationType,
    /// 0–100.
    pub threat_level: f32,
    /// 0–100.
    pub resource_availability: f32,
    pub faction_owner: Option<usize>,
    /// Whether the guild has scouted this location.
    pub scouted: bool,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationType {
    Settlement,
    Wilderness,
    Dungeon,
    Ruin,
    Outpost,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum CalamityType {
    /// An aggressive faction with a super-ruler unit.
    AggressiveFaction { faction_id: usize },
    /// A major monster threatening the world.
    MajorMonster { name: String, strength: f32 },
    /// A flood of minor crises overwhelming the region.
    CrisisFlood,
    /// A conquest victory condition.
    Conquest,
}

/// Active endgame crisis with tracking state.
///
/// All escalation parameters come from TOML templates in `assets/crises/`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum ActiveCrisis {
    /// The Sleeping King: champions rally to a distant ruler.
    SleepingKing {
        /// The faction ID of the King's growing empire.
        king_faction_id: usize,
        /// Adventurer IDs of the champions (scattered across map).
        champion_ids: Vec<u32>,
        /// How many champions have arrived.
        champions_arrived: u32,
        /// Tick when next champion activates.
        next_activation_tick: u64,
        /// Ticks between champion activations.
        activation_interval: u64,
        /// Power growth formula from template.
        #[serde(default = "default_quadratic")]
        power_formula: String,
        /// Champions needed before declaring war (from template).
        #[serde(default = "default_war_threshold")]
        war_threshold: u32,
    },
    /// The Breach: dungeon monsters pour out in waves.
    Breach {
        source_location_id: usize,
        wave_number: u32,
        wave_strength: f32,
        next_wave_tick: u64,
        /// Strength multiplier per wave (from template).
        #[serde(default = "default_strength_multiplier")]
        strength_multiplier: f32,
        /// Ticks subtracted from interval each wave (from template).
        #[serde(default = "default_wave_acceleration")]
        wave_acceleration: u64,
        /// Minimum ticks between waves (from template).
        #[serde(default = "default_min_wave_interval")]
        min_wave_interval: u64,
        /// Initial wave interval for computing next wave tick (from template).
        #[serde(default = "default_initial_wave_interval")]
        initial_wave_interval: u64,
    },
    /// The Corruption: spreading contamination.
    Corruption {
        origin_region_id: usize,
        corrupted_regions: Vec<usize>,
        spread_rate_ticks: u64,
        next_spread_tick: u64,
        /// Control damage per tick to corrupted regions (from template).
        #[serde(default = "default_control_damage")]
        control_damage_per_tick: f32,
        /// Unrest damage per tick to corrupted regions (from template).
        #[serde(default = "default_unrest_damage")]
        unrest_damage_per_tick: f32,
    },
    /// The Unifier: political crisis, a charismatic leader unites factions.
    Unifier {
        unifier_faction_id: usize,
        absorbed_factions: Vec<usize>,
        /// Ticks between absorption attempts (from template).
        #[serde(default = "default_absorb_interval")]
        absorb_interval_ticks: u64,
        /// Fraction of absorbed faction's strength gained (from template).
        #[serde(default = "default_absorption_rate")]
        strength_absorption_rate: f32,
    },
    /// The Decline: slow resource drain, everything gets worse.
    Decline {
        severity: f32,
        tick_started: u64,
        /// Gold drained per application (from template).
        #[serde(default = "default_gold_drain")]
        gold_drain_per_tick: f32,
        /// Supplies drained per application (from template).
        #[serde(default = "default_supply_drain")]
        supply_drain_per_tick: f32,
        /// Morale drained per adventurer per application (from template).
        #[serde(default = "default_morale_drain")]
        morale_drain_per_tick: f32,
        /// Control drained per region per application (from template).
        #[serde(default = "default_control_drain")]
        control_drain_per_tick: f32,
        /// Severity growth rate (from template).
        #[serde(default = "default_severity_growth_rate")]
        severity_growth_rate: f32,
    },
}

// Serde defaults for backward compatibility with saved states.
fn default_quadratic() -> String { "quadratic".into() }
fn default_war_threshold() -> u32 { 5 }
fn default_strength_multiplier() -> f32 { 1.3 }
fn default_wave_acceleration() -> u64 { 200 }
fn default_min_wave_interval() -> u64 { 500 }
fn default_initial_wave_interval() -> u64 { 3000 }
fn default_control_damage() -> f32 { 0.3 }
fn default_unrest_damage() -> f32 { 0.5 }
fn default_absorb_interval() -> u64 { 5000 }
fn default_absorption_rate() -> f32 { 0.7 }
fn default_gold_drain() -> f32 { 0.5 }
fn default_supply_drain() -> f32 { 0.3 }
fn default_morale_drain() -> f32 { 0.1 }
fn default_control_drain() -> f32 { 0.1 }
fn default_severity_growth_rate() -> f32 { 10000.0 }

// ---------------------------------------------------------------------------
// Factions & Diplomacy
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FactionState {
    pub id: usize,
    pub name: String,
    /// Relationship to the guild (−100 to 100).
    pub relationship_to_guild: f32,
    pub military_strength: f32,
    /// Strength cap — factions rebuild toward this over time.
    #[serde(default = "default_max_strength")]
    pub max_military_strength: f32,
    pub territory_size: usize,
    pub diplomatic_stance: DiplomaticStance,
    /// Whether this faction is in a coalition with the guild.
    #[serde(default)]
    pub coalition_member: bool,
    /// Faction-to-faction war targets (faction IDs this faction is at war with).
    #[serde(default)]
    pub at_war_with: Vec<usize>,
    /// Whether this faction has an adventurer guild (NPC guild for coalition).
    #[serde(default)]
    pub has_guild: bool,
    /// NPC guild adventurer count (if has_guild).
    #[serde(default)]
    pub guild_adventurer_count: u32,
    /// Recent actions taken by this faction (bounded).
    pub recent_actions: Vec<FactionActionRecord>,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DiplomaticStance {
    /// Positive relations, willing to trade and cooperate.
    Friendly,
    /// Default stance, no strong feelings.
    Neutral,
    /// Negative relations, building military, may declare war.
    Hostile,
    /// Actively attacking the guild's territory.
    AtWar,
    /// Allied — shares intel, provides military aid, joint operations.
    Coalition,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FactionActionRecord {
    pub tick: u64,
    pub action: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DiplomacyMatrix {
    /// Faction-to-faction relations. `relations[a][b]` = how faction a feels
    /// about faction b (signed).
    pub relations: Vec<Vec<i32>>,
    /// Which faction the guild is affiliated with.
    pub guild_faction_id: usize,
    /// Active diplomatic agreements between faction pairs.
    #[serde(default)]
    pub agreements: Vec<(usize, usize, DiplomaticAgreement)>,
}

// ---------------------------------------------------------------------------
// Progression Unlocks
// ---------------------------------------------------------------------------

/// NOT identity-indexed. Described by mechanical properties so the model
/// can handle LFM-generated novel abilities.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct UnlockInstance {
    pub id: u32,
    pub category: UnlockCategory,
    pub properties: UnlockProperties,
    pub name: String,
    pub description: String,
    /// Whether this unlock is available for use.
    pub active: bool,
    /// Remaining cooldown in milliseconds (0 = ready).
    pub cooldown_remaining_ms: u64,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum UnlockCategory {
    /// Scout networks, alarms — reduces uncertainty.
    Information,
    /// Send potion, call favor — direct intervention.
    ActiveAbility,
    /// Improved coordination, last stands.
    PassiveBuff,
    /// Better supply chains, cheaper hiring.
    Economic,
}

/// Mechanical properties — this is what the model sees, not the name.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct UnlockProperties {
    /// 0 = passive (always on).
    pub cooldown_ms: u64,
    pub target_type: TargetType,
    /// Effect strength (interpretation depends on category).
    pub magnitude: f32,
    /// 0 = instant or permanent.
    pub duration_ms: u64,
    /// Gold cost to use.
    pub resource_cost: f32,
    pub is_passive: bool,
    /// Learned category features for the entity encoder.
    pub category_embedding: [f32; 8],
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TargetType {
    GuildSelf,
    Adventurer,
    Party,
    Quest,
    Area,
    Faction,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProgressionEvent {
    pub tick: u64,
    pub unlock_id: u32,
    pub description: String,
}

// ---------------------------------------------------------------------------
// NPC Relationships
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NpcRelationship {
    pub npc_id: u32,
    pub npc_name: String,
    pub npc_type: NpcType,
    /// −100 to 100.
    pub relationship_score: f32,
    /// Last interaction timestamp (elapsed_ms).
    pub last_interaction_ms: u64,
    /// Whether this NPC can rescue for free (relationship-gated).
    pub rescue_available: bool,
    /// Gold cost if rescue is not free.
    pub rescue_cost: f32,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NpcType {
    Adventurer,
    FactionLeader,
    Merchant,
    Informant,
    Mercenary,
}

// ---------------------------------------------------------------------------
// Narrative events
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CampaignEvent {
    pub id: u32,
    pub tick: u64,
    pub description: String,
}

// ---------------------------------------------------------------------------
// Campaign outcome
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CampaignOutcome {
    /// Player defeated the endgame calamity.
    Victory,
    /// Guild collapsed (no adventurers, no gold, or calamity won).
    Defeat,
    /// Hit the maximum tick limit.
    Timeout,
}

// ---------------------------------------------------------------------------
// Progression queue
// ---------------------------------------------------------------------------

/// Content generated by the LLM and cached for presentation at rest.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PendingProgression {
    /// What adventurer this applies to (if any).
    pub adventurer_id: Option<u32>,
    /// What type of progression.
    pub kind: ProgressionKind,
    /// The generated content (DSL text for class/ability, TOML for quest hook).
    pub content: String,
    /// Human-readable description for the rest event UI.
    pub description: String,
    /// Tick when this was generated.
    pub generated_at_tick: u64,
    /// The trigger that caused this generation.
    pub trigger: String,
}

/// What kind of progression content was generated.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProgressionKind {
    /// A new ability for an adventurer (ability DSL).
    Ability,
    /// A new class offer for an adventurer (class DSL).
    ClassOffer,
    /// A quest hook that fired from game events.
    QuestHook,
    /// A stat boost from level-up (applied automatically).
    LevelUp,
    /// A hero class candidacy opportunity.
    HeroCandidacy,
    /// Equipment or item reward.
    ItemReward,
}

// ---------------------------------------------------------------------------
// Campaign phase
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CampaignPhase {
    /// Character creation — backstory events playing out.
    /// Systems don't tick. Only creation choices are valid.
    CharacterCreation,
    /// Starting package selection (final creation step).
    ChoosingStartingPackage,
    /// Normal gameplay.
    Playing,
}

impl Default for CampaignPhase {
    fn default() -> Self {
        Self::CharacterCreation
    }
}

// ---------------------------------------------------------------------------
// Player character
// ---------------------------------------------------------------------------

/// The player's named character — an adventurer with a special flag.
/// Built incrementally during character creation from backstory choices.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PlayerCharacter {
    /// The adventurer ID in the adventurers list.
    pub adventurer_id: u32,
    /// Player-chosen name.
    pub name: String,
    /// Origin backstory (e.g. "Noble Exile", "Frontier Settler").
    pub origin: String,
    /// Accumulated backstory summary from creation choices.
    pub backstory: Vec<String>,
    /// Personal goal — tracked but doesn't end the game.
    pub goal: Option<PersonalGoal>,
    /// Whether the PC is alive (if dead, leadership transfers).
    pub alive: bool,
    /// Successor adventurer ID (appointed second-in-command).
    pub successor_id: Option<u32>,
}

/// A personal goal chosen during character creation.
/// Cosmetic to the world — just tracks progress toward a player ambition.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PersonalGoal {
    pub name: String,
    pub description: String,
    /// Conditions to check against CampaignState.
    pub conditions: Vec<GoalCondition>,
    /// Has this goal been achieved? (doesn't end the game)
    pub achieved: bool,
    /// Can this goal become impossible?
    pub fail_condition: Option<String>,
    pub failed: bool,
}

/// A condition for goal completion, checked against game state.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum GoalCondition {
    /// Faction relationship above threshold.
    FactionRelation { faction_id: usize, min_relation: f32 },
    /// Guild reputation above threshold.
    Reputation { min_reputation: f32 },
    /// Gold above threshold.
    Gold { min_gold: f32 },
    /// Region control above threshold.
    RegionControl { region_id: usize, min_control: f32 },
    /// Quest victory count above threshold.
    QuestsCompleted { min_count: usize },
    /// Adventurer count above threshold.
    AdventurerCount { min_count: usize },
    /// PC level above threshold.
    PlayerLevel { min_level: u32 },
    /// All factions at Friendly or Coalition.
    AllFactionsAllied,
    /// Specific trait acquired by PC.
    HasTrait { trait_name: String },
}

// ---------------------------------------------------------------------------
// Choice events
// ---------------------------------------------------------------------------

/// A branching decision presented to the player.
///
/// Generated by quest outcomes, NPC encounters, progression milestones,
/// faction diplomacy, and random events. If the deadline passes without
/// the player choosing, `default_option` is auto-selected (the path of
/// least investment/commitment).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChoiceEvent {
    pub id: u32,
    /// What category generated this choice.
    pub source: ChoiceSource,
    /// Display text describing the situation.
    pub prompt: String,
    /// Available options (2–4).
    pub options: Vec<ChoiceOption>,
    /// Index into `options` that is auto-selected on deadline expiry.
    /// Should be the lowest-investment/safest/most passive option.
    pub default_option: usize,
    /// Deadline in elapsed_ms. `None` = no deadline (blocks until chosen).
    pub deadline_ms: Option<u64>,
    /// When this choice was created.
    pub created_at_ms: u64,
}

/// What system generated this choice.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum ChoiceSource {
    /// Quest reached a branching point.
    QuestBranch { quest_id: u32 },
    /// Progression milestone — pick one of N unlocks.
    ProgressionUnlock,
    /// NPC encounter (merchant deal, faction proposal, etc).
    NpcEncounter { npc_id: u32 },
    /// Flashpoint approach selection.
    FlashpointIntent { region_id: usize },
    /// Random world event.
    WorldEvent,
    /// Faction demand (ransom or ultimatum).
    FactionDemand,
    /// Rivalry duel challenge.
    RivalryDuel { challenger: u32, challenged: u32 },
}

/// A single option in a choice event.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChoiceOption {
    /// Short label (e.g. "Stealth Approach", "Invest in Scout Network").
    pub label: String,
    /// Description of what happens if chosen.
    pub description: String,
    /// Effects applied when this option is selected.
    pub effects: Vec<ChoiceEffect>,
}

/// A concrete effect applied when a choice option is selected.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum ChoiceEffect {
    /// Add/remove gold.
    Gold(f32),
    /// Add/remove supplies.
    Supplies(f32),
    /// Change reputation.
    Reputation(f32),
    /// Change faction relationship.
    FactionRelation { faction_id: usize, delta: f32 },
    /// Grant an unlock.
    GrantUnlock(UnlockInstance),
    /// Modify quest threat level.
    ModifyQuestThreat { quest_id: u32, multiplier: f32 },
    /// Modify quest reward.
    ModifyQuestReward { quest_id: u32, gold_bonus: f32, rep_bonus: f32 },
    /// Add an adventurer to the guild.
    AddAdventurer(Adventurer),
    /// Heal/injure an adventurer.
    ModifyAdventurerInjury { adventurer_id: u32, delta: f32 },
    /// Change adventurer loyalty.
    ModifyAdventurerLoyalty { adventurer_id: u32, delta: f32 },
    /// Add item to inventory.
    AddItem(InventoryItem),
    /// Set a quest to a specific status.
    SetQuestStatus { quest_id: u32, status: ActiveQuestStatus },
    /// Narrative flavor — no mechanical effect.
    Narrative(String),
    /// Attend a festival for morale/relationship bonuses.
    AttendFestival(u32),
}

// ---------------------------------------------------------------------------
// Starting choice
// ---------------------------------------------------------------------------

/// A starting package the player can choose at tick 0.
///
/// Loaded from data files (TOML/JSON). Each package defines its own
/// adventurers, gold bonus, supply bonus, and flavor text.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StartingChoice {
    /// Display name (e.g. "War Chest", "The Veteran", "Fresh Recruits").
    pub name: String,
    /// Description shown to the player.
    pub description: String,
    /// Adventurers granted by this package.
    pub adventurers: Vec<Adventurer>,
    /// Gold added to the guild's starting gold.
    pub gold_bonus: f32,
    /// Supplies added to the guild's starting supplies.
    pub supply_bonus: f32,
    /// Starting reputation modifier.
    pub reputation_bonus: f32,
    /// Optional starting inventory items.
    pub items: Vec<InventoryItem>,
}

impl StartingChoice {
    /// Load all starting packages from a directory of TOML files.
    pub fn load_from_dir(dir: &std::path::Path) -> Result<Vec<Self>, String> {
        let mut choices = Vec::new();
        let entries = std::fs::read_dir(dir)
            .map_err(|e| format!("Failed to read {}: {}", dir.display(), e))?;
        for entry in entries {
            let entry = entry.map_err(|e| format!("Read error: {}", e))?;
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("toml") {
                let content = std::fs::read_to_string(&path)
                    .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;
                let choice: StartingChoice = toml::from_str(&content)
                    .map_err(|e| format!("Failed to parse {}: {}", path.display(), e))?;
                choices.push(choice);
            }
        }
        Ok(choices)
    }
}

// ---------------------------------------------------------------------------
// Rival guild
// ---------------------------------------------------------------------------

/// State for an AI-controlled competing guild.
///
/// Creates urgency and strategic tension by competing for quests,
/// faction favor, and recruits.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RivalGuildState {
    /// Display name (e.g. "The Iron Company").
    pub name: String,
    /// Rival's gold reserves (abstract).
    pub gold: f32,
    /// 0–100, competes with player reputation.
    pub reputation: f32,
    /// Abstract adventurer headcount (not individual units).
    pub adventurer_count: u32,
    /// Aggregate combat power.
    pub power_level: f32,
    /// Total quests the rival has completed.
    pub quests_completed: u32,
    /// Faction relations, parallel to `CampaignState::factions`.
    pub faction_relations: Vec<f32>,
    /// Whether the rival is active. False until tick 2000 (grace period).
    pub active: bool,
    /// Behavioral personality affecting quest/faction priorities.
    pub personality: RivalPersonality,
}

/// Personality archetype for the rival guild AI.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum RivalPersonality {
    /// Prioritizes combat quests, builds military power, may sabotage.
    #[default]
    Aggressive,
    /// Prioritizes faction relations, avoids direct conflict.
    Diplomatic,
    /// Analyzes what the player neglects and focuses on those areas.
    Opportunistic,
}

// ---------------------------------------------------------------------------
// New system types
// ---------------------------------------------------------------------------

/// A formal diplomatic agreement between two factions.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum DiplomaticAgreement {
    TradeAgreement { gold_per_tick: f32, expires_tick: u64 },
    NonAggressionPact { expires_tick: u64 },
    MilitaryAlliance { expires_tick: u64 },
}

/// A trade route between two guild-controlled settlements.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TradeRoute {
    pub id: u32,
    pub start_location_id: usize,
    pub end_location_id: usize,
    pub gold_per_trip: f32,
    pub active: bool,
}

/// A caravan traveling along a trade route.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Caravan {
    pub id: u32,
    pub route_id: u32,
    pub position: (f32, f32),
    pub progress: f32,
    pub gold_carried: f32,
    pub guard_strength: f32,
    pub forward: bool,
}

/// A retired adventurer who provides lasting legacy bonuses.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RetiredAdventurer {
    pub id: u32,
    pub name: String,
    pub archetype: String,
    pub level: u32,
    pub legacy_type: LegacyType,
    pub bonus_value: f32,
    pub retired_at_tick: u64,
}

/// The type of lasting bonus a retired adventurer provides.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum LegacyType {
    TrainingMentor,
    Quartermaster,
    Diplomat,
    Strategist,
    Recruiter,
    Lorekeeper,
}

/// An active mentor-apprentice training relationship.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MentorAssignment {
    pub mentor_id: u32,
    pub apprentice_id: u32,
    pub started_tick: u64,
    pub xp_transferred: f32,
    pub skill_focus: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CivilWarState {
    pub faction_id: usize,
    pub rebel_strength: f32,
    pub loyalist_strength: f32,
    pub started_tick: u64,
    pub rebel_leader_name: String,
    pub cause: CivilWarCause,
    #[serde(default)]
    pub guild_supported_side: Option<bool>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CivilWarCause {
    SuccessionCrisis,
    Corruption,
    MilitaryDefeat,
    ForeignInfluence,
    ReligiousSplit,
}

/// A legendary deed earned by an adventurer.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LegendaryDeed {
    pub title: String,
    pub earned_at_tick: u64,
    pub deed_type: DeedType,
    pub bonus: DeedBonus,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DeedType {
    Slayer,
    Peacemaker,
    Explorer,
    Survivor,
    Wealthy,
    Defender,
    Undefeated,
    Savior,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum DeedBonus {
    FactionRelationBoost(f32),
    CombatPowerBoost(f32),
    QuestRewardBoost(f32),
    RecruitmentBoost(f32),
    MoraleAura(f32),
}

/// An intelligence fragment.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Rumor {
    pub id: u32,
    pub text: String,
    pub rumor_type: RumorType,
    pub accuracy: f32,
    pub source_tick: u64,
    pub revealed: bool,
    pub target_region_id: Option<usize>,
    pub target_faction_id: Option<usize>,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RumorType {
    HiddenQuest,
    CrisisWarning,
    FactionPlan,
    TreasureLocation,
    AmbushThreat,
    TradeOpportunity,
}

impl Default for RumorType {
    fn default() -> Self { RumorType::HiddenQuest }
}

/// War exhaustion for a single faction.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct WarExhaustion {
    pub faction_id: usize,
    pub exhaustion_level: f32,
    pub war_start_tick: u64,
    pub casualties: u32,
    pub gold_spent: f32,
}

/// Guild reputation tier.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum GuildTier {
    #[default]
    Bronze,
    Silver,
    Gold,
    Legendary,
}

impl GuildTier {
    pub fn from_reputation(rep: f32) -> GuildTier {
        if rep >= 75.0 { GuildTier::Legendary }
        else if rep >= 50.0 { GuildTier::Gold }
        else if rep >= 25.0 { GuildTier::Silver }
        else { GuildTier::Bronze }
    }
    pub fn name(&self) -> &'static str {
        match self {
            GuildTier::Bronze => "Bronze",
            GuildTier::Silver => "Silver",
            GuildTier::Gold => "Gold",
            GuildTier::Legendary => "Legendary",
        }
    }
}

/// A spy planted in a faction.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Spy {
    pub id: u32,
    pub adventurer_id: u32,
    pub target_faction_id: usize,
    pub cover: f32,
    pub intel_gathered: f32,
    pub planted_tick: u64,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SabotageType {
    WeakenDefenses,
    StealGold,
    SowDiscord,
}

/// A mercenary company.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MercenaryCompany {
    pub id: u32,
    pub name: String,
    pub strength: f32,
    pub cost_per_tick: f32,
    pub loyalty: f32,
    pub specialty: MercenarySpecialty,
    pub hired_tick: u64,
    pub contract_duration: u64,
    pub assigned_party_id: Option<u32>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum MercenarySpecialty {
    HeavyInfantry,
    Scouts,
    Archers,
    Siege,
    Cavalry,
    Assassins,
}

/// Black market state.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BlackMarketState {
    pub available_deals: Vec<BlackMarketDeal>,
    pub heat: f32,
    pub total_profit: f32,
    pub last_refresh_tick: u64,
}

impl Default for BlackMarketState {
    fn default() -> Self {
        Self {
            available_deals: Vec::new(),
            heat: 0.0,
            total_profit: 0.0,
            last_refresh_tick: 0,
        }
    }
}

/// A single black market deal.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BlackMarketDeal {
    pub id: u32,
    pub description: String,
    pub deal_type: DealType,
    pub gold_reward: f32,
    pub reputation_risk: f32,
    pub supply_cost: f32,
    pub heat_cost: f32,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DealType {
    StolenGoods,
    SmuggledSupplies,
    ForgedDocuments,
    PoisonContracts,
    InformationBrokering,
    RelicFencing,
}

/// Types of harvestable resources.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ResourceType {
    Iron,
    Wood,
    Crystal,
    Herbs,
    Hide,
    Obsidian,
}

/// A harvestable resource node in a region.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ResourceNode {
    pub id: u32,
    pub region_id: usize,
    pub resource_type: ResourceType,
    pub amount: f32,
    pub regen_rate: f32,
    pub max_amount: f32,
}

/// A recipe for crafting equipment.
#[derive(Clone, Debug)]
pub struct CraftingRecipe {
    pub name: &'static str,
    pub materials: &'static [(ResourceType, f32)],
    pub output_slot: EquipmentSlot,
    pub output_quality: f32,
    pub stat_bonus: f32,
}

/// A migration wave moving between regions.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MigrationWave {
    pub id: u32,
    pub origin_region_id: usize,
    pub destination_region_id: usize,
    pub population_count: u32,
    pub cause: MigrationCause,
    pub started_tick: u64,
    pub progress: f32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum MigrationCause {
    War,
    Famine,
    Crisis,
    Persecution,
    Opportunity,
}

/// A faction-hosted seasonal festival.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Festival {
    pub id: u32,
    pub name: String,
    pub faction_id: usize,
    pub festival_type: FestivalType,
    pub started_tick: u64,
    pub duration: u64,
    pub attended: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum FestivalType {
    HarvestFeast,
    WarMemorial,
    TradeFair,
    ReligiousCeremony,
    ArtisanExpo,
    MartialTournament,
}

/// An active rivalry between two adventurers.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Rivalry {
    pub adventurer_a: u32,
    pub adventurer_b: u32,
    pub intensity: f32,
    pub cause: RivalryCause,
    pub started_tick: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum RivalryCause {
    QuestCompetition,
    PersonalInsult,
    LoyaltyConflict,
    RomanticRivalry,
    ProfessionalJealousy,
}

/// A narrative chronicle entry.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChronicleEntry {
    pub tick: u64,
    pub entry_type: ChronicleType,
    pub text: String,
    pub participants: Vec<u32>,
    pub location_id: Option<usize>,
    pub faction_id: Option<usize>,
    pub significance: f32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ChronicleType {
    BattleRecord,
    QuestCompletion,
    HeroicDeed,
    Tragedy,
    DiplomaticEvent,
    CrisisEvent,
    Discovery,
    Construction,
    Death,
    Betrayal,
}

/// A recurring faction champion that grows stronger.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Nemesis {
    pub id: u32,
    pub name: String,
    pub faction_id: usize,
    pub strength: f32,
    pub kills: u32,
    pub created_tick: u64,
    pub region_id: Option<usize>,
    pub defeated: bool,
}

/// Accumulated favor balance with a faction.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct FactionFavor {
    pub faction_id: usize,
    pub favor_balance: f32,
    pub favors_given: u32,
    pub favors_called: u32,
    #[serde(default)]
    pub trade_deal_expires_tick: u64,
}

/// A favor request from a faction.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FavorRequest {
    pub id: u32,
    pub faction_id: usize,
    pub description: String,
    pub reward_favor: f32,
    pub quest_type: String,
    pub expires_tick: u64,
}

/// A site preparation at a region.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SitePreparation {
    pub id: u32,
    pub region_id: usize,
    pub prep_type: PrepType,
    pub level: f32,
    pub assigned_party_id: Option<u32>,
    pub gold_invested: f32,
    pub created_tick: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PrepType {
    Defensive,
    Offensive,
    Logistical,
}

/// A council vote on a major guild decision.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CouncilVote {
    pub id: u32,
    pub topic: VoteTopic,
    pub proposed_tick: u64,
    pub deadline_tick: u64,
    pub votes_for: Vec<u32>,
    pub votes_against: Vec<u32>,
    pub resolved: bool,
    pub passed: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum VoteTopic {
    DeclareWar { faction_id: usize },
    SuePeace { faction_id: usize },
    ExileAdventurer { adventurer_id: u32 },
    ChangePolicy { policy: String },
    MajorExpedition { region_id: usize },
    AllianceProposal { faction_id: usize },
}

/// An active disease spreading through the world.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Disease {
    pub id: u32,
    pub name: String,
    pub severity: f32,
    pub spread_rate: f32,
    pub affected_regions: Vec<usize>,
    pub started_tick: u64,
    pub containment: f32,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum DiseaseStatus {
    Healthy,
    Infected { disease_id: u32, severity: f32 },
    Recovering,
}

impl Default for DiseaseStatus {
    fn default() -> Self { DiseaseStatus::Healthy }
}

/// An enemy prisoner held by the guild.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Prisoner {
    pub id: u32,
    pub name: String,
    pub faction_id: usize,
    pub strength: f32,
    pub captured_tick: u64,
    pub ransom_value: f32,
    pub escape_chance: f32,
    pub loyalty_shift: f32,
}

/// A propaganda campaign run by the guild.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PropagandaCampaign {
    pub id: u32,
    pub campaign_type: PropagandaType,
    pub target_region_id: Option<usize>,
    pub target_faction_id: Option<usize>,
    pub effectiveness: f32,
    pub gold_spent: f32,
    pub started_tick: u64,
    pub duration: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PropagandaType {
    BoostReputation,
    CounterRival,
    DiscreditFaction,
    RecruitmentDrive,
    WarPropaganda,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MonsterSpecies {
    Wolves,
    Bandits,
    Undead,
    Goblins,
    Trolls,
    Drakes,
    Aberrations,
}

/// A monster population in a region.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MonsterPopulation {
    pub region_id: usize,
    pub species: MonsterSpecies,
    pub population: f32,
    pub aggression: f32,
    pub last_hunted_tick: u64,
}

/// A prophetic vision received by an adventurer.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Vision {
    pub id: u32,
    pub adventurer_id: u32,
    pub vision_type: VisionType,
    pub text: String,
    pub accuracy: f32,
    pub tick: u64,
    pub fulfilled: bool,
    #[serde(default)]
    pub faded: bool,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum VisionType {
    CrisisWarning,
    BetrayalForecast,
    TreasureReveal,
    DeathOmen,
    VictoryGlimpse,
    FactionDoom,
}

/// A hobby adventurers develop during idle downtime.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Hobby {
    Cooking,
    Cartography,
    Gambling,
    Herbalism,
    Smithing,
    Storytelling,
    Training,
    Meditation,
}

/// Tracks hobby progress for an adventurer.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct HobbyProgress {
    pub hobby: Hobby,
    pub skill_level: f32,
    pub started_tick: u64,
}

/// A loan the guild has taken from a faction.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Loan {
    pub id: u32,
    pub lender_faction_id: usize,
    pub principal: f32,
    pub interest_rate: f32,
    pub amount_owed: f32,
    pub taken_tick: u64,
    pub due_tick: u64,
    pub payments_made: u32,
}

/// Victory condition type.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum VictoryCondition {
    SurviveCrisis,
    EconomicDominance,
    DiplomaticUnity,
    MilitaryConquest,
    CulturalHegemony,
    QuestMaster,
}

impl Default for VictoryCondition {
    fn default() -> Self { VictoryCondition::SurviveCrisis }
}

/// Progress toward the active victory condition.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct VictoryProgress {
    pub percent: f32,
    pub total_gold_earned: f32,
    pub quests_completed: u32,
    pub regions_controlled: u32,
    pub max_adventurer_tier: u32,
    pub total_building_tiers: u32,
    pub factions_above_60: u32,
}

/// An underground dungeon beneath a region.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Dungeon {
    pub id: u32,
    pub region_id: usize,
    pub name: String,
    pub depth: u32,
    pub explored: f32,
    pub threat_level: f32,
    pub connected_to: Vec<u32>,
    pub loot_remaining: f32,
    pub monster_strength: f32,
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NpcRole {
    Merchant,
    Noble,
    Informant,
    Healer,
    Blacksmith,
    Scholar,
}

/// A named NPC with individual reputation tracking.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NamedNpc {
    pub id: u32,
    pub name: String,
    pub role: NpcRole,
    pub region_id: usize,
    pub reputation: f32,
    pub services_unlocked: Vec<String>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum WeatherType {
    Storm,
    Blizzard,
    Flood,
    Drought,
    Fog,
    Heatwave,
}

/// An active weather hazard.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WeatherEvent {
    pub id: u32,
    pub weather_type: WeatherType,
    pub affected_regions: Vec<usize>,
    pub severity: f32,
    pub started_tick: u64,
    pub duration: u64,
}

/// A legacy artifact.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Artifact {
    pub id: u32,
    pub name: String,
    pub origin_adventurer_name: String,
    pub origin_deed: String,
    pub slot: String,
    pub stat_bonuses: ArtifactStats,
    pub special_effect: ArtifactEffect,
    pub created_tick: u64,
    pub equipped_by: Option<u32>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ArtifactStats {
    pub attack: f32,
    pub defense: f32,
    pub hp: f32,
    pub speed: f32,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum ArtifactEffect {
    MoraleAura(f32),
    CombatPowerBoost(f32),
    XpMultiplier(f32),
    FactionInfluence(f32),
    ThreatReduction(f32),
    HealingBoost(f32),
    None,
}

impl Default for ArtifactEffect {
    fn default() -> Self { ArtifactEffect::None }
}

/// Dynamic difficulty adjustment state.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DifficultyState {
    pub current_pressure: f32,
    pub target_pressure: f32,
    pub guild_power_rating: f32,
    pub consecutive_wins: u32,
    pub consecutive_losses: u32,
    pub scaling_events_triggered: u32,
}

impl Default for DifficultyState {
    fn default() -> Self {
        Self {
            current_pressure: 50.0,
            target_pressure: 50.0,
            guild_power_rating: 0.0,
            consecutive_wins: 0,
            consecutive_losses: 0,
            scaling_events_triggered: 0,
        }
    }
}

/// Regional culture identity.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RegionalCulture {
    pub region_id: usize,
    pub martial_influence: f32,
    pub trade_influence: f32,
    pub scholarly_influence: f32,
    pub diplomatic_influence: f32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CultureAxis {
    Martial,
    Trade,
    Scholarly,
    Diplomatic,
}

impl LegacyType {
    pub fn base_bonus(&self) -> f32 {
        match self {
            LegacyType::TrainingMentor => 0.10,
            LegacyType::Quartermaster => 0.10,
            LegacyType::Diplomat => 5.0,
            LegacyType::Strategist => 0.05,
            LegacyType::Recruiter => 2.0,
            LegacyType::Lorekeeper => 0.10,
        }
    }
    pub fn bonus_description(&self) -> &'static str {
        match self {
            LegacyType::TrainingMentor => "+10% XP gain",
            LegacyType::Quartermaster => "-10% supply consumption",
            LegacyType::Diplomat => "+5 faction relation",
            LegacyType::Strategist => "+5% combat power",
            LegacyType::Recruiter => "+2 base stats on recruits",
            LegacyType::Lorekeeper => "+10% quest gold rewards",
        }
    }
}

impl VoteTopic {
    pub fn description(&self) -> String {
        match self {
            VoteTopic::DeclareWar { faction_id } => format!("Declare war on faction {}", faction_id),
            VoteTopic::SuePeace { faction_id } => format!("Sue for peace with faction {}", faction_id),
            VoteTopic::ExileAdventurer { adventurer_id } => format!("Exile adventurer {}", adventurer_id),
            VoteTopic::ChangePolicy { policy } => format!("Change policy: {}", policy),
            VoteTopic::MajorExpedition { region_id } => format!("Launch expedition to region {}", region_id),
            VoteTopic::AllianceProposal { faction_id } => format!("Alliance with faction {}", faction_id),
        }
    }
}

impl FestivalType {
    pub fn display_name(&self) -> &'static str {
        match self {
            FestivalType::HarvestFeast => "Harvest Feast",
            FestivalType::WarMemorial => "War Memorial",
            FestivalType::TradeFair => "Trade Fair",
            FestivalType::ReligiousCeremony => "Religious Ceremony",
            FestivalType::ArtisanExpo => "Artisan Expo",
            FestivalType::MartialTournament => "Martial Tournament",
        }
    }
    pub fn reward_description(&self) -> &'static str {
        match self {
            FestivalType::HarvestFeast => "+20% trade income",
            FestivalType::WarMemorial => "+morale, less aggression",
            FestivalType::TradeFair => "Better buy/sell prices",
            FestivalType::ReligiousCeremony => "Reduced civilian unrest",
            FestivalType::ArtisanExpo => "Crafting bonus",
            FestivalType::MartialTournament => "Prize gold + reputation",
        }
    }
}

impl RegionalCulture {
    pub fn dominant(&self) -> Option<CultureAxis> {
        let vals = [
            (self.martial_influence, CultureAxis::Martial),
            (self.trade_influence, CultureAxis::Trade),
            (self.scholarly_influence, CultureAxis::Scholarly),
            (self.diplomatic_influence, CultureAxis::Diplomatic),
        ];
        // Only return a dominant if one axis is clearly above neutral (25)
        vals.iter()
            .max_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal))
            .filter(|v| v.0 > 30.0)
            .map(|v| v.1)
    }
}

impl Default for RegionalCulture {
    fn default() -> Self {
        Self {
            region_id: 0,
            martial_influence: 25.0,
            trade_influence: 25.0,
            scholarly_influence: 25.0,
            diplomatic_influence: 25.0,
        }
    }
}

impl ResourceType {
    pub const ALL: [ResourceType; 6] = [
        ResourceType::Iron, ResourceType::Wood, ResourceType::Crystal,
        ResourceType::Herbs, ResourceType::Hide, ResourceType::Obsidian,
    ];
}

impl MonsterSpecies {
    pub const ALL: [MonsterSpecies; 7] = [
        MonsterSpecies::Wolves, MonsterSpecies::Bandits, MonsterSpecies::Undead,
        MonsterSpecies::Goblins, MonsterSpecies::Trolls, MonsterSpecies::Drakes,
        MonsterSpecies::Aberrations,
    ];
}

impl VictoryCondition {
    pub const ALL: [VictoryCondition; 6] = [
        VictoryCondition::SurviveCrisis, VictoryCondition::EconomicDominance,
        VictoryCondition::DiplomaticUnity, VictoryCondition::MilitaryConquest,
        VictoryCondition::CulturalHegemony, VictoryCondition::QuestMaster,
    ];
}

// Serde defaults for new fields
fn default_population() -> u32 { 500 }
fn default_civilian_morale() -> f32 { 50.0 }
fn default_tax_rate() -> f32 { 0.1 }

// ---------------------------------------------------------------------------
// RNG helper
// ---------------------------------------------------------------------------

/// Deterministic LCG (same as combat sim). Returns value in [0, u32::MAX].
#[inline]
pub fn lcg_next(state: &mut u64) -> u32 {
    *state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
    (*state >> 33) as u32
}

fn default_max_strength() -> f32 {
    100.0
}

/// Returns a float in [0, 1).
#[inline]
pub fn lcg_f32(state: &mut u64) -> f32 {
    lcg_next(state) as f32 / u32::MAX as f32
}

// ---------------------------------------------------------------------------
// Test campaign constructors
// ---------------------------------------------------------------------------

impl CampaignState {
    /// Create a campaign with world content but no adventurers.
    ///
    /// The player must issue `ChooseStartingPackage` as their first action
    /// to receive adventurers and starting resources. Until then, the sim
    /// does not tick.
    ///
    /// Includes 3 regions, 2 factions, 4 locations, 2 NPC relationships.
    pub fn default_test_campaign(seed: u64) -> Self {
        // These adventurers are NOT placed in the guild — they're templates
        // for the starting choice packages. The guild starts empty.
        let _adventurer_templates = vec![
            Adventurer {
                id: 1,
                name: "Kael the Swift".into(),
                archetype: "ranger".into(),
                level: 3,
                xp: 0,
                stats: AdventurerStats {
                    max_hp: 80.0,
                    attack: 18.0,
                    defense: 10.0,
                    speed: 14.0,
                    ability_power: 8.0,
                },
                equipment: Equipment::default(),
                traits: vec!["keen_eye".into()],
                status: AdventurerStatus::Idle,
                loyalty: 70.0,
                stress: 10.0,
                fatigue: 5.0,
                injury: 0.0,
                resolve: 60.0,
                morale: 80.0,
                party_id: None,
                guild_relationship: 50.0,
                leadership_role: None,
                is_player_character: false,
                faction_id: None,
                rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
            },
            Adventurer {
                id: 2,
                name: "Sera the Stalwart".into(),
                archetype: "knight".into(),
                level: 4,
                xp: 0,
                stats: AdventurerStats {
                    max_hp: 120.0,
                    attack: 14.0,
                    defense: 20.0,
                    speed: 8.0,
                    ability_power: 5.0,
                },
                equipment: Equipment::default(),
                traits: vec!["shield_wall".into()],
                status: AdventurerStatus::Idle,
                loyalty: 80.0,
                stress: 5.0,
                fatigue: 10.0,
                injury: 0.0,
                resolve: 75.0,
                morale: 85.0,
                party_id: None,
                guild_relationship: 60.0,
                leadership_role: None,
                is_player_character: false,
                faction_id: None,
                rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
            },
            Adventurer {
                id: 3,
                name: "Mira the Wise".into(),
                archetype: "mage".into(),
                level: 3,
                xp: 0,
                stats: AdventurerStats {
                    max_hp: 60.0,
                    attack: 8.0,
                    defense: 6.0,
                    speed: 10.0,
                    ability_power: 25.0,
                },
                equipment: Equipment::default(),
                traits: vec!["arcane_focus".into()],
                status: AdventurerStatus::Idle,
                loyalty: 65.0,
                stress: 15.0,
                fatigue: 8.0,
                injury: 0.0,
                resolve: 55.0,
                morale: 75.0,
                party_id: None,
                guild_relationship: 40.0,
                leadership_role: None,
                is_player_character: false,
                faction_id: None,
                rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
            },
            Adventurer {
                id: 4,
                name: "Bron the Healer".into(),
                archetype: "cleric".into(),
                level: 2,
                xp: 0,
                stats: AdventurerStats {
                    max_hp: 70.0,
                    attack: 6.0,
                    defense: 12.0,
                    speed: 9.0,
                    ability_power: 20.0,
                },
                equipment: Equipment::default(),
                traits: vec!["healing_hands".into()],
                status: AdventurerStatus::Idle,
                loyalty: 85.0,
                stress: 8.0,
                fatigue: 3.0,
                injury: 0.0,
                resolve: 70.0,
                morale: 90.0,
                party_id: None,
                guild_relationship: 65.0,
                leadership_role: None,
                is_player_character: false,
                faction_id: None,
                rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
            },
        ];

        // Load world template: pick one based on seed from assets/world_templates/,
        // falling back to the built-in default if no templates are found.
        let world_template = Self::load_world_template(seed);

        let regions = world_template.regions;
        let locations = world_template.locations;
        let factions = world_template.factions;
        let diplomacy = world_template.diplomacy;
        let npc_relationships = world_template.npc_relationships;
        let global_threat_level = world_template.global_threat_level;

        CampaignState {
            tick: 0,
            elapsed_ms: 0,
            guild: GuildState {
                gold: 100.0,
                supplies: 80.0,
                reputation: 25.0,
                base: BaseState {
                    base_type: BaseType::Camp,
                    position: (0.0, 0.0),
                    upgrade_slots: Vec::new(),
                    defensive_strength: 10.0,
                },
                active_quest_capacity: 3,
                unlock_bitmask: 0,
                inventory: Vec::new(),
                spend_priority: Default::default(),
                market_prices: Default::default(),
                total_trade_income: 0.0,
                investment: Default::default(),
                purchase_history: Default::default(),
                guild_tier: GuildTier::default(),
                resources: std::collections::HashMap::new(),
            },
            overworld: OverworldState {
                regions,
                locations,
                global_threat_level,
                campaign_progress: 0.0,
                endgame_calamity: None,
                active_crises: Vec::new(),
                season: Season::default(),
                season_tick: 0,
                active_weather: Vec::new(),
                next_weather_id: 1,
            },
            factions,
            diplomacy,
            adventurers: Vec::new(), // Empty until ChooseStartingPackage
            parties: Vec::new(),
            request_board: Vec::new(),
            active_quests: Vec::new(),
            completed_quests: Vec::new(),
            active_battles: Vec::new(),
            pending_choices: Vec::new(),
            hook_state: super::quest_hooks::HookState::default(),
            unlocks: Vec::new(),
            progression_history: Vec::new(),
            adventurer_bonds: std::collections::HashMap::new(),
            event_log: Vec::new(),
            npc_relationships,
            rng: seed,
            next_quest_id: 1,
            next_party_id: 1,
            next_battle_id: 1,
            next_unlock_id: 1,
            next_event_id: 1,
            combat_mode: CombatMode::Oracle,
            pending_progression: Vec::new(),
            resting: false,
            ticks_since_rest: 0,
            phase: CampaignPhase::CharacterCreation,
            available_starting_choices: Self::load_or_default_starting_choices(),
            player_character: None,
            creation_event_queue: Vec::new(),
            guild_buildings: super::systems::buildings::GuildBuildings::default(),
            config: CampaignConfig::default(),
            llm_config: None,
            llm_store: None,
            vae_model: None,
            rival_guild: RivalGuildState::default(),
            trade_routes: Vec::new(),
            caravans: Vec::new(),
            next_caravan_id: 1,
            next_route_id: 1,
            retired_adventurers: Vec::new(),
            mentor_assignments: Vec::new(),
            civil_wars: Vec::new(),
            rumors: Vec::new(),
            war_exhaustion: Vec::new(),
            spies: Vec::new(),
            next_spy_id: 1,
            available_mercenaries: Vec::new(),
            hired_mercenaries: Vec::new(),
            black_market: BlackMarketState::default(),
            resource_nodes: Vec::new(),
            gathering_boosts: std::collections::HashMap::new(),
            migrations: Vec::new(),
            next_migration_id: 1,
            active_festivals: Vec::new(),
            rivalries: Vec::new(),
            chronicle: Vec::new(),
            nemeses: Vec::new(),
            faction_favors: Vec::new(),
            favor_requests: Vec::new(),
            site_preparations: Vec::new(),
            next_site_id: 1,
            council_votes: Vec::new(),
            next_vote_id: 1,
            diseases: Vec::new(),
            next_disease_id: 1,
            prisoners: Vec::new(),
            next_prisoner_id: 1,
            captured_adventurers: Vec::new(),
            propaganda_campaigns: Vec::new(),
            monster_populations: Vec::new(),
            visions: Vec::new(),
            next_vision_id: 1,
            loans: Vec::new(),
            credit_rating: 100.0,
            victory_condition: VictoryCondition::default(),
            victory_progress: VictoryProgress::default(),
            named_npcs: Vec::new(),
            artifacts: Vec::new(),
            next_artifact_id: 1,
            difficulty_scaling: DifficultyState::default(),
            regional_cultures: Vec::new(),
            dungeons: Vec::new(),
            resources: std::collections::HashMap::new(),
            system_trackers: SystemTrackers::default(),
        }
    }

    /// Load a world template based on seed from `assets/world_templates/`,
    /// falling back to the built-in default frontier template.
    fn load_world_template(seed: u64) -> super::world_templates::WorldTemplate {
        let dir = std::path::Path::new("assets/world_templates");
        if dir.exists() {
            match super::world_templates::WorldTemplate::load_from_dir(dir) {
                Ok(templates) if !templates.is_empty() => {
                    let idx = (seed as usize) % templates.len();
                    return templates.into_iter().nth(idx).unwrap();
                }
                Ok(_) => {} // empty dir, fall through
                Err(_) => {} // parse error, fall through
            }
        }
        super::world_templates::WorldTemplate::default_frontier()
    }

    /// Load starting choices from `assets/starting_packages/` or return defaults.
    fn load_or_default_starting_choices() -> Vec<StartingChoice> {
        let dir = std::path::Path::new("assets/starting_packages");
        if dir.exists() {
            match StartingChoice::load_from_dir(dir) {
                Ok(choices) if !choices.is_empty() => return choices,
                Ok(_) => {} // empty dir, fall through
                Err(_) => {} // parse error, fall through
            }
        }

        // Fallback: three inline defaults
        vec![
            StartingChoice {
                name: "War Chest".into(),
                description: "Extra gold, two mid-level adventurers".into(),
                adventurers: vec![
                    Adventurer {
                        id: 1, name: "Finn".into(), archetype: "ranger".into(), level: 2, xp: 0,
                        stats: AdventurerStats { max_hp: 70.0, attack: 14.0, defense: 8.0, speed: 12.0, ability_power: 6.0 },
                        equipment: Equipment::default(), traits: Vec::new(),
                        status: AdventurerStatus::Idle,
                        loyalty: 60.0, stress: 10.0, fatigue: 5.0, injury: 0.0, resolve: 50.0, morale: 70.0,
                        party_id: None, guild_relationship: 40.0,
                        leadership_role: None, is_player_character: false, faction_id: None, rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
                    },
                    Adventurer {
                        id: 2, name: "Greta".into(), archetype: "knight".into(), level: 2, xp: 0,
                        stats: AdventurerStats { max_hp: 100.0, attack: 10.0, defense: 16.0, speed: 7.0, ability_power: 4.0 },
                        equipment: Equipment::default(), traits: Vec::new(),
                        status: AdventurerStatus::Idle,
                        loyalty: 65.0, stress: 5.0, fatigue: 8.0, injury: 0.0, resolve: 55.0, morale: 75.0,
                        party_id: None, guild_relationship: 45.0,
                        leadership_role: None, is_player_character: false, faction_id: None, rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
                    },
                ],
                gold_bonus: 150.0, supply_bonus: 30.0, reputation_bonus: 5.0, items: Vec::new(),
            },
            StartingChoice {
                name: "The Veteran".into(),
                description: "One overleveled adventurer with a cursed arm".into(),
                adventurers: vec![
                    Adventurer {
                        id: 1, name: "Gareth Ironhand".into(), archetype: "knight".into(), level: 6, xp: 0,
                        stats: AdventurerStats { max_hp: 150.0, attack: 22.0, defense: 25.0, speed: 6.0, ability_power: 8.0 },
                        equipment: Equipment::default(), traits: vec!["cursed_arm".into()],
                        status: AdventurerStatus::Idle,
                        loyalty: 40.0, stress: 30.0, fatigue: 20.0, injury: 15.0, resolve: 80.0, morale: 50.0,
                        party_id: None, guild_relationship: 25.0,
                        leadership_role: None, is_player_character: false, faction_id: None, rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
                    },
                ],
                gold_bonus: 0.0, supply_bonus: 0.0, reputation_bonus: 10.0, items: Vec::new(),
            },
            StartingChoice {
                name: "Fresh Recruits".into(),
                description: "Four level-1 rookies".into(),
                adventurers: vec![
                    Adventurer {
                        id: 1, name: "Alaric".into(), archetype: "ranger".into(), level: 1, xp: 0,
                        stats: AdventurerStats { max_hp: 60.0, attack: 12.0, defense: 6.0, speed: 13.0, ability_power: 5.0 },
                        equipment: Equipment::default(), traits: Vec::new(),
                        status: AdventurerStatus::Idle,
                        loyalty: 55.0, stress: 12.0, fatigue: 8.0, injury: 0.0, resolve: 45.0, morale: 65.0,
                        party_id: None, guild_relationship: 35.0,
                        leadership_role: None, is_player_character: false, faction_id: None, rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
                    },
                    Adventurer {
                        id: 2, name: "Brynn".into(), archetype: "mage".into(), level: 1, xp: 0,
                        stats: AdventurerStats { max_hp: 45.0, attack: 5.0, defense: 4.0, speed: 9.0, ability_power: 18.0 },
                        equipment: Equipment::default(), traits: Vec::new(),
                        status: AdventurerStatus::Idle,
                        loyalty: 50.0, stress: 15.0, fatigue: 5.0, injury: 0.0, resolve: 40.0, morale: 60.0,
                        party_id: None, guild_relationship: 30.0,
                        leadership_role: None, is_player_character: false, faction_id: None, rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
                    },
                    Adventurer {
                        id: 3, name: "Cira".into(), archetype: "cleric".into(), level: 1, xp: 0,
                        stats: AdventurerStats { max_hp: 55.0, attack: 4.0, defense: 8.0, speed: 8.0, ability_power: 15.0 },
                        equipment: Equipment::default(), traits: Vec::new(),
                        status: AdventurerStatus::Idle,
                        loyalty: 70.0, stress: 8.0, fatigue: 3.0, injury: 0.0, resolve: 50.0, morale: 75.0,
                        party_id: None, guild_relationship: 45.0,
                        leadership_role: None, is_player_character: false, faction_id: None, rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
                    },
                    Adventurer {
                        id: 4, name: "Daven".into(), archetype: "rogue".into(), level: 1, xp: 0,
                        stats: AdventurerStats { max_hp: 50.0, attack: 15.0, defense: 5.0, speed: 14.0, ability_power: 4.0 },
                        equipment: Equipment::default(), traits: Vec::new(),
                        status: AdventurerStatus::Idle,
                        loyalty: 45.0, stress: 18.0, fatigue: 10.0, injury: 0.0, resolve: 35.0, morale: 55.0,
                        party_id: None, guild_relationship: 25.0,
                        leadership_role: None, is_player_character: false, faction_id: None, rallying_to: None,
                    tier_status: Default::default(),
                    history_tags: Default::default(),
                    backstory: None,
                    deeds: Vec::new(),
                    hobbies: Vec::new(),
                    disease_status: DiseaseStatus::Healthy,
                    },
                ],
                gold_bonus: 20.0, supply_bonus: 10.0, reputation_bonus: 0.0, items: Vec::new(),
            },
        ]
    }

    /// Create a test campaign with custom config.
    pub fn with_config(seed: u64, config: CampaignConfig) -> Self {
        let mut state = Self::default_test_campaign(seed);
        // Apply starting state from config
        state.guild.gold = config.starting_state.gold.max(0.0);
        state.guild.supplies = config.starting_state.supplies.max(0.0);
        state.guild.reputation = config.starting_state.reputation.clamp(0.0, 100.0);
        state.guild.base.defensive_strength = config.starting_state.base_defensive_strength;
        state.guild.active_quest_capacity = config.starting_state.active_quest_capacity;
        state.overworld.global_threat_level = config.starting_state.global_threat_level;
        state.config = config;
        state
    }
}
