//! Per-fixture runtime for `assets/sim/tom_probe.sim` — Theory-of-Mind
//! end-to-end probe (post-fix shape).
//!
//! ## What lights up
//!
//! - The Knower SoA (`agent_alive`).
//! - The `BeliefAcquired` event ring + per-tick tail clear.
//! - The `physics_WhatIBelieve` kernel (per-Knower; emits one
//!   `BeliefAcquired { observer: self, subject: self, fact_bit: 1 }`
//!   per tick into the ring).
//! - The `fold_beliefs_flags` kernel (per-event; OR's `fact_bit` into
//!   `view_storage_primary[observer * agent_cap + subject]` via
//!   WGSL native `atomicOr` — no CAS retry, P11 trivial).
//! - Per-(observer, subject) belief storage: 6 SoA columns mirroring
//!   the spec's `BeliefState` block.
//!
//! ## Wave 3 ToM Phase 3.8 — hand-written WGSL retirement
//!
//! Phase 3/3.5/3.6 shipped the observe/scry/reveal/decay verbs as
//! hand-written WGSL kernels (`OBSERVE_WGSL`, `SCRY_WGSL`,
//! `REVEAL_WGSL`, `DECAY_WGSL`) embedded as `const &str` literals in
//! this file. Phase 3.8 retires those four constants per the user's
//! "no hand-written WGSL in runtime crates" constraint:
//!
//! - **observe / scry / reveal**: now `physics @phase(post)` consumer
//!   rules in `assets/sim/tom_probe.sim` (`ApplyObserveBeliefUpdate`,
//!   `ApplyScryBeliefUpdate`, `ApplyRevealBeliefUpdate`). The runtime's
//!   `observe()` / `scry()` / `reveal()` methods now write a synthetic
//!   chronicle record (kind=64 / 65 / 66, engine-aliased) into the
//!   unified `event_ring` via
//!   `engine::gpu::EventRing::append_chronicle_record` and dispatch the
//!   compiler-emitted consumer kernel from .sim.
//! - **decay**: stays as a runtime-dispatched compiler-generated kernel
//!   (no DSL surface for "for_each_agent body" today). The WGSL string
//!   moved out of this crate into
//!   `dsl_compiler::belief_decay_wgsl::decay_kernel_wgsl()` so this
//!   file no longer carries any literal `_WGSL: &str` constant.
//!
//! ## BeliefState SoA (Wave 3 ToM Phase 2)
//!
//! Each (observer, target) pair is described by 6 parallel SoA
//! columns mirroring the spec's BeliefState block:
//!
//! | Field            | Type              | Buffer                       |
//! |------------------|-------------------|------------------------------|
//! | flags            | u32               | `beliefs_flags_primary`      |
//! | last_known_pos   | vec4 (vec3 padded)| `beliefs_pos_primary`        |
//! | last_known_creature_type | u8 (q8)   | `beliefs_type_primary`       |
//! | last_seen_tick   | u32               | `beliefs_tick_primary`       |
//! | confidence       | u8 (q8)           | `beliefs_confidence_primary` |
//! | suspicion        | u8 (q8)           | `beliefs_suspicion_primary`  |
//!
//! Cell indexing across all 6 columns is `observer * agent_count +
//! target` — identical row-major flat layout.
//!
//! ## Expected outcome (FULL FIRE)
//!
//! After N ticks at agent_count = N: `beliefs_flags(i, i) = 1u` for
//! every alive Knower; every off-diagonal `beliefs_flags(i, j != i)
//! = 0u`.

use engine::ability::registry_gpu::PackedAbilityRegistryGpu;
use engine::ability::{AbilityRegistry, PackedAbilityRegistry};
use engine::sim_trait::CompiledSim;
use engine::GpuContext;
use glam::Vec3;
use wgpu::util::DeviceExt;

include!(concat!(env!("OUT_DIR"), "/generated.rs"));

use engine::gpu::{
    bgl_storage, bgl_uniform, AgentBuffers, EventRing, KernelBindingsContext,
    EVENT_STRIDE_U32,
};

/// Chronicle record stride in u32 words. Matches
/// `engine::gpu::EVENT_STRIDE_U32` and
/// `dsl_compiler::cpu_chronicle_reference::CHRONICLE_RECORD_STRIDE_U32`.
const CHRONICLE_STRIDE_U32: usize = EVENT_STRIDE_U32 as usize;

/// Engine `EventKindId::EffectObserveApplied`. Matches
/// `engine_events::engine_event_kind_id_for_name("EffectObserveApplied")`.
const KIND_OBSERVE: u32 = 64;
/// Engine `EventKindId::EffectScryApplied`.
const KIND_SCRY: u32 = 65;
/// Engine `EventKindId::EffectRevealApplied`.
const KIND_REVEAL: u32 = 66;
/// Engine `EventKindId::EffectDecoyApplied` (Wave 3 ToM Phase 4).
const KIND_DECOY: u32 = 68;
/// Engine `EventKindId::EffectEraseBeliefApplied` (Wave 3 ToM Phase 4).
const KIND_ERASE_BELIEF: u32 = 69;
/// Engine `EventKindId::EffectDisguiseApplied` (Wave 3 ToM Phase 5).
const KIND_DISGUISE: u32 = 67;

/// Decay kernel infrastructure. The kernel WGSL is
/// generated by `dsl_compiler::belief_decay_wgsl::decay_kernel_wgsl()`
/// (NOT by a literal `const &str` in this file — Phase 3.8 retirement
/// of hand-written WGSL in runtime crates). The 4-kernel
/// `BeliefConsumerGpu` struct that previously held observe/scry/reveal/
/// decay pipelines collapsed to this single `DecayGpu` struct: the 3
/// other consumers are .sim-authored and use the compiler-emitted
/// dispatch helpers.
struct DecayGpu {
    cfg_buf: wgpu::Buffer,
    pipeline: wgpu::ComputePipeline,
    bgl: wgpu::BindGroupLayout,
}

/// Uniform for the compiler-generated decay kernel. Same shape as the
/// retired `BeliefConsumerCfg` so the WGSL field offsets stay stable —
/// the kernel reads `cfg.tick`, `cfg.cell_count`. The other fields are
/// inert padding for std140-like alignment.
#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct DecayCfg {
    observer: u32,
    target_or_subject: u32,
    subject: u32,
    agent_count: u32,
    tick: u32,
    cell_count: u32,
    _pad0: u32,
    _pad1: u32,
}

impl DecayGpu {
    fn new(device: &wgpu::Device) -> Self {
        let cfg_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("tom_probe_runtime::decay::cfg"),
            size: std::mem::size_of::<DecayCfg>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("tom_probe_runtime::decay::bgl"),
            entries: &[
                bgl_uniform(0),
                bgl_storage(1, false), // beliefs_confidence
                bgl_storage(2, true),  // beliefs_tick (read-only)
            ],
        });
        let wgsl_src = dsl_compiler::belief_decay_wgsl::decay_kernel_wgsl();
        let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("tom_probe_runtime::decay::wgsl"),
            source: wgpu::ShaderSource::Wgsl(wgsl_src.into()),
        });
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("tom_probe_runtime::decay::pl"),
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("tom_probe_runtime::decay::pipeline"),
            layout: Some(&pl),
            module: &module,
            entry_point: Some("cs_decay"),
            compilation_options: Default::default(),
            cache: None,
        });
        Self { cfg_buf, pipeline, bgl }
    }
}

/// Per-fixture state for the ToM probe.
pub struct TomProbeState {
    gpu: GpuContext,

    // -- Knower SoA --
    agent_alive_buf: wgpu::Buffer,

    // -- Agent SoA: pos (vec4-padded vec3) + creature_type (u32 per
    // cell). Phase 3.8 — creature_type is allocated as one u32 per
    // agent (4 bytes) so the .sim consumer's `agents.creature_type(t)`
    // accessor reads it via the standard `array<u32>` agent-SoA shape.
    // The pre-3.8 hand-written observe kernel used u8-packed bytes;
    // the move to .sim-authored consumer flips to the engine-standard
    // u32 layout. Test seeders take `&[u8]` and zero-extend to u32.
    agent_pos_buf: wgpu::Buffer,
    agent_pos_staging: wgpu::Buffer,
    agent_pos_cache: Vec<[f32; 4]>,
    agent_pos_dirty: bool,

    agent_creature_type_buf: wgpu::Buffer,
    agent_creature_type_staging: wgpu::Buffer,
    agent_creature_type_cache: Vec<u8>,
    agent_creature_type_dirty: bool,

    // -- Wave 3 ToM Phase 5 — per-agent disguise SoA --
    // `disguise_expires_at_tick`: until which world.tick the disguise
    // is active. Until that tick, observers see `disguise_fake_type`
    // instead of the agent's true `creature_type`.
    agent_disguise_expires_at_tick_buf: wgpu::Buffer,
    agent_disguise_expires_at_tick_staging: wgpu::Buffer,
    agent_disguise_expires_at_tick_cache: Vec<u32>,
    agent_disguise_expires_at_tick_dirty: bool,

    agent_disguise_fake_type_buf: wgpu::Buffer,
    agent_disguise_fake_type_staging: wgpu::Buffer,
    agent_disguise_fake_type_cache: Vec<u32>,
    agent_disguise_fake_type_dirty: bool,

    // -- BeliefState SoA: 6 columns --
    beliefs_flags_primary: wgpu::Buffer,
    beliefs_flags_staging: wgpu::Buffer,
    beliefs_flags_cache: Vec<u32>,
    beliefs_flags_dirty: bool,

    beliefs_pos_primary: wgpu::Buffer,
    beliefs_pos_staging: wgpu::Buffer,
    beliefs_pos_cache: Vec<[f32; 4]>,
    beliefs_pos_dirty: bool,

    beliefs_type_primary: wgpu::Buffer,
    beliefs_type_staging: wgpu::Buffer,
    beliefs_type_cache: Vec<u8>,
    beliefs_type_dirty: bool,

    beliefs_tick_primary: wgpu::Buffer,
    beliefs_tick_staging: wgpu::Buffer,
    beliefs_tick_cache: Vec<u32>,
    beliefs_tick_dirty: bool,

    beliefs_confidence_primary: wgpu::Buffer,
    beliefs_confidence_staging: wgpu::Buffer,
    beliefs_confidence_cache: Vec<u8>,
    beliefs_confidence_dirty: bool,

    beliefs_suspicion_primary: wgpu::Buffer,
    beliefs_suspicion_staging: wgpu::Buffer,
    beliefs_suspicion_cache: Vec<u8>,
    beliefs_suspicion_dirty: bool,

    // -- Event ring + per-kernel cfg uniforms --
    event_ring: EventRing,
    physics_cfg_buf: wgpu::Buffer,
    fold_cfg_buf: wgpu::Buffer,
    /// cfg uniforms for the Wave 3 ToM Phase 3.8 .sim-authored
    /// chronicle consumers (observe / scry / reveal). Each consumer
    /// kernel has its own `Cfg` struct (PerEvent-shape:
    /// `{ event_count, tick, seed, agent_cap }`); per-step writes
    /// update `event_count` and `tick` before the dispatch.
    apply_observe_cfg_buf: wgpu::Buffer,
    apply_scry_cfg_buf: wgpu::Buffer,
    apply_reveal_cfg_buf: wgpu::Buffer,
    /// Wave 3 ToM Phase 4 — cfg uniforms for the .sim-authored deception
    /// consumers (decoy / erase_belief). Same `Cfg` shape as the Phase 3.8
    /// observe/scry/reveal consumers.
    apply_decoy_cfg_buf: wgpu::Buffer,
    apply_erase_belief_cfg_buf: wgpu::Buffer,
    /// Wave 3 ToM Phase 5 — cfg uniform for the .sim-authored disguise
    /// consumer (`physics_ApplyDisguise`). Reads `cfg.tick` so the
    /// rule's `world.tick + duration` math lands at the right epoch.
    apply_disguise_cfg_buf: wgpu::Buffer,

    /// Empty placeholder for the shared
    /// [`KernelBindingsContext::registry`] field — this fixture has no
    /// abilities, but the compiler-emitted constructor signature requires
    /// the context to expose one.
    registry_gpu: PackedAbilityRegistryGpu,

    cache: dispatch::KernelCache,

    /// Compiler-generated decay kernel (Phase 3.8 — replaces the
    /// retired hand-written `DECAY_WGSL` const).
    decay_gpu: DecayGpu,

    tick: u64,
    agent_count: u32,
    seed: u64,
}

/// Allocate a paired (primary, staging) buffer.
fn alloc_belief_column_pair(
    device: &wgpu::Device,
    label_primary: &str,
    label_staging: &str,
    bytes: u64,
) -> (wgpu::Buffer, wgpu::Buffer) {
    let bytes = bytes.max(16);
    let primary = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some(label_primary),
        size: bytes,
        usage: wgpu::BufferUsages::STORAGE
            | wgpu::BufferUsages::COPY_SRC
            | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let staging = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some(label_staging),
        size: bytes,
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });
    (primary, staging)
}

impl TomProbeState {
    pub fn new(seed: u64, agent_count: u32) -> Self {
        let gpu = GpuContext::new_blocking().expect("init wgpu adapter + device");

        // Knower SoA — `agent_alive` is the only field the producer
        // rule reads (`where (self.alive)`). Every slot starts alive.
        let alive_init: Vec<u32> = vec![1u32; agent_count as usize];
        let agent_alive_buf =
            gpu.device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("tom_probe_runtime::agent_alive"),
                contents: bytemuck::cast_slice(&alive_init),
                usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            });

        let agent_pos_bytes = (agent_count as u64) * 16;
        let (agent_pos_buf, agent_pos_staging) = alloc_belief_column_pair(
            &gpu.device,
            "tom_probe_runtime::agent_pos_primary",
            "tom_probe_runtime::agent_pos_staging",
            agent_pos_bytes,
        );

        // Phase 3.8 — agent_creature_type is one u32 per agent (4
        // bytes per slot) so the compiler-emitted observe consumer's
        // `array<u32>` binding type matches the host-supplied buffer.
        // Pre-3.8 was u8 packed; flipping to u32 for the .sim path.
        let agent_creature_type_bytes = ((agent_count as u64) * 4).max(16);
        let (agent_creature_type_buf, agent_creature_type_staging) =
            alloc_belief_column_pair(
                &gpu.device,
                "tom_probe_runtime::agent_creature_type_primary",
                "tom_probe_runtime::agent_creature_type_staging",
                agent_creature_type_bytes,
            );

        // Wave 3 ToM Phase 5 — per-agent disguise SoA. One u32 per slot.
        let agent_disguise_bytes = ((agent_count as u64) * 4).max(16);
        let (agent_disguise_expires_at_tick_buf, agent_disguise_expires_at_tick_staging) =
            alloc_belief_column_pair(
                &gpu.device,
                "tom_probe_runtime::agent_disguise_expires_at_tick_primary",
                "tom_probe_runtime::agent_disguise_expires_at_tick_staging",
                agent_disguise_bytes,
            );
        let (agent_disguise_fake_type_buf, agent_disguise_fake_type_staging) =
            alloc_belief_column_pair(
                &gpu.device,
                "tom_probe_runtime::agent_disguise_fake_type_primary",
                "tom_probe_runtime::agent_disguise_fake_type_staging",
                agent_disguise_bytes,
            );

        // -- BeliefState SoA columns --
        let cell_count = (agent_count as u64) * (agent_count as u64);

        let flags_bytes = cell_count * 4;
        let (beliefs_flags_primary, beliefs_flags_staging) = alloc_belief_column_pair(
            &gpu.device,
            "tom_probe_runtime::beliefs_flags_primary",
            "tom_probe_runtime::beliefs_flags_staging",
            flags_bytes,
        );

        let pos_bytes = cell_count * 16;
        let (beliefs_pos_primary, beliefs_pos_staging) = alloc_belief_column_pair(
            &gpu.device,
            "tom_probe_runtime::beliefs_pos_primary",
            "tom_probe_runtime::beliefs_pos_staging",
            pos_bytes,
        );

        let u8_buf_bytes = ((cell_count + 15) / 16 * 16).max(16);
        let (beliefs_type_primary, beliefs_type_staging) = alloc_belief_column_pair(
            &gpu.device,
            "tom_probe_runtime::beliefs_type_primary",
            "tom_probe_runtime::beliefs_type_staging",
            u8_buf_bytes,
        );

        let tick_bytes = cell_count * 4;
        let (beliefs_tick_primary, beliefs_tick_staging) = alloc_belief_column_pair(
            &gpu.device,
            "tom_probe_runtime::beliefs_tick_primary",
            "tom_probe_runtime::beliefs_tick_staging",
            tick_bytes,
        );

        let (beliefs_confidence_primary, beliefs_confidence_staging) =
            alloc_belief_column_pair(
                &gpu.device,
                "tom_probe_runtime::beliefs_confidence_primary",
                "tom_probe_runtime::beliefs_confidence_staging",
                u8_buf_bytes,
            );

        let (beliefs_suspicion_primary, beliefs_suspicion_staging) =
            alloc_belief_column_pair(
                &gpu.device,
                "tom_probe_runtime::beliefs_suspicion_primary",
                "tom_probe_runtime::beliefs_suspicion_staging",
                u8_buf_bytes,
            );

        let event_ring = EventRing::new(&gpu, "tom_probe_runtime");

        let physics_cfg_init =
            physics_WhatIBelieve::PhysicsWhatIBelieveCfg {
                agent_cap: agent_count,
                tick: 0,
                seed: 0,
                _pad: 0,
            };
        let physics_cfg_buf =
            gpu.device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("tom_probe_runtime::physics_WhatIBelieve_cfg"),
                contents: bytemuck::bytes_of(&physics_cfg_init),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });

        let fold_cfg_init = fold_beliefs_flags::FoldBeliefsFlagsCfg {
            event_count: 0,
            tick: 0,
            second_key_pop: agent_count,
            agent_cap: 0,
        };
        let fold_cfg_buf =
            gpu.device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("tom_probe_runtime::fold_beliefs_flags_cfg"),
                contents: bytemuck::bytes_of(&fold_cfg_init),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });

        let decay_gpu = DecayGpu::new(&gpu.device);

        // Phase 3.8 — cfg buffers for the .sim-authored
        // observe/scry/reveal consumers. Each kernel reads from its
        // own `Cfg { event_count, tick, seed, agent_cap }`; the runtime
        // writes per-call values into these buffers before dispatch.
        let mk_consumer_cfg = |label: &'static str| {
            let init = physics_ApplyObserveBeliefUpdate::PhysicsApplyObserveBeliefUpdateCfg {
                event_count: 0,
                tick: 0,
                seed: 0,
                agent_cap: agent_count,
            };
            gpu.device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some(label),
                contents: bytemuck::bytes_of(&init),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            })
        };
        let apply_observe_cfg_buf = mk_consumer_cfg(
            "tom_probe_runtime::physics_ApplyObserveBeliefUpdate_cfg",
        );
        let apply_scry_cfg_buf = mk_consumer_cfg(
            "tom_probe_runtime::physics_ApplyScryBeliefUpdate_cfg",
        );
        let apply_reveal_cfg_buf = mk_consumer_cfg(
            "tom_probe_runtime::physics_ApplyRevealBeliefUpdate_cfg",
        );
        let apply_decoy_cfg_buf = mk_consumer_cfg(
            "tom_probe_runtime::physics_ApplyDecoyBeliefUpdate_cfg",
        );
        let apply_erase_belief_cfg_buf = mk_consumer_cfg(
            "tom_probe_runtime::physics_ApplyEraseBeliefUpdate_cfg",
        );
        let apply_disguise_cfg_buf = mk_consumer_cfg(
            "tom_probe_runtime::physics_ApplyDisguise_cfg",
        );

        let registry_gpu = PackedAbilityRegistryGpu::upload(
            &PackedAbilityRegistry::pack(&AbilityRegistry::new()),
            &gpu,
            "tom_probe_runtime",
        );

        Self {
            gpu,
            agent_alive_buf,
            agent_pos_buf,
            agent_pos_staging,
            agent_pos_cache: vec![[0.0f32; 4]; agent_count as usize],
            agent_pos_dirty: false,
            agent_creature_type_buf,
            agent_creature_type_staging,
            agent_creature_type_cache: vec![0u8; agent_count as usize],
            agent_creature_type_dirty: false,
            agent_disguise_expires_at_tick_buf,
            agent_disguise_expires_at_tick_staging,
            agent_disguise_expires_at_tick_cache: vec![0u32; agent_count as usize],
            agent_disguise_expires_at_tick_dirty: false,
            agent_disguise_fake_type_buf,
            agent_disguise_fake_type_staging,
            agent_disguise_fake_type_cache: vec![0u32; agent_count as usize],
            agent_disguise_fake_type_dirty: false,
            beliefs_flags_primary,
            beliefs_flags_staging,
            beliefs_flags_cache: vec![0u32; cell_count as usize],
            beliefs_flags_dirty: false,
            beliefs_pos_primary,
            beliefs_pos_staging,
            beliefs_pos_cache: vec![[0.0f32; 4]; cell_count as usize],
            beliefs_pos_dirty: false,
            beliefs_type_primary,
            beliefs_type_staging,
            beliefs_type_cache: vec![0u8; cell_count as usize],
            beliefs_type_dirty: false,
            beliefs_tick_primary,
            beliefs_tick_staging,
            beliefs_tick_cache: vec![0u32; cell_count as usize],
            beliefs_tick_dirty: false,
            beliefs_confidence_primary,
            beliefs_confidence_staging,
            beliefs_confidence_cache: vec![0u8; cell_count as usize],
            beliefs_confidence_dirty: false,
            beliefs_suspicion_primary,
            beliefs_suspicion_staging,
            beliefs_suspicion_cache: vec![0u8; cell_count as usize],
            beliefs_suspicion_dirty: false,
            event_ring,
            physics_cfg_buf,
            fold_cfg_buf,
            apply_observe_cfg_buf,
            apply_scry_cfg_buf,
            apply_reveal_cfg_buf,
            apply_decoy_cfg_buf,
            apply_erase_belief_cfg_buf,
            apply_disguise_cfg_buf,
            registry_gpu,
            cache: dispatch::KernelCache::default(),
            decay_gpu,
            tick: 0,
            agent_count,
            seed,
        }
    }

    // -- BeliefState readback accessors --

    pub fn beliefs_flags(&mut self) -> &[u32] {
        if self.beliefs_flags_dirty {
            let bytes = (self.beliefs_flags_cache.len() as u64) * 4;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::beliefs_flags::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.beliefs_flags_primary,
                0,
                &self.beliefs_flags_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.beliefs_flags_staging.slice(..);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            let raw: &[u32] = bytemuck::cast_slice(&mapped);
            self.beliefs_flags_cache.copy_from_slice(raw);
            drop(mapped);
            self.beliefs_flags_staging.unmap();
            self.beliefs_flags_dirty = false;
        }
        &self.beliefs_flags_cache
    }

    pub fn beliefs_pos(&mut self) -> &[[f32; 4]] {
        if self.beliefs_pos_dirty {
            let bytes = (self.beliefs_pos_cache.len() as u64) * 16;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::beliefs_pos::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.beliefs_pos_primary,
                0,
                &self.beliefs_pos_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.beliefs_pos_staging.slice(..);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            let raw: &[[f32; 4]] = bytemuck::cast_slice(&mapped);
            self.beliefs_pos_cache.copy_from_slice(raw);
            drop(mapped);
            self.beliefs_pos_staging.unmap();
            self.beliefs_pos_dirty = false;
        }
        &self.beliefs_pos_cache
    }

    pub fn beliefs_type(&mut self) -> &[u8] {
        if self.beliefs_type_dirty {
            let cell_count = self.beliefs_type_cache.len();
            let bytes = cell_count as u64;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::beliefs_type::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.beliefs_type_primary,
                0,
                &self.beliefs_type_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.beliefs_type_staging.slice(..bytes);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            self.beliefs_type_cache.copy_from_slice(&mapped[..cell_count]);
            drop(mapped);
            self.beliefs_type_staging.unmap();
            self.beliefs_type_dirty = false;
        }
        &self.beliefs_type_cache
    }

    pub fn beliefs_tick(&mut self) -> &[u32] {
        if self.beliefs_tick_dirty {
            let bytes = (self.beliefs_tick_cache.len() as u64) * 4;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::beliefs_tick::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.beliefs_tick_primary,
                0,
                &self.beliefs_tick_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.beliefs_tick_staging.slice(..);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            let raw: &[u32] = bytemuck::cast_slice(&mapped);
            self.beliefs_tick_cache.copy_from_slice(raw);
            drop(mapped);
            self.beliefs_tick_staging.unmap();
            self.beliefs_tick_dirty = false;
        }
        &self.beliefs_tick_cache
    }

    pub fn beliefs_confidence(&mut self) -> &[u8] {
        if self.beliefs_confidence_dirty {
            let cell_count = self.beliefs_confidence_cache.len();
            let bytes = cell_count as u64;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::beliefs_confidence::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.beliefs_confidence_primary,
                0,
                &self.beliefs_confidence_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.beliefs_confidence_staging.slice(..bytes);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            self.beliefs_confidence_cache
                .copy_from_slice(&mapped[..cell_count]);
            drop(mapped);
            self.beliefs_confidence_staging.unmap();
            self.beliefs_confidence_dirty = false;
        }
        &self.beliefs_confidence_cache
    }

    pub fn beliefs_suspicion(&mut self) -> &[u8] {
        if self.beliefs_suspicion_dirty {
            let cell_count = self.beliefs_suspicion_cache.len();
            let bytes = cell_count as u64;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::beliefs_suspicion::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.beliefs_suspicion_primary,
                0,
                &self.beliefs_suspicion_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.beliefs_suspicion_staging.slice(..bytes);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            self.beliefs_suspicion_cache
                .copy_from_slice(&mapped[..cell_count]);
            drop(mapped);
            self.beliefs_suspicion_staging.unmap();
            self.beliefs_suspicion_dirty = false;
        }
        &self.beliefs_suspicion_cache
    }

    // -- Test-only seed helpers --

    pub fn seed_beliefs_flags(&mut self, values: &[u32]) {
        let expected = self.cell_count() as usize;
        assert_eq!(values.len(), expected);
        self.gpu.queue.write_buffer(
            &self.beliefs_flags_primary,
            0,
            bytemuck::cast_slice(values),
        );
        self.beliefs_flags_dirty = true;
    }

    pub fn seed_beliefs_pos(&mut self, values: &[[f32; 4]]) {
        let expected = self.cell_count() as usize;
        assert_eq!(values.len(), expected);
        self.gpu.queue.write_buffer(
            &self.beliefs_pos_primary,
            0,
            bytemuck::cast_slice(values),
        );
        self.beliefs_pos_dirty = true;
    }

    pub fn seed_beliefs_type(&mut self, values: &[u8]) {
        let expected = self.cell_count() as usize;
        assert_eq!(values.len(), expected);
        let padded_size = ((expected + 15) / 16 * 16).max(16);
        let mut padded = vec![0u8; padded_size];
        padded[..expected].copy_from_slice(values);
        self.gpu
            .queue
            .write_buffer(&self.beliefs_type_primary, 0, &padded);
        self.beliefs_type_dirty = true;
    }

    pub fn seed_beliefs_tick(&mut self, values: &[u32]) {
        let expected = self.cell_count() as usize;
        assert_eq!(values.len(), expected);
        self.gpu.queue.write_buffer(
            &self.beliefs_tick_primary,
            0,
            bytemuck::cast_slice(values),
        );
        self.beliefs_tick_dirty = true;
    }

    pub fn seed_beliefs_confidence(&mut self, values: &[u8]) {
        let expected = self.cell_count() as usize;
        assert_eq!(values.len(), expected);
        let padded_size = ((expected + 15) / 16 * 16).max(16);
        let mut padded = vec![0u8; padded_size];
        padded[..expected].copy_from_slice(values);
        self.gpu
            .queue
            .write_buffer(&self.beliefs_confidence_primary, 0, &padded);
        self.beliefs_confidence_dirty = true;
    }

    pub fn seed_beliefs_suspicion(&mut self, values: &[u8]) {
        let expected = self.cell_count() as usize;
        assert_eq!(values.len(), expected);
        let padded_size = ((expected + 15) / 16 * 16).max(16);
        let mut padded = vec![0u8; padded_size];
        padded[..expected].copy_from_slice(values);
        self.gpu
            .queue
            .write_buffer(&self.beliefs_suspicion_primary, 0, &padded);
        self.beliefs_suspicion_dirty = true;
    }

    pub fn cell_count(&self) -> u32 {
        self.agent_count * self.agent_count
    }

    // -- Wave 3 ToM Phase 3 agent SoA seeders + readers --

    pub fn seed_agent_pos(&mut self, values: &[[f32; 4]]) {
        let expected = self.agent_count as usize;
        assert_eq!(values.len(), expected);
        self.gpu
            .queue
            .write_buffer(&self.agent_pos_buf, 0, bytemuck::cast_slice(values));
        self.agent_pos_dirty = true;
    }

    /// Seed the `agent_creature_type` column. Phase 3.8 — accepts
    /// `&[u8]` for API parity but stores one `u32` per agent (zero-
    /// extended low byte) so the .sim consumer's `array<u32>` binding
    /// reads the right value.
    pub fn seed_agent_creature_type(&mut self, values: &[u8]) {
        let expected = self.agent_count as usize;
        assert_eq!(values.len(), expected);
        let widened: Vec<u32> = values.iter().map(|&b| b as u32).collect();
        self.gpu.queue.write_buffer(
            &self.agent_creature_type_buf,
            0,
            bytemuck::cast_slice(&widened),
        );
        self.agent_creature_type_dirty = true;
    }

    pub fn agent_pos(&mut self) -> &[[f32; 4]] {
        if self.agent_pos_dirty {
            let bytes = (self.agent_pos_cache.len() as u64) * 16;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::agent_pos::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.agent_pos_buf,
                0,
                &self.agent_pos_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.agent_pos_staging.slice(..);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            let raw: &[[f32; 4]] = bytemuck::cast_slice(&mapped);
            self.agent_pos_cache.copy_from_slice(raw);
            drop(mapped);
            self.agent_pos_staging.unmap();
            self.agent_pos_dirty = false;
        }
        &self.agent_pos_cache
    }

    /// Read the agent SoA `creature_type` column back to host memory.
    /// Phase 3.8 — the underlying buffer is `array<u32>`; this reader
    /// truncates to u8 to preserve the pre-existing API.
    pub fn agent_creature_type(&mut self) -> &[u8] {
        if self.agent_creature_type_dirty {
            let cell_count = self.agent_creature_type_cache.len();
            let bytes = (cell_count as u64) * 4;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::agent_creature_type::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.agent_creature_type_buf,
                0,
                &self.agent_creature_type_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.agent_creature_type_staging.slice(..bytes);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            let words: &[u32] = bytemuck::cast_slice(&mapped);
            for (i, w) in words.iter().take(cell_count).enumerate() {
                self.agent_creature_type_cache[i] = (*w & 0xFF) as u8;
            }
            drop(mapped);
            self.agent_creature_type_staging.unmap();
            self.agent_creature_type_dirty = false;
        }
        &self.agent_creature_type_cache
    }

    /// Wave 3 ToM Phase 3.8 — observe verb. Queues a synthetic
    /// `EffectObserveApplied` chronicle record (kind=64) into the
    /// unified `event_ring` and dispatches the .sim-authored
    /// `physics_ApplyObserveBeliefUpdate` consumer kernel. The
    /// consumer reads the chronicle record + agent SoA's `pos` /
    /// `creature_type` and writes the 4 columns it touches:
    ///   - `last_known_pos[obs * N + tgt]`
    ///   - `last_known_creature_type[obs * N + tgt]`
    ///   - `last_seen_tick[obs * N + tgt] ← world.tick`
    ///   - `confidence[obs * N + tgt] ← 255`
    ///
    /// Replaces the retired hand-written `OBSERVE_WGSL` const.
    pub fn observe(&mut self, observer: u32, target: u32) {
        assert!(observer < self.agent_count);
        assert!(target < self.agent_count);

        // 1. Reset event_tail to 0 so the synthetic record lands at slot 0.
        self.queue_clear_tail();

        // 2. Append the chronicle record.
        let mut record = [0u32; CHRONICLE_STRIDE_U32];
        record[0] = KIND_OBSERVE;
        record[1] = self.tick as u32;
        record[2] = observer;
        record[3] = target;
        record[4] = 0; // target_observer (unused for self-observe)
        self.event_ring
            .append_chronicle_record(&self.gpu.queue, &record);

        // 3. Update consumer cfg + dispatch the .sim consumer.
        let cfg = physics_ApplyObserveBeliefUpdate::PhysicsApplyObserveBeliefUpdateCfg {
            event_count: 1,
            tick: self.tick as u32,
            seed: self.seed as u32,
            agent_cap: self.agent_count,
        };
        self.gpu.queue.write_buffer(
            &self.apply_observe_cfg_buf,
            0,
            bytemuck::bytes_of(&cfg),
        );

        let mut encoder =
            self.gpu
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::observe::encoder"),
                });
        let agent_buffers = AgentBuffers {
            pos_buf: Some(&self.agent_pos_buf),
            alive_buf: Some(&self.agent_alive_buf),
            ..Default::default()
        };
        let ctx = KernelBindingsContext {
            state: &agent_buffers,
            event_ring: &self.event_ring,
            registry: &self.registry_gpu,
            voxel_grid: None,
            navgrid: None,
            navgrid_cfg: None,
        };
        let extras = physics_ApplyObserveBeliefUpdate::PhysicsApplyObserveBeliefUpdateExtras {
            agent_disguise_expires_at_tick: &self.agent_disguise_expires_at_tick_buf,
            agent_disguise_fake_type: &self.agent_disguise_fake_type_buf,
            agent_creature_type: &self.agent_creature_type_buf,
            beliefs_pos: &self.beliefs_pos_primary,
            beliefs_type: &self.beliefs_type_primary,
            beliefs_tick: &self.beliefs_tick_primary,
            beliefs_confidence: &self.beliefs_confidence_primary,
            cfg: &self.apply_observe_cfg_buf,
        };
        let bindings =
            physics_ApplyObserveBeliefUpdate::PhysicsApplyObserveBeliefUpdateBindings::from_context_with_extras(
                &ctx, &extras,
            );
        dispatch::dispatch_physics_applyobservebeliefupdate(
            &mut self.cache,
            &bindings,
            &self.gpu.device,
            &mut encoder,
            1,
        );
        self.gpu.queue.submit(Some(encoder.finish()));

        self.beliefs_pos_dirty = true;
        self.beliefs_type_dirty = true;
        self.beliefs_tick_dirty = true;
        self.beliefs_confidence_dirty = true;
    }

    /// Wave 3 ToM Phase 3.8 — scry verb. Queues a synthetic
    /// `EffectScryApplied` chronicle record (kind=65) and dispatches
    /// the .sim-authored `physics_ApplyScryBeliefUpdate` consumer.
    /// The consumer copies the 6 BeliefState columns from
    /// `[target_observer * N + subject]` to `[caster * N + subject]`.
    ///
    /// Replaces the retired hand-written `SCRY_WGSL` const.
    pub fn scry(&mut self, observer: u32, target_observer: u32, subject: u32) {
        assert!(observer < self.agent_count);
        assert!(target_observer < self.agent_count);
        assert!(subject < self.agent_count);

        self.queue_clear_tail();

        // Chronicle record layout per `cpu_chronicle_reference::Scry`:
        //   slot 2 = caster (= observer), slot 3 = target (= subject_idx),
        //   slot 4 = target_observer, slot 5 = subject_idx.
        let mut record = [0u32; CHRONICLE_STRIDE_U32];
        record[0] = KIND_SCRY;
        record[1] = self.tick as u32;
        record[2] = observer;
        record[3] = subject;
        record[4] = target_observer;
        record[5] = subject;
        self.event_ring
            .append_chronicle_record(&self.gpu.queue, &record);

        let cfg = physics_ApplyScryBeliefUpdate::PhysicsApplyScryBeliefUpdateCfg {
            event_count: 1,
            tick: self.tick as u32,
            seed: self.seed as u32,
            agent_cap: self.agent_count,
        };
        self.gpu.queue.write_buffer(
            &self.apply_scry_cfg_buf,
            0,
            bytemuck::bytes_of(&cfg),
        );

        let mut encoder =
            self.gpu
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::scry::encoder"),
                });
        let agent_buffers = AgentBuffers {
            alive_buf: Some(&self.agent_alive_buf),
            ..Default::default()
        };
        let ctx = KernelBindingsContext {
            state: &agent_buffers,
            event_ring: &self.event_ring,
            registry: &self.registry_gpu,
            voxel_grid: None,
            navgrid: None,
            navgrid_cfg: None,
        };
        let extras = physics_ApplyScryBeliefUpdate::PhysicsApplyScryBeliefUpdateExtras {
            beliefs_pos: &self.beliefs_pos_primary,
            beliefs_type: &self.beliefs_type_primary,
            beliefs_tick: &self.beliefs_tick_primary,
            beliefs_confidence: &self.beliefs_confidence_primary,
            beliefs_suspicion: &self.beliefs_suspicion_primary,
            beliefs_flags: &self.beliefs_flags_primary,
            cfg: &self.apply_scry_cfg_buf,
        };
        let bindings =
            physics_ApplyScryBeliefUpdate::PhysicsApplyScryBeliefUpdateBindings::from_context_with_extras(
                &ctx, &extras,
            );
        dispatch::dispatch_physics_applyscrybeliefupdate(
            &mut self.cache,
            &bindings,
            &self.gpu.device,
            &mut encoder,
            1,
        );
        self.gpu.queue.submit(Some(encoder.finish()));

        self.beliefs_pos_dirty = true;
        self.beliefs_type_dirty = true;
        self.beliefs_tick_dirty = true;
        self.beliefs_confidence_dirty = true;
        self.beliefs_suspicion_dirty = true;
        self.beliefs_flags_dirty = true;
    }

    /// Wave 3 ToM Phase 3.8 — reveal verb. Multi-target dispatch:
    /// queues N synthetic `EffectRevealApplied` chronicle records
    /// (kind=66), one per (caster, observer) pair across all agent
    /// slots. The .sim-authored `physics_ApplyRevealBeliefUpdate`
    /// consumer fires once per record, each writing to its own
    /// observer cell.
    ///
    /// AOE-style fan-out: avoids a `for_each_agent` body shape in
    /// the DSL while still emitting all-observers reveal semantics
    /// with the same external behaviour as the retired hand-written
    /// `REVEAL_WGSL` (which used `workgroup_size(64)` × N threads).
    pub fn reveal(&mut self, caster: u32, subject: u32) {
        assert!(caster < self.agent_count);
        assert!(subject < self.agent_count);

        self.queue_clear_tail();

        // Multi-target dispatch — one chronicle record per observer
        // slot. Per cpu_chronicle_reference::Reveal:
        //   slot 2 = caster (a), slot 3 = target (= observer cell),
        //   slot 4 = subject_idx.
        for observer in 0..self.agent_count {
            let mut record = [0u32; CHRONICLE_STRIDE_U32];
            record[0] = KIND_REVEAL;
            record[1] = self.tick as u32;
            record[2] = caster;
            record[3] = observer;
            record[4] = subject;
            self.event_ring
                .append_chronicle_record(&self.gpu.queue, &record);
        }

        let cfg = physics_ApplyRevealBeliefUpdate::PhysicsApplyRevealBeliefUpdateCfg {
            event_count: self.agent_count,
            tick: self.tick as u32,
            seed: self.seed as u32,
            agent_cap: self.agent_count,
        };
        self.gpu.queue.write_buffer(
            &self.apply_reveal_cfg_buf,
            0,
            bytemuck::bytes_of(&cfg),
        );

        let mut encoder =
            self.gpu
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::reveal::encoder"),
                });
        let agent_buffers = AgentBuffers {
            alive_buf: Some(&self.agent_alive_buf),
            ..Default::default()
        };
        let ctx = KernelBindingsContext {
            state: &agent_buffers,
            event_ring: &self.event_ring,
            registry: &self.registry_gpu,
            voxel_grid: None,
            navgrid: None,
            navgrid_cfg: None,
        };
        let extras = physics_ApplyRevealBeliefUpdate::PhysicsApplyRevealBeliefUpdateExtras {
            beliefs_pos: &self.beliefs_pos_primary,
            beliefs_type: &self.beliefs_type_primary,
            beliefs_tick: &self.beliefs_tick_primary,
            beliefs_confidence: &self.beliefs_confidence_primary,
            beliefs_suspicion: &self.beliefs_suspicion_primary,
            beliefs_flags: &self.beliefs_flags_primary,
            cfg: &self.apply_reveal_cfg_buf,
        };
        let bindings =
            physics_ApplyRevealBeliefUpdate::PhysicsApplyRevealBeliefUpdateBindings::from_context_with_extras(
                &ctx, &extras,
            );
        dispatch::dispatch_physics_applyrevealbeliefupdate(
            &mut self.cache,
            &bindings,
            &self.gpu.device,
            &mut encoder,
            self.agent_count,
        );
        self.gpu.queue.submit(Some(encoder.finish()));

        self.beliefs_pos_dirty = true;
        self.beliefs_type_dirty = true;
        self.beliefs_tick_dirty = true;
        self.beliefs_confidence_dirty = true;
        self.beliefs_suspicion_dirty = true;
        self.beliefs_flags_dirty = true;
    }

    /// Wave 3 ToM Phase 4 — decoy verb. Queues a synthetic
    /// `EffectDecoyApplied` chronicle record (kind=68) into the unified
    /// `event_ring` and dispatches the .sim-authored
    /// `physics_ApplyDecoyBeliefUpdate` consumer kernel. The consumer
    /// unpacks `fake_pos` (= packed (x_q8, y_q8, z_q8, fake_type) quartet)
    /// and writes the 4 columns at `[target * N + subject_idx]`:
    /// `last_known_pos`, `last_known_creature_type`, `last_seen_tick`
    /// (= world.tick), `confidence` (= 255).
    ///
    /// `fake_pos` is the caller-packed u32: low byte = x_q8, then y_q8,
    /// z_q8, high byte = fake_type. The pin pre-packs simple non-negative
    /// test values (e.g. `(7 << 24) | (3 << 16) | (5 << 8) | 9` for
    /// pos=(9,5,3) + fake_type=7).
    pub fn decoy(&mut self, caster: u32, target: u32, subject_idx: u32, fake_pos: u32) {
        assert!(caster < self.agent_count);
        assert!(target < self.agent_count);
        assert!(subject_idx < self.agent_count);

        self.queue_clear_tail();

        // Chronicle record layout per `cpu_chronicle_reference::Decoy`:
        //   slot 2 = caster, slot 3 = target (OBSERVER),
        //   slot 4 = subject_idx, slot 5 = fake_pos.
        let mut record = [0u32; CHRONICLE_STRIDE_U32];
        record[0] = KIND_DECOY;
        record[1] = self.tick as u32;
        record[2] = caster;
        record[3] = target;
        record[4] = subject_idx;
        record[5] = fake_pos;
        self.event_ring
            .append_chronicle_record(&self.gpu.queue, &record);

        let cfg = physics_ApplyDecoyBeliefUpdate::PhysicsApplyDecoyBeliefUpdateCfg {
            event_count: 1,
            tick: self.tick as u32,
            seed: self.seed as u32,
            agent_cap: self.agent_count,
        };
        self.gpu.queue.write_buffer(
            &self.apply_decoy_cfg_buf,
            0,
            bytemuck::bytes_of(&cfg),
        );

        let mut encoder =
            self.gpu
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::decoy::encoder"),
                });
        let agent_buffers = AgentBuffers {
            alive_buf: Some(&self.agent_alive_buf),
            ..Default::default()
        };
        let ctx = KernelBindingsContext {
            state: &agent_buffers,
            event_ring: &self.event_ring,
            registry: &self.registry_gpu,
            voxel_grid: None,
            navgrid: None,
            navgrid_cfg: None,
        };
        let extras = physics_ApplyDecoyBeliefUpdate::PhysicsApplyDecoyBeliefUpdateExtras {
            beliefs_pos: &self.beliefs_pos_primary,
            beliefs_type: &self.beliefs_type_primary,
            beliefs_tick: &self.beliefs_tick_primary,
            beliefs_confidence: &self.beliefs_confidence_primary,
            cfg: &self.apply_decoy_cfg_buf,
        };
        let bindings =
            physics_ApplyDecoyBeliefUpdate::PhysicsApplyDecoyBeliefUpdateBindings::from_context_with_extras(
                &ctx, &extras,
            );
        dispatch::dispatch_physics_applydecoybeliefupdate(
            &mut self.cache,
            &bindings,
            &self.gpu.device,
            &mut encoder,
            1,
        );
        self.gpu.queue.submit(Some(encoder.finish()));

        self.beliefs_pos_dirty = true;
        self.beliefs_type_dirty = true;
        self.beliefs_tick_dirty = true;
        self.beliefs_confidence_dirty = true;
    }

    /// Wave 3 ToM Phase 4 — erase_belief verb. Queues a synthetic
    /// `EffectEraseBeliefApplied` chronicle record (kind=69) and
    /// dispatches the .sim-authored `physics_ApplyEraseBeliefUpdate`
    /// consumer. The consumer reads the `fields` u8 bitset and clears
    /// the matching cells of `[target * N + subject_idx]` (bit 0 = pos,
    /// 1 = type, 2 = tick, 3 = confidence, 4 = suspicion, 5 = flags).
    ///
    /// Wave 3 ToM Phase 5 — the compiler now fuses
    /// `physics_ApplyEraseBeliefUpdate` and `physics_ApplyDisguise` into
    /// a single kernel `physics_ApplyEraseBeliefUpdate_and_ApplyDisguise`
    /// (both `@phase(post)` PerEvent on the same ring). Each rule-arm is
    /// gated on its own event kind tag (67 vs 69), so dispatching with
    /// a single chronicle record fires only the matching arm.
    pub fn erase_belief(&mut self, caster: u32, target: u32, subject_idx: u32, fields: u8) {
        assert!(caster < self.agent_count);
        assert!(target < self.agent_count);
        assert!(subject_idx < self.agent_count);

        self.queue_clear_tail();

        let mut record = [0u32; CHRONICLE_STRIDE_U32];
        record[0] = KIND_ERASE_BELIEF;
        record[1] = self.tick as u32;
        record[2] = caster;
        record[3] = target;
        record[4] = subject_idx;
        record[5] = fields as u32;
        self.event_ring
            .append_chronicle_record(&self.gpu.queue, &record);

        let cfg = physics_ApplyEraseBeliefUpdate_and_ApplyDisguise::PhysicsApplyEraseBeliefUpdateAndApplyDisguiseCfg {
            event_count: 1,
            tick: self.tick as u32,
            seed: self.seed as u32,
            agent_cap: self.agent_count,
        };
        self.gpu.queue.write_buffer(
            &self.apply_erase_belief_cfg_buf,
            0,
            bytemuck::bytes_of(&cfg),
        );

        let mut encoder =
            self.gpu
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::erase_belief::encoder"),
                });
        let agent_buffers = AgentBuffers {
            alive_buf: Some(&self.agent_alive_buf),
            ..Default::default()
        };
        let ctx = KernelBindingsContext {
            state: &agent_buffers,
            event_ring: &self.event_ring,
            registry: &self.registry_gpu,
            voxel_grid: None,
            navgrid: None,
            navgrid_cfg: None,
        };
        let extras = physics_ApplyEraseBeliefUpdate_and_ApplyDisguise::PhysicsApplyEraseBeliefUpdateAndApplyDisguiseExtras {
            agent_disguise_expires_at_tick: &self.agent_disguise_expires_at_tick_buf,
            agent_disguise_fake_type: &self.agent_disguise_fake_type_buf,
            beliefs_pos: &self.beliefs_pos_primary,
            beliefs_type: &self.beliefs_type_primary,
            beliefs_tick: &self.beliefs_tick_primary,
            beliefs_confidence: &self.beliefs_confidence_primary,
            beliefs_suspicion: &self.beliefs_suspicion_primary,
            beliefs_flags: &self.beliefs_flags_primary,
            cfg: &self.apply_erase_belief_cfg_buf,
        };
        let bindings = physics_ApplyEraseBeliefUpdate_and_ApplyDisguise::PhysicsApplyEraseBeliefUpdateAndApplyDisguiseBindings::from_context_with_extras(
            &ctx, &extras,
        );
        dispatch::dispatch_physics_applyerasebeliefupdate_and_applydisguise(
            &mut self.cache,
            &bindings,
            &self.gpu.device,
            &mut encoder,
            1,
        );
        self.gpu.queue.submit(Some(encoder.finish()));

        self.beliefs_pos_dirty = true;
        self.beliefs_type_dirty = true;
        self.beliefs_tick_dirty = true;
        self.beliefs_confidence_dirty = true;
        self.beliefs_suspicion_dirty = true;
        self.beliefs_flags_dirty = true;
    }

    /// Wave 3 ToM Phase 5 — disguise verb. Queues a synthetic
    /// `EffectDisguiseApplied` chronicle record (kind=67) and dispatches
    /// the .sim-authored `physics_ApplyDisguise` consumer. The consumer
    /// decodes payload_a (= `(duration_ticks << 8) | fake_type`), then
    /// writes the per-agent `disguise_expires_at_tick` (=
    /// `world.tick + duration`) and `disguise_fake_type` (= low byte)
    /// SoA columns at slot `caster`.
    ///
    /// Subsequent observe calls consult these columns at consume-time
    /// and substitute `disguise_fake_type` for the true `creature_type`
    /// when the disguise window is still active.
    pub fn disguise(&mut self, caster: u32, fake_type: u8, duration_ticks: u32) {
        assert!(caster < self.agent_count);
        // Pack the payload exactly as the GPU dispatcher does for kind 36
        // (see `cg::emit::wgsl_body` Disguise arm).
        let payload_a = (duration_ticks << 8) | (fake_type as u32);

        self.queue_clear_tail();

        let mut record = [0u32; CHRONICLE_STRIDE_U32];
        record[0] = KIND_DISGUISE;
        record[1] = self.tick as u32;
        record[2] = caster;
        record[3] = caster; // implicit-target rule: target = caster for self-cast
        record[4] = payload_a;
        self.event_ring
            .append_chronicle_record(&self.gpu.queue, &record);

        let cfg = physics_ApplyEraseBeliefUpdate_and_ApplyDisguise::PhysicsApplyEraseBeliefUpdateAndApplyDisguiseCfg {
            event_count: 1,
            tick: self.tick as u32,
            seed: self.seed as u32,
            agent_cap: self.agent_count,
        };
        self.gpu.queue.write_buffer(
            &self.apply_disguise_cfg_buf,
            0,
            bytemuck::bytes_of(&cfg),
        );

        let mut encoder =
            self.gpu
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::disguise::encoder"),
                });
        let agent_buffers = AgentBuffers {
            alive_buf: Some(&self.agent_alive_buf),
            ..Default::default()
        };
        let ctx = KernelBindingsContext {
            state: &agent_buffers,
            event_ring: &self.event_ring,
            registry: &self.registry_gpu,
            voxel_grid: None,
            navgrid: None,
            navgrid_cfg: None,
        };
        let extras = physics_ApplyEraseBeliefUpdate_and_ApplyDisguise::PhysicsApplyEraseBeliefUpdateAndApplyDisguiseExtras {
            agent_disguise_expires_at_tick: &self.agent_disguise_expires_at_tick_buf,
            agent_disguise_fake_type: &self.agent_disguise_fake_type_buf,
            beliefs_pos: &self.beliefs_pos_primary,
            beliefs_type: &self.beliefs_type_primary,
            beliefs_tick: &self.beliefs_tick_primary,
            beliefs_confidence: &self.beliefs_confidence_primary,
            beliefs_suspicion: &self.beliefs_suspicion_primary,
            beliefs_flags: &self.beliefs_flags_primary,
            cfg: &self.apply_disguise_cfg_buf,
        };
        let bindings = physics_ApplyEraseBeliefUpdate_and_ApplyDisguise::PhysicsApplyEraseBeliefUpdateAndApplyDisguiseBindings::from_context_with_extras(
            &ctx, &extras,
        );
        dispatch::dispatch_physics_applyerasebeliefupdate_and_applydisguise(
            &mut self.cache,
            &bindings,
            &self.gpu.device,
            &mut encoder,
            1,
        );
        self.gpu.queue.submit(Some(encoder.finish()));

        self.agent_disguise_expires_at_tick_dirty = true;
        self.agent_disguise_fake_type_dirty = true;
    }

    /// Read the agent SoA `disguise_expires_at_tick` column.
    pub fn agent_disguise_expires_at_tick(&mut self) -> &[u32] {
        if self.agent_disguise_expires_at_tick_dirty {
            let bytes = (self.agent_disguise_expires_at_tick_cache.len() as u64) * 4;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::agent_disguise_expires::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.agent_disguise_expires_at_tick_buf,
                0,
                &self.agent_disguise_expires_at_tick_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.agent_disguise_expires_at_tick_staging.slice(..bytes);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            let raw: &[u32] = bytemuck::cast_slice(&mapped);
            self.agent_disguise_expires_at_tick_cache.copy_from_slice(raw);
            drop(mapped);
            self.agent_disguise_expires_at_tick_staging.unmap();
            self.agent_disguise_expires_at_tick_dirty = false;
        }
        &self.agent_disguise_expires_at_tick_cache
    }

    /// Read the agent SoA `disguise_fake_type` column.
    pub fn agent_disguise_fake_type(&mut self) -> &[u32] {
        if self.agent_disguise_fake_type_dirty {
            let bytes = (self.agent_disguise_fake_type_cache.len() as u64) * 4;
            let mut encoder = self.gpu.device.create_command_encoder(
                &wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::agent_disguise_fake_type::readback"),
                },
            );
            encoder.copy_buffer_to_buffer(
                &self.agent_disguise_fake_type_buf,
                0,
                &self.agent_disguise_fake_type_staging,
                0,
                bytes,
            );
            self.gpu.queue.submit(Some(encoder.finish()));
            let slice = self.agent_disguise_fake_type_staging.slice(..bytes);
            slice.map_async(wgpu::MapMode::Read, |_| {});
            self.gpu.device.poll(wgpu::PollType::Wait).expect("poll");
            let mapped = slice.get_mapped_range();
            let raw: &[u32] = bytemuck::cast_slice(&mapped);
            self.agent_disguise_fake_type_cache.copy_from_slice(raw);
            drop(mapped);
            self.agent_disguise_fake_type_staging.unmap();
            self.agent_disguise_fake_type_dirty = false;
        }
        &self.agent_disguise_fake_type_cache
    }

    /// Wave 3 ToM Phase 3.8 — per-tick decay. Compiler-generated WGSL
    /// (see `dsl_compiler::belief_decay_wgsl::decay_kernel_wgsl`).
    /// Replaces the retired hand-written `DECAY_WGSL` const.
    pub fn decay_step(&mut self) {
        let cfg = DecayCfg {
            observer: 0,
            target_or_subject: 0,
            subject: 0,
            agent_count: self.agent_count,
            tick: self.tick as u32,
            cell_count: self.cell_count(),
            _pad0: 0,
            _pad1: 0,
        };
        self.gpu
            .queue
            .write_buffer(&self.decay_gpu.cfg_buf, 0, bytemuck::bytes_of(&cfg));

        let bg = self
            .gpu
            .device
            .create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("tom_probe_runtime::decay::bg"),
                layout: &self.decay_gpu.bgl,
                entries: &[
                    wgpu::BindGroupEntry {
                        binding: 0,
                        resource: self.decay_gpu.cfg_buf.as_entire_binding(),
                    },
                    wgpu::BindGroupEntry {
                        binding: 1,
                        resource: self.beliefs_confidence_primary.as_entire_binding(),
                    },
                    wgpu::BindGroupEntry {
                        binding: 2,
                        resource: self.beliefs_tick_primary.as_entire_binding(),
                    },
                ],
            });

        let mut encoder =
            self.gpu
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("tom_probe_runtime::decay::encoder"),
                });
        {
            let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("tom_probe_runtime::decay::pass"),
                timestamp_writes: None,
            });
            pass.set_pipeline(&self.decay_gpu.pipeline);
            pass.set_bind_group(0, &bg, &[]);
            let word_count = self.cell_count().div_ceil(4);
            let workgroups = word_count.div_ceil(64).max(1);
            pass.dispatch_workgroups(workgroups, 1, 1);
        }
        self.gpu.queue.submit(Some(encoder.finish()));

        self.beliefs_confidence_dirty = true;
    }

    /// Helper: queue a `event_tail = 0` write so the next chronicle
    /// append lands at slot 0. Resets both the GPU-side counter and
    /// the host-side estimate so subsequent
    /// `EventRing::append_chronicle_record` calls see slot 0.
    fn queue_clear_tail(&mut self) {
        let zero = 0u32;
        self.gpu
            .queue
            .write_buffer(self.event_ring.tail(), 0, bytemuck::bytes_of(&zero));
        self.event_ring.reset_tail_estimate();
    }

    pub fn agent_count(&self) -> u32 {
        self.agent_count
    }

    pub fn tick(&self) -> u64 {
        self.tick
    }

    pub fn seed(&self) -> u64 {
        self.seed
    }
}

impl CompiledSim for TomProbeState {
    fn step(&mut self) {
        let mut encoder = self.gpu.device.create_command_encoder(
            &wgpu::CommandEncoderDescriptor {
                label: Some("tom_probe_runtime::step"),
            },
        );

        // (1) Per-tick clear of event_tail.
        self.event_ring.clear_tail_in(&mut encoder);

        // (2) physics_WhatIBelieve — emits one BeliefAcquired/agent.
        let physics_cfg = physics_WhatIBelieve::PhysicsWhatIBelieveCfg {
            agent_cap: self.agent_count,
            tick: self.tick as u32,
            seed: 0,
            _pad: 0,
        };
        self.gpu.queue.write_buffer(
            &self.physics_cfg_buf,
            0,
            bytemuck::bytes_of(&physics_cfg),
        );
        // The physics_bindings/`ctx` are constructed in a fresh scope
        // so `ctx`'s immutable borrow of `self.event_ring` ends before
        // `self.event_ring.note_emits()` (mutable borrow) below.
        {
            let agent_buffers = AgentBuffers {
                alive_buf: Some(&self.agent_alive_buf),
                ..Default::default()
            };
            let ctx = KernelBindingsContext {
                state: &agent_buffers,
                event_ring: &self.event_ring,
                registry: &self.registry_gpu,
                voxel_grid: None,
                navgrid: None,
                navgrid_cfg: None,
            };
            let physics_extras = physics_WhatIBelieve::PhysicsWhatIBelieveExtras {
                cfg: &self.physics_cfg_buf,
            };
            let physics_bindings =
                physics_WhatIBelieve::PhysicsWhatIBelieveBindings::from_context_with_extras(
                    &ctx, &physics_extras,
                );
            dispatch::dispatch_physics_whatibelieve(
                &mut self.cache,
                &physics_bindings,
                &self.gpu.device,
                &mut encoder,
                self.agent_count,
            );
        }
        self.event_ring.note_emits(self.agent_count);

        // (3) fold_beliefs_flags — folds BeliefAcquired into flags.
        let event_count_estimate = self.agent_count;
        let fold_cfg = fold_beliefs_flags::FoldBeliefsFlagsCfg {
            event_count: event_count_estimate,
            tick: self.tick as u32,
            second_key_pop: self.agent_count,
            agent_cap: 0,
        };
        self.gpu.queue.write_buffer(
            &self.fold_cfg_buf,
            0,
            bytemuck::bytes_of(&fold_cfg),
        );
        let fold_bindings = fold_beliefs_flags::FoldBeliefsFlagsBindings {
            event_ring: self.event_ring.ring(),
            event_tail: self.event_ring.tail(),
            view_storage_primary: &self.beliefs_flags_primary,
            view_storage_anchor: None,
            view_storage_ids: None,
            sim_cfg: self.event_ring.sim_cfg(),
            cfg: &self.fold_cfg_buf,
        };
        dispatch::dispatch_fold_beliefs_flags(
            &mut self.cache,
            &fold_bindings,
            &self.gpu.device,
            &mut encoder,
            event_count_estimate.max(1),
        );

        // (4) Wave 3 ToM Phase 3.8 — observe / scry / reveal consumers.
        // The schedule lists them but during a normal step() the ring
        // carries only kind=1 BeliefAcquired records, so the kind
        // filters in each consumer reject every slot. Dispatching with
        // event_count = 0 is the cheapest way to skip the kernel — the
        // entry-point's `if (event_idx >= cfg.event_count) { return; }`
        // guard fires on every thread. Per-step the consumers do
        // nothing; per-`observe()` / `::scry()` / `::reveal()` call
        // the runtime synchronously dispatches them outside this
        // step() encoder with `event_count = 1` (or N for reveal).
        // The schedule entries here keep the kernels in the kernel
        // cache (init-once) and pin them to the per-step submission
        // order; passing `event_count = 0` makes them no-ops.
        let zero_cfg = physics_ApplyObserveBeliefUpdate::PhysicsApplyObserveBeliefUpdateCfg {
            event_count: 0,
            tick: self.tick as u32,
            seed: 0,
            agent_cap: self.agent_count,
        };
        self.gpu.queue.write_buffer(
            &self.apply_observe_cfg_buf,
            0,
            bytemuck::bytes_of(&zero_cfg),
        );
        self.gpu.queue.write_buffer(
            &self.apply_scry_cfg_buf,
            0,
            bytemuck::bytes_of(&zero_cfg),
        );
        self.gpu.queue.write_buffer(
            &self.apply_reveal_cfg_buf,
            0,
            bytemuck::bytes_of(&zero_cfg),
        );
        // Wave 3 ToM Phase 4 — same zero-event_count gate for the new
        // deception consumers. The struct shape is identical (Cfg has
        // 4 u32 words: event_count, tick, seed, agent_cap), so the same
        // bytes_of works for all 5 consumers.
        self.gpu.queue.write_buffer(
            &self.apply_decoy_cfg_buf,
            0,
            bytemuck::bytes_of(&zero_cfg),
        );
        self.gpu.queue.write_buffer(
            &self.apply_erase_belief_cfg_buf,
            0,
            bytemuck::bytes_of(&zero_cfg),
        );
        // Wave 3 ToM Phase 5 — same zero-event_count gate for the
        // disguise consumer.
        self.gpu.queue.write_buffer(
            &self.apply_disguise_cfg_buf,
            0,
            bytemuck::bytes_of(&zero_cfg),
        );

        self.gpu.queue.submit(Some(encoder.finish()));
        self.beliefs_flags_dirty = true;
        self.beliefs_tick_dirty = true;
        self.tick += 1;
    }

    fn agent_count(&self) -> u32 {
        self.agent_count
    }

    fn tick(&self) -> u64 {
        self.tick
    }

    fn positions(&mut self) -> &[Vec3] {
        &[]
    }
}

pub fn make_sim(seed: u64, agent_count: u32) -> Box<dyn CompiledSim> {
    Box::new(TomProbeState::new(seed, agent_count))
}
