// GENERATED by dsl_compiler. Do not edit by hand.
@group(0) @binding(0) var<storage, read> source_ring: array<u32>;
@group(0) @binding(1) var<storage, read> source_tail: array<u32>;
@group(0) @binding(2) var<storage, read_write> batch_ring: array<u32>;
@group(0) @binding(3) var<storage, read_write> batch_tail: atomic<u32>;
struct AppendEventsCfg { source_capacity: u32, batch_capacity: u32, _pad0: u32, _pad1: u32 };
@group(0) @binding(4) var<uniform> cfg: AppendEventsCfg;
@compute @workgroup_size(64)
fn cs_append_events(@builtin(global_invocation_id) gid: vec3<u32>) {
// Stub body: touch every binding so naga keeps them live.
let _sr = source_ring[0];
let _st = source_tail[0];
let _br = batch_ring[0];
let _bt = atomicLoad(&batch_tail);
let _c = cfg.source_capacity;
}
