// GENERATED by dsl_compiler — do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.
//!
//! Per-kernel cache + dispatch driver. Replaces the hand-written
//! `DispatchOp::Kernel(KernelId::X) => dispatch_kernel!(...)` block
//! in engine_gpu so the dispatch table can never drift from `KernelId`.

use wgpu::util::DeviceExt as _;

/// Lazy-initialised kernel cache. One slot per emitted kernel;
/// populated on first dispatch via `<Kernel>::new(device)`.
#[derive(Default)]
pub struct KernelCache {
    pub mask_hold: Option<crate::mask_Hold::MaskHoldKernel>,
    pub mask_movetoward: Option<crate::mask_MoveToward::MaskMoveTowardKernel>,
    pub fused_mask_flee: Option<crate::fused_mask_Flee::FusedMaskFleeKernel>,
    pub fold_threat_level: Option<crate::fold_threat_level::FoldThreatLevelKernel>,
    pub fold_engaged_with: Option<crate::fold_engaged_with::FoldEngagedWithKernel>,
    pub fold_my_enemies: Option<crate::fold_my_enemies::FoldMyEnemiesKernel>,
    pub fold_kin_fear: Option<crate::fold_kin_fear::FoldKinFearKernel>,
    pub fold_pack_focus: Option<crate::fold_pack_focus::FoldPackFocusKernel>,
    pub fold_rally_boost: Option<crate::fold_rally_boost::FoldRallyBoostKernel>,
    pub fold_memory: Option<crate::fold_memory::FoldMemoryKernel>,
    pub fused_spatial_build_hash: Option<crate::fused_spatial_build_hash::FusedSpatialBuildHashKernel>,
    pub upload_sim_cfg: Option<crate::upload_sim_cfg::UploadSimCfgKernel>,
    pub pack_agents: Option<crate::pack_agents::PackAgentsKernel>,
    pub seed_indirect_0: Option<crate::seed_indirect_0::SeedIndirect0Kernel>,
    pub unpack_agents: Option<crate::unpack_agents::UnpackAgentsKernel>,
    pub kick_snapshot: Option<crate::kick_snapshot::KickSnapshotKernel>,
}

/// Dispatch one [`crate::schedule::DispatchOp`] against the kernel
/// cache. Lazy-inits the kernel on first reach, builds the cfg
/// uniform buffer, binds, and records into `encoder`.
pub fn dispatch_by_id(
    op: &crate::schedule::DispatchOp,
    cache: &mut KernelCache,
    sources: &crate::binding_sources::BindingSources<'_>,
    encoder: &mut wgpu::CommandEncoder,
    device: &wgpu::Device,
    state: &engine::state::SimState,
) {
    use crate::Kernel;
    use crate::KernelId;
    use crate::schedule::DispatchOp;
    let agent_cap = state.agent_cap();
    match op {
        DispatchOp::Kernel(KernelId::MaskHold) => {
            let kernel = cache.mask_hold.get_or_insert_with(|| <crate::mask_Hold::MaskHoldKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::mask_Hold::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::MaskMoveToward) => {
            let kernel = cache.mask_movetoward.get_or_insert_with(|| <crate::mask_MoveToward::MaskMoveTowardKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::mask_MoveToward::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FusedMaskFlee) => {
            let kernel = cache.fused_mask_flee.get_or_insert_with(|| <crate::fused_mask_Flee::FusedMaskFleeKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fused_mask_Flee::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FoldThreatLevel) => {
            let kernel = cache.fold_threat_level.get_or_insert_with(|| <crate::fold_threat_level::FoldThreatLevelKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fold_threat_level::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FoldEngagedWith) => {
            let kernel = cache.fold_engaged_with.get_or_insert_with(|| <crate::fold_engaged_with::FoldEngagedWithKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fold_engaged_with::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FoldMyEnemies) => {
            let kernel = cache.fold_my_enemies.get_or_insert_with(|| <crate::fold_my_enemies::FoldMyEnemiesKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fold_my_enemies::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FoldKinFear) => {
            let kernel = cache.fold_kin_fear.get_or_insert_with(|| <crate::fold_kin_fear::FoldKinFearKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fold_kin_fear::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FoldPackFocus) => {
            let kernel = cache.fold_pack_focus.get_or_insert_with(|| <crate::fold_pack_focus::FoldPackFocusKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fold_pack_focus::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FoldRallyBoost) => {
            let kernel = cache.fold_rally_boost.get_or_insert_with(|| <crate::fold_rally_boost::FoldRallyBoostKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fold_rally_boost::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FoldMemory) => {
            let kernel = cache.fold_memory.get_or_insert_with(|| <crate::fold_memory::FoldMemoryKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fold_memory::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::FusedSpatialBuildHash) => {
            let kernel = cache.fused_spatial_build_hash.get_or_insert_with(|| <crate::fused_spatial_build_hash::FusedSpatialBuildHashKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::fused_spatial_build_hash::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::UploadSimCfg) => {
            let kernel = cache.upload_sim_cfg.get_or_insert_with(|| <crate::upload_sim_cfg::UploadSimCfgKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::upload_sim_cfg::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::PackAgents) => {
            let kernel = cache.pack_agents.get_or_insert_with(|| <crate::pack_agents::PackAgentsKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::pack_agents::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::SeedIndirect0) => {
            let kernel = cache.seed_indirect_0.get_or_insert_with(|| <crate::seed_indirect_0::SeedIndirect0Kernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::seed_indirect_0::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::UnpackAgents) => {
            let kernel = cache.unpack_agents.get_or_insert_with(|| <crate::unpack_agents::UnpackAgentsKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::unpack_agents::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::Kernel(KernelId::KickSnapshot) => {
            let kernel = cache.kick_snapshot.get_or_insert_with(|| <crate::kick_snapshot::KickSnapshotKernel as Kernel>::new(device));
            let cfg = kernel.build_cfg(state);
            let cfg_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("crate::kick_snapshot::cfg"),
                contents: bytemuck::cast_slice(&[cfg]),
                usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            });
            let bindings = kernel.bind(sources, &cfg_buf);
            kernel.record(device, encoder, &bindings, agent_cap);
        }
        DispatchOp::FixedPoint { kernel: other, .. } => {
            unreachable!("FixedPoint {other:?} not currently emitted by SCHEDULE")
        }
        DispatchOp::Indirect { kernel: other, .. } => {
            unreachable!("Indirect {other:?} not currently emitted by SCHEDULE")
        }
        DispatchOp::GatedBy { kernel: other, .. } => {
            unreachable!("GatedBy {other:?} not currently emitted by SCHEDULE")
        }
    }
}
