// GENERATED by dsl_compiler::emit_view_wgsl. Do not edit by hand.
// WGSL fold kernel for @materialized view `memory` — storage = per_entity_ring(K = 64).
// Companion to the CPU emitter in emit_view::emit_per_entity_ring_struct;
// layout must match byte-for-byte so a fold that runs on CPU reproduces on GPU.
//
// Concurrency: naturally race-safe. `atomicAdd` on cursors[owner] serialises
// all writers to the same row; each writer's returned counter modulo K is
// its exclusive slot. No CAS loop, no linear scan, no eviction tiebreak —
// the ring's FIFO semantics fall out of the monotonic cursor.

// Slot count per owner — the `K` from per_entity_ring(K = 64).
const K: u32 = 64u;

// Per-ring slot — mirrors the Rust `MemoryEntry` struct (12B payload + 4B pad → 16B).
// `source == 0u` marks an empty slot (AgentIds are 1-based, so 0 is unused).
struct MemoryEntry {
    source:      u32,
    value:       f32,
    anchor_tick: u32,
    _pad:        u32,
}

// Dispatch-level uniform: event count + current tick. The event buffer layout
// comes from the DSL event struct; engine_gpu packs it into `events[]` below.
struct FoldCfg {
    num_events: u32,
    tick:       u32,
    agent_cap:  u32,
    _pad:       u32,
}

// Bindings — engine_gpu owns the bind-group layout; these numbers are the
// dedicated per-entity-ring slot (kept disjoint from pair_map / slot_map /
// symmetric_pair_topk). Rings is the flattened `agent_cap * K` entry array;
// cursors is the monotonic write-cursor per owner.
@group(0) @binding(0) var<storage, read_write> view_memory_rings:   array<MemoryEntry>;
@group(0) @binding(1) var<storage, read_write> view_memory_cursors: array<atomic<u32>>;

// Event-carrier struct for `RecordMemory` → `memory` fold.
// engine_gpu packs the event's `observer` / `source` AgentIds (raw u32s)
// plus the `delta` payload into this struct for each pending event.
struct RecordMemoryFold {
    owner:  u32,
    source: u32,
    delta:  f32,
    _pad:   u32,
}

@group(0) @binding(2) var<storage, read>  events_record_memory: array<RecordMemoryFold>;
@group(0) @binding(3) var<uniform>         cfg_record_memory:   FoldCfg;

// Fold `RecordMemory` events into view `memory`. One thread per event;
// atomicAdd on the owner's cursor gives each writer a unique slot index.
@compute @workgroup_size(64)
fn cs_fold_memory(@builtin(global_invocation_id) gid: vec3<u32>) {
    let event_idx = gid.x;
    if (event_idx >= cfg_record_memory.num_events) { return; }
    let e = events_record_memory[event_idx];

    // AgentIds are 1-based; raw id 0 means "unassigned" and can't own a ring.
    if (e.owner == 0u) { return; }
    let owner_slot = e.owner - 1u;
    if (owner_slot >= cfg_record_memory.agent_cap) { return; }
    let row_base = owner_slot * K;

    // Reserve a slot: atomicAdd returns the pre-increment cursor, giving this
    // invocation an exclusive write index. Overflow wraps modulo K (FIFO evict).
    let cursor = atomicAdd(&view_memory_cursors[owner_slot], 1u);
    let slot_idx = cursor % K;
    let write_idx = row_base + slot_idx;

    // Project the event into an entry. Matches CPU emit's Phase-1 shape:
    //   source = event's non-owner AgentId (raw), value = 1.0, anchor_tick = tick.
    // Richer projections (e.g. RecordMemory's `fact` / `confidence`) land in Phase 4.
    view_memory_rings[write_idx].source      = e.source;
    view_memory_rings[write_idx].value       = 1.0;
    view_memory_rings[write_idx].anchor_tick = cfg_record_memory.tick;
}

