// GENERATED by dsl_compiler — do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

use crate::binding_sources::BindingSources;

pub struct FusedMaskFleeKernel {
    pipeline: wgpu::ComputePipeline,
    bgl: wgpu::BindGroupLayout,
}

pub struct FusedMaskFleeBindings<'a> {
    pub agent_alive: &'a wgpu::Buffer,
    pub mask_2_bitmap: &'a wgpu::Buffer,
    pub mask_3_bitmap: &'a wgpu::Buffer,
    pub mask_4_bitmap: &'a wgpu::Buffer,
    pub mask_5_bitmap: &'a wgpu::Buffer,
    pub cfg: &'a wgpu::Buffer,
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct FusedMaskFleeCfg { pub agent_cap: u32, pub _pad: [u32; 3] }

const SHADER_SRC: &str = include_str!("fused_mask_Flee.wgsl");

impl crate::Kernel for FusedMaskFleeKernel {
    type Bindings<'a> = FusedMaskFleeBindings<'a>;
    type Cfg = FusedMaskFleeCfg;

    fn new(device: &wgpu::Device) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("engine_gpu_rules::fused_mask_Flee::wgsl"),
            source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),
        });
        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("engine_gpu_rules::fused_mask_Flee::bgl"),
            entries: &[
                crate::bgl_storage(0, true), // agent_alive
                crate::bgl_storage(1, false), // mask_2_bitmap
                crate::bgl_storage(2, false), // mask_3_bitmap
                crate::bgl_storage(3, false), // mask_4_bitmap
                crate::bgl_storage(4, false), // mask_5_bitmap
                crate::bgl_uniform(5), // cfg
            ],
        });
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("engine_gpu_rules::fused_mask_Flee::pl"),
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("engine_gpu_rules::fused_mask_Flee::pipeline"),
            layout: Some(&pl),
            module: &shader,
            entry_point: Some("cs_fused_mask_Flee"),
            compilation_options: Default::default(),
            cache: None,
        });
        Self { pipeline, bgl }
    }

    fn build_cfg(&self, state: &engine::state::SimState) -> FusedMaskFleeCfg {
        let _ = state;
        FusedMaskFleeCfg { agent_cap: state.agent_cap(), _pad: [0; 3] }
    }

    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> FusedMaskFleeBindings<'a> {
        let _ = sources;
        FusedMaskFleeBindings {
            agent_alive: sources.external.agents,
            mask_2_bitmap: sources.transient.mask_bitmaps,
            mask_3_bitmap: sources.transient.mask_bitmaps,
            mask_4_bitmap: sources.transient.mask_bitmaps,
            mask_5_bitmap: sources.transient.mask_bitmaps,
            cfg: cfg,
        }
    }

    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &FusedMaskFleeBindings<'_>, agent_cap: u32) {
        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("engine_gpu_rules::fused_mask_Flee::bg"),
            layout: &self.bgl,
            entries: &[
                wgpu::BindGroupEntry { binding: 0, resource: bindings.agent_alive.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.mask_2_bitmap.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 2, resource: bindings.mask_3_bitmap.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 3, resource: bindings.mask_4_bitmap.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 4, resource: bindings.mask_5_bitmap.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 5, resource: bindings.cfg.as_entire_binding() },
            ],
        });
        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some("engine_gpu_rules::fused_mask_Flee::pass"),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.pipeline);
        pass.set_bind_group(0, &bg, &[]);
        pass.dispatch_workgroups((agent_cap + 63u32) / 64u32, 1, 1);
    }
}

pub fn fused_mask_Flee_bgl_entries() -> Vec<wgpu::BindGroupLayoutEntry> {
    vec![
                crate::bgl_storage(0, true), // agent_alive
                crate::bgl_storage(1, false), // mask_2_bitmap
                crate::bgl_storage(2, false), // mask_3_bitmap
                crate::bgl_storage(3, false), // mask_4_bitmap
                crate::bgl_storage(4, false), // mask_5_bitmap
                crate::bgl_uniform(5), // cfg
    ]
}

pub fn fused_mask_Flee_bind_group_entries<'a>(
    bindings: &'a FusedMaskFleeBindings<'a>,
) -> Vec<wgpu::BindGroupEntry<'a>> {
    vec![
                wgpu::BindGroupEntry { binding: 0, resource: bindings.agent_alive.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.mask_2_bitmap.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 2, resource: bindings.mask_3_bitmap.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 3, resource: bindings.mask_4_bitmap.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 4, resource: bindings.mask_5_bitmap.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 5, resource: bindings.cfg.as_entire_binding() },
    ]
}

pub fn fused_mask_Flee_build_cfg(state: &engine::state::SimState) -> FusedMaskFleeCfg {
    FusedMaskFleeCfg { agent_cap: state.agent_cap(), _pad: [0; 3] }
}
