// GENERATED by dsl_compiler::emit_mask_wgsl. Do not edit by hand.
// GENERATED by dsl_compiler::emit_masks_wgsl_fused_v2.
// 4-slot BGL matching emit_mask_kernel::emit_fused_mask_rs.
// Stub body — per-mask logic pending follow-up.

@group(0) @binding(0) var<storage, read>       agents:       array<u32>;
@group(0) @binding(1) var<storage, read_write> mask_bitmaps: array<atomic<u32>>;
@group(0) @binding(2) var<storage, read>       sim_cfg:      array<u32>;
struct FusedMaskCfg { agent_cap: u32, num_mask_words: u32, _pad0: u32, _pad1: u32 };
@group(0) @binding(3) var<uniform>             cfg:          FusedMaskCfg;

@compute @workgroup_size(64)
fn cs_fused_masks(@builtin(global_invocation_id) gid: vec3<u32>) {
    if (gid.x >= cfg.agent_cap) { return; }
    // Touch every binding so naga keeps slots live.
    let _a = agents[0];
    let _s = sim_cfg[0];
    let _w = cfg.num_mask_words;
    // Stub: write a 0-or-keep into mask_bitmaps[0] via atomicOr(0).
    let _x = atomicOr(&mask_bitmaps[0], 0u);
}
