// GENERATED by dsl_compiler. Do not edit by hand.
@group(0) @binding(0) var<storage, read> agents_input: array<u32>;
@group(0) @binding(1) var<storage, read_write> mask_soa: array<u32>;
@group(0) @binding(2) var<storage, read_write> agent_data: array<u32>;
struct FusedAgentUnpackCfg { agent_cap: u32, radius_q: f32, _pad0: u32, _pad1: u32 };
@group(0) @binding(3) var<uniform> cfg: FusedAgentUnpackCfg;
@compute @workgroup_size(64)
fn cs_fused_agent_unpack(@builtin(global_invocation_id) gid: vec3<u32>) {
// Stub body: touch every binding so naga keeps them live.
let _ai = agents_input[0];
let _ms = mask_soa[0];
let _ad = agent_data[0];
let _c = cfg.agent_cap;
}
