// GENERATED by dsl_compiler — do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

struct MaskHoldCfg { agent_cap: u32, _pad0: u32, _pad1: u32, _pad2: u32 };

@group(0) @binding(0) var<storage, read> agent_alive: array<u32>;
@group(0) @binding(1) var<storage, read_write> mask_0_bitmap: array<atomic<u32>>;
@group(0) @binding(2) var<uniform> cfg: MaskHoldCfg;

@compute @workgroup_size(64)
fn cs_mask_Hold(@builtin(global_invocation_id) gid: vec3<u32>) {
let agent_id = gid.x;
if (agent_id >= cfg.agent_cap) { return; }

// op#0 (mask_predicate)
let mask_0_value: bool = false;
if (mask_0_value) {
    let mask_0_word = agent_id >> 5u;
    let mask_0_bit  = 1u << (agent_id & 31u);
    atomicOr(&mask_0_bitmap[mask_0_word], mask_0_bit);
}
}
