// GENERATED by dsl_compiler::emit_movement_wgsl. Do not edit by hand.
// Runtime-prelude consts (Stream B prelude module).
const EVENT_RING_CAP: u32 = 65536u;
const EVENT_RING_PAYLOAD_WORDS: u32 = 8u;
const RECORD_U32_STRIDE: u32 = 10u;

@group(0) @binding(0) var<storage, read_write> agents:             array<u32>;
@group(0) @binding(1) var<storage, read>       scoring:            array<u32>;
@group(0) @binding(2) var<storage, read_write> event_ring_records: array<u32>;
@group(0) @binding(3) var<storage, read_write> event_ring_tail:    atomic<u32>;
@group(0) @binding(4) var<storage, read>       sim_cfg:            array<u32>;
struct MovementCfg { agent_cap: u32, tick: u32, event_ring_capacity: u32, _pad: u32 };
@group(0) @binding(5) var<uniform>             cfg:                MovementCfg;

// GpuAgentSlot stride (16 u32 = 64 bytes per agent).
const SLOT_STRIDE_U32: u32 = 16u;
const SLOT_OFFSET_ALIVE: u32 = 4u;
const SLOT_OFFSET_POS_X: u32 = 11u;
const SLOT_OFFSET_POS_Y: u32 = 12u;
const SLOT_OFFSET_POS_Z: u32 = 13u;

// ScoreOutput stride (4 u32 = 16 bytes per agent).
const SCORING_STRIDE_U32: u32 = 4u;
const SCORING_OFFSET_ACTION: u32 = 0u;
const SCORING_OFFSET_TARGET: u32 = 1u;

// SimCfg field offsets (in u32 indices).
const SIM_CFG_OFFSET_TICK: u32 = 0u;
const SIM_CFG_OFFSET_MOVE_SPEED: u32 = 7u;

// Action ids (mirror engine action enum).
const ACTION_MOVE_TOWARD: u32 = 1u;
const ACTION_FLEE: u32 = 2u;
const NO_TARGET: u32 = 0xFFFFFFFFu;

fn agent_alive(slot: u32) -> u32 {
return agents[slot * SLOT_STRIDE_U32 + SLOT_OFFSET_ALIVE];
}

fn agent_pos(slot: u32) -> vec3<f32> {
let base = slot * SLOT_STRIDE_U32;
return vec3<f32>(
bitcast<f32>(agents[base + SLOT_OFFSET_POS_X]),
bitcast<f32>(agents[base + SLOT_OFFSET_POS_Y]),
bitcast<f32>(agents[base + SLOT_OFFSET_POS_Z]),
);
}

fn set_agent_pos(slot: u32, p: vec3<f32>) {
let base = slot * SLOT_STRIDE_U32;
agents[base + SLOT_OFFSET_POS_X] = bitcast<u32>(p.x);
agents[base + SLOT_OFFSET_POS_Y] = bitcast<u32>(p.y);
agents[base + SLOT_OFFSET_POS_Z] = bitcast<u32>(p.z);
}

fn scoring_action(slot: u32) -> u32 {
return scoring[slot * SCORING_STRIDE_U32 + SCORING_OFFSET_ACTION];
}

fn scoring_target(slot: u32) -> u32 {
return scoring[slot * SCORING_STRIDE_U32 + SCORING_OFFSET_TARGET];
}

fn sim_cfg_tick() -> u32 {
return sim_cfg[SIM_CFG_OFFSET_TICK];
}

fn sim_cfg_move_speed() -> f32 {
return bitcast<f32>(sim_cfg[SIM_CFG_OFFSET_MOVE_SPEED]);
}

fn normalize_or_zero(v: vec3<f32>) -> vec3<f32> {
let len2 = v.x * v.x + v.y * v.y + v.z * v.z;
if (len2 <= 0.0) { return vec3<f32>(0.0, 0.0, 0.0); }
let inv = 1.0 / sqrt(len2);
return v * inv;
}

// Runtime-prelude body (Stream B prelude module).
//
// Every per-kind helper packs typed args into the fixed 10-word
// EventRecord layout the CPU drain expects:
//   [0]      kind
//   [1]      tick
//   [2..10]  payload[0..8]
//
// Returns the slot index the record landed in, or 0xFFFFFFFFu on
// overflow. Silent drop on full ring — the CPU drain sees tail > cap
// and flips the overflow flag. We deliberately don't retry / spin
// because that would serialise emitters.

fn gpu_emit_event(kind: u32, tick: u32,
p0: u32, p1: u32, p2: u32, p3: u32,
p4: u32, p5: u32, p6: u32, p7: u32) -> u32 {
let idx = atomicAdd(&event_ring_tail, 1u);
if (idx >= EVENT_RING_CAP) {
return 0xFFFFFFFFu;
}
let base = idx * RECORD_U32_STRIDE;
event_ring_records[base + 0u] = kind;
event_ring_records[base + 1u] = tick;
event_ring_records[base + 2u] = p0;
event_ring_records[base + 3u] = p1;
event_ring_records[base + 4u] = p2;
event_ring_records[base + 5u] = p3;
event_ring_records[base + 6u] = p4;
event_ring_records[base + 7u] = p5;
event_ring_records[base + 8u] = p6;
event_ring_records[base + 9u] = p7;
return idx;
}

// Per-kind encoders. Argument names match the Event::<Variant> field
// names; the helper packs them into the payload layout the CPU drain
// expects. WGSL reserves `target` so helpers use `target_id` etc.

fn gpu_emit_agent_moved(actor: u32, tick: u32,
fx: f32, fy: f32, fz: f32,
lx: f32, ly: f32, lz: f32) -> u32 {
return gpu_emit_event(0u, tick, actor,
bitcast<u32>(fx), bitcast<u32>(fy), bitcast<u32>(fz),
bitcast<u32>(lx), bitcast<u32>(ly), bitcast<u32>(lz),
0u);
}

fn gpu_emit_agent_attacked(actor: u32, target_id: u32, damage: f32, tick: u32) -> u32 {
return gpu_emit_event(1u, tick, actor, target_id, bitcast<u32>(damage),
0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_agent_died(agent_id: u32, tick: u32) -> u32 {
return gpu_emit_event(2u, tick, agent_id, 0u, 0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_agent_fled(agent_id: u32, tick: u32,
fx: f32, fy: f32, fz: f32,
tx: f32, ty: f32, tz: f32) -> u32 {
return gpu_emit_event(3u, tick, agent_id,
bitcast<u32>(fx), bitcast<u32>(fy), bitcast<u32>(fz),
bitcast<u32>(tx), bitcast<u32>(ty), bitcast<u32>(tz),
0u);
}

fn gpu_emit_agent_ate(agent_id: u32, delta: f32, tick: u32) -> u32 {
return gpu_emit_event(4u, tick, agent_id, bitcast<u32>(delta),
0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_agent_drank(agent_id: u32, delta: f32, tick: u32) -> u32 {
return gpu_emit_event(5u, tick, agent_id, bitcast<u32>(delta),
0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_agent_rested(agent_id: u32, delta: f32, tick: u32) -> u32 {
return gpu_emit_event(6u, tick, agent_id, bitcast<u32>(delta),
0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_agent_cast(actor: u32, ability: u32, target_id: u32, depth: u32, tick: u32) -> u32 {
return gpu_emit_event(7u, tick, actor, ability, target_id, depth,
0u, 0u, 0u, 0u);
}

fn gpu_emit_opportunity_attack(actor: u32, target_id: u32, tick: u32) -> u32 {
return gpu_emit_event(25u, tick, actor, target_id, 0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_effect_damage(actor: u32, target_id: u32, amount: f32, tick: u32) -> u32 {
return gpu_emit_event(26u, tick, actor, target_id, bitcast<u32>(amount),
0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_effect_heal(actor: u32, target_id: u32, amount: f32, tick: u32) -> u32 {
return gpu_emit_event(27u, tick, actor, target_id, bitcast<u32>(amount),
0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_effect_shield(actor: u32, target_id: u32, amount: f32, tick: u32) -> u32 {
return gpu_emit_event(28u, tick, actor, target_id, bitcast<u32>(amount),
0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_effect_stun(actor: u32, target_id: u32, expires_at_tick: u32, tick: u32) -> u32 {
return gpu_emit_event(29u, tick, actor, target_id, expires_at_tick,
0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_cast_depth_exceeded(actor: u32, ability: u32, tick: u32) -> u32 {
return gpu_emit_event(33u, tick, actor, ability, 0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_engagement_committed(actor: u32, target_id: u32, tick: u32) -> u32 {
return gpu_emit_event(34u, tick, actor, target_id, 0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_engagement_broken(actor: u32, former_target: u32, reason: u32, tick: u32) -> u32 {
return gpu_emit_event(35u, tick, actor, former_target, reason,
0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_fear_spread(observer: u32, dead_kin: u32, tick: u32) -> u32 {
return gpu_emit_event(36u, tick, observer, dead_kin, 0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_pack_assist(observer: u32, target_id: u32, tick: u32) -> u32 {
return gpu_emit_event(37u, tick, observer, target_id, 0u, 0u, 0u, 0u, 0u, 0u);
}

fn gpu_emit_rally_call(observer: u32, wounded_kin: u32, tick: u32) -> u32 {
return gpu_emit_event(38u, tick, observer, wounded_kin, 0u, 0u, 0u, 0u, 0u, 0u);
}

@compute @workgroup_size(64)
fn cs_movement(@builtin(global_invocation_id) gid: vec3<u32>) {
let slot = gid.x;
if (slot >= cfg.agent_cap) { return; }
if (agent_alive(slot) == 0u) { return; }

let self_id = slot + 1u;
let action = scoring_action(slot);
let t_slot_raw = scoring_target(slot);
let tick = sim_cfg_tick();
let self_pos = agent_pos(slot);

if (action == ACTION_MOVE_TOWARD) {
if (t_slot_raw == NO_TARGET) { return; }
if (t_slot_raw >= cfg.agent_cap) { return; }
if (agent_alive(t_slot_raw) == 0u) { return; }
let target_pos = agent_pos(t_slot_raw);
let delta = target_pos - self_pos;
if (delta.x * delta.x + delta.y * delta.y + delta.z * delta.z <= 0.0) { return; }
let dir = normalize_or_zero(delta);
let speed = sim_cfg_move_speed();
let new_pos = self_pos + dir * speed;
set_agent_pos(slot, new_pos);
let _idx = gpu_emit_agent_moved(self_id, tick,
self_pos.x, self_pos.y, self_pos.z,
new_pos.x, new_pos.y, new_pos.z);
return;
}

if (action == ACTION_FLEE) {
if (t_slot_raw == NO_TARGET) { return; }
if (t_slot_raw >= cfg.agent_cap) { return; }
if (agent_alive(t_slot_raw) == 0u) { return; }
let threat_pos = agent_pos(t_slot_raw);
let away = normalize_or_zero(self_pos - threat_pos);
if (away.x * away.x + away.y * away.y + away.z * away.z <= 0.0) { return; }
let speed = sim_cfg_move_speed();
let new_pos = self_pos + away * speed;
set_agent_pos(slot, new_pos);
let _idx = gpu_emit_agent_fled(self_id, tick,
self_pos.x, self_pos.y, self_pos.z,
new_pos.x, new_pos.y, new_pos.z);
return;
}
}
