// GENERATED by dsl_compiler. Do not edit by hand.
@group(0) @binding(0) var<storage, read_write> agents: array<u32>;
@group(0) @binding(1) var<storage, read> scoring: array<u32>;
@group(0) @binding(2) var<storage, read_write> event_ring_records: array<u32>;
@group(0) @binding(3) var<storage, read_write> event_ring_tail: atomic<u32>;
@group(0) @binding(4) var<storage, read> sim_cfg: array<u32>;
struct MovementCfg { agent_cap: u32, tick: u32, event_ring_capacity: u32, _pad: u32 };
@group(0) @binding(5) var<uniform> cfg: MovementCfg;
@compute @workgroup_size(64)
fn cs_movement(@builtin(global_invocation_id) gid: vec3<u32>) {
if (gid.x >= cfg.agent_cap) { return; }
// Stub body: touch every binding so naga keeps them live.
let _a = agents[0];
let _s = scoring[0];
let _r = event_ring_records[0];
let _t = atomicLoad(&event_ring_tail);
let _c = sim_cfg[0];
let _g = cfg.tick;
}
