// GENERATED by dsl_compiler — do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

use crate::binding_sources::BindingSources;

pub struct PackAgentsKernel {
    pipeline: wgpu::ComputePipeline,
    bgl: wgpu::BindGroupLayout,
}

pub struct PackAgentsBindings<'a> {
    pub agent_pos: &'a wgpu::Buffer,
    pub agent_hp: &'a wgpu::Buffer,
    pub agent_max_hp: &'a wgpu::Buffer,
    pub agent_alive: &'a wgpu::Buffer,
    pub agent_movement_mode: &'a wgpu::Buffer,
    pub agent_level: &'a wgpu::Buffer,
    pub agent_move_speed: &'a wgpu::Buffer,
    pub agent_move_speed_mult: &'a wgpu::Buffer,
    pub agent_shield_hp: &'a wgpu::Buffer,
    pub agent_armor: &'a wgpu::Buffer,
    pub agent_magic_resist: &'a wgpu::Buffer,
    pub agent_attack_damage: &'a wgpu::Buffer,
    pub agent_attack_range: &'a wgpu::Buffer,
    pub agent_mana: &'a wgpu::Buffer,
    pub agent_max_mana: &'a wgpu::Buffer,
    pub agent_hunger: &'a wgpu::Buffer,
    pub agent_thirst: &'a wgpu::Buffer,
    pub agent_rest_timer: &'a wgpu::Buffer,
    pub agent_safety: &'a wgpu::Buffer,
    pub agent_shelter: &'a wgpu::Buffer,
    pub agent_social: &'a wgpu::Buffer,
    pub agent_purpose: &'a wgpu::Buffer,
    pub agent_esteem: &'a wgpu::Buffer,
    pub agent_risk_tolerance: &'a wgpu::Buffer,
    pub agent_social_drive: &'a wgpu::Buffer,
    pub agent_ambition: &'a wgpu::Buffer,
    pub agent_altruism: &'a wgpu::Buffer,
    pub agent_curiosity: &'a wgpu::Buffer,
    pub agent_engaged_with: &'a wgpu::Buffer,
    pub agent_stun_expires_at_tick: &'a wgpu::Buffer,
    pub agent_slow_expires_at_tick: &'a wgpu::Buffer,
    pub agent_slow_factor_q8: &'a wgpu::Buffer,
    pub agent_cooldown_next_ready_tick: &'a wgpu::Buffer,
    pub agent_creature_type: &'a wgpu::Buffer,
    pub agent_spawn_tick: &'a wgpu::Buffer,
    pub agent_grid_id: &'a wgpu::Buffer,
    pub agent_local_pos: &'a wgpu::Buffer,
    pub agent_move_target: &'a wgpu::Buffer,
    pub agent_scratch_packed: &'a wgpu::Buffer,
    pub cfg: &'a wgpu::Buffer,
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PackAgentsCfg { pub agent_cap: u32, pub _pad: [u32; 3] }

const SHADER_SRC: &str = include_str!("pack_agents.wgsl");

impl crate::Kernel for PackAgentsKernel {
    type Bindings<'a> = PackAgentsBindings<'a>;
    type Cfg = PackAgentsCfg;

    fn new(device: &wgpu::Device) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("engine_gpu_rules::pack_agents::wgsl"),
            source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),
        });
        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("engine_gpu_rules::pack_agents::bgl"),
            entries: &[
                crate::bgl_storage(0, true), // agent_pos
                crate::bgl_storage(1, true), // agent_hp
                crate::bgl_storage(2, true), // agent_max_hp
                crate::bgl_storage(3, true), // agent_alive
                crate::bgl_storage(4, true), // agent_movement_mode
                crate::bgl_storage(5, true), // agent_level
                crate::bgl_storage(6, true), // agent_move_speed
                crate::bgl_storage(7, true), // agent_move_speed_mult
                crate::bgl_storage(8, true), // agent_shield_hp
                crate::bgl_storage(9, true), // agent_armor
                crate::bgl_storage(10, true), // agent_magic_resist
                crate::bgl_storage(11, true), // agent_attack_damage
                crate::bgl_storage(12, true), // agent_attack_range
                crate::bgl_storage(13, true), // agent_mana
                crate::bgl_storage(14, true), // agent_max_mana
                crate::bgl_storage(15, true), // agent_hunger
                crate::bgl_storage(16, true), // agent_thirst
                crate::bgl_storage(17, true), // agent_rest_timer
                crate::bgl_storage(18, true), // agent_safety
                crate::bgl_storage(19, true), // agent_shelter
                crate::bgl_storage(20, true), // agent_social
                crate::bgl_storage(21, true), // agent_purpose
                crate::bgl_storage(22, true), // agent_esteem
                crate::bgl_storage(23, true), // agent_risk_tolerance
                crate::bgl_storage(24, true), // agent_social_drive
                crate::bgl_storage(25, true), // agent_ambition
                crate::bgl_storage(26, true), // agent_altruism
                crate::bgl_storage(27, true), // agent_curiosity
                crate::bgl_storage(28, true), // agent_engaged_with
                crate::bgl_storage(29, true), // agent_stun_expires_at_tick
                crate::bgl_storage(30, true), // agent_slow_expires_at_tick
                crate::bgl_storage(31, true), // agent_slow_factor_q8
                crate::bgl_storage(32, true), // agent_cooldown_next_ready_tick
                crate::bgl_storage(33, true), // agent_creature_type
                crate::bgl_storage(34, true), // agent_spawn_tick
                crate::bgl_storage(35, true), // agent_grid_id
                crate::bgl_storage(36, true), // agent_local_pos
                crate::bgl_storage(37, true), // agent_move_target
                crate::bgl_storage(38, false), // agent_scratch_packed
                crate::bgl_uniform(39), // cfg
            ],
        });
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("engine_gpu_rules::pack_agents::pl"),
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("engine_gpu_rules::pack_agents::pipeline"),
            layout: Some(&pl),
            module: &shader,
            entry_point: Some("cs_pack_agents"),
            compilation_options: Default::default(),
            cache: None,
        });
        Self { pipeline, bgl }
    }

    fn build_cfg(&self, state: &engine::state::SimState) -> PackAgentsCfg {
        let _ = state;
        PackAgentsCfg { agent_cap: state.agent_cap(), _pad: [0; 3] }
    }

    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> PackAgentsBindings<'a> {
        let _ = sources;
        PackAgentsBindings {
            agent_pos: sources.external.agents,
            agent_hp: sources.external.agents,
            agent_max_hp: sources.external.agents,
            agent_alive: sources.external.agents,
            agent_movement_mode: sources.external.agents,
            agent_level: sources.external.agents,
            agent_move_speed: sources.external.agents,
            agent_move_speed_mult: sources.external.agents,
            agent_shield_hp: sources.external.agents,
            agent_armor: sources.external.agents,
            agent_magic_resist: sources.external.agents,
            agent_attack_damage: sources.external.agents,
            agent_attack_range: sources.external.agents,
            agent_mana: sources.external.agents,
            agent_max_mana: sources.external.agents,
            agent_hunger: sources.external.agents,
            agent_thirst: sources.external.agents,
            agent_rest_timer: sources.external.agents,
            agent_safety: sources.external.agents,
            agent_shelter: sources.external.agents,
            agent_social: sources.external.agents,
            agent_purpose: sources.external.agents,
            agent_esteem: sources.external.agents,
            agent_risk_tolerance: sources.external.agents,
            agent_social_drive: sources.external.agents,
            agent_ambition: sources.external.agents,
            agent_altruism: sources.external.agents,
            agent_curiosity: sources.external.agents,
            agent_engaged_with: sources.external.agents,
            agent_stun_expires_at_tick: sources.external.agents,
            agent_slow_expires_at_tick: sources.external.agents,
            agent_slow_factor_q8: sources.external.agents,
            agent_cooldown_next_ready_tick: sources.external.agents,
            agent_creature_type: sources.external.agents,
            agent_spawn_tick: sources.external.agents,
            agent_grid_id: sources.external.agents,
            agent_local_pos: sources.external.agents,
            agent_move_target: sources.external.agents,
            agent_scratch_packed: sources.transient.mask_unpack_agents_input,
            cfg: cfg,
        }
    }

    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &PackAgentsBindings<'_>, agent_cap: u32) {
        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("engine_gpu_rules::pack_agents::bg"),
            layout: &self.bgl,
            entries: &[
                wgpu::BindGroupEntry { binding: 0, resource: bindings.agent_pos.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.agent_hp.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 2, resource: bindings.agent_max_hp.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 3, resource: bindings.agent_alive.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 4, resource: bindings.agent_movement_mode.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 5, resource: bindings.agent_level.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 6, resource: bindings.agent_move_speed.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 7, resource: bindings.agent_move_speed_mult.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 8, resource: bindings.agent_shield_hp.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 9, resource: bindings.agent_armor.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 10, resource: bindings.agent_magic_resist.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 11, resource: bindings.agent_attack_damage.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 12, resource: bindings.agent_attack_range.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 13, resource: bindings.agent_mana.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 14, resource: bindings.agent_max_mana.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 15, resource: bindings.agent_hunger.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 16, resource: bindings.agent_thirst.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 17, resource: bindings.agent_rest_timer.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 18, resource: bindings.agent_safety.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 19, resource: bindings.agent_shelter.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 20, resource: bindings.agent_social.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 21, resource: bindings.agent_purpose.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 22, resource: bindings.agent_esteem.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 23, resource: bindings.agent_risk_tolerance.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 24, resource: bindings.agent_social_drive.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 25, resource: bindings.agent_ambition.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 26, resource: bindings.agent_altruism.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 27, resource: bindings.agent_curiosity.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 28, resource: bindings.agent_engaged_with.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 29, resource: bindings.agent_stun_expires_at_tick.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 30, resource: bindings.agent_slow_expires_at_tick.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 31, resource: bindings.agent_slow_factor_q8.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 32, resource: bindings.agent_cooldown_next_ready_tick.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 33, resource: bindings.agent_creature_type.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 34, resource: bindings.agent_spawn_tick.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 35, resource: bindings.agent_grid_id.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 36, resource: bindings.agent_local_pos.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 37, resource: bindings.agent_move_target.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 38, resource: bindings.agent_scratch_packed.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 39, resource: bindings.cfg.as_entire_binding() },
            ],
        });
        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some("engine_gpu_rules::pack_agents::pass"),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.pipeline);
        pass.set_bind_group(0, &bg, &[]);
        pass.dispatch_workgroups((agent_cap + 63u32) / 64u32, 1, 1);
    }
}

pub fn pack_agents_bgl_entries() -> Vec<wgpu::BindGroupLayoutEntry> {
    vec![
                crate::bgl_storage(0, true), // agent_pos
                crate::bgl_storage(1, true), // agent_hp
                crate::bgl_storage(2, true), // agent_max_hp
                crate::bgl_storage(3, true), // agent_alive
                crate::bgl_storage(4, true), // agent_movement_mode
                crate::bgl_storage(5, true), // agent_level
                crate::bgl_storage(6, true), // agent_move_speed
                crate::bgl_storage(7, true), // agent_move_speed_mult
                crate::bgl_storage(8, true), // agent_shield_hp
                crate::bgl_storage(9, true), // agent_armor
                crate::bgl_storage(10, true), // agent_magic_resist
                crate::bgl_storage(11, true), // agent_attack_damage
                crate::bgl_storage(12, true), // agent_attack_range
                crate::bgl_storage(13, true), // agent_mana
                crate::bgl_storage(14, true), // agent_max_mana
                crate::bgl_storage(15, true), // agent_hunger
                crate::bgl_storage(16, true), // agent_thirst
                crate::bgl_storage(17, true), // agent_rest_timer
                crate::bgl_storage(18, true), // agent_safety
                crate::bgl_storage(19, true), // agent_shelter
                crate::bgl_storage(20, true), // agent_social
                crate::bgl_storage(21, true), // agent_purpose
                crate::bgl_storage(22, true), // agent_esteem
                crate::bgl_storage(23, true), // agent_risk_tolerance
                crate::bgl_storage(24, true), // agent_social_drive
                crate::bgl_storage(25, true), // agent_ambition
                crate::bgl_storage(26, true), // agent_altruism
                crate::bgl_storage(27, true), // agent_curiosity
                crate::bgl_storage(28, true), // agent_engaged_with
                crate::bgl_storage(29, true), // agent_stun_expires_at_tick
                crate::bgl_storage(30, true), // agent_slow_expires_at_tick
                crate::bgl_storage(31, true), // agent_slow_factor_q8
                crate::bgl_storage(32, true), // agent_cooldown_next_ready_tick
                crate::bgl_storage(33, true), // agent_creature_type
                crate::bgl_storage(34, true), // agent_spawn_tick
                crate::bgl_storage(35, true), // agent_grid_id
                crate::bgl_storage(36, true), // agent_local_pos
                crate::bgl_storage(37, true), // agent_move_target
                crate::bgl_storage(38, false), // agent_scratch_packed
                crate::bgl_uniform(39), // cfg
    ]
}

pub fn pack_agents_bind_group_entries<'a>(
    bindings: &'a PackAgentsBindings<'a>,
) -> Vec<wgpu::BindGroupEntry<'a>> {
    vec![
                wgpu::BindGroupEntry { binding: 0, resource: bindings.agent_pos.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.agent_hp.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 2, resource: bindings.agent_max_hp.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 3, resource: bindings.agent_alive.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 4, resource: bindings.agent_movement_mode.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 5, resource: bindings.agent_level.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 6, resource: bindings.agent_move_speed.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 7, resource: bindings.agent_move_speed_mult.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 8, resource: bindings.agent_shield_hp.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 9, resource: bindings.agent_armor.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 10, resource: bindings.agent_magic_resist.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 11, resource: bindings.agent_attack_damage.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 12, resource: bindings.agent_attack_range.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 13, resource: bindings.agent_mana.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 14, resource: bindings.agent_max_mana.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 15, resource: bindings.agent_hunger.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 16, resource: bindings.agent_thirst.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 17, resource: bindings.agent_rest_timer.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 18, resource: bindings.agent_safety.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 19, resource: bindings.agent_shelter.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 20, resource: bindings.agent_social.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 21, resource: bindings.agent_purpose.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 22, resource: bindings.agent_esteem.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 23, resource: bindings.agent_risk_tolerance.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 24, resource: bindings.agent_social_drive.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 25, resource: bindings.agent_ambition.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 26, resource: bindings.agent_altruism.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 27, resource: bindings.agent_curiosity.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 28, resource: bindings.agent_engaged_with.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 29, resource: bindings.agent_stun_expires_at_tick.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 30, resource: bindings.agent_slow_expires_at_tick.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 31, resource: bindings.agent_slow_factor_q8.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 32, resource: bindings.agent_cooldown_next_ready_tick.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 33, resource: bindings.agent_creature_type.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 34, resource: bindings.agent_spawn_tick.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 35, resource: bindings.agent_grid_id.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 36, resource: bindings.agent_local_pos.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 37, resource: bindings.agent_move_target.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 38, resource: bindings.agent_scratch_packed.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 39, resource: bindings.cfg.as_entire_binding() },
    ]
}

pub fn pack_agents_build_cfg(state: &engine::state::SimState) -> PackAgentsCfg {
    PackAgentsCfg { agent_cap: state.agent_cap(), _pad: [0; 3] }
}
