// GENERATED by dsl_compiler — do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

use crate::binding_sources::BindingSources;

pub struct PhysicsChronicleBreakKernel {
    pipeline: wgpu::ComputePipeline,
    bgl: wgpu::BindGroupLayout,
}

pub struct PhysicsChronicleBreakBindings<'a> {
    pub event_ring: &'a wgpu::Buffer,
    pub cfg: &'a wgpu::Buffer,
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PhysicsChronicleBreakCfg { pub agent_cap: u32, pub _pad: [u32; 3] }

const SHADER_SRC: &str = include_str!("physics_chronicle_break.wgsl");

impl crate::Kernel for PhysicsChronicleBreakKernel {
    type Bindings<'a> = PhysicsChronicleBreakBindings<'a>;
    type Cfg = PhysicsChronicleBreakCfg;

    fn new(device: &wgpu::Device) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("engine_gpu_rules::physics_chronicle_break::wgsl"),
            source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),
        });
        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("engine_gpu_rules::physics_chronicle_break::bgl"),
            entries: &[
                crate::bgl_storage(0, false), // event_ring
                crate::bgl_uniform(1), // cfg
            ],
        });
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("engine_gpu_rules::physics_chronicle_break::pl"),
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("engine_gpu_rules::physics_chronicle_break::pipeline"),
            layout: Some(&pl),
            module: &shader,
            entry_point: Some("cs_physics_chronicle_break"),
            compilation_options: Default::default(),
            cache: None,
        });
        Self { pipeline, bgl }
    }

    fn build_cfg(&self, state: &engine::state::SimState) -> PhysicsChronicleBreakCfg {
        let _ = state;
        PhysicsChronicleBreakCfg { agent_cap: state.agent_cap(), _pad: [0; 3] }
    }

    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> PhysicsChronicleBreakBindings<'a> {
        let _ = sources;
        PhysicsChronicleBreakBindings {
            event_ring: sources.transient.cascade_current_ring,
            cfg: cfg,
        }
    }

    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &PhysicsChronicleBreakBindings<'_>, agent_cap: u32) {
        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("engine_gpu_rules::physics_chronicle_break::bg"),
            layout: &self.bgl,
            entries: &[
                wgpu::BindGroupEntry { binding: 0, resource: bindings.event_ring.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.cfg.as_entire_binding() },
            ],
        });
        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some("engine_gpu_rules::physics_chronicle_break::pass"),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.pipeline);
        pass.set_bind_group(0, &bg, &[]);
        pass.dispatch_workgroups((agent_cap + 63u32) / 64u32, 1, 1);
    }
}

pub fn physics_chronicle_break_bgl_entries() -> Vec<wgpu::BindGroupLayoutEntry> {
    vec![
                crate::bgl_storage(0, false), // event_ring
                crate::bgl_uniform(1), // cfg
    ]
}

pub fn physics_chronicle_break_bind_group_entries<'a>(
    bindings: &'a PhysicsChronicleBreakBindings<'a>,
) -> Vec<wgpu::BindGroupEntry<'a>> {
    vec![
                wgpu::BindGroupEntry { binding: 0, resource: bindings.event_ring.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.cfg.as_entire_binding() },
    ]
}

pub fn physics_chronicle_break_build_cfg(state: &engine::state::SimState) -> PhysicsChronicleBreakCfg {
    PhysicsChronicleBreakCfg { agent_cap: state.agent_cap(), _pad: [0; 3] }
}
