// GENERATED by dsl_compiler::emit_pool. Do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

/// Pooled-lifetime buffers — shape-keyed; reused across compatible kernels.
pub struct Pool {
}

impl Pool {
    pub fn new(_device: &wgpu::Device) -> Self {
        Self {}
    }
}
