// GENERATED by dsl_compiler::emit_kernel_module. Do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

use crate::binding_sources::BindingSources;

pub struct ScoringKernel {
    pipeline: wgpu::ComputePipeline,
    bgl: wgpu::BindGroupLayout,
}

pub struct ScoringBindings<'a> {
    pub agent_data: &'a wgpu::Buffer,
    pub mask_bitmaps: &'a wgpu::Buffer,
    pub scoring_out: &'a wgpu::Buffer,
    pub sim_cfg: &'a wgpu::Buffer,
    pub cfg: &'a wgpu::Buffer,
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ScoringCfg { pub agent_cap: u32, pub num_actions: u32, pub tick: u32, pub _pad: u32 }

const SHADER_SRC: &str = include_str!("scoring.wgsl");

impl crate::Kernel for ScoringKernel {
    type Bindings<'a> = ScoringBindings<'a>;
    type Cfg = ScoringCfg;

    fn new(device: &wgpu::Device) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("engine_gpu_rules::scoring::wgsl"),
            source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),
        });
        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("engine_gpu_rules::scoring::bgl"),
            entries: &[
                crate::bgl_storage(0, true), // agent_data
                crate::bgl_storage(1, true), // mask_bitmaps
                crate::bgl_storage(2, false), // scoring_out
                crate::bgl_storage(3, true), // sim_cfg
                crate::bgl_uniform(4), // cfg
            ],
        });
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("engine_gpu_rules::scoring::pl"),
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("engine_gpu_rules::scoring::pipeline"),
            layout: Some(&pl),
            module: &shader,
            entry_point: Some("cs_scoring"),
            compilation_options: Default::default(),
            cache: None,
        });
        Self { pipeline, bgl }
    }

    fn build_cfg(&self, state: &engine::state::SimState) -> ScoringCfg {
        let _ = state;
        ScoringCfg { agent_cap: state.agent_cap(), num_actions: 16, tick: state.tick, _pad: 0 }
    }

    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> ScoringBindings<'a> {
        let _ = sources;
        ScoringBindings {
            agent_data: sources.external.agents,
            mask_bitmaps: sources.transient.mask_bitmaps,
            scoring_out: sources.transient.action_buf,
            sim_cfg: sources.external.sim_cfg,
            cfg: cfg,
        }
    }

    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &ScoringBindings<'_>, agent_cap: u32) {
        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("engine_gpu_rules::scoring::bg"),
            layout: &self.bgl,
            entries: &[
                wgpu::BindGroupEntry { binding: 0, resource: bindings.agent_data.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.mask_bitmaps.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 2, resource: bindings.scoring_out.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 3, resource: bindings.sim_cfg.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 4, resource: bindings.cfg.as_entire_binding() },
            ],
        });
        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some("engine_gpu_rules::scoring::pass"),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.pipeline);
        pass.set_bind_group(0, &bg, &[]);
        pass.dispatch_workgroups((agent_cap + 63) / 64, 1, 1);
    }
}
