// GENERATED by dsl_compiler::emit_scoring_wgsl. Do not edit by hand.
// GENERATED by dsl_compiler::emit_scoring_wgsl::emit_scoring_wgsl_v2.
// 5-slot stub matching emit_scoring_rs_v2's BGL. View reads are TODO.

@group(0) @binding(0) var<storage, read>       agent_data:   array<u32>;
@group(0) @binding(1) var<storage, read>       mask_bitmaps: array<u32>;
@group(0) @binding(2) var<storage, read_write> scoring_out:  array<u32>;
@group(0) @binding(3) var<storage, read>       sim_cfg:      array<u32>;
struct ScoringCfg { agent_cap: u32, num_actions: u32, tick: u32, _pad: u32 };
@group(0) @binding(4) var<uniform>             cfg:          ScoringCfg;

// ScoreOutput stride matches engine_gpu/src/sync_helpers.rs.
const SCORING_STRIDE_U32: u32 = 4u;
const ACTION_HOLD: u32 = 0u;
const NO_TARGET: u32 = 0xFFFFFFFFu;

@compute @workgroup_size(64)
fn cs_scoring(@builtin(global_invocation_id) gid: vec3<u32>) {
    let i = gid.x;
    if (i >= cfg.agent_cap) { return; }
    // Touch every binding so naga keeps slots live.
    let _a = agent_data[0];
    let _m = mask_bitmaps[0];
    let _s = sim_cfg[0];
    let _t = cfg.tick;
    // Stub body: write a default 'hold' action per agent.
    let base = i * SCORING_STRIDE_U32;
    scoring_out[base + 0u] = ACTION_HOLD;
    scoring_out[base + 1u] = NO_TARGET;
    scoring_out[base + 2u] = 0u;
    scoring_out[base + 3u] = 0u;
}
