// GENERATED by dsl_compiler — do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

use crate::binding_sources::BindingSources;

pub struct SpatialFilteredWalk30Kernel {
    pipeline: wgpu::ComputePipeline,
    bgl: wgpu::BindGroupLayout,
}

pub struct SpatialFilteredWalk30Bindings<'a> {
    pub agent_pos: &'a wgpu::Buffer,
    pub agent_alive: &'a wgpu::Buffer,
    pub spatial_grid_cells: &'a wgpu::Buffer,
    pub spatial_grid_offsets: &'a wgpu::Buffer,
    pub spatial_query_results: &'a wgpu::Buffer,
    pub cfg: &'a wgpu::Buffer,
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SpatialFilteredWalk30Cfg { pub agent_cap: u32, pub _pad: [u32; 3] }

const SHADER_SRC: &str = include_str!("spatial_filtered_walk_30.wgsl");

impl crate::Kernel for SpatialFilteredWalk30Kernel {
    type Bindings<'a> = SpatialFilteredWalk30Bindings<'a>;
    type Cfg = SpatialFilteredWalk30Cfg;

    fn new(device: &wgpu::Device) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("engine_gpu_rules::spatial_filtered_walk_30::wgsl"),
            source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),
        });
        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("engine_gpu_rules::spatial_filtered_walk_30::bgl"),
            entries: &[
                crate::bgl_storage(0, true), // agent_pos
                crate::bgl_storage(1, true), // agent_alive
                crate::bgl_storage(2, true), // spatial_grid_cells
                crate::bgl_storage(3, true), // spatial_grid_offsets
                crate::bgl_storage(4, false), // spatial_query_results
                crate::bgl_uniform(5), // cfg
            ],
        });
        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("engine_gpu_rules::spatial_filtered_walk_30::pl"),
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("engine_gpu_rules::spatial_filtered_walk_30::pipeline"),
            layout: Some(&pl),
            module: &shader,
            entry_point: Some("cs_spatial_filtered_walk_30"),
            compilation_options: Default::default(),
            cache: None,
        });
        Self { pipeline, bgl }
    }

    fn build_cfg(&self, state: &engine::state::SimState) -> SpatialFilteredWalk30Cfg {
        let _ = state;
        SpatialFilteredWalk30Cfg { agent_cap: state.agent_cap(), _pad: [0; 3] }
    }

    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> SpatialFilteredWalk30Bindings<'a> {
        let _ = sources;
        SpatialFilteredWalk30Bindings {
            agent_pos: sources.external.agents,
            agent_alive: sources.external.agents,
            spatial_grid_cells: &sources.pool.spatial_grid_cells,
            spatial_grid_offsets: &sources.pool.spatial_grid_offsets,
            spatial_query_results: &sources.pool.spatial_query_results,
            cfg: cfg,
        }
    }

    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &SpatialFilteredWalk30Bindings<'_>, agent_cap: u32) {
        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("engine_gpu_rules::spatial_filtered_walk_30::bg"),
            layout: &self.bgl,
            entries: &[
                wgpu::BindGroupEntry { binding: 0, resource: bindings.agent_pos.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.agent_alive.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 2, resource: bindings.spatial_grid_cells.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 3, resource: bindings.spatial_grid_offsets.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 4, resource: bindings.spatial_query_results.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 5, resource: bindings.cfg.as_entire_binding() },
            ],
        });
        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some("engine_gpu_rules::spatial_filtered_walk_30::pass"),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.pipeline);
        pass.set_bind_group(0, &bg, &[]);
        pass.dispatch_workgroups((agent_cap + 63u32) / 64u32, 1, 1);
    }
}

pub fn spatial_filtered_walk_30_bgl_entries() -> Vec<wgpu::BindGroupLayoutEntry> {
    vec![
                crate::bgl_storage(0, true), // agent_pos
                crate::bgl_storage(1, true), // agent_alive
                crate::bgl_storage(2, true), // spatial_grid_cells
                crate::bgl_storage(3, true), // spatial_grid_offsets
                crate::bgl_storage(4, false), // spatial_query_results
                crate::bgl_uniform(5), // cfg
    ]
}

pub fn spatial_filtered_walk_30_bind_group_entries<'a>(
    bindings: &'a SpatialFilteredWalk30Bindings<'a>,
) -> Vec<wgpu::BindGroupEntry<'a>> {
    vec![
                wgpu::BindGroupEntry { binding: 0, resource: bindings.agent_pos.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 1, resource: bindings.agent_alive.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 2, resource: bindings.spatial_grid_cells.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 3, resource: bindings.spatial_grid_offsets.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 4, resource: bindings.spatial_query_results.as_entire_binding() },
                wgpu::BindGroupEntry { binding: 5, resource: bindings.cfg.as_entire_binding() },
    ]
}

pub fn spatial_filtered_walk_30_build_cfg(state: &engine::state::SimState) -> SpatialFilteredWalk30Cfg {
    SpatialFilteredWalk30Cfg { agent_cap: state.agent_cap(), _pad: [0; 3] }
}
