// GENERATED by dsl_compiler — do not edit by hand.
// Regenerate with `cargo run --bin xtask -- compile-dsl`.

struct UnpackAgentsCfg { agent_cap: u32, _pad0: u32, _pad1: u32, _pad2: u32 };

@group(0) @binding(0) var<storage, read_write> agent_pos: array<vec3<f32>>;
@group(0) @binding(1) var<storage, read_write> agent_hp: array<f32>;
@group(0) @binding(2) var<storage, read_write> agent_max_hp: array<f32>;
@group(0) @binding(3) var<storage, read_write> agent_alive: array<u32>;
@group(0) @binding(4) var<storage, read_write> agent_movement_mode: array<u32>;
@group(0) @binding(5) var<storage, read_write> agent_level: array<u32>;
@group(0) @binding(6) var<storage, read_write> agent_move_speed: array<f32>;
@group(0) @binding(7) var<storage, read_write> agent_move_speed_mult: array<f32>;
@group(0) @binding(8) var<storage, read_write> agent_shield_hp: array<f32>;
@group(0) @binding(9) var<storage, read_write> agent_armor: array<f32>;
@group(0) @binding(10) var<storage, read_write> agent_magic_resist: array<f32>;
@group(0) @binding(11) var<storage, read_write> agent_attack_damage: array<f32>;
@group(0) @binding(12) var<storage, read_write> agent_attack_range: array<f32>;
@group(0) @binding(13) var<storage, read_write> agent_mana: array<f32>;
@group(0) @binding(14) var<storage, read_write> agent_max_mana: array<f32>;
@group(0) @binding(15) var<storage, read_write> agent_hunger: array<f32>;
@group(0) @binding(16) var<storage, read_write> agent_thirst: array<f32>;
@group(0) @binding(17) var<storage, read_write> agent_rest_timer: array<f32>;
@group(0) @binding(18) var<storage, read_write> agent_safety: array<f32>;
@group(0) @binding(19) var<storage, read_write> agent_shelter: array<f32>;
@group(0) @binding(20) var<storage, read_write> agent_social: array<f32>;
@group(0) @binding(21) var<storage, read_write> agent_purpose: array<f32>;
@group(0) @binding(22) var<storage, read_write> agent_esteem: array<f32>;
@group(0) @binding(23) var<storage, read_write> agent_risk_tolerance: array<f32>;
@group(0) @binding(24) var<storage, read_write> agent_social_drive: array<f32>;
@group(0) @binding(25) var<storage, read_write> agent_ambition: array<f32>;
@group(0) @binding(26) var<storage, read_write> agent_altruism: array<f32>;
@group(0) @binding(27) var<storage, read_write> agent_curiosity: array<f32>;
@group(0) @binding(28) var<storage, read_write> agent_engaged_with: array<u32>;
@group(0) @binding(29) var<storage, read_write> agent_stun_expires_at_tick: array<u32>;
@group(0) @binding(30) var<storage, read_write> agent_slow_expires_at_tick: array<u32>;
@group(0) @binding(31) var<storage, read_write> agent_slow_factor_q8: array<i32>;
@group(0) @binding(32) var<storage, read_write> agent_cooldown_next_ready_tick: array<u32>;
@group(0) @binding(33) var<storage, read_write> agent_creature_type: array<u32>;
@group(0) @binding(34) var<storage, read_write> agent_spawn_tick: array<u32>;
@group(0) @binding(35) var<storage, read_write> agent_grid_id: array<u32>;
@group(0) @binding(36) var<storage, read_write> agent_local_pos: array<vec3<f32>>;
@group(0) @binding(37) var<storage, read_write> agent_move_target: array<vec3<f32>>;
@group(0) @binding(38) var<storage, read_write> agent_scratch_packed: array<u32>;
@group(0) @binding(39) var<uniform> cfg: UnpackAgentsCfg;

@compute @workgroup_size(64)
fn cs_unpack_agents(@builtin(global_invocation_id) gid: vec3<u32>) {
let agent_id = gid.x;
if (agent_id >= cfg.agent_cap) { return; }

// op#32 (plumbing)
{
    // PlumbingKind::UnpackAgents — structural stub. Verbatim
    // port of engine_gpu_rules/src/fused_agent_unpack.wgsl (the
    // legacy file is itself a stub that touches every binding).
    let _as = agent_scratch_packed[0];
    let _ap = agent_pos[agent_id];
    let _c = cfg.agent_cap;
}
}
