//! engine_gpu_rules build sentinel.
//!
//! Every .rs and .wgsl file under `src/` (other than `lib.rs`) must start
//! with `// GENERATED by dsl_compiler` within the first 5 lines. Hand-edited
//! files in this crate are forbidden by the constitution (P1).

use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src");
    walk(Path::new("src"));
}

fn walk(dir: &Path) {
    if !dir.exists() { return; }
    for entry in fs::read_dir(dir).expect("readable src dir") {
        let entry = entry.expect("readable entry");
        let path = entry.path();
        let ft = entry.file_type().expect("file type");
        if ft.is_dir() { walk(&path); continue; }
        let ext = path.extension().and_then(|e| e.to_str());
        if !matches!(ext, Some("rs") | Some("wgsl")) { continue; }
        if path.file_name() == Some(std::ffi::OsStr::new("lib.rs"))
           && path.parent() == Some(Path::new("src")) { continue; }
        let content = fs::read_to_string(&path).expect("readable file");
        let head: String = content.lines().take(5).collect::<Vec<_>>().join("\n");
        if !head.contains("// GENERATED by dsl_compiler") {
            panic!(
                "engine_gpu_rules: {} is missing the `// GENERATED by dsl_compiler` header. \
                 Hand-edited files in this crate are forbidden. Edit the .sim source \
                 in assets/sim/ and rerun `cargo run -p xtask --bin xtask -- compile-dsl`.",
                path.display()
            );
        }
    }
}
