// GENERATED by dsl_compiler from assets/sim/config.sim.
// Was emitted from .sim source by xtask `compile-dsl` (retired Phase 7, 2026-05-02); now hand-maintained.
// Do not edit by hand.

use serde::{Deserialize, Serialize};

/// Compiler-emitted tunables for the `movement` config block.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MovementConfig {
    pub move_speed_mps: f32,
    pub max_move_radius: f32,
}

impl Default for MovementConfig {
    fn default() -> Self {
        Self {
            move_speed_mps: 1.0_f32,
            max_move_radius: 20.0_f32,
        }
    }
}
