//! engine_rules — emitted rule logic for the CPU/Serial backend.
//!
//! Generated by `cargo run --bin xtask -- compile-dsl`.
//! Do not edit by hand; edit the `.sim` sources instead.
#![allow(clippy::all)]
#![allow(unused_imports)]
#![allow(unused_parens)]

// Re-export engine primitives at crate level so generated files can use
// `crate::cascade`, `crate::event`, `crate::state`, `crate::ids`,
// `crate::ability`, `crate::spatial`, `crate::mask` etc. — the same
// `crate::` paths the emitter produces.
pub use engine::ability;
pub use engine::cascade;
pub use engine::event;
pub use engine::ids;
// engine::mask is exposed via `pub mod mask` (the DSL-emitted module) below.
// For code that needs the raw engine mask primitives use `engine::mask` directly.
pub use engine::policy;
pub use engine::scratch;
pub use engine::spatial;
pub use engine::state;
pub use engine::telemetry;

// engine_data re-exports — event enum lives here.
pub use engine_data::config;
pub use engine_data::events;
pub use engine_data::types;
pub use engine_data::EVENT_HASH;

// Generated modules — populated by `compile-dsl`.
pub mod backend;
pub mod mask;
pub mod mask_fill;
pub mod physics;
pub mod step;
pub mod views;

// cascade_reg.rs is the generated cascade registration module.
pub mod cascade_reg;

pub use backend::SerialBackend;
pub use views::ViewRegistry;

/// Convenience type alias: the cascade registry instantiated with the
/// engine-rules event type and view registry.
pub type SimCascadeRegistry =
    engine::cascade::CascadeRegistry<engine_data::events::Event, ViewRegistry>;

/// Convenience type alias: the event ring for engine_rules events.
pub type SimEventRing = engine::event::EventRing<engine_data::events::Event>;

/// Construct a `SimCascadeRegistry` pre-populated with all DSL-emitted
/// physics dispatchers. Generated by `emit_cascade_register.rs` and
/// written to `crates/engine_rules/src/cascade_reg.rs`.
pub fn with_engine_builtins() -> SimCascadeRegistry {
    cascade_reg::with_engine_builtins()
}
