//! engine build sentinel.
//!
//! Two structural rules:
//!   1. Top-level files + directories under `src/` must be on the
//!      allowlist below. New behaviour belongs in engine_rules; new
//!      primitives require an allowlist edit, which is a constitutional
//!      governance event (Spec B' §5 D11): pros/cons writeup + 2 biased-
//!      against critic PASSes + user approval recorded as ADR.
//!   2. No file under `src/` may carry the `// GENERATED by dsl_compiler`
//!      marker, EXCEPT `event/event_like_impl.rs` (the Task 2 workaround
//!      where `impl engine::event::EventLike for engine_data::events::Event`
//!      lives — pending the Task 5 follow-up that inverts the engine_data dep
//!      direction and moves the impl to engine_data).

use std::fs;
use std::path::Path;

const ALLOWED_TOP_LEVEL: &[&str] = &[
    "lib.rs",
    "backend.rs",
    "channel.rs",
    "creature.rs",
    "ids.rs",
    "mask.rs",
    "pool.rs",
    "rng.rs",
    "schema_hash.rs",
    "scratch.rs",
    "sim_trait.rs",
    "spatial.rs",
    // step.rs: compile-only unimplemented!() stubs so #[ignore]d tests that
    // still import engine::step::* compile. Pending Task 11 cleanup — once
    // engine_rules::step is canonical, this file and entry are deleted.
    "step.rs",
    "terrain.rs",
    "trajectory.rs",
];

const ALLOWED_DIRS: &[&str] = &[
    "ability",
    "aggregate",
    "cascade",
    "debug",                  // NEW: Plan 4 — debug+trace runtime per spec/engine.md §13
    // evaluator/: SimState-backed ReadContext/CascadeContext impls for the DSL
    // IR interpreter. Gated entirely on `#[cfg(feature = "interpreted-rules")]` —
    // zero cost when the feature is off. Lives in engine (not engine_rules) because
    // engine has no dep on engine_rules; engine_rules can't provide the context impls
    // without a circular dep. ADR pending (P1b port, 2026-04-25).
    "evaluator",
    "event",
    // gpu/: wgpu platform primitives (GpuContext, Kernel trait, BGL
    // helpers). Sim-agnostic; per-fixture runtime crates' generated
    // dispatch modules `impl engine::gpu::Kernel` against this surface.
    // Phase 7 boids GPU pipeline (2026-05-02).
    "gpu",
    "invariant",
    "obs",
    "policy",
    "pool",
    "probe",
    "snapshot",
    // state/: SimState SoA struct; pending Task 6 migration to engine_data as
    // an emitted artifact. Remove this entry and the directory once Task 6 lands.
    "state",
    "telemetry",
    "view",
];

/// Paths relative to `src/` that are allowed to carry the `// GENERATED` marker.
///
/// Currently: `event/event_like_impl.rs` (Task 2 workaround — B2-deferred carve-out).
/// Once Task 5 moves the impl to engine_data, this list shrinks to empty and the
/// constant can be removed.
const GENERATED_MARKER_EXEMPT: &[&str] = &[
    "event/event_like_impl.rs",
];

fn main() {
    println!("cargo:rerun-if-changed=src");
    let src = Path::new("src");

    // Rule 1: top-level allowlist
    for entry in fs::read_dir(src).expect("readable engine/src") {
        let entry = entry.expect("readable entry");
        let name = entry.file_name();
        let name_s = name.to_string_lossy();
        let ft = entry.file_type().expect("file type");
        if ft.is_dir() {
            if !ALLOWED_DIRS.contains(&name_s.as_ref()) {
                panic!(
                    "engine/src/{}/: not in primitives allowlist. Engine contains \
                     primitives only — behaviour belongs in engine_rules. To add a \
                     new primitive subdir, edit engine/build.rs ALLOWED_DIRS and \
                     follow Spec B' §5 D11 (pros/cons writeup + 2 biased-against \
                     critic PASSes + user approval recorded as ADR).",
                    name_s
                );
            }
        } else if name_s.ends_with(".rs") {
            if !ALLOWED_TOP_LEVEL.contains(&name_s.as_ref()) {
                panic!(
                    "engine/src/{}: not in primitives allowlist. See engine/build.rs.",
                    name_s
                );
            }
        }
    }

    // Rule 2: reject `// GENERATED by dsl_compiler` markers (with exception list)
    walk_for_generated_marker(src, src);
}

fn walk_for_generated_marker(root: &Path, dir: &Path) {
    for entry in fs::read_dir(dir).expect("readable dir") {
        let entry = entry.expect("entry");
        let path = entry.path();
        let ft = entry.file_type().expect("file type");
        if ft.is_dir() {
            walk_for_generated_marker(root, &path);
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        // Exemption check: paths relative to src/ that are explicitly allowed.
        let rel = path
            .strip_prefix(root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        if GENERATED_MARKER_EXEMPT.contains(&rel.as_str()) {
            continue;
        }
        let content = fs::read_to_string(&path).expect("readable rs");
        if content.contains("// GENERATED by dsl_compiler") {
            panic!(
                "engine/src/{}: contains `// GENERATED by dsl_compiler` marker. \
                 Generated code lives in engine_rules/ or engine_data/, not engine/. \
                 If this file was hand-written, remove the marker; if it was supposed \
                 to be emitted, move it to the right crate.",
                rel
            );
        }
    }
}
