// GENERATED by dsl_compiler from assets/sim/events.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use crate::ids::AgentId;

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct AgentCommunicated {
    pub speaker: AgentId,
    pub recipient: AgentId,
    pub fact_ref: u64,
    pub tick: u32,
}
