// GENERATED by dsl_compiler from assets/sim/events.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use crate::ids::AgentId;
use glam::Vec3;

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct AgentPlacedTile {
    pub agent_id: AgentId,
    pub where_pos: Vec3,
    pub kind_tag: u32,
    pub tick: u32,
}
