// GENERATED by dsl_compiler from assets/sim/events.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use engine::ids::AgentId;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct AgentDied {
    #[serde(with = "crate::id_serde::agent_id")]
    pub agent: AgentId,
    pub tick: u64,
}
