// GENERATED by dsl_compiler from assets/sim/events.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct ChronicleEntry {
    pub tick: u32,
    pub template_id: u32,
}
