// GENERATED by dsl_compiler from assets/sim/events.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use crate::ids::AgentId;

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct EffectGoldTransfer {
    pub from: AgentId,
    pub to: AgentId,
    pub amount: i64,
    pub tick: u32,
}
