//! engine_data build sentinel.
//!
//! Like engine_rules, but with a small allowlist for hand-written files
//! that legitimately live here pending follow-up plans:
//!   - `lib.rs` — standard module-root exemption
//!   - `ids.rs` — transitional ID newtype defs (B1' Task 3 deferred)
//!   - `types.rs` — hand-written shared enum vocabulary
//!   - `id_serde.rs` — hand-written serde glue for niche IDs

use std::fs;
use std::path::Path;

const HAND_WRITTEN_ALLOWLIST: &[&str] = &[
    "lib.rs",
    "ids.rs",
    "types.rs",
    "id_serde.rs",
];

fn main() {
    println!("cargo:rerun-if-changed=src");
    walk(Path::new("src"));
}

fn walk(dir: &Path) {
    for entry in fs::read_dir(dir).expect("readable src dir") {
        let entry = entry.expect("readable entry");
        let path = entry.path();
        let ft = entry.file_type().expect("file type");
        if ft.is_dir() { walk(&path); continue; }
        if path.extension().and_then(|e| e.to_str()) != Some("rs") { continue; }
        // Allowlist applies only at the top-level src/ directory.
        if path.parent() == Some(Path::new("src")) {
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if HAND_WRITTEN_ALLOWLIST.contains(&name) { continue; }
        }
        let content = fs::read_to_string(&path).expect("readable rs file");
        let head: String = content.lines().take(5).collect::<Vec<_>>().join("\n");
        if !head.contains("// GENERATED by dsl_compiler") {
            panic!(
                "engine_data: {} is missing the `// GENERATED by dsl_compiler` header. \
                 Hand-edited files in engine_data are restricted to the top-level allowlist \
                 (lib.rs, ids.rs, types.rs, id_serde.rs). Other files must be emitted from DSL.",
                path.display()
            );
        }
    }
}
