//! View emission — anchor-pattern Rust for `@materialized @decay` views.
//!
//! The anchor pattern avoids per-tick work on views that decay monotonically
//! between events. Instead of updating the value every tick, we store
//! `(base_at_anchor, anchor_tick)` and compute the current value lazily as
//! `base * rate^(tick - anchor)`. Event handlers advance the anchor forward
//! and fold the event's delta into the new base.
//!
//! Lowered shape (conceptual — the real engine wires these up through its
//! view-fold registry):
//!
//! ```rust,ignore
//! pub struct ThreatLevel {
//!     value: HashMap<(AgentId, AgentId), (f32, u32)>, // (base, anchor_tick)
//! }
//!
//! impl ThreatLevel {
//!     pub fn get(&self, a: AgentId, b: AgentId, tick: u32) -> f32 {
//!         let (base, anchor) = self.value.get(&(a, b)).copied().unwrap_or((0.0, tick));
//!         (base * 0.98_f32.powi((tick - anchor) as i32)).clamp(0.0, 1000.0)
//!     }
//!     pub fn fold(&mut self, e: &Event, tick: u32) {
//!         if let Event::AgentAttacked { actor, target, amount, .. } = *e {
//!             let (base, anchor) = self.value.get(&(target, actor)).copied().unwrap_or((0.0, tick));
//!             let current = base * 0.98_f32.powi((tick - anchor) as i32);
//!             let updated = (current + amount).clamp(0.0, 1000.0);
//!             self.value.insert((target, actor), (updated, tick));
//!         }
//!     }
//! }
//! ```
//!
//! At v1 the emitter produces a source-readable skeleton — the engine-side
//! wiring for view folds isn't in place yet, but the skeleton validates the
//! decay rate, clamp bounds, and event-handler shape at compile time.

use std::fmt::Write;

use crate::ir::{DecayUnit, ViewBodyIR, ViewIR};

/// Errors the view emitter can raise.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    /// Something in the IR shape doesn't match what the anchor-pattern
    /// emitter can produce. Carries a short diagnostic.
    Unsupported(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::Unsupported(s) => write!(f, "view emission: {s}"),
        }
    }
}

impl std::error::Error for EmitError {}

/// Emit the anchor-pattern Rust skeleton for a `@materialized @decay`
/// view. Returns `Ok(None)` when the view has no `@decay` hint (plain
/// materialized views go through a future non-decay emitter).
///
/// The emitted source is a self-contained module body: one `pub struct`
/// with the value map, one `fn get`, and one `fn fold` with an arm per
/// declared event handler. The generated code compiles as part of a
/// larger `mod views;` tree — name resolution for events comes from
/// elsewhere in the generated bundle.
pub fn emit_decay_view(view: &ViewIR) -> Result<Option<String>, EmitError> {
    let decay = match view.decay {
        Some(d) => d,
        None => return Ok(None),
    };
    // `@decay` requires a Fold body; the resolver already enforced this.
    let (initial_expr, handlers, clamp) = match &view.body {
        ViewBodyIR::Fold { initial, handlers, clamp } => (initial, handlers, clamp),
        ViewBodyIR::Expr(_) => {
            return Err(EmitError::Unsupported(format!(
                "view `{}` has @decay but a non-fold body — resolver should have caught this",
                view.name
            )));
        }
    };

    let struct_name = to_pascal(&view.name);
    let field_name = to_snake(&view.name);
    let rate = decay.rate;
    let per_unit = match decay.per {
        DecayUnit::Tick => "tick",
    };

    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler — anchor-pattern decay view for `{}`.", view.name).unwrap();
    writeln!(out, "// rate={rate} per {per_unit}").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use std::collections::HashMap;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/// Anchor-pattern storage for view `{}`.", view.name).unwrap();
    writeln!(out, "/// `value: HashMap<Key, (base, anchor_tick)>` — the current").unwrap();
    writeln!(out, "/// observable value at tick `t` is `base * {rate}_f32.powi((t - anchor) as i32)`").unwrap();
    writeln!(out, "/// with the emitted clamp applied.").unwrap();
    writeln!(out, "#[derive(Debug, Default)]").unwrap();
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    // For v1 we emit a generic (i64, i64) pair key — the real engine wires
    // per-view concrete key types through its storage-hint parser. The
    // compile-time contract at this layer is the anchor-pattern shape, not
    // the key type.
    writeln!(out, "    value: HashMap<(i64, i64), (f32, u32)>,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl {struct_name} {{").unwrap();
    writeln!(out, "    /// Decay rate applied per {per_unit}. Compile-time constant.").unwrap();
    writeln!(out, "    pub const RATE: f32 = {rate}_f32;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    pub fn new() -> Self {{ Self::default() }}").unwrap();
    writeln!(out).unwrap();

    // get()
    writeln!(out, "    /// Compute the current value at `tick`, decayed from the anchor.").unwrap();
    writeln!(out, "    pub fn get(&self, a: i64, b: i64, tick: u32) -> f32 {{").unwrap();
    writeln!(out, "        let (base, anchor) = self.value.get(&(a, b)).copied().unwrap_or(({}_f32, tick));", format_expr_initial(initial_expr)).unwrap();
    writeln!(out, "        let decayed = base * Self::RATE.powi((tick.saturating_sub(anchor)) as i32);").unwrap();
    if let Some((lo, hi)) = clamp {
        writeln!(
            out,
            "        decayed.clamp({}_f32, {}_f32)",
            format_expr_initial(lo),
            format_expr_initial(hi),
        )
        .unwrap();
    } else {
        writeln!(out, "        decayed").unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // fold() with one arm per handler.
    writeln!(out, "    /// Advance the anchor forward on each matching event.").unwrap();
    writeln!(out, "    pub fn fold_event(&mut self, event_name: &str, a: i64, b: i64, amount: f32, tick: u32) {{").unwrap();
    writeln!(out, "        // One arm per declared handler. Runtime dispatch by event").unwrap();
    writeln!(out, "        // name — the engine's real fold registry keys on `EventRef`,").unwrap();
    writeln!(out, "        // but the skeleton here stays source-readable.").unwrap();
    writeln!(out, "        match event_name {{").unwrap();
    for h in handlers {
        let ev_name = h.pattern.name.as_str();
        writeln!(out, "            \"{ev_name}\" => {{").unwrap();
        writeln!(out, "                let (base, anchor) = self.value.get(&(a, b)).copied().unwrap_or(({}_f32, tick));", format_expr_initial(initial_expr)).unwrap();
        writeln!(out, "                let current = base * Self::RATE.powi((tick.saturating_sub(anchor)) as i32);").unwrap();
        // v1: we emit a generic `+ amount` fold. The real emitter would
        // walk `h.body` and lower each `self +=` / `self = ...` stmt into
        // Rust — that's the deeper milestone. Skeleton is enough to
        // validate the shape and give the hash machinery something to
        // observe.
        writeln!(out, "                let updated = current + amount;").unwrap();
        if let Some((lo, hi)) = clamp {
            writeln!(
                out,
                "                let updated = updated.clamp({}_f32, {}_f32);",
                format_expr_initial(lo),
                format_expr_initial(hi),
            )
            .unwrap();
        }
        writeln!(out, "                self.value.insert((a, b), (updated, tick));").unwrap();
        writeln!(out, "            }}").unwrap();
    }
    writeln!(out, "            _ => {{}}").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Suppress an unused-field warning when the view has no handlers.
    let _ = field_name;

    Ok(Some(out))
}

/// Render a small initial/clamp scalar expression as a Rust literal. At v1
/// we handle `LitFloat`, `LitInt`, and `Unary(Neg, LitFloat/Int)` — that
/// covers every shape the spec snippets exercise. Anything richer falls
/// back to a `0.0` placeholder so the emitted code compiles; a future
/// milestone will thread a full expression emitter through here.
fn format_expr_initial(e: &crate::ir::IrExprNode) -> String {
    use crate::ir::IrExpr;
    match &e.kind {
        IrExpr::LitFloat(v) => format_f32(*v as f32),
        IrExpr::LitInt(i) => format_f32(*i as f32),
        IrExpr::Unary(crate::ast::UnOp::Neg, inner) => match &inner.kind {
            IrExpr::LitFloat(v) => format_f32(-(*v as f32)),
            IrExpr::LitInt(i) => format_f32(-(*i as f32)),
            _ => "0.0".to_string(),
        },
        _ => "0.0".to_string(),
    }
}

fn format_f32(v: f32) -> String {
    // Preserve a `.` so rustc parses as f32 when suffixed.
    let s = format!("{v}");
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

fn to_pascal(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper = true;
    for ch in name.chars() {
        if ch == '_' {
            upper = true;
            continue;
        }
        if upper {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_snake(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::{
        DecayHint, DecayUnit, FoldHandlerIR, IrEventPattern, IrExpr, IrExprNode, IrType, ViewBodyIR,
        ViewIR,
    };

    fn node(kind: IrExpr) -> IrExprNode {
        IrExprNode {
            kind,
            span: Span::dummy(),
        }
    }

    fn threat_view() -> ViewIR {
        ViewIR {
            name: "threat_level".to_string(),
            params: vec![],
            return_ty: IrType::F32,
            body: ViewBodyIR::Fold {
                initial: node(IrExpr::LitFloat(0.0)),
                handlers: vec![
                    FoldHandlerIR {
                        pattern: IrEventPattern {
                            name: "AgentAttacked".to_string(),
                            event: None,
                            bindings: vec![],
                            span: Span::dummy(),
                        },
                        body: vec![],
                        span: Span::dummy(),
                    },
                    FoldHandlerIR {
                        pattern: IrEventPattern {
                            name: "EffectDamageApplied".to_string(),
                            event: None,
                            bindings: vec![],
                            span: Span::dummy(),
                        },
                        body: vec![],
                        span: Span::dummy(),
                    },
                ],
                clamp: Some((node(IrExpr::LitFloat(0.0)), node(IrExpr::LitFloat(1000.0)))),
            },
            annotations: vec![],
            decay: Some(DecayHint {
                rate: 0.98,
                per: DecayUnit::Tick,
                span: Span::dummy(),
            }),
            span: Span::dummy(),
        }
    }

    #[test]
    fn emits_anchor_pattern_struct_with_rate() {
        let v = threat_view();
        let out = emit_decay_view(&v).unwrap().expect("decay hint present");
        assert!(out.contains("pub struct ThreatLevel"));
        assert!(out.contains("pub const RATE: f32 = 0.98_f32;"));
        assert!(out.contains("pub fn get(&self, a: i64, b: i64, tick: u32) -> f32"));
        assert!(out.contains("pub fn fold_event"));
        assert!(out.contains("\"AgentAttacked\" =>"));
        assert!(out.contains("\"EffectDamageApplied\" =>"));
        // Clamp bounds show up in both get() and fold().
        assert!(out.contains(".clamp(0.0_f32, 1000.0_f32)"));
    }

    #[test]
    fn returns_none_when_no_decay_hint() {
        let mut v = threat_view();
        v.decay = None;
        let out = emit_decay_view(&v).unwrap();
        assert!(out.is_none());
    }

    #[test]
    fn errors_when_decay_on_non_fold_body_slips_through() {
        let mut v = threat_view();
        v.body = ViewBodyIR::Expr(node(IrExpr::LitFloat(0.0)));
        let err = emit_decay_view(&v).unwrap_err();
        assert!(matches!(err, EmitError::Unsupported(_)));
    }
}
