//! WGSL emitter for `MovementKernel` — applies the per-agent movement
//! decision (MoveToward / Flee) selected by scoring this tick, writes
//! the new agent position, and emits an `AgentMoved` / `AgentFled`
//! event into the cascade ring.
//!
//! Recovered from the pre-T16 hand-written movement WGSL
//! (`crates/engine_gpu/src/movement.rs:608` at commit `4474566c~1`)
//! and adapted to the post-T16 raw-u32 binding layout. The kernel
//! `include_str!`s `emit_runtime_prelude_wgsl` for event-emission
//! helpers.
//!
//! ## Binding layout
//!
//! | Slot | Name                   | Direction   | Type            |
//! |------|------------------------|-------------|-----------------|
//! | 0    | agents                 | read_write  | array<u32> SoA  |
//! | 1    | scoring                | read        | array<u32> SoA  |
//! | 2    | event_ring_records     | read_write  | array<u32>      |
//! | 3    | event_ring_tail        | read_write  | atomic<u32>     |
//! | 4    | sim_cfg                | read        | array<u32>      |
//! | 5    | cfg                    | uniform     | MovementCfg     |
//!
//! ## Field offsets
//!
//! `agents` is `GpuAgentSlot` SoA (16 u32 stride, 64 bytes):
//! - alive: 4
//! - pos_x: 11, pos_y: 12, pos_z: 13
//!
//! `scoring` is `ScoreOutput` SoA (4 u32 stride, 16 bytes):
//! - chosen_action: 0
//! - chosen_target:  1
//!
//! `sim_cfg` is `SimCfg` SoA (16 u32 stride):
//! - tick: 0
//! - move_speed: 7

use crate::emit_runtime_prelude_wgsl::{
    emit_runtime_prelude_consts, emit_runtime_prelude_wgsl,
};

/// Default event ring capacity. Mirrors
/// `engine_gpu::event_ring::DEFAULT_CAPACITY`.
const DEFAULT_EVENT_RING_CAPACITY: u32 = 65536;

/// Emit the body of `engine_gpu_rules/src/movement.wgsl`. Caller
/// prepends the `// GENERATED by ...` header.
pub fn emit_movement_wgsl() -> String {
    let mut out = String::new();
    out.push_str(&emit_runtime_prelude_consts(DEFAULT_EVENT_RING_CAPACITY));
    out.push_str(
        "\n\
@group(0) @binding(0) var<storage, read_write> agents:             array<u32>;\n\
@group(0) @binding(1) var<storage, read>       scoring:            array<u32>;\n\
@group(0) @binding(2) var<storage, read_write> event_ring_records: array<u32>;\n\
@group(0) @binding(3) var<storage, read_write> event_ring_tail:    atomic<u32>;\n\
@group(0) @binding(4) var<storage, read>       sim_cfg:            array<u32>;\n\
struct MovementCfg { agent_cap: u32, tick: u32, event_ring_capacity: u32, _pad: u32 };\n\
@group(0) @binding(5) var<uniform>             cfg:                MovementCfg;\n\
\n\
// GpuAgentSlot stride (16 u32 = 64 bytes per agent).\n\
const SLOT_STRIDE_U32: u32 = 16u;\n\
const SLOT_OFFSET_ALIVE: u32 = 4u;\n\
const SLOT_OFFSET_POS_X: u32 = 11u;\n\
const SLOT_OFFSET_POS_Y: u32 = 12u;\n\
const SLOT_OFFSET_POS_Z: u32 = 13u;\n\
\n\
// ScoreOutput stride (4 u32 = 16 bytes per agent).\n\
const SCORING_STRIDE_U32: u32 = 4u;\n\
const SCORING_OFFSET_ACTION: u32 = 0u;\n\
const SCORING_OFFSET_TARGET: u32 = 1u;\n\
\n\
// SimCfg field offsets (in u32 indices).\n\
const SIM_CFG_OFFSET_TICK: u32 = 0u;\n\
const SIM_CFG_OFFSET_MOVE_SPEED: u32 = 7u;\n\
\n\
// Action ids (mirror engine action enum).\n\
const ACTION_MOVE_TOWARD: u32 = 1u;\n\
const ACTION_FLEE: u32 = 2u;\n\
const NO_TARGET: u32 = 0xFFFFFFFFu;\n\
\n\
fn agent_alive(slot: u32) -> u32 {\n\
    return agents[slot * SLOT_STRIDE_U32 + SLOT_OFFSET_ALIVE];\n\
}\n\
\n\
fn agent_pos(slot: u32) -> vec3<f32> {\n\
    let base = slot * SLOT_STRIDE_U32;\n\
    return vec3<f32>(\n\
        bitcast<f32>(agents[base + SLOT_OFFSET_POS_X]),\n\
        bitcast<f32>(agents[base + SLOT_OFFSET_POS_Y]),\n\
        bitcast<f32>(agents[base + SLOT_OFFSET_POS_Z]),\n\
    );\n\
}\n\
\n\
fn set_agent_pos(slot: u32, p: vec3<f32>) {\n\
    let base = slot * SLOT_STRIDE_U32;\n\
    agents[base + SLOT_OFFSET_POS_X] = bitcast<u32>(p.x);\n\
    agents[base + SLOT_OFFSET_POS_Y] = bitcast<u32>(p.y);\n\
    agents[base + SLOT_OFFSET_POS_Z] = bitcast<u32>(p.z);\n\
}\n\
\n\
fn scoring_action(slot: u32) -> u32 {\n\
    return scoring[slot * SCORING_STRIDE_U32 + SCORING_OFFSET_ACTION];\n\
}\n\
\n\
fn scoring_target(slot: u32) -> u32 {\n\
    return scoring[slot * SCORING_STRIDE_U32 + SCORING_OFFSET_TARGET];\n\
}\n\
\n\
fn sim_cfg_tick() -> u32 {\n\
    return sim_cfg[SIM_CFG_OFFSET_TICK];\n\
}\n\
\n\
fn sim_cfg_move_speed() -> f32 {\n\
    return bitcast<f32>(sim_cfg[SIM_CFG_OFFSET_MOVE_SPEED]);\n\
}\n\
\n\
fn normalize_or_zero(v: vec3<f32>) -> vec3<f32> {\n\
    let len2 = v.x * v.x + v.y * v.y + v.z * v.z;\n\
    if (len2 <= 0.0) { return vec3<f32>(0.0, 0.0, 0.0); }\n\
    let inv = 1.0 / sqrt(len2);\n\
    return v * inv;\n\
}\n\
\n",
    );
    out.push_str(&emit_runtime_prelude_wgsl());
    out.push_str(
        "\n\
@compute @workgroup_size(64)\n\
fn cs_movement(@builtin(global_invocation_id) gid: vec3<u32>) {\n\
    let slot = gid.x;\n\
    if (slot >= cfg.agent_cap) { return; }\n\
    if (agent_alive(slot) == 0u) { return; }\n\
\n\
    let self_id = slot + 1u;\n\
    let action = scoring_action(slot);\n\
    let t_slot_raw = scoring_target(slot);\n\
    let tick = sim_cfg_tick();\n\
    let self_pos = agent_pos(slot);\n\
\n\
    if (action == ACTION_MOVE_TOWARD) {\n\
        if (t_slot_raw == NO_TARGET) { return; }\n\
        if (t_slot_raw >= cfg.agent_cap) { return; }\n\
        if (agent_alive(t_slot_raw) == 0u) { return; }\n\
        let target_pos = agent_pos(t_slot_raw);\n\
        let delta = target_pos - self_pos;\n\
        if (delta.x * delta.x + delta.y * delta.y + delta.z * delta.z <= 0.0) { return; }\n\
        let dir = normalize_or_zero(delta);\n\
        let speed = sim_cfg_move_speed();\n\
        let new_pos = self_pos + dir * speed;\n\
        set_agent_pos(slot, new_pos);\n\
        let _idx = gpu_emit_agent_moved(self_id, tick,\n\
                                        self_pos.x, self_pos.y, self_pos.z,\n\
                                        new_pos.x, new_pos.y, new_pos.z);\n\
        return;\n\
    }\n\
\n\
    if (action == ACTION_FLEE) {\n\
        if (t_slot_raw == NO_TARGET) { return; }\n\
        if (t_slot_raw >= cfg.agent_cap) { return; }\n\
        if (agent_alive(t_slot_raw) == 0u) { return; }\n\
        let threat_pos = agent_pos(t_slot_raw);\n\
        let away = normalize_or_zero(self_pos - threat_pos);\n\
        if (away.x * away.x + away.y * away.y + away.z * away.z <= 0.0) { return; }\n\
        let speed = sim_cfg_move_speed();\n\
        let new_pos = self_pos + away * speed;\n\
        set_agent_pos(slot, new_pos);\n\
        let _idx = gpu_emit_agent_fled(self_id, tick,\n\
                                       self_pos.x, self_pos.y, self_pos.z,\n\
                                       new_pos.x, new_pos.y, new_pos.z);\n\
        return;\n\
    }\n\
}\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn movement_naga_parses() {
        let src = emit_movement_wgsl();
        naga::front::wgsl::parse_str(&src)
            .map_err(|e| format!("--- WGSL ---\n{src}\n--- naga error ---\n{}", e.emit_to_string(&src)))
            .expect("emit_movement_wgsl should parse cleanly");
    }

    #[test]
    fn movement_uses_prelude_helpers() {
        let src = emit_movement_wgsl();
        assert!(src.contains("gpu_emit_agent_moved"));
        assert!(src.contains("gpu_emit_agent_fled"));
    }
}
