//! Emit a complete Rust kernel module from a `KernelSpec`. Walks the
//! spec ONCE; calls each lowering in lockstep so the four outputs
//! (BGL entries, WGSL bindings — emitted by the WGSL side, but the
//! type info matches; Rust BindGroupEntry constructions, Rust
//! Bindings struct fields) cannot drift.
//!
//! Output is the full file content for
//! `engine_gpu_rules/src/<name>.rs` — the kernel impl + Bindings
//! struct + Cfg struct + `impl Kernel for <Pascal>Kernel { ... }`.
//! The companion WGSL file (`engine_gpu_rules/src/<name>.wgsl`) is
//! emitted separately by the per-kernel WGSL emitter; that emitter
//! calls `kernel_lowerings::lower_wgsl_bindings(spec)` for the
//! `@group(0)` declarations and appends the per-kernel body.

use std::fmt::Write;

use crate::kernel_binding_ir::{BgSource, KernelSpec};
use crate::kernel_lowerings::{
    lower_rust_bg_entries, lower_rust_bgl_entries, lower_rust_bind_body,
    lower_rust_bindings_struct_fields,
};

/// Emit the full Rust kernel module — pipeline + BGL + Bindings struct
/// + Cfg struct + build_cfg + bind + record. All four lowerings are
/// called in sequence from the same `KernelSpec`.
///
/// The kernel module is layout-stable: any spec change updates every
/// lowering that depends on it, so BGL count, struct fields, and
/// BindGroupEntry construction stay aligned.
pub fn emit_kernel_module_rs(spec: &KernelSpec) -> String {
    let pascal = &spec.pascal;
    let name = &spec.name;
    let entry_point = &spec.entry_point;
    let cfg_struct = &spec.cfg_struct;
    let cfg_struct_decl = &spec.cfg_struct_decl;
    let cfg_build_expr = &spec.cfg_build_expr;

    let bgl_entries = lower_rust_bgl_entries(spec);
    let bg_entries = lower_rust_bg_entries(spec);
    let bindings_struct_fields = lower_rust_bindings_struct_fields(spec);
    let bind_body = lower_rust_bind_body(spec);

    // Detect view-handle accessor — fold kernels need to destructure
    // (primary, anchor, ids) at the start of bind(). For now no spec
    // uses BgSource::ViewHandle; fold kernels build their own bind
    // body via custom emit (see emit_view_fold_kernel.rs).
    debug_assert!(
        spec.bindings
            .iter()
            .all(|b| !matches!(b.bg_source, BgSource::ViewHandle { .. })),
        "ViewHandle bg_source not supported by emit_kernel_module_rs; \
         fold kernels emit their bind() body separately"
    );

    let mut out = String::new();
    writeln!(
        out,
        "// GENERATED by dsl_compiler::emit_kernel_module. Do not edit by hand."
    )
    .unwrap();
    writeln!(
        out,
        "// Regenerate with `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use crate::binding_sources::BindingSources;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub struct {pascal}Kernel {{").unwrap();
    writeln!(out, "    pipeline: wgpu::ComputePipeline,").unwrap();
    writeln!(out, "    bgl: wgpu::BindGroupLayout,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub struct {pascal}Bindings<'a> {{").unwrap();
    out.push_str(&bindings_struct_fields);
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    out.push_str(cfg_struct_decl);
    if !cfg_struct_decl.ends_with('\n') {
        writeln!(out).unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "const SHADER_SRC: &str = include_str!(\"{name}.wgsl\");").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl crate::Kernel for {pascal}Kernel {{").unwrap();
    writeln!(out, "    type Bindings<'a> = {pascal}Bindings<'a>;").unwrap();
    writeln!(out, "    type Cfg = {cfg_struct};").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    fn new(device: &wgpu::Device) -> Self {{").unwrap();
    writeln!(
        out,
        "        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::{name}::wgsl\"),"
    )
    .unwrap();
    writeln!(
        out,
        "            source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),"
    )
    .unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(
        out,
        "        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::{name}::bgl\"),"
    )
    .unwrap();
    writeln!(out, "            entries: &[").unwrap();
    out.push_str(&bgl_entries);
    writeln!(out, "            ],").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(
        out,
        "        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::{name}::pl\"),"
    )
    .unwrap();
    writeln!(out, "            bind_group_layouts: &[&bgl],").unwrap();
    writeln!(out, "            push_constant_ranges: &[],").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(
        out,
        "        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::{name}::pipeline\"),"
    )
    .unwrap();
    writeln!(out, "            layout: Some(&pl),").unwrap();
    writeln!(out, "            module: &shader,").unwrap();
    writeln!(out, "            entry_point: Some(\"{entry_point}\"),").unwrap();
    writeln!(out, "            compilation_options: Default::default(),").unwrap();
    writeln!(out, "            cache: None,").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        Self {{ pipeline, bgl }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "    fn build_cfg(&self, state: &engine::state::SimState) -> {cfg_struct} {{"
    )
    .unwrap();
    writeln!(out, "        let _ = state;").unwrap();
    writeln!(out, "        {cfg_build_expr}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> {pascal}Bindings<'a> {{"
    )
    .unwrap();
    writeln!(out, "        let _ = sources;").unwrap();
    writeln!(out, "        {pascal}Bindings {{").unwrap();
    out.push_str(&bind_body);
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &{pascal}Bindings<'_>, agent_cap: u32) {{"
    )
    .unwrap();
    writeln!(out, "        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {{").unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::{name}::bg\"),"
    )
    .unwrap();
    writeln!(out, "            layout: &self.bgl,").unwrap();
    writeln!(out, "            entries: &[").unwrap();
    out.push_str(&bg_entries);
    writeln!(out, "            ],").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(
        out,
        "        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::{name}::pass\"),"
    )
    .unwrap();
    writeln!(out, "            timestamp_writes: None,").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        pass.set_pipeline(&self.pipeline);").unwrap();
    writeln!(out, "        pass.set_bind_group(0, &bg, &[]);").unwrap();
    writeln!(
        out,
        "        pass.dispatch_workgroups((agent_cap + 63) / 64, 1, 1);"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kernel_binding_ir::{AccessMode, BgSource, KernelBinding, KernelKind, KernelSpec};

    fn make_demo_spec() -> KernelSpec {
        KernelSpec {
            name: "fused_mask".into(),
            pascal: "FusedMask".into(),
            entry_point: "cs_fused_masks".into(),
            cfg_struct: "FusedMaskCfg".into(),
            cfg_build_expr: "FusedMaskCfg { agent_cap: state.agent_cap(), num_mask_words: (state.agent_cap() + 31) / 32, _pad0: 0, _pad1: 0 }".into(),
            cfg_struct_decl: "#[repr(C)]\n#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]\npub struct FusedMaskCfg {\n    pub agent_cap: u32,\n    pub num_mask_words: u32,\n    pub _pad0: u32,\n    pub _pad1: u32,\n}".into(),
            bindings: vec![
                KernelBinding {
                    slot: 0,
                    name: "agents".into(),
                    access: AccessMode::ReadStorage,
                    wgsl_ty: "array<u32>".into(),
                    bg_source: BgSource::External("agents".into()),
                },
                KernelBinding {
                    slot: 1,
                    name: "mask_bitmaps".into(),
                    access: AccessMode::AtomicStorage,
                    wgsl_ty: "u32".into(),
                    bg_source: BgSource::Transient("mask_bitmaps".into()),
                },
                KernelBinding {
                    slot: 2,
                    name: "sim_cfg".into(),
                    access: AccessMode::ReadStorage,
                    wgsl_ty: "array<u32>".into(),
                    bg_source: BgSource::External("sim_cfg".into()),
                },
                KernelBinding {
                    slot: 3,
                    name: "cfg".into(),
                    access: AccessMode::Uniform,
                    wgsl_ty: "FusedMaskCfg".into(),
                    bg_source: BgSource::Cfg,
                },
            ],
            kind: KernelKind::Generic,
        }
    }

    #[test]
    fn emits_kernel_struct_with_pipeline_and_bgl() {
        let rs = emit_kernel_module_rs(&make_demo_spec());
        assert!(rs.contains("pub struct FusedMaskKernel {"));
        assert!(rs.contains("pipeline: wgpu::ComputePipeline,"));
        assert!(rs.contains("bgl: wgpu::BindGroupLayout,"));
    }

    #[test]
    fn emits_bindings_struct_with_one_field_per_binding() {
        let rs = emit_kernel_module_rs(&make_demo_spec());
        assert!(rs.contains("pub struct FusedMaskBindings<'a> {"));
        assert!(rs.contains("pub agents: &'a wgpu::Buffer,"));
        assert!(rs.contains("pub mask_bitmaps: &'a wgpu::Buffer,"));
        assert!(rs.contains("pub sim_cfg: &'a wgpu::Buffer,"));
        assert!(rs.contains("pub cfg: &'a wgpu::Buffer,"));
    }

    #[test]
    fn emits_bgl_entries_with_correct_helpers() {
        let rs = emit_kernel_module_rs(&make_demo_spec());
        assert!(rs.contains("crate::fused_mask::bgl_storage(0, true)"));
        assert!(rs.contains("crate::fused_mask::bgl_storage(1, false)"));
        assert!(rs.contains("crate::fused_mask::bgl_storage(2, true)"));
        assert!(rs.contains("crate::fused_mask::bgl_uniform(3)"));
    }

    #[test]
    fn emits_entry_point_match_kernel_spec() {
        let rs = emit_kernel_module_rs(&make_demo_spec());
        assert!(rs.contains("entry_point: Some(\"cs_fused_masks\")"));
    }

    #[test]
    fn emits_bind_body_routing_to_sources() {
        let rs = emit_kernel_module_rs(&make_demo_spec());
        assert!(rs.contains("agents: sources.external.agents,"));
        assert!(rs.contains("mask_bitmaps: sources.transient.mask_bitmaps,"));
        assert!(rs.contains("sim_cfg: sources.external.sim_cfg,"));
        assert!(rs.contains("cfg: cfg,"));
    }

    #[test]
    fn emits_bg_entries_in_slot_order() {
        let rs = emit_kernel_module_rs(&make_demo_spec());
        assert!(rs.contains("binding: 0, resource: bindings.agents.as_entire_binding()"));
        assert!(rs.contains("binding: 1, resource: bindings.mask_bitmaps.as_entire_binding()"));
        assert!(rs.contains("binding: 2, resource: bindings.sim_cfg.as_entire_binding()"));
        assert!(rs.contains("binding: 3, resource: bindings.cfg.as_entire_binding()"));
    }

    #[test]
    fn bgl_entry_count_matches_bg_entry_count() {
        // Structural property — the test that gpu_pipeline_smoke
        // ultimately enforces: count(BGL entries) == count(BindGroup
        // entries). One spec, one walk, one count.
        let spec = make_demo_spec();
        let rs = emit_kernel_module_rs(&spec);
        let bgl_count = rs.matches("crate::fused_mask::bgl_").count();
        let bg_count = rs.matches("wgpu::BindGroupEntry { binding:").count();
        assert_eq!(bgl_count, spec.bindings.len());
        assert_eq!(bg_count, spec.bindings.len());
        assert_eq!(bgl_count, bg_count);
    }
}
