//! Rust emission for compiler milestone 4 — `mask` predicates.
//!
//! Every `mask <Name>(<args>) when <predicate>` declaration produces:
//!
//! 1. A standalone module file `mask/<snake_case>.rs` carrying a pure
//!    predicate fn `pub fn mask_<name>(state: &SimState, self_id: AgentId,
//!    <args>: AgentId) -> bool`. The body is the mechanical lowering of
//!    `<predicate>` as a short-circuiting chain of `if !<clause> { return
//!    false; }` statements.
//! 2. An entry in the aggregate `mask/mod.rs`'s `register()` stub (no-op
//!    for milestone 4 — the engine imports the per-mask fns directly).
//!
//! The emitter is deliberately verbose — `writeln!` into a `String`, no
//! macros, no helper traits beyond lowering utilities. Reviewers should be
//! able to skim the emitted output without tracing abstractions.
//!
//! Body lowering surface (milestone 4): `&&`-chains of boolean clauses,
//! `agents.*` accessor calls (with `agents.pos(x)` hoisted into a prelude
//! `let x_pos = ...` binding so guard lines stay short), `distance`
//! builtin, binary comparisons and arithmetic, `UnresolvedCall` routed to
//! `crate::rules::<name>` for hand-written game views that haven't been
//! DSL-declared yet (e.g. `is_hostile`). Any IR construct outside this
//! surface raises `EmitError::Unsupported`.
//!
//! ## Rustfmt stability
//!
//! The xtask's scaffolded-kinds write path (`write_scaffolded_kinds` in
//! `src/bin/xtask/compile_dsl_cmd.rs`) does *not* run rustfmt on mask
//! files; only the events + physics paths are rustfmt'd. But the `--check`
//! CI guard rustfmts the in-memory emission before comparing. That means
//! the emitter has to produce rustfmt-stable output on its own: multi-line
//! `if` bodies, hoisted pos bindings, balanced paren usage. If rustfmt
//! reformats the emission, `--check` reports a spurious mismatch. Keep
//! changes here round-trippable through `rustfmt --edition=2021`.

use std::fmt::Write;

use crate::ast::{BinOp, UnOp};
use crate::ir::{
    Builtin, IrActionHeadShape, IrCallArg, IrExpr, IrExprNode, MaskIR, NamespaceId,
};

/// Errors raised during mask emission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    /// Some IR construct isn't supported by the milestone-4 emitter yet.
    /// Carries a short diagnostic string with the offending shape.
    Unsupported(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::Unsupported(s) => write!(f, "mask emission: {s}"),
        }
    }
}

impl std::error::Error for EmitError {}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/// Emit a single mask module file (`mask/<snake_case>.rs`). Called once per
/// `MaskIR`; result is written to the engine's generated `mask/` directory.
///
/// Returns `Err(String)` (not `EmitError`) so the xtask call site stays
/// symmetric with `emit_scoring` / `emit_entity`. Internally we still use
/// the typed `EmitError` for precise diagnostics.
pub fn emit_mask(mask: &MaskIR, source_file: Option<&str>) -> Result<String, String> {
    emit_mask_result(mask, source_file).map_err(|e| e.to_string())
}

fn emit_mask_result(mask: &MaskIR, source_file: Option<&str>) -> Result<String, EmitError> {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    emit_imports(&mut out);
    emit_predicate_fn(&mut out, mask)?;
    Ok(out)
}

/// Emit the aggregate `mask/mod.rs`. The aggregator re-exports each
/// per-mask fn (`pub use <stem>::mask_<stem>;`) and exposes a `pub fn
/// register()` stub. Milestone 4 keeps the stub a no-op: the engine's
/// mask-build path calls the per-mask fns by name. `register()` is kept
/// on the API surface so SPIR-V / GPU-side mask dispatch can grow here
/// later without adding a new entry point.
pub fn emit_mask_mod(masks: &[MaskIR]) -> String {
    let mut sorted: Vec<&MaskIR> = masks.iter().collect();
    sorted.sort_by(|a, b| a.head.name.cmp(&b.head.name));

    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();

    if sorted.is_empty() {
        writeln!(out, "// No `mask` declarations in scope. `register()` is a no-op.").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "/// Called from the engine's mask-build path. With zero masks in").unwrap();
        writeln!(out, "/// scope this is a no-op; the per-mask fns are imported by the").unwrap();
        writeln!(out, "/// call site directly when any mask does land.").unwrap();
        writeln!(out, "pub fn register() {{}}").unwrap();
        return out;
    }

    for m in &sorted {
        writeln!(out, "pub mod {};", snake_case(&m.head.name)).unwrap();
    }
    writeln!(out).unwrap();
    for m in &sorted {
        let stem = snake_case(&m.head.name);
        writeln!(out, "pub use {stem}::mask_{stem};").unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "/// Called from the engine's mask-build path. For milestone 4 this").unwrap();
    writeln!(out, "/// is a no-op shim — the engine imports each per-mask fn directly").unwrap();
    writeln!(out, "/// via the `pub use` re-exports above. `register()` is kept on the").unwrap();
    writeln!(out, "/// surface so SPIR-V / GPU-side mask dispatch can grow here later").unwrap();
    writeln!(out, "/// without adding new scaffolding.").unwrap();
    writeln!(out, "pub fn register() {{}}").unwrap();
    out
}

// ---------------------------------------------------------------------------
// Header / imports
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(out, "// GENERATED by dsl_compiler from {}.", path).unwrap(),
        None => writeln!(out, "// GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "// Do not edit by hand.").unwrap();
    writeln!(out).unwrap();
}

fn emit_imports(out: &mut String) {
    writeln!(out, "use crate::ids::AgentId;").unwrap();
    writeln!(out, "use crate::state::SimState;").unwrap();
    writeln!(out).unwrap();
}

// ---------------------------------------------------------------------------
// Predicate fn
// ---------------------------------------------------------------------------

/// Indent depth for top-level statements inside the predicate body: 4 spaces.
const BASE_INDENT: usize = 4;

fn emit_predicate_fn(out: &mut String, mask: &MaskIR) -> Result<(), EmitError> {
    let fn_name = format!("mask_{}", snake_case(&mask.head.name));

    // Param list: `state: &SimState`, `self_id: AgentId` plus one
    // positional param per action-head slot. Milestone 4 only supports
    // the positional shape — `Named` heads would require a richer call
    // convention that we don't need for the attack mask.
    let mut params = vec!["state: &SimState".to_string(), "self_id: AgentId".to_string()];
    match &mask.head.shape {
        IrActionHeadShape::None => {}
        IrActionHeadShape::Positional(binds) => {
            for (name, _local) in binds {
                if name == "_" {
                    return Err(EmitError::Unsupported(format!(
                        "`_` placeholder arg in mask `{}` head; name the arg",
                        mask.head.name
                    )));
                }
                params.push(format!("{name}: AgentId"));
            }
        }
        IrActionHeadShape::Named(_) => {
            return Err(EmitError::Unsupported(format!(
                "named-field action head on mask `{}` not supported in milestone 4",
                mask.head.name
            )));
        }
    }

    writeln!(
        out,
        "/// Predicate: can `self_id` issue this mask's action head against the given target?"
    )
    .unwrap();
    writeln!(
        out,
        "/// Lowered from `mask {}` in `assets/sim/masks.sim`.",
        mask.head.name
    )
    .unwrap();
    writeln!(out, "pub fn {fn_name}({}) -> bool {{", params.join(", ")).unwrap();
    emit_predicate_body(out, &mask.predicate)?;
    writeln!(out, "}}").unwrap();
    Ok(())
}

/// Lower the predicate expression as a chain of `if !(<clause>) { return
/// false; }` statements, split on top-level `&&` for short-circuit
/// readability. Anything that doesn't fit that shape is emitted as a
/// single clause guard. The final `true` fallthrough means "every clause
/// passed".
///
/// Before emitting the guards we walk the predicate once to hoist every
/// `agents.pos(<local>)` call into a prelude `let <local>_pos = state.
/// agent_pos(<local>).unwrap_or(Vec3::ZERO);` binding. The hoist keeps
/// per-guard lines short enough that rustfmt treats the emission as
/// already-formatted — critical because the xtask's scaffolded-kinds
/// write path doesn't run rustfmt on mask files.
fn emit_predicate_body(out: &mut String, predicate: &IrExprNode) -> Result<(), EmitError> {
    let mut clauses: Vec<&IrExprNode> = Vec::new();
    flatten_and(predicate, &mut clauses);

    let mut hoisted: Vec<String> = Vec::new();
    for clause in &clauses {
        collect_pos_hoists(clause, &mut hoisted);
    }

    let pad = " ".repeat(BASE_INDENT);
    let inner_pad = " ".repeat(BASE_INDENT + 4);
    for local in &hoisted {
        let arg = if local == "self" { "self_id".to_string() } else { local.clone() };
        let binding = pos_binding_name(local);
        writeln!(
            out,
            "{pad}let {binding} = state.agent_pos({arg}).unwrap_or(glam::Vec3::ZERO);"
        )
        .unwrap();
    }
    for clause in &clauses {
        let cond = lower_clause(clause, &hoisted)?;
        writeln!(out, "{pad}if !{cond} {{").unwrap();
        writeln!(out, "{inner_pad}return false;").unwrap();
        writeln!(out, "{pad}}}").unwrap();
    }
    writeln!(out, "{pad}true").unwrap();
    Ok(())
}

/// Walk a binary `&&` tree and collect every leaf clause in source order.
/// Non-`&&` expressions are treated as a single-leaf clause.
fn flatten_and<'a>(node: &'a IrExprNode, out: &mut Vec<&'a IrExprNode>) {
    if let IrExpr::Binary(BinOp::And, lhs, rhs) = &node.kind {
        flatten_and(lhs, out);
        flatten_and(rhs, out);
    } else {
        out.push(node);
    }
}

/// Walk the predicate AST and record every `agents.pos(<Local>)` call's
/// source-level local name, de-duplicated and in first-seen order. Only
/// `agents.pos` of a bare `Local` argument is hoisted — more complex
/// expressions stay inline.
fn collect_pos_hoists(node: &IrExprNode, out: &mut Vec<String>) {
    match &node.kind {
        IrExpr::NamespaceCall { ns, method, args }
            if *ns == NamespaceId::Agents && method == "pos" =>
        {
            if args.len() == 1 {
                if let IrExpr::Local(_, name) = &args[0].value.kind {
                    if !out.contains(name) {
                        out.push(name.clone());
                    }
                }
            }
            for a in args {
                collect_pos_hoists(&a.value, out);
            }
        }
        IrExpr::NamespaceCall { args, .. }
        | IrExpr::BuiltinCall(_, args)
        | IrExpr::UnresolvedCall(_, args) => {
            for a in args {
                collect_pos_hoists(&a.value, out);
            }
        }
        IrExpr::Binary(_, l, r) => {
            collect_pos_hoists(l, out);
            collect_pos_hoists(r, out);
        }
        IrExpr::Unary(_, r) => collect_pos_hoists(r, out),
        _ => {}
    }
}

/// Name of the hoisted `let` binding for `agents.pos(<local>)`. `self` maps
/// to `self_pos`; other locals map to `<name>_pos`.
fn pos_binding_name(local: &str) -> String {
    if local == "self" {
        "self_pos".into()
    } else {
        format!("{local}_pos")
    }
}

/// Lower a single top-level clause: the negation target inside `if !(...)`.
/// Callers place the result inside `()` — we strip one layer of outer
/// parens from the recursive lowering so the `!(...)` form doesn't
/// produce a double-paren `!((...))` that rustfmt would collapse later.
fn lower_clause(node: &IrExprNode, hoisted: &[String]) -> Result<String, EmitError> {
    let raw = lower_expr_with_hoist(node, hoisted)?;
    let stripped = if raw.starts_with('(') && raw.ends_with(')') && balanced(&raw) {
        raw[1..raw.len() - 1].to_string()
    } else {
        raw
    };
    Ok(format!("({stripped})"))
}

/// True iff the string's outer `(` matches the outer `)`. Used by
/// `lower_clause` to avoid stripping parens that don't belong to the
/// outermost pair (e.g. `(a) + (b)` — stripping outer `(` / `)` there
/// would produce `a) + (b`).
fn balanced(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.first() != Some(&b'(') || bytes.last() != Some(&b')') {
        return false;
    }
    let mut depth: i32 = 0;
    for (i, b) in bytes.iter().enumerate() {
        match b {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 && i != bytes.len() - 1 {
                    return false;
                }
            }
            _ => {}
        }
    }
    depth == 0
}

// ---------------------------------------------------------------------------
// Expression lowering
// ---------------------------------------------------------------------------

/// Entry point for non-guard lowering (unit tests); equivalent to
/// `lower_expr_with_hoist(node, &[])`.
#[cfg(test)]
fn lower_expr(node: &IrExprNode) -> Result<String, EmitError> {
    lower_expr_with_hoist(node, &[])
}

/// Lower an expression, substituting hoisted `agents.pos(<local>)` calls
/// with their prelude bindings (`self_pos`, `target_pos`, …).
fn lower_expr_with_hoist(node: &IrExprNode, hoisted: &[String]) -> Result<String, EmitError> {
    lower_expr_kind(&node.kind, hoisted)
}

fn lower_expr_kind(kind: &IrExpr, hoisted: &[String]) -> Result<String, EmitError> {
    match kind {
        IrExpr::LitBool(b) => Ok(if *b { "true".into() } else { "false".into() }),
        IrExpr::LitInt(v) => Ok(format!("{v}")),
        IrExpr::LitFloat(v) => Ok(render_float(*v)),
        IrExpr::LitString(s) => Ok(format!("{s:?}")),
        IrExpr::Local(_, name) => {
            if name == "self" {
                Ok("self_id".into())
            } else {
                Ok(name.clone())
            }
        }
        IrExpr::NamespaceCall { ns, method, args } => {
            // Hoisted agents.pos(<local>) — use the prelude binding.
            if *ns == NamespaceId::Agents && method == "pos" && args.len() == 1 {
                if let IrExpr::Local(_, name) = &args[0].value.kind {
                    if hoisted.iter().any(|h| h == name) {
                        return Ok(pos_binding_name(name));
                    }
                }
            }
            lower_namespace_call(*ns, method, args, hoisted)
        }
        IrExpr::BuiltinCall(b, args) => lower_builtin_call(*b, args, hoisted),
        IrExpr::UnresolvedCall(name, args) => lower_unresolved_call(name, args, hoisted),
        IrExpr::Binary(op, lhs, rhs) => {
            let l = lower_expr_with_hoist(lhs, hoisted)?;
            let r = lower_expr_with_hoist(rhs, hoisted)?;
            Ok(format!("({l} {} {r})", binop_str(*op)))
        }
        IrExpr::Unary(op, rhs) => {
            let r = lower_expr_with_hoist(rhs, hoisted)?;
            Ok(format!("({}{r})", unop_str(*op)))
        }
        other => Err(EmitError::Unsupported(format!(
            "expression shape {other:?} not supported in milestone 4 mask emission"
        ))),
    }
}

fn lower_namespace_call(
    ns: NamespaceId,
    method: &str,
    args: &[IrCallArg],
    hoisted: &[String],
) -> Result<String, EmitError> {
    let lowered = lower_positional_args(args, &format!("{}.{method}", ns.name()), hoisted)?;
    match (ns, method) {
        (NamespaceId::Agents, "alive") => {
            expect_arity(args, 1, "agents.alive")?;
            Ok(format!("state.agent_alive({})", lowered[0]))
        }
        (NamespaceId::Agents, "pos") => {
            expect_arity(args, 1, "agents.pos")?;
            // Mask predicates observe post-decrement state, so `agent_pos`
            // is `Some` for every live slot. Dead slots return `None`; we
            // fall back to `Vec3::ZERO` so the predicate keeps a valid
            // f32 without panicking. Alive-check clauses elsewhere in the
            // predicate gate the meaningful result. Note: this arm only
            // fires for `agents.pos(<non-local>)` — `agents.pos(<local>)`
            // is rewritten to the hoisted binding in `lower_expr_kind`.
            Ok(format!(
                "state.agent_pos({}).unwrap_or(glam::Vec3::ZERO)",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "hp") => {
            expect_arity(args, 1, "agents.hp")?;
            Ok(format!("state.agent_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "shield_hp") => {
            expect_arity(args, 1, "agents.shield_hp")?;
            Ok(format!("state.agent_shield_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        _ => Err(EmitError::Unsupported(format!(
            "stdlib call `{}.{method}` not supported in milestone 4 mask emission",
            ns.name()
        ))),
    }
}

fn lower_builtin_call(
    b: Builtin,
    args: &[IrCallArg],
    hoisted: &[String],
) -> Result<String, EmitError> {
    let lowered = lower_positional_args(args, b.name(), hoisted)?;
    match b {
        Builtin::Distance => {
            expect_arity(args, 2, "distance")?;
            let recv = maybe_paren(&lowered[0]);
            Ok(format!("{recv}.distance({})", lowered[1]))
        }
        Builtin::PlanarDistance => {
            expect_arity(args, 2, "planar_distance")?;
            let lhs = maybe_paren(&lowered[0]);
            let rhs = maybe_paren(&lowered[1]);
            Ok(format!("{lhs}.truncate().distance({rhs}.truncate())"))
        }
        Builtin::Min => {
            expect_arity(args, 2, "min")?;
            Ok(format!("({}).min({})", lowered[0], lowered[1]))
        }
        Builtin::Max => {
            expect_arity(args, 2, "max")?;
            Ok(format!("({}).max({})", lowered[0], lowered[1]))
        }
        Builtin::Abs => {
            expect_arity(args, 1, "abs")?;
            Ok(format!("({}).abs()", lowered[0]))
        }
        _ => Err(EmitError::Unsupported(format!(
            "builtin `{}` not supported in milestone 4 mask emission",
            b.name()
        ))),
    }
}

/// Wrap `s` in parens unless it's already a simple identifier / accessor
/// chain that rustfmt wouldn't add parens to. Reduces `((x)).method()`
/// to `x.method()` for the hoisted-binding common case.
fn maybe_paren(s: &str) -> String {
    let is_simple = s.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '.');
    if is_simple { s.to_string() } else { format!("({s})") }
}

/// Lower a call whose callee couldn't be resolved by the compiler. These
/// are game-view fns the DSL mentions that haven't been lifted into a
/// `view` declaration yet (e.g. `is_hostile`). The convention:
/// `UnresolvedCall("foo", args)` emits `crate::rules::foo(state, args...)`.
/// The corresponding fn must exist hand-written in
/// `crates/engine/src/rules/`. This module shrinks as later milestones
/// let the DSL declare views directly; see `docs/game/compiler_progress.md`
/// row 6.
fn lower_unresolved_call(
    name: &str,
    args: &[IrCallArg],
    hoisted: &[String],
) -> Result<String, EmitError> {
    let lowered = lower_positional_args(args, name, hoisted)?;
    let mut argv = vec!["state".to_string()];
    argv.extend(lowered);
    Ok(format!("crate::rules::{name}({})", argv.join(", ")))
}

fn lower_positional_args(
    args: &[IrCallArg],
    call_name: &str,
    hoisted: &[String],
) -> Result<Vec<String>, EmitError> {
    args.iter()
        .map(|a| {
            if a.name.is_some() {
                return Err(EmitError::Unsupported(format!(
                    "named argument on call `{call_name}` not supported in milestone 4"
                )));
            }
            lower_expr_with_hoist(&a.value, hoisted)
        })
        .collect()
}

fn expect_arity(args: &[IrCallArg], expected: usize, name: &str) -> Result<(), EmitError> {
    if args.len() == expected {
        Ok(())
    } else {
        Err(EmitError::Unsupported(format!(
            "`{name}` expects {expected} arg(s), got {}",
            args.len()
        )))
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
    }
}

fn unop_str(op: UnOp) -> &'static str {
    match op {
        UnOp::Not => "!",
        UnOp::Neg => "-",
    }
}

/// Render a float so it parses back identically. `f64::to_string` drops the
/// trailing `.0` for whole numbers (`3.0` → `"3"`), which would type-infer
/// to an integer in Rust. Always emit at least one fractional digit so
/// the literal stays `f32`/`f64`-typed wherever it's used.
fn render_float(v: f64) -> String {
    let s = format!("{v}");
    if s.contains('.') || s.contains('e') || s.contains('E') || s == "inf" || s == "-inf" || s == "NaN"
    {
        s
    } else {
        format!("{s}.0")
    }
}

// ---------------------------------------------------------------------------
// Naming utilities — kept identical to emit_physics.rs. If either drifts,
// both must move to a shared util module.
// ---------------------------------------------------------------------------

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::{
        IrActionHead, IrActionHeadShape, IrCallArg, IrExpr, IrExprNode, LocalRef, MaskIR,
        NamespaceId,
    };

    fn span() -> Span {
        Span::dummy()
    }

    fn local(name: &str, id: u16) -> IrExprNode {
        IrExprNode { kind: IrExpr::Local(LocalRef(id), name.to_string()), span: span() }
    }

    fn ns_call(ns: NamespaceId, method: &str, args: Vec<IrExprNode>) -> IrExprNode {
        IrExprNode {
            kind: IrExpr::NamespaceCall {
                ns,
                method: method.to_string(),
                args: args
                    .into_iter()
                    .map(|a| IrCallArg { name: None, value: a, span: span() })
                    .collect(),
            },
            span: span(),
        }
    }

    fn unresolved(name: &str, args: Vec<IrExprNode>) -> IrExprNode {
        IrExprNode {
            kind: IrExpr::UnresolvedCall(
                name.to_string(),
                args.into_iter()
                    .map(|a| IrCallArg { name: None, value: a, span: span() })
                    .collect(),
            ),
            span: span(),
        }
    }

    fn builtin(b: Builtin, args: Vec<IrExprNode>) -> IrExprNode {
        IrExprNode {
            kind: IrExpr::BuiltinCall(
                b,
                args.into_iter()
                    .map(|a| IrCallArg { name: None, value: a, span: span() })
                    .collect(),
            ),
            span: span(),
        }
    }

    fn binop(op: BinOp, lhs: IrExprNode, rhs: IrExprNode) -> IrExprNode {
        IrExprNode { kind: IrExpr::Binary(op, Box::new(lhs), Box::new(rhs)), span: span() }
    }

    fn lit_float(v: f64) -> IrExprNode {
        IrExprNode { kind: IrExpr::LitFloat(v), span: span() }
    }

    /// Build the attack-mask IR that `masks.sim` lowers to. Predicate:
    /// `agents.alive(target) && is_hostile(self, target) &&
    ///  distance(agents.pos(self), agents.pos(target)) < 2.0`.
    fn attack_mask_ir() -> MaskIR {
        let self_local = local("self", 0);
        let target_local = local("target", 1);

        let alive = ns_call(NamespaceId::Agents, "alive", vec![target_local.clone()]);
        let hostile = unresolved(
            "is_hostile",
            vec![self_local.clone(), target_local.clone()],
        );
        let self_pos = ns_call(NamespaceId::Agents, "pos", vec![self_local.clone()]);
        let target_pos = ns_call(NamespaceId::Agents, "pos", vec![target_local.clone()]);
        let dist = builtin(Builtin::Distance, vec![self_pos, target_pos]);
        let lt = binop(BinOp::Lt, dist, lit_float(2.0));
        let and1 = binop(BinOp::And, alive, hostile);
        let predicate = binop(BinOp::And, and1, lt);

        MaskIR {
            head: IrActionHead {
                name: "Attack".into(),
                shape: IrActionHeadShape::Positional(vec![("target".into(), LocalRef(1))]),
                span: span(),
            },
            predicate,
            annotations: vec![],
            span: span(),
        }
    }

    #[test]
    fn attack_mask_emits_expected_shape() {
        let mask = attack_mask_ir();
        let out = emit_mask(&mask, Some("assets/sim/masks.sim")).unwrap();

        // Header + imports.
        assert!(out.contains("// GENERATED by dsl_compiler from assets/sim/masks.sim."));
        assert!(out.contains("use crate::ids::AgentId;"));
        assert!(out.contains("use crate::state::SimState;"));

        // Fn signature with `self_id` + head-argument `target`.
        assert!(
            out.contains(
                "pub fn mask_attack(state: &SimState, self_id: AgentId, target: AgentId) -> bool {"
            ),
            "unexpected signature in:\n{out}"
        );

        // Hoisted pos bindings — one per unique local referenced via
        // agents.pos(...). `self` → `self_pos` (from `self_id`); `target`
        // → `target_pos` (from `target`).
        assert!(
            out.contains("let self_pos = state.agent_pos(self_id).unwrap_or(glam::Vec3::ZERO);"),
            "missing hoisted self_pos in:\n{out}"
        );
        assert!(
            out.contains("let target_pos = state.agent_pos(target).unwrap_or(glam::Vec3::ZERO);"),
            "missing hoisted target_pos in:\n{out}"
        );

        // Alive clause.
        assert!(
            out.contains("if !(state.agent_alive(target)) {"),
            "missing alive guard in:\n{out}"
        );

        // Unresolved `is_hostile` call routed through `crate::rules::*`.
        assert!(
            out.contains("if !(crate::rules::is_hostile(state, self_id, target)) {"),
            "missing is_hostile guard in:\n{out}"
        );

        // Distance clause using the hoisted bindings and short-circuit
        // multi-line `if` body.
        assert!(
            out.contains("if !(self_pos.distance(target_pos) < 2.0) {"),
            "missing distance guard in:\n{out}"
        );
        assert!(
            out.contains("        return false;"),
            "missing return in guard body:\n{out}"
        );
        // Trailing fallthrough.
        assert!(out.contains("    true\n}"), "missing true fallthrough in:\n{out}");
    }

    #[test]
    fn lower_expr_local_rewrites_self() {
        let out = lower_expr(&local("self", 0)).unwrap();
        assert_eq!(out, "self_id");
    }

    #[test]
    fn aggregate_mod_reexports_mask_fn() {
        let mask = attack_mask_ir();
        let out = emit_mask_mod(std::slice::from_ref(&mask));
        assert!(out.contains("pub mod attack;"));
        assert!(out.contains("pub use attack::mask_attack;"));
        assert!(out.contains("pub fn register()"));
    }

    #[test]
    fn empty_aggregate_mod_is_a_no_op() {
        let out = emit_mask_mod(&[]);
        assert!(out.contains("pub fn register() {}"));
        assert!(!out.contains("pub mod"));
    }

    #[test]
    fn named_action_head_is_rejected() {
        let mut mask = attack_mask_ir();
        mask.head.shape = IrActionHeadShape::Named(vec![]);
        let err = emit_mask(&mask, None).unwrap_err();
        assert!(err.contains("named-field action head"), "unexpected err: {err}");
    }
}
