//! Emission of `engine_rules/src/backend.rs` — the `SerialBackend` type that
//! implements `engine::backend::SimBackend` by delegating to
//! `engine_rules::step::step`.
//!
//! This file is almost entirely static; it exists as a compiler-owned
//! emission so that the full `engine_rules` surface can be regenerated
//! in one `compile-dsl` run without manual hand-editing.

use std::fmt::Write;

/// Emit `engine_rules/src/backend.rs`.
pub fn emit_backend(source_file: Option<&str>) -> String {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    writeln!(out, "use engine::backend::SimBackend;").unwrap();
    writeln!(out, "use engine::cascade::CascadeRegistry;").unwrap();
    writeln!(out, "use engine::debug::DebugConfig;").unwrap();
    writeln!(out, "use engine::event::EventRing;").unwrap();
    writeln!(out, "use engine::policy::PolicyBackend;").unwrap();
    writeln!(out, "use engine::scratch::SimScratch;").unwrap();
    writeln!(out, "use engine::state::SimState;").unwrap();
    writeln!(out, "use engine_data::events::Event;").unwrap();
    writeln!(out, "use crate::views::ViewRegistry;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// Serial (CPU) backend — thin `SimBackend` wrapper around").unwrap();
    writeln!(out, "/// `engine_rules::step::step`. Constructed once and held for the duration").unwrap();
    writeln!(out, "/// of a combat tick loop; stateless beyond the `Copy`/`Default` marker.").unwrap();
    writeln!(out, "#[derive(Debug, Default, Clone, Copy)]").unwrap();
    writeln!(out, "pub struct SerialBackend;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl SimBackend for SerialBackend {{").unwrap();
    writeln!(out, "    type Event = Event;").unwrap();
    writeln!(out, "    type Views = ViewRegistry;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    fn step<B: PolicyBackend>(").unwrap();
    writeln!(out, "        &mut self,").unwrap();
    writeln!(out, "        state:   &mut SimState,").unwrap();
    writeln!(out, "        scratch: &mut SimScratch,").unwrap();
    writeln!(out, "        events:  &mut EventRing<Self::Event>,").unwrap();
    writeln!(out, "        views:   &mut Self::Views,").unwrap();
    writeln!(out, "        policy:  &B,").unwrap();
    writeln!(out, "        cascade: &CascadeRegistry<Self::Event, Self::Views>,").unwrap();
    writeln!(out, "    ) {{").unwrap();
    writeln!(out, "        crate::step::step(state, scratch, events, views, policy, cascade, &DebugConfig::default());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    out
}

fn emit_header(out: &mut String, _source_file: Option<&str>) {
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();
}
