//! Emits `engine_gpu_rules/src/resident_context.rs` — one `wgpu::Buffer`
//! field per Resident-class buffer, plus a `new()` constructor and (when
//! the kernel emit accumulator declares any scoring views) a
//! `scoring_view_buffers_slice()` helper that returns the per-view
//! `wgpu::Buffer` references in the same order as
//! `emit_scoring_wgsl::scoring_view_binding_order` — so scoring's
//! `bind()` body just hands the slice to `record()` without re-walking
//! the view list.
//!
//! Initial implementation has no fields: kernel emitters in later tasks
//! call `add_resident_field` to populate the context. Producing an
//! empty struct on bootstrap keeps every kernel emitter free to add
//! fields independently.

use std::fmt::Write;

#[derive(Debug, Clone)]
pub struct ResidentField {
    /// Snake-case field name on `ResidentPathContext`.
    pub name: String,
    /// Doc string written above the field.
    pub doc:  String,
}

/// Per-materialized-view fold-handle metadata. The Task-11 fold-kernel
/// emit walks materialized views (skipping `ViewBodyIR::Expr`) and
/// emits one `fold_view_<name>_handles()` accessor per view returning
/// the `(primary, anchor_opt, ids_opt)` triple of buffer references.
///
/// Non-topk views (slot_map / dense pair_map) only have a primary
/// buffer; topk views additionally carry an anchor + ids buffer pair
/// (the per-entity topk slot table + the per-owner slot count
/// counter). Whether anchor/ids exist is stored in
/// `anchor_field` / `ids_field` — `None` means "this view has no
/// such buffer; the fold-kernel record() body falls back to the
/// primary buffer to keep the BGL slot live."
///
/// Buffer fields (primary / optional anchor / optional ids) are
/// declared via the `fields` list passed to
/// [`emit_resident_context_rs_with_scoring_and_folds`]; this struct
/// only carries the per-view *which-fields* lookup so the accessor
/// emit knows what to return.
#[derive(Debug, Clone)]
pub struct FoldViewSpec {
    /// Snake-case view name (used in the accessor's name and in the
    /// generated field references).
    pub name: String,
    /// Resident field name for the primary buffer (e.g.
    /// `"view_storage_threat_level"` or `"standing_primary"`).
    pub primary_field: String,
    /// Resident field name for the anchor buffer (topk only).
    pub anchor_field:  Option<String>,
    /// Resident field name for the ids buffer (topk only).
    pub ids_field:     Option<String>,
}

/// Emit the resident-context module with the default (no scoring-view)
/// shape — kept for callers that don't yet thread the scoring view list.
pub fn emit_resident_context_rs(fields: &[ResidentField]) -> String {
    emit_resident_context_rs_with_scoring(fields, &[])
}

/// Emit the resident-context module + a `scoring_view_buffers_slice`
/// helper. `scoring_view_field_names` is the ordered list of
/// `view_storage_<name>` field names (same order as
/// `scoring_view_binding_order`); the helper returns
/// `&[&wgpu::Buffer]` over them. When the slice is empty the helper
/// still emits and returns an empty static slice — scoring's `bind()`
/// body always calls it.
pub fn emit_resident_context_rs_with_scoring(
    fields: &[ResidentField],
    scoring_view_field_names: &[String],
) -> String {
    emit_resident_context_rs_with_scoring_and_folds(fields, scoring_view_field_names, &[])
}

/// Like [`emit_resident_context_rs_with_scoring`], plus per-materialized-view
/// `fold_view_<name>_handles()` accessor methods. Each accessor returns
/// `(&wgpu::Buffer, Option<&wgpu::Buffer>, Option<&wgpu::Buffer>)` —
/// the (primary, anchor_opt, ids_opt) triple the Fold<View>Kernel's
/// `bind()` body destructures.
pub fn emit_resident_context_rs_with_scoring_and_folds(
    fields: &[ResidentField],
    scoring_view_field_names: &[String],
    fold_view_specs: &[FoldViewSpec],
) -> String {
    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler::emit_resident_context. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// Resident-lifetime buffers — persist across ticks within a batch.").unwrap();
    writeln!(out, "pub struct ResidentPathContext {{").unwrap();
    for f in fields {
        writeln!(out, "    /// {}", f.doc).unwrap();
        writeln!(out, "    pub {}: wgpu::Buffer,", f.name).unwrap();
    }
    writeln!(out, "    /// Cached slice over scoring view buffers — populated lazily by").unwrap();
    writeln!(out, "    /// `scoring_view_buffers_slice` and re-used across `bind()` calls.").unwrap();
    writeln!(out, "    /// `OnceLock` keeps it `Sync`-safe without runtime locking.").unwrap();
    writeln!(out, "    scoring_view_buffers_cache: std::sync::OnceLock<Vec<&'static wgpu::Buffer>>,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl ResidentPathContext {{").unwrap();
    writeln!(out, "    /// Allocate every Resident-class buffer up-front. agent_cap is").unwrap();
    writeln!(out, "    /// the maximum agent capacity across the batch — caps that grow").unwrap();
    writeln!(out, "    /// at runtime force a context rebuild (the existing GpuBackend").unwrap();
    writeln!(out, "    /// resident-rebuild path).").unwrap();
    writeln!(out, "    pub fn new(_device: &wgpu::Device, _agent_cap: u32) -> Self {{").unwrap();
    if fields.is_empty() {
        writeln!(out, "        Self {{ scoring_view_buffers_cache: std::sync::OnceLock::new() }}").unwrap();
    } else {
        writeln!(out, "        Self {{").unwrap();
        for f in fields {
            // Each kernel emitter is responsible for the actual size /
            // descriptor when it lands. The bootstrap stub allocates a
            // 256-byte placeholder — large enough to satisfy WGSL
            // struct stride contracts (StandingEdge = 16B × K=8 = 128B
            // per row; MemoryEntry = 16B × K=64 = 1024B per row, but
            // the smoke test only needs the binding to validate, not
            // hold real data; a 256-byte buffer covers any single-row
            // BGL min_binding_size check). Kernel emitters in later
            // tasks override this routine wholesale by re-emitting
            // the file with size driven from the per-view K.
            writeln!(out, "            {}: _device.create_buffer(&wgpu::BufferDescriptor {{", f.name).unwrap();
            writeln!(out, "                label: Some(\"engine_gpu_rules::resident::{}\"),", f.name).unwrap();
            writeln!(out, "                size: 256,").unwrap();
            writeln!(out, "                usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::COPY_SRC,").unwrap();
            writeln!(out, "                mapped_at_creation: false,").unwrap();
            writeln!(out, "            }}),").unwrap();
        }
        writeln!(out, "            scoring_view_buffers_cache: std::sync::OnceLock::new(),").unwrap();
        writeln!(out, "        }}").unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    /// Slice of per-view scoring buffers in `scoring_view_binding_order`").unwrap();
    writeln!(out, "    /// emit order. Used by `ScoringKernel::bind()`.").unwrap();
    writeln!(out, "    pub fn scoring_view_buffers_slice<'a>(&'a self) -> &'a [&'a wgpu::Buffer] {{").unwrap();
    if scoring_view_field_names.is_empty() {
        writeln!(out, "        &[]").unwrap();
    } else {
        // SAFETY note: We extend the per-view buffer references to
        // 'static via the OnceLock. This is sound because
        // ResidentPathContext owns those buffers for its full lifetime
        // and never moves them; the OnceLock guarantees a single init.
        writeln!(out, "        let v = self.scoring_view_buffers_cache.get_or_init(|| {{").unwrap();
        writeln!(out, "            // SAFETY: the &wgpu::Buffer references inside `Self` live as long as").unwrap();
        writeln!(out, "            // `Self` does. The OnceLock is dropped together with `Self`,").unwrap();
        writeln!(out, "            // so the 'static cast is sound for as long as the cache exists.").unwrap();
        writeln!(out, "            let raw: Vec<&'static wgpu::Buffer> = vec![").unwrap();
        for n in scoring_view_field_names {
            writeln!(out, "                unsafe {{ &*((&self.{n}) as *const wgpu::Buffer) }},").unwrap();
        }
        writeln!(out, "            ];").unwrap();
        writeln!(out, "            raw").unwrap();
        writeln!(out, "        }});").unwrap();
        writeln!(out, "        // Re-borrow at the caller's lifetime.").unwrap();
        writeln!(out, "        // Vec<&'static T> coerces to &[&T] here.").unwrap();
        writeln!(out, "        unsafe {{ std::mem::transmute::<&[&'static wgpu::Buffer], &'a [&'a wgpu::Buffer]>(v.as_slice()) }}").unwrap();
    }
    writeln!(out, "    }}").unwrap();

    // T11: per-materialized-view fold-handle accessors. Walked from
    // the IR by xtask; each emits a method returning the
    // `(primary, anchor_opt, ids_opt)` triple the corresponding
    // `Fold<Pascal>Kernel::bind()` body destructures.
    for spec in fold_view_specs {
        writeln!(out).unwrap();
        writeln!(
            out,
            "    /// Returns (primary, anchor_opt, ids_opt) for the `{}` fold kernel.",
            spec.name
        )
        .unwrap();
        writeln!(
            out,
            "    /// Used by `Fold{}Kernel::bind()`.",
            pascal(&spec.name)
        )
        .unwrap();
        writeln!(
            out,
            "    pub fn fold_view_{}_handles<'a>(&'a self) -> (&'a wgpu::Buffer, Option<&'a wgpu::Buffer>, Option<&'a wgpu::Buffer>) {{",
            spec.name
        )
        .unwrap();
        let anchor = match &spec.anchor_field {
            Some(f) => format!("Some(&self.{f})"),
            None => "None".to_string(),
        };
        let ids = match &spec.ids_field {
            Some(f) => format!("Some(&self.{f})"),
            None => "None".to_string(),
        };
        writeln!(
            out,
            "        (&self.{primary}, {anchor}, {ids})",
            primary = spec.primary_field
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}").unwrap();
    out
}

/// Lowercase snake_case → PascalCase. Mirrors the helper in
/// `emit_view_fold_kernel`; kept private here so the resident-context
/// emit doesn't depend on that module.
fn pascal(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c == '_' {
            up = true;
            continue;
        }
        if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_context_emits_unit_struct_body() {
        let src = emit_resident_context_rs(&[]);
        assert!(src.contains("pub struct ResidentPathContext"));
    }

    #[test]
    fn single_field_emits_field_and_init() {
        let src = emit_resident_context_rs(&[ResidentField {
            name: "agents".into(),
            doc: "Agent SoA buffer".into(),
        }]);
        assert!(src.contains("pub agents: wgpu::Buffer"));
        assert!(src.contains("Agent SoA buffer"));
    }

    #[test]
    fn scoring_view_slice_helper_always_emitted() {
        let src = emit_resident_context_rs(&[]);
        assert!(src.contains("scoring_view_buffers_slice"));
    }

    #[test]
    fn scoring_view_slice_with_names_lists_fields() {
        let src = emit_resident_context_rs_with_scoring(
            &[ResidentField { name: "view_storage_x".into(), doc: "x".into() }],
            &["view_storage_x".into()],
        );
        assert!(src.contains("scoring_view_buffers_slice"));
        assert!(src.contains("&self.view_storage_x"));
    }
}
