//! Entity emission. Scaffolded at milestone-3-completion; filled in at
//! milestone 5.
//!
//! Emission target: `crates/engine_rules/src/entities/`. Entity outputs are
//! data (CreatureType enum, Capabilities struct, hostility matrix, spawn
//! templates) with no engine dependency; the engine imports the emitted
//! types the same way it imports `Event` today.
//!
//! Until milestone 5 lands, `emit_entity_mod` produces an empty aggregator
//! with a re-export shim so the directory compiles.

use crate::ir::EntityIR;

pub fn emit_entity(_entity: &EntityIR, _source_file: Option<&str>) -> Result<String, String> {
    Err("entity emission not yet implemented (milestone 5)".into())
}

pub fn emit_entity_mod(entities: &[EntityIR]) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler. Do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push_str("\n");
    if entities.is_empty() {
        out.push_str("// No `entity` declarations in scope yet (milestone 5 fills\n");
        out.push_str("// this in). The engine currently uses the hand-written\n");
        out.push_str("// `crates/engine/src/creature.rs` for CreatureType + hostility.\n");
        out.push_str("// When milestone 5 lands, `CreatureType` et al. move here and\n");
        out.push_str("// `engine::creature` becomes a re-export shim analogous to\n");
        out.push_str("// `engine::event` (see milestone 2).\n");
    } else {
        out.push_str("// milestone 5: aggregate entity emission\n");
    }
    out
}
