//! Emission of `engine_rules/src/cascade_reg.rs` — the `with_engine_builtins`
//! factory that constructs a `SimCascadeRegistry` pre-populated with all
//! DSL-emitted physics dispatchers.
//!
//! The emitted file is a thin wrapper: it defines the `SimCascadeRegistry`
//! type alias and a `with_engine_builtins()` function that creates a fresh
//! `CascadeRegistry` and delegates to `crate::physics::register` to install
//! every per-event-kind dispatcher.

use std::fmt::Write;

/// Emit `engine_rules/src/cascade_reg.rs`.
///
/// `source_file` is the DSL source path stamped into the file header when a
/// single `.sim` file contributed the relevant rule set; `None` falls back to
/// a generic header.
pub fn emit_cascade_register(source_file: Option<&str>) -> String {
    let mut out = String::new();
    emit_header(&mut out, source_file);

    writeln!(out, "use engine::cascade::CascadeRegistry;").unwrap();
    writeln!(out, "use engine_data::events::Event;").unwrap();
    writeln!(out, "use crate::ViewRegistry;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub type SimCascadeRegistry = CascadeRegistry<Event, ViewRegistry>;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// Construct a `SimCascadeRegistry` with all DSL-emitted physics dispatchers.").unwrap();
    writeln!(out, "pub fn with_engine_builtins() -> SimCascadeRegistry {{").unwrap();
    writeln!(out, "    let mut reg = CascadeRegistry::new();").unwrap();
    writeln!(out, "    crate::physics::register(&mut reg);").unwrap();
    writeln!(out, "    reg").unwrap();
    writeln!(out, "}}").unwrap();
    out
}

fn emit_header(out: &mut String, source_file: Option<&str>) {
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    if let Some(s) = source_file {
        writeln!(out, "// Source: {s}").unwrap();
    }
    writeln!(out).unwrap();
}
