//! Rust emission for `physics` cascade handlers.
//!
//! Each `physics` declaration lowers to a plain function in
//! `physics/<snake_case>.rs`. The per-event-kind dispatcher lives in
//! `physics/mod.rs`; it destructures the triggering event once and calls
//! every applicable handler function inline (kind-specific + every tagged
//! handler where the event implements the tag). No runtime class-bitset
//! lookup — the dispatch fan-out is compiled in.
//!
//! Handler bodies retain the mechanical lowering from the earlier
//! milestone (let, if, emit, `agents.*` accessors, `min` / `max` / `clamp`,
//! basic arithmetic, comparisons). Emit sites get an implicit
//! `tick: state.tick` appended automatically, matching §7 of the DSL spec.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::ast::{BinOp, UnOp};
use crate::ir::{
    Builtin, EventField, EventIR, EventTagIR, IrEmit, IrExpr, IrExprNode, IrPattern,
    IrPhysicsPattern, IrStmt, IrType, NamespaceId, PhysicsHandlerIR, PhysicsIR,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    /// The pattern lacked an event/tag ref — the referenced name didn't
    /// resolve during lowering.
    UnresolvedEventInPattern(String),
    /// The `emit` statement names an event the compiler doesn't know.
    UnresolvedEventInEmit(String),
    /// Some IR construct isn't supported by the emitter. Carries a short
    /// diagnostic string with the offending shape.
    Unsupported(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::UnresolvedEventInPattern(n) => {
                write!(f, "physics handler matches `{n}` which is not a declared event or tag")
            }
            EmitError::UnresolvedEventInEmit(n) => {
                write!(f, "physics handler emits event `{n}` which is not declared")
            }
            EmitError::Unsupported(s) => write!(f, "physics emission: {s}"),
        }
    }
}

impl std::error::Error for EmitError {}

// ---------------------------------------------------------------------------
// Context passed to the emitter
// ---------------------------------------------------------------------------

/// Per-compilation context the physics emitter needs beyond the IR rule
/// itself: the full event catalog (for per-kind dispatcher fan-out) and
/// the tag catalog (for tag-matched handler argument lists). Passed by
/// reference so the emitter can look up field types by event/tag name.
pub struct EmitContext<'a> {
    pub events: &'a [EventIR],
    pub event_tags: &'a [EventTagIR],
}

// ---------------------------------------------------------------------------
// Public emission entry points
// ---------------------------------------------------------------------------

/// Emit a single physics module file (`physics/<snake_case>.rs`). The file
/// exports one `pub fn <name>(<args>, state, events)` per handler in the
/// rule; the aggregate `mod.rs` owns the trigger → dispatcher routing.
pub fn emit_physics(
    physics: &PhysicsIR,
    source_file: Option<&str>,
    ctx: &EmitContext<'_>,
) -> Result<String, EmitError> {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    emit_imports(&mut out, physics, ctx)?;
    emit_handler_fn(&mut out, physics, ctx)?;
    // The legacy per-rule `<Name>Handler` unit-struct + CascadeHandler impl
    // was deleted in the 2026-04-19 event-taxonomy rename (task 136). Test
    // call sites now invoke the per-event-kind dispatcher in
    // `physics/mod.rs` (`dispatch_effect_*`) directly.
    Ok(out)
}

/// Emit the aggregate `physics/mod.rs`. Owns per-event-kind dispatcher
/// functions (one per event that has at least one matching handler) plus
/// a `register` fn that installs every dispatcher on the registry.
pub fn emit_physics_mod(physics: &[PhysicsIR], ctx: &EmitContext<'_>) -> String {
    let mut sorted: Vec<&PhysicsIR> = physics.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();

    for p in &sorted {
        writeln!(out, "pub mod {};", snake_case(&p.name)).unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "use crate::cascade::{{CascadeRegistry, EventKindId}};").unwrap();
    writeln!(out, "use crate::event::{{Event, EventRing}};").unwrap();
    writeln!(out, "use crate::state::SimState;").unwrap();
    writeln!(out).unwrap();

    // Group handlers by the event kind they fire on. A kind-matched rule
    // contributes to exactly one event; a tag-matched rule contributes to
    // every event that claims the tag.
    let applicable = applicable_handlers(physics, ctx);
    // Emit one dispatcher fn per event-kind that has any handler. Sort by
    // event name for reorder stability.
    let mut kinds: Vec<&str> = applicable.keys().map(|s| s.as_str()).collect();
    kinds.sort();
    for kind in &kinds {
        let event = ctx
            .events
            .iter()
            .find(|e| e.name == *kind)
            .expect("dispatcher target must be a declared event");
        let handlers = applicable.get(*kind).unwrap();
        emit_dispatcher_fn(&mut out, event, handlers, ctx);
    }

    // Registration fn — installs every dispatcher.
    writeln!(out, "/// Install every compiler-emitted physics dispatcher on `registry`.").unwrap();
    writeln!(out, "/// Called from `CascadeRegistry::register_engine_builtins` so the").unwrap();
    writeln!(out, "/// engine's built-in handler set picks up DSL-owned rules without").unwrap();
    writeln!(out, "/// the engine knowing about each handler by name.").unwrap();
    writeln!(out, "pub fn register(registry: &mut CascadeRegistry) {{").unwrap();
    if kinds.is_empty() {
        writeln!(out, "    let _ = registry;").unwrap();
    } else {
        for kind in &kinds {
            writeln!(
                out,
                "    registry.install_kind(EventKindId::{kind}, dispatch_{});",
                snake_case(kind)
            )
            .unwrap();
        }
    }
    writeln!(out, "}}").unwrap();

    out
}

// ---------------------------------------------------------------------------
// Applicable-handler resolution
// ---------------------------------------------------------------------------

/// A reference to a handler applicable to a given event kind. Carries the
/// owning physics rule + the handler index, so the dispatcher can emit a
/// call to the per-rule module by stable name.
#[derive(Debug, Clone)]
#[allow(dead_code)]
struct HandlerRef<'a> {
    rule_name: &'a str,
    handler: &'a PhysicsHandlerIR,
    /// `None` for kind-matched handlers; `Some(tag_name)` for tag-matched.
    via_tag: Option<&'a str>,
}

/// Map event-kind name → ordered list of handlers that should fire on that
/// kind. Kind-matched rules come first (source order), then tag-matched
/// rules (by rule name for reorder stability).
fn applicable_handlers<'a>(
    physics: &'a [PhysicsIR],
    ctx: &'a EmitContext<'a>,
) -> BTreeMap<String, Vec<HandlerRef<'a>>> {
    let mut out: BTreeMap<String, Vec<HandlerRef<'a>>> = BTreeMap::new();

    let mut sorted: Vec<&PhysicsIR> = physics.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    // Pass 1: kind-matched rules.
    for p in &sorted {
        for h in &p.handlers {
            if let IrPhysicsPattern::Kind(pat) = &h.pattern {
                out.entry(pat.name.clone())
                    .or_default()
                    .push(HandlerRef {
                        rule_name: p.name.as_str(),
                        handler: h,
                        via_tag: None,
                    });
            }
        }
    }
    // Pass 2: tag-matched rules — one entry per event that claims the tag.
    for p in &sorted {
        for h in &p.handlers {
            if let IrPhysicsPattern::Tag { name: tag_name, tag, .. } = &h.pattern {
                let Some(tref) = tag else { continue };
                let tag_ir = &ctx.event_tags[tref.0 as usize];
                for event in ctx.events {
                    if event.tags.iter().any(|r| *r == *tref) {
                        out.entry(event.name.clone())
                            .or_default()
                            .push(HandlerRef {
                                rule_name: p.name.as_str(),
                                handler: h,
                                via_tag: Some(tag_ir.name.as_str()),
                            });
                    }
                }
                let _ = tag_name;
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Dispatcher emission
// ---------------------------------------------------------------------------

fn emit_dispatcher_fn(
    out: &mut String,
    event: &EventIR,
    handlers: &[HandlerRef<'_>],
    ctx: &EmitContext<'_>,
) {
    let event_fields = fields_with_implicit_tick(event);
    writeln!(
        out,
        "#[allow(unused_variables)]"
    )
    .unwrap();
    writeln!(
        out,
        "pub fn dispatch_{}(event: &Event, state: &mut SimState, events: &mut EventRing) {{",
        snake_case(&event.name)
    )
    .unwrap();
    // Destructure every field of the event variant into same-name locals.
    let binds: Vec<String> = event_fields.iter().map(|f| f.name.clone()).collect();
    writeln!(
        out,
        "    let Event::{} {{ {} }} = *event else {{ return; }};",
        event.name,
        binds.join(", ")
    )
    .unwrap();
    for hr in handlers {
        emit_dispatcher_call(out, event, &event_fields, hr, ctx);
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Emit a single `<rule_name>::<fn_name>(<args>, state, events);` call
/// inside the dispatcher. Arguments are drawn from the event's destructured
/// locals (by pattern-binding field name).
fn emit_dispatcher_call(
    out: &mut String,
    event: &EventIR,
    event_fields: &[EventField],
    hr: &HandlerRef<'_>,
    ctx: &EmitContext<'_>,
) {
    let binding_names = handler_binding_names(hr.handler, ctx);
    // The call passes the event's field values in the same order as the
    // handler's argument list. If the handler binds a name that differs
    // from the event field name, use the event field name here — the
    // handler body uses the binding name as the argument identifier.
    let mut args: Vec<String> = Vec::new();
    for (event_field, _) in &binding_names {
        // Ensure the event actually declares this field.
        if !event_fields.iter().any(|f| f.name == *event_field) {
            // Tag-matched handlers may bind `tick`, which the event
            // always declares (implicit). Skip guard for other names;
            // the resolver validated the binding shape already.
        }
        args.push(event_field.clone());
    }
    let module = snake_case(hr.rule_name);
    let fn_name = handler_fn_name(hr.rule_name);
    writeln!(
        out,
        "    {}::{}({}, state, events);",
        module,
        fn_name,
        args.join(", ")
    )
    .unwrap();
    let _ = event;
}

/// Returns the list of `(event_field_name, binding_name)` pairs the
/// handler's generated function signature exposes. For kind-matched
/// handlers, this is just the pattern's bindings. For tag-matched
/// handlers, only tag-declared fields (plus `tick`) are exposed.
fn handler_binding_names(
    handler: &PhysicsHandlerIR,
    ctx: &EmitContext<'_>,
) -> Vec<(String, String)> {
    let mut pairs = Vec::new();
    for b in handler.pattern.bindings() {
        if let IrPattern::Bind { name, .. } = &b.value {
            pairs.push((b.field.clone(), name.clone()));
        }
    }
    let _ = ctx;
    pairs
}

// ---------------------------------------------------------------------------
// Per-rule file emission (function signature + body)
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(out, "// GENERATED by dsl_compiler from {}.", path).unwrap(),
        None => writeln!(out, "// GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "// Do not edit by hand.").unwrap();
    writeln!(out).unwrap();
}

fn emit_imports(
    out: &mut String,
    physics: &PhysicsIR,
    ctx: &EmitContext<'_>,
) -> Result<(), EmitError> {
    // Sanity check: every trigger + emit must resolve.
    for handler in &physics.handlers {
        match &handler.pattern {
            IrPhysicsPattern::Kind(p) => {
                if p.event.is_none() {
                    return Err(EmitError::UnresolvedEventInPattern(p.name.clone()));
                }
            }
            IrPhysicsPattern::Tag { name, tag, .. } => {
                if tag.is_none() {
                    return Err(EmitError::UnresolvedEventInPattern(format!("@{name}")));
                }
            }
        }
        scan_emits(&handler.body)?;
    }

    // Collect niche-id imports from the handler's argument types.
    let mut niche_ids: BTreeSet<&'static str> = BTreeSet::new();
    let mut needs_vec3 = false;
    let mut needs_quest_category = false;
    let mut needs_resolution = false;
    for h in &physics.handlers {
        for (_, ty) in handler_arg_types(h, ctx)? {
            collect_import(
                &ty,
                &mut niche_ids,
                &mut needs_vec3,
                &mut needs_quest_category,
                &mut needs_resolution,
            );
        }
    }

    // Scan the handler bodies for `emit EventName { ... }` statements; only
    // import `Event` when some body actually constructs one. (The legacy
    // per-rule `<Name>Handler` shim that forced an `Event` import was
    // deleted in the 2026-04-19 event-taxonomy rename — task 136.)
    let mut emits_any_event = false;
    for h in &physics.handlers {
        if body_emits_event(&h.body) {
            emits_any_event = true;
            break;
        }
    }
    if emits_any_event {
        writeln!(out, "use crate::event::{{Event, EventRing}};").unwrap();
    } else {
        writeln!(out, "use crate::event::EventRing;").unwrap();
    }
    writeln!(out, "use crate::state::SimState;").unwrap();
    if !niche_ids.is_empty() {
        let joined: Vec<&str> = niche_ids.iter().copied().collect();
        if joined.len() == 1 {
            writeln!(out, "use crate::ids::{};", joined[0]).unwrap();
        } else {
            writeln!(out, "use crate::ids::{{{}}};", joined.join(", ")).unwrap();
        }
    }
    if needs_vec3 {
        writeln!(out, "use glam::Vec3;").unwrap();
    }
    if needs_quest_category {
        writeln!(out, "use crate::types::QuestCategory;").unwrap();
    }
    if needs_resolution {
        writeln!(out, "use crate::types::Resolution;").unwrap();
    }
    writeln!(out).unwrap();
    Ok(())
}

fn collect_import(
    ty: &IrType,
    niche_ids: &mut BTreeSet<&'static str>,
    needs_vec3: &mut bool,
    needs_quest_category: &mut bool,
    needs_resolution: &mut bool,
) {
    match ty {
        IrType::AgentId => {
            niche_ids.insert("AgentId");
        }
        IrType::ItemId => {
            niche_ids.insert("ItemId");
        }
        IrType::GroupId => {
            niche_ids.insert("GroupId");
        }
        IrType::QuestId => {
            niche_ids.insert("QuestId");
        }
        IrType::AuctionId => {
            niche_ids.insert("AuctionId");
        }
        IrType::EventId => {
            niche_ids.insert("EventId");
        }
        IrType::AbilityId => {
            niche_ids.insert("AbilityId");
        }
        IrType::Vec3 => {
            *needs_vec3 = true;
        }
        IrType::Named(n) => match n.as_str() {
            "QuestCategory" => *needs_quest_category = true,
            "Resolution" => *needs_resolution = true,
            _ => {}
        },
        IrType::Optional(inner) | IrType::Array(inner, _) | IrType::List(inner) => {
            collect_import(inner, niche_ids, needs_vec3, needs_quest_category, needs_resolution)
        }
        IrType::Tuple(items) => {
            for t in items {
                collect_import(t, niche_ids, needs_vec3, needs_quest_category, needs_resolution);
            }
        }
        _ => {}
    }
}

/// Returns `true` when the handler body contains at least one `emit` statement
/// (directly or nested under `if` / `for` / `match`). Used by the emitter to
/// skip the `Event` import in rules that only mutate via `agents.*` accessors.
fn body_emits_event(stmts: &[IrStmt]) -> bool {
    for s in stmts {
        match s {
            IrStmt::Emit(_) => return true,
            IrStmt::If { then_body, else_body, .. } => {
                if body_emits_event(then_body) { return true; }
                if let Some(b) = else_body {
                    if body_emits_event(b) { return true; }
                }
            }
            IrStmt::For { body, .. } => {
                if body_emits_event(body) { return true; }
            }
            IrStmt::Match { arms, .. } => {
                for arm in arms {
                    if body_emits_event(&arm.body) { return true; }
                }
            }
            IrStmt::Let { .. } | IrStmt::Expr(_) | IrStmt::SelfUpdate { .. } => {}
        }
    }
    false
}

fn scan_emits(stmts: &[IrStmt]) -> Result<(), EmitError> {
    for s in stmts {
        match s {
            IrStmt::Emit(e) => {
                if e.event.is_none() {
                    return Err(EmitError::UnresolvedEventInEmit(e.event_name.clone()));
                }
            }
            IrStmt::If { then_body, else_body, .. } => {
                scan_emits(then_body)?;
                if let Some(b) = else_body {
                    scan_emits(b)?;
                }
            }
            IrStmt::For { body, .. } => scan_emits(body)?,
            IrStmt::Match { arms, .. } => {
                for arm in arms {
                    scan_emits(&arm.body)?;
                }
            }
            IrStmt::Let { .. } | IrStmt::Expr(_) | IrStmt::SelfUpdate { .. } => {}
        }
    }
    Ok(())
}

fn emit_handler_fn(
    out: &mut String,
    physics: &PhysicsIR,
    ctx: &EmitContext<'_>,
) -> Result<(), EmitError> {
    if physics.handlers.len() != 1 {
        return Err(EmitError::Unsupported(format!(
            "expected exactly one `on` handler per physics rule (got {} in `{}`)",
            physics.handlers.len(),
            physics.name
        )));
    }
    let handler = &physics.handlers[0];
    let fn_name = handler_fn_name(&physics.name);
    let args = handler_arg_types(handler, ctx)?;

    writeln!(out, "#[allow(unused_variables)]").unwrap();
    write!(out, "pub fn {fn_name}(").unwrap();
    for (name, ty) in &args {
        write!(out, "{name}: {}, ", render_type(ty)).unwrap();
    }
    writeln!(out, "state: &mut SimState, events: &mut EventRing) {{").unwrap();

    if let Some(where_clause) = &handler.where_clause {
        let cond = lower_expr(where_clause)?;
        writeln!(out, "    if !({cond}) {{ return; }}").unwrap();
    }

    for stmt in &handler.body {
        emit_stmt(out, stmt, 4)?;
    }

    writeln!(out, "}}").unwrap();
    Ok(())
}

/// Return the `(binding_name, type)` pairs the handler exposes as arguments.
/// For a kind-matched handler, types come from the event declaration. For a
/// tag-matched handler, types come from the tag declaration (plus `tick:
/// u32` if bound).
fn handler_arg_types(
    handler: &PhysicsHandlerIR,
    ctx: &EmitContext<'_>,
) -> Result<Vec<(String, IrType)>, EmitError> {
    let mut out = Vec::new();
    match &handler.pattern {
        IrPhysicsPattern::Kind(pat) => {
            let Some(event_ref) = pat.event else {
                return Err(EmitError::UnresolvedEventInPattern(pat.name.clone()));
            };
            let event = &ctx.events[event_ref.0 as usize];
            let fields = fields_with_implicit_tick(event);
            for b in &pat.bindings {
                if let IrPattern::Bind { name, .. } = &b.value {
                    let Some(field) = fields.iter().find(|f| f.name == b.field) else {
                        return Err(EmitError::Unsupported(format!(
                            "handler binds unknown field `{}` on event `{}`",
                            b.field, event.name
                        )));
                    };
                    out.push((name.clone(), field.ty.clone()));
                }
            }
        }
        IrPhysicsPattern::Tag { tag, bindings, name, .. } => {
            let Some(tref) = tag else {
                return Err(EmitError::UnresolvedEventInPattern(format!("@{name}")));
            };
            let tag_ir = &ctx.event_tags[tref.0 as usize];
            for b in bindings {
                if let IrPattern::Bind { name: bname, .. } = &b.value {
                    let ty = if b.field == "tick" {
                        IrType::U32
                    } else {
                        let Some(field) = tag_ir.fields.iter().find(|f| f.name == b.field) else {
                            return Err(EmitError::Unsupported(format!(
                                "handler binds unknown field `{}` on tag `@{}`",
                                b.field, tag_ir.name
                            )));
                        };
                        field.ty.clone()
                    };
                    out.push((bname.clone(), ty));
                }
            }
        }
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Statement & expression lowering
// ---------------------------------------------------------------------------

fn emit_stmt(out: &mut String, stmt: &IrStmt, indent: usize) -> Result<(), EmitError> {
    let pad = " ".repeat(indent);
    match stmt {
        IrStmt::Let { name, value, .. } => {
            let v = lower_expr(value)?;
            writeln!(out, "{pad}let {name} = {v};").unwrap();
        }
        IrStmt::Emit(emit) => emit_emit(out, emit, indent)?,
        IrStmt::If { cond, then_body, else_body, .. } => {
            let c = lower_expr(cond)?;
            writeln!(out, "{pad}if {c} {{").unwrap();
            for s in then_body {
                emit_stmt(out, s, indent + 4)?;
            }
            if let Some(eb) = else_body {
                writeln!(out, "{pad}}} else {{").unwrap();
                for s in eb {
                    emit_stmt(out, s, indent + 4)?;
                }
            }
            writeln!(out, "{pad}}}").unwrap();
        }
        IrStmt::For { .. } => {
            return Err(EmitError::Unsupported(
                "`for` statements not supported in physics emission".into(),
            ));
        }
        IrStmt::Match { .. } => {
            return Err(EmitError::Unsupported(
                "`match` statements not supported in physics emission".into(),
            ));
        }
        IrStmt::SelfUpdate { .. } => {
            return Err(EmitError::Unsupported(
                "`self += ...` self-update statements only valid in fold bodies".into(),
            ));
        }
        IrStmt::Expr(e) => {
            let v = lower_expr(e)?;
            writeln!(out, "{pad}{v};").unwrap();
        }
    }
    Ok(())
}

fn emit_emit(out: &mut String, emit: &IrEmit, indent: usize) -> Result<(), EmitError> {
    let pad = " ".repeat(indent);
    if emit.event.is_none() {
        return Err(EmitError::UnresolvedEventInEmit(emit.event_name.clone()));
    }
    let mut field_lines: Vec<String> = Vec::with_capacity(emit.fields.len() + 1);
    let mut saw_tick = false;
    for f in &emit.fields {
        if f.name == "tick" {
            saw_tick = true;
        }
        let v = lower_expr(&f.value)?;
        if f.name == v {
            field_lines.push(f.name.clone());
        } else {
            field_lines.push(format!("{}: {}", f.name, v));
        }
    }
    // Implicit tick: every emit call gets `tick: state.tick` auto-appended
    // unless the author already specified it.
    if !saw_tick {
        field_lines.push("tick: state.tick".to_string());
    }
    let body = if field_lines.is_empty() {
        String::new()
    } else {
        format!(" {} ", field_lines.join(", "))
    };
    writeln!(
        out,
        "{pad}events.push(Event::{} {{{body}}});",
        emit.event_name
    )
    .unwrap();
    Ok(())
}

fn lower_expr(node: &IrExprNode) -> Result<String, EmitError> {
    lower_expr_kind(&node.kind)
}

fn lower_expr_kind(kind: &IrExpr) -> Result<String, EmitError> {
    match kind {
        IrExpr::LitBool(b) => Ok(if *b { "true".into() } else { "false".into() }),
        IrExpr::LitInt(v) => Ok(format!("{v}")),
        IrExpr::LitFloat(v) => Ok(render_float(*v)),
        IrExpr::LitString(s) => Ok(format!("{s:?}")),
        IrExpr::Local(_, name) => Ok(name.clone()),
        IrExpr::NamespaceField { ns, field, .. } => lower_namespace_field(*ns, field),
        IrExpr::NamespaceCall { ns, method, args } => lower_namespace_call(*ns, method, args),
        IrExpr::Binary(op, lhs, rhs) => {
            let l = lower_expr(lhs)?;
            let r = lower_expr(rhs)?;
            Ok(format!("({l} {} {r})", binop_str(*op)))
        }
        IrExpr::Unary(op, rhs) => {
            let r = lower_expr(rhs)?;
            Ok(format!("({}{r})", unop_str(*op)))
        }
        IrExpr::BuiltinCall(b, args) => lower_builtin_call(*b, args),
        IrExpr::If { cond, then_expr, else_expr } => {
            let c = lower_expr(cond)?;
            let t = lower_expr(then_expr)?;
            let e = match else_expr {
                Some(e) => lower_expr(e)?,
                None => return Err(EmitError::Unsupported("`if` expression without else".into())),
            };
            Ok(format!("(if {c} {{ {t} }} else {{ {e} }})"))
        }
        IrExpr::Field { base, field_name, .. } => {
            let b = lower_expr(base)?;
            Ok(format!("{b}.{field_name}"))
        }
        IrExpr::EnumVariant { ty, variant } => {
            if ty.is_empty() {
                Ok(variant.clone())
            } else {
                Ok(format!("{ty}::{variant}"))
            }
        }
        other => Err(EmitError::Unsupported(format!(
            "expression shape {other:?} not supported in physics emission"
        ))),
    }
}

fn lower_namespace_field(ns: NamespaceId, field: &str) -> Result<String, EmitError> {
    if ns == NamespaceId::Config {
        if field.contains('.') {
            return Ok(format!("state.config.{field}"));
        }
        return Err(EmitError::Unsupported(format!(
            "bare `config.{field}` is not a value; address a specific field"
        )));
    }
    if ns == NamespaceId::World {
        if field == "tick" {
            return Ok("state.tick".into());
        }
    }
    Err(EmitError::Unsupported(format!(
        "namespace-field `{}.{field}` not supported",
        ns.name()
    )))
}

fn lower_namespace_call(
    ns: NamespaceId,
    method: &str,
    args: &[crate::ir::IrCallArg],
) -> Result<String, EmitError> {
    let lowered: Vec<String> = args
        .iter()
        .map(|a| {
            if a.name.is_some() {
                return Err(EmitError::Unsupported(format!(
                    "named argument on stdlib call `{}.{method}` not supported",
                    ns.name()
                )));
            }
            lower_expr(&a.value)
        })
        .collect::<Result<_, _>>()?;
    match (ns, method) {
        (NamespaceId::Agents, "alive") => {
            expect_arity(args, 1, "agents.alive")?;
            Ok(format!("state.agent_alive({})", lowered[0]))
        }
        (NamespaceId::Agents, "hp") => {
            expect_arity(args, 1, "agents.hp")?;
            Ok(format!("state.agent_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "shield_hp") => {
            expect_arity(args, 1, "agents.shield_hp")?;
            Ok(format!("state.agent_shield_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_hp") => {
            expect_arity(args, 2, "agents.set_hp")?;
            Ok(format!("state.set_agent_hp({}, {})", lowered[0], lowered[1]))
        }
        (NamespaceId::Agents, "set_shield_hp") => {
            expect_arity(args, 2, "agents.set_shield_hp")?;
            Ok(format!("state.set_agent_shield_hp({}, {})", lowered[0], lowered[1]))
        }
        (NamespaceId::Agents, "kill") => {
            expect_arity(args, 1, "agents.kill")?;
            Ok(format!("state.kill_agent({})", lowered[0]))
        }
        (NamespaceId::Agents, "max_hp") => {
            expect_arity(args, 1, "agents.max_hp")?;
            Ok(format!("state.agent_max_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "attack_damage") => {
            expect_arity(args, 1, "agents.attack_damage")?;
            Ok(format!(
                "state.agent_attack_damage({}).unwrap_or(state.config.combat.attack_damage)",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "stun_expires_at_tick") => {
            expect_arity(args, 1, "agents.stun_expires_at_tick")?;
            Ok(format!("state.agent_stun_expires_at({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_stun_expires_at_tick") => {
            expect_arity(args, 2, "agents.set_stun_expires_at_tick")?;
            Ok(format!(
                "state.set_agent_stun_expires_at({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "slow_expires_at_tick") => {
            expect_arity(args, 1, "agents.slow_expires_at_tick")?;
            Ok(format!("state.agent_slow_expires_at({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_slow_expires_at_tick") => {
            expect_arity(args, 2, "agents.set_slow_expires_at_tick")?;
            Ok(format!(
                "state.set_agent_slow_expires_at({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "slow_factor_q8") => {
            expect_arity(args, 1, "agents.slow_factor_q8")?;
            Ok(format!("state.agent_slow_factor_q8({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_slow_factor_q8") => {
            expect_arity(args, 2, "agents.set_slow_factor_q8")?;
            Ok(format!(
                "state.set_agent_slow_factor_q8({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "gold") => {
            expect_arity(args, 1, "agents.gold")?;
            Ok(format!(
                "state.agent_inventory({}).map(|i| i.gold).unwrap_or(0)",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "set_gold") => {
            expect_arity(args, 2, "agents.set_gold")?;
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = {v}; state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "add_gold") => {
            expect_arity(args, 2, "agents.add_gold")?;
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = __inv.gold.wrapping_add({v}); state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "sub_gold") => {
            expect_arity(args, 2, "agents.sub_gold")?;
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = __inv.gold.wrapping_sub({v}); state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "adjust_standing") => {
            expect_arity(args, 3, "agents.adjust_standing")?;
            Ok(format!(
                "state.adjust_standing({}, {}, {})",
                lowered[0], lowered[1], lowered[2]
            ))
        }
        (NamespaceId::Agents, "record_memory") => {
            // Audit fix HIGH #4 — primitive that the `record_memory` physics
            // rule lowers to. Args: `(observer, source, payload, confidence,
            // tick)`. Quantises `confidence` to q8, builds a `MemoryEvent`
            // (kind=0 — payload taxonomy is tracked by `payload` alone in the
            // MVP shell), and pushes it onto the observer's cold memory ring.
            // Emitted inline so the physics fn stays free of ad-hoc helper
            // modules; see `crates/engine/src/state/agent_types.rs::MemoryEvent`.
            expect_arity(args, 5, "agents.record_memory")?;
            Ok(format!(
                "state.push_agent_memory({observer}, crate::state::agent_types::MemoryEvent {{ \
                 source: {source}, \
                 kind: 0, \
                 payload: {payload}, \
                 confidence_q8: (({confidence}).clamp(0.0, 1.0) * 255.0) as u8, \
                 tick: {tick}, \
                 }})",
                observer   = lowered[0],
                source     = lowered[1],
                payload    = lowered[2],
                confidence = lowered[3],
                tick       = lowered[4],
            ))
        }
        _ => Err(EmitError::Unsupported(format!(
            "stdlib call `{}.{method}` not supported in physics emission",
            ns.name()
        ))),
    }
}

fn lower_builtin_call(b: Builtin, args: &[crate::ir::IrCallArg]) -> Result<String, EmitError> {
    let lowered: Vec<String> = args
        .iter()
        .map(|a| {
            if a.name.is_some() {
                return Err(EmitError::Unsupported(format!(
                    "named argument on builtin `{}` not supported",
                    b.name()
                )));
            }
            lower_expr(&a.value)
        })
        .collect::<Result<_, _>>()?;
    match b {
        Builtin::Min => {
            expect_arity(args, 2, "min")?;
            Ok(format!("({}).min({})", lowered[0], lowered[1]))
        }
        Builtin::Max => {
            expect_arity(args, 2, "max")?;
            Ok(format!("({}).max({})", lowered[0], lowered[1]))
        }
        Builtin::Clamp => {
            expect_arity(args, 3, "clamp")?;
            Ok(format!(
                "({}).clamp({}, {})",
                lowered[0], lowered[1], lowered[2]
            ))
        }
        Builtin::Abs => {
            expect_arity(args, 1, "abs")?;
            Ok(format!("({}).abs()", lowered[0]))
        }
        Builtin::Floor => {
            expect_arity(args, 1, "floor")?;
            Ok(format!("({}).floor()", lowered[0]))
        }
        Builtin::Ceil => {
            expect_arity(args, 1, "ceil")?;
            Ok(format!("({}).ceil()", lowered[0]))
        }
        Builtin::Round => {
            expect_arity(args, 1, "round")?;
            Ok(format!("({}).round()", lowered[0]))
        }
        Builtin::Sqrt => {
            expect_arity(args, 1, "sqrt")?;
            Ok(format!("({}).sqrt()", lowered[0]))
        }
        _ => Err(EmitError::Unsupported(format!(
            "builtin `{}` not supported in physics emission",
            b.name()
        ))),
    }
}

fn expect_arity(
    args: &[crate::ir::IrCallArg],
    expected: usize,
    name: &str,
) -> Result<(), EmitError> {
    if args.len() == expected {
        Ok(())
    } else {
        Err(EmitError::Unsupported(format!(
            "`{name}` expects {expected} arg(s), got {}",
            args.len()
        )))
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
    }
}

fn unop_str(op: UnOp) -> &'static str {
    match op {
        UnOp::Not => "!",
        UnOp::Neg => "-",
    }
}

fn render_float(v: f64) -> String {
    let s = format!("{v}");
    if s.contains('.') || s.contains('e') || s.contains('E') || s == "inf" || s == "-inf" || s == "NaN"
    {
        s
    } else {
        format!("{s}.0")
    }
}

// ---------------------------------------------------------------------------
// Utility: synthesize the implicit `tick: u32` on event fields
// ---------------------------------------------------------------------------

fn fields_with_implicit_tick(event: &EventIR) -> Vec<EventField> {
    let mut out = event.fields.clone();
    if !out.iter().any(|f| f.name == "tick") {
        out.push(EventField {
            name: "tick".into(),
            ty: IrType::U32,
            span: crate::ast::Span::dummy(),
        });
    }
    out
}

// ---------------------------------------------------------------------------
// Type rendering (handler argument signatures)
// ---------------------------------------------------------------------------

fn render_type(ty: &IrType) -> String {
    match ty {
        IrType::Bool => "bool".into(),
        IrType::I8 => "i8".into(),
        IrType::U8 => "u8".into(),
        IrType::I16 => "i16".into(),
        IrType::U16 => "u16".into(),
        IrType::I32 => "i32".into(),
        IrType::U32 => "u32".into(),
        IrType::I64 => "i64".into(),
        IrType::U64 => "u64".into(),
        IrType::F32 => "f32".into(),
        IrType::F64 => "f64".into(),
        IrType::Vec3 => "Vec3".into(),
        IrType::String => "String".into(),
        IrType::AgentId => "AgentId".into(),
        IrType::ItemId => "ItemId".into(),
        IrType::GroupId => "GroupId".into(),
        IrType::QuestId => "QuestId".into(),
        IrType::AuctionId => "AuctionId".into(),
        IrType::EventId => "EventId".into(),
        IrType::AbilityId => "AbilityId".into(),
        IrType::Optional(inner) => format!("Option<{}>", render_type(inner)),
        IrType::Array(inner, cap) => format!("[{}; {}]", render_type(inner), cap),
        IrType::Tuple(items) => {
            let parts: Vec<String> = items.iter().map(render_type).collect();
            format!("({})", parts.join(", "))
        }
        IrType::Named(n) => n.clone(),
        IrType::Enum { name, .. } => name.clone(),
        IrType::Unknown => "()".into(),
        other => format!("/* unsupported type {other:?} */"),
    }
}

// ---------------------------------------------------------------------------
// Naming utilities
// ---------------------------------------------------------------------------

/// Handler fn name: the same snake_case as the physics rule name. The
/// emitter no longer emits an `impl CascadeHandler` — the dispatcher calls
/// this fn directly.
fn handler_fn_name(rule: &str) -> String {
    snake_case(rule)
}

#[allow(dead_code)]
fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '_' || ch == '-' {
            upper_next = true;
        } else if upper_next {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::{
        EventField, EventIR, EventRef, IrCallArg, IrEmit, IrEventPattern, IrExpr, IrExprNode,
        IrFieldInit, IrPattern, IrPatternBinding, IrStmt, LocalRef, NamespaceId, PhysicsHandlerIR,
        PhysicsIR,
    };

    fn span() -> Span {
        Span::dummy()
    }

    fn local(name: &str, id: u16) -> IrExprNode {
        IrExprNode { kind: IrExpr::Local(LocalRef(id), name.to_string()), span: span() }
    }

    fn pattern_bind(field: &str, name: &str, id: u16) -> IrPatternBinding {
        IrPatternBinding {
            field: field.to_string(),
            value: IrPattern::Bind { name: name.to_string(), local: LocalRef(id) },
            span: span(),
        }
    }

    fn ns_call(ns: NamespaceId, method: &str, args: Vec<IrExprNode>) -> IrExprNode {
        IrExprNode {
            kind: IrExpr::NamespaceCall {
                ns,
                method: method.to_string(),
                args: args
                    .into_iter()
                    .map(|a| IrCallArg { name: None, value: a, span: span() })
                    .collect(),
            },
            span: span(),
        }
    }

    fn sample_event() -> EventIR {
        EventIR {
            name: "EffectDamageApplied".into(),
            fields: vec![
                EventField { name: "caster".into(), ty: IrType::AgentId, span: span() },
                EventField { name: "target".into(), ty: IrType::AgentId, span: span() },
                EventField { name: "amount".into(), ty: IrType::F32, span: span() },
            ],
            tags: vec![],
            annotations: vec![],
            span: span(),
        }
    }

    fn make_minimal_handler() -> PhysicsIR {
        let pattern = IrPhysicsPattern::Kind(IrEventPattern {
            name: "EffectDamageApplied".into(),
            event: Some(EventRef(0)),
            bindings: vec![
                pattern_bind("target", "t", 0),
                pattern_bind("amount", "a", 1),
            ],
            span: span(),
        });
        let body = vec![IrStmt::Expr(ns_call(
            NamespaceId::Agents,
            "set_hp",
            vec![local("t", 0), ns_call(NamespaceId::Agents, "hp", vec![local("t", 0)])],
        ))];
        PhysicsIR {
            name: "noop".into(),
            handlers: vec![PhysicsHandlerIR { pattern, where_clause: None, body, span: span() }],
            annotations: vec![],
            span: span(),
        }
    }

    #[test]
    fn handler_fn_signature_and_body() {
        let p = make_minimal_handler();
        let ev = sample_event();
        let ctx = EmitContext { events: std::slice::from_ref(&ev), event_tags: &[] };
        let out = emit_physics(&p, Some("assets/sim/physics.sim"), &ctx).unwrap();
        assert!(out.contains("// GENERATED by dsl_compiler from assets/sim/physics.sim."));
        assert!(out.contains("pub fn noop(t: AgentId, a: f32, state: &mut SimState, events: &mut EventRing)"));
        assert!(out.contains("state.set_agent_hp(t, state.agent_hp(t).unwrap_or(0.0));"));
    }

    #[test]
    fn dispatcher_destructures_and_calls() {
        let p = make_minimal_handler();
        let ev = sample_event();
        let ctx = EmitContext { events: std::slice::from_ref(&ev), event_tags: &[] };
        let out = emit_physics_mod(std::slice::from_ref(&p), &ctx);
        assert!(out.contains("pub fn dispatch_effect_damage_applied(event: &Event, state: &mut SimState, events: &mut EventRing)"));
        assert!(out.contains("let Event::EffectDamageApplied { caster, target, amount, tick }"));
        assert!(out.contains("noop::noop(target, amount, state, events);"));
        assert!(out.contains("registry.install_kind(EventKindId::EffectDamageApplied, dispatch_effect_damage_applied);"));
    }

    #[test]
    fn emit_appends_implicit_tick() {
        let p = PhysicsIR {
            name: "emitter".into(),
            handlers: vec![PhysicsHandlerIR {
                pattern: IrPhysicsPattern::Kind(IrEventPattern {
                    name: "EffectDamageApplied".into(),
                    event: Some(EventRef(0)),
                    bindings: vec![pattern_bind("target", "t", 0)],
                    span: span(),
                }),
                where_clause: None,
                body: vec![IrStmt::Emit(IrEmit {
                    event_name: "AgentDied".into(),
                    event: Some(EventRef(1)),
                    fields: vec![IrFieldInit {
                        name: "agent_id".into(),
                        value: local("t", 0),
                        span: span(),
                    }],
                    span: span(),
                })],
                span: span(),
            }],
            annotations: vec![],
            span: span(),
        };
        let ev = sample_event();
        let ctx = EmitContext { events: std::slice::from_ref(&ev), event_tags: &[] };
        let out = emit_physics(&p, None, &ctx).unwrap();
        assert!(out.contains("events.push(Event::AgentDied { agent_id: t, tick: state.tick });"));
    }
}
