//! Rust + TOML emission for `config` declarations.
//!
//! Every `config <Name> { ... }` block produces:
//!
//! 1. A per-block Rust struct `<Name>Config` under
//!    `crates/engine_rules/src/config/<snake>.rs` carrying one field per
//!    declared entry plus a `Default` impl baking in the DSL's default
//!    values. `serde::{Deserialize, Serialize}` is derived so the aggregate
//!    `Config` type round-trips through `toml::from_str` / `to_string`.
//! 2. An entry in the aggregate `crates/engine_rules/src/config/mod.rs`,
//!    which re-exports each per-block struct and bundles them on a single
//!    `pub struct Config`. `Config::default()` walks the per-block defaults;
//!    `Config::from_toml(path)` reads + parses a `default.toml`.
//!
//! Alongside the Rust output we emit `assets/config/default.toml` carrying
//! the authored default values. The TOML is what a user edits to tune
//! balance at runtime; re-running the compiler OVERWRITES this file, so
//! hand edits there are only safe when the DSL source is the ultimate
//! source of truth (same "generated file, edit the source" contract as
//! every other emission target).
//!
//! The emitter is deliberately mechanical — `writeln!` into a `String`, no
//! macros, one Rust struct per block, one `[block]` table per block in the
//! TOML. Reviewers should be able to skim the output directly.

use std::fmt::Write;

use crate::ast;
use crate::ir::{ConfigIR, IrType};

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    Unsupported(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::Unsupported(s) => write!(f, "config emission: {s}"),
        }
    }
}

impl std::error::Error for EmitError {}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/// Emit a single per-block Rust module (`config/<snake>.rs`). Carries the
/// struct + `Default` impl; the aggregate `mod.rs` re-exports the struct
/// under its PascalCase name.
pub fn emit_config(block: &ConfigIR, source_file: Option<&str>) -> Result<String, EmitError> {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
    writeln!(out).unwrap();

    let struct_name = struct_name(&block.name);
    writeln!(out, "/// Compiler-emitted tunables for the `{}` config block.", block.name)
        .unwrap();
    writeln!(out, "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]").unwrap();
    writeln!(out, "#[serde(default)]").unwrap();
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    for f in &block.fields {
        let rust_ty = rust_type_name(&f.ty)?;
        writeln!(out, "    pub {}: {},", f.name, rust_ty).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl Default for {struct_name} {{").unwrap();
    writeln!(out, "    fn default() -> Self {{").unwrap();
    writeln!(out, "        Self {{").unwrap();
    for f in &block.fields {
        let lit = render_default(&f.ty, &f.default)?;
        writeln!(out, "            {}: {},", f.name, lit).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(out)
}

/// Emit the aggregate `config/mod.rs`. Exposes one `<Name>Config` re-export
/// per block and a top-level `Config` that bundles them all, with a
/// `from_toml` loader and a hand-emitted `ConfigError` type (we don't pull
/// in `thiserror` for one error enum).
pub fn emit_config_mod(blocks: &[ConfigIR]) -> String {
    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();

    // Sort by block name so the aggregator is reorder-stable.
    let mut sorted: Vec<&ConfigIR> = blocks.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    if sorted.is_empty() {
        writeln!(out, "// No `config` declarations in scope yet.").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]")
            .unwrap();
        writeln!(out, "pub struct Config {{}}").unwrap();
        writeln!(out).unwrap();
        emit_config_error(&mut out);
        emit_config_impl(&mut out, &[]);
        return out;
    }

    for c in &sorted {
        writeln!(out, "pub mod {};", snake_case(&c.name)).unwrap();
    }
    writeln!(out).unwrap();
    for c in &sorted {
        let stem = snake_case(&c.name);
        let sname = struct_name(&c.name);
        writeln!(out, "pub use {stem}::{sname};").unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/// Aggregate bundle of every `config` block declared in the DSL.").unwrap();
    writeln!(out, "/// Embedded in `SimState` so runtime code reads tunables via").unwrap();
    writeln!(out, "/// `state.config.<block>.<field>`; loaded from TOML at startup").unwrap();
    writeln!(out, "/// via [`Config::from_toml`], or [`Config::default`] bakes in the").unwrap();
    writeln!(out, "/// DSL's `= <default>` clauses.").unwrap();
    writeln!(out, "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]").unwrap();
    writeln!(out, "pub struct Config {{").unwrap();
    for c in &sorted {
        let sname = struct_name(&c.name);
        let field = snake_case(&c.name);
        writeln!(out, "    #[serde(default)]").unwrap();
        writeln!(out, "    pub {field}: {sname},").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    emit_config_error(&mut out);
    emit_config_impl(&mut out, &sorted);
    out
}

/// Emit `assets/config/default.toml` — one `[block]` table per config block,
/// with each declared field at its DSL `= <default>` value. Re-running the
/// compiler overwrites this file; the intent is that hand edits between
/// compiler runs represent a user's balance-tuning snapshot, and once a
/// schema change lands the user merges their tune-deltas back onto the
/// regenerated file.
pub fn emit_config_toml(blocks: &[ConfigIR]) -> Result<String, EmitError> {
    let mut out = String::new();
    writeln!(out, "# GENERATED by dsl_compiler from the `config` blocks in assets/sim/.").unwrap();
    writeln!(out, "# Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out, "# Hand edits to this file are appropriate for TUNING — changes will").unwrap();
    writeln!(out, "# be read at runtime via Config::from_toml. Do NOT change the set of").unwrap();
    writeln!(out, "# fields here; that bumps the config schema hash. Change values freely.").unwrap();
    writeln!(out).unwrap();

    // Stable ordering: sorted by block name. Field order within a block
    // preserves source order (the emitted Rust struct layout depends on it,
    // and humans editing the TOML find it easier to match the DSL source).
    let mut sorted: Vec<&ConfigIR> = blocks.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    for (i, c) in sorted.iter().enumerate() {
        if i > 0 {
            writeln!(out).unwrap();
        }
        writeln!(out, "[{}]", snake_case(&c.name)).unwrap();
        for f in &c.fields {
            let lit = render_toml_default(&f.ty, &f.default)?;
            writeln!(out, "{} = {}", f.name, lit).unwrap();
        }
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Helpers — type rendering, literal rendering, header
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(out, "// GENERATED by dsl_compiler from {}.", path).unwrap(),
        None => writeln!(out, "// GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "// Do not edit by hand.").unwrap();
    writeln!(out).unwrap();
}

fn emit_config_error(out: &mut String) {
    writeln!(out, "/// Loader error for [`Config::from_toml`]. Kept tiny so `engine_rules`").unwrap();
    writeln!(out, "/// doesn't need `thiserror` / `anyhow`; the two underlying error types").unwrap();
    writeln!(out, "/// (`std::io::Error` on the file read, `toml::de::Error` on parse) are").unwrap();
    writeln!(out, "/// wrapped by hand-emitted `From` impls.").unwrap();
    writeln!(out, "#[derive(Debug)]").unwrap();
    writeln!(out, "pub enum ConfigError {{").unwrap();
    writeln!(out, "    Io(std::io::Error),").unwrap();
    writeln!(out, "    Parse(toml::de::Error),").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl From<std::io::Error> for ConfigError {{").unwrap();
    writeln!(out, "    fn from(e: std::io::Error) -> Self {{ ConfigError::Io(e) }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl From<toml::de::Error> for ConfigError {{").unwrap();
    writeln!(out, "    fn from(e: toml::de::Error) -> Self {{ ConfigError::Parse(e) }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl std::fmt::Display for ConfigError {{").unwrap();
    writeln!(out, "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    writeln!(out, "            ConfigError::Io(e) => write!(f, \"config io error: {{e}}\"),").unwrap();
    writeln!(out, "            ConfigError::Parse(e) => write!(f, \"config parse error: {{e}}\"),").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl std::error::Error for ConfigError {{}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_config_impl(out: &mut String, _blocks: &[&ConfigIR]) {
    writeln!(out, "impl Config {{").unwrap();
    writeln!(out, "    /// Read + parse a TOML file into a fully-populated `Config`.").unwrap();
    writeln!(out, "    /// Unknown tables are ignored by `serde`'s default behaviour;").unwrap();
    writeln!(out, "    /// missing fields fall back to their `Default` values via the").unwrap();
    writeln!(out, "    /// per-block `#[serde(default)]` attribute on this struct.").unwrap();
    writeln!(out, "    pub fn from_toml(path: &std::path::Path) -> Result<Self, ConfigError> {{").unwrap();
    writeln!(out, "        let s = std::fs::read_to_string(path)?;").unwrap();
    writeln!(out, "        let cfg = toml::from_str(&s)?;").unwrap();
    writeln!(out, "        Ok(cfg)").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

/// Produce the Rust type name for an `IrType` constrained to the config
/// primitive surface: bool / iN / uN / f32 / f64 / String. Anything outside
/// that surface is rejected here (config blocks don't allow nested structs
/// or arrays in this milestone).
fn rust_type_name(ty: &IrType) -> Result<&'static str, EmitError> {
    Ok(match ty {
        IrType::Bool => "bool",
        IrType::I8 => "i8",
        IrType::U8 => "u8",
        IrType::I16 => "i16",
        IrType::U16 => "u16",
        IrType::I32 => "i32",
        IrType::U32 => "u32",
        IrType::I64 => "i64",
        IrType::U64 => "u64",
        IrType::F32 => "f32",
        IrType::F64 => "f64",
        IrType::String => "String",
        other => {
            return Err(EmitError::Unsupported(format!(
                "config field type {other:?} is outside the permitted primitive surface \
                 (bool/iN/uN/f32/f64/String)"
            )))
        }
    })
}

/// Render a default literal for the Rust `Default::default` body. Reconciles
/// the declared type with the parsed literal so `u32 = 10` is written as
/// `10u32`, and `f32 = 1.0` stays `1.0_f32`. Strings use Rust's debug form
/// so embedded quotes / escapes round-trip.
fn render_default(ty: &IrType, def: &ast::ConfigDefault) -> Result<String, EmitError> {
    match (ty, def) {
        (IrType::Bool, ast::ConfigDefault::Bool(b)) => Ok(if *b { "true".into() } else { "false".into() }),
        (IrType::F32, ast::ConfigDefault::Float(v)) => Ok(format!("{}_f32", render_float(*v))),
        (IrType::F64, ast::ConfigDefault::Float(v)) => Ok(format!("{}_f64", render_float(*v))),
        (IrType::F32, ast::ConfigDefault::Int(v)) => Ok(format!("{}_f32", render_float(*v as f64))),
        (IrType::F64, ast::ConfigDefault::Int(v)) => Ok(format!("{}_f64", render_float(*v as f64))),
        (IrType::F32, ast::ConfigDefault::Uint(v)) => Ok(format!("{}_f32", render_float(*v as f64))),
        (IrType::F64, ast::ConfigDefault::Uint(v)) => Ok(format!("{}_f64", render_float(*v as f64))),
        (IrType::String, ast::ConfigDefault::String(s)) => Ok(format!("String::from({s:?})")),
        (int_ty, ast::ConfigDefault::Uint(v)) if is_integer(int_ty) => {
            Ok(format!("{}{}", v, int_suffix(int_ty)))
        }
        (int_ty, ast::ConfigDefault::Int(v)) if is_integer(int_ty) => {
            Ok(format!("{}{}", v, int_suffix(int_ty)))
        }
        (ty, def) => Err(EmitError::Unsupported(format!(
            "type {ty:?} is not assignable from default literal {def:?}"
        ))),
    }
}

/// Render a default literal for the TOML table. TOML booleans are bare
/// `true`/`false`, integers are bare decimal, floats always carry a decimal
/// point or exponent (same rule as the Rust emitter), strings use TOML's
/// basic-string form with the standard backslash escapes.
fn render_toml_default(ty: &IrType, def: &ast::ConfigDefault) -> Result<String, EmitError> {
    match (ty, def) {
        (IrType::Bool, ast::ConfigDefault::Bool(b)) => Ok(if *b { "true".into() } else { "false".into() }),
        (IrType::F32 | IrType::F64, ast::ConfigDefault::Float(v)) => Ok(render_float(*v)),
        (IrType::F32 | IrType::F64, ast::ConfigDefault::Int(v)) => Ok(render_float(*v as f64)),
        (IrType::F32 | IrType::F64, ast::ConfigDefault::Uint(v)) => Ok(render_float(*v as f64)),
        (IrType::String, ast::ConfigDefault::String(s)) => Ok(toml_string(s)),
        (int_ty, ast::ConfigDefault::Uint(v)) if is_integer(int_ty) => Ok(format!("{v}")),
        (int_ty, ast::ConfigDefault::Int(v)) if is_integer(int_ty) => Ok(format!("{v}")),
        (ty, def) => Err(EmitError::Unsupported(format!(
            "type {ty:?} has no TOML representation for default literal {def:?}"
        ))),
    }
}

fn is_integer(ty: &IrType) -> bool {
    matches!(
        ty,
        IrType::I8
            | IrType::U8
            | IrType::I16
            | IrType::U16
            | IrType::I32
            | IrType::U32
            | IrType::I64
            | IrType::U64
    )
}

fn int_suffix(ty: &IrType) -> &'static str {
    match ty {
        IrType::I8 => "i8",
        IrType::U8 => "u8",
        IrType::I16 => "i16",
        IrType::U16 => "u16",
        IrType::I32 => "i32",
        IrType::U32 => "u32",
        IrType::I64 => "i64",
        IrType::U64 => "u64",
        _ => "",
    }
}

fn render_float(v: f64) -> String {
    let s = format!("{v}");
    if s.contains('.') || s.contains('e') || s.contains('E') || s == "inf" || s == "-inf" || s == "NaN" {
        s
    } else {
        format!("{s}.0")
    }
}

/// Emit a TOML basic string. Minimal escapes: `\"`, `\\`, `\n`, `\t`, `\r`.
/// Anything outside printable ASCII goes through as-is (TOML is UTF-8).
fn toml_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

// ---------------------------------------------------------------------------
// Naming — snake_case / struct name
// ---------------------------------------------------------------------------

fn struct_name(block_name: &str) -> String {
    // DSL authors use lower_snake block names (`combat`, `movement`, ...);
    // the emitted struct gets a PascalCase + `Config` suffix so downstream
    // call sites read `CombatConfig` / `MovementConfig`.
    let pascal = pascal_case(block_name);
    format!("{pascal}Config")
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '_' || ch == '-' {
            upper_next = true;
        } else if upper_next {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::ConfigFieldIR;

    fn cfg_block(name: &str, fields: Vec<(&str, IrType, ast::ConfigDefault)>) -> ConfigIR {
        ConfigIR {
            name: name.into(),
            fields: fields
                .into_iter()
                .map(|(n, ty, def)| ConfigFieldIR {
                    name: n.into(),
                    ty,
                    default: def,
                    span: Span::dummy(),
                })
                .collect(),
            annotations: vec![],
            span: Span::dummy(),
        }
    }

    #[test]
    fn struct_emits_field_per_entry() {
        let block = cfg_block(
            "combat",
            vec![
                ("attack_damage", IrType::F32, ast::ConfigDefault::Float(10.0)),
                ("attack_range", IrType::F32, ast::ConfigDefault::Float(2.0)),
            ],
        );
        let out = emit_config(&block, Some("assets/sim/config.sim")).unwrap();
        assert!(out.contains("pub struct CombatConfig {"));
        assert!(out.contains("pub attack_damage: f32,"));
        assert!(out.contains("pub attack_range: f32,"));
        assert!(out.contains("attack_damage: 10.0_f32,"));
        assert!(out.contains("attack_range: 2.0_f32,"));
        assert!(out.contains("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"));
        assert!(out.contains("#[serde(default)]"));
    }

    #[test]
    fn int_and_bool_defaults_render_correctly() {
        let block = cfg_block(
            "misc",
            vec![
                ("limit", IrType::U32, ast::ConfigDefault::Uint(32)),
                ("negative", IrType::I32, ast::ConfigDefault::Int(-1)),
                ("flag", IrType::Bool, ast::ConfigDefault::Bool(true)),
            ],
        );
        let out = emit_config(&block, None).unwrap();
        assert!(out.contains("limit: 32u32,"));
        assert!(out.contains("negative: -1i32,"));
        assert!(out.contains("flag: true,"));
    }

    #[test]
    fn mod_rs_has_aggregate_config_struct() {
        let combat = cfg_block(
            "combat",
            vec![("attack_damage", IrType::F32, ast::ConfigDefault::Float(10.0))],
        );
        let movement = cfg_block(
            "movement",
            vec![("move_speed_mps", IrType::F32, ast::ConfigDefault::Float(1.0))],
        );
        let out = emit_config_mod(&[combat, movement]);
        assert!(out.contains("pub mod combat;"));
        assert!(out.contains("pub mod movement;"));
        assert!(out.contains("pub use combat::CombatConfig;"));
        assert!(out.contains("pub use movement::MovementConfig;"));
        assert!(out.contains("pub struct Config {"));
        assert!(out.contains("pub combat: CombatConfig,"));
        assert!(out.contains("pub movement: MovementConfig,"));
        assert!(out.contains("pub fn from_toml("));
        assert!(out.contains("pub enum ConfigError"));
    }

    #[test]
    fn toml_default_table_roundtrip_shape() {
        let combat = cfg_block(
            "combat",
            vec![
                ("attack_damage", IrType::F32, ast::ConfigDefault::Float(10.0)),
                ("attack_range", IrType::F32, ast::ConfigDefault::Float(2.0)),
            ],
        );
        let movement = cfg_block(
            "movement",
            vec![("move_speed_mps", IrType::F32, ast::ConfigDefault::Float(1.0))],
        );
        let out = emit_config_toml(&[movement, combat]).unwrap();
        // Sorted: combat before movement.
        let combat_pos = out.find("[combat]").expect("combat table");
        let movement_pos = out.find("[movement]").expect("movement table");
        assert!(combat_pos < movement_pos);
        assert!(out.contains("attack_damage = 10.0"));
        assert!(out.contains("move_speed_mps = 1.0"));
    }

    #[test]
    fn empty_blocks_still_produce_valid_config_struct() {
        let out = emit_config_mod(&[]);
        assert!(out.contains("pub struct Config {}"));
        assert!(out.contains("pub fn from_toml("));
    }
}
