//! Rust emission for compiler milestone 3 — `physics` cascade handlers.
//!
//! Every `physics` declaration produces:
//!
//! 1. A standalone module file `physics/<snake_case>.rs` carrying:
//!    - A unit struct `<Name>Handler`.
//!    - An `impl CascadeHandler` block whose `handle` body is the
//!      mechanically lowered DSL handler body.
//!    - A `pub fn register(registry: &mut CascadeRegistry)` shim that
//!      installs the handler.
//! 2. An entry in the aggregate `physics/mod.rs`'s `register` fn that
//!    forwards to each per-handler `register`. The aggregate fn is the
//!    single hook the engine calls during builtin registration.
//!
//! The emitter is deliberately verbose — `writeln!` into a `String`, no
//! macros, no helper traits beyond a tiny set of lowering fns shared with
//! the event emitter. Reviewers should be able to skim the emitted output
//! without tracing any abstractions back to the emitter.
//!
//! Body lowering is intentionally narrow at milestone 3: the DSL surface
//! that the damage rule exercises (let, if, emit, the `agents.*` accessor
//! namespace, `min` / `max` builtins, basic arithmetic, comparisons). Any
//! IR construct outside this surface raises `EmitError::Unsupported`. As
//! more physics rules migrate, the emitter grows to cover what they need
//! and nothing more.

use std::collections::BTreeSet;
use std::fmt::Write;

use crate::ast::{BinOp, UnOp};
use crate::ir::{
    Builtin, IrEmit, IrExpr, IrExprNode, IrPattern, IrPatternBinding, IrStmt, NamespaceId,
    PhysicsHandlerIR, PhysicsIR,
};

/// Errors raised during physics emission. Propagated up to the xtask which
/// renders them with a path + the offending rule name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    /// The pattern lacked an event ref — meaning the event name didn't
    /// resolve to a declared event during lowering. Likely a missing
    /// `event` declaration in the same compilation unit.
    UnresolvedEventInPattern(String),
    /// The `emit` statement names an event the compiler doesn't know.
    UnresolvedEventInEmit(String),
    /// Some IR construct isn't supported by the milestone-3 emitter yet.
    /// Carries a short diagnostic string with the offending shape.
    Unsupported(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::UnresolvedEventInPattern(n) => {
                write!(f, "physics handler matches event `{n}` which is not declared")
            }
            EmitError::UnresolvedEventInEmit(n) => {
                write!(f, "physics handler emits event `{n}` which is not declared")
            }
            EmitError::Unsupported(s) => write!(f, "physics emission: {s}"),
        }
    }
}

impl std::error::Error for EmitError {}

// ---------------------------------------------------------------------------
// Public emission entry points
// ---------------------------------------------------------------------------

/// Emit a single physics module file (`physics/<snake_case>.rs`).
///
/// `source_file` is the DSL source path the rule came from. If the path is
/// known we stamp it into the header; otherwise we emit a generic header.
pub fn emit_physics(physics: &PhysicsIR, source_file: Option<&str>) -> Result<String, EmitError> {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    emit_imports(&mut out, physics)?;
    emit_handler_struct(&mut out, physics);
    emit_impl_block(&mut out, physics)?;
    emit_register_fn(&mut out, physics);
    Ok(out)
}

/// Emit the aggregate `physics/mod.rs` — re-exports each per-rule module
/// and exposes a single `register(registry)` that forwards to every
/// handler's `register` shim. Sorted alphabetically so rustfmt is a no-op.
pub fn emit_physics_mod(physics: &[PhysicsIR]) -> String {
    let mut sorted: Vec<&PhysicsIR> = physics.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();

    for p in &sorted {
        writeln!(out, "pub mod {};", snake_case(&p.name)).unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "use crate::cascade::CascadeRegistry;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/// Install every compiler-emitted physics handler on `registry`.").unwrap();
    writeln!(out, "/// Called from `CascadeRegistry::register_engine_builtins` so the").unwrap();
    writeln!(out, "/// engine's built-in handler set picks up DSL-owned rules without").unwrap();
    writeln!(out, "/// the engine knowing about each handler by name.").unwrap();
    writeln!(out, "pub fn register(registry: &mut CascadeRegistry) {{").unwrap();
    if sorted.is_empty() {
        writeln!(out, "    let _ = registry;").unwrap();
    } else {
        for p in &sorted {
            writeln!(out, "    {}::register(registry);", snake_case(&p.name)).unwrap();
        }
    }
    writeln!(out, "}}").unwrap();

    out
}

// ---------------------------------------------------------------------------
// Header / imports
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(out, "// GENERATED by dsl_compiler from {}.", path).unwrap(),
        None => writeln!(out, "// GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "// Do not edit by hand.").unwrap();
    writeln!(out).unwrap();
}

/// Walk the rule's pattern + body to find every event we reference (the
/// trigger pattern + every `emit` statement). The handler always imports
/// `Event`, `EventRing`, `SimState`, `CascadeHandler`, `CascadeRegistry`,
/// `EventKindId`, `Lane`. Any niche IDs surfaced by the emit-statement
/// fields are unused at the import site (the values flow through `state`
/// / `events` references), so we don't need to declare them here.
fn emit_imports(out: &mut String, physics: &PhysicsIR) -> Result<(), EmitError> {
    // Walk to surface every emitted event name — a sanity check that all
    // emit statements name declared events. We don't actually emit
    // per-event imports; the `Event` enum import covers them.
    let mut seen: BTreeSet<String> = BTreeSet::new();
    for handler in &physics.handlers {
        if handler.pattern.event.is_none() {
            return Err(EmitError::UnresolvedEventInPattern(handler.pattern.name.clone()));
        }
        seen.insert(handler.pattern.name.clone());
        scan_emits(&handler.body, &mut seen)?;
    }

    writeln!(out, "use crate::cascade::{{CascadeHandler, CascadeRegistry, EventKindId, Lane}};")
        .unwrap();
    writeln!(out, "use crate::event::{{Event, EventRing}};").unwrap();
    writeln!(out, "use crate::state::SimState;").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

fn scan_emits(stmts: &[IrStmt], seen: &mut BTreeSet<String>) -> Result<(), EmitError> {
    for s in stmts {
        match s {
            IrStmt::Emit(e) => {
                if e.event.is_none() {
                    return Err(EmitError::UnresolvedEventInEmit(e.event_name.clone()));
                }
                seen.insert(e.event_name.clone());
            }
            IrStmt::If { then_body, else_body, .. } => {
                scan_emits(then_body, seen)?;
                if let Some(b) = else_body {
                    scan_emits(b, seen)?;
                }
            }
            IrStmt::For { body, .. } => scan_emits(body, seen)?,
            IrStmt::Match { arms, .. } => {
                for arm in arms {
                    scan_emits(&arm.body, seen)?;
                }
            }
            IrStmt::Let { .. } | IrStmt::Expr(_) | IrStmt::SelfUpdate { .. } => {}
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Struct + impl + register fn
// ---------------------------------------------------------------------------

fn emit_handler_struct(out: &mut String, physics: &PhysicsIR) {
    writeln!(out, "pub struct {}Handler;", pascal_case(&physics.name)).unwrap();
    writeln!(out).unwrap();
}

fn emit_impl_block(out: &mut String, physics: &PhysicsIR) -> Result<(), EmitError> {
    let struct_name = format!("{}Handler", pascal_case(&physics.name));
    // Milestone 3 supports exactly one handler per physics declaration —
    // the damage rule has one. Multi-handler bodies (multiple `on` clauses
    // in a single `physics` block) raise Unsupported until a follow-up
    // commit grows the emitter to dispatch on the event variant.
    if physics.handlers.len() != 1 {
        return Err(EmitError::Unsupported(format!(
            "expected exactly one `on` handler per physics rule (got {} in `{}`)",
            physics.handlers.len(),
            physics.name
        )));
    }
    let handler = &physics.handlers[0];

    writeln!(out, "impl CascadeHandler for {struct_name} {{").unwrap();
    writeln!(out, "    fn trigger(&self) -> EventKindId {{ EventKindId::{} }}", handler.pattern.name)
        .unwrap();
    // Lane defaults to Effect — milestone 3 doesn't surface a `@lane` annotation
    // yet. Every physics rule lands in the Effect lane, matching the legacy
    // `register_engine_builtins` registrations.
    writeln!(out, "    fn lane(&self) -> Lane {{ Lane::Effect }}").unwrap();
    writeln!(out).unwrap();
    // `#[allow(unused_variables)]` covers the event-pattern bindings — some
    // handlers (e.g. shield) don't reference `caster` or `tick` in their
    // body. We could track which bindings are live by walking the body, but
    // it's mechanical noise: the generated file is already machine-owned and
    // the `-D warnings` CI guard is what forces the allow.
    writeln!(out, "    #[allow(unused_variables)]").unwrap();
    writeln!(
        out,
        "    fn handle(&self, event: &Event, state: &mut SimState, events: &mut EventRing) {{"
    )
    .unwrap();

    emit_handler_body(out, handler)?;

    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

fn emit_register_fn(out: &mut String, physics: &PhysicsIR) {
    let struct_name = format!("{}Handler", pascal_case(&physics.name));
    writeln!(out, "pub fn register(registry: &mut CascadeRegistry) {{").unwrap();
    writeln!(out, "    registry.register({struct_name});").unwrap();
    writeln!(out, "}}").unwrap();
}

// ---------------------------------------------------------------------------
// Handler body: pattern destructure + statement lowering
// ---------------------------------------------------------------------------

/// Indent depth for handler statements: 8 spaces (two indent steps inside
/// the `fn handle` body). Nested constructs add 4 spaces per level.
const BASE_INDENT: usize = 8;

fn emit_handler_body(out: &mut String, handler: &PhysicsHandlerIR) -> Result<(), EmitError> {
    // Destructure the trigger event into named locals. We pin the "_" arm
    // returning early so the engine cascade dispatcher's call shape stays
    // identical to the hand-written legacy handler.
    let event_name = &handler.pattern.name;
    let bindings = collect_pattern_bindings(&handler.pattern.bindings)?;

    if bindings.is_empty() {
        writeln!(
            out,
            "        if !matches!(*event, Event::{event_name} {{ .. }}) {{ return; }}"
        )
        .unwrap();
    } else {
        let names: Vec<String> = bindings.iter().map(|(_, name)| name.clone()).collect();
        let tuple = if names.len() == 1 {
            names[0].clone()
        } else {
            format!("({})", names.join(", "))
        };
        let field_pat: Vec<String> = bindings
            .iter()
            .map(|(field, name)| {
                if field == name {
                    field.clone()
                } else {
                    format!("{field}: {name}")
                }
            })
            .collect();
        let value_tuple = if names.len() == 1 {
            names[0].clone()
        } else {
            format!("({})", names.join(", "))
        };
        writeln!(out, "        let {tuple} = match *event {{").unwrap();
        writeln!(
            out,
            "            Event::{event_name} {{ {}, .. }} => {value_tuple},",
            field_pat.join(", ")
        )
        .unwrap();
        writeln!(out, "            _ => return,").unwrap();
        writeln!(out, "        }};").unwrap();
    }

    if let Some(where_clause) = &handler.where_clause {
        let cond = lower_expr(where_clause)?;
        writeln!(out, "        if !({cond}) {{ return; }}").unwrap();
    }

    for stmt in &handler.body {
        emit_stmt(out, stmt, BASE_INDENT)?;
    }

    Ok(())
}

/// Returns a list of `(event_field_name, local_binding_name)` pairs. Only
/// simple ident binds (`field: local`) are accepted at milestone 3 — ctor /
/// wildcard / nested patterns aren't part of the damage rule's surface and
/// would land as `Unsupported`.
fn collect_pattern_bindings(
    bindings: &[IrPatternBinding],
) -> Result<Vec<(String, String)>, EmitError> {
    let mut out = Vec::with_capacity(bindings.len());
    for b in bindings {
        match &b.value {
            IrPattern::Bind { name, .. } => out.push((b.field.clone(), name.clone())),
            IrPattern::Wildcard => {}
            other => {
                return Err(EmitError::Unsupported(format!(
                    "pattern binding for field `{}` is {:?}; only simple ident binds supported in milestone 3",
                    b.field, other
                )));
            }
        }
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Statement lowering
// ---------------------------------------------------------------------------

fn emit_stmt(out: &mut String, stmt: &IrStmt, indent: usize) -> Result<(), EmitError> {
    let pad = " ".repeat(indent);
    match stmt {
        IrStmt::Let { name, value, .. } => {
            let v = lower_expr(value)?;
            writeln!(out, "{pad}let {name} = {v};").unwrap();
        }
        IrStmt::Emit(emit) => emit_emit(out, emit, indent)?,
        IrStmt::If { cond, then_body, else_body, .. } => {
            let c = lower_expr(cond)?;
            writeln!(out, "{pad}if {c} {{").unwrap();
            for s in then_body {
                emit_stmt(out, s, indent + 4)?;
            }
            if let Some(eb) = else_body {
                writeln!(out, "{pad}}} else {{").unwrap();
                for s in eb {
                    emit_stmt(out, s, indent + 4)?;
                }
            }
            writeln!(out, "{pad}}}").unwrap();
        }
        IrStmt::For { .. } => {
            return Err(EmitError::Unsupported(
                "`for` statements not supported in milestone 3 physics emission".into(),
            ));
        }
        IrStmt::Match { .. } => {
            return Err(EmitError::Unsupported(
                "`match` statements not supported in milestone 3 physics emission".into(),
            ));
        }
        IrStmt::SelfUpdate { .. } => {
            return Err(EmitError::Unsupported(
                "`self += ...` self-update statements only valid in fold bodies".into(),
            ));
        }
        IrStmt::Expr(e) => {
            // Any standalone expression — typically a namespace call returning
            // unit (`agents.set_hp(t, v)`, `agents.kill(t)`). Lower it as an
            // expression and terminate with `;`.
            let v = lower_expr(e)?;
            writeln!(out, "{pad}{v};").unwrap();
        }
    }
    Ok(())
}

fn emit_emit(out: &mut String, emit: &IrEmit, indent: usize) -> Result<(), EmitError> {
    let pad = " ".repeat(indent);
    if emit.event.is_none() {
        return Err(EmitError::UnresolvedEventInEmit(emit.event_name.clone()));
    }
    let mut field_lines: Vec<String> = Vec::with_capacity(emit.fields.len());
    for f in &emit.fields {
        let v = lower_expr(&f.value)?;
        if f.name == v {
            field_lines.push(f.name.clone());
        } else {
            field_lines.push(format!("{}: {}", f.name, v));
        }
    }
    let body = if field_lines.is_empty() {
        String::new()
    } else {
        format!(" {} ", field_lines.join(", "))
    };
    writeln!(
        out,
        "{pad}events.push(Event::{} {{{body}}});",
        emit.event_name
    )
    .unwrap();
    Ok(())
}

// ---------------------------------------------------------------------------
// Expression lowering
// ---------------------------------------------------------------------------

fn lower_expr(node: &IrExprNode) -> Result<String, EmitError> {
    lower_expr_kind(&node.kind)
}

fn lower_expr_kind(kind: &IrExpr) -> Result<String, EmitError> {
    match kind {
        IrExpr::LitBool(b) => Ok(if *b { "true".into() } else { "false".into() }),
        IrExpr::LitInt(v) => Ok(format!("{v}")),
        IrExpr::LitFloat(v) => Ok(render_float(*v)),
        IrExpr::LitString(s) => Ok(format!("{s:?}")),
        IrExpr::Local(_, name) => Ok(name.clone()),
        IrExpr::NamespaceCall { ns, method, args } => lower_namespace_call(*ns, method, args),
        IrExpr::Binary(op, lhs, rhs) => {
            let l = lower_expr(lhs)?;
            let r = lower_expr(rhs)?;
            Ok(format!("({l} {} {r})", binop_str(*op)))
        }
        IrExpr::Unary(op, rhs) => {
            let r = lower_expr(rhs)?;
            Ok(format!("({}{r})", unop_str(*op)))
        }
        IrExpr::BuiltinCall(b, args) => lower_builtin_call(*b, args),
        IrExpr::If { cond, then_expr, else_expr } => {
            let c = lower_expr(cond)?;
            let t = lower_expr(then_expr)?;
            let e = match else_expr {
                Some(e) => lower_expr(e)?,
                None => return Err(EmitError::Unsupported("`if` expression without else".into())),
            };
            Ok(format!("(if {c} {{ {t} }} else {{ {e} }})"))
        }
        IrExpr::Field { base, field_name, .. } => {
            // Direct field access on an event-pattern local — mostly used
            // when authors thread `event.field`-shaped DSL through. For
            // milestone 3 we surface this as a verbatim Rust field access;
            // the semantic check (does the field exist on the local's type?)
            // belongs to a later compiler pass.
            let b = lower_expr(base)?;
            Ok(format!("{b}.{field_name}"))
        }
        // Everything else is out of milestone-3 scope. We surface the IR
        // variant name so the diagnostic points at the right place.
        other => Err(EmitError::Unsupported(format!(
            "expression shape {other:?} not supported in milestone 3 physics emission"
        ))),
    }
}

fn lower_namespace_call(
    ns: NamespaceId,
    method: &str,
    args: &[crate::ir::IrCallArg],
) -> Result<String, EmitError> {
    // Lower the args first so positional / named treatment is uniform —
    // milestone 3 only sees positional args.
    let lowered: Vec<String> = args
        .iter()
        .map(|a| {
            if a.name.is_some() {
                return Err(EmitError::Unsupported(format!(
                    "named argument on stdlib call `{}.{method}` not supported",
                    ns.name()
                )));
            }
            lower_expr(&a.value)
        })
        .collect::<Result<_, _>>()?;
    match (ns, method) {
        // `agents` accessor surface — these map one-to-one onto SimState
        // methods, with the engine's `Option<f32>` getters defaulted to 0.0
        // (matching the legacy handler's `unwrap_or(0.0)`).
        (NamespaceId::Agents, "alive") => {
            expect_arity(args, 1, "agents.alive")?;
            Ok(format!("state.agent_alive({})", lowered[0]))
        }
        (NamespaceId::Agents, "hp") => {
            expect_arity(args, 1, "agents.hp")?;
            Ok(format!("state.agent_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "shield_hp") => {
            expect_arity(args, 1, "agents.shield_hp")?;
            Ok(format!("state.agent_shield_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_hp") => {
            expect_arity(args, 2, "agents.set_hp")?;
            Ok(format!("state.set_agent_hp({}, {})", lowered[0], lowered[1]))
        }
        (NamespaceId::Agents, "set_shield_hp") => {
            expect_arity(args, 2, "agents.set_shield_hp")?;
            Ok(format!("state.set_agent_shield_hp({}, {})", lowered[0], lowered[1]))
        }
        (NamespaceId::Agents, "kill") => {
            expect_arity(args, 1, "agents.kill")?;
            Ok(format!("state.kill_agent({})", lowered[0]))
        }
        // Heal clamp reads the target's authored max hp. Absent slots default
        // the max to the current hp (legacy `unwrap_or(cur_hp)` semantics); we
        // return 0.0 here and leave the DSL author to reference `max(cur_hp, ...)`
        // if they want a non-zero fallback. The heal rule doesn't need it
        // because it guards on `alive(t)` first — an alive slot always has a
        // max_hp.
        (NamespaceId::Agents, "max_hp") => {
            expect_arity(args, 1, "agents.max_hp")?;
            Ok(format!("state.agent_max_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "attack_damage") => {
            expect_arity(args, 1, "agents.attack_damage")?;
            // Legacy fallback was `ATTACK_DAMAGE` from step.rs — passed in so
            // the opportunity-attack rule sees the kernel's default when the
            // slot is empty. `crate::step::ATTACK_DAMAGE` is the engine
            // constant.
            Ok(format!(
                "state.agent_attack_damage({}).unwrap_or(crate::step::ATTACK_DAMAGE)",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "stun_remaining_ticks") => {
            expect_arity(args, 1, "agents.stun_remaining_ticks")?;
            Ok(format!("state.agent_stun_remaining({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_stun_remaining_ticks") => {
            expect_arity(args, 2, "agents.set_stun_remaining_ticks")?;
            Ok(format!(
                "state.set_agent_stun_remaining({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "slow_remaining_ticks") => {
            expect_arity(args, 1, "agents.slow_remaining_ticks")?;
            Ok(format!("state.agent_slow_remaining({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_slow_remaining_ticks") => {
            expect_arity(args, 2, "agents.set_slow_remaining_ticks")?;
            Ok(format!(
                "state.set_agent_slow_remaining({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "slow_factor_q8") => {
            expect_arity(args, 1, "agents.slow_factor_q8")?;
            Ok(format!("state.agent_slow_factor_q8({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_slow_factor_q8") => {
            expect_arity(args, 2, "agents.set_slow_factor_q8")?;
            Ok(format!(
                "state.set_agent_slow_factor_q8({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "gold") => {
            expect_arity(args, 1, "agents.gold")?;
            // Gold lives inside the per-agent `Inventory` struct on
            // `SimState::cold_inventory`. Missing slots contribute 0.
            Ok(format!(
                "state.agent_inventory({}).map(|i| i.gold).unwrap_or(0)",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "set_gold") => {
            expect_arity(args, 2, "agents.set_gold")?;
            // Write preserves the other Inventory fields. If the slot is
            // absent (dead / uninit), the write is silently dropped — same
            // semantic as the legacy `set_agent_inventory` which short-circuits
            // when the slot is missing.
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = {v}; state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "add_gold") => {
            expect_arity(args, 2, "agents.add_gold")?;
            // Wrapping add — preserves the exact legacy `TransferGoldHandler`
            // semantics (i64 overflow wraps, doesn't panic). No-op if the slot
            // is absent.
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = __inv.gold.wrapping_add({v}); state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "sub_gold") => {
            expect_arity(args, 2, "agents.sub_gold")?;
            // Wrapping sub — paired with `add_gold` for gold-transfer. No-op
            // if the slot is absent.
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = __inv.gold.wrapping_sub({v}); state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "adjust_standing") => {
            expect_arity(args, 3, "agents.adjust_standing")?;
            // Delegates to `SimState::adjust_standing`, which clamps to
            // `[-1000, 1000]` and keys the ordered tuple `(min(a,b), max(a,b))`.
            // Return value (the post-clamp standing) is discarded when used
            // as a statement.
            Ok(format!(
                "state.adjust_standing({}, {}, {})",
                lowered[0], lowered[1], lowered[2]
            ))
        }
        _ => Err(EmitError::Unsupported(format!(
            "stdlib call `{}.{method}` not supported in milestone 3 physics emission",
            ns.name()
        ))),
    }
}

fn lower_builtin_call(b: Builtin, args: &[crate::ir::IrCallArg]) -> Result<String, EmitError> {
    let lowered: Vec<String> = args
        .iter()
        .map(|a| {
            if a.name.is_some() {
                return Err(EmitError::Unsupported(format!(
                    "named argument on builtin `{}` not supported",
                    b.name()
                )));
            }
            lower_expr(&a.value)
        })
        .collect::<Result<_, _>>()?;
    match b {
        Builtin::Min => {
            expect_arity(args, 2, "min")?;
            // f32::min — wrap LHS in parens so a complex expression doesn't
            // bind the receiver wrong.
            Ok(format!("({}).min({})", lowered[0], lowered[1]))
        }
        Builtin::Max => {
            expect_arity(args, 2, "max")?;
            Ok(format!("({}).max({})", lowered[0], lowered[1]))
        }
        Builtin::Clamp => {
            expect_arity(args, 3, "clamp")?;
            Ok(format!(
                "({}).clamp({}, {})",
                lowered[0], lowered[1], lowered[2]
            ))
        }
        Builtin::Abs => {
            expect_arity(args, 1, "abs")?;
            Ok(format!("({}).abs()", lowered[0]))
        }
        Builtin::Floor => {
            expect_arity(args, 1, "floor")?;
            Ok(format!("({}).floor()", lowered[0]))
        }
        Builtin::Ceil => {
            expect_arity(args, 1, "ceil")?;
            Ok(format!("({}).ceil()", lowered[0]))
        }
        Builtin::Round => {
            expect_arity(args, 1, "round")?;
            Ok(format!("({}).round()", lowered[0]))
        }
        Builtin::Sqrt => {
            expect_arity(args, 1, "sqrt")?;
            Ok(format!("({}).sqrt()", lowered[0]))
        }
        _ => Err(EmitError::Unsupported(format!(
            "builtin `{}` not supported in milestone 3 physics emission",
            b.name()
        ))),
    }
}

fn expect_arity(
    args: &[crate::ir::IrCallArg],
    expected: usize,
    name: &str,
) -> Result<(), EmitError> {
    if args.len() == expected {
        Ok(())
    } else {
        Err(EmitError::Unsupported(format!(
            "`{name}` expects {expected} arg(s), got {}",
            args.len()
        )))
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
    }
}

fn unop_str(op: UnOp) -> &'static str {
    match op {
        UnOp::Not => "!",
        UnOp::Neg => "-",
    }
}

/// Render a float so it parses back identically. `f64::to_string` drops the
/// trailing `.0` for whole numbers (`3.0` → `"3"`), which would type-infer to
/// an integer in Rust. We always emit at least one fractional digit so the
/// literal stays `f32`/`f64`-typed wherever it's used.
fn render_float(v: f64) -> String {
    let s = format!("{v}");
    if s.contains('.') || s.contains('e') || s.contains('E') || s == "inf" || s == "-inf" || s == "NaN"
    {
        s
    } else {
        format!("{s}.0")
    }
}

// ---------------------------------------------------------------------------
// Naming utilities (snake_case / PascalCase) — duplicated from emit_rust.rs
// because the event emitter's `snake_case` is module-private. Kept identical
// in behaviour; if either drifts, both must move to a shared util module.
// ---------------------------------------------------------------------------

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '_' || ch == '-' {
            upper_next = true;
        } else if upper_next {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::{
        EventField, EventIR, EventRef, IrCallArg, IrEmit, IrEventPattern, IrExpr, IrExprNode,
        IrFieldInit, IrPattern, IrPatternBinding, IrStmt, LocalRef, NamespaceId,
        PhysicsHandlerIR, PhysicsIR,
    };

    fn span() -> Span {
        Span::dummy()
    }

    fn local(name: &str, id: u16) -> IrExprNode {
        IrExprNode { kind: IrExpr::Local(LocalRef(id), name.to_string()), span: span() }
    }

    fn pattern_bind(field: &str, name: &str, id: u16) -> IrPatternBinding {
        IrPatternBinding {
            field: field.to_string(),
            value: IrPattern::Bind { name: name.to_string(), local: LocalRef(id) },
            span: span(),
        }
    }

    fn ns_call(ns: NamespaceId, method: &str, args: Vec<IrExprNode>) -> IrExprNode {
        IrExprNode {
            kind: IrExpr::NamespaceCall {
                ns,
                method: method.to_string(),
                args: args
                    .into_iter()
                    .map(|a| IrCallArg { name: None, value: a, span: span() })
                    .collect(),
            },
            span: span(),
        }
    }

    fn _event(name: &str) -> EventIR {
        EventIR {
            name: name.into(),
            fields: vec![EventField { name: "tick".into(), ty: crate::ir::IrType::U32, span: span() }],
            annotations: vec![],
            span: span(),
        }
    }

    fn make_minimal_handler() -> PhysicsIR {
        // Pattern: on EffectDamageApplied { target: t, amount: a, tick: tk }
        let pattern = IrEventPattern {
            name: "EffectDamageApplied".into(),
            event: Some(EventRef(0)),
            bindings: vec![
                pattern_bind("target", "t", 0),
                pattern_bind("amount", "a", 1),
                pattern_bind("tick", "tk", 2),
            ],
            span: span(),
        };
        // Body: agents.set_hp(t, agents.hp(t)) — a no-op call exercising the
        // namespace-call lowering + statement-expression form.
        let body = vec![IrStmt::Expr(ns_call(
            NamespaceId::Agents,
            "set_hp",
            vec![local("t", 0), ns_call(NamespaceId::Agents, "hp", vec![local("t", 0)])],
        ))];
        PhysicsIR {
            name: "noop".into(),
            handlers: vec![PhysicsHandlerIR { pattern, where_clause: None, body, span: span() }],
            annotations: vec![],
            span: span(),
        }
    }

    #[test]
    fn struct_and_register_emit() {
        let p = make_minimal_handler();
        let out = emit_physics(&p, Some("assets/sim/physics.sim")).unwrap();
        assert!(out.contains("// GENERATED by dsl_compiler from assets/sim/physics.sim."));
        assert!(out.contains("pub struct NoopHandler;"));
        assert!(out.contains("impl CascadeHandler for NoopHandler {"));
        assert!(out.contains("fn trigger(&self) -> EventKindId { EventKindId::EffectDamageApplied }"));
        assert!(out.contains("fn lane(&self) -> Lane { Lane::Effect }"));
        assert!(out.contains("pub fn register(registry: &mut CascadeRegistry) {"));
        assert!(out.contains("registry.register(NoopHandler);"));
    }

    #[test]
    fn pattern_destructure_emits_match() {
        let p = make_minimal_handler();
        let out = emit_physics(&p, None).unwrap();
        // Three bindings → `let (t, a, tk) = match *event { Event::EffectDamageApplied { target: t, amount: a, tick: tk, .. } => (t, a, tk), _ => return }`.
        assert!(out.contains("let (t, a, tk) = match *event {"));
        assert!(out.contains("Event::EffectDamageApplied { target: t, amount: a, tick: tk, .. } => (t, a, tk),"));
        assert!(out.contains("_ => return,"));
    }

    #[test]
    fn namespace_call_lowers_to_state_call() {
        let p = make_minimal_handler();
        let out = emit_physics(&p, None).unwrap();
        assert!(out.contains("state.set_agent_hp(t, state.agent_hp(t).unwrap_or(0.0));"));
    }

    #[test]
    fn aggregate_mod_register_fn() {
        let mut handlers = vec![make_minimal_handler()];
        handlers[0].name = "zebra".into();
        let mut p2 = make_minimal_handler();
        p2.name = "alpha".into();
        handlers.push(p2);
        let out = emit_physics_mod(&handlers);
        assert!(out.contains("pub mod alpha;"));
        assert!(out.contains("pub mod zebra;"));
        assert!(out.contains("pub fn register(registry: &mut CascadeRegistry)"));
        // Sorted alphabetically — alpha before zebra in the register body.
        let alpha = out.find("alpha::register").unwrap();
        let zebra = out.find("zebra::register").unwrap();
        assert!(alpha < zebra);
    }

    #[test]
    fn empty_aggregate_register_is_a_no_op() {
        let out = emit_physics_mod(&[]);
        assert!(out.contains("pub fn register(registry: &mut CascadeRegistry)"));
        assert!(out.contains("let _ = registry;"));
    }

    #[test]
    fn unresolved_emit_is_an_error() {
        let mut p = make_minimal_handler();
        p.handlers[0].body = vec![IrStmt::Emit(IrEmit {
            event_name: "Bogus".into(),
            event: None,
            fields: vec![IrFieldInit {
                name: "tick".into(),
                value: local("tk", 2),
                span: span(),
            }],
            span: span(),
        })];
        let err = emit_physics(&p, None).unwrap_err();
        assert!(matches!(err, EmitError::UnresolvedEventInEmit(_)));
    }

    #[test]
    fn pascal_and_snake_match_event_emitter() {
        assert_eq!(snake_case("Damage"), "damage");
        assert_eq!(snake_case("AgentDied"), "agent_died");
        assert_eq!(pascal_case("damage"), "Damage");
        assert_eq!(pascal_case("agent_died"), "AgentDied");
    }
}
