//! Emits `engine_gpu_rules/src/schedule.rs` — the `DispatchOp` enum and
//! the topologically-sorted `SCHEDULE` constant.
//!
//! Compile-time errors raised here (per spec):
//!   * Diamond writes — multiple rows write the same buffer.
//!   * Cycles — row X reads what Y writes and vice versa.
//!   * Unscheduled kernel — a module exists but no row produces it.

use std::collections::{BTreeMap, HashSet};
use std::fmt::Write;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DispatchOpKind {
    /// Single dispatch of one kernel.
    Kernel,
    /// Fixed-point loop over a kernel until its event ring drains.
    FixedPoint { max_iter: u32 },
    /// Indirect dispatch driven by `args_buf`.
    Indirect { args_buf_ref: String /* BufferRef variant name */ },
    /// Conditional: only run if a producer wrote a non-sentinel value.
    GatedBy { gate_ref: String /* BufferRef variant name */ },
}

#[derive(Debug, Clone)]
pub struct ScheduleEntry {
    /// PascalCase variant name in `KernelId`.
    pub kernel: String,
    pub kind: DispatchOpKind,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ScheduleError {
    DiamondWrite { buffer: String, kernels: Vec<String> },
    Cycle { path: Vec<String> },
    Unscheduled { kernel: String },
}

impl std::fmt::Display for ScheduleError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::DiamondWrite { buffer, kernels } => write!(
                f, "diamond write on buffer `{buffer}`: rows {kernels:?} both write it"
            ),
            Self::Cycle { path } => write!(f, "schedule cycle: {path:?}"),
            Self::Unscheduled { kernel } => write!(f, "unscheduled kernel `{kernel}` (no row produces it)"),
        }
    }
}

impl std::error::Error for ScheduleError {}

/// Build the schedule from a per-row read/write description.
///
/// `nodes`: each tuple is `(kernel_pascal, reads, writes)`.
///
/// Returns the entries in topological order or a `ScheduleError`.
pub fn build_schedule(
    nodes: &[(String, Vec<String>, Vec<String>)],
) -> Result<Vec<ScheduleEntry>, ScheduleError> {
    // 1. Diamond detection.
    let mut writers: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (k, _r, ws) in nodes {
        for w in ws {
            writers.entry(w.clone()).or_default().push(k.clone());
        }
    }
    for (buf, ks) in &writers {
        if ks.len() > 1 {
            return Err(ScheduleError::DiamondWrite {
                buffer: buf.clone(),
                kernels: ks.clone(),
            });
        }
    }

    // 2. Edge construction: producer(buf) -> consumer(buf).
    let kernel_set: HashSet<&str> = nodes.iter().map(|(k, _, _)| k.as_str()).collect();
    let mut adj: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut indeg: BTreeMap<String, u32> = BTreeMap::new();
    for (k, _, _) in nodes {
        adj.entry(k.clone()).or_default();
        indeg.entry(k.clone()).or_insert(0);
    }
    for (k, reads, _) in nodes {
        for r in reads {
            if let Some(producers) = writers.get(r) {
                for p in producers {
                    if p == k { continue; } // self-read is allowed (intra-kernel)
                    if !kernel_set.contains(p.as_str()) { continue; }
                    adj.get_mut(p).unwrap().push(k.clone());
                    *indeg.get_mut(k).unwrap() += 1;
                }
            }
        }
    }

    // 3. Kahn's algorithm.
    let mut queue: Vec<String> = indeg.iter()
        .filter(|(_, &d)| d == 0)
        .map(|(k, _)| k.clone())
        .collect();
    queue.sort();
    let mut order: Vec<String> = Vec::new();
    while let Some(k) = queue.pop() {
        order.push(k.clone());
        for next in adj.get(&k).cloned().unwrap_or_default() {
            let d = indeg.get_mut(&next).unwrap();
            *d -= 1;
            if *d == 0 { queue.push(next); }
        }
        queue.sort();
    }
    if order.len() != nodes.len() {
        // Cycle: report the kernels with non-zero in-degree.
        let path: Vec<String> = indeg.iter()
            .filter(|(_, &d)| d > 0)
            .map(|(k, _)| k.clone())
            .collect();
        return Err(ScheduleError::Cycle { path });
    }

    // 4. Map to ScheduleEntry. Default kind is Kernel; callers override
    //    by constructing entries directly when they need FixedPoint /
    //    Indirect / GatedBy (e.g. cascade physics).
    Ok(order.into_iter().map(|k| ScheduleEntry {
        kernel: k,
        kind: DispatchOpKind::Kernel,
    }).collect())
}

/// Emit `engine_gpu_rules/src/schedule.rs`.
pub fn emit_schedule_rs(entries: &[ScheduleEntry]) -> String {
    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler::emit_schedule. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use crate::{{KernelId, BufferRef}};").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "#[derive(Copy, Clone, Debug)]").unwrap();
    writeln!(out, "pub enum DispatchOp {{").unwrap();
    writeln!(out, "    Kernel(KernelId),").unwrap();
    writeln!(out, "    FixedPoint {{ kernel: KernelId, max_iter: u32 }},").unwrap();
    writeln!(out, "    Indirect {{ kernel: KernelId, args_buf: BufferRef }},").unwrap();
    writeln!(out, "    GatedBy {{ kernel: KernelId, gate: BufferRef }},").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    if entries.is_empty() {
        writeln!(out, "pub const SCHEDULE: &[DispatchOp] = &[];").unwrap();
        return out;
    }

    writeln!(out, "pub const SCHEDULE: &[DispatchOp] = &[").unwrap();
    for e in entries {
        match &e.kind {
            DispatchOpKind::Kernel => {
                writeln!(out, "    DispatchOp::Kernel(KernelId::{}),", e.kernel).unwrap();
            }
            DispatchOpKind::FixedPoint { max_iter } => {
                writeln!(out, "    DispatchOp::FixedPoint {{ kernel: KernelId::{}, max_iter: {max_iter} }},", e.kernel).unwrap();
            }
            DispatchOpKind::Indirect { args_buf_ref } => {
                writeln!(out, "    DispatchOp::Indirect {{ kernel: KernelId::{}, args_buf: BufferRef::{} }},", e.kernel, args_buf_ref).unwrap();
            }
            DispatchOpKind::GatedBy { gate_ref } => {
                writeln!(out, "    DispatchOp::GatedBy {{ kernel: KernelId::{}, gate: BufferRef::{} }},", e.kernel, gate_ref).unwrap();
            }
        }
    }
    writeln!(out, "];").unwrap();
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn diamond_writes_rejected() {
        let nodes = vec![
            ("A".into(), vec![],            vec!["buf".into()]),
            ("B".into(), vec![],            vec!["buf".into()]),
        ];
        let err = build_schedule(&nodes).unwrap_err();
        match err {
            ScheduleError::DiamondWrite { buffer, .. } => assert_eq!(buffer, "buf"),
            other => panic!("expected DiamondWrite, got {other:?}"),
        }
    }

    #[test]
    fn cycle_detected() {
        let nodes = vec![
            ("A".into(), vec!["b".into()], vec!["a".into()]),
            ("B".into(), vec!["a".into()], vec!["b".into()]),
        ];
        let err = build_schedule(&nodes).unwrap_err();
        assert!(matches!(err, ScheduleError::Cycle { .. }));
    }

    #[test]
    fn topo_sort_orders_producer_before_consumer() {
        let nodes = vec![
            ("Consumer".into(), vec!["x".into()], vec![]),
            ("Producer".into(), vec![],           vec!["x".into()]),
        ];
        let order = build_schedule(&nodes).unwrap();
        let names: Vec<&str> = order.iter().map(|e| e.kernel.as_str()).collect();
        let p = names.iter().position(|s| *s == "Producer").unwrap();
        let c = names.iter().position(|s| *s == "Consumer").unwrap();
        assert!(p < c);
    }
}
