//! Emits spatial kernel wrappers (grid build + per-query kernels).
//!
//! The hand-written body lives in engine_gpu::spatial_gpu — these
//! emitted modules wrap that code's BGL + dispatch shape. The WGSL
//! source for the existing hand-written path uses one fused module
//! with multiple entry points and a 12-binding layout; the emitted
//! kernels here carve out compact 4-/5-binding BGLs and fall back
//! to a no-op WGSL stub (xtask-side) until T16 unifies the WGSL.
//!
//! T12 also introduces the first Pooled-lifetime fields in
//! `BindingSources`: `spatial_grid_cells`, `spatial_grid_offsets`,
//! and `spatial_query_results` — the per-frame scratch buffers that
//! the spatial pipeline writes and consumes within a tick.

pub fn emit_spatial_hash_rs() -> String {
    common_kernel_body("SpatialHashKernel", "spatial_hash", &[
        ("agents", true), ("grid_cells", false), ("grid_offsets", false), ("sim_cfg", true),
    ])
}

pub fn emit_kin_query_rs() -> String {
    common_kernel_body("SpatialKinQueryKernel", "spatial_kin_query", &[
        ("agents", true), ("grid_cells", true), ("grid_offsets", true),
        ("query_results", false), ("sim_cfg", true),
    ])
}

pub fn emit_engagement_query_rs() -> String {
    common_kernel_body("SpatialEngagementQueryKernel", "spatial_engagement_query", &[
        ("agents", true), ("grid_cells", true), ("grid_offsets", true),
        ("query_results", false), ("sim_cfg", true),
    ])
}

pub fn emit_alive_pack_rs() -> String {
    common_kernel_body("AlivePackKernel", "alive_pack", &[
        ("agents", true), ("alive_bitmap", false),
    ])
}

pub fn emit_fused_agent_unpack_rs() -> String {
    common_kernel_body("FusedAgentUnpackKernel", "fused_agent_unpack", &[
        ("agents_input", true), ("mask_soa", false), ("agent_data", false),
    ])
}

#[allow(dead_code)]
fn common_kernel_body(struct_name: &str, file_stem: &str, bindings: &[(&str, bool)]) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler::emit_spatial_kernel. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use crate::binding_sources::BindingSources;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    writeln!(out, "    pipeline: wgpu::ComputePipeline,").unwrap();
    writeln!(out, "    bgl: wgpu::BindGroupLayout,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    let bindings_struct = format!("{struct_name}Bindings");
    writeln!(out, "pub struct {bindings_struct}<'a> {{").unwrap();
    for (name, _read_only) in bindings {
        writeln!(out, "    pub {name}: &'a wgpu::Buffer,").unwrap();
    }
    writeln!(out, "    pub cfg: &'a wgpu::Buffer,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    let cfg_struct = format!("{struct_name}Cfg");
    writeln!(out, "#[repr(C)]").unwrap();
    writeln!(out, "#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]").unwrap();
    writeln!(out, "pub struct {cfg_struct} {{ pub agent_cap: u32, pub radius_q: f32, pub _pad: [u32; 2] }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "const SHADER_SRC: &str = include_str!(\"{file_stem}.wgsl\");").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl crate::Kernel for {struct_name} {{").unwrap();
    writeln!(out, "    type Bindings<'a> = {bindings_struct}<'a>;").unwrap();
    writeln!(out, "    type Cfg = {cfg_struct};").unwrap();
    writeln!(out, "    fn new(device: &wgpu::Device) -> Self {{").unwrap();
    writeln!(out, "        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {{").unwrap();
    writeln!(out, "            label: Some(\"engine_gpu_rules::{file_stem}::wgsl\"),").unwrap();
    writeln!(out, "            source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {{").unwrap();
    writeln!(out, "            label: Some(\"engine_gpu_rules::{file_stem}::bgl\"),").unwrap();
    writeln!(out, "            entries: &[").unwrap();
    for (i, (_name, ro)) in bindings.iter().enumerate() {
        writeln!(out, "                crate::fused_mask::bgl_storage({i}, {ro}),").unwrap();
    }
    writeln!(out, "                crate::fused_mask::bgl_uniform({}),", bindings.len()).unwrap();
    writeln!(out, "            ],").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {{").unwrap();
    writeln!(out, "            label: Some(\"engine_gpu_rules::{file_stem}::pl\"),").unwrap();
    writeln!(out, "            bind_group_layouts: &[&bgl], push_constant_ranges: &[],").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {{").unwrap();
    writeln!(out, "            label: Some(\"engine_gpu_rules::{file_stem}::pipeline\"),").unwrap();
    writeln!(out, "            layout: Some(&pl), module: &shader, entry_point: Some(\"cs_{file_stem}\"),").unwrap();
    writeln!(out, "            compilation_options: Default::default(), cache: None,").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        Self {{ pipeline, bgl }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    fn build_cfg(&self, state: &engine::state::SimState) -> {cfg_struct} {{").unwrap();
    writeln!(out, "        {cfg_struct} {{ agent_cap: state.agent_cap(), radius_q: 12.0, _pad: [0; 2] }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> {bindings_struct}<'a> {{").unwrap();
    writeln!(out, "        {bindings_struct} {{").unwrap();
    for (name, _ro) in bindings {
        // Map well-known binding names to the right BindingSources field.
        // - `agents`, `sim_cfg`, `ability_registry`, `tag_values` -> external
        // - `grid_cells`, `grid_offsets`, `query_results`, `alive_bitmap` -> pool (or resident for alive_bitmap)
        // - `agents_input`, `mask_soa` -> transient
        // - `agent_data`, `event_ring`, etc. -> external/resident depending on kernel
        let expr = match *name {
            "agents" | "sim_cfg" | "agent_data" | "agents_input" | "mask_soa" => {
                // agents/agent_data/sim_cfg are external; mask_soa/agents_input are transient
                match *name {
                    "agents" | "agent_data" => "sources.external.agents",
                    "sim_cfg" => "sources.external.sim_cfg",
                    "agents_input" => "sources.transient.fused_agent_unpack_input",
                    "mask_soa" => "sources.transient.fused_agent_unpack_mask_soa",
                    _ => unreachable!(),
                }
            }
            "grid_cells" => "&sources.pool.spatial_grid_cells",
            "grid_offsets" => "&sources.pool.spatial_grid_offsets",
            "query_results" => "&sources.pool.spatial_query_results",
            "alive_bitmap" => "&sources.resident.alive_bitmap",
            _ => "/* unmapped binding - extend the spatial-kernel name lookup */ unimplemented!(\"name lookup\")",
        };
        writeln!(out, "            {name}: {expr},").unwrap();
    }
    writeln!(out, "            cfg,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &{bindings_struct}<'_>, agent_cap: u32) {{").unwrap();
    writeln!(out, "        let mut entries: Vec<wgpu::BindGroupEntry> = Vec::new();").unwrap();
    for (i, (name, _)) in bindings.iter().enumerate() {
        writeln!(out, "        entries.push(wgpu::BindGroupEntry {{ binding: {i}, resource: bindings.{name}.as_entire_binding() }});").unwrap();
    }
    writeln!(out, "        entries.push(wgpu::BindGroupEntry {{ binding: {}, resource: bindings.cfg.as_entire_binding() }});", bindings.len()).unwrap();
    writeln!(out, "        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {{").unwrap();
    writeln!(out, "            label: Some(\"engine_gpu_rules::{file_stem}::bg\"),").unwrap();
    writeln!(out, "            layout: &self.bgl,").unwrap();
    writeln!(out, "            entries: &entries,").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {{").unwrap();
    writeln!(out, "            label: Some(\"engine_gpu_rules::{file_stem}::pass\"),").unwrap();
    writeln!(out, "            timestamp_writes: None,").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        pass.set_pipeline(&self.pipeline);").unwrap();
    writeln!(out, "        pass.set_bind_group(0, &bg, &[]);").unwrap();
    writeln!(out, "        pass.dispatch_workgroups((agent_cap + 63) / 64, 1, 1);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    out
}
