//! Python emission for compiler milestone 2.
//!
//! `EventIR` → `@dataclass` in a per-event Python module, plus an aggregate
//! `__init__.py` that re-exports every dataclass. The emitted dataclasses are
//! a structural mirror of the Rust structs — same field names, same order,
//! best-effort type mapping. Python consumers use them to unpack trace rows.

use std::collections::BTreeSet;
use std::fmt::Write;

use crate::ir::{EventIR, IrType};

pub fn emit_event_dataclass(event: &EventIR, source_file: Option<&str>) -> String {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    writeln!(out, "from dataclasses import dataclass").unwrap();
    if uses_optional_or_list(event) {
        // No import needed — we use builtin `list[...]` and `T | None` syntax.
    }
    writeln!(out).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "@dataclass").unwrap();
    writeln!(out, "class {}:", event.name).unwrap();
    // Synthesize implicit tick on the emitted fields list.
    let mut fields = event.fields.clone();
    if !fields.iter().any(|f| f.name == "tick") {
        fields.push(crate::ir::EventField {
            name: "tick".into(),
            ty: IrType::U32,
            span: crate::ast::Span::dummy(),
        });
    }
    if fields.is_empty() {
        writeln!(out, "    pass").unwrap();
        return out;
    }
    for f in &fields {
        let (ty, comment) = render_py_type(&f.ty);
        match comment {
            Some(c) => writeln!(out, "    {}: {}  # {}", f.name, ty, c).unwrap(),
            None => writeln!(out, "    {}: {}", f.name, ty).unwrap(),
        }
    }
    out
}

pub fn emit_events_init(events: &[EventIR]) -> String {
    let mut sorted: Vec<&EventIR> = events.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    writeln!(out, "# GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(
        out,
        "# Regenerate with `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out).unwrap();
    for e in &sorted {
        writeln!(out, "from .{} import {}", snake_case(&e.name), e.name).unwrap();
    }
    writeln!(out).unwrap();
    let names: Vec<String> = sorted.iter().map(|e| format!("\"{}\"", e.name)).collect();
    writeln!(out, "__all__ = [{}]", names.join(", ")).unwrap();
    out
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(out, "# GENERATED by dsl_compiler from {}.", path).unwrap(),
        None => writeln!(out, "# GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "# Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "# Do not edit by hand.").unwrap();
    writeln!(out).unwrap();
}

/// Returns (type text, optional trailing comment).
fn render_py_type(ty: &IrType) -> (String, Option<String>) {
    match ty {
        IrType::Bool => ("bool".into(), None),
        IrType::I8
        | IrType::U8
        | IrType::I16
        | IrType::U16
        | IrType::I32
        | IrType::I64
        | IrType::U32
        | IrType::U64 => ("int".into(), None),
        IrType::F32 | IrType::F64 => ("float".into(), None),
        IrType::String => ("str".into(), None),
        IrType::Vec3 => (
            "tuple[float, float, float]".into(),
            None,
        ),
        IrType::AgentId => ("int".into(), Some("AgentId".into())),
        IrType::ItemId => ("int".into(), Some("ItemId".into())),
        IrType::GroupId => ("int".into(), Some("GroupId".into())),
        IrType::QuestId => ("int".into(), Some("QuestId".into())),
        IrType::AuctionId => ("int".into(), Some("AuctionId".into())),
        IrType::EventId => ("int".into(), Some("EventId".into())),
        IrType::AbilityId => ("int".into(), Some("AbilityId".into())),
        IrType::Array(inner, cap) => {
            let (inner_ty, _) = render_py_type(inner);
            (
                format!("tuple[{}, ...]", inner_ty),
                Some(format!("len={}", cap)),
            )
        }
        IrType::Optional(inner) => {
            let (inner_ty, comment) = render_py_type(inner);
            (format!("{} | None", inner_ty), comment)
        }
        IrType::Tuple(items) => {
            let parts: Vec<String> = items.iter().map(|t| render_py_type(t).0).collect();
            (format!("tuple[{}]", parts.join(", ")), None)
        }
        IrType::SortedVec(inner, cap) => {
            let (inner_ty, _) = render_py_type(inner);
            (format!("list[{}]", inner_ty), Some(format!("SortedVec cap={}", cap)))
        }
        IrType::RingBuffer(inner, cap) => {
            let (inner_ty, _) = render_py_type(inner);
            (
                format!("list[{}]", inner_ty),
                Some(format!("RingBuffer cap={}", cap)),
            )
        }
        IrType::SmallVec(inner, cap) => {
            let (inner_ty, _) = render_py_type(inner);
            (format!("list[{}]", inner_ty), Some(format!("SmallVec cap={}", cap)))
        }
        IrType::List(inner) => {
            let (inner_ty, _) = render_py_type(inner);
            (format!("list[{}]", inner_ty), None)
        }
        IrType::EntityRef(_) => ("int".into(), Some("EntityRef".into())),
        IrType::EventRef(_) => ("int".into(), Some("EventRef".into())),
        IrType::Enum { name, .. } => ("str".into(), Some(format!("enum {}", name))),
        IrType::Named(n) => ("object".into(), Some(n.clone())),
        IrType::Unknown => ("object".into(), Some("unknown".into())),
    }
}

fn uses_optional_or_list(event: &EventIR) -> bool {
    fn walk(ty: &IrType, seen: &mut BTreeSet<&'static str>) {
        match ty {
            IrType::Optional(inner) => {
                seen.insert("opt");
                walk(inner, seen);
            }
            IrType::List(inner)
            | IrType::SortedVec(inner, _)
            | IrType::RingBuffer(inner, _)
            | IrType::SmallVec(inner, _)
            | IrType::Array(inner, _) => {
                seen.insert("list");
                walk(inner, seen);
            }
            IrType::Tuple(items) => {
                for t in items {
                    walk(t, seen);
                }
            }
            _ => {}
        }
    }
    let mut seen = BTreeSet::new();
    for f in &event.fields {
        walk(&f.ty, &mut seen);
    }
    !seen.is_empty()
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::{EventField, EventIR, IrType};

    fn mk_field(name: &str, ty: IrType) -> EventField {
        EventField { name: name.into(), ty, span: Span::dummy() }
    }

    fn mk_event(name: &str, fields: Vec<EventField>) -> EventIR {
        EventIR {
            name: name.into(),
            fields,
            tags: vec![],
            annotations: vec![],
            span: Span::dummy(),
        }
    }

    #[test]
    fn simple_primitives() {
        let e = mk_event("Heal", vec![mk_field("amount", IrType::F32)]);
        let out = emit_event_dataclass(&e, None);
        assert!(out.contains("@dataclass"));
        assert!(out.contains("class Heal:"));
        assert!(out.contains("amount: float"));
        // Implicit tick.
        assert!(out.contains("tick: int"));
    }

    #[test]
    fn with_niche_id() {
        let e = mk_event(
            "Damage",
            vec![
                mk_field("target", IrType::AgentId),
                mk_field("amount", IrType::F32),
            ],
        );
        let out = emit_event_dataclass(&e, Some("assets/sim/events.sim"));
        assert!(out.contains("target: int  # AgentId"));
        assert!(out.contains("# GENERATED by dsl_compiler from assets/sim/events.sim."));
    }

    #[test]
    fn with_optional() {
        let e = mk_event(
            "MaybeHit",
            vec![mk_field("target", IrType::Optional(Box::new(IrType::AgentId)))],
        );
        let out = emit_event_dataclass(&e, None);
        assert!(out.contains("target: int | None  # AgentId"));
    }

    #[test]
    fn with_array() {
        let e = mk_event(
            "MultiHit",
            vec![mk_field("targets", IrType::Array(Box::new(IrType::AgentId), 4))],
        );
        let out = emit_event_dataclass(&e, None);
        assert!(out.contains("targets: tuple[int, ...]  # len=4"));
    }

    #[test]
    fn init_file_alphabetical() {
        let e1 = mk_event("Zebra", vec![mk_field("t", IrType::U32)]);
        let e2 = mk_event("Apple", vec![mk_field("t", IrType::U32)]);
        let out = emit_events_init(&[e1, e2]);
        let a = out.find("from .apple import Apple").unwrap();
        let z = out.find("from .zebra import Zebra").unwrap();
        assert!(a < z);
        assert!(out.contains("__all__ = [\"Apple\", \"Zebra\"]"));
    }
}
