//! Mask-predicate emission. Scaffolded at milestone-3-completion; filled
//! in at milestone 4.
//!
//! Emission target: `crates/engine/src/generated/mask/<name>.rs` (one file
//! per `mask` declaration). Mask predicates reference `engine::state::SimState`,
//! so they must live in the engine crate (same reason physics does; see
//! `docs/game/feature_flow.md`).
//!
//! Milestone 4 replaces the `todo!()` below with a real emitter. Until then,
//! `emit_mask_mod` produces a valid empty aggregator so the generated
//! directory compiles without any mask declarations in scope.

use crate::ir::MaskIR;

/// Emit the per-mask module body. Called once per `MaskIR`; result is
/// written to `<out>/<snake_case_head>.rs`.
pub fn emit_mask(_mask: &MaskIR, _source_file: Option<&str>) -> Result<String, String> {
    Err("mask emission not yet implemented (milestone 4)".into())
}

/// Emit `crates/engine/src/generated/mask/mod.rs`. The aggregator exposes
/// `pub fn register(...)` for the engine's mask-build path to call.
///
/// With zero masks in scope this returns a no-op aggregator so the module
/// compiles as soon as the scaffolding lands.
pub fn emit_mask_mod(masks: &[MaskIR]) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by dsl_compiler. Do not edit by hand.\n");
    out.push_str("// Regenerate with `cargo run --bin xtask -- compile-dsl`.\n");
    out.push_str("\n");
    if masks.is_empty() {
        out.push_str("// No `mask` declarations in scope yet (milestone 4 will fill\n");
        out.push_str("// this in). The engine's mask-build path calls `register()`\n");
        out.push_str("// unconditionally — keeping the signature stable lets the\n");
        out.push_str("// call site land before the first mask does.\n");
        out.push_str("\n");
        out.push_str("pub fn register() {}\n");
    } else {
        // Real path lands in milestone 4.
        out.push_str("// milestone 4: aggregate mask registration\n");
        out.push_str("pub fn register() {}\n");
    }
    out
}
