//! Entity emission (milestone 6).
//!
//! Every `entity` declaration of root `Agent` contributes one variant to the
//! aggregate `CreatureType` enum and one arm to `Capabilities::for_creature`.
//! Predator/prey lists (`preys_on` + `prey_of`) feed the symmetric closure
//! behind `CreatureType::is_hostile_to`.
//!
//! Emission target: `crates/engine_rules/src/entities/`. The aggregate
//! `mod.rs` carries the full `CreatureType` enum, the `Capabilities` struct,
//! `for_creature`, and `is_hostile_to` — all in one file, because every
//! Agent-root entity contributes to the same enum + impls and they would
//! just re-export each other otherwise. Per-entity stub files sit alongside
//! as named bookmarks; their body is a pointer comment.
//!
//! The engine consumes the emitted output the same way it consumes `Event`:
//! `engine::creature` becomes a re-export shim over `engine_rules::entities`.
//!
//! The emitter is deliberately mechanical — `writeln!` into a `String`, no
//! macros / traits. Reviewers should be able to skim the output without
//! tracing any abstractions back to the emitter.

use std::fmt::Write;

use crate::ast;
use crate::ir::{EntityFieldIR, EntityFieldValueIR, EntityIR, IrExpr, IrExprNode, IrType};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Emit one stub file per entity. The real `CreatureType` / `Capabilities`
/// content lives in the aggregate `mod.rs`; each per-entity file is a
/// header-only comment so `rustc` has something coherent to look at and the
/// xtask's `prune_stale` stays consistent with the other declaration kinds
/// (each kind emits one file per declaration plus an aggregator).
pub fn emit_entity(entity: &EntityIR, source_file: Option<&str>) -> Result<String, String> {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    writeln!(out).unwrap();
    writeln!(
        out,
        "// Entity `{}` — an Agent-root creature. The `CreatureType::{}`",
        entity.name, entity.name
    )
    .unwrap();
    writeln!(
        out,
        "// variant, per-variant `Capabilities::for_creature(...)` arm, and"
    )
    .unwrap();
    writeln!(
        out,
        "// hostility-matrix contribution live in this directory's `mod.rs`."
    )
    .unwrap();
    writeln!(out).unwrap();
    let snake = snake_case(&entity.name);
    writeln!(out, "// This file is intentionally near-empty — see `mod.rs`.").unwrap();
    writeln!(
        out,
        "#[allow(dead_code)]\npub(super) const __ENTITY_{}: &str = \"{}\";",
        snake.to_uppercase(),
        entity.name
    )
    .unwrap();
    Ok(out)
}

/// Emit the aggregate `entities/mod.rs`. Contains the full `CreatureType`
/// enum + impl and the `Capabilities` struct + `for_creature` — everything
/// the engine needs to compile against `engine_rules::entities`.
pub fn emit_entity_mod(entities: &[EntityIR]) -> String {
    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();

    let agents: Vec<&EntityIR> = entities
        .iter()
        .filter(|e| matches!(e.root, ast::EntityRoot::Agent))
        .collect();
    // EntityRef indices resolve against the order in `comp.entities` — mirror
    // it here so `IrExpr::Entity(EntityRef(i))` can round-trip to the source
    // name inside `prey_of: [Wolf, ...]` lists.
    let all_names: Vec<&str> = entities.iter().map(|e| e.name.as_str()).collect();

    // Per-entity stub modules (one per declaration, Agent-root or otherwise)
    // — pruned and rewritten on every compile. Non-agent roots still get a
    // stub so reviewers can grep entity names.
    if entities.is_empty() {
        writeln!(out, "// No `entity` declarations in scope yet.").unwrap();
        return out;
    }
    let mut sorted: Vec<&EntityIR> = entities.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    for e in &sorted {
        writeln!(out, "pub mod {};", snake_case(&e.name)).unwrap();
    }
    writeln!(out).unwrap();

    if agents.is_empty() {
        writeln!(
            out,
            "// No Agent-root entities declared — CreatureType + Capabilities omitted."
        )
        .unwrap();
        return out;
    }

    // Imports: ChannelSet / CommunicationChannel / LanguageId live in
    // `engine_rules::types`. SmallVec is the `languages` storage; the
    // `smallvec!` macro builds the per-variant literals.
    writeln!(
        out,
        "use crate::types::{{ChannelSet, CommunicationChannel, LanguageId}};"
    )
    .unwrap();
    writeln!(out, "use smallvec::{{smallvec, SmallVec}};").unwrap();
    writeln!(out).unwrap();

    emit_creature_type(&mut out, &agents, &all_names);
    writeln!(out).unwrap();
    emit_capabilities(&mut out, &agents, &all_names);

    out
}

// ---------------------------------------------------------------------------
// CreatureType emission
// ---------------------------------------------------------------------------

fn emit_creature_type(out: &mut String, agents: &[&EntityIR], all_names: &[&str]) {
    // Source-order discriminants. Reordering entities in the DSL source
    // reorders the discriminants; that's a schema bump because the wire
    // layout changes (state_hash covers entity field layouts at
    // milestone 6).
    writeln!(
        out,
        "#[derive(Copy, Clone, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]"
    )
    .unwrap();
    writeln!(out, "#[repr(u8)]").unwrap();
    writeln!(out, "pub enum CreatureType {{").unwrap();
    for (i, e) in agents.iter().enumerate() {
        if i == 0 {
            writeln!(out, "    #[default]").unwrap();
        }
        writeln!(out, "    {} = {},", e.name, i).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl CreatureType {{").unwrap();

    // `ALL` — dense list, declaration order.
    writeln!(out, "    pub const ALL: &'static [CreatureType] = &[").unwrap();
    for e in agents {
        writeln!(out, "        CreatureType::{},", e.name).unwrap();
    }
    writeln!(out, "    ];").unwrap();
    writeln!(out).unwrap();

    // `name()` — debug string matching the variant name.
    writeln!(out, "    pub fn name(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for e in agents {
        writeln!(
            out,
            "            CreatureType::{} => \"{}\",",
            e.name, e.name
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // `is_hostile_to` — dense `matches!` over the symmetric closure of each
    // entity's predator/prey lists. Self-hostility excluded. Always symmetric.
    let hostility_pairs = collect_hostility_pairs(agents, all_names);
    writeln!(
        out,
        "    /// Pairwise hostility predicate. Symmetric closure of the"
    )
    .unwrap();
    writeln!(
        out,
        "    /// `predator_prey.{{prey_of, preys_on}}` lists in `assets/sim/entities.sim`."
    )
    .unwrap();
    writeln!(out, "    pub fn is_hostile_to(self, other: CreatureType) -> bool {{").unwrap();
    if hostility_pairs.is_empty() {
        writeln!(out, "        let _ = other;").unwrap();
        writeln!(out, "        false").unwrap();
    } else {
        writeln!(out, "        matches!(").unwrap();
        writeln!(out, "            (self, other),").unwrap();
        // rustfmt formats or-patterns with leading `|` on continuation lines
        // — match that so emitted output survives `rustfmt` unchanged.
        for (i, (a, b)) in hostility_pairs.iter().enumerate() {
            if i == 0 {
                writeln!(
                    out,
                    "            (CreatureType::{}, CreatureType::{})",
                    a, b
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "                | (CreatureType::{}, CreatureType::{})",
                    a, b
                )
                .unwrap();
            }
        }
        writeln!(out, "        )").unwrap();
    }
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();
}

// ---------------------------------------------------------------------------
// Capabilities emission
// ---------------------------------------------------------------------------

fn emit_capabilities(out: &mut String, agents: &[&EntityIR], all_names: &[&str]) {
    // Struct definition. Field order matches the DSL declaration order in
    // the first entity's `capabilities` struct literal, falling back to the
    // canonical order from `dsl/spec.md` §2.1 if no entities define it.
    let cap_fields = capability_field_order(agents);
    writeln!(
        out,
        "/// Per-agent capability bundle — what the agent *can* do, structurally."
    )
    .unwrap();
    writeln!(out, "/// `dsl/spec.md` §2.1 is authoritative.").unwrap();
    writeln!(out, "#[derive(Clone, Debug)]").unwrap();
    writeln!(out, "pub struct Capabilities {{").unwrap();
    for f in &cap_fields {
        let ty = capability_field_type(f);
        writeln!(out, "    pub {}: {},", f, ty).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // `for_creature(ct)` — per-variant default builder.
    writeln!(out, "impl Capabilities {{").unwrap();
    writeln!(
        out,
        "    /// Spawn-time capability defaults for each creature type."
    )
    .unwrap();
    writeln!(out, "    pub fn for_creature(ct: CreatureType) -> Self {{").unwrap();
    writeln!(out, "        match ct {{").unwrap();
    for e in agents {
        let caps = find_capabilities_fields(e);
        writeln!(out, "            CreatureType::{} => Self {{", e.name).unwrap();
        for f in &cap_fields {
            let val = render_capability_value(f, caps.as_deref(), all_names);
            writeln!(out, "                {}: {},", f, val).unwrap();
        }
        writeln!(out, "            }},").unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(out, "// GENERATED by dsl_compiler from {}.", path).unwrap(),
        None => writeln!(out, "// GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "// Do not edit by hand.").unwrap();
}

/// Canonical capability field order — when no entity declares a
/// `capabilities: Capabilities { ... }` block we fall back to this shape.
/// Mirrors `dsl/spec.md` §2.1.
const CANONICAL_CAPABILITY_ORDER: &[&str] = &[
    "channels",
    "languages",
    "can_fly",
    "can_build",
    "can_trade",
    "can_climb",
    "can_tunnel",
    "can_marry",
    "max_spouses",
    // Task 177 — deer-herding flee bias. Falls through the generic
    // bool emitter arms in `capability_field_type` /
    // `render_capability_value`, so no type/render edits are needed
    // here; listing it in the canonical order lets the emitter keep
    // producing the field when an entity omits it (pre-177 test
    // fixtures that never set it take the `false` default).
    "herds_when_fleeing",
];

/// Pull the capability field order from the first entity that has a
/// `capabilities: Capabilities { ... }` block. If none do, return the
/// canonical order. The emitted struct's field order matches this — so
/// reordering fields in the DSL source reorders the struct layout.
fn capability_field_order(entities: &[&EntityIR]) -> Vec<String> {
    for e in entities {
        if let Some(fields) = find_capabilities_fields(e) {
            let names: Vec<String> = fields.iter().map(|f| f.name.clone()).collect();
            if !names.is_empty() {
                // Ensure `languages` is present — legacy engine wants it in
                // the struct even when entities only declared `channels`.
                // If missing, splice it in after `channels`.
                let mut out = names.clone();
                if !out.iter().any(|n| n == "languages") {
                    let insert_at = out
                        .iter()
                        .position(|n| n == "channels")
                        .map(|i| i + 1)
                        .unwrap_or(0);
                    out.insert(insert_at, "languages".to_string());
                }
                return out;
            }
        }
    }
    CANONICAL_CAPABILITY_ORDER
        .iter()
        .map(|s| s.to_string())
        .collect()
}

/// The Rust type for each known capability field. Fields the emitter
/// doesn't recognise default to `bool` — callers should flag any mismatch.
fn capability_field_type(field: &str) -> &'static str {
    match field {
        "channels" => "ChannelSet",
        "languages" => "SmallVec<[LanguageId; 4]>",
        "max_spouses" => "u8",
        // All remaining known capability fields are bools per spec §2.1.
        "can_fly" | "can_build" | "can_trade" | "can_climb" | "can_tunnel" | "can_marry" => "bool",
        _ => "bool",
    }
}

/// Look up the `capabilities` field on an entity. Returns the inner struct-
/// literal fields, or `None` if the entity has no `capabilities` block.
fn find_capabilities_fields(entity: &EntityIR) -> Option<Vec<EntityFieldIR>> {
    for f in &entity.fields {
        if f.name == "capabilities" {
            if let EntityFieldValueIR::StructLiteral { fields, .. } = &f.value {
                return Some(fields.clone());
            }
        }
    }
    None
}

/// Render one `CreatureType::X => Self { <field>: <val>, ... }` value for
/// the given capability field and the entity's capability block.
///
/// When the entity omits a field, we substitute a default (`false` / `0` /
/// empty). This matches the pre-milestone engine behaviour — fields not
/// mentioned in `Capabilities::for_creature(X)` kept their type defaults.
fn render_capability_value(
    field: &str,
    caps: Option<&[EntityFieldIR]>,
    all_names: &[&str],
) -> String {
    let value = caps.and_then(|fs| fs.iter().find(|f| f.name == field));
    match field {
        "channels" => render_channel_list(value, all_names),
        "languages" => render_language_list(value, all_names),
        "max_spouses" => render_int_value(value, "0"),
        "can_fly" | "can_build" | "can_trade" | "can_climb" | "can_tunnel" | "can_marry" => {
            render_bool_value(value, "false")
        }
        _ => render_bool_value(value, "false"),
    }
}

/// Render a `channels` list like `smallvec![CommunicationChannel::Speech,
/// CommunicationChannel::Testimony]`. Accepts either a bare single value
/// (`channels: PackSignal`) or a list (`channels: [Speech, Testimony]`).
/// Splits across multiple lines when the single-line form would exceed
/// rustfmt's 100-column width (measured relative to the `channels:` field
/// indent, which is 16 columns deep inside a `for_creature` match arm).
fn render_channel_list(value: Option<&EntityFieldIR>, all_names: &[&str]) -> String {
    let Some(field) = value else {
        return "SmallVec::new()".into();
    };
    let names = collect_variant_names(&field.value, all_names);
    if names.is_empty() {
        return "SmallVec::new()".into();
    }
    let parts: Vec<String> = names
        .iter()
        .map(|n| format!("CommunicationChannel::{}", n))
        .collect();
    render_smallvec_literal(&parts, /* field_indent */ 16, /* field_label_len */ "channels: ".len())
}

/// Render a `languages` list like `smallvec![LanguageId::COMMON]`.
fn render_language_list(value: Option<&EntityFieldIR>, all_names: &[&str]) -> String {
    let Some(field) = value else {
        return "SmallVec::new()".into();
    };
    let names = collect_variant_names(&field.value, all_names);
    if names.is_empty() {
        return "SmallVec::new()".into();
    }
    let parts: Vec<String> = names
        .iter()
        .map(|n| format!("LanguageId::{}", language_const(n)))
        .collect();
    render_smallvec_literal(&parts, 16, "languages: ".len())
}

/// Emit a `smallvec![...]` literal, preferring single-line but splitting
/// across lines with trailing-`,` when the single-line form would exceed
/// rustfmt's 100-column max-width.
fn render_smallvec_literal(parts: &[String], field_indent: usize, field_label_len: usize) -> String {
    let single = format!("smallvec![{}]", parts.join(", "));
    // Width of the whole field-line: `    {indent}name: {single},`.
    let line_len = field_indent + field_label_len + single.len() + 1 /* trailing comma */;
    // rustfmt's 100-column default; a conservative split at 99 keeps us
    // below rustfmt's "too wide" trigger.
    if line_len < 99 {
        return single;
    }
    let continuation = " ".repeat(field_indent + 4);
    let closer = " ".repeat(field_indent);
    let mut out = String::from("smallvec![\n");
    for p in parts {
        out.push_str(&continuation);
        out.push_str(p);
        out.push_str(",\n");
    }
    out.push_str(&closer);
    out.push(']');
    out
}

/// DSL `Common`, `Draconic`, ... → `LanguageId::COMMON`, `DRACONIC`, ... —
/// SHOUTY_SNAKE_CASE of the PascalCase source ident.
fn language_const(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 2);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            out.push(ch);
            prev_upper = true;
        } else {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            prev_upper = false;
        }
    }
    out
}

fn render_bool_value(value: Option<&EntityFieldIR>, default: &str) -> String {
    let Some(field) = value else {
        return default.into();
    };
    match &field.value {
        // The parser's type_ref path can consume `true` / `false` as type
        // names; detect and convert.
        EntityFieldValueIR::Type(IrType::Named(n)) if n == "true" || n == "false" => n.clone(),
        EntityFieldValueIR::Expr(e) => match &e.kind {
            IrExpr::LitBool(b) => if *b { "true" } else { "false" }.into(),
            _ => default.into(),
        },
        _ => default.into(),
    }
}

fn render_int_value(value: Option<&EntityFieldIR>, default: &str) -> String {
    let Some(field) = value else {
        return default.into();
    };
    match &field.value {
        EntityFieldValueIR::Expr(e) => match &e.kind {
            IrExpr::LitInt(v) => v.to_string(),
            _ => default.into(),
        },
        _ => default.into(),
    }
}

/// Pull out the PascalCase names of the variants in a field value. Accepts:
/// - A single bare type (`channels: PackSignal`) — one name.
/// - A list (`channels: [Speech, Testimony]`) — N names.
/// - Anything else — empty.
///
/// `entity_ref_names` maps `EntityRef` indices back to source names. It's
/// needed because `Wolf` inside `prey_of: [Wolf]` resolves to
/// `IrExpr::Entity(EntityRef(_))` whenever `Wolf` is a declared entity — the
/// resolver prefers that over `EnumVariant`. Pass `&[]` when no entity
/// context is available.
fn collect_variant_names(
    value: &EntityFieldValueIR,
    entity_ref_names: &[&str],
) -> Vec<String> {
    match value {
        EntityFieldValueIR::Type(IrType::Named(n)) => {
            // `channels: PackSignal` — bare type resolved as Named.
            vec![n.clone()]
        }
        EntityFieldValueIR::Type(IrType::EntityRef(r)) => {
            // `creature_type: Wolf` — Wolf is a declared entity.
            entity_ref_names
                .get(r.0 as usize)
                .map(|n| vec![(*n).to_string()])
                .unwrap_or_default()
        }
        EntityFieldValueIR::List(items) => items
            .iter()
            .filter_map(|e| expr_variant_name(e, entity_ref_names))
            .collect(),
        _ => Vec::new(),
    }
}

/// Extract a variant name from an expression node when possible. Covers
/// `EnumVariant` (uppercase idents that didn't resolve to a declared symbol)
/// and `Entity(EntityRef)` (the case where an entity name appears inside a
/// list, e.g. `preys_on: [Wolf]` where `Wolf` is a declared entity).
fn expr_variant_name(e: &IrExprNode, entity_ref_names: &[&str]) -> Option<String> {
    match &e.kind {
        IrExpr::EnumVariant { variant, .. } => Some(variant.clone()),
        IrExpr::Entity(r) => entity_ref_names
            .get(r.0 as usize)
            .map(|s| (*s).to_string()),
        _ => None,
    }
}

/// Walk every entity's `predator_prey` block and build the symmetric closure
/// of hostile `(CreatureType, CreatureType)` pairs.
///
/// `entity X { predator_prey: PredatorPrey { prey_of: [Y], preys_on: [Z] } }`
/// produces `(X,Y)`, `(Y,X)`, `(X,Z)`, `(Z,X)`. Self-pairs are excluded. The
/// output is deduplicated and sorted by the declaration order of the two
/// creatures; this keeps the emitted `matches!` arm order stable.
fn collect_hostility_pairs(agents: &[&EntityIR], all_names: &[&str]) -> Vec<(String, String)> {
    use std::collections::BTreeSet;

    // Order map: canonical declaration-order index per entity name.
    let order: std::collections::HashMap<&str, usize> = agents
        .iter()
        .enumerate()
        .map(|(i, e)| (e.name.as_str(), i))
        .collect();

    // Collected pairs, keyed on (idx_a, idx_b, name_a, name_b) so sorting is
    // purely by declaration order — ties broken by names for determinism.
    let mut pairs: BTreeSet<(usize, usize, String, String)> = BTreeSet::new();

    for entity in agents {
        let Some(pp) = find_predator_prey(entity) else {
            continue;
        };
        let pp_fields = match &pp.value {
            EntityFieldValueIR::StructLiteral { fields, .. } => fields,
            _ => continue,
        };
        for pp_field in pp_fields {
            let other_names = collect_variant_names(&pp_field.value, all_names);
            for other in &other_names {
                if other == &entity.name {
                    continue; // no self-hostility
                }
                // Skip unknown references — the emitted `matches!` arm needs
                // both creatures to exist in the CreatureType enum.
                if !order.contains_key(other.as_str()) {
                    continue;
                }
                insert_symmetric(&mut pairs, &order, &entity.name, other);
            }
        }
    }

    pairs
        .into_iter()
        .map(|(_, _, a, b)| (a, b))
        .collect()
}

fn insert_symmetric(
    out: &mut std::collections::BTreeSet<(usize, usize, String, String)>,
    order: &std::collections::HashMap<&str, usize>,
    a: &str,
    b: &str,
) {
    let ia = order[a];
    let ib = order[b];
    out.insert((ia, ib, a.to_string(), b.to_string()));
    out.insert((ib, ia, b.to_string(), a.to_string()));
}

fn find_predator_prey(entity: &EntityIR) -> Option<&EntityFieldIR> {
    entity.fields.iter().find(|f| f.name == "predator_prey")
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Schema hash input
// ---------------------------------------------------------------------------

/// A flattened `(entity_name, field_name, field_type_tag)` tuple that feeds
/// `schema_hash::state_hash`. Kept here because only the emitter knows how
/// to project the IR shape into a stable layout signature.
///
/// `field_type_tag` is a short ASCII description — `"bool"`, `"u8"`,
/// `"ChannelSet"`, `"SmallVec<LanguageId;4>"`, `"Named:<ident>"`, etc. The
/// state_hash folds these bytes verbatim; renaming a tag is a schema bump.
pub fn schema_hash_input(entities: &[EntityIR]) -> Vec<SchemaHashRow> {
    let mut rows: Vec<SchemaHashRow> = Vec::new();
    for e in entities {
        let root = match e.root {
            ast::EntityRoot::Agent => "Agent",
            ast::EntityRoot::Item => "Item",
            ast::EntityRoot::Group => "Group",
        };
        rows.push(SchemaHashRow {
            entity: e.name.clone(),
            root: root.to_string(),
            field: "_root".into(),
            tag: format!("root:{}", root),
        });
        for f in &e.fields {
            append_field_rows(&e.name, root, &f.name, &f.value, &mut rows);
        }
    }
    rows
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SchemaHashRow {
    pub entity: String,
    pub root: String,
    pub field: String,
    pub tag: String,
}

fn append_field_rows(
    entity: &str,
    root: &str,
    prefix: &str,
    value: &EntityFieldValueIR,
    rows: &mut Vec<SchemaHashRow>,
) {
    match value {
        EntityFieldValueIR::Type(t) => {
            rows.push(SchemaHashRow {
                entity: entity.into(),
                root: root.into(),
                field: prefix.into(),
                tag: type_tag(t),
            });
        }
        EntityFieldValueIR::StructLiteral { ty, fields } => {
            rows.push(SchemaHashRow {
                entity: entity.into(),
                root: root.into(),
                field: prefix.into(),
                tag: format!("struct:{}", type_tag(ty)),
            });
            for sub in fields {
                let sub_prefix = format!("{}.{}", prefix, sub.name);
                append_field_rows(entity, root, &sub_prefix, &sub.value, rows);
            }
        }
        EntityFieldValueIR::List(items) => {
            rows.push(SchemaHashRow {
                entity: entity.into(),
                root: root.into(),
                field: prefix.into(),
                tag: format!("list:{}", items.len()),
            });
        }
        EntityFieldValueIR::Expr(_) => {
            rows.push(SchemaHashRow {
                entity: entity.into(),
                root: root.into(),
                field: prefix.into(),
                tag: "expr".into(),
            });
        }
    }
}

fn type_tag(t: &IrType) -> String {
    match t {
        IrType::Bool => "bool".into(),
        IrType::I8 => "i8".into(),
        IrType::U8 => "u8".into(),
        IrType::I16 => "i16".into(),
        IrType::U16 => "u16".into(),
        IrType::I32 => "i32".into(),
        IrType::U32 => "u32".into(),
        IrType::I64 => "i64".into(),
        IrType::U64 => "u64".into(),
        IrType::F32 => "f32".into(),
        IrType::F64 => "f64".into(),
        IrType::Vec3 => "vec3".into(),
        IrType::String => "String".into(),
        IrType::AgentId => "AgentId".into(),
        IrType::ItemId => "ItemId".into(),
        IrType::GroupId => "GroupId".into(),
        IrType::QuestId => "QuestId".into(),
        IrType::AuctionId => "AuctionId".into(),
        IrType::EventId => "EventId".into(),
        IrType::AbilityId => "AbilityId".into(),
        IrType::Named(n) => format!("Named:{}", n),
        IrType::EntityRef(r) => format!("EntityRef:{}", r.0),
        IrType::EventRef(r) => format!("EventRef:{}", r.0),
        _ => format!("{:?}", t),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::{EntityFieldIR, EntityFieldValueIR, EntityIR, IrExpr, IrExprNode, IrType};

    fn mk_type_field(name: &str, ty: &str) -> EntityFieldIR {
        EntityFieldIR {
            name: name.into(),
            value: EntityFieldValueIR::Type(IrType::Named(ty.into())),
            annotations: vec![],
            span: Span::dummy(),
        }
    }

    fn mk_int_field(name: &str, v: i64) -> EntityFieldIR {
        EntityFieldIR {
            name: name.into(),
            value: EntityFieldValueIR::Expr(IrExprNode {
                kind: IrExpr::LitInt(v),
                span: Span::dummy(),
            }),
            annotations: vec![],
            span: Span::dummy(),
        }
    }

    fn mk_variant_list(name: &str, variants: &[&str]) -> EntityFieldIR {
        EntityFieldIR {
            name: name.into(),
            value: EntityFieldValueIR::List(
                variants
                    .iter()
                    .map(|v| IrExprNode {
                        kind: IrExpr::EnumVariant {
                            ty: String::new(),
                            variant: (*v).into(),
                        },
                        span: Span::dummy(),
                    })
                    .collect(),
            ),
            annotations: vec![],
            span: Span::dummy(),
        }
    }

    fn mk_struct_field(name: &str, ty: &str, fields: Vec<EntityFieldIR>) -> EntityFieldIR {
        EntityFieldIR {
            name: name.into(),
            value: EntityFieldValueIR::StructLiteral {
                ty: IrType::Named(ty.into()),
                fields,
            },
            annotations: vec![],
            span: Span::dummy(),
        }
    }

    fn mk_agent(name: &str, fields: Vec<EntityFieldIR>) -> EntityIR {
        EntityIR {
            name: name.into(),
            root: ast::EntityRoot::Agent,
            fields,
            annotations: vec![],
            span: Span::dummy(),
        }
    }

    #[test]
    fn creature_type_enum_lists_agent_entities_in_source_order() {
        let wolf = mk_agent("Wolf", vec![]);
        let deer = mk_agent("Deer", vec![]);
        let out = emit_entity_mod(&[wolf, deer]);
        assert!(out.contains("pub enum CreatureType {"));
        assert!(out.contains("#[default]"));
        // Source order preserves discriminants: Wolf=0 appears first, Deer=1 second.
        let wolf_pos = out.find("Wolf = 0").expect("Wolf = 0 present");
        let deer_pos = out.find("Deer = 1").expect("Deer = 1 present");
        assert!(wolf_pos < deer_pos);
        assert!(out.contains("pub const ALL: &'static [CreatureType] = &["));
        assert!(out.contains("CreatureType::Wolf,"));
        assert!(out.contains("CreatureType::Deer,"));
        assert!(out.contains("pub fn name(self) -> &'static str"));
    }

    #[test]
    fn hostility_matrix_is_symmetric_closure_of_predator_prey() {
        let wolf = mk_agent(
            "Wolf",
            vec![mk_struct_field(
                "predator_prey",
                "PredatorPrey",
                vec![mk_variant_list("preys_on", &["Deer"])],
            )],
        );
        let deer = mk_agent("Deer", vec![]);
        let out = emit_entity_mod(&[wolf, deer]);
        // Both directions emitted.
        assert!(out.contains("(CreatureType::Wolf, CreatureType::Deer)"));
        assert!(out.contains("(CreatureType::Deer, CreatureType::Wolf)"));
    }

    #[test]
    fn hostility_matrix_accepts_entity_refs_in_lists() {
        // `preys_on: [Deer]` — where `Deer` is also a declared entity —
        // lowers to `IrExpr::Entity(EntityRef(...))`, not `EnumVariant`.
        // The emitter must still route that to the right creature name.
        let wolf = mk_agent(
            "Wolf",
            vec![EntityFieldIR {
                name: "predator_prey".into(),
                value: EntityFieldValueIR::StructLiteral {
                    ty: IrType::Named("PredatorPrey".into()),
                    fields: vec![EntityFieldIR {
                        name: "preys_on".into(),
                        value: EntityFieldValueIR::List(vec![IrExprNode {
                            kind: IrExpr::Entity(crate::ir::EntityRef(1)),
                            span: Span::dummy(),
                        }]),
                        annotations: vec![],
                        span: Span::dummy(),
                    }],
                },
                annotations: vec![],
                span: Span::dummy(),
            }],
        );
        let deer = mk_agent("Deer", vec![]);
        let out = emit_entity_mod(&[wolf, deer]);
        assert!(out.contains("(CreatureType::Wolf, CreatureType::Deer)"));
        assert!(out.contains("(CreatureType::Deer, CreatureType::Wolf)"));
    }

    #[test]
    fn capabilities_for_creature_emits_per_variant_defaults() {
        let wolf = mk_agent(
            "Wolf",
            vec![mk_struct_field(
                "capabilities",
                "Capabilities",
                vec![
                    mk_variant_list("channels", &["PackSignal"]),
                    mk_variant_list("languages", &[]),
                    mk_type_field("can_fly", "false"),
                    mk_type_field("can_build", "false"),
                    mk_type_field("can_trade", "false"),
                    mk_type_field("can_climb", "false"),
                    mk_type_field("can_tunnel", "true"),
                    mk_type_field("can_marry", "false"),
                    mk_int_field("max_spouses", 0),
                ],
            )],
        );
        let out = emit_entity_mod(&[wolf]);
        assert!(out.contains("pub struct Capabilities"));
        assert!(out.contains("pub channels: ChannelSet"));
        assert!(out.contains("pub languages: SmallVec<[LanguageId; 4]>"));
        assert!(out.contains("pub max_spouses: u8"));
        assert!(out.contains("pub fn for_creature(ct: CreatureType) -> Self"));
        assert!(out.contains("CreatureType::Wolf => Self {"));
        assert!(out.contains("channels: smallvec![CommunicationChannel::PackSignal]"));
        assert!(out.contains("can_tunnel: true"));
        assert!(out.contains("max_spouses: 0"));
    }

    #[test]
    fn empty_entity_list_produces_stub_mod() {
        let out = emit_entity_mod(&[]);
        assert!(out.contains("GENERATED by dsl_compiler"));
        assert!(out.contains("No `entity` declarations"));
    }

    #[test]
    fn per_entity_stub_is_a_header_comment() {
        let wolf = mk_agent("Wolf", vec![]);
        let stub = emit_entity(&wolf, Some("assets/sim/entities.sim")).unwrap();
        assert!(stub.contains("Entity `Wolf`"));
        assert!(stub.contains("GENERATED by dsl_compiler from assets/sim/entities.sim"));
        assert!(stub.contains("see `mod.rs`"));
    }

    #[test]
    fn language_const_shouty_snake() {
        assert_eq!(language_const("Common"), "COMMON");
        assert_eq!(language_const("Draconic"), "DRACONIC");
        assert_eq!(language_const("PigLatin"), "PIG_LATIN");
    }

    #[test]
    fn schema_hash_input_collects_entity_rows() {
        let wolf = mk_agent(
            "Wolf",
            vec![
                mk_type_field("creature_type", "Wolf"),
                mk_struct_field(
                    "capabilities",
                    "Capabilities",
                    vec![mk_int_field("max_spouses", 0)],
                ),
            ],
        );
        let rows = schema_hash_input(&[wolf]);
        assert!(rows.iter().any(|r| r.entity == "Wolf" && r.field == "_root"));
        assert!(
            rows.iter().any(|r| r.field == "capabilities.max_spouses" && r.tag == "expr"),
            "nested struct fields flattened via `.` paths"
        );
    }
}
