//! Emission of `engine_rules/src/mask_fill.rs` — the `fill_all` function that
//! populates the `MaskBuffer` and `TargetMask` for every alive agent.
//!
//! The emitted function is derived from the `mask` declarations in the IR:
//!   - Self-only masks (no positional args) produce a `buf.set(slot, Kind, true)` call.
//!   - Target-bound masks (with a `from <source>` clause) produce a candidate-
//!     enumerator call (`mask_<name>_candidates`) followed by a check on whether
//!     any candidates were pushed.
//!
//! The Cast mask is special — it takes an `ability: AbilityId` argument. The
//! emitter generates a per-ability loop over the registry that sets the Cast bit
//! if any ability passes the gate.

use std::fmt::Write;

use crate::ir::{IrActionHeadShape, MaskIR};

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

/// Emit `engine_rules/src/mask_fill.rs` from the mask IR.
pub fn emit_mask_fill(masks: &[MaskIR], source_file: Option<&str>) -> String {
    let mut out = String::new();
    emit_header(&mut out, source_file);

    writeln!(out, "use engine::ability::AbilityId;").unwrap();
    writeln!(out, "use engine::mask::{{MaskBuffer, MicroKind, TargetMask}};").unwrap();
    writeln!(out, "use engine::state::SimState;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// Fill every mask bit and target-mask candidate list for the current tick.").unwrap();
    writeln!(out, "/// Resets `buf` and `targets` before populating.").unwrap();
    writeln!(out, "pub fn fill_all(buf: &mut MaskBuffer, targets: &mut TargetMask, state: &SimState) {{").unwrap();
    writeln!(out, "    buf.reset();").unwrap();
    writeln!(out, "    targets.reset();").unwrap();
    writeln!(out, "    for id in state.agents_alive() {{").unwrap();
    writeln!(out, "        let slot = (id.raw() - 1) as usize;").unwrap();

    // Emit a call for each mask declaration.
    for mask in masks {
        let stem = snake_case(&mask.head.name);
        match &mask.head.shape {
            IrActionHeadShape::None => {
                // Self-only mask — one bool call.
                emit_self_only_mask(&mut out, &mask.head.name, &stem);
            }
            IrActionHeadShape::Positional(params) => {
                if params.is_empty() {
                    // Treated as self-only.
                    emit_self_only_mask(&mut out, &mask.head.name, &stem);
                } else {
                    // Check if it's the special Cast mask (has a non-AgentId param).
                    let is_cast = params.iter().any(|(n, _, _)| n == "ability");
                    if is_cast {
                        emit_cast_mask(&mut out);
                    } else if mask.candidate_source.is_some() {
                        // Target-bound mask with candidate enumerator.
                        emit_target_bound_mask(&mut out, &mask.head.name, &stem);
                    } else {
                        // Per-target predicate without enumerator — treat as self-only gate.
                        emit_self_only_mask(&mut out, &mask.head.name, &stem);
                    }
                }
            }
            IrActionHeadShape::Named(_) => {
                // Named params are rare; fall back to self-only.
                emit_self_only_mask(&mut out, &mask.head.name, &stem);
            }
        }
    }

    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    out
}

fn emit_header(out: &mut String, source_file: Option<&str>) {
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    if let Some(s) = source_file {
        writeln!(out, "// Source: {s}").unwrap();
    }
    writeln!(out).unwrap();
}

fn micro_kind_from_name(name: &str) -> Option<&'static str> {
    match name {
        "Hold"       => Some("MicroKind::Hold"),
        "MoveToward" => Some("MicroKind::MoveToward"),
        "Flee"       => Some("MicroKind::Flee"),
        "Attack"     => Some("MicroKind::Attack"),
        "Cast"       => Some("MicroKind::Cast"),
        "UseItem"    => Some("MicroKind::UseItem"),
        "Eat"        => Some("MicroKind::Eat"),
        "Drink"      => Some("MicroKind::Drink"),
        "Rest"       => Some("MicroKind::Rest"),
        _            => None,
    }
}

fn emit_self_only_mask(out: &mut String, name: &str, stem: &str) {
    if let Some(kind) = micro_kind_from_name(name) {
        writeln!(out, "        if crate::mask::mask_{stem}(state, id) {{").unwrap();
        writeln!(out, "            buf.set(slot, {kind}, true);").unwrap();
        writeln!(out, "        }}").unwrap();
    }
}

fn emit_cast_mask(out: &mut String) {
    writeln!(out, "        // Cast mask — per-ability gate; set if ANY ability passes.").unwrap();
    writeln!(out, "        let n_abilities = state.ability_registry.len();").unwrap();
    writeln!(out, "        if n_abilities == 0 {{").unwrap();
    writeln!(out, "            buf.set(slot, MicroKind::Cast, true);").unwrap();
    writeln!(out, "        }} else {{").unwrap();
    writeln!(out, "            'cast_gate: for raw in 1..=(n_abilities as u32) {{").unwrap();
    writeln!(out, "                if let Some(ability_id) = AbilityId::new(raw) {{").unwrap();
    writeln!(out, "                    if crate::mask::mask_cast(state, id, ability_id) {{").unwrap();
    writeln!(out, "                        buf.set(slot, MicroKind::Cast, true);").unwrap();
    writeln!(out, "                        break 'cast_gate;").unwrap();
    writeln!(out, "                    }}").unwrap();
    writeln!(out, "                }}").unwrap();
    writeln!(out, "            }}").unwrap();
    writeln!(out, "        }}").unwrap();
}

fn emit_target_bound_mask(out: &mut String, name: &str, stem: &str) {
    if let Some(kind) = micro_kind_from_name(name) {
        writeln!(out, "        crate::mask::mask_{stem}_candidates(state, id, targets);").unwrap();
        writeln!(out, "        if !targets.candidates_for(id, {kind}).is_empty() {{").unwrap();
        writeln!(out, "            buf.set(slot, {kind}, true);").unwrap();
        writeln!(out, "        }}").unwrap();
    }
}
