//! Emission of `engine_rules/src/step.rs` — the canonical serial tick pipeline.
//!
//! The emitted `step` function runs the 6-phase tick loop:
//!   1. mask build (`mask_fill::fill_all`)
//!   2. policy evaluate (`backend.evaluate`)
//!   3. deterministic action shuffle (Fisher-Yates)
//!   4. apply actions + cascade fixed-point
//!   5. view fold (`views.fold_all`)
//!   6. tick advance (`state.tick += 1`)
//!
//! Unlike the physics / mask / view emitters this module emits a single
//! file that is almost entirely static — the step body doesn't vary with
//! the DSL rule set. It is kept as a compiler-owned emission (rather than
//! a hand-written stub in `engine_rules/src/step.rs`) so that future
//! DSL-driven phases (e.g. invariant checks wired from `invariant`
//! declarations) can grow into it without a separate authoring surface.

use std::fmt::Write;

/// Emit `engine_rules/src/step.rs`.
///
/// `source_file` is the DSL source path stamped into the file header when
/// a single `.sim` file contributed the relevant rule set; `None` falls
/// back to a generic header.
pub fn emit_step(source_file: Option<&str>) -> String {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    writeln!(out, "use engine::cascade::CascadeRegistry;").unwrap();
    writeln!(out, "use engine::event::EventRing;").unwrap();
    writeln!(out, "use engine::ids::AgentId;").unwrap();
    writeln!(out, "use engine::policy::{{Action, ActionKind, AnnounceAudience, MacroAction, MicroTarget, PolicyBackend}};").unwrap();
    writeln!(out, "use engine::rng::per_agent_u32;").unwrap();
    writeln!(out, "use engine::scratch::SimScratch;").unwrap();
    writeln!(out, "use engine::state::SimState;").unwrap();
    writeln!(out, "use engine_data::events::Event;").unwrap();
    writeln!(out, "use engine_data::entities::Capabilities;").unwrap();
    writeln!(out, "use crate::views::ViewRegistry;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// Canonical Serial tick step (6-phase pipeline).").unwrap();
    writeln!(out, "pub fn step<B: PolicyBackend>(").unwrap();
    writeln!(out, "    state:   &mut SimState,").unwrap();
    writeln!(out, "    scratch: &mut SimScratch,").unwrap();
    writeln!(out, "    events:  &mut EventRing<Event>,").unwrap();
    writeln!(out, "    views:   &mut ViewRegistry,").unwrap();
    writeln!(out, "    policy:  &B,").unwrap();
    writeln!(out, "    cascade: &CascadeRegistry<Event, ViewRegistry>,").unwrap();
    writeln!(out, ") {{").unwrap();
    writeln!(out, "    crate::mask_fill::fill_all(&mut scratch.mask, &mut scratch.target_mask, state);").unwrap();
    writeln!(out, "    scratch.actions.clear();").unwrap();
    writeln!(out, "    policy.evaluate(state, &scratch.mask, &scratch.target_mask, &mut scratch.actions);").unwrap();
    writeln!(out, "    shuffle_actions_in_place(state.seed, state.tick, &scratch.actions, &mut scratch.shuffle_idx);").unwrap();
    writeln!(out, "    let events_before = events.total_pushed();").unwrap();
    writeln!(out, "    apply_actions(state, scratch, events);").unwrap();
    writeln!(out, "    cascade.run_fixed_point(state, views, events);").unwrap();
    writeln!(out, "    views.fold_all(events, events_before, state.tick);").unwrap();
    writeln!(out, "    state.tick = state.tick.wrapping_add(1);").unwrap();
    writeln!(out, "}}").unwrap();
    out
}

fn emit_header(out: &mut String, source_file: Option<&str>) {
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    if let Some(s) = source_file {
        writeln!(out, "// Source: {s}").unwrap();
    }
    writeln!(out).unwrap();
}
