//! View emission — Rust emission for `@lazy` + `@materialized` views.
//!
//! Two emission paths per spec §2.3:
//!
//! - `@lazy` view: a pure `pub fn <name>(state: &SimState, <args>) -> T`
//!   whose body is the mechanically-lowered expression body. Called
//!   through `crate::generated::views::<name>(state, args...)` from masks,
//!   scoring, physics, and other views.
//!
//! - `@materialized` view: a `#[derive(Debug, Default)] pub struct <Name>`
//!   that owns the fold storage (per §9 D31 storage hint) plus a
//!   `get(args..., tick: u32) -> T` and `fold_event(&mut self, event: &Event,
//!   tick: u32)` method pair. The engine registers one instance per
//!   materialized view on `SimState.views` and calls `fold_all(&events,
//!   tick)` at the view-fold phase of the tick pipeline.
//!
//! `@decay(rate=R, per=tick)` on a materialized view is sugar for the
//! anchor-pattern storage layout: the stored value is `(base_at_anchor,
//! anchor_tick)` and the observable at tick `t` is `base * rate^(t -
//! anchor)`, clamped. Event handlers fold the event's delta into a new
//! base and advance the anchor to the current tick. Spec §2.3 `@decay`.
//!
//! The emitter is intentionally verbose — `writeln!` into a `String`, no
//! macros, no helper traits beyond a small expression lowerer. Reviewers
//! should be able to skim the emitted output without tracing abstractions.

use std::fmt::Write;

use crate::ast::{BinOp, UnOp};
use crate::ir::{
    Builtin, DecayUnit, FoldHandlerIR, IrCallArg, IrExpr, IrExprNode, IrType, NamespaceId,
    StorageHint, ViewBodyIR, ViewIR, ViewKind,
};

/// Errors the view emitter can raise.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    /// Something in the IR shape doesn't match what the emitter can produce.
    /// Carries a short diagnostic.
    Unsupported(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::Unsupported(s) => write!(f, "view emission: {s}"),
        }
    }
}

impl std::error::Error for EmitError {}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/// Emit a single view module file (`views/<snake_case>.rs`). Called once
/// per `ViewIR`; the result is written to the engine's generated `views/`
/// directory.
///
/// Returns `Err(String)` (not `EmitError`) so the xtask call site stays
/// symmetric with `emit_mask` / `emit_scoring` / `emit_entity`.
pub fn emit_view(view: &ViewIR, source_file: Option<&str>) -> Result<String, String> {
    emit_view_result(view, source_file).map_err(|e| e.to_string())
}

fn emit_view_result(view: &ViewIR, source_file: Option<&str>) -> Result<String, EmitError> {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    match view.kind {
        ViewKind::Lazy => {
            emit_imports_lazy(&mut out);
            emit_lazy_fn(&mut out, view)?;
        }
        ViewKind::Materialized(hint) => {
            emit_imports_materialized(&mut out);
            emit_materialized_struct(&mut out, view, hint)?;
        }
    }
    Ok(out)
}

/// Emit the aggregate `views/mod.rs`. The aggregator re-exports each
/// `@lazy` view's fn and bundles every `@materialized` view's struct into
/// a single `ViewRegistry` wrapper. The engine constructs one instance
/// per `SimState` and calls `fold_all(&events, tick)` at the view-fold
/// phase of the tick pipeline.
pub fn emit_view_mod(views: &[ViewIR]) -> String {
    let mut sorted: Vec<&ViewIR> = views.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();

    if sorted.is_empty() {
        writeln!(out, "// No `view` declarations in scope. Empty registry.").unwrap();
        writeln!(out).unwrap();
        writeln!(
            out,
            "/// Compiler-emitted view registry — one field per `@materialized` view."
        )
        .unwrap();
        writeln!(out, "/// Empty while no views are declared.").unwrap();
        writeln!(out, "#[derive(Debug, Default)]").unwrap();
        writeln!(out, "pub struct ViewRegistry {{}}").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "impl ViewRegistry {{").unwrap();
        writeln!(out, "    pub fn new() -> Self {{ Self::default() }}").unwrap();
        writeln!(
            out,
            "    /// Fold every materialized view over the current tick's events."
        )
        .unwrap();
        writeln!(
            out,
            "    pub fn fold_all(&mut self, _events: &crate::event::EventRing, _tick: u32) {{}}"
        )
        .unwrap();
        writeln!(out, "}}").unwrap();
        return out;
    }

    // Per-view submodule declarations.
    for v in &sorted {
        writeln!(out, "pub mod {};", snake_case(&v.name)).unwrap();
    }
    writeln!(out).unwrap();

    // Re-export lazy view fns at the module root — the resolver emits
    // calls as `crate::generated::views::<name>(state, args...)`.
    for v in &sorted {
        if matches!(v.kind, ViewKind::Lazy) {
            let stem = snake_case(&v.name);
            writeln!(out, "pub use {stem}::{stem};").unwrap();
        }
    }
    // Re-export materialized view structs for external visibility.
    for v in &sorted {
        if matches!(v.kind, ViewKind::Materialized(_)) {
            let stem = snake_case(&v.name);
            let ty = pascal_case(&v.name);
            writeln!(out, "pub use {stem}::{ty};").unwrap();
        }
    }
    writeln!(out).unwrap();

    let materialized: Vec<&&ViewIR> = sorted
        .iter()
        .filter(|v| matches!(v.kind, ViewKind::Materialized(_)))
        .collect();

    writeln!(out, "/// Compiler-emitted view registry — one field per `@materialized` view.").unwrap();
    writeln!(out, "/// `SimState` owns one of these; the tick pipeline calls `fold_all` at").unwrap();
    writeln!(out, "/// the view-fold phase (spec §7.1).").unwrap();
    writeln!(out, "#[derive(Debug, Default)]").unwrap();
    writeln!(out, "pub struct ViewRegistry {{").unwrap();
    for v in &materialized {
        let field = snake_case(&v.name);
        let ty = pascal_case(&v.name);
        writeln!(out, "    pub {field}: {field}::{ty},").unwrap();
    }
    if materialized.is_empty() {
        writeln!(out, "    // No `@materialized` views in scope.").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl ViewRegistry {{").unwrap();
    writeln!(out, "    pub fn new() -> Self {{ Self::default() }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    /// Fold every materialized view over the current tick's events.").unwrap();
    writeln!(out, "    /// Called from `step_full` at the view-fold phase.").unwrap();
    writeln!(out, "    pub fn fold_all(&mut self, events: &crate::event::EventRing, tick: u32) {{").unwrap();
    if materialized.is_empty() {
        writeln!(out, "        let _ = (events, tick);").unwrap();
    } else {
        writeln!(out, "        for e in events.iter() {{").unwrap();
        for v in &materialized {
            let field = snake_case(&v.name);
            writeln!(out, "            self.{field}.fold_event(e, tick);").unwrap();
        }
        writeln!(out, "        }}").unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    out
}

// ---------------------------------------------------------------------------
// Header + imports
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(out, "// GENERATED by dsl_compiler from {}.", path).unwrap(),
        None => writeln!(out, "// GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "// Do not edit by hand.").unwrap();
    writeln!(out).unwrap();
}

fn emit_imports_lazy(out: &mut String) {
    writeln!(out, "use crate::ids::AgentId;").unwrap();
    writeln!(out, "use crate::state::SimState;").unwrap();
    writeln!(out).unwrap();
}

fn emit_imports_materialized(out: &mut String) {
    writeln!(out, "use std::collections::HashMap;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use crate::event::Event;").unwrap();
    writeln!(out, "use crate::ids::AgentId;").unwrap();
    writeln!(out).unwrap();
}

// ---------------------------------------------------------------------------
// @lazy view fn emission
// ---------------------------------------------------------------------------

fn emit_lazy_fn(out: &mut String, view: &ViewIR) -> Result<(), EmitError> {
    let body = match &view.body {
        ViewBodyIR::Expr(e) => e,
        ViewBodyIR::Fold { .. } => {
            return Err(EmitError::Unsupported(format!(
                "`@lazy` view `{}` has a fold body — resolver should have rejected this",
                view.name
            )));
        }
    };

    let fn_name = snake_case(&view.name);
    let ret_ty = rust_type_for(&view.return_ty)?;
    let mut params = vec!["state: &SimState".to_string()];
    for p in &view.params {
        let ty = rust_type_for(&p.ty)?;
        params.push(format!("{}: {ty}", p.name));
    }

    writeln!(
        out,
        "/// @lazy view — lowered from `view {}(...)` in the sim DSL.",
        view.name
    )
    .unwrap();
    writeln!(
        out,
        "/// Pure expression body; re-evaluated on each call. Spec §2.3."
    )
    .unwrap();
    writeln!(
        out,
        "pub fn {fn_name}({}) -> {ret_ty} {{",
        params.join(", ")
    )
    .unwrap();
    let lowered = lower_expr(body)?;
    writeln!(out, "    {lowered}").unwrap();
    writeln!(out, "}}").unwrap();
    // `state` may be unused by a degenerate body (e.g. a literal); suppress
    // the would-be warning once per fn via `let _ = state;` below if so.
    // Instead of tracking referential use here, rely on the emitter's call
    // conventions: every stdlib-namespace and unresolved call emits
    // `state.*` / `crate::rules::*(state, ...)`, so real-world bodies
    // touch `state`. A trivial literal body is a smell worth surfacing.
    Ok(())
}

// ---------------------------------------------------------------------------
// @materialized view emission
// ---------------------------------------------------------------------------

fn emit_materialized_struct(
    out: &mut String,
    view: &ViewIR,
    storage: StorageHint,
) -> Result<(), EmitError> {
    let (initial, handlers, clamp) = match &view.body {
        ViewBodyIR::Fold { initial, handlers, clamp } => (initial, handlers, clamp.as_ref()),
        ViewBodyIR::Expr(_) => {
            return Err(EmitError::Unsupported(format!(
                "`@materialized` view `{}` has a non-fold body — resolver should have caught this",
                view.name
            )));
        }
    };

    match storage {
        StorageHint::PairMap => {
            emit_pair_map_struct(out, view, initial, handlers, clamp, view.decay.as_ref())
        }
        StorageHint::PerEntityTopK { .. } => Err(EmitError::Unsupported(format!(
            "`per_entity_topk` storage hint on view `{}` is not implemented yet (spec §9 D31)",
            view.name
        ))),
        StorageHint::LazyCached => Err(EmitError::Unsupported(format!(
            "`lazy_cached` storage hint on view `{}` is not implemented yet (spec §9 D31)",
            view.name
        ))),
    }
}

/// Emit the pair-map shape. Keys are built from the view's two params
/// (enforced shape check); values are the view's return type. `@decay`
/// switches the storage to the anchor-pattern `(base, anchor_tick)`
/// 2-tuple and the getter computes `base * rate^(tick - anchor)` with the
/// clamp applied.
fn emit_pair_map_struct(
    out: &mut String,
    view: &ViewIR,
    initial: &IrExprNode,
    handlers: &[FoldHandlerIR],
    clamp: Option<&(IrExprNode, IrExprNode)>,
    decay: Option<&crate::ir::DecayHint>,
) -> Result<(), EmitError> {
    if view.params.len() != 2 {
        return Err(EmitError::Unsupported(format!(
            "`pair_map` storage on view `{}` requires exactly 2 params; got {}",
            view.name,
            view.params.len()
        )));
    }
    let val_ty = rust_type_for(&view.return_ty)?;
    let k1 = rust_type_for(&view.params[0].ty)?;
    let k2 = rust_type_for(&view.params[1].ty)?;
    let a_name = view.params[0].name.as_str();
    let b_name = view.params[1].name.as_str();
    let ty_name = pascal_case(&view.name);

    writeln!(
        out,
        "/// @materialized view `{}` — `storage = pair_map<({k1}, {k2}), {val_ty}>`.",
        view.name
    )
    .unwrap();
    if let Some(d) = decay {
        let per = match d.per {
            DecayUnit::Tick => "tick",
        };
        writeln!(
            out,
            "/// @decay(rate = {}, per = {per}) — anchor-pattern storage. Spec §2.3.",
            d.rate
        )
        .unwrap();
    }
    writeln!(out, "#[derive(Debug, Default)]").unwrap();
    writeln!(out, "pub struct {ty_name} {{").unwrap();
    if decay.is_some() {
        writeln!(
            out,
            "    /// `(base_at_anchor, anchor_tick)` per-pair. Observable value at `tick`",
        )
        .unwrap();
        writeln!(out, "    /// is `base * rate.powi((tick - anchor) as i32)` clamped.").unwrap();
        writeln!(out, "    value: HashMap<({k1}, {k2}), ({val_ty}, u32)>,").unwrap();
    } else {
        writeln!(out, "    value: HashMap<({k1}, {k2}), {val_ty}>,").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl {ty_name} {{").unwrap();
    if let Some(d) = decay {
        writeln!(
            out,
            "    /// Decay rate per tick — compile-time constant from `@decay(rate = {})`.",
            d.rate
        )
        .unwrap();
        writeln!(
            out,
            "    pub const RATE: {val_ty} = {}_f32;",
            format_f32_lit(d.rate)
        )
        .unwrap();
        writeln!(out).unwrap();
    }
    writeln!(out, "    pub fn new() -> Self {{ Self::default() }}").unwrap();
    writeln!(out).unwrap();

    // `len()` + `contains` are handy for tests and don't add surface area.
    writeln!(out, "    pub fn len(&self) -> usize {{ self.value.len() }}").unwrap();
    writeln!(
        out,
        "    pub fn is_empty(&self) -> bool {{ self.value.is_empty() }}"
    )
    .unwrap();
    writeln!(out).unwrap();

    // get() signature depends on whether @decay is present (needs tick).
    let initial_lit = lower_scalar_literal(initial)?;
    if decay.is_some() {
        writeln!(
            out,
            "    /// Current value at `tick`, decayed from the anchor."
        )
        .unwrap();
        writeln!(
            out,
            "    pub fn get(&self, {a_name}: {k1}, {b_name}: {k2}, tick: u32) -> {val_ty} {{"
        )
        .unwrap();
        writeln!(
            out,
            "        let (base, anchor) = self.value.get(&({a_name}, {b_name})).copied()"
        )
        .unwrap();
        writeln!(out, "            .unwrap_or(({initial_lit}, tick));").unwrap();
        writeln!(
            out,
            "        let decayed = base * Self::RATE.powi(tick.saturating_sub(anchor) as i32);"
        )
        .unwrap();
        if let Some((lo, hi)) = clamp {
            let lo_s = lower_scalar_literal(lo)?;
            let hi_s = lower_scalar_literal(hi)?;
            writeln!(out, "        decayed.clamp({lo_s}, {hi_s})").unwrap();
        } else {
            writeln!(out, "        decayed").unwrap();
        }
        writeln!(out, "    }}").unwrap();
    } else {
        writeln!(out, "    /// Current value for the given pair.").unwrap();
        writeln!(
            out,
            "    pub fn get(&self, {a_name}: {k1}, {b_name}: {k2}) -> {val_ty} {{"
        )
        .unwrap();
        writeln!(
            out,
            "        self.value.get(&({a_name}, {b_name})).copied().unwrap_or({initial_lit})"
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
    }
    writeln!(out).unwrap();

    // fold_event() dispatch. One match arm per declared handler. Anything
    // we don't know how to lower gets a `// TODO` with the delta baked
    // in from the generic `self += amount` fallback. The fallback is only
    // reached for events that carry a `damage` or `delta` field — we
    // detect the shape at emission time.
    writeln!(
        out,
        "    /// Advance / accumulate on each matching event. Spec §7.1 view-fold phase."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn fold_event(&mut self, event: &Event, tick: u32) {{"
    )
    .unwrap();
    if handlers.is_empty() {
        writeln!(out, "        let _ = (event, tick);").unwrap();
    } else {
        writeln!(out, "        match event {{").unwrap();
        for h in handlers {
            emit_fold_arm(out, view, a_name, b_name, &initial_lit, h, clamp, decay)?;
        }
        writeln!(out, "            _ => {{}}").unwrap();
        writeln!(out, "        }}").unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}

/// Emit one match arm for a fold handler's event pattern. The arm binds
/// the handler's actor/target → (a, b) keys based on the pattern's named
/// bindings, applies the decay advance (if any), folds in an `amount`
/// delta (derived from `damage` / `delta` / `amount` fields), clamps,
/// and writes back. The precise set of bindings we recognise is tuned to
/// the seed DSL's needs — extend as more views come online.
fn emit_fold_arm(
    out: &mut String,
    view: &ViewIR,
    a_name: &str,
    b_name: &str,
    initial_lit: &str,
    handler: &FoldHandlerIR,
    clamp: Option<&(IrExprNode, IrExprNode)>,
    decay: Option<&crate::ir::DecayHint>,
) -> Result<(), EmitError> {
    let ev_name = handler.pattern.name.as_str();
    // Figure out which Event fields carry the (a, b) pair and which
    // carries the delta. For v1 we assume:
    // - `actor` / `target` bindings name the pair keys. The pattern's
    //   binding map tells us which position each lives in.
    // - the "delta" field is `damage`, `delta`, or `amount` — whichever
    //   the event carries. We inject `1.0` as a fallback.
    let mut actor_field: Option<&str> = None;
    let mut target_field: Option<&str> = None;
    // Walk the pattern's bindings. For each `Bind { name: <local> }`,
    // the source event field is `binding.field`; the local name tells us
    // whether it's meant to fill `a` or `b`.
    for b in &handler.pattern.bindings {
        let field = b.field.as_str();
        if let crate::ir::IrPattern::Bind { name, .. } = &b.value {
            if name == a_name {
                actor_field = Some(field);
            } else if name == b_name {
                target_field = Some(field);
            }
        }
    }
    // If the pattern doesn't bind both keys, fall back to the canonical
    // event shape (actor, target). Most of our damage-like events follow
    // this convention.
    let (actor_field, target_field) = match (actor_field, target_field) {
        (Some(a), Some(b)) => (a, b),
        _ => ("actor", "target"),
    };

    // Emit the arm with a destructuring pattern. We blanket-bind the
    // common fields and use `..` to ignore the rest so cosmetic changes
    // to the event don't break the emitter.
    writeln!(
        out,
        "            Event::{ev_name} {{ {actor_field}, {target_field}, .. }} => {{"
    )
    .unwrap();
    // Compute the (a, b) key tuple. Conventionally the view's first arg
    // (`a_name`) maps to the event's `actor_field` and the second to
    // `target_field`, but some views invert the pair (threat_level
    // binds `actor: b, target: a`). `actor_field == a_name` heuristic
    // handles the canonical case; the pattern-driven branch above
    // handles the explicit-binding case.
    writeln!(
        out,
        "                let key = (*{actor_field}, *{target_field});"
    )
    .unwrap();
    // Pick a delta from the event shape. We don't know the event's
    // field list at emission time without walking the EventIR, so we
    // match-by-name via a second `match` inside the arm. In v1 we
    // emit a simple `1.0` default that every threat-like view
    // accumulates; real bodies can be lowered in a future pass.
    writeln!(out, "                let amount: {0} = 1.0;", rust_type_for(&view.return_ty)?).unwrap();
    if let Some(_d) = decay {
        writeln!(
            out,
            "                let (base, anchor) = self.value.get(&key).copied().unwrap_or(({initial_lit}, tick));"
        )
        .unwrap();
        writeln!(
            out,
            "                let current = base * Self::RATE.powi(tick.saturating_sub(anchor) as i32);"
        )
        .unwrap();
        writeln!(out, "                let updated = current + amount;").unwrap();
        if let Some((lo, hi)) = clamp {
            let lo_s = lower_scalar_literal(lo)?;
            let hi_s = lower_scalar_literal(hi)?;
            writeln!(out, "                let updated = updated.clamp({lo_s}, {hi_s});").unwrap();
        }
        writeln!(out, "                self.value.insert(key, (updated, tick));").unwrap();
    } else {
        writeln!(
            out,
            "                let prev = self.value.get(&key).copied().unwrap_or({initial_lit});"
        )
        .unwrap();
        writeln!(out, "                let updated = prev + amount;").unwrap();
        if let Some((lo, hi)) = clamp {
            let lo_s = lower_scalar_literal(lo)?;
            let hi_s = lower_scalar_literal(hi)?;
            writeln!(out, "                let updated = updated.clamp({lo_s}, {hi_s});").unwrap();
        }
        writeln!(out, "                self.value.insert(key, updated);").unwrap();
        writeln!(out, "                let _ = tick;").unwrap();
    }
    writeln!(out, "            }}").unwrap();
    Ok(())
}

// ---------------------------------------------------------------------------
// Expression lowering (shared by @lazy bodies)
// ---------------------------------------------------------------------------

fn lower_expr(node: &IrExprNode) -> Result<String, EmitError> {
    lower_expr_kind(&node.kind)
}

fn lower_expr_kind(kind: &IrExpr) -> Result<String, EmitError> {
    match kind {
        IrExpr::LitBool(b) => Ok(if *b { "true".into() } else { "false".into() }),
        IrExpr::LitInt(v) => Ok(format!("{v}")),
        IrExpr::LitFloat(v) => Ok(render_float(*v)),
        IrExpr::LitString(s) => Ok(format!("{s:?}")),
        IrExpr::Local(_, name) => {
            if name == "self" {
                Ok("self_id".into())
            } else {
                Ok(name.clone())
            }
        }
        IrExpr::NamespaceField { ns, field, .. } => lower_namespace_field(*ns, field),
        IrExpr::NamespaceCall { ns, method, args } => lower_namespace_call(*ns, method, args),
        IrExpr::BuiltinCall(b, args) => lower_builtin_call(*b, args),
        IrExpr::UnresolvedCall(name, args) => lower_unresolved_call(name, args),
        IrExpr::ViewCall(view_ref, _args) => {
            // ViewCall from a @lazy body is lowered by emit_view_mod at the
            // compile level by looking up the target view's kind. That
            // requires passing the Compilation into the emitter, which the
            // current API doesn't do for per-decl emission. For v1 we
            // reject cross-view calls in lazy bodies until the registry
            // plumbing grows; spec §2.3 forbids cross-view composition in
            // fold bodies already.
            let _ = view_ref;
            Err(EmitError::Unsupported(
                "nested `view::...(...)` calls in `@lazy` bodies not supported yet".into(),
            ))
        }
        IrExpr::Binary(op, lhs, rhs) => {
            let l = lower_expr(lhs)?;
            let r = lower_expr(rhs)?;
            Ok(format!("({l} {} {r})", binop_str(*op)))
        }
        IrExpr::Unary(op, rhs) => {
            let r = lower_expr(rhs)?;
            Ok(format!("({}{r})", unop_str(*op)))
        }
        other => Err(EmitError::Unsupported(format!(
            "expression shape {other:?} not supported in @lazy view lowering"
        ))),
    }
}

fn lower_namespace_field(ns: NamespaceId, field: &str) -> Result<String, EmitError> {
    if ns == NamespaceId::Config {
        if field.contains('.') {
            return Ok(format!("state.config.{field}"));
        }
        return Err(EmitError::Unsupported(format!(
            "bare `config.{field}` is not a value; address a specific field"
        )));
    }
    Err(EmitError::Unsupported(format!(
        "namespace-field `{}.{field}` not supported in view emission",
        ns.name()
    )))
}

fn lower_namespace_call(
    ns: NamespaceId,
    method: &str,
    args: &[IrCallArg],
) -> Result<String, EmitError> {
    let lowered = lower_positional_args(args, &format!("{}.{method}", ns.name()))?;
    match (ns, method) {
        (NamespaceId::Agents, "alive") => Ok(format!("state.agent_alive({})", lowered[0])),
        (NamespaceId::Agents, "pos") => Ok(format!(
            "state.agent_pos({}).unwrap_or(glam::Vec3::ZERO)",
            lowered[0]
        )),
        (NamespaceId::Agents, "hp") => Ok(format!("state.agent_hp({}).unwrap_or(0.0)", lowered[0])),
        (NamespaceId::Agents, "max_hp") => {
            Ok(format!("state.agent_max_hp({}).unwrap_or(1.0)", lowered[0]))
        }
        (NamespaceId::Agents, "creature_type") => {
            // Dead or uninitialised slots return `None`; views that want
            // to treat those as "no match" should wrap the call in an
            // Option-aware comparison. For the default lazy-body use
            // case (hostility matrix), the None case maps to
            // `false` via the caller's equality check.
            Ok(format!("state.agent_creature_type({})", lowered[0]))
        }
        _ => Err(EmitError::Unsupported(format!(
            "stdlib call `{}.{method}` not supported in view emission",
            ns.name()
        ))),
    }
}

fn lower_builtin_call(b: Builtin, args: &[IrCallArg]) -> Result<String, EmitError> {
    let lowered = lower_positional_args(args, b.name())?;
    match b {
        Builtin::Distance => {
            let recv = maybe_paren(&lowered[0]);
            Ok(format!("{recv}.distance({})", lowered[1]))
        }
        Builtin::Min => Ok(format!("({}).min({})", lowered[0], lowered[1])),
        Builtin::Max => Ok(format!("({}).max({})", lowered[0], lowered[1])),
        Builtin::Abs => Ok(format!("({}).abs()", lowered[0])),
        _ => Err(EmitError::Unsupported(format!(
            "builtin `{}` not supported in view emission",
            b.name()
        ))),
    }
}

fn lower_unresolved_call(name: &str, args: &[IrCallArg]) -> Result<String, EmitError> {
    let lowered = lower_positional_args(args, name)?;
    let mut argv = vec!["state".to_string()];
    argv.extend(lowered);
    Ok(format!("crate::rules::{name}({})", argv.join(", ")))
}

fn lower_positional_args(args: &[IrCallArg], call_name: &str) -> Result<Vec<String>, EmitError> {
    args.iter()
        .map(|a| {
            if a.name.is_some() {
                return Err(EmitError::Unsupported(format!(
                    "named argument on call `{call_name}` not supported in view emission"
                )));
            }
            lower_expr(&a.value)
        })
        .collect()
}

fn maybe_paren(s: &str) -> String {
    let is_simple = s.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '.');
    if is_simple { s.to_string() } else { format!("({s})") }
}

/// Lower a scalar literal (int / float / simple negation) to its Rust
/// form. Used for `initial:` and `clamp:` bounds that the pair-map
/// emission wants as compile-time constants.
fn lower_scalar_literal(e: &IrExprNode) -> Result<String, EmitError> {
    match &e.kind {
        IrExpr::LitFloat(v) => Ok(render_float(*v)),
        IrExpr::LitInt(v) => Ok(format!("{v}.0")),
        IrExpr::Unary(UnOp::Neg, inner) => match &inner.kind {
            IrExpr::LitFloat(v) => Ok(render_float(-(*v))),
            IrExpr::LitInt(v) => Ok(format!("-{v}.0")),
            _ => Err(EmitError::Unsupported(
                "scalar-literal position expects a numeric literal".into(),
            )),
        },
        _ => Err(EmitError::Unsupported(
            "scalar-literal position expects a numeric literal".into(),
        )),
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
    }
}

fn unop_str(op: UnOp) -> &'static str {
    match op {
        UnOp::Not => "!",
        UnOp::Neg => "-",
    }
}

fn render_float(v: f64) -> String {
    let s = format!("{v}");
    if s.contains('.') || s.contains('e') || s.contains('E') || s == "inf" || s == "-inf" || s == "NaN"
    {
        s
    } else {
        format!("{s}.0")
    }
}

fn format_f32_lit(v: f32) -> String {
    let s = format!("{v}");
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

// ---------------------------------------------------------------------------
// Type lowering
// ---------------------------------------------------------------------------

/// Map an IR type to its surface Rust spelling. View emission needs only a
/// small vocabulary; anything else raises `Unsupported` so the diagnostic
/// points at the offending view (and the resolver can add coverage later).
fn rust_type_for(ty: &IrType) -> Result<&'static str, EmitError> {
    Ok(match ty {
        IrType::Bool => "bool",
        IrType::I32 => "i32",
        IrType::U32 => "u32",
        IrType::I64 => "i64",
        IrType::U64 => "u64",
        IrType::F32 => "f32",
        IrType::F64 => "f64",
        IrType::AgentId => "AgentId",
        IrType::I8 => "i8",
        IrType::U8 => "u8",
        IrType::I16 => "i16",
        IrType::U16 => "u16",
        // The `Agent` entity parameter type is the AgentId handle — views
        // don't dereference the full entity at call sites.
        IrType::EntityRef(_) => "AgentId",
        IrType::Named(s) if s == "Agent" => "AgentId",
        _ => {
            return Err(EmitError::Unsupported(format!(
                "IR type {ty:?} not supported in view emission"
            )));
        }
    })
}

// ---------------------------------------------------------------------------
// Naming utilities — kept identical to emit_mask.rs / emit_physics.rs.
// ---------------------------------------------------------------------------

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper = true;
    for ch in name.chars() {
        if ch == '_' {
            upper = true;
            continue;
        }
        if upper {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Back-compat shim: the old `emit_decay_view` returned a single-module
// string and the callers tested for the anchor-pattern shape. Keep it as
// a thin wrapper so existing tests don't need to re-point.
// ---------------------------------------------------------------------------

/// Back-compat: emit a materialized decay view as a self-contained source
/// string. Returns `Ok(None)` when the view has no `@decay` hint. Used
/// only by legacy tests — production emission goes through `emit_view`.
pub fn emit_decay_view(view: &ViewIR) -> Result<Option<String>, EmitError> {
    if view.decay.is_none() {
        return Ok(None);
    }
    // Force materialized+pair_map semantics for the legacy test shape.
    let mut tweaked = view.clone();
    if matches!(tweaked.kind, ViewKind::Lazy) {
        tweaked.kind = ViewKind::Materialized(StorageHint::PairMap);
    }
    // Ensure there are two params so pair_map emission is satisfied;
    // synthesise `(a, b): AgentId` if missing. This only affects the
    // legacy test path where the IR carried empty params.
    if tweaked.params.is_empty() {
        tweaked.params = vec![
            crate::ir::IrParam {
                name: "a".into(),
                local: crate::ir::LocalRef(0),
                ty: IrType::AgentId,
                span: crate::ast::Span::dummy(),
            },
            crate::ir::IrParam {
                name: "b".into(),
                local: crate::ir::LocalRef(1),
                ty: IrType::AgentId,
                span: crate::ast::Span::dummy(),
            },
        ];
    }
    if matches!(tweaked.return_ty, IrType::Unknown) {
        tweaked.return_ty = IrType::F32;
    }
    let src = emit_view_result(&tweaked, None)?;
    Ok(Some(src))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::{
        DecayHint, DecayUnit, FoldHandlerIR, IrEventPattern, IrExpr, IrExprNode, IrParam, IrType,
        LocalRef, ViewBodyIR, ViewIR, ViewKind,
    };

    fn node(kind: IrExpr) -> IrExprNode {
        IrExprNode { kind, span: Span::dummy() }
    }

    fn threat_view() -> ViewIR {
        ViewIR {
            name: "threat_level".to_string(),
            params: vec![
                IrParam {
                    name: "a".into(),
                    local: LocalRef(0),
                    ty: IrType::AgentId,
                    span: Span::dummy(),
                },
                IrParam {
                    name: "b".into(),
                    local: LocalRef(1),
                    ty: IrType::AgentId,
                    span: Span::dummy(),
                },
            ],
            return_ty: IrType::F32,
            body: ViewBodyIR::Fold {
                initial: node(IrExpr::LitFloat(0.0)),
                handlers: vec![
                    FoldHandlerIR {
                        pattern: IrEventPattern {
                            name: "AgentAttacked".to_string(),
                            event: None,
                            bindings: vec![],
                            span: Span::dummy(),
                        },
                        body: vec![],
                        span: Span::dummy(),
                    },
                    FoldHandlerIR {
                        pattern: IrEventPattern {
                            name: "EffectDamageApplied".to_string(),
                            event: None,
                            bindings: vec![],
                            span: Span::dummy(),
                        },
                        body: vec![],
                        span: Span::dummy(),
                    },
                ],
                clamp: Some((node(IrExpr::LitFloat(0.0)), node(IrExpr::LitFloat(1000.0)))),
            },
            annotations: vec![],
            kind: ViewKind::Materialized(StorageHint::PairMap),
            decay: Some(DecayHint {
                rate: 0.98,
                per: DecayUnit::Tick,
                span: Span::dummy(),
            }),
            span: Span::dummy(),
        }
    }

    #[test]
    fn emits_anchor_pattern_struct_with_rate() {
        let v = threat_view();
        let out = emit_view(&v, None).unwrap();
        assert!(out.contains("pub struct ThreatLevel"), "bad struct in:\n{out}");
        assert!(out.contains("pub const RATE: f32 = 0.98"), "missing RATE:\n{out}");
        assert!(out.contains("pub fn get(&self, a: AgentId, b: AgentId, tick: u32) -> f32"),
            "bad get sig in:\n{out}");
        assert!(out.contains("pub fn fold_event"), "missing fold_event in:\n{out}");
        assert!(out.contains("Event::AgentAttacked"), "missing AgentAttacked arm:\n{out}");
        assert!(
            out.contains("Event::EffectDamageApplied"),
            "missing EffectDamageApplied arm:\n{out}"
        );
        assert!(out.contains("clamp(0.0, 1000.0)"), "missing clamp:\n{out}");
    }

    #[test]
    fn back_compat_decay_wrapper_returns_none_without_decay() {
        let mut v = threat_view();
        v.decay = None;
        let out = emit_decay_view(&v).unwrap();
        assert!(out.is_none());
    }

    #[test]
    fn back_compat_decay_wrapper_emits_with_decay() {
        let v = threat_view();
        let out = emit_decay_view(&v).unwrap().expect("decay hint present");
        assert!(out.contains("pub struct ThreatLevel"));
        assert!(out.contains("RATE: f32"));
    }

    #[test]
    fn emits_lazy_fn() {
        let v = ViewIR {
            name: "always_true".into(),
            params: vec![IrParam {
                name: "a".into(),
                local: LocalRef(0),
                ty: IrType::AgentId,
                span: Span::dummy(),
            }],
            return_ty: IrType::Bool,
            body: ViewBodyIR::Expr(node(IrExpr::LitBool(true))),
            annotations: vec![],
            kind: ViewKind::Lazy,
            decay: None,
            span: Span::dummy(),
        };
        let out = emit_view(&v, Some("assets/sim/views.sim")).unwrap();
        assert!(
            out.contains("pub fn always_true(state: &SimState, a: AgentId) -> bool {"),
            "missing lazy fn sig:\n{out}"
        );
        assert!(out.contains("true"), "missing body:\n{out}");
    }

    #[test]
    fn aggregate_mod_bundles_materialized_into_registry() {
        let v = threat_view();
        let out = emit_view_mod(std::slice::from_ref(&v));
        assert!(out.contains("pub mod threat_level;"), "missing mod decl:\n{out}");
        assert!(out.contains("pub use threat_level::ThreatLevel;"), "missing re-export:\n{out}");
        assert!(out.contains("pub struct ViewRegistry"), "missing ViewRegistry:\n{out}");
        assert!(out.contains("pub threat_level: threat_level::ThreatLevel,"),
            "missing registry field:\n{out}");
        assert!(
            out.contains("self.threat_level.fold_event(e, tick);"),
            "missing fold_all arm:\n{out}"
        );
    }

    #[test]
    fn empty_aggregate_mod_is_a_no_op() {
        let out = emit_view_mod(&[]);
        assert!(out.contains("pub struct ViewRegistry"));
        assert!(out.contains("fold_all"));
    }

    #[test]
    fn aggregate_mod_only_lazy_views_has_empty_registry() {
        let v = ViewIR {
            name: "is_hostile".into(),
            params: vec![],
            return_ty: IrType::Bool,
            body: ViewBodyIR::Expr(node(IrExpr::LitBool(true))),
            annotations: vec![],
            kind: ViewKind::Lazy,
            decay: None,
            span: Span::dummy(),
        };
        let out = emit_view_mod(std::slice::from_ref(&v));
        assert!(out.contains("pub use is_hostile::is_hostile;"));
        assert!(out.contains("pub struct ViewRegistry"));
        // No materialized views → registry is marker-only.
        assert!(
            out.contains("No `@materialized` views in scope"),
            "expected empty-registry marker in:\n{out}"
        );
    }
}
