//! Emits one Rust + WGSL pair per materialized view fold kernel.
//!
//! Each materialized view in the IR (i.e. those with a `Fold` body, not
//! lazy `Expr` bodies) gets its own `Fold<Pascal>Kernel` wrapper struct
//! that implements `crate::Kernel`. The kernel wraps `cs_fold_<view>`
//! and binds the per-view storage triple (primary + optional anchor +
//! optional ids) plus the post-cascade batch event ring + tail.
//!
//! BGL slot order (matches the no-op WGSL stub the xtask writes alongside;
//! T16 hoists the real WGSL body once the hand-written fold dispatch
//! retires):
//!
//! | Slot | Name                   | Type                          | Access     |
//! |------|------------------------|-------------------------------|------------|
//! | 0    | `event_ring`           | `array<EventRecord>` (ro)     | read       |
//! | 1    | `event_tail`           | `atomic<u32>` (ro)            | read       |
//! | 2    | `view_storage_primary` | `array<...>` (rw)             | read_write |
//! | 3    | `view_storage_anchor`  | `array<...>` (rw, optional)   | read_write |
//! | 4    | `view_storage_ids`     | `array<...>` (rw, optional)   | read_write |
//! | 5    | `sim_cfg`              | `SimCfg` (storage)            | read       |
//! | 6    | `cfg`                  | `Fold<Pascal>Cfg` (uniform)   | uniform    |
//!
//! For non-topk views (no anchor / ids), the resident accessor returns
//! `None` for those positions; the emitted `record()` body falls back
//! to the primary buffer to keep the BGL slot live (a `dummy` binding
//! reuses the primary buffer's `as_entire_binding()`).

pub fn emit_view_fold_rs(view_name: &str) -> String {
    use std::fmt::Write;
    let pascal = pascal(view_name);
    let mut out = String::new();
    writeln!(
        out,
        "// GENERATED by dsl_compiler::emit_view_fold_kernel. Do not edit by hand."
    )
    .unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use crate::binding_sources::BindingSources;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub struct Fold{pascal}Kernel {{").unwrap();
    writeln!(out, "    pipeline: wgpu::ComputePipeline,").unwrap();
    writeln!(out, "    bgl: wgpu::BindGroupLayout,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub struct Fold{pascal}Bindings<'a> {{").unwrap();
    writeln!(out, "    pub event_ring: &'a wgpu::Buffer,").unwrap();
    writeln!(out, "    pub event_tail: &'a wgpu::Buffer,").unwrap();
    writeln!(out, "    pub view_storage_primary: &'a wgpu::Buffer,").unwrap();
    writeln!(out, "    pub view_storage_anchor: Option<&'a wgpu::Buffer>,").unwrap();
    writeln!(out, "    pub view_storage_ids: Option<&'a wgpu::Buffer>,").unwrap();
    writeln!(out, "    pub sim_cfg: &'a wgpu::Buffer,").unwrap();
    writeln!(out, "    pub cfg: &'a wgpu::Buffer,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[repr(C)]").unwrap();
    writeln!(
        out,
        "#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]"
    )
    .unwrap();
    writeln!(
        out,
        "pub struct Fold{pascal}Cfg {{ pub event_count: u32, pub tick: u32, pub _pad: [u32; 2] }}"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "const SHADER_SRC: &str = include_str!(\"fold_{view_name}.wgsl\");"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl crate::Kernel for Fold{pascal}Kernel {{").unwrap();
    writeln!(out, "    type Bindings<'a> = Fold{pascal}Bindings<'a>;").unwrap();
    writeln!(out, "    type Cfg = Fold{pascal}Cfg;").unwrap();
    writeln!(out, "    fn new(device: &wgpu::Device) -> Self {{").unwrap();
    writeln!(
        out,
        "        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::fold_{view_name}::wgsl\"),"
    )
    .unwrap();
    writeln!(
        out,
        "            source: wgpu::ShaderSource::Wgsl(SHADER_SRC.into()),"
    )
    .unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(
        out,
        "        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::fold_{view_name}::bgl\"),"
    )
    .unwrap();
    writeln!(out, "            entries: &[").unwrap();
    writeln!(
        out,
        "                crate::fused_mask::bgl_storage(0, true),  // event_ring"
    )
    .unwrap();
    writeln!(
        out,
        "                crate::fused_mask::bgl_storage(1, true),  // event_tail"
    )
    .unwrap();
    writeln!(
        out,
        "                crate::fused_mask::bgl_storage(2, false), // view_storage primary"
    )
    .unwrap();
    writeln!(
        out,
        "                crate::fused_mask::bgl_storage(3, false), // view_storage anchor (optional)"
    )
    .unwrap();
    writeln!(
        out,
        "                crate::fused_mask::bgl_storage(4, false), // view_storage ids (optional)"
    )
    .unwrap();
    writeln!(
        out,
        "                crate::fused_mask::bgl_storage(5, true),  // sim_cfg"
    )
    .unwrap();
    writeln!(
        out,
        "                crate::fused_mask::bgl_uniform(6),        // cfg"
    )
    .unwrap();
    writeln!(out, "            ],").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(
        out,
        "        let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::fold_{view_name}::pl\"),"
    )
    .unwrap();
    writeln!(
        out,
        "            bind_group_layouts: &[&bgl], push_constant_ranges: &[],"
    )
    .unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(
        out,
        "        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::fold_{view_name}::pipeline\"),"
    )
    .unwrap();
    writeln!(
        out,
        "            layout: Some(&pl), module: &shader, entry_point: Some(\"cs_fold_{view_name}\"),"
    )
    .unwrap();
    writeln!(
        out,
        "            compilation_options: Default::default(), cache: None,"
    )
    .unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        Self {{ pipeline, bgl }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    fn build_cfg(&self, state: &engine::state::SimState) -> Fold{pascal}Cfg {{"
    )
    .unwrap();
    writeln!(
        out,
        "        Fold{pascal}Cfg {{ event_count: 0, tick: state.tick, _pad: [0; 2] }}"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    fn bind<'a>(&'a self, sources: &'a BindingSources<'a>, cfg: &'a wgpu::Buffer) -> Fold{pascal}Bindings<'a> {{"
    )
    .unwrap();
    writeln!(
        out,
        "        // The view's storage shape (SlotMap / PairMapScalar / PairMapDecay,"
    )
    .unwrap();
    writeln!(
        out,
        "        // optionally topk) determines whether anchor/ids fields exist on"
    )
    .unwrap();
    writeln!(
        out,
        "        // the resident context. The emitter sets `Some(...)` if the view"
    )
    .unwrap();
    writeln!(
        out,
        "        // declared topk + anchor; otherwise None. The emitted helper"
    )
    .unwrap();
    writeln!(
        out,
        "        // `sources.resident.fold_view_<name>_handles()` returns a triple"
    )
    .unwrap();
    writeln!(
        out,
        "        // of (primary, anchor_opt, ids_opt) borrowed from the ctx fields."
    )
    .unwrap();
    writeln!(
        out,
        "        let (primary, anchor, ids) = sources.resident.fold_view_{view_name}_handles();"
    )
    .unwrap();
    writeln!(out, "        Fold{pascal}Bindings {{").unwrap();
    writeln!(
        out,
        "            event_ring:           &sources.resident.batch_events_ring,"
    )
    .unwrap();
    writeln!(
        out,
        "            event_tail:           &sources.resident.batch_events_tail,"
    )
    .unwrap();
    writeln!(out, "            view_storage_primary: primary,").unwrap();
    writeln!(out, "            view_storage_anchor:  anchor,").unwrap();
    writeln!(out, "            view_storage_ids:     ids,").unwrap();
    writeln!(
        out,
        "            sim_cfg:              sources.external.sim_cfg,"
    )
    .unwrap();
    writeln!(out, "            cfg,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    fn record(&self, device: &wgpu::Device, encoder: &mut wgpu::CommandEncoder, bindings: &Fold{pascal}Bindings<'_>, agent_cap: u32) {{"
    )
    .unwrap();
    writeln!(
        out,
        "        let dummy = bindings.view_storage_primary; // fallback for None anchors/ids"
    )
    .unwrap();
    writeln!(
        out,
        "        let bg = device.create_bind_group(&wgpu::BindGroupDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::fold_{view_name}::bg\"),"
    )
    .unwrap();
    writeln!(out, "            layout: &self.bgl,").unwrap();
    writeln!(out, "            entries: &[").unwrap();
    writeln!(
        out,
        "                wgpu::BindGroupEntry {{ binding: 0, resource: bindings.event_ring.as_entire_binding() }},"
    )
    .unwrap();
    writeln!(
        out,
        "                wgpu::BindGroupEntry {{ binding: 1, resource: bindings.event_tail.as_entire_binding() }},"
    )
    .unwrap();
    writeln!(
        out,
        "                wgpu::BindGroupEntry {{ binding: 2, resource: bindings.view_storage_primary.as_entire_binding() }},"
    )
    .unwrap();
    writeln!(
        out,
        "                wgpu::BindGroupEntry {{ binding: 3, resource: bindings.view_storage_anchor.unwrap_or(dummy).as_entire_binding() }},"
    )
    .unwrap();
    writeln!(
        out,
        "                wgpu::BindGroupEntry {{ binding: 4, resource: bindings.view_storage_ids.unwrap_or(dummy).as_entire_binding() }},"
    )
    .unwrap();
    writeln!(
        out,
        "                wgpu::BindGroupEntry {{ binding: 5, resource: bindings.sim_cfg.as_entire_binding() }},"
    )
    .unwrap();
    writeln!(
        out,
        "                wgpu::BindGroupEntry {{ binding: 6, resource: bindings.cfg.as_entire_binding() }},"
    )
    .unwrap();
    writeln!(out, "            ],").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(
        out,
        "        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {{"
    )
    .unwrap();
    writeln!(
        out,
        "            label: Some(\"engine_gpu_rules::fold_{view_name}::pass\"),"
    )
    .unwrap();
    writeln!(out, "            timestamp_writes: None,").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "        pass.set_pipeline(&self.pipeline);").unwrap();
    writeln!(out, "        pass.set_bind_group(0, &bg, &[]);").unwrap();
    writeln!(
        out,
        "        pass.dispatch_workgroups((agent_cap + 63) / 64, 1, 1);"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    out
}

/// Lowercase snake_case → PascalCase converter. `engaged_with` →
/// `EngagedWith`; `threat_level` → `ThreatLevel`.
fn pascal(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c == '_' {
            up = true;
            continue;
        }
        if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_converts_snake_to_pascal() {
        assert_eq!(pascal("engaged_with"), "EngagedWith");
        assert_eq!(pascal("threat_level"), "ThreatLevel");
        assert_eq!(pascal("standing"), "Standing");
        assert_eq!(pascal("kin_fear"), "KinFear");
    }
}
