//! Emits `engine_gpu_rules/src/binding_sources.rs` — the 5-field
//! aggregate the trait method `Kernel::bind` consumes. Stable across
//! regens (its shape is fixed; the containers it references are
//! per-task-extended).

use std::fmt::Write;

pub fn emit_binding_sources_rs() -> String {
    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler::emit_binding_sources. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use crate::resident_context::ResidentPathContext;").unwrap();
    writeln!(out, "use crate::pingpong_context::PingPongContext;").unwrap();
    writeln!(out, "use crate::pool::Pool;").unwrap();
    writeln!(out, "use crate::transient_handles::TransientHandles;").unwrap();
    writeln!(out, "use crate::external_buffers::ExternalBuffers;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// Aggregate of every container kernels can pull buffers from.").unwrap();
    writeln!(out, "/// `Kernel::bind` takes `&BindingSources<'a>` and walks into the").unwrap();
    writeln!(out, "/// right field; each kernel's emitted bind() body is real").unwrap();
    writeln!(out, "/// generated code, not `unimplemented!()`.").unwrap();
    writeln!(out, "pub struct BindingSources<'a> {{").unwrap();
    writeln!(out, "    pub resident:  &'a ResidentPathContext,").unwrap();
    writeln!(out, "    pub pingpong:  &'a PingPongContext,").unwrap();
    writeln!(out, "    pub pool:      &'a Pool,").unwrap();
    writeln!(out, "    pub transient: &'a TransientHandles<'a>,").unwrap();
    writeln!(out, "    pub external:  &'a ExternalBuffers<'a>,").unwrap();
    writeln!(out, "}}").unwrap();
    out
}
