//! Rust emission for compiler milestone 2.
//!
//! Every `event` declaration produces:
//!
//! 1. A standalone `struct` in `events/<snake_case>.rs` (kept for serde /
//!    Python trace-row parity, and for external consumers that want to
//!    construct a single event value without the enum tag).
//! 2. A variant in the aggregate `Event` enum (in `events/mod.rs`) with
//!    the SAME fields inlined — `Event::AgentDied { agent_id, tick }` — so
//!    pattern-matching call sites inside `engine::*` read exactly like the
//!    pre-milestone hand-written enum. The integration step at milestone 2
//!    relies on this shape: `engine` deleted its own `Event` and now
//!    consumes `engine_rules::events::Event` with zero call-site changes.
//!
//! The emitter is deliberately mechanical — no macros, no helper traits,
//! just `writeln!` into a `String`. Reviewers should be able to skim the
//! emitted output without tracing any abstractions back to the emitter.

use std::collections::BTreeSet;
use std::fmt::Write;

use crate::ir::{EventField, EventIR, IrType};
use crate::ast::Span;

/// Returns a copy of `event.fields` with the synthetic `tick: u32` appended
/// if not already present. `tick` is implicit on every event; this helper
/// keeps both the per-struct emission and the aggregate enum consistent.
fn fields_with_implicit_tick(event: &EventIR) -> Vec<EventField> {
    let mut out = event.fields.clone();
    if !out.iter().any(|f| f.name == "tick") {
        out.push(EventField { name: "tick".into(), ty: IrType::U32, span: Span::dummy() });
    }
    out
}

/// Emit a single event file (`events/<snake_case>.rs`).
///
/// `source_file` is the DSL source path the event came from. If a single path
/// is threaded through, we stamp it into the header; otherwise the caller
/// passes `None` and we emit a generic header.
pub fn emit_event(event: &EventIR, source_file: Option<&str>) -> String {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    // Synthesize the `tick: u32` field for imports + struct emission so the
    // per-struct file stays in sync with the enum variant.
    let mut e = event.clone();
    e.fields = fields_with_implicit_tick(event);
    emit_imports(&mut out, std::slice::from_ref(&e));
    emit_struct(&mut out, &e);
    out
}

/// Emit the aggregate `events/mod.rs` — contains the enum `Event` whose
/// variants carry the same field shape as the per-struct modules, inlined.
pub fn emit_events_mod(events: &[EventIR]) -> String {
    // Synthesize implicit `tick: u32` on every event variant before emission.
    let hydrated: Vec<EventIR> = events
        .iter()
        .map(|e| {
            let mut c = e.clone();
            c.fields = fields_with_implicit_tick(e);
            c
        })
        .collect();
    let mut sorted: Vec<&EventIR> = hydrated.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();

    for e in &sorted {
        writeln!(out, "pub mod {};", snake_case(&e.name)).unwrap();
    }
    writeln!(out).unwrap();
    for e in &sorted {
        writeln!(out, "pub use {}::{};", snake_case(&e.name), e.name).unwrap();
    }
    writeln!(out).unwrap();

    // Imports for the inline-struct enum variants: the same niche IDs /
    // Vec3 / etc. used by the per-event structs, plus any named types
    // we know how to route (QuestCategory / Resolution).
    let events_owned: Vec<EventIR> = sorted.iter().copied().cloned().collect();
    emit_imports(&mut out, &events_owned);

    // Copy on the enum requires Copy on every variant's every field. This
    // matches the pre-milestone hand-written `engine_data::events::Event`, which
    // was `#[derive(Copy, Clone, Debug, PartialEq)]`. The engine's ring
    // buffer depends on `Event: Copy` (it returns owned copies via
    // `EventRing::get_pushed`). If a future declaration adds a non-Copy
    // field (e.g. `String`), this drops to `Clone` only and the ring
    // buffer will fail to compile — flagging that call site so it can be
    // migrated to `Clone`.
    let all_variants_copy = hydrated
        .iter()
        .all(|e| e.fields.iter().all(|f| is_copy(&f.ty)));
    if all_variants_copy {
        writeln!(out, "#[derive(Copy, Clone, Debug, PartialEq)]").unwrap();
    } else {
        writeln!(out, "#[derive(Clone, Debug, PartialEq)]").unwrap();
    }
    writeln!(out, "pub enum Event {{").unwrap();
    for e in &sorted {
        if e.fields.is_empty() {
            writeln!(out, "    {},", e.name).unwrap();
            continue;
        }
        writeln!(out, "    {} {{", e.name).unwrap();
        for f in &e.fields {
            writeln!(out, "        {}: {},", f.name, render_type(&f.ty)).unwrap();
        }
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Associated helpers — two methods every replayable sim needs:
    // `tick()` to bucket events into a frame, `is_replayable()` to
    // partition replayable from side-channel ones. The latter honours the
    // `@replayable` annotation: anything NOT marked is treated as a side
    // channel (chronicle / telemetry) and excluded from replay hashes.
    emit_event_impl(&mut out, &sorted);
    writeln!(out).unwrap();

    // `impl engine::event::EventLike for Event` — the trait bridge that
    // lets engine's generic containers (`EventRing<E>`, `CascadeRegistry<E>`,
    // etc.) work with this event enum. Emitting it here (inside engine_data)
    // satisfies the orphan rule now that engine_data depends on engine.
    emit_event_like_impl(&mut out, &sorted);

    out
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(
            out,
            "// GENERATED by dsl_compiler from {}.",
            path
        )
        .unwrap(),
        None => writeln!(out, "// GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "// Do not edit by hand.").unwrap();
    writeln!(out).unwrap();
}

fn emit_imports(out: &mut String, events: &[EventIR]) {
    let mut niche_ids: BTreeSet<&'static str> = BTreeSet::new();
    let mut needs_vec3 = false;
    let mut needs_smallvec = false;
    let mut named_engine_types: BTreeSet<&'static str> = BTreeSet::new();

    for e in events {
        for f in &e.fields {
            collect_imports(
                &f.ty,
                &mut niche_ids,
                &mut needs_vec3,
                &mut needs_smallvec,
                &mut named_engine_types,
            );
        }
    }

    // Emit imports in alphabetical order so `rustfmt` is a no-op.
    // Order: crate::ids, crate::types, glam, smallvec.
    let mut wrote_anything = false;
    if !niche_ids.is_empty() {
        let joined: Vec<&str> = niche_ids.iter().copied().collect();
        if joined.len() == 1 {
            writeln!(out, "use crate::ids::{};", joined[0]).unwrap();
        } else {
            writeln!(out, "use crate::ids::{{{}}};", joined.join(", ")).unwrap();
        }
        wrote_anything = true;
    }
    // Named types we route into `crate::types::*`.
    for ty in &named_engine_types {
        if let Some(import) = engine_named_import(ty) {
            writeln!(out, "{}", import).unwrap();
            wrote_anything = true;
        }
    }
    if needs_vec3 {
        writeln!(out, "use glam::Vec3;").unwrap();
        wrote_anything = true;
    }
    if needs_smallvec {
        writeln!(out, "use smallvec::SmallVec;").unwrap();
        wrote_anything = true;
    }
    if wrote_anything {
        writeln!(out).unwrap();
    }
}

/// Canonical import for each named type that may appear in an event field.
/// Returns `None` for types we don't recognise — those render by bare name
/// and expect the caller to import them.
///
/// Routed types live in `engine_rules::types`; the emitter references them
/// via `crate::types::...` because every emission target is inside the
/// `engine_rules` crate root.
fn engine_named_import(name: &str) -> Option<&'static str> {
    match name {
        "QuestCategory" => Some("use crate::types::QuestCategory;"),
        "Resolution" => Some("use crate::types::Resolution;"),
        _ => None,
    }
}

fn collect_imports(
    ty: &IrType,
    niche_ids: &mut BTreeSet<&'static str>,
    needs_vec3: &mut bool,
    needs_smallvec: &mut bool,
    named_engine_types: &mut BTreeSet<&'static str>,
) {
    match ty {
        IrType::AgentId => {
            niche_ids.insert("AgentId");
        }
        IrType::ItemId => {
            niche_ids.insert("ItemId");
        }
        IrType::GroupId => {
            niche_ids.insert("GroupId");
        }
        IrType::QuestId => {
            niche_ids.insert("QuestId");
        }
        IrType::AuctionId => {
            niche_ids.insert("AuctionId");
        }
        IrType::EventId => {
            niche_ids.insert("EventId");
        }
        IrType::AbilityId => {
            niche_ids.insert("AbilityId");
        }
        IrType::Vec3 => {
            *needs_vec3 = true;
        }
        IrType::Named(n) => {
            // Interned matches on the engine-side named types we know how
            // to route. Unknown names render bare and rely on caller-side
            // imports — the compiler flags them with `Named(..)` in the IR.
            match n.as_str() {
                "QuestCategory" => {
                    named_engine_types.insert("QuestCategory");
                }
                "Resolution" => {
                    named_engine_types.insert("Resolution");
                }
                _ => {}
            }
        }
        IrType::SortedVec(inner, _)
        | IrType::RingBuffer(inner, _)
        | IrType::SmallVec(inner, _)
        | IrType::Array(inner, _)
        | IrType::Optional(inner)
        | IrType::List(inner) => {
            if matches!(ty, IrType::SmallVec(_, _)) {
                *needs_smallvec = true;
            }
            collect_imports(inner, niche_ids, needs_vec3, needs_smallvec, named_engine_types);
        }
        IrType::Tuple(items) => {
            for t in items {
                collect_imports(t, niche_ids, needs_vec3, needs_smallvec, named_engine_types);
            }
        }
        _ => {}
    }
}

fn emit_struct(out: &mut String, event: &EventIR) {
    let all_copy = event.fields.iter().all(|f| is_copy(&f.ty));
    // No serde derive for now — milestone 2's cutover dropped it so the
    // emitted struct doesn't require `Vec3: Serialize` or a bridge for
    // every niche ID. Trace emission (milestone 11's Python surface)
    // brings serde back behind a feature flag.
    if all_copy {
        writeln!(out, "#[derive(Copy, Clone, Debug, PartialEq)]").unwrap();
    } else {
        writeln!(out, "#[derive(Clone, Debug, PartialEq)]").unwrap();
    }
    writeln!(out, "pub struct {} {{", event.name).unwrap();
    for f in &event.fields {
        writeln!(out, "    pub {}: {},", f.name, render_type(&f.ty)).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

/// Emit `impl Event { fn tick() .. fn is_replayable() .. }`. Both methods
/// walk the variant list: `tick()` looks for a field named `tick` (the
/// engine convention — every replayable variant carries one); any variant
/// without a tick field returns `0`. `is_replayable()` checks the
/// `@replayable` annotation on each source declaration.
fn emit_event_impl(out: &mut String, events: &[&EventIR]) {
    writeln!(out, "impl Event {{").unwrap();

    // `tick()` — the pre-milestone engine::event shape returns `u32`. Some
    // DSL events may declare `tick: u64` if the source author wrote it that
    // way; we emit a `u32` signature here because every call site in the
    // engine already expects u32. If a variant's `tick` field is a wider
    // type, we narrow via `as u32`. When there's no `tick` field, the
    // variant returns `0` — this only fires for events without replay
    // semantics, which the caller filters out via `is_replayable()` first.
    writeln!(out, "    pub fn tick(&self) -> u32 {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for e in events {
        let has_tick = e.fields.iter().any(|f| f.name == "tick");
        if has_tick {
            let tick_field = e.fields.iter().find(|f| f.name == "tick").unwrap();
            let narrow = matches!(tick_field.ty, IrType::U64 | IrType::I64);
            if narrow {
                writeln!(
                    out,
                    "            Event::{} {{ tick, .. }} => *tick as u32,",
                    e.name
                )
                .unwrap();
            } else {
                writeln!(out, "            Event::{} {{ tick, .. }} => *tick,", e.name).unwrap();
            }
        } else if e.fields.is_empty() {
            writeln!(out, "            Event::{} => 0,", e.name).unwrap();
        } else {
            writeln!(out, "            Event::{} {{ .. }} => 0,", e.name).unwrap();
        }
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();

    // `is_replayable()` — honour the `@replayable` annotation.
    writeln!(out, "    pub fn is_replayable(&self) -> bool {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for e in events {
        let replayable = event_is_replayable(e);
        let pat = if e.fields.is_empty() {
            format!("Event::{}", e.name)
        } else {
            format!("Event::{} {{ .. }}", e.name)
        };
        writeln!(out, "            {} => {},", pat, replayable).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();
}

fn event_is_replayable(e: &EventIR) -> bool {
    e.annotations
        .iter()
        .any(|a| a.name == "replayable")
}

/// Emit `impl engine::event::EventLike for Event { ... }`.
///
/// This is the machine-owned counterpart of the hand-written bridge in
/// `crates/engine/src/event/mod.rs`. It must be kept in sync with the
/// `EventKindId` discriminants in `crates/engine/src/cascade/handler.rs`.
/// Any time a variant is added or the `EventLike` trait changes, regenerate
/// with `cargo run --bin xtask -- compile-dsl`.
///
/// `kind()` maps each variant to its stable `EventKindId` ordinal.
/// `tick()` and `is_replayable()` delegate to the `impl Event { .. }` block
/// emitted just above this one (avoiding duplication).
/// `hash_replayable()` writes each replayable variant's fields into a
/// `sha2::Sha256` hasher in a fixed order.
pub fn emit_event_like_impl(out: &mut String, events: &[&EventIR]) {
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Lives in `engine` (not `engine_data`) to avoid the dep cycle while").unwrap();
    writeln!(out, "// `engine` retains its `engine_data` regular dep (chronicle.rs, Plan B2).").unwrap();
    writeln!(out, "// Included from `engine/src/event/mod.rs` via `mod event_like_impl;`.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use engine_data::events::Event;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl crate::event::EventLike for Event {{").unwrap();

    // ---- kind() ----
    writeln!(out, "    fn kind(&self) -> crate::cascade::EventKindId {{").unwrap();
    writeln!(out, "        use crate::cascade::EventKindId;").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for e in events {
        let pat = if e.fields.is_empty() {
            format!("Event::{}", e.name)
        } else {
            format!("Event::{} {{ .. }}", e.name)
        };
        writeln!(out, "            {} => EventKindId::{},", pat, e.name).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();

    // ---- tick() ----
    writeln!(out, "    fn tick(&self) -> u32 {{ Event::tick(self) }}").unwrap();

    // ---- is_replayable() ----
    writeln!(out, "    fn is_replayable(&self) -> bool {{ Event::is_replayable(self) }}").unwrap();

    // ---- hash_replayable() ----
    writeln!(out, "    fn hash_replayable(&self, h: &mut sha2::Sha256) {{").unwrap();
    writeln!(out, "        use sha2::Digest;").unwrap();
    writeln!(out, "        use crate::cascade::EventKindId;").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for e in events {
        let replayable = event_is_replayable(e);
        if !replayable {
            // Non-replayable: should never reach here, emit debug_assert
            let pat = if e.fields.is_empty() {
                format!("Event::{}", e.name)
            } else {
                format!("Event::{} {{ .. }}", e.name)
            };
            writeln!(out, "            {} => {{", pat).unwrap();
            writeln!(out, "                debug_assert!(false, \"{} reached replayable hash path\");", e.name).unwrap();
            writeln!(out, "            }}").unwrap();
            continue;
        }
        // Replayable: destructure all fields
        if e.fields.is_empty() {
            writeln!(out, "            Event::{} => {{", e.name).unwrap();
        } else {
            let field_names: Vec<&str> = e.fields.iter().map(|f| f.name.as_str()).collect();
            writeln!(out, "            Event::{} {{ {} }} => {{", e.name, field_names.join(", ")).unwrap();
        }
        // Write discriminant byte using EventKindId ordinal
        writeln!(out, "                h.update([EventKindId::{} as u8]);", e.name).unwrap();
        // Write each field
        for f in &e.fields {
            emit_hash_field(out, &f.name, &f.ty);
        }
        writeln!(out, "            }}").unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();
}

/// Emit the `h.update(...)` call(s) for a single field, given its name and type.
fn emit_hash_field(out: &mut String, name: &str, ty: &IrType) {
    match ty {
        // Niche ID types — call .raw() then .to_le_bytes()
        IrType::AgentId
        | IrType::ItemId
        | IrType::GroupId
        | IrType::QuestId
        | IrType::AuctionId
        | IrType::EventId
        | IrType::AbilityId => {
            writeln!(out, "                h.update({name}.raw().to_le_bytes());").unwrap();
        }
        // Vec3 — iterate over x/y/z components as f32 bits
        IrType::Vec3 => {
            writeln!(out, "                for __v in [{name}.x, {name}.y, {name}.z] {{").unwrap();
            writeln!(out, "                    h.update(__v.to_bits().to_le_bytes());").unwrap();
            writeln!(out, "                }}").unwrap();
        }
        // Floating-point — hash via bit representation
        IrType::F32 | IrType::F64 => {
            writeln!(out, "                h.update({name}.to_bits().to_le_bytes());").unwrap();
        }
        // Bool — cast to u8
        IrType::Bool => {
            writeln!(out, "                h.update([*{name} as u8]);").unwrap();
        }
        // Integer scalars — use to_le_bytes()
        IrType::U8 => {
            writeln!(out, "                h.update([*{name}]);").unwrap();
        }
        IrType::I8 => {
            writeln!(out, "                h.update([*{name} as u8]);").unwrap();
        }
        IrType::U16 | IrType::I16 | IrType::U32 | IrType::I32 | IrType::U64 | IrType::I64 => {
            writeln!(out, "                h.update({name}.to_le_bytes());").unwrap();
        }
        // Named types we handle specifically
        IrType::Named(n) => match n.as_str() {
            "QuestCategory" => {
                writeln!(out, "                h.update([*{name} as u8]);").unwrap();
            }
            "Resolution" => {
                // Resolution is a non-trivial enum with one variant carrying data.
                // Use engine_data path since the generated file lives in engine (not engine_data).
                writeln!(out, "                let (__res_tag, __min_parties) = match {name} {{").unwrap();
                writeln!(out, "                    engine_data::types::Resolution::HighestBid        => (0u8, 0u8),").unwrap();
                writeln!(out, "                    engine_data::types::Resolution::FirstAcceptable   => (1u8, 0u8),").unwrap();
                writeln!(out, "                    engine_data::types::Resolution::MutualAgreement   => (2u8, 0u8),").unwrap();
                writeln!(out, "                    engine_data::types::Resolution::Coalition {{ min_parties }} => (3u8, *min_parties),").unwrap();
                writeln!(out, "                    engine_data::types::Resolution::Majority          => (4u8, 0u8),").unwrap();
                writeln!(out, "                }};").unwrap();
                writeln!(out, "                h.update([__res_tag, __min_parties]);").unwrap();
            }
            _ => {
                // Unknown named type — emit a compile-time marker so the
                // developer adds a case above.
                writeln!(out, "                let _ = {name}; // TODO: hash Named({n}) — add a case in emit_hash_field").unwrap();
            }
        },
        // Array — iterate over elements
        IrType::Array(inner, _) => {
            writeln!(out, "                for __elem in {name}.iter() {{").unwrap();
            // Recurse; the inner emit will reference `__elem`
            emit_hash_field(out, "__elem", inner);
            writeln!(out, "                }}").unwrap();
        }
        // Optional
        IrType::Optional(inner) => {
            writeln!(out, "                h.update([{name}.is_some() as u8]);").unwrap();
            writeln!(out, "                if let Some(ref __inner) = *{name} {{").unwrap();
            emit_hash_field(out, "__inner", inner);
            writeln!(out, "                }}").unwrap();
        }
        // Catch-all: emit a placeholder
        _ => {
            writeln!(out, "                let _ = {name}; // TODO: hash {:?} — add a case in emit_hash_field", ty).unwrap();
        }
    }
}

fn is_copy(ty: &IrType) -> bool {
    match ty {
        IrType::Bool
        | IrType::I8
        | IrType::U8
        | IrType::I16
        | IrType::U16
        | IrType::I32
        | IrType::U32
        | IrType::I64
        | IrType::U64
        | IrType::F32
        | IrType::F64
        | IrType::Vec3
        | IrType::AgentId
        | IrType::ItemId
        | IrType::GroupId
        | IrType::QuestId
        | IrType::AuctionId
        | IrType::EventId
        | IrType::AbilityId => true,
        IrType::Array(inner, _) | IrType::Optional(inner) => is_copy(inner),
        IrType::Tuple(items) => items.iter().all(is_copy),
        // Engine-side named types we route: assume Copy (QuestCategory,
        // Resolution both derive Copy today). If a future addition breaks
        // this assumption, the emitted per-struct file won't compile — at
        // which point this heuristic needs to grow a lookup table.
        IrType::Named(_) => true,
        _ => false,
    }
}

fn render_type(ty: &IrType) -> String {
    match ty {
        IrType::Bool => "bool".into(),
        IrType::I8 => "i8".into(),
        IrType::U8 => "u8".into(),
        IrType::I16 => "i16".into(),
        IrType::U16 => "u16".into(),
        IrType::I32 => "i32".into(),
        IrType::U32 => "u32".into(),
        IrType::I64 => "i64".into(),
        IrType::U64 => "u64".into(),
        IrType::F32 => "f32".into(),
        IrType::F64 => "f64".into(),
        IrType::Vec3 => "Vec3".into(),
        IrType::String => "String".into(),
        IrType::AgentId => "AgentId".into(),
        IrType::ItemId => "ItemId".into(),
        IrType::GroupId => "GroupId".into(),
        IrType::QuestId => "QuestId".into(),
        IrType::AuctionId => "AuctionId".into(),
        IrType::EventId => "EventId".into(),
        IrType::AbilityId => "AbilityId".into(),
        IrType::SortedVec(inner, cap) => {
            format!("SmallVec<[{}; {}]>", render_type(inner), cap)
        }
        IrType::RingBuffer(inner, cap) => {
            format!("SmallVec<[{}; {}]>", render_type(inner), cap)
        }
        IrType::SmallVec(inner, cap) => {
            format!("SmallVec<[{}; {}]>", render_type(inner), cap)
        }
        IrType::Array(inner, cap) => format!("[{}; {}]", render_type(inner), cap),
        IrType::Optional(inner) => format!("Option<{}>", render_type(inner)),
        IrType::Tuple(items) => {
            let parts: Vec<String> = items.iter().map(render_type).collect();
            format!("({})", parts.join(", "))
        }
        IrType::List(inner) => format!("Vec<{}>", render_type(inner)),
        IrType::EntityRef(_) => "u32 /* EntityRef */".into(),
        IrType::EventRef(_) => "u32 /* EventRef */".into(),
        IrType::Enum { name, .. } => name.clone(),
        IrType::Named(n) => n.clone(),
        IrType::Unknown => "()".into(),
    }
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Annotation, Span};
    use crate::ir::{EventField, EventIR, IrType};

    fn mk_field(name: &str, ty: IrType) -> EventField {
        EventField { name: name.into(), ty, span: Span::dummy() }
    }

    fn mk_event(name: &str, fields: Vec<EventField>, ann: Vec<Annotation>) -> EventIR {
        EventIR {
            name: name.into(),
            fields,
            tags: vec![],
            annotations: ann,
            span: Span::dummy(),
        }
    }

    fn replayable_annotation() -> Annotation {
        Annotation { name: "replayable".into(), args: vec![], span: Span::dummy() }
    }

    #[test]
    fn simple_primitives() {
        let e = mk_event("Heal", vec![mk_field("amount", IrType::F32)], vec![]);
        let out = emit_event(&e, None);
        assert!(out.contains("pub struct Heal"));
        assert!(out.contains("pub amount: f32"));
        // Implicit tick synthesized as u32.
        assert!(out.contains("pub tick: u32"));
        assert!(out.contains("#[derive(Copy, Clone, Debug, PartialEq)]"));
        assert!(!out.contains("Serialize"));
        assert!(!out.contains("use crate::ids"));
    }

    #[test]
    fn with_niche_id() {
        let e = mk_event(
            "Damage",
            vec![
                mk_field("target", IrType::AgentId),
                mk_field("amount", IrType::F32),
            ],
            vec![],
        );
        let out = emit_event(&e, Some("assets/sim/events.sim"));
        assert!(out.contains("use crate::ids::AgentId;"));
        assert!(out.contains("pub target: AgentId"));
        assert!(out.contains("// GENERATED by dsl_compiler from assets/sim/events.sim."));
        // Serde has been dropped from per-struct files — no serde import.
        assert!(!out.contains("use serde"));
    }

    #[test]
    fn with_optional() {
        let e = mk_event(
            "MaybeHit",
            vec![
                mk_field("target", IrType::Optional(Box::new(IrType::AgentId))),
                mk_field("amount", IrType::F32),
            ],
            vec![],
        );
        let out = emit_event(&e, None);
        assert!(out.contains("pub target: Option<AgentId>"));
        assert!(out.contains("use crate::ids::AgentId;"));
    }

    #[test]
    fn with_array() {
        let e = mk_event(
            "MultiHit",
            vec![mk_field("targets", IrType::Array(Box::new(IrType::AgentId), 4))],
            vec![],
        );
        let out = emit_event(&e, None);
        assert!(out.contains("pub targets: [AgentId; 4]"));
        assert!(out.contains("use crate::ids::AgentId;"));
        assert!(out.contains("#[derive(Copy, Clone, Debug, PartialEq)]"));
    }

    #[test]
    fn with_string_is_not_copy() {
        let e = mk_event("Log", vec![mk_field("msg", IrType::String)], vec![]);
        let out = emit_event(&e, None);
        assert!(out.contains("pub msg: String"));
        assert!(!out.contains("Clone, Copy"));
    }

    #[test]
    fn aggregate_mod_is_alphabetical_with_struct_variants() {
        let e1 = mk_event(
            "Zebra",
            vec![mk_field("t", IrType::U64)],
            vec![replayable_annotation()],
        );
        let e2 = mk_event("Apple", vec![], vec![replayable_annotation()]);
        let out = emit_events_mod(&[e1, e2]);
        let apple = out.find("pub mod apple;").unwrap();
        let zebra = out.find("pub mod zebra;").unwrap();
        assert!(apple < zebra);
        assert!(out.contains("pub enum Event {"));
        assert!(out.contains("Apple {"));
        assert!(out.contains("Zebra {"));
        // Implicit tick appended.
        assert!(out.contains("tick: u32"));
        assert!(out.contains("pub fn tick(&self) -> u32"));
        assert!(out.contains("pub fn is_replayable(&self) -> bool"));
    }

    #[test]
    fn replayable_annotation_flips_is_replayable() {
        let e1 = mk_event("Replayable", vec![], vec![replayable_annotation()]);
        let e2 = mk_event("SideChannel", vec![], vec![]);
        let out = emit_events_mod(&[e1, e2]);
        assert!(out.contains("Event::Replayable { .. } => true"));
        assert!(out.contains("Event::SideChannel { .. } => false"));
    }

    #[test]
    fn snake_case_basic() {
        assert_eq!(snake_case("Damage"), "damage");
        assert_eq!(snake_case("AgentDied"), "agent_died");
        assert_eq!(snake_case("TransferGold"), "transfer_gold");
        assert_eq!(snake_case("SlowApplied"), "slow_applied");
    }
}
