//! WGSL emitter for `AlivePackKernel` — packs the per-agent alive bit
//! into a `u32` bitmap, one thread per output word.
//!
//! Recovered from the pre-T16 hand-written `ALIVE_PACK_WGSL` constant
//! (`crates/engine_gpu/src/alive_bitmap.rs:112` at commit `4474566c~1`)
//! and adapted to the post-T16 emitted Rust binding layout: the agents
//! buffer is now a raw `array<u32>` SoA stride (16 u32s per
//! `GpuAgentSlot`) instead of the typed `array<AgentSlot>` the old
//! WGSL declared. The alive field sits at offset 4 (in u32s) per
//! `crates/engine_gpu/src/sync_helpers.rs::GpuAgentSlot`.
//!
//! `num_words` is computed inline from `cfg.agent_cap` (the old WGSL
//! cfg carried it as a separate field; the emitted `AlivePackCfg`
//! drops it).

/// Emit the body of `engine_gpu_rules/src/alive_pack.wgsl`. Caller
/// prepends the `// GENERATED by ...` header.
///
/// The output declares the same BGL the emitted Rust side
/// (`engine_gpu_rules::alive_pack::AlivePackKernel`) builds: agents at
/// slot 0, alive_bitmap at slot 1, cfg uniform at slot 2.
pub fn emit_alive_pack_wgsl() -> String {
    String::from(
        "@group(0) @binding(0) var<storage, read>       agents:       array<u32>;\n\
@group(0) @binding(1) var<storage, read_write> alive_bitmap: array<u32>;\n\
struct AlivePackCfg { agent_cap: u32, radius_q: f32, _pad0: u32, _pad1: u32 };\n\
@group(0) @binding(2) var<uniform>             cfg:          AlivePackCfg;\n\
\n\
// GpuAgentSlot stride (16 × u32) and `alive` field offset (4 × u32).\n\
const SLOT_STRIDE_U32: u32 = 16u;\n\
const ALIVE_OFFSET_U32: u32 = 4u;\n\
\n\
@compute @workgroup_size(64)\n\
fn cs_alive_pack(@builtin(global_invocation_id) gid: vec3<u32>) {\n\
    let word_idx = gid.x;\n\
    let num_words = (cfg.agent_cap + 31u) >> 5u;\n\
    if (word_idx >= num_words) { return; }\n\
\n\
    let base_slot = word_idx * 32u;\n\
    var word: u32 = 0u;\n\
    // Scan 32 slots into a single u32. Each thread owns its word;\n\
    // non-atomic write at the end (no inter-thread contention).\n\
    for (var i: u32 = 0u; i < 32u; i = i + 1u) {\n\
        let slot = base_slot + i;\n\
        if (slot >= cfg.agent_cap) { break; }\n\
        let alive_word = agents[slot * SLOT_STRIDE_U32 + ALIVE_OFFSET_U32];\n\
        if (alive_word != 0u) {\n\
            word = word | (1u << i);\n\
        }\n\
    }\n\
    alive_bitmap[word_idx] = word;\n\
}\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_kernel_entry_point() {
        let src = emit_alive_pack_wgsl();
        assert!(src.contains("fn cs_alive_pack"));
        assert!(src.contains("@workgroup_size(64)"));
        assert!(src.contains("alive_bitmap"));
    }

    #[test]
    fn naga_parses() {
        let src = emit_alive_pack_wgsl();
        naga::front::wgsl::parse_str(&src)
            .map_err(|e| e.emit_to_string(&src))
            .expect("emit_alive_pack_wgsl produces naga-valid WGSL");
    }
}
