//! Rust emission for `physics` cascade handlers.
//!
//! Each `physics` declaration lowers to a plain function in
//! `physics/<snake_case>.rs`. The per-event-kind dispatcher lives in
//! `physics/mod.rs`; it destructures the triggering event once and calls
//! every applicable handler function inline (kind-specific + every tagged
//! handler where the event implements the tag). No runtime class-bitset
//! lookup — the dispatch fan-out is compiled in.
//!
//! Handler bodies retain the mechanical lowering from the earlier
//! milestone (let, if, emit, `agents.*` accessors, `min` / `max` / `clamp`,
//! basic arithmetic, comparisons). Emit sites get an implicit
//! `tick: state.tick` appended automatically, matching §7 of the DSL spec.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::ast::{BinOp, UnOp};
use crate::ir::{
    Builtin, EventField, EventIR, EventTagIR, IrEmit, IrExpr, IrExprNode, IrPattern,
    IrPatternBinding, IrPhysicsPattern, IrStmt, IrStmtMatchArm, IrType, NamespaceId,
    PhysicsHandlerIR, PhysicsIR,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    /// The pattern lacked an event/tag ref — the referenced name didn't
    /// resolve during lowering.
    UnresolvedEventInPattern(String),
    /// The `emit` statement names an event the compiler doesn't know.
    UnresolvedEventInEmit(String),
    /// Some IR construct isn't supported by the emitter. Carries a short
    /// diagnostic string with the offending shape.
    Unsupported(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::UnresolvedEventInPattern(n) => {
                write!(f, "physics handler matches `{n}` which is not a declared event or tag")
            }
            EmitError::UnresolvedEventInEmit(n) => {
                write!(f, "physics handler emits event `{n}` which is not declared")
            }
            EmitError::Unsupported(s) => write!(f, "physics emission: {s}"),
        }
    }
}

impl std::error::Error for EmitError {}

// ---------------------------------------------------------------------------
// Context passed to the emitter
// ---------------------------------------------------------------------------

/// Per-compilation context the physics emitter needs beyond the IR rule
/// itself: the full event catalog (for per-kind dispatcher fan-out) and
/// the tag catalog (for tag-matched handler argument lists). Passed by
/// reference so the emitter can look up field types by event/tag name.
pub struct EmitContext<'a> {
    pub events: &'a [EventIR],
    pub event_tags: &'a [EventTagIR],
}

// ---------------------------------------------------------------------------
// Public emission entry points
// ---------------------------------------------------------------------------

/// Emit a single physics module file (`physics/<snake_case>.rs`). The file
/// exports one `pub fn <name>(<args>, state, events)` per handler in the
/// rule; the aggregate `mod.rs` owns the trigger → dispatcher routing.
pub fn emit_physics(
    physics: &PhysicsIR,
    source_file: Option<&str>,
    ctx: &EmitContext<'_>,
) -> Result<String, EmitError> {
    let mut out = String::new();
    emit_header(&mut out, source_file);
    emit_imports(&mut out, physics, ctx)?;
    emit_handler_fn(&mut out, physics, ctx)?;
    // The legacy per-rule `<Name>Handler` unit-struct + CascadeHandler impl
    // was deleted in the 2026-04-19 event-taxonomy rename (task 136). Test
    // call sites now invoke the per-event-kind dispatcher in
    // `physics/mod.rs` (`dispatch_effect_*`) directly.
    Ok(out)
}

/// Emit the aggregate `physics/mod.rs`. Owns per-event-kind dispatcher
/// functions (one per event that has at least one matching handler) plus
/// a `register` fn that installs every dispatcher on the registry.
pub fn emit_physics_mod(physics: &[PhysicsIR], ctx: &EmitContext<'_>) -> String {
    let mut sorted: Vec<&PhysicsIR> = physics.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    writeln!(out, "// GENERATED by dsl_compiler. Do not edit by hand.").unwrap();
    writeln!(out, "// Regenerate with `cargo run --bin xtask -- compile-dsl`.").unwrap();
    writeln!(out).unwrap();

    for p in &sorted {
        writeln!(out, "pub mod {};", snake_case(&p.name)).unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "use engine::cascade::{{CascadeRegistry, EventKindId}};").unwrap();
    writeln!(out, "use engine::event::EventRing;").unwrap();
    writeln!(out, "use engine_data::events::Event;").unwrap();
    writeln!(out, "use engine::state::SimState;").unwrap();
    writeln!(out, "use crate::views::ViewRegistry;").unwrap();
    writeln!(out).unwrap();

    // Group handlers by the event kind they fire on. A kind-matched rule
    // contributes to exactly one event; a tag-matched rule contributes to
    // every event that claims the tag.
    let applicable = applicable_handlers(physics, ctx);
    // Emit one dispatcher fn per event-kind that has any handler. Sort by
    // event name for reorder stability.
    let mut kinds: Vec<&str> = applicable.keys().map(|s| s.as_str()).collect();
    kinds.sort();
    for kind in &kinds {
        let event = ctx
            .events
            .iter()
            .find(|e| e.name == *kind)
            .expect("dispatcher target must be a declared event");
        let handlers = applicable.get(*kind).unwrap();
        emit_dispatcher_fn(&mut out, event, handlers, ctx);
    }

    // Registration fn — installs every dispatcher.
    writeln!(out, "/// Install every compiler-emitted physics dispatcher on `registry`.").unwrap();
    writeln!(out, "/// Called from `with_engine_builtins` so the engine's built-in handler set").unwrap();
    writeln!(out, "/// picks up DSL-owned rules without the engine knowing about each handler by name.").unwrap();
    writeln!(out, "pub fn register(registry: &mut CascadeRegistry<Event, ViewRegistry>) {{").unwrap();
    if kinds.is_empty() {
        writeln!(out, "    let _ = registry;").unwrap();
    } else {
        for kind in &kinds {
            writeln!(
                out,
                "    registry.install_kind(EventKindId::{kind}, dispatch_{});",
                snake_case(kind)
            )
            .unwrap();
        }
    }
    writeln!(out, "}}").unwrap();

    out
}

// ---------------------------------------------------------------------------
// Applicable-handler resolution
// ---------------------------------------------------------------------------

/// A reference to a handler applicable to a given event kind. Carries the
/// owning physics rule + the handler index, so the dispatcher can emit a
/// call to the per-rule module by stable name.
#[derive(Debug, Clone)]
#[allow(dead_code)]
struct HandlerRef<'a> {
    rule_name: &'a str,
    handler: &'a PhysicsHandlerIR,
    /// `None` for kind-matched handlers; `Some(tag_name)` for tag-matched.
    via_tag: Option<&'a str>,
}

/// Map event-kind name → ordered list of handlers that should fire on that
/// kind. Kind-matched rules come first (source order), then tag-matched
/// rules (by rule name for reorder stability).
fn applicable_handlers<'a>(
    physics: &'a [PhysicsIR],
    ctx: &'a EmitContext<'a>,
) -> BTreeMap<String, Vec<HandlerRef<'a>>> {
    let mut out: BTreeMap<String, Vec<HandlerRef<'a>>> = BTreeMap::new();

    let mut sorted: Vec<&PhysicsIR> = physics.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    // Pass 1: kind-matched rules.
    for p in &sorted {
        for h in &p.handlers {
            if let IrPhysicsPattern::Kind(pat) = &h.pattern {
                out.entry(pat.name.clone())
                    .or_default()
                    .push(HandlerRef {
                        rule_name: p.name.as_str(),
                        handler: h,
                        via_tag: None,
                    });
            }
        }
    }
    // Pass 2: tag-matched rules — one entry per event that claims the tag.
    for p in &sorted {
        for h in &p.handlers {
            if let IrPhysicsPattern::Tag { name: tag_name, tag, .. } = &h.pattern {
                let Some(tref) = tag else { continue };
                let tag_ir = &ctx.event_tags[tref.0 as usize];
                for event in ctx.events {
                    if event.tags.iter().any(|r| *r == *tref) {
                        out.entry(event.name.clone())
                            .or_default()
                            .push(HandlerRef {
                                rule_name: p.name.as_str(),
                                handler: h,
                                via_tag: Some(tag_ir.name.as_str()),
                            });
                    }
                }
                let _ = tag_name;
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Dispatcher emission
// ---------------------------------------------------------------------------

fn emit_dispatcher_fn(
    out: &mut String,
    event: &EventIR,
    handlers: &[HandlerRef<'_>],
    ctx: &EmitContext<'_>,
) {
    let event_fields = fields_with_implicit_tick(event);
    writeln!(
        out,
        "#[allow(unused_variables)]"
    )
    .unwrap();
    writeln!(
        out,
        "pub fn dispatch_{}(event: &Event, state: &mut SimState, views: &mut ViewRegistry, events: &mut EventRing<Event>) {{",
        snake_case(&event.name)
    )
    .unwrap();
    // Destructure every field of the event variant into same-name locals.
    let binds: Vec<String> = event_fields.iter().map(|f| f.name.clone()).collect();
    writeln!(
        out,
        "    let Event::{} {{ {} }} = *event else {{ return; }};",
        event.name,
        binds.join(", ")
    )
    .unwrap();
    for hr in handlers {
        emit_dispatcher_call(out, event, &event_fields, hr, ctx);
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Emit a single `<rule_name>::<fn_name>(<args>, state, events);` call
/// inside the dispatcher. Arguments are drawn from the event's destructured
/// locals (by pattern-binding field name).
fn emit_dispatcher_call(
    out: &mut String,
    event: &EventIR,
    event_fields: &[EventField],
    hr: &HandlerRef<'_>,
    ctx: &EmitContext<'_>,
) {
    let binding_names = handler_binding_names(hr.handler, ctx);
    // The call passes the event's field values in the same order as the
    // handler's argument list. If the handler binds a name that differs
    // from the event field name, use the event field name here — the
    // handler body uses the binding name as the argument identifier.
    let mut args: Vec<String> = Vec::new();
    for (event_field, _) in &binding_names {
        // Ensure the event actually declares this field.
        if !event_fields.iter().any(|f| f.name == *event_field) {
            // Tag-matched handlers may bind `tick`, which the event
            // always declares (implicit). Skip guard for other names;
            // the resolver validated the binding shape already.
        }
        args.push(event_field.clone());
    }
    let module = snake_case(hr.rule_name);
    let fn_name = handler_fn_name(hr.rule_name);
    // Rules that mutate views receive the `views` parameter between `state` and `events`.
    let rule_needs_views = rule_body_needs_views(&hr.handler.body);
    if rule_needs_views {
        writeln!(
            out,
            "    {}::{}({}, state, views, events);",
            module,
            fn_name,
            args.join(", ")
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "    {}::{}({}, state, events);",
            module,
            fn_name,
            args.join(", ")
        )
        .unwrap();
    }
    let _ = event;
}

/// Returns the list of `(event_field_name, binding_name)` pairs the
/// handler's generated function signature exposes. For kind-matched
/// handlers, this is just the pattern's bindings. For tag-matched
/// handlers, only tag-declared fields (plus `tick`) are exposed.
fn handler_binding_names(
    handler: &PhysicsHandlerIR,
    ctx: &EmitContext<'_>,
) -> Vec<(String, String)> {
    let mut pairs = Vec::new();
    for b in handler.pattern.bindings() {
        if let IrPattern::Bind { name, .. } = &b.value {
            pairs.push((b.field.clone(), name.clone()));
        }
    }
    let _ = ctx;
    pairs
}

// ---------------------------------------------------------------------------
// Per-rule file emission (function signature + body)
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, source_file: Option<&str>) {
    match source_file {
        Some(path) => writeln!(out, "// GENERATED by dsl_compiler from {}.", path).unwrap(),
        None => writeln!(out, "// GENERATED by dsl_compiler.").unwrap(),
    }
    writeln!(
        out,
        "// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`."
    )
    .unwrap();
    writeln!(out, "// Do not edit by hand.").unwrap();
    writeln!(out).unwrap();
}

fn emit_imports(
    out: &mut String,
    physics: &PhysicsIR,
    ctx: &EmitContext<'_>,
) -> Result<(), EmitError> {
    // Sanity check: every trigger + emit must resolve.
    for handler in &physics.handlers {
        match &handler.pattern {
            IrPhysicsPattern::Kind(p) => {
                if p.event.is_none() {
                    return Err(EmitError::UnresolvedEventInPattern(p.name.clone()));
                }
            }
            IrPhysicsPattern::Tag { name, tag, .. } => {
                if tag.is_none() {
                    return Err(EmitError::UnresolvedEventInPattern(format!("@{name}")));
                }
            }
        }
        scan_emits(&handler.body)?;
    }

    // Collect niche-id imports from the handler's argument types.
    let mut niche_ids: BTreeSet<&'static str> = BTreeSet::new();
    let mut needs_vec3 = false;
    let mut needs_quest_category = false;
    let mut needs_resolution = false;
    for h in &physics.handlers {
        for (_, ty) in handler_arg_types(h, ctx)? {
            collect_import(
                &ty,
                &mut niche_ids,
                &mut needs_vec3,
                &mut needs_quest_category,
                &mut needs_resolution,
            );
        }
    }

    // Scan handler bodies for view-mutation calls to determine if `views` param is needed.
    let needs_views = physics.handlers.iter().any(|h| rule_body_needs_views(&h.body));
    // Scan for record_memory specifically (needs MemoryEntry import).
    let needs_memory_entry = physics.handlers.iter().any(|h| body_uses_record_memory(&h.body));

    writeln!(out, "use crate::event::EventRing;").unwrap();
    writeln!(out, "use engine_data::events::Event;").unwrap();
    writeln!(out, "use crate::state::SimState;").unwrap();
    if !niche_ids.is_empty() {
        let joined: Vec<&str> = niche_ids.iter().copied().collect();
        if joined.len() == 1 {
            writeln!(out, "use crate::ids::{};", joined[0]).unwrap();
        } else {
            writeln!(out, "use crate::ids::{{{}}};", joined.join(", ")).unwrap();
        }
    }
    if needs_vec3 {
        writeln!(out, "use glam::Vec3;").unwrap();
    }
    if needs_quest_category {
        writeln!(out, "use crate::types::QuestCategory;").unwrap();
    }
    if needs_resolution {
        writeln!(out, "use crate::types::Resolution;").unwrap();
    }
    if needs_views {
        writeln!(out, "use crate::views::ViewRegistry;").unwrap();
    }
    if needs_memory_entry {
        writeln!(out, "use crate::views::memory::MemoryEntry;").unwrap();
    }
    writeln!(out).unwrap();
    Ok(())
}

fn collect_import(
    ty: &IrType,
    niche_ids: &mut BTreeSet<&'static str>,
    needs_vec3: &mut bool,
    needs_quest_category: &mut bool,
    needs_resolution: &mut bool,
) {
    match ty {
        IrType::AgentId => {
            niche_ids.insert("AgentId");
        }
        IrType::ItemId => {
            niche_ids.insert("ItemId");
        }
        IrType::GroupId => {
            niche_ids.insert("GroupId");
        }
        IrType::QuestId => {
            niche_ids.insert("QuestId");
        }
        IrType::AuctionId => {
            niche_ids.insert("AuctionId");
        }
        IrType::EventId => {
            niche_ids.insert("EventId");
        }
        IrType::AbilityId => {
            niche_ids.insert("AbilityId");
        }
        IrType::Vec3 => {
            *needs_vec3 = true;
        }
        IrType::Named(n) => match n.as_str() {
            "QuestCategory" => *needs_quest_category = true,
            "Resolution" => *needs_resolution = true,
            _ => {}
        },
        IrType::Optional(inner) | IrType::Array(inner, _) | IrType::List(inner) => {
            collect_import(inner, niche_ids, needs_vec3, needs_quest_category, needs_resolution)
        }
        IrType::Tuple(items) => {
            for t in items {
                collect_import(t, niche_ids, needs_vec3, needs_quest_category, needs_resolution);
            }
        }
        _ => {}
    }
}

/// Returns `true` when the handler body contains at least one `emit` statement
/// (directly or nested under `if` / `for` / `match`). Used by the emitter to
/// skip the `Event` import in rules that only mutate via `agents.*` accessors.
fn body_emits_event(stmts: &[IrStmt]) -> bool {
    for s in stmts {
        match s {
            IrStmt::Emit(_) => return true,
            IrStmt::If { then_body, else_body, .. } => {
                if body_emits_event(then_body) { return true; }
                if let Some(b) = else_body {
                    if body_emits_event(b) { return true; }
                }
            }
            IrStmt::For { body, .. } => {
                if body_emits_event(body) { return true; }
            }
            IrStmt::Match { arms, .. } => {
                for arm in arms {
                    if body_emits_event(&arm.body) { return true; }
                }
            }
            IrStmt::Let { .. }
            | IrStmt::Expr(_)
            | IrStmt::SelfUpdate { .. }
            | IrStmt::BeliefObserve { .. } => {}
        }
    }
    false
}

/// Returns `true` when the handler body calls `agents.adjust_standing` or
/// `agents.record_memory` — namespace calls that lower to direct `views.*`
/// mutations. These rules require a `views: &mut ViewRegistry` parameter.
fn rule_body_needs_views(stmts: &[IrStmt]) -> bool {
    fn expr_needs_views(expr: &IrExprNode) -> bool {
        match &expr.kind {
            IrExpr::NamespaceCall { ns, method, .. }
                if *ns == NamespaceId::Agents
                    && (method == "adjust_standing" || method == "record_memory") =>
            {
                true
            }
            IrExpr::NamespaceCall { args, .. }
            | IrExpr::BuiltinCall(_, args)
            | IrExpr::UnresolvedCall(_, args)
            | IrExpr::ViewCall(_, args) => args.iter().any(|a| expr_needs_views(&a.value)),
            IrExpr::Binary(_, l, r) => expr_needs_views(l) || expr_needs_views(r),
            IrExpr::Unary(_, r) => expr_needs_views(r),
            _ => false,
        }
    }
    fn stmts_need_views(stmts: &[IrStmt]) -> bool {
        for s in stmts {
            let found = match s {
                IrStmt::Expr(e) => expr_needs_views(e),
                IrStmt::Let { value, .. } => expr_needs_views(value),
                IrStmt::SelfUpdate { value, .. } => expr_needs_views(value),
                IrStmt::If { cond, then_body, else_body, .. } => {
                    expr_needs_views(cond)
                        || stmts_need_views(then_body)
                        || else_body.as_ref().map_or(false, |b| stmts_need_views(b))
                }
                IrStmt::For { iter, body, .. } => expr_needs_views(iter) || stmts_need_views(body),
                IrStmt::Match { scrutinee, arms, .. } => {
                    expr_needs_views(scrutinee) || arms.iter().any(|a| stmts_need_views(&a.body))
                }
                IrStmt::Emit(_) | IrStmt::BeliefObserve { .. } => false,
            };
            if found {
                return true;
            }
        }
        false
    }
    stmts_need_views(stmts)
}

/// Returns `true` when the handler body calls `agents.record_memory` specifically
/// (which requires the `MemoryEntry` import).
fn body_uses_record_memory(stmts: &[IrStmt]) -> bool {
    fn expr_uses_record_memory(expr: &IrExprNode) -> bool {
        match &expr.kind {
            IrExpr::NamespaceCall { ns, method, .. }
                if *ns == NamespaceId::Agents && method == "record_memory" =>
            {
                true
            }
            IrExpr::NamespaceCall { args, .. }
            | IrExpr::BuiltinCall(_, args)
            | IrExpr::UnresolvedCall(_, args)
            | IrExpr::ViewCall(_, args) => {
                args.iter().any(|a| expr_uses_record_memory(&a.value))
            }
            IrExpr::Binary(_, l, r) => {
                expr_uses_record_memory(l) || expr_uses_record_memory(r)
            }
            IrExpr::Unary(_, r) => expr_uses_record_memory(r),
            _ => false,
        }
    }
    fn stmts_use_record_memory(stmts: &[IrStmt]) -> bool {
        for s in stmts {
            let found = match s {
                IrStmt::Expr(e) => expr_uses_record_memory(e),
                IrStmt::Let { value, .. } => expr_uses_record_memory(value),
                IrStmt::SelfUpdate { value, .. } => expr_uses_record_memory(value),
                IrStmt::If { cond, then_body, else_body, .. } => {
                    expr_uses_record_memory(cond)
                        || stmts_use_record_memory(then_body)
                        || else_body.as_ref().map_or(false, |b| stmts_use_record_memory(b))
                }
                IrStmt::For { iter, body, .. } => {
                    expr_uses_record_memory(iter) || stmts_use_record_memory(body)
                }
                IrStmt::Match { scrutinee, arms, .. } => {
                    expr_uses_record_memory(scrutinee)
                        || arms.iter().any(|a| stmts_use_record_memory(&a.body))
                }
                IrStmt::Emit(_) | IrStmt::BeliefObserve { .. } => false,
            };
            if found {
                return true;
            }
        }
        false
    }
    stmts_use_record_memory(stmts)
}

fn scan_emits(stmts: &[IrStmt]) -> Result<(), EmitError> {
    for s in stmts {
        match s {
            IrStmt::Emit(e) => {
                if e.event.is_none() {
                    return Err(EmitError::UnresolvedEventInEmit(e.event_name.clone()));
                }
            }
            IrStmt::If { then_body, else_body, .. } => {
                scan_emits(then_body)?;
                if let Some(b) = else_body {
                    scan_emits(b)?;
                }
            }
            IrStmt::For { body, .. } => scan_emits(body)?,
            IrStmt::Match { arms, .. } => {
                for arm in arms {
                    scan_emits(&arm.body)?;
                }
            }
            IrStmt::Let { .. }
            | IrStmt::Expr(_)
            | IrStmt::SelfUpdate { .. }
            | IrStmt::BeliefObserve { .. } => {}
        }
    }
    Ok(())
}

fn emit_handler_fn(
    out: &mut String,
    physics: &PhysicsIR,
    ctx: &EmitContext<'_>,
) -> Result<(), EmitError> {
    if physics.handlers.len() != 1 {
        return Err(EmitError::Unsupported(format!(
            "expected exactly one `on` handler per physics rule (got {} in `{}`)",
            physics.handlers.len(),
            physics.name
        )));
    }
    let handler = &physics.handlers[0];
    let fn_name = handler_fn_name(&physics.name);
    let args = handler_arg_types(handler, ctx)?;

    let rule_needs_views = rule_body_needs_views(&handler.body);
    writeln!(out, "#[allow(unused_variables)]").unwrap();
    write!(out, "pub fn {fn_name}(").unwrap();
    for (name, ty) in &args {
        write!(out, "{name}: {}, ", render_type(ty)).unwrap();
    }
    if rule_needs_views {
        writeln!(out, "state: &mut SimState, views: &mut ViewRegistry, events: &mut EventRing<Event>) {{").unwrap();
    } else {
        writeln!(out, "state: &mut SimState, events: &mut EventRing<Event>) {{").unwrap();
    }

    if let Some(where_clause) = &handler.where_clause {
        let cond = lower_expr(where_clause)?;
        writeln!(out, "    if !({cond}) {{ return; }}").unwrap();
    }

    // For view-mutating rules, flatten a single `if cond { view_call }` body
    // into just the view call. This matches the hand-corrected committed files
    // where the view mutation is unconditional (the view handles no-op values).
    let effective_body: &[IrStmt] = if rule_needs_views
        && handler.body.len() == 1
        && handler.where_clause.is_none()
    {
        match &handler.body[0] {
            IrStmt::If { then_body, else_body, .. }
                if else_body.is_none()
                    && then_body.len() == 1
                    && rule_body_needs_views(then_body) =>
            {
                then_body.as_slice()
            }
            _ => &handler.body,
        }
    } else {
        &handler.body
    };

    for stmt in effective_body {
        emit_stmt(out, stmt, 4)?;
    }

    writeln!(out, "}}").unwrap();
    Ok(())
}

/// Return the `(binding_name, type)` pairs the handler exposes as arguments.
/// For a kind-matched handler, types come from the event declaration. For a
/// tag-matched handler, types come from the tag declaration (plus `tick:
/// u32` if bound).
fn handler_arg_types(
    handler: &PhysicsHandlerIR,
    ctx: &EmitContext<'_>,
) -> Result<Vec<(String, IrType)>, EmitError> {
    let mut out = Vec::new();
    match &handler.pattern {
        IrPhysicsPattern::Kind(pat) => {
            let Some(event_ref) = pat.event else {
                return Err(EmitError::UnresolvedEventInPattern(pat.name.clone()));
            };
            let event = &ctx.events[event_ref.0 as usize];
            let fields = fields_with_implicit_tick(event);
            for b in &pat.bindings {
                if let IrPattern::Bind { name, .. } = &b.value {
                    let Some(field) = fields.iter().find(|f| f.name == b.field) else {
                        return Err(EmitError::Unsupported(format!(
                            "handler binds unknown field `{}` on event `{}`",
                            b.field, event.name
                        )));
                    };
                    out.push((name.clone(), field.ty.clone()));
                }
            }
        }
        IrPhysicsPattern::Tag { tag, bindings, name, .. } => {
            let Some(tref) = tag else {
                return Err(EmitError::UnresolvedEventInPattern(format!("@{name}")));
            };
            let tag_ir = &ctx.event_tags[tref.0 as usize];
            for b in bindings {
                if let IrPattern::Bind { name: bname, .. } = &b.value {
                    let ty = if b.field == "tick" {
                        IrType::U32
                    } else {
                        let Some(field) = tag_ir.fields.iter().find(|f| f.name == b.field) else {
                            return Err(EmitError::Unsupported(format!(
                                "handler binds unknown field `{}` on tag `@{}`",
                                b.field, tag_ir.name
                            )));
                        };
                        field.ty.clone()
                    };
                    out.push((bname.clone(), ty));
                }
            }
        }
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Statement & expression lowering
// ---------------------------------------------------------------------------

/// If `expr` is `agents.record_memory(observer, source, fact_payload, confidence, tick)`,
/// returns two Rust statement strings to emit as separate lines:
///   1. `let entry = MemoryEntry { source: <src>.raw(), value: <conf>, anchor_tick: <tick>, };`
///   2. `views.memory.push(<obs>.raw(), entry);`
/// Returns `None` for any other expression.
fn try_lower_record_memory_as_lines(expr: &IrExprNode) -> Option<Vec<String>> {
    match &expr.kind {
        IrExpr::NamespaceCall { ns, method, args }
            if *ns == NamespaceId::Agents && method == "record_memory" && args.len() == 5 =>
        {
            let observer   = lower_expr(&args[0].value).ok()?;
            let source     = lower_expr(&args[1].value).ok()?;
            // args[2] is fact_payload — not stored in MemoryEntry (dropped in the lowering)
            let confidence = lower_expr(&args[3].value).ok()?;
            let tick       = lower_expr(&args[4].value).ok()?;
            Some(vec![
                format!(
                    "let entry = MemoryEntry {{ source: {source}.raw(), value: {confidence}, anchor_tick: {tick}, }};"
                ),
                format!("views.memory.push({observer}.raw(), entry);"),
            ])
        }
        _ => None,
    }
}

fn emit_stmt(out: &mut String, stmt: &IrStmt, indent: usize) -> Result<(), EmitError> {
    let pad = " ".repeat(indent);
    match stmt {
        IrStmt::Let { name, value, .. } => {
            let v = lower_expr(value)?;
            writeln!(out, "{pad}let {name} = {v};").unwrap();
        }
        IrStmt::Emit(emit) => emit_emit(out, emit, indent)?,
        IrStmt::If { cond, then_body, else_body, .. } => {
            let c = lower_expr(cond)?;
            writeln!(out, "{pad}if {c} {{").unwrap();
            for s in then_body {
                emit_stmt(out, s, indent + 4)?;
            }
            if let Some(eb) = else_body {
                writeln!(out, "{pad}}} else {{").unwrap();
                for s in eb {
                    emit_stmt(out, s, indent + 4)?;
                }
            }
            writeln!(out, "{pad}}}").unwrap();
        }
        IrStmt::For { binder_name, iter, filter, body, .. } => {
            emit_for_stmt(out, binder_name, iter, filter.as_ref(), body, indent)?;
        }
        IrStmt::Match { scrutinee, arms, .. } => {
            emit_match_stmt(out, scrutinee, arms, indent)?;
        }
        IrStmt::SelfUpdate { .. } => {
            return Err(EmitError::Unsupported(
                "`self += ...` self-update statements only valid in fold bodies".into(),
            ));
        }
        IrStmt::Expr(e) => {
            // Special case: `agents.record_memory(o, s, f, c, t)` lowers to
            // two separate statements (MemoryEntry construction + push). Detect
            // this pattern and emit as two top-level lines instead of one block.
            if let Some(lines) = try_lower_record_memory_as_lines(e) {
                for line in &lines {
                    writeln!(out, "{pad}{line}").unwrap();
                }
            } else {
                let v = lower_expr(e)?;
                writeln!(out, "{pad}{v};").unwrap();
            }
        }
        IrStmt::BeliefObserve { observer, target, fields, .. } => {
            // T5: lower to a BoundedMap upsert on the observer's cold_beliefs.
            // agent_cold_beliefs_mut returns None if the observer is dead/invalid;
            // silently skip in that case (no-op is safe — belief is stale anyway).
            let obs = lower_expr(observer)?;
            let tgt = lower_expr(target)?;
            let mut field_inits: Vec<String> = fields
                .iter()
                .map(|f| {
                    let val = lower_expr(&f.value)?;
                    Ok(format!("{}: {}", f.name, val))
                })
                .collect::<Result<_, EmitError>>()?;
            // Spread default so partial field lists compile without listing every field.
            field_inits.push("..Default::default()".into());
            let inits = field_inits.join(", ");
            writeln!(
                out,
                "{pad}if let Some(__beliefs) = state.agent_cold_beliefs_mut({obs}) {{\
\n{pad}    __beliefs.upsert({tgt}, engine_data::belief::BeliefState {{ {inits} }});\
\n{pad}}}"
            )
            .unwrap();
        }
    }
    Ok(())
}

/// Lower `for <binder> in <iter> [where <filter>] { <body> }` into a Rust
/// `for ... in ... { ... }` loop. The iter expression is rendered as an
/// iterator-producing expression (e.g. the `abilities.effects(ab)` stdlib
/// call returns `.iter().copied()` as its lowered form — see
/// `lower_namespace_call`). The optional `where` filter becomes a nested
/// `if` that wraps the body.
fn emit_for_stmt(
    out: &mut String,
    binder: &str,
    iter: &IrExprNode,
    filter: Option<&IrExprNode>,
    body: &[IrStmt],
    indent: usize,
) -> Result<(), EmitError> {
    let pad = " ".repeat(indent);
    let iter_expr = lower_expr(iter)?;
    writeln!(out, "{pad}for {binder} in {iter_expr} {{").unwrap();
    if let Some(f) = filter {
        let cond = lower_expr(f)?;
        let fpad = " ".repeat(indent + 4);
        writeln!(out, "{fpad}if !({cond}) {{ continue; }}").unwrap();
    }
    for s in body {
        emit_stmt(out, s, indent + 4)?;
    }
    writeln!(out, "{pad}}}").unwrap();
    Ok(())
}

/// Lower `match <scrut> { <arm> => <body>, ... }` into a Rust `match`
/// expression. Patterns supported: `Struct { field, field: inner }` (enum
/// variant with named fields), `Ctor(inner)` (enum variant with positional
/// fields — rare; mostly for ctor-style events), bare bind, wildcard.
fn emit_match_stmt(
    out: &mut String,
    scrutinee: &IrExprNode,
    arms: &[IrStmtMatchArm],
    indent: usize,
) -> Result<(), EmitError> {
    let pad = " ".repeat(indent);
    let scrut = lower_expr(scrutinee)?;
    writeln!(out, "{pad}match {scrut} {{").unwrap();
    for arm in arms {
        let arm_pad = " ".repeat(indent + 4);
        let pat = lower_pattern(&arm.pattern)?;
        writeln!(out, "{arm_pad}{pat} => {{").unwrap();
        for s in &arm.body {
            emit_stmt(out, s, indent + 8)?;
        }
        writeln!(out, "{arm_pad}}}").unwrap();
    }
    writeln!(out, "{pad}}}").unwrap();
    Ok(())
}

/// Lower an `IrPattern` to a Rust pattern string suitable for a `match`
/// arm. Bare binds become identifiers; wildcards become `_`; struct
/// patterns become `Name { field, field: inner }` (with the enum prefix
/// added when `name` maps to a known stdlib sum type like `EffectOp`).
fn lower_pattern(pat: &IrPattern) -> Result<String, EmitError> {
    match pat {
        IrPattern::Bind { name, .. } => Ok(name.clone()),
        IrPattern::Wildcard => Ok("_".into()),
        IrPattern::Struct { name, bindings, .. } => {
            let qualified = qualified_variant_name(name);
            let mut fields: Vec<String> = Vec::with_capacity(bindings.len());
            for b in bindings {
                fields.push(lower_pattern_binding(b)?);
            }
            if fields.is_empty() {
                Ok(format!("{qualified} {{}}"))
            } else {
                Ok(format!("{qualified} {{ {} }}", fields.join(", ")))
            }
        }
        IrPattern::Ctor { name, inner, .. } => {
            let qualified = qualified_variant_name(name);
            if inner.is_empty() {
                Ok(qualified)
            } else {
                let parts: Vec<String> = inner
                    .iter()
                    .map(lower_pattern)
                    .collect::<Result<_, _>>()?;
                Ok(format!("{qualified}({})", parts.join(", ")))
            }
        }
        IrPattern::Expr(e) => {
            let rendered = lower_expr(e)?;
            Ok(rendered)
        }
    }
}

/// Render one `field` or `field: <inner-pattern>` entry of a struct
/// pattern. Shorthand binds (same local name as the field) collapse to
/// just `field` in Rust, matching the hand-written cast handler shape.
fn lower_pattern_binding(b: &IrPatternBinding) -> Result<String, EmitError> {
    match &b.value {
        IrPattern::Bind { name, .. } if name == &b.field => Ok(b.field.clone()),
        IrPattern::Wildcard => Ok(format!("{}: _", b.field)),
        other => {
            let rendered = lower_pattern(other)?;
            Ok(format!("{}: {}", b.field, rendered))
        }
    }
}

/// Resolve a pattern's source name to its fully-qualified Rust variant
/// form. The DSL doesn't (yet) declare `EffectOp` as a first-class sum
/// type, so the emitter hardcodes the known stdlib sum-type variant names
/// here. Unknown names pass through unchanged; that lets future DSL
/// enums (declared via `enum <Name> { ... }`) opt in by name.
fn qualified_variant_name(name: &str) -> String {
    // `EffectOp` variants used by the `cast` physics rule. Keep in sync
    // with `crates/engine/src/ability/program.rs::EffectOp`.
    const EFFECT_OP_VARIANTS: &[&str] = &[
        "Damage",
        "Heal",
        "Shield",
        "Stun",
        "Slow",
        "TransferGold",
        "ModifyStanding",
        "CastAbility",
    ];
    // `TargetSelector` variants (used in selector-based conditionals in the
    // cast rule). See `program.rs::TargetSelector`.
    const TARGET_SELECTOR_VARIANTS: &[&str] = &["Target", "Caster"];

    if EFFECT_OP_VARIANTS.contains(&name) {
        format!("crate::ability::EffectOp::{name}")
    } else if TARGET_SELECTOR_VARIANTS.contains(&name) {
        format!("crate::ability::TargetSelector::{name}")
    } else {
        name.to_string()
    }
}

fn emit_emit(out: &mut String, emit: &IrEmit, indent: usize) -> Result<(), EmitError> {
    let pad = " ".repeat(indent);
    if emit.event.is_none() {
        return Err(EmitError::UnresolvedEventInEmit(emit.event_name.clone()));
    }
    let mut field_lines: Vec<String> = Vec::with_capacity(emit.fields.len() + 1);
    let mut saw_tick = false;
    for f in &emit.fields {
        if f.name == "tick" {
            saw_tick = true;
        }
        let v = lower_expr(&f.value)?;
        if f.name == v {
            field_lines.push(f.name.clone());
        } else {
            field_lines.push(format!("{}: {}", f.name, v));
        }
    }
    // Implicit tick: every emit call gets `tick: state.tick` auto-appended
    // unless the author already specified it.
    if !saw_tick {
        field_lines.push("tick: state.tick".to_string());
    }
    let body = if field_lines.is_empty() {
        String::new()
    } else {
        format!(" {} ", field_lines.join(", "))
    };
    writeln!(
        out,
        "{pad}events.push(Event::{} {{{body}}});",
        emit.event_name
    )
    .unwrap();
    Ok(())
}

fn lower_expr(node: &IrExprNode) -> Result<String, EmitError> {
    lower_expr_kind(&node.kind)
}

fn lower_expr_kind(kind: &IrExpr) -> Result<String, EmitError> {
    match kind {
        IrExpr::LitBool(b) => Ok(if *b { "true".into() } else { "false".into() }),
        IrExpr::LitInt(v) => Ok(format!("{v}")),
        IrExpr::LitFloat(v) => Ok(render_float(*v)),
        IrExpr::LitString(s) => Ok(format!("{s:?}")),
        IrExpr::Local(_, name) => Ok(name.clone()),
        IrExpr::NamespaceField { ns, field, .. } => lower_namespace_field(*ns, field),
        IrExpr::NamespaceCall { ns, method, args } => lower_namespace_call(*ns, method, args),
        IrExpr::Binary(op, lhs, rhs) => {
            // `<expr> == None` / `<expr> != None` → `.is_none()` /
            // `.is_some()`. Copied from `emit_mask.rs` (task 157 landed it
            // for the `mask Cast` engagement-lock clause); the engagement
            // physics rules (task 163) need the same parity so
            // `agents.engaged_with(x) != None` compiles. Only the RHS-
            // `None` form is detected; a swapped source would need a
            // parser normalisation pass, which is out of scope here.
            if matches!(op, BinOp::Eq | BinOp::NotEq) {
                if let IrExpr::EnumVariant { ty, variant } = &rhs.kind {
                    if ty.is_empty() && variant == "None" {
                        let l = lower_expr(lhs)?;
                        let method = if matches!(op, BinOp::Eq) { "is_none" } else { "is_some" };
                        return Ok(format!("({l}).{method}()"));
                    }
                }
            }
            let l = lower_expr(lhs)?;
            let r = lower_expr(rhs)?;
            Ok(format!("({l} {} {r})", binop_str(*op)))
        }
        IrExpr::Unary(op, rhs) => {
            let r = lower_expr(rhs)?;
            Ok(format!("({}{r})", unop_str(*op)))
        }
        IrExpr::BuiltinCall(b, args) => lower_builtin_call(*b, args),
        IrExpr::If { cond, then_expr, else_expr } => {
            let c = lower_expr(cond)?;
            let t = lower_expr(then_expr)?;
            let e = match else_expr {
                Some(e) => lower_expr(e)?,
                None => return Err(EmitError::Unsupported("`if` expression without else".into())),
            };
            Ok(format!("(if {c} {{ {t} }} else {{ {e} }})"))
        }
        IrExpr::Field { base, field_name, .. } => {
            let b = lower_expr(base)?;
            Ok(format!("{b}.{field_name}"))
        }
        IrExpr::EnumVariant { ty, variant } => {
            // Route engine stdlib sum types (`EffectOp`, `TargetSelector`)
            // through `qualified_variant_name` so the emitted path carries
            // the `crate::ability::...` prefix. Other enums keep their
            // source-level `Ty::Variant` form (matches DSL-declared enums
            // re-exported at the `engine_rules::enums` top level).
            if ty.is_empty() {
                Ok(qualified_variant_name(variant))
            } else if ty == "TargetSelector" || ty == "EffectOp" {
                Ok(qualified_variant_name(variant))
            } else {
                Ok(format!("{ty}::{variant}"))
            }
        }
        other => Err(EmitError::Unsupported(format!(
            "expression shape {other:?} not supported in physics emission"
        ))),
    }
}

fn lower_namespace_field(ns: NamespaceId, field: &str) -> Result<String, EmitError> {
    if ns == NamespaceId::Config {
        if field.contains('.') {
            return Ok(format!("state.config.{field}"));
        }
        return Err(EmitError::Unsupported(format!(
            "bare `config.{field}` is not a value; address a specific field"
        )));
    }
    if ns == NamespaceId::World {
        if field == "tick" {
            return Ok("state.tick".into());
        }
    }
    if ns == NamespaceId::Cascade && field == "max_iterations" {
        // Compile-time constant — the cascade framework's per-tick
        // iteration ceiling. Used by the `cast` rule to bound
        // `CastAbility` recursion without a hand-written handler. Cast to
        // `u8` so comparisons against the event's `depth: u8` don't need an
        // explicit widening in DSL source (the literal `8` would default to
        // `i32`, forcing a cast; the generated `as u8` keeps the arithmetic
        // tidy).
        return Ok("(crate::cascade::MAX_CASCADE_ITERATIONS as u8)".into());
    }
    Err(EmitError::Unsupported(format!(
        "namespace-field `{}.{field}` not supported",
        ns.name()
    )))
}

fn lower_namespace_call(
    ns: NamespaceId,
    method: &str,
    args: &[crate::ir::IrCallArg],
) -> Result<String, EmitError> {
    let lowered: Vec<String> = args
        .iter()
        .map(|a| {
            if a.name.is_some() {
                return Err(EmitError::Unsupported(format!(
                    "named argument on stdlib call `{}.{method}` not supported",
                    ns.name()
                )));
            }
            lower_expr(&a.value)
        })
        .collect::<Result<_, _>>()?;
    match (ns, method) {
        (NamespaceId::Agents, "alive") => {
            expect_arity(args, 1, "agents.alive")?;
            Ok(format!("state.agent_alive({})", lowered[0]))
        }
        (NamespaceId::Agents, "hp") => {
            expect_arity(args, 1, "agents.hp")?;
            Ok(format!("state.agent_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "shield_hp") => {
            expect_arity(args, 1, "agents.shield_hp")?;
            Ok(format!("state.agent_shield_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_hp") => {
            expect_arity(args, 2, "agents.set_hp")?;
            Ok(format!("state.set_agent_hp({}, {})", lowered[0], lowered[1]))
        }
        (NamespaceId::Agents, "set_shield_hp") => {
            expect_arity(args, 2, "agents.set_shield_hp")?;
            Ok(format!("state.set_agent_shield_hp({}, {})", lowered[0], lowered[1]))
        }
        (NamespaceId::Agents, "kill") => {
            expect_arity(args, 1, "agents.kill")?;
            Ok(format!("state.kill_agent({})", lowered[0]))
        }
        (NamespaceId::Agents, "max_hp") => {
            expect_arity(args, 1, "agents.max_hp")?;
            Ok(format!("state.agent_max_hp({}).unwrap_or(0.0)", lowered[0]))
        }
        (NamespaceId::Agents, "attack_damage") => {
            expect_arity(args, 1, "agents.attack_damage")?;
            Ok(format!(
                "state.agent_attack_damage({}).unwrap_or(state.config.combat.attack_damage)",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "stun_expires_at_tick") => {
            expect_arity(args, 1, "agents.stun_expires_at_tick")?;
            Ok(format!("state.agent_stun_expires_at({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_stun_expires_at_tick") => {
            expect_arity(args, 2, "agents.set_stun_expires_at_tick")?;
            Ok(format!(
                "state.set_agent_stun_expires_at({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "slow_expires_at_tick") => {
            expect_arity(args, 1, "agents.slow_expires_at_tick")?;
            Ok(format!("state.agent_slow_expires_at({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_slow_expires_at_tick") => {
            expect_arity(args, 2, "agents.set_slow_expires_at_tick")?;
            Ok(format!(
                "state.set_agent_slow_expires_at({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "slow_factor_q8") => {
            expect_arity(args, 1, "agents.slow_factor_q8")?;
            Ok(format!("state.agent_slow_factor_q8({}).unwrap_or(0)", lowered[0]))
        }
        (NamespaceId::Agents, "set_slow_factor_q8") => {
            expect_arity(args, 2, "agents.set_slow_factor_q8")?;
            Ok(format!(
                "state.set_agent_slow_factor_q8({}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "gold") => {
            expect_arity(args, 1, "agents.gold")?;
            Ok(format!(
                "state.agent_inventory({}).map(|i| i.gold).unwrap_or(0)",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "set_gold") => {
            expect_arity(args, 2, "agents.set_gold")?;
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = {v}; state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "add_gold") => {
            expect_arity(args, 2, "agents.add_gold")?;
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = __inv.gold.wrapping_add({v}); state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "sub_gold") => {
            expect_arity(args, 2, "agents.sub_gold")?;
            Ok(format!(
                "if let Some(mut __inv) = state.agent_inventory({a}) {{ __inv.gold = __inv.gold.wrapping_sub({v}); state.set_agent_inventory({a}, __inv); }}",
                a = lowered[0],
                v = lowered[1]
            ))
        }
        (NamespaceId::Agents, "adjust_standing") => {
            expect_arity(args, 3, "agents.adjust_standing")?;
            // Task 3.2: route directly to the @materialized `standing` view.
            // The DSL `delta` is typed i16 at callsites (EffectStandingDelta);
            // widen to the view's i32 storage. `state.tick` is in scope
            // inside every generated physics handler. `views` is the
            // ViewRegistry param added to rules that mutate views.
            Ok(format!(
                "views.standing.adjust({}, {}, {} as i32, state.tick)",
                lowered[0], lowered[1], lowered[2]
            ))
        }
        (NamespaceId::Agents, "cooldown_next_ready") => {
            expect_arity(args, 1, "agents.cooldown_next_ready")?;
            Ok(format!(
                "state.agent_cooldown_next_ready({}).unwrap_or(0)",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "set_cooldown_next_ready") => {
            expect_arity(args, 2, "agents.set_cooldown_next_ready")?;
            Ok(format!(
                "state.set_agent_cooldown_next_ready({}, {})",
                lowered[0], lowered[1]
            ))
        }
        // 2026-04-22 ability-cooldowns subsystem — dual-cursor post-cast
        // write. Args: `(caster, ability, now)`. Writes both the per-agent
        // global cursor (`hot_cooldown_next_ready_tick`) and the
        // per-(agent, slot) local cursor (`ability_cooldowns`). See
        // `SimState::record_cast_cooldowns` for the semantics.
        (NamespaceId::Agents, "record_cast_cooldowns") => {
            expect_arity(args, 3, "agents.record_cast_cooldowns")?;
            Ok(format!(
                "state.record_cast_cooldowns({}, {}, {})",
                lowered[0], lowered[1], lowered[2]
            ))
        }
        // Engagement accessors (task 163). The DSL `engagement_on_move` /
        // `engagement_on_death` physics rules call these to eagerly write
        // the SoA `hot_engaged_with` slot. `clear_engaged_with` writes
        // `None`; `set_engaged_with(a, b)` writes `Some(b)`. The split
        // avoids needing an `Option` ctor in the DSL source.
        (NamespaceId::Agents, "engaged_with") => {
            expect_arity(args, 1, "agents.engaged_with")?;
            Ok(format!("state.agent_engaged_with({})", lowered[0]))
        }
        (NamespaceId::Agents, "engaged_with_or") => {
            // Unwrap-or-default for `state.agent_engaged_with(id)`. Lets
            // the physics rule sentinel on the agent itself when no
            // partner is set, avoiding an `if let Some(...)` narrowing
            // that the GPU-emittable subset doesn't yet support.
            expect_arity(args, 2, "agents.engaged_with_or")?;
            Ok(format!(
                "state.agent_engaged_with({}).unwrap_or({})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "set_engaged_with") => {
            expect_arity(args, 2, "agents.set_engaged_with")?;
            Ok(format!(
                "state.set_agent_engaged_with({}, Some({}))",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Agents, "clear_engaged_with") => {
            expect_arity(args, 1, "agents.clear_engaged_with")?;
            Ok(format!(
                "state.set_agent_engaged_with({}, None)",
                lowered[0]
            ))
        }
        // Spatial queries — nearest hostile (task 163). Wraps
        // `SpatialHash::within_radius` + the `CreatureType::is_hostile_to`
        // predicate with an argmin loop; ties broken on raw `AgentId`.
        // `nearest_hostile_to` returns `Option<AgentId>`; the `_or`
        // sibling returns the supplied default when nothing matches so
        // the rule body can stay in the scalar subset (no `if let`
        // narrowing required).
        (NamespaceId::Query, "nearest_hostile_to") => {
            expect_arity(args, 2, "query.nearest_hostile_to")?;
            Ok(format!(
                "crate::spatial::nearest_hostile_to(state, {}, {})",
                lowered[0], lowered[1]
            ))
        }
        (NamespaceId::Query, "nearest_hostile_to_or") => {
            expect_arity(args, 3, "query.nearest_hostile_to_or")?;
            Ok(format!(
                "crate::spatial::nearest_hostile_to(state, {}, {}).unwrap_or({})",
                lowered[0], lowered[1], lowered[2]
            ))
        }
        // Same-species scan — yields a `Vec<AgentId>` the physics body can
        // `for`-iterate. Bounded by the cell-reach cap inside
        // `SpatialHash::within_radius`. Task 167.
        (NamespaceId::Query, "nearby_kin") => {
            expect_arity(args, 2, "query.nearby_kin")?;
            Ok(format!(
                "crate::spatial::nearby_kin(state, {}, {})",
                lowered[0], lowered[1]
            ))
        }
        // `abilities.*` — ability registry accessors. `is_known` gates the
        // cast handler on an unknown id; `cooldown_ticks` reads the
        // program's gate; `effects` yields the program's `EffectOp` smallvec
        // as a `for`-loop iterable. The `cast` physics rule is the only
        // caller in-tree; see `assets/sim/physics.sim`.
        (NamespaceId::Abilities, "is_known") => {
            expect_arity(args, 1, "abilities.is_known")?;
            Ok(format!("state.ability_registry.get({}).is_some()", lowered[0]))
        }
        (NamespaceId::Abilities, "cooldown_ticks") => {
            expect_arity(args, 1, "abilities.cooldown_ticks")?;
            Ok(format!(
                "state.ability_registry.get({}).map(|p| p.gate.cooldown_ticks).unwrap_or(0)",
                lowered[0]
            ))
        }
        // `ability::on_cooldown(slot)` — inverted, designer-facing form
        // of `abilities.cooldown_ready`. Returns `true` when the
        // (self, slot) pair is still on cooldown. The implicit subject
        // is the rule's `self` local; the slot arg is coerced to `u8`.
        // Added 2026-04-22 (ability-cooldowns subsystem, Task 7).
        (NamespaceId::Abilities, "on_cooldown") => {
            expect_arity(args, 1, "ability.on_cooldown")?;
            Ok(format!(
                "(!state.can_cast_ability(self, ({}) as u8, state.tick as u32))",
                lowered[0]
            ))
        }
        (NamespaceId::Abilities, "effects") => {
            expect_arity(args, 1, "abilities.effects")?;
            // Yields owned `EffectOp` values so the `for`-loop body doesn't
            // re-borrow `state.ability_registry` (every ability accessor on
            // `SimState` is &self). `EffectOp: Copy`, so collecting into an
            // owned `SmallVec` is cheap (fits on the stack at the fixed
            // `MAX_EFFECTS_PER_PROGRAM` cap). Unknown ids produce an empty
            // smallvec so the for-loop short-circuits cleanly.
            Ok(format!(
                "{{ \
                 let __effects: smallvec::SmallVec<[crate::ability::EffectOp; crate::ability::MAX_EFFECTS_PER_PROGRAM]> = \
                 state.ability_registry.get({}).map(|p| p.effects.iter().copied().collect()).unwrap_or_default(); \
                 __effects \
                 }}",
                lowered[0]
            ))
        }
        (NamespaceId::Agents, "record_memory") => {
            // Route directly to the @materialized `memory` view.
            // Args: (observer, source, fact_payload, confidence, tick).
            // Lowers to constructing a MemoryEntry and pushing it into
            // `views.memory`. The `views` param is added to the emitted
            // function signature when this stdlib call is present.
            expect_arity(args, 5, "agents.record_memory")?;
            Ok(format!(
                "{{ \
                 let entry = MemoryEntry {{ source: {source}.raw(), value: {confidence}, anchor_tick: {tick}, }}; \
                 views.memory.push({observer}.raw(), entry); \
                 }}",
                observer   = lowered[0],
                source     = lowered[1],
                confidence = lowered[3],
                tick       = lowered[4],
            ))
        }
        // ----------------------------------------------------------------
        // Roadmap §1 — Memberships (grammar stub). Parser + resolver accept
        // these; the physics emitter refuses to lower them because the
        // per-agent `cold_memberships: SmallVec<[Membership; 4]>` runtime
        // state doesn't exist yet. Subsystem §1 implementation will
        // replace each `Unsupported` arm below with a real lowering.
        // See `docs/superpowers/roadmap.md:161-211`.
        // ----------------------------------------------------------------
        (NamespaceId::Membership, "is_group_member")
        | (NamespaceId::Membership, "is_group_leader")
        | (NamespaceId::Membership, "can_join_group")
        | (NamespaceId::Membership, "is_outcast") => Err(EmitError::Unsupported(format!(
            "memberships primitive `membership::{method}` pending runtime impl"
        ))),
        // ----------------------------------------------------------------
        // Roadmap §3 — Relationships (grammar stub). The per-agent
        // `cold_relationships: SmallVec<[Relationship; 8]>` slab doesn't
        // exist yet; Subsystem §3 implementation replaces each arm with
        // a real lowering. See `docs/superpowers/roadmap.md:279-311`.
        // ----------------------------------------------------------------
        (NamespaceId::Relationship, "is_hostile")
        | (NamespaceId::Relationship, "is_friendly")
        | (NamespaceId::Relationship, "knows_well") => Err(EmitError::Unsupported(format!(
            "relationships primitive `relationship::{method}` pending runtime impl"
        ))),
        // ----------------------------------------------------------------
        // Roadmap §6 — Theory-of-mind (grammar stub). Needs the
        // `Relationship.believed_knowledge: Bitset<32>` slot + the
        // DomainId / FactId enums; none of those exist yet. Subsystem §6
        // implementation lowers each arm to a bit-read against the
        // observer's relationship slot. See
        // `docs/superpowers/roadmap.md:447-506`.
        // ----------------------------------------------------------------
        (NamespaceId::TheoryOfMind, "believes_knows")
        | (NamespaceId::TheoryOfMind, "can_deceive")
        | (NamespaceId::TheoryOfMind, "is_surprised_by") => Err(EmitError::Unsupported(format!(
            "theory_of_mind primitive `theory_of_mind::{method}` pending runtime impl"
        ))),
        // ----------------------------------------------------------------
        // Roadmap §7 — Groups (grammar stub). Plan 1 T16 shipped the
        // `AggregatePool<Group>` Pod shape; instance data (members,
        // leader_id, treasury, etc.) lands with Subsystem §7. Until then
        // the emitter refuses to lower these predicates.
        // See `docs/superpowers/roadmap.md:510-574`.
        // ----------------------------------------------------------------
        (NamespaceId::Group, "exists")
        | (NamespaceId::Group, "is_active")
        | (NamespaceId::Group, "has_leader")
        | (NamespaceId::Group, "can_afford_from_treasury") => Err(EmitError::Unsupported(format!(
            "groups primitive `group::{method}` pending runtime impl"
        ))),
        // ----------------------------------------------------------------
        // Roadmap §12 — Quests (grammar stub). Plan 1 T16 shipped the
        // `AggregatePool<Quest>` Pod shape; instance data (party_member_ids,
        // destination, progress, status, ...) lands with Subsystem §12.
        // Until then the emitter refuses to lower these predicates.
        // See `docs/superpowers/roadmap.md:811-872`.
        // ----------------------------------------------------------------
        (NamespaceId::Quest, "can_accept")
        | (NamespaceId::Quest, "is_target")
        | (NamespaceId::Quest, "party_near_destination") => Err(EmitError::Unsupported(format!(
            "quests primitive `quest::{method}` pending runtime impl"
        ))),
        _ => Err(EmitError::Unsupported(format!(
            "stdlib call `{}.{method}` not supported in physics emission",
            ns.name()
        ))),
    }
}

fn lower_builtin_call(b: Builtin, args: &[crate::ir::IrCallArg]) -> Result<String, EmitError> {
    let lowered: Vec<String> = args
        .iter()
        .map(|a| {
            if a.name.is_some() {
                return Err(EmitError::Unsupported(format!(
                    "named argument on builtin `{}` not supported",
                    b.name()
                )));
            }
            lower_expr(&a.value)
        })
        .collect::<Result<_, _>>()?;
    match b {
        Builtin::Min => {
            expect_arity(args, 2, "min")?;
            Ok(format!("({}).min({})", lowered[0], lowered[1]))
        }
        Builtin::Max => {
            expect_arity(args, 2, "max")?;
            Ok(format!("({}).max({})", lowered[0], lowered[1]))
        }
        Builtin::Clamp => {
            expect_arity(args, 3, "clamp")?;
            Ok(format!(
                "({}).clamp({}, {})",
                lowered[0], lowered[1], lowered[2]
            ))
        }
        Builtin::Abs => {
            expect_arity(args, 1, "abs")?;
            Ok(format!("({}).abs()", lowered[0]))
        }
        Builtin::Floor => {
            expect_arity(args, 1, "floor")?;
            Ok(format!("({}).floor()", lowered[0]))
        }
        Builtin::Ceil => {
            expect_arity(args, 1, "ceil")?;
            Ok(format!("({}).ceil()", lowered[0]))
        }
        Builtin::Round => {
            expect_arity(args, 1, "round")?;
            Ok(format!("({}).round()", lowered[0]))
        }
        Builtin::Sqrt => {
            expect_arity(args, 1, "sqrt")?;
            Ok(format!("({}).sqrt()", lowered[0]))
        }
        Builtin::SaturatingAdd => {
            expect_arity(args, 2, "saturating_add")?;
            Ok(format!("({}).saturating_add({})", lowered[0], lowered[1]))
        }
        _ => Err(EmitError::Unsupported(format!(
            "builtin `{}` not supported in physics emission",
            b.name()
        ))),
    }
}

fn expect_arity(
    args: &[crate::ir::IrCallArg],
    expected: usize,
    name: &str,
) -> Result<(), EmitError> {
    if args.len() == expected {
        Ok(())
    } else {
        Err(EmitError::Unsupported(format!(
            "`{name}` expects {expected} arg(s), got {}",
            args.len()
        )))
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
    }
}

fn unop_str(op: UnOp) -> &'static str {
    match op {
        UnOp::Not => "!",
        UnOp::Neg => "-",
    }
}

fn render_float(v: f64) -> String {
    let s = format!("{v}");
    if s.contains('.') || s.contains('e') || s.contains('E') || s == "inf" || s == "-inf" || s == "NaN"
    {
        s
    } else {
        format!("{s}.0")
    }
}

// ---------------------------------------------------------------------------
// Utility: synthesize the implicit `tick: u32` on event fields
// ---------------------------------------------------------------------------

fn fields_with_implicit_tick(event: &EventIR) -> Vec<EventField> {
    let mut out = event.fields.clone();
    if !out.iter().any(|f| f.name == "tick") {
        out.push(EventField {
            name: "tick".into(),
            ty: IrType::U32,
            span: crate::ast::Span::dummy(),
        });
    }
    out
}

// ---------------------------------------------------------------------------
// Type rendering (handler argument signatures)
// ---------------------------------------------------------------------------

fn render_type(ty: &IrType) -> String {
    match ty {
        IrType::Bool => "bool".into(),
        IrType::I8 => "i8".into(),
        IrType::U8 => "u8".into(),
        IrType::I16 => "i16".into(),
        IrType::U16 => "u16".into(),
        IrType::I32 => "i32".into(),
        IrType::U32 => "u32".into(),
        IrType::I64 => "i64".into(),
        IrType::U64 => "u64".into(),
        IrType::F32 => "f32".into(),
        IrType::F64 => "f64".into(),
        IrType::Vec3 => "Vec3".into(),
        IrType::String => "String".into(),
        IrType::AgentId => "AgentId".into(),
        IrType::ItemId => "ItemId".into(),
        IrType::GroupId => "GroupId".into(),
        IrType::QuestId => "QuestId".into(),
        IrType::AuctionId => "AuctionId".into(),
        IrType::EventId => "EventId".into(),
        IrType::AbilityId => "AbilityId".into(),
        IrType::Optional(inner) => format!("Option<{}>", render_type(inner)),
        IrType::Array(inner, cap) => format!("[{}; {}]", render_type(inner), cap),
        IrType::Tuple(items) => {
            let parts: Vec<String> = items.iter().map(render_type).collect();
            format!("({})", parts.join(", "))
        }
        IrType::Named(n) => n.clone(),
        IrType::Enum { name, .. } => name.clone(),
        IrType::Unknown => "()".into(),
        other => format!("/* unsupported type {other:?} */"),
    }
}

// ---------------------------------------------------------------------------
// Naming utilities
// ---------------------------------------------------------------------------

/// Handler fn name: the same snake_case as the physics rule name. The
/// emitter no longer emits an `impl CascadeHandler` — the dispatcher calls
/// this fn directly.
fn handler_fn_name(rule: &str) -> String {
    snake_case(rule)
}

#[allow(dead_code)]
fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '_' || ch == '-' {
            upper_next = true;
        } else if upper_next {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_upper = false;
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && !prev_upper {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
            prev_upper = true;
        } else {
            out.push(ch);
            prev_upper = false;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Span;
    use crate::ir::{
        EventField, EventIR, EventRef, IrCallArg, IrEmit, IrEventPattern, IrExpr, IrExprNode,
        IrFieldInit, IrPattern, IrPatternBinding, IrStmt, LocalRef, NamespaceId, PhysicsHandlerIR,
        PhysicsIR,
    };

    fn span() -> Span {
        Span::dummy()
    }

    fn local(name: &str, id: u16) -> IrExprNode {
        IrExprNode { kind: IrExpr::Local(LocalRef(id), name.to_string()), span: span() }
    }

    fn pattern_bind(field: &str, name: &str, id: u16) -> IrPatternBinding {
        IrPatternBinding {
            field: field.to_string(),
            value: IrPattern::Bind { name: name.to_string(), local: LocalRef(id) },
            span: span(),
        }
    }

    fn ns_call(ns: NamespaceId, method: &str, args: Vec<IrExprNode>) -> IrExprNode {
        IrExprNode {
            kind: IrExpr::NamespaceCall {
                ns,
                method: method.to_string(),
                args: args
                    .into_iter()
                    .map(|a| IrCallArg { name: None, value: a, span: span() })
                    .collect(),
            },
            span: span(),
        }
    }

    fn sample_event() -> EventIR {
        EventIR {
            name: "EffectDamageApplied".into(),
            fields: vec![
                EventField { name: "caster".into(), ty: IrType::AgentId, span: span() },
                EventField { name: "target".into(), ty: IrType::AgentId, span: span() },
                EventField { name: "amount".into(), ty: IrType::F32, span: span() },
            ],
            tags: vec![],
            annotations: vec![],
            span: span(),
        }
    }

    fn make_minimal_handler() -> PhysicsIR {
        let pattern = IrPhysicsPattern::Kind(IrEventPattern {
            name: "EffectDamageApplied".into(),
            event: Some(EventRef(0)),
            bindings: vec![
                pattern_bind("target", "t", 0),
                pattern_bind("amount", "a", 1),
            ],
            span: span(),
        });
        let body = vec![IrStmt::Expr(ns_call(
            NamespaceId::Agents,
            "set_hp",
            vec![local("t", 0), ns_call(NamespaceId::Agents, "hp", vec![local("t", 0)])],
        ))];
        PhysicsIR {
            name: "noop".into(),
            handlers: vec![PhysicsHandlerIR { pattern, where_clause: None, body, span: span() }],
            annotations: vec![],
            cpu_only: false,
            span: span(),
        }
    }

    #[test]
    fn handler_fn_signature_and_body() {
        let p = make_minimal_handler();
        let ev = sample_event();
        let ctx = EmitContext { events: std::slice::from_ref(&ev), event_tags: &[] };
        let out = emit_physics(&p, Some("assets/sim/physics.sim"), &ctx).unwrap();
        assert!(out.contains("// GENERATED by dsl_compiler from assets/sim/physics.sim."));
        assert!(out.contains("pub fn noop(t: AgentId, a: f32, state: &mut SimState, events: &mut EventRing<Event>)"));
        assert!(out.contains("state.set_agent_hp(t, state.agent_hp(t).unwrap_or(0.0));"));
    }

    #[test]
    fn dispatcher_destructures_and_calls() {
        let p = make_minimal_handler();
        let ev = sample_event();
        let ctx = EmitContext { events: std::slice::from_ref(&ev), event_tags: &[] };
        let out = emit_physics_mod(std::slice::from_ref(&p), &ctx);
        assert!(out.contains("pub fn dispatch_effect_damage_applied(event: &Event, state: &mut SimState, views: &mut ViewRegistry, events: &mut EventRing<Event>)"));
        assert!(out.contains("let Event::EffectDamageApplied { caster, target, amount, tick }"));
        assert!(out.contains("noop::noop(target, amount, state, events);"));
        assert!(out.contains("registry.install_kind(EventKindId::EffectDamageApplied, dispatch_effect_damage_applied);"));
    }

    #[test]
    fn emit_appends_implicit_tick() {
        let p = PhysicsIR {
            name: "emitter".into(),
            handlers: vec![PhysicsHandlerIR {
                pattern: IrPhysicsPattern::Kind(IrEventPattern {
                    name: "EffectDamageApplied".into(),
                    event: Some(EventRef(0)),
                    bindings: vec![pattern_bind("target", "t", 0)],
                    span: span(),
                }),
                where_clause: None,
                body: vec![IrStmt::Emit(IrEmit {
                    event_name: "AgentDied".into(),
                    event: Some(EventRef(1)),
                    fields: vec![IrFieldInit {
                        name: "agent_id".into(),
                        value: local("t", 0),
                        span: span(),
                    }],
                    span: span(),
                })],
                span: span(),
            }],
            annotations: vec![],
            cpu_only: false,
            span: span(),
        };
        let ev = sample_event();
        let ctx = EmitContext { events: std::slice::from_ref(&ev), event_tags: &[] };
        let out = emit_physics(&p, None, &ctx).unwrap();
        assert!(out.contains("events.push(Event::AgentDied { agent_id: t, tick: state.tick });"));
    }

    // ---------------------------------------------------------------------
    // For / Match lowering — pinned by the `cast` physics rule. These
    // exercises use hand-built IR (no parser) so the test focus stays on
    // the emitter; the parser + resolver path is covered by the full
    // `compile-dsl` integration test.
    // ---------------------------------------------------------------------

    use crate::ir::IrStmtMatchArm;

    fn ns_call_args(ns: NamespaceId, method: &str, args: Vec<IrExprNode>) -> IrExprNode {
        ns_call(ns, method, args)
    }

    #[test]
    fn for_loop_over_abilities_effects_lowers_to_rust_for() {
        // Minimal handler: `on AgentCast { actor: caster, ability: ab } {
        //   for op in abilities.effects(ab) { emit AgentDied { agent_id: caster } }
        // }`. The body has no semantic meaning — we just assert the for-loop
        // renders with the right iter expression.
        let ev = EventIR {
            name: "AgentCast".into(),
            fields: vec![
                EventField { name: "actor".into(), ty: IrType::AgentId, span: span() },
                EventField { name: "ability".into(), ty: IrType::AbilityId, span: span() },
            ],
            tags: vec![],
            annotations: vec![],
            span: span(),
        };
        let died_ev = EventIR {
            name: "AgentDied".into(),
            fields: vec![
                EventField { name: "agent_id".into(), ty: IrType::AgentId, span: span() },
            ],
            tags: vec![],
            annotations: vec![],
            span: span(),
        };
        let pattern = IrPhysicsPattern::Kind(IrEventPattern {
            name: "AgentCast".into(),
            event: Some(EventRef(0)),
            bindings: vec![
                pattern_bind("actor", "caster", 0),
                pattern_bind("ability", "ab", 1),
            ],
            span: span(),
        });
        let body = vec![IrStmt::For {
            binder: LocalRef(2),
            binder_name: "op".into(),
            iter: ns_call_args(NamespaceId::Abilities, "effects", vec![local("ab", 1)]),
            filter: None,
            body: vec![IrStmt::Emit(IrEmit {
                event_name: "AgentDied".into(),
                event: Some(EventRef(1)),
                fields: vec![IrFieldInit {
                    name: "agent_id".into(),
                    value: local("caster", 0),
                    span: span(),
                }],
                span: span(),
            })],
            span: span(),
        }];
        let p = PhysicsIR {
            name: "for_test".into(),
            handlers: vec![PhysicsHandlerIR { pattern, where_clause: None, body, span: span() }],
            annotations: vec![],
            cpu_only: false,
            span: span(),
        };
        let ctx = EmitContext { events: &[ev, died_ev], event_tags: &[] };
        let out = emit_physics(&p, None, &ctx).unwrap();
        assert!(
            out.contains("for op in"),
            "expected `for op in ...` loop in emitted body, got:\n{out}"
        );
        assert!(
            out.contains("state.ability_registry.get(ab)"),
            "expected abilities.effects lowering to ability_registry.get, got:\n{out}"
        );
    }

    #[test]
    fn match_over_struct_variant_lowers_to_rust_match() {
        // `match op { Damage { amount } => { emit AgentDied { agent_id: caster } } }`
        let ev = EventIR {
            name: "AgentCast".into(),
            fields: vec![
                EventField { name: "actor".into(), ty: IrType::AgentId, span: span() },
            ],
            tags: vec![],
            annotations: vec![],
            span: span(),
        };
        let died_ev = EventIR {
            name: "AgentDied".into(),
            fields: vec![
                EventField { name: "agent_id".into(), ty: IrType::AgentId, span: span() },
            ],
            tags: vec![],
            annotations: vec![],
            span: span(),
        };
        let pattern = IrPhysicsPattern::Kind(IrEventPattern {
            name: "AgentCast".into(),
            event: Some(EventRef(0)),
            bindings: vec![pattern_bind("actor", "caster", 0)],
            span: span(),
        });
        let match_stmt = IrStmt::Match {
            scrutinee: local("op", 1),
            arms: vec![IrStmtMatchArm {
                pattern: IrPattern::Struct {
                    name: "Damage".into(),
                    ctor: None,
                    bindings: vec![IrPatternBinding {
                        field: "amount".into(),
                        value: IrPattern::Bind {
                            name: "amount".into(),
                            local: LocalRef(2),
                        },
                        span: span(),
                    }],
                },
                body: vec![IrStmt::Emit(IrEmit {
                    event_name: "AgentDied".into(),
                    event: Some(EventRef(1)),
                    fields: vec![IrFieldInit {
                        name: "agent_id".into(),
                        value: local("caster", 0),
                        span: span(),
                    }],
                    span: span(),
                })],
                span: span(),
            }],
            span: span(),
        };
        let p = PhysicsIR {
            name: "match_test".into(),
            handlers: vec![PhysicsHandlerIR {
                pattern,
                where_clause: None,
                body: vec![match_stmt],
                span: span(),
            }],
            annotations: vec![],
            cpu_only: false,
            span: span(),
        };
        let ctx = EmitContext { events: &[ev, died_ev], event_tags: &[] };
        let out = emit_physics(&p, None, &ctx).unwrap();
        assert!(
            out.contains("match op"),
            "expected `match op` in emitted body, got:\n{out}"
        );
        assert!(
            out.contains("crate::ability::EffectOp::Damage { amount }"),
            "expected qualified EffectOp::Damage struct pattern, got:\n{out}"
        );
    }

    // -------------------------------------------------------------------------
    // T5: BeliefObserve lowering
    // -------------------------------------------------------------------------

    #[test]
    fn belief_observe_lowers_to_bounded_map_upsert() {
        // `beliefs(observer).observe(target) with { confidence: amount }` should
        // lower to:
        //   if let Some(__beliefs) = state.agent_cold_beliefs_mut(observer) {
        //       __beliefs.upsert(target, engine_data::belief::BeliefState { confidence: amount, ..Default::default() });
        //   }
        let ev = EventIR {
            name: "EffectDamageApplied".into(),
            fields: vec![
                EventField { name: "caster".into(), ty: IrType::AgentId, span: span() },
                EventField { name: "target".into(), ty: IrType::AgentId, span: span() },
                EventField { name: "amount".into(), ty: IrType::F32, span: span() },
            ],
            tags: vec![],
            annotations: vec![],
            span: span(),
        };
        let pattern = IrPhysicsPattern::Kind(IrEventPattern {
            name: "EffectDamageApplied".into(),
            event: Some(EventRef(0)),
            bindings: vec![
                pattern_bind("caster", "observer", 0),
                pattern_bind("target", "tgt", 1),
                pattern_bind("amount", "amount", 2),
            ],
            span: span(),
        });
        let belief_stmt = IrStmt::BeliefObserve {
            observer: local("observer", 0),
            target: local("tgt", 1),
            fields: vec![IrFieldInit {
                name: "confidence".into(),
                value: local("amount", 2),
                span: span(),
            }],
            span: span(),
        };
        let p = PhysicsIR {
            name: "record_observe".into(),
            handlers: vec![PhysicsHandlerIR {
                pattern,
                where_clause: None,
                body: vec![belief_stmt],
                span: span(),
            }],
            annotations: vec![],
            cpu_only: false,
            span: span(),
        };
        let ctx = EmitContext { events: std::slice::from_ref(&ev), event_tags: &[] };
        let out = emit_physics(&p, None, &ctx).unwrap();
        assert!(
            out.contains("agent_cold_beliefs_mut(observer)"),
            "expected agent_cold_beliefs_mut call; got:\n{out}"
        );
        assert!(
            out.contains("__beliefs.upsert(tgt,"),
            "expected __beliefs.upsert call; got:\n{out}"
        );
        assert!(
            out.contains("engine_data::belief::BeliefState {"),
            "expected BeliefState struct literal; got:\n{out}"
        );
        assert!(
            out.contains("confidence: amount"),
            "expected confidence field init; got:\n{out}"
        );
        assert!(
            out.contains("..Default::default()"),
            "expected spread default for unspecified fields; got:\n{out}"
        );
    }
}
