// GENERATED by dsl_compiler from assets/sim/events.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use crate::ids::AgentId;
use glam::Vec3;

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct AgentPlacedVoxel {
    pub actor: AgentId,
    pub location: Vec3,
    pub mat_tag: u32,
    pub tick: u32,
}
