// GENERATED by dsl_compiler from assets/sim/events.sim.
// Was emitted from .sim source by xtask `compile-dsl` (retired Phase 7, 2026-05-02); now hand-maintained.
// Do not edit by hand.

use crate::ids::AgentId;

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct AnnounceEmitted {
    pub speaker: AgentId,
    pub audience_tag: u8,
    pub fact_payload: u64,
    pub tick: u32,
}
