// GENERATED by dsl_compiler from assets/sim/events.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use crate::ids::AgentId;

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct AnnounceEmitted {
    pub speaker: AgentId,
    pub audience_tag: u8,
    pub fact_payload: u64,
    pub tick: u32,
}
