// GENERATED by dsl_compiler from assets/sim/events.sim.
// Was emitted from .sim source by xtask `compile-dsl` (retired Phase 7, 2026-05-02); now hand-maintained.
// Do not edit by hand.

use crate::ids::AgentId;

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct EffectReflectApplied {
    pub actor: AgentId,
    pub target: AgentId,
    pub duration_ticks: u32,
    pub fraction_q8: i16,
    pub tick: u32,
}
