// GENERATED by dsl_compiler from assets/sim/events.sim.
// Was emitted from .sim source by xtask `compile-dsl` (retired Phase 7, 2026-05-02); now hand-maintained.
// Do not edit by hand.

use crate::ids::AgentId;

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct EffectGoldTransfer {
    pub from: AgentId,
    pub to: AgentId,
    pub amount: i32,
    pub tick: u32,
}
