// GENERATED by dsl_compiler from assets/sim/physics.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use crate::event::EventRing;
use engine_data::events::Event;
use crate::ids::AgentId;
use crate::state::SimState;

#[allow(unused_variables)]
pub fn chronicle_flee(a: AgentId, state: &mut SimState, events: &mut EventRing<Event>) {
    events.push(Event::ChronicleEntry {
        template_id: 7,
        agent: a,
        target: a,
        tick: state.tick,
    });
}
