// GENERATED by dsl_compiler from assets/sim/physics.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use crate::event::EventRing;
use crate::ids::AgentId;
use crate::state::SimState;
use engine_data::events::Event;

#[allow(unused_variables)]
pub fn engagement_on_move(mover: AgentId, state: &mut SimState, events: &mut EventRing<Event>) {
    if state.agent_alive(mover) {
        let new =
            crate::spatial::nearest_hostile_to(state, mover, state.config.combat.engagement_range)
                .unwrap_or(mover);
        let old = state.agent_engaged_with(mover).unwrap_or(mover);
        if (old != new) {
            if (old != mover) {
                state.set_agent_engaged_with(mover, None);
                state.set_agent_engaged_with(old, None);
                let reason = (if (new == mover) { 1 } else { 0 });
                events.push(Event::EngagementBroken {
                    actor: mover,
                    former_target: old,
                    reason,
                    tick: state.tick,
                });
            }
            if (new != mover) {
                let stranded = state.agent_engaged_with(new).unwrap_or(new);
                if (stranded != new) {
                    if (stranded != mover) {
                        state.set_agent_engaged_with(new, None);
                        state.set_agent_engaged_with(stranded, None);
                        events.push(Event::EngagementBroken {
                            actor: new,
                            former_target: stranded,
                            reason: 0,
                            tick: state.tick,
                        });
                    }
                }
                state.set_agent_engaged_with(mover, Some(new));
                state.set_agent_engaged_with(new, Some(mover));
                events.push(Event::EngagementCommitted {
                    actor: mover,
                    target: new,
                    tick: state.tick,
                });
            }
        }
    }
}
