// GENERATED by dsl_compiler from assets/sim/physics.sim.
// Edit the .sim source; rerun `cargo run --bin xtask -- compile-dsl`.
// Do not edit by hand.

use crate::event::EventRing;
use engine_data::events::Event;
use crate::ids::AgentId;
use crate::state::SimState;
use crate::views::ViewRegistry;

#[allow(unused_variables)]
pub fn modify_standing(
    a: AgentId,
    b: AgentId,
    delta: i16,
    state: &mut SimState,
    views: &mut ViewRegistry,
    events: &mut EventRing<Event>,
) {
    views.standing.adjust(a, b, delta as i32, state.tick);
}
